### ISSUE TITLE
help table in schema could use some clean up with certain characters

### ISSUE THREAD

**Issue by Jkat** [aces/Loris#1018]
For example, the entry with the text...

<pre>By clicking on “New Profile” under the Candidate Menu</pre>

shows up in mysql as...

<pre>By clicking on ?New Profile? under the Candidate Menu</pre>

due to the type of quotes being used.

**Comment by Jkat** [comment]
This may depend on the char encoding of the database.

Also other clean ups include things like "DCC-ID" vs "DCCID".

**Comment by stellarxo** [comment]
https://github.com/aces/Loris/pull/1786

**Comment by stellarxo** [comment]
https://github.com/aces/Loris/pull/2062/files
