### ISSUE TITLE
Loris-16.0.rc2 install problem on CentOS/6.7--database

### ISSUE THREAD

**Issue by steve-YEG** [aces/Loris#1891]
I have gotten to step 1.1 of the README.CentOS6.md  file in Loris-16.0.rc2.   I created a MySQL user called 'lorisadmin' and enabled all privileges for it, and created a database called "LORIS'.  I then connected to MySQL with LORIS as an argument and 0000-00-00-schema.sql as stdin.  That populated the database just fine--I can see what see to be the tables in that SQL dump:
+---------------------------------------+
| Tables_in_LORIS                       |
+---------------------------------------+
| CNV                                   |
| ExternalLinkTypes                     |
| ExternalLinks                         |
| GWAS                                  |
| MRICandidateErrors                    |
| Project                               |
| SNP                                   |
| SNP_candidate_rel                     |
| StatisticsTabs                        |
| Visit_Windows                         |
| acknowledgements                      |
| candidate                             |
| caveat_options                        |
| certification                         |
| certification_history                 |
| certification_training                |
| certification_training_quiz_answers   |
| certification_training_quiz_questions |
| conflicts_resolved                    |
| conflicts_unresolved                  |
| consent_info_history                  |
...
| users                                 |
| violations_resolved                   |
+---------------------------------------+
93 rows in set (0.00 sec)

The next step of the ReadMe file are to do three UPDATE commands to change/localize three items.  This does not work:
mysql> UPDATE Config SET Value='/var/www/als/' WHERE ConfigID=(SELECT ID FROM ConfigSettings WHERE Name='base');
ERROR 1146 (42S02): Table 'LORIS.Config' doesn't exist

I looked in the supplied schema and there is no table entry for "Config"   There is a ConfigID in the "0000-00-03-ConfigTables.sql" file.  Should it have been loaded instead of the schema.sql file, or in addition to it?  Should I also load the database with some or all of the other .sql files there?
Maybe I am hopelessly lost and following the wrong instructions.

Thank you,
     steve.

**Comment by driusan** [comment]
It sounds like those instructions are out of date. You need to source all the `0000-00-*.sql` files if you're manually populating the database schema. They used to be one big, monolithic file, but it was difficult to maintain so they were split up. Those instructions need to be updated.

Thanks for pointing this out!
