### ISSUE TITLE
Loris-16.0.rc2 install problem on CentOS/6.7--database

### ISSUE THREAD

**Issue by steve-YEG** [aces/Loris#1926]
**I sent this to Christine:**
One related question.  In the README.CentOS6.md right before section 1.2 Config XML it says:

    While connected to MySQL, you can also reset the admin password:

    ```SQL
    -- Reset password to YOURPASSWORD
    UPDATE users SET Password_md5=CONCAT('aa', MD5('aaYOURPASSWORD')) WHERE ID=1;
    ```
I am not sure what the word "reset" is referring to.  The instructions never said to change the MySQL lorisadmin , or did the populating of the data base change the password as a side effect?

**Here is her reply**:
Hi Steve, 
Thanks for your comment - you're right, it is a little unclear why that information is placed at that point in the CentOS Readme. The passwords input into the install script do not need to be changed in order to use Loris.  
We'll add some clarifying text, but in the meanwhile you can consider this as a helpful tip for future occasions on which a password reset via the mysql back-end is desired. 
 Note this instruction resets a front end (web login) user account password - lorisadmin (Unix) and Lorisuser (mysql) accounts are not affected.  User passwords can also be reset in the front end using the User Accounts module. 

**I was confused about part of this so I asked this question:**
Thank you.  I am not sure that I used an 'install script".  At the top of the "README.CentOS6.md" it says:

    "This document contains details on how to manually perform a basic CentOS 6.x install of LORIS without using the install script (as the install script makes some assumptions about apt-get being installed.)"

 I currently have these IDs

    lorisadmin what I am logged into and use to run MySql.  It has a different password when I login and when I start MySql with -p.
    lorisuser-a linux ID that I do not recall using
    MySql lorisuser which I do not recall using
    MySql lorisadmin see the first item in this list
    MySql root what I use when I run MySql -p from Linux ID root (or sudo).

I need this to know how to edit the copy of the config.xml in section 1.2 of the README.CentOS6.md instructions that I am trying to follow.
It seems like there is another MySql ID which is named "1" and the password will be 'aaYOURPASSWORD' if I "reset the password. If that is the case, then it is likely in the copy of config.xml  that I should replace the "%HOSTNAME%" with "localhost", "%USERNAME%", with "1", the "%PASSWORD%" with  "aaYOURPASSWORD",  and "%DATBASE%" with "LORIS" (the name that I choose for my database.) ?
I have no clue how I should fill in the "quatUSER", or "quatPASSWORD".
**end**

I had an idea while writing this, and looked at the Ubuntu install script and it does not have any "quat" objects, and it seems to use the mysqluser and password for the %USERNAME% and %PASSWORD%

I will try that out on Thursday.
      steve.

I think that lI have largely answered my own  question, but the README.CentOS6.md needs to be edited.

**Comment by christinerogers** [comment]
Thanks for your feedback!  We'll be clarifying the CentOS readme in these regards for the 16.1 release.
