### ISSUE TITLE
Image Uploader Readme not clear

### ISSUE THREAD

**Issue by dyt811** [aces/Loris#1981]
Currently following this [guide](https://github.com/aces/Loris/blob/16.1-dev/modules/imaging_uploader/README.md). It suggested to visit [ImageUploader readme](https://github.com/aces/Loris/blob/16.1-dev/modules/imaging_uploader/README.md) for configuration but so far, the only configuration I see mentioned are related to php.ini. Is there any instructions on configuring the path of the uploader? For some reason I am seeing files uploaded to /tmp/[random string].

**Comment by stellarxo** [comment]
It should be /data/incoming/ I believe. @MounaSafiHarab

**Comment by christinerogers** [comment]
This path can be set in the Configuration module  : section Paths, field: "MRI-Upload Directory".   Added a note to the [Wiki Imaging Setup page](https://github.com/aces/Loris/wiki/Imaging-Database#4-imaging-uploader) to clarify this.
