### ISSUE TITLE
Imaging script not working on Centos 6

### ISSUE THREAD

**Issue by um4r12** [aces/Loris#2030]
Hi, I am attempting to run the imaging_install.sh on Centos 6, however, Centos does not use apt-get. If you run the script with apt-get, you get an error: "apt-get: command not found", as expected. And when you change to script to ignore apt-get, and is replaced with yum instead, then you get an error: 'no package dcmtk [is] available'.  Any suggestions?

**Comment by christinerogers** [comment]
Hello -- We've added some detailed documentation for Imaging installation on CentOS here: 
https://github.com/aces/Loris/wiki/CentOS-Imaging-installation-transcript

Further feedback is most welcome.  Thanks!
