### ISSUE TITLE
 Loris-MRI/imaging_install.sh does the perl module part work?

### ISSUE THREAD

**Issue by steve-YEG** [aces/Loris#2036]
I am working on a LORIS 16 install on CentOS 6  and was trying to install the MRI-imaging module and this part of the [ imaging_install.sh](urhttps://github.com/aces/Loris-MRI/blob/16.1-dev/imaging_install.shl) script fails:(lines 74-87)
`
#################################################################################################
############################INSTALL THE PERL LIBRARIES###########################################
#################################################################################################
echo "Installing the perl libraries...THis will take a few minutes..."
#echo $rootpass | sudo perl -MCPAN -e shell
sudo -S cpan install Math::Round
#echo $rootpass | sudo -S cpan install Bundle::CPAN
sudo -S cpan install Getopt::Tabular
sudo -S cpan install Time::JulianDay
sudo -S cpan install Path::Class
sudo -S cpan install Archive::Extract
sudo -S cpan install Archive::Zip
echo`

Although I am using CentOS 6, I checked a Ubuntu 14.04.1 LTS  system and the cpan man page indicates that it would fail there also.  The Sudo's do not look right either.
 
Am I dreaming, or is there a problem here?
Thank you,
      steve.

**Comment by christinerogers** [comment]
Hi Steve,
We've recently added some detailed documentation for Imaging installation on CentOS here: 
https://github.com/aces/Loris/wiki/CentOS-Imaging-installation-transcript

Further feedback is most welcome. Thanks!
