### ISSUE TITLE
addMonthYear wrong order 

### ISSUE THREAD

**Issue by cyc115** [aces/Loris#2089]
current implementation of `addMonthYear` in NDB_BVL_Instrument.class.inc adds the field in the order or Year-Month instead of the advertised Month-Year.

see below : 

```

    function addMonthYear($field, $label, $options=array())
    {
        if (is_array($options)) {
            $options['format'] = 'YM';
        }
        $this->form->addElement('date', $field, $label, $options);
        $this->monthYearFields[] = $field;
    }

```

It also displays a default value as shown below
![selection_348](https://cloud.githubusercontent.com/assets/2107333/17497802/0a9993b6-5d9a-11e6-95a4-fdb64ddf6997.jpg)

**Comment by xlecours** [comment]
We have switch from QuickForm to LorisForm and the yearMonth fields are now date fields.
