### ISSUE TITLE
Unable to properly use prepared statements when using MySQL 'LIKE' keyword

### ISSUE THREAD

**Issue by Jkat** [aces/Loris#2177]
Write a function to bind parameters when issuing a MySQL statement that uses the 'LIKE' keyword with wildcard

eg. "SELECT 'X' FROM table WHERE column LIKE %parameter%"

**Comment by Jkat** [comment]
Priority of this is probably super low.

**Comment by Jkat** [comment]
Probably not worth the effort really.

**Comment by driusan** [comment]
You can use `SELECT 'x' FROM TABLE WHERE COLUMN LIKE CONCAT('%', parameter, '%')`
