### ISSUE TITLE
Could not instantiate feedback object

### ISSUE THREAD

**Issue by ncote** [aces/Loris#2576]
In release 17.0.0, on accessing a candidate's profile, the following error appears, and the candidate profile is not displayed:

```
Could not instantiate feedback object
```

This seems to be due to a change in behaviour in php 7.    In php/libraries/NDB_BVL_Feedback.class.inc , 
we have:
```php
    // contains info necessary to structure the object
    var $_feedbackObjectInfo ='';

    // contains full candidate profile/timepoint/instrument info
    var $_feedbackCandidateProfileInfo ='';
````
Later, we see: 
```
$this->_feedbackObjectInfo['CandID'] = $candID;
```

In php <7, this would work by creating an array and assigning a value at a string index.  In php 7, an attempt is made to index into the existing string with a string index, which emits a warning and assigns the first character of the value to the variable.

The error can be fixed by assigning empty arrays as initial values.

Shall I submit a pull request?

**Comment by xlecours** [comment]
Please do

**Comment by xlecours** [comment]
Thanks for the explanation

**Comment by xlecours** [comment]
@driusan This one should go into our next minor release
