### ISSUE TITLE
Error in BrainBrowser Volume Viewer v2.4.1

### ISSUE THREAD

**Issue by josephmje** [aces/Loris#2753]
Hi,

The scans uploaded to Loris don't load in BrainBrowser. I get an error in the console:

```
TypeError: c[c.order[1]] is undefined  
d()  
e.volume_loaders.minc/<()  
BrainBrowser.loader.loadFromURL/f.onreadystatechange()
```

It refers to brainbrowser.volume-viewer.min.js

**Comment by MounaSafiHarab** [comment]
Hi Joseph,

- Which version of LORIS do you have installed?
- Do you have the MincTools path set properly in your config.xml (can you tell me what you have it set to)?
- Do you see the images in Imaging Browser or are they broken? 
- Are your `Paths` set properly in the Configuration module (you can attach a screenshot here)?

**Comment by josephmje** [comment]
Hi @MounaSafiHarab ,

I have Loris v17.0.2 installed.

The MincTools path is set to:
```
    <!-- MINC TOOLS PATH -->
    <MINCToolsPath>/opt/minc/1.9.15</MINCToolsPath>
```

The png images in Imaging Browser are visible.

I have attached a screenshot of the `Paths` in the Configuration module. The `Media` and `Genomic Data Path` are currently not set properly.
![configure_paths](https://cloud.githubusercontent.com/assets/22102194/25236532/13841cd2-25b6-11e7-832a-34d92ba13bd5.png)

Thanks

**Comment by MounaSafiHarab** [comment]
Hi @josephmje 

Can you try to add the trailing `/` in the `MincToolsPath` in config.xml so the path reads this: `/opt/minc/1.9.15/`?
Out of curiosity, did you create this folder `1.9.15`? because a default MINC installation would be in `/opt/minc/`.

**Comment by josephmje** [comment]
Hi @MounaSafiHarab 

Adding the trailing `/` fixed the issue. I installed minc toolkit from source and specified `/opt/minc/1.9.15` as the install prefix. Would this affect any other aspects of Loris?

**Comment by MounaSafiHarab** [comment]
Great it is working now!

The additional path should not theoretically affect anything else in Loris. I asked because that was going to be my second suggestion of debugging (after adding the trailing `/`) in case the `.` in the path is causing issues. But since your problem is resolved, then I think it should be fine.

Closing the issue.
