### ISSUE TITLE
Incomplete forms count inconsistent across Dashboard / Stats / Data Team Helper

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#2773]
reported by @um4r12 via loris-dev listserv :

On the dashboard, the number of Incomplete Forms that is displayed in the My Tasks panel only considers an incomplete form if it is 'In Progress'. 
If a visit stage is started, the instruments that are populated are not considered to be 'In Progress' until they are opened. So the number displayed on the dashboard excludes unopened instruments. 
However, in the Data Team Helper module, and the Statistics page, an unopened instrument is considered to be incomplete. 

Improvement: This count should be consistent across modules -- it should include unopened as well as In Progress.

**Comment by ridz1208** [comment]
@driusan given that the panel is now a widget from the module itself, would this still be an issue ??

**Comment by christinerogers** [comment]
I think is still an issue.  However it's been noted as extremely low priority in discussion.  closing for now.
