### ISSUE TITLE
Imaging Uploader: Why so much manual naming?

### ISSUE THREAD

**Issue by gdevenyi** [aces/Loris#2909]
There seems to be three manual naming schemes that need to be all filled in properly before the Imaging Uploader will work properly.

1. The zip/tar.gz filename
2. The web form
3. The PatientName field in the DICOMs

It occurs to me that one of these could be used to properly populate all the fields, reducing the amount of manual work.

Personally, I'd prefer the web form (and DICOM data) being populated from the name of the zip/tar.gz file.

**Comment by MounaSafiHarab** [comment]
Hi @gdevenyi 

This is a valid point. The redundancy is there for a specific reason (with the original thought that having data entered in more than one place would minimize chances that a random typo happens in all 3 places simultaneously). I will bring this up again in a Loris imaging meeting to see the best course of action to make it easier for the users while also maintaining data integrity.

**Comment by johnsaigle** [comment]
@cmadjar Do you know the status of this issue? Was it talked about in an imaging meeting?

**Comment by cmadjar** [comment]
@johnsaigle @gdevenyi I went back to the minutes of the imaging meeting and found this comment:
@davidblader looked into doing the DICOM deidentification at the time of upload and it freezes the browser...

As Mouna explained, the redundancy in the browser is there for quality insurance reasons. I will bring this up again at the next imaging meeting and update the issue after that.

**Comment by cmadjar** [comment]
@gdevenyi @johnsaigle So we discussed this during the imaging meeting of Friday and came to the following conclusion:

"We could autopopulate PSCID, CandID and Visit on the web form of the imaging uploader based on the name of the uploaded file which will remove one of the redundancy. Note that the user will still need to select whether they upload a phantom scan or a participant's scan but all other fields won't need to be entered."

**Comment by johnsaigle** [comment]
@cmadjar I just unassigned David B because he doesn't work here anymore... 😂 

Just wanted to make a note that this still needs to be addressed at some point.

**Comment by cmadjar** [comment]
@johnsaigle lol. I'll give it a try if I have some time.

**Comment by cmadjar** [comment]
@gdevenyi believe it or not but there is finally a PR sent to remove one of the manual naming when uploading imaging dataset. See #5306.

Sorry for the delay with this one...
