### ISSUE TITLE
[API] PUT /candidates/$CandID/$VisitLabel/instruments/$InstrumentName[/dde]

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#3127]
The doc says:

`A PUT request MAY not specify score columns that will be calculated/overwriten by server-side scoring. If the client attempted to score fields client-side and the value passed by the PUT request conflict with the server-side calculation of the score, the server-side calculation will win.`

But server calculation do not trigger

**Comment by johnsaigle** [comment]
@xlecours Is this fixed in the API now?
