### ISSUE TITLE
Media Uploader: Limit list content based upon selection of other fields

### ISSUE THREAD

**Issue by gdevenyi** [aces/Loris#3233]
Example:

You ask for Site as an input for the form.

You can use this information to limit the list of "Visit Label" to only show that site.

**Comment by johnsaigle** [comment]
I think this is now resolved.

Example:

Select "Visit_label" in dropdown.
The instrument dropdown now contains only instruments at that site.

Example 2:
Select a PSCID
The Visit_label dropdown contains only visits that candidate has timepoints for.

<img width="688" alt="Screen Shot 2019-11-27 at 11 35 37" src="https://user-images.githubusercontent.com/4022790/69742058-223d2880-110a-11ea-8d75-7843b5c9e5a9.png">
<img width="688" alt="Screen Shot 2019-11-27 at 11 35 23" src="https://user-images.githubusercontent.com/4022790/69742059-223d2880-110a-11ea-97f8-30cc557035e8.png">


I'm going to close this issue but please feel free to re-open it if I've misunderstood.
