### ISSUE TITLE
Vagrant install impossible due to missing config.xml file

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#3313]
It's not possible to get LORIS running "out of the box" with Vagrant as there is no `config.xml` file existing in the `project` directory. Without this a user cannot run LORIS or follow along with the install instructions to configure it manually.

Output from /var/log/apache2/loris-error.log:

`[Fri Nov 24 19:34:08.802273 2017] [php7:error] [pid 16922] [client 192.168.49.1:49907] PHP Fatal error:  Uncaught ConfigurationException: Config file config.xml does not exist in the defined locations. in /var/www/loris/php/libraries/NDB_Config.class.inc:146\nStack trace:\n#0 /var/www/loris/php/libraries/NDB_Config.class.inc(73): NDB_Config->configFilePath()\n#1 /var/www/loris/php/libraries/NDB_Factory.class.inc(118): NDB_Config::singleton(NULL)\n#2 /var/www/loris/php/libraries/NDB_Client.class.inc(54): NDB_Factory->config(NULL)\n#3 /var/www/loris/htdocs/main.php(29): NDB_Client->initialize()\n#4 {main}\n  thrown in /var/www/loris/php/libraries/NDB_Config.class.inc on line 146`

**Comment by christinerogers** [comment]
@johnsaigle can this issue be updated or closed?  
(Per LORIS meeting today, we don't support vagrant but would like to suggest a path for those looking to test it)

**Comment by johnsaigle** [comment]
I can re-test shortly. Is the idea to keep the Vagrant file in the repo even though we're not supporting it?

**Comment by driusan** [comment]
I have no problem with removing it if no one is going to maintain it.

**Comment by johnsaigle** [comment]
Agreed
