### ISSUE TITLE
There is PHP Fatal error on Major branch.

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#3508]
PHP Fatal error:  Interface 'Psr\\Http\\Server\\RequestHandlerInterface' not found in /var/www/loris/php/libraries/NDB_Page.class.inc on line 29

**Comment by xlecours** [comment]
It is supposed to be in your `vendor/psr` directory. Is it?

**Comment by kongtiaowang** [comment]
OK, Thanks. It works.
