### ISSUE TITLE
Factory function won't work in NDB_Form class

### ISSUE THREAD

**Issue by thomasbeaudry** [aces/Loris#3604]
The factory function will no longer work in LORIS 19.0.X.  The first if statement of the function will always fail since class names no longer start with "NDB_Form_":
 
https://github.com/aces/Loris/blob/32d7d83089cf6db994da4904909dedd07ee3a6bb/php/libraries/NDB_Form.class.inc#L60

**Comment by johnsaigle** [comment]
@driusan Can you comment on how this issue fits in to the changes in the module routing in recent releases?

**Comment by johnsaigle** [comment]
I'm closing this because we've had 3 major releases since this issue was opened and it doesn't appear to be a problem
