### ISSUE TITLE
ABIDE LORIS Instance

### ISSUE THREAD

**Issue by crocodoyle** [aces/Loris#3815]
1. The DQT doesn’t work at all (download button is not there). It is also not obvious how the filtering is supposed to work.
2. In the Imaging Browser, the “QC Comments” button opens a blank window.
3. In the Imaging Browser, the “Download .mnc” button returns “file not found”.

**Comment by driusan** [comment]
Please report these issues to whoever maintains the ABIDE LORIS instance, this repo is for the LORIS software.
