### ISSUE TITLE
Add Checkbox element to Form.js

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#3919]
In reactifying certain modules, a need for a Checkbox React component was discovered. @HenriRabalais has already developed one for Biobank that he is pushing to Loris

PR: https://github.com/aces/Loris/pull/3918

**Comment by driusan** [comment]
Why is there an issue for this if there's already a PR?

**Comment by zaliqarosli** [comment]
I had created it simultaneously and then thought it should probably go into in projects anyways? Not sure how this new Github issue/projects workflow should work :/
