### ISSUE TITLE
[API/Proposal] API images validation/insertion

### ISSUE THREAD

**Issue by driusan** [aces/Loris#3920]
I want to propose a change to the LORIS API to add 2 new endpoints: one for validating that a set of parameters passed (or fails) an endpoint, and another for inserting data into the files table (without validation). The API would then be able to handle both processed, or non-mnc file insertion without validation getting in the way (or inserting without validating for retrospective studies), and the imaging pipeline would be updated to validate the protocol by making an API request.

The validate endpoint would be something like:

```
POST /api-v??/projects/$projname/images/validate

{
    "TE" : "1234"
    "TR" : "56",
    "TI" : "44444",
    /* Etc, anything in the mri_protocol table is required, and it *may* include other headers at the POSTer's discretion */
}
```

and respond with either something of the form:

```
{ "valid": true, "scantype" : "t1w", "caveat" : true}
```

or

```
{"valid" : false, "reason" : "human readable string describing what failed" }
```

The insertion would be handled by just allowing PUT requests to the existing imaging endpoint and inserting into the files table. (We would need to document which types of metadata extraction are supporting and need to support, at a minimum, MINC, in order to have the imaging pipeline use it, this would probably be done in a second phase, since we need a robust metadata extraction architecture that allows us to add support for other formats to populate paramater_file as appropriate.)

**Comment by cmadjar** [comment]
It was discussed multiple times during the imaging meeting that the protocol identification will be done in the backend LORIS-MRI scripts. However, there is a plan to use the API to query the database by the LORIS-MRI scripts instead of using SQL directly. There is a github project created for that in LORIS-MRI repo to start this process: https://github.com/aces/Loris-MRI/projects/1. Closing the issue since the project exists.

**Comment by driusan** [comment]
You can't really discuss on a project, so I think it would be a good idea to keep this open as a place to work through the details
