### ISSUE TITLE
[Docs] Update CentOS configuration guide

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#3946]
The [install process](https://github.com/aces/Loris/blob/minor/README.CentOS6.md) for CentOS has not been updated for a couple of major releases now.

### TODO

* Ensure Markdown renders properly
* Update references to dependencies to the versions appropriate to LORIS
* Change references to LORIS to an up-to-date release
* Fix typos

**Comment by johnsaigle** [comment]
@christinerogers pointed out that most of the CentOS install process is actually documented [in the wiki](https://github.com/aces/Loris/wiki/CentOS-install-guide), not in this file. I think in order to reduce duplication it makes sense to delete the CentOS readme or change it to just point to the Wiki entry. 

@ridz1208 Do you have a preference?

**Comment by driusan** [comment]
It should not be in the wiki, it should be in the code so that changes are reviewed.

**Comment by christinerogers** [comment]
Agreed, and each install Readme should be tested more thoroughly for each (major) release.  Particularly because install Readme issues can't be updated until the next release (bugfix etc), and these keep users from getting started with Loris.

**Comment by johnsaigle** [comment]
@christinerogers You're right we should include it more formally in the release testing procedure.

**Comment by christinerogers** [comment]
creating 21.0.0 specific issue #5018  for dependencies impacting install 
to make the CentOS Readme accurate for release 21 (post-release)
