### ISSUE TITLE
Filtering breaks while *not* on first page of table

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#3948]
You are scrolling through the data table and then decide to filter while on the 2nd or 3rd page of the data. The filtering doesn't work. It only works while you're on the first page of the data table.

<img width="1278" alt="screenshot 2018-09-11 11 57 48" src="https://user-images.githubusercontent.com/17415878/45372153-43276580-b5ba-11e8-877a-f72a24a00b3d.png">
<img width="1280" alt="screenshot 2018-09-11 11 57 53" src="https://user-images.githubusercontent.com/17415878/45372166-49b5dd00-b5ba-11e8-8de2-1551e3b76006.png">

**Comment by driusan** [comment]
Is this across all modules or only the media module?

**Comment by zaliqarosli** [comment]
@driusan i believe all reactified menu filters

**Comment by HenriRabalais** [comment]
PR sent #4632

**Comment by zaliqarosli** [comment]
PR merged
