### ISSUE TITLE
API should be a module

### ISSUE THREAD

**Issue by driusan** [aces/Loris#3968]
Now that hierarchical URLs can be accomplished via the Loris router, there's no longer any reason for the API to be written using rewrite rules in the htdocs folder.

We should convert the API to a real module.

**Comment by johnsaigle** [comment]
Some work has been done on this #3993 but there is more to be done.

**Comment by xlecours** [comment]
https://github.com/aces/Loris/pull/3993

**Comment by driusan** [comment]
Why is this closed? #3993 only does the project endpoints, what about the rest of the API?
