### ISSUE TITLE
httpd cannot be accessed

### ISSUE THREAD

**Issue by Tsite2007** [aces/Loris#3972]
When I start the httpd service , the error log say:
[Tue Sep 25 15:35:36 2018] [alert] [client 202.85.216.21] /var/www/loris/htdocs/.htaccess: RewriteRule: unknown flag 'END'.
so, the apache service   cannot be accessed

**Comment by driusan** [comment]
What version of apache are you using? The END flag (and therefore LORIS) requires apache >= 2.4

**Comment by johnsaigle** [comment]
I am closing this as the bug most likely resulted from the wrong Apache version and the linked PR has made it clear what version LORIS requires.
