### ISSUE TITLE
New API module can't use api/v*/login/ to get access anymore.

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#4004]
New API moduel can't use api/v*/login/ to get access anymore. If people want to use the API, the user has to login Loris site first.
![screen shot 2018-10-16 at 11 54 13 am](https://user-images.githubusercontent.com/9876007/47029921-a321a680-d13a-11e8-9279-65b9b55f11d9.png)

**Comment by driusan** [comment]
I'm not able to reproduce this. With both the PHP builtin or Apache/mod_rewrite I'm getting a token (or error depending on if the password is right.)

(There also shouldn't be a slash at the end of the login endpoint, but it's working for me whether or not I include it.)

**Comment by xlecours** [comment]
Hi @kongtiaowang 
Is this still an issue?
Thanks
