### ISSUE TITLE
[Data Release, Instrument Manager] Module should not rely on superuser permission

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4017]
These modules rely on superuser which acts as a short circuit to all other permissions. That means if a user wants to use these modules at all then they effectively have global access to all other parts of LORIS. These are administrative functions so it's likely that anyone using them will already have elevated permissions -- but there's still no good reason that these modules shouldn't have specific permissions.

### Pull Requests
- [x] Data Release #3062 
- [x] Instrument Manager #4191

**Comment by ridz1208** [comment]
Data_release: https://github.com/aces/Loris/pull/3062

**Comment by johnsaigle** [comment]
Done!
