### ISSUE TITLE
PHP 7.3: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4037]
When we move to PHP 7.3 for LORIS, we'll need to update ambiguous references to `continue` in the source code or else be inundated by warnings.

See https://wiki.php.net/rfc/continue_on_switch_deprecation for more info.

### TODO

Change ambiguous `continue`s to `break`s

**Comment by driusan** [comment]
Have you confirmed that any of these exist? As far as I know we don't have very many switches, let alone ones in loops.

**Comment by johnsaigle** [comment]
I came across it once in `NDB_BVL_Instrument` and I think also in the `generate_tables_and_test_names` script.

**Comment by johnsaigle** [comment]
#4073 Fixes one occurrence of this issue in the NDB_BVL_Instrument class. The issue still exists in the script.

**Comment by Ahmed-Badawy** [comment]
the issue still exists for me. 
![image](https://user-images.githubusercontent.com/5174871/53416516-57caaf00-39dc-11e9-97cc-40d54556458b.png)

**Comment by johnsaigle** [comment]
@Ahmed-Badawy Just to be clear, are you running this on a LORIS codebase? It looks like you're just running on old version of PHPUnit here.

**Comment by woasimtalokdar** [comment]
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in G:\xampp\htdocs\wpoldversion\wp-content\themes\Divi\includes\builder\functions.php on line 6230

**Comment by johnsaigle** [comment]
@woasimtalokdar This appears to be an issue with WordPress, not our software.

**Comment by zimkha** [comment]
please I have the same problem with graphlql that I want to integrate in my project laravel, how to make for this error, I specify that I am in envrironement php 7.1.26

**Comment by johnsaigle** [comment]
I think this has been addressed at some point. #4099

It's not showing up anymore in `make checkstatic` reports, anyway.
