### ISSUE TITLE
Creation of Biobank Module

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#4042]
The development of a Biobank Module has been requested.

This module would allow the tracking of biospecimen inventory and shipments. Specimens would be tracked throughout their lifecycle and be associated to a candidate and timepoint. Containers holding specimen would be organized in a hierarchical structure that would allow fluid navigation throughout the inventory. Specimens will be able to be collected, prepared and analysed. Fields for these processes will be configurable. Permissions for viewing, creating, updating and deleting both specimens and containers will be implemented.

**Comment by johnsaigle** [comment]
#4359

**Comment by johnsaigle** [comment]
There's no doubt that this is coming to LORIS soon so I don't think an issue for this is necessary.
