### ISSUE TITLE
Remove redundant boilerplate from LORIS PHP files

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4061]
Many files have old boilerplate that is unnecessary and in some cases generates notices and warnings. 

Red flags are anything found in the [generic includes](https://github.com/aces/Loris/blob/minor/tools/generic_includes.php), viz.:
* NDB_Client
* Database
* NDB_Config
* Modification of the PHP include path
* Starting a session/including NDB_Client

### TODO
* Remove the above includes/initialization steps from LORIS code, especially module code and ajax scripts. Ensure that no functionality changes.

**Comment by johnsaigle** [comment]
This is done frequently by old `tools/` scripts also.

**Comment by johnsaigle** [comment]
We can also now remove the file doc comments from most PHP files in LORIS> As of now, only class comments are required.

"Standalone" scripts, such as tools/ and ajax/ scripts, should still contain a file comment if they do not have a class.

**Comment by driusan** [comment]
I don't think anyone is going to do this to any extent more than has been done / fixed while working on individual things that are noticed. There's no specifics that are actionable in this ticket.
