### ISSUE TITLE
Freeze Columns Is Not Working

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#4063]
The ability to freeze a column on a datatable when scrolling horizontally is not working.

**Comment by johnsaigle** [comment]
How would I test this? I don't know how to freeze a column in a table.

**Comment by HenriRabalais** [comment]
To be honest, I'm not sure. I've never seen it in action. I just remember being told that it was a behaviour that could be set for certain columns and that it currently isn't working. IIRC it's a setting that's hardcoded.

**Comment by johnsaigle** [comment]
I'm going to close this because we don't know exactly what it refers to and no one else seems to have run into it for over a year
