### ISSUE TITLE
Reactify modules test need to be updated

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#4065]
Reactify modules test need to be updated

**Comment by johnsaigle** [comment]
@kongtiaowang Do you know which modules use new React tests and which do not? Could you post a list here?

**Comment by kongtiaowang** [comment]
It is hard to say, for now, every week we have new React code to be merged.

**Comment by johnsaigle** [comment]
I'm going to close this ticket because it's not very specific. We do need to update tests for new React modules but there is no list of tasks for us to complete.

Travis will fail anything with bad integration tests so I don't think we need to worry about not having tests.
