### ISSUE TITLE
DICOM archive of the major branch broken

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#4067]
See screenshot to visualize the bug.

![screen shot 2018-11-06 at 9 55 31 am](https://user-images.githubusercontent.com/1402456/48072361-51ed5b80-e1aa-11e8-8ddd-07dab8ee8e84.png)

Also, the following warning shows up in the Apache `loris-error.log` file:
```
[Tue Nov 06 09:57:48.115110 2018] [php7:warn] [pid 30720] [client 142.157.131.89:56356] PHP Warning:  preg_match(): Unknown modifier 'p' in 
/var/www/loris/modules/dicom_archive/php/dicomarchiveanonymizer.class.inc on line 58, referer: https://cecile-dev.loris.ca/dicom_archive/
```

 @davidblader Assigning this to you since you are currently working with the preg_match() function in one of your PR. Feel free to change the assignee if you can't do the fix.

**Comment by davidblader** [comment]
this has to do with the refactoring of hiddenHeaders. the fix is very straightforward but i think @HenriRabalais has something in the works already for this issue

**Comment by HenriRabalais** [comment]
@cmadjar @davidblader Yeah, the fix has already been made in minor. I'm not sure when minor will be merged into major, but for the time being I could issue a PR to fix it on major? Not sure how to proceed under these circumstances.

**Comment by driusan** [comment]
We'll probably merge minor into major after 20.1 is released, which hopefully shouldn't be too far off. We just need to re-test it quickly after having merge 20.0.2 into 20.1-dev.

**Comment by johnsaigle** [comment]
Can this issue be closed?

**Comment by cmadjar** [comment]
Just checked the DICOM archive module on major and everything looks great again :). Closing the issue. 
Thanks @johnsaigle for bringing that up!!
