### ISSUE TITLE
Remove unused 'log' config setting

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4100]
The 'log' config setting isn't used anywhere but the `Message` and `Log` class which are now removed from the major branch (#3999, #4041).

We should remove traces of it from LORIS. Places to scrub:
* Configuration module
* DB Schema (probably 0000-00-03)
* ?

The actual folder that this setting points to, `tools/logs/`, is still used in instrument scoring and should not be touched.

**Comment by driusan** [comment]
There are PR/other issues for the things listed and the remaining "?" isn't really actionable, so I think it's worth closing this.
