### ISSUE TITLE
Validate user-facing input fields against the naughty strings database

### ISSUE THREAD

**Issue by gdevenyi** [aces/Loris#4116]
https://github.com/minimaxir/big-list-of-naughty-strings

**Comment by johnsaigle** [comment]
I'm not in favour of this for a few reasons.

* Blacklisting is inherently limited to the quality of your list; a whitelist of allowed types/characters is always going to be stronger. An attacker could look at our source code, look at the BLNS and just use different encodings or vectors.

* The list is more useful as a reference than as something to check against. It contains a lot of different things, from iOS attacks to XSS injection to literal "naughty words". It's not useful to check all user fields against a big list without respect to context. We are instead increasingly using strong types, file upload validation, output sanitizing etc. etc. etc. to deal with malicious input.

* This list contains things like MS-DOS specific vectors, or function calls that can trigger OS comamnd injection on Ruby. This isn't relevant to LORIS.

**Comment by gdevenyi** [comment]
Not suggesting you use the whole list, or you even automate it, simply a suggestion that there are likely "bad strings" that the input fields of Loris may cause undefined behaviour.

**Comment by johnsaigle** [comment]
Definitely true. Bad strings are a security fundamental that we take seriously. There are checks in the various modules to do input validation for different strings. Some examples:

* Anything going in or out of the DB (with a few known exceptions) is sanitized to prevent XSS. Using React also helps as it auto escapes data passed in as a `data` field in its components

* We are writing a File Download Validator (to be followed by an Upload validator) to prevent path traversal. We could probably also include a check that only ASCII characters are used in a file name for example but in general this will be caught by file-existence checks or type checks.

* We are moving to use strong typing wherever possible to prevent classic PHP blunders where type coercion causes security issues.

* We use prepared statements to prevent SQLi

* Any strings involved in OS command execution are escaped using built-in PHP functions

etc. etc.

The only part I'm not very clear on is how Unicode inputs might affect execution. We use UTF-8 everywhere but in terms of interacting with the file system I'm not sure how this would work exactly.
