### ISSUE TITLE
Fix JS lint warnings

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4138]
There are many JavaScript files within the code base that generate warnings in our automated testing procedure. Most of them have to do with lines being too long or functions missing documentation.

Fixing these warnings would be a good way for someone new to get familiar with the code base as well as to learn our code review procedure. 

### TODO
* On a development instance of LORIS run `npm run lint:javascript`
* Issue a pull request that eliminates warnings

**Comment by driusan** [comment]
Note: you don't need to fix *all* of the warnings, fixing some of them would still be a step forward.

**Comment by johnsaigle** [comment]
@driusan This one has been untapped for almost a year, should we leave it up?

If so, we can add the `Bug` label so we don't have to fight stale bot.

**Comment by driusan** [comment]
Sure. I think we should definitely keep the issue, because all those warnings are really annoying and should be fixed.

**Comment by laemtl** [comment]
Replaced by #6750
