### ISSUE TITLE
[Dicom Archive] Prepend PatientName to DICOM download filename

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#4176]
Update Dicom Archive module ASAP with the same feature change as #4157 in Imaging Browser.

Must go into same release as #4157, to avoid the same DICOM tarball download being named differently depending on which module it was downloaded from. 

cc: @cmadjar @johnsaigle

**Comment by johnsaigle** [comment]
@christinerogers #4157 should prepend the patient name regardless of where the download comes from. Maybe you missed my comment here https://github.com/aces/Loris/pull/4157#issuecomment-443754399.

However if you find this does not happen in your testing, please let me know.

**Comment by christinerogers** [comment]
I did miss that, thanks @johnsaigle . 
Let's change the PR header of 4157 back then too.
