### ISSUE TITLE
Add PSR18 implementation to LORIS

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4187]
There is a need for a [PSR18 Http Client](https://www.php-fig.org/psr/psr-18/) implementation in LORIS. This will allow us to avoid rolling ad-hoc connections to outgoing servers. 

This will be useful in areas such as developing our API, creating "CBRAIN hooks", and leveraging external services such as "Have I Been Pwned?" when validating passwords.

### Related PRs
https://github.com/aces/Loris/pull/3962
https://github.com/aces/Loris/pull/3961
https://github.com/aces/Loris/pull/3765

**Comment by driusan** [comment]
should have been autoclosed by #4188..
