### ISSUE TITLE
nifti files are stored under mincpath

### ISSUE THREAD

**Issue by driusan** [aces/Loris#4197]
I noticed while reviewing #4096 that .nii and .nii.gz files are both using the mincPath configuration setting for the location to store them.

This makes the configuration name confusing and should probably be cleaned up.

**Comment by cmadjar** [comment]
@driusan Looking at the Config paths, there is a lot of redundancy and I think this could be cleaned up: `mincPath` = `data` = `imagePath`

- `imagePath` used by `get_file.php`, tool `generate_project_statistics_csv.php`, `php/installer/Installer.class.inc`, `mri_violations.class.inc`, API 0.0.2 and 0.0.3-dev (`candidates/visits/images/format/Thumbnail.php`) and `imaging_install.sh`
- `data` does not appear to be used anywhere in the LORIS code...
- `mincPath` used by `php/installer/Installer.class.inc`, brainbrowser `image.php`, `get_file.php`, API 0.0.2 and 0.0.3-dev (`candidates/visits/images/Image.php`) and `imaging_install.sh`

Will bring it up at the next Imaging meeting so we can decide as a group what to do with it but we should probably just use the `imagePath` one.

**Comment by cmadjar** [comment]
Discussed during the LORIS-MRI meeting of January 18th. Will keep only the `dataDirBasepath` field in the Config module
