### ISSUE TITLE
Minor edge case for reenabling inactive users

### ISSUE THREAD

**Issue by Jkat** [aces/Loris#4208]
https://github.com/aces/Loris/blob/9284f379e120f1075cc6520f41ba924d7e96feb2/php/libraries/SinglePointLogin.class.inc#L361

1. user is inactive
2. you set them back as Active=Y manually (mysql update or frontend)
3. they try to log in but last login is >365 days so Active gets set back to N(!)
4. they complain again
5. you check and tell yourself "wtf i set it to Y how is it back to N"

possible fix: https://github.com/aces/Loris/pull/4207
or maybe to issue an insert into the `user_login_history` table but 1) that feels a bit wrong and 2) wouldn't solve using manually mysql updates

**Comment by driusan** [comment]
I don't see how this fixes the issue. Wouldn't it still fall into the `||` condition after step 2?

**Comment by Jkat** [comment]
Yeah shoot, I just realized, forgot the side effect at the end of calling that function (from it's original intended purpose)
