### ISSUE TITLE
imaging_uploader can't upload a file on major.

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#4209]

**Comment by johnsaigle** [comment]
It looks like the module doesn't load properly on the front-end either. There is no error message in the logs and the page returns `200`. However, there is no content on the page, just the LORIS menu bar and footer.

**Comment by johnsaigle** [comment]
@kongtiaowang Can you provide more detail here? What happens?

I tried uploading a file and I get a "Not Started" status. I'm not really familiar enough with this module to go further.

**Comment by johnsaigle** [comment]
I think this is probably addressed somewhere in the latest v21 release.
