### ISSUE TITLE
Add stronger typing 

### ISSUE THREAD

**Issue by driusan** [aces/Loris#4210]
@johnsaigle has been adding PHP type hints to all of our classes based on the doc block (Status: https://github.com/aces/Loris/projects/11), but how well the compiler can find errors is dependent on how granular our type system is, and right now the vast majority of places are using "string", "array", or (sometimes) "int".

We should implement classes/interfaces for some commonly used types so that PHP/phan can better determine when the wrong type of thing is accidentally passed and yell at us.

#4055 adds a class for CandIDs, and my gut feeling tells me SessionIDs and CommentIDs are probably low hanging fruit. (In most cases what the code that's using them probably really needs is a Candidate or Session object, not an ID, but it would be easier to start by typing the IDs than it would be to completely rewrite the code that's using them to use a data model.)

**Comment by johnsaigle** [comment]
Create [a project](https://github.com/aces/Loris/projects/15) to track the steps involved in this issue since it'll need to be broken into many separate tasks.

**Comment by driusan** [comment]
This is probably too vague to be an issue, and it should just be something we look out for in code review
