### ISSUE TITLE
Remove module ajax directories and replace with real end points

### ISSUE THREAD

**Issue by driusan** [aces/Loris#4217]
The `module/*/ajax` directories are a hack which for the most part bypass the entire LORIS framework via the AjaxHelper.php script.

Now that modules and pages can implement the handle() method and include deep hierarchies, there is no longer any reason for it. They should be replaced by real LORIS end points which include an appropriate Content-Type header (such as application/json) to bypass the PageDecorationMiddleware.

**Comment by johnsaigle** [comment]
Should this maybe be a project instead of a ticket?

**Comment by driusan** [comment]
Sure, I just made https://github.com/aces/Loris/projects/13
