### ISSUE TITLE
add return types to data_release

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#4271]
Related to: https://github.com/aces/Loris/pull/4270/files/101d2d13b26d2e7f4787325692d240242ae9781f#diff-0b0d599fe0612ffeea1aa7ce6185c9c3

This class has return types on some functions and not others, should be made consistent

**Comment by johnsaigle** [comment]
Should be resolved by #5396

**Comment by ridz1208** [comment]
who cares
