### ISSUE TITLE
Add return types to Database class "pselect*" functions

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4284]
#3878 did not add return types to `pselect*` functions because they can return array, null, and sometimes false (I believe). Wrapper functions in other classes and modules that call `pselect` functions are unable to have return types for the same reason.

It would be good to standardize and document the types that these functions can return and eventually to add appropriate return types.

**Comment by driusan** [comment]
They shouldn't return false, they should all be either `?array` or `?string`, I think.

**Comment by johnsaigle** [comment]
Agreed I think some of them have strange error handling though.

This issue is somewhat addressed by https://github.com/aces/Loris/pull/6039 because it makes the array formats more clear. When that is merged we can take a look at making the functions more consistent.

**Comment by johnsaigle** [comment]
I think for the most part they return `?array` now. Only `pselectOne()` needs a return type. Adding it causes phan errors for downstream functions that use it though, so it will require a slightly larger cleanup PR.

**Comment by laemtl** [comment]
It seems to have been addressed.
