### ISSUE TITLE
0.0.3-dev API candidate creation require FULL SITE NAME instead of alias

### ISSUE THREAD

**Issue by dyt811** [aces/Loris#4327]
* As tested in 20.1

## Symptom:
- 0.0.3-dev API now REQUIRE site information at the time when creating candidate. 
- However, it currently requiring site name instead of site alias. 
- Confirmed at LORIS meeting that site alias is probably more appropriate. 
- See related issue that alias should really be unique enforced: https://github.com/aces/Loris/issues/4326

## Expected:
- Providing site alias instead of full site name.

**Comment by xlecours** [comment]
> Confirmed at LORIS meeting that site alias is probably more appropriate.
I can see this entry in the meeting agenda but there is no minutes that goes with it.

What is the issue with the full site name? it is unique in the table.

**Comment by johnsaigle** [comment]
@dyt811 Can you provide some more information here?

**Comment by ridz1208** [comment]
adding to next loris meeting

**Comment by xlecours** [comment]
The api specification requires a full site name when creating a candidate and a visit. It will remain. In 0.0.3, there was no way of knowing the valid site names, or valid aliases but API v0.0.4-dev now offers an endpoint to list the sites from a study.
