### ISSUE TITLE
[JS] negotiation discovery

### ISSUE THREAD

**Issue by PapillonMcGill** [aces/Loris#4351]
lots (not tested all link yet) generate som error in the log

[Wed Feb 20 08:44:23.786739 2019] [negotiation:error] [pid 4150] [client 192.168.122.1:35038] AH00687: Negotiation: discovered file(s) matching request: /home/lorisadmin/Loris/htdocs/js/components/Markdown.js (None could be negotiated)., referer: https://cbigr-dev.loris.ca/candidate_list/
[Wed Feb 20 08:44:23.787373 2019] [negotiation:error] [pid 4172] [client 192.168.122.1:35034] AH00687: Negotiation: discovered file(s) matching request: /home/lorisadmin/Loris/htdocs/js/components/Breadcrumbs.js (None could be negotiated)., referer: https://cbigr-dev.loris.ca/candidate_list/
[Wed Feb 20 08:44:23.787434 2019] [core:error] [pid 3082] [client 192.168.122.1:35040] AH00037: Symbolic link not allowed or link target not accessible: /home/lorisadmin/Loris/htdocs/fontawesome, referer: https://cbigr-dev.loris.ca/candidate_list/
[Wed Feb 20 08:44:23.790514 2019] [negotiation:error] [pid 3081] [client 192.168.122.1:35036] AH00687: Negotiation: discovered file(s) matching request: /home/lorisadmin/Loris/htdocs/js/components/Form.js (None could be negotiated)., referer: https://cbigr-dev.loris.ca/candidate_list/
[Wed Feb 20 08:44:23.862481 2019] [negotiation:error] [pid 3083] [client 192.168.122.1:35048] AH00687: Negotiation: discovered file(s) matching request: /home/lorisadmin/Loris/htdocs/js/components/Breadcrumbs.js (None could be negotiated)., referer: https://cbigr-dev.loris.ca/candidate_list/
[Wed Feb 20 08:44:23.873093 2019] [negotiation:error] [pid 4172] [client 192.168.122.1:35050] AH00687: Negotiation: discovered file(s) matching request: /home/lorisadmin/Loris/htdocs/js/components/Form.js (None could be negotiated)., referer: https://cbigr-dev.loris.ca/candidate_list/
[Wed Feb 20 08:44:23.879354 2019] [negotiation:error] [pid 4150] [client 192.168.122.1:35052] AH00687: Negotiation: discovered file(s) matching request: /home/lorisadmin/Loris/htdocs/js/components/Markdown.js (None could be negotiated)., referer: https://cbigr-dev.loris.ca/candidate_list/
[Wed Feb 20 08:44:24.383210 2019] [negotiation:error] [pid 3082] [client 192.168.122.1:35054] AH00687: Negotiation: discovered file(s) matching request: /home/lorisadmin/Loris/htdocs/js/components/Form.js (None could be negotiated)., referer: https://cbigr-dev.loris.ca/candidate_list/

TO REPRODUCE:
install latest major (2019-02-20) and apply SQL patches
login in and click on the menu item

**Comment by johnsaigle** [comment]
@PapillonMcGill is this still an issue? I'm not able to reproduce. No issues appear in the error log when I click menu items.

**Comment by PapillonMcGill** [comment]
@johnsaigle Not with v21.0.3-256-gea79c06 at least.

**Comment by driusan** [comment]
sounds apache configuration related, not LORIS related.
