### ISSUE TITLE
[JS] fontawesome  symbolic link

### ISSUE THREAD

**Issue by PapillonMcGill** [aces/Loris#4352]
when clicking on a menu item, an error show up on the error log

[Wed Feb 20 08:44:23.787434 2019] [core:error] [pid 3082] [client 192.168.122.1:35040] AH00037: Symbolic link not allowed or link target not accessible: /home/lorisadmin/Loris/htdocs/fontawesome, referer: https://cbigr-dev.loris.ca/candidate_list/

TO REPRODUCE:
install latest major (2019-02-20) and apply SQL patches
login and click on a menu item

**Comment by johnsaigle** [comment]
@kchatpar Did you encounter this issue when installing your LORIS?

**Comment by johnsaigle** [comment]
I'm not able to reproduce this. I'm going to close it for now since it's an old issue and there hasn't been any feedback.

If this is still an issue, please feel free to re-open it
