### ISSUE TITLE
[Reliability] module Class missing

### ISSUE THREAD

**Issue by PapillonMcGill** [aces/Loris#4353]
Blank page on the screen and following error in log:

[Wed Feb 20 09:07:08.559584 2019] [php7:error] [pid 3084] [client 192.168.122.1:36190] PHP Fatal error:  Uncaught LorisModuleMissingException: reliability is missing Module class in /var/www/Loris/php/libraries/Module.class.inc:75\nStack trace:\n#0 /var/www/Loris/src/Router/BaseRouter.php(90): Module::factory('reliability')\n#1 /var/www/Loris/src/Middleware/ResponseGenerator.php(49): LORIS\\Router\\BaseRouter->handle(Object(Zend\\Diactoros\\ServerRequest))\n#2 /var/www/Loris/src/Middleware/ContentLength.php(51): LORIS\\Middleware\\ResponseGenerator->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\Router\\BaseRouter))\n#3 /var/www/Loris/htdocs/index.php(47): LORIS\\Middleware\\ContentLength->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\Router\\BaseRouter))\n#4 {main}\n  thrown in /var/www/Loris/php/libraries/Module.class.inc on line 75, referer: https://cbigr-dev.loris.ca/candidate_list/

TO REPRODUCE
install latest major (2019-02-20),
login and click on Clinical -> Reliability menu

**Comment by driusan** [comment]
Reliability was deleted in #3886 ?

**Comment by PapillonMcGill** [comment]
Then we should remove it from the menu

**Comment by driusan** [comment]
But #3886 also removed it from the menu..

**Comment by PapillonMcGill** [comment]
It just remove the creation of the menu for new install but there is not removal from existing instance.
reliability table and entry in LorisMenu are still present.

@driusan do you want me to create a PR to remove them?

**Comment by johnsaigle** [comment]
@PapillonMcGill @driusan Was Reliability ever removed from the menu in a SQL patch? This should be done for the 21.0.0 release if not.

**Comment by PapillonMcGill** [comment]
@johnsaigle  Nope, wasn't removed in major when I created this issues.
