### ISSUE TITLE
Link to coding standards in contributing.md broken.

### ISSUE THREAD

**Issue by kchatpar** [aces/Loris#4361]
In the file contributing.md the link to coding standards is broken.

https://github.com/aces/Loris/blob/master/CONTRIBUTING.md

In the second paragraph the Coding Standards link doesn't work.

Also, some links on the [wiki technical page](https://github.com/aces/Loris/wiki/Technical) are broken:

- [ ] Coding Standards (docs/) 
- [ ] Pull Request template

**Comment by driusan** [comment]
The extension for the Coding standards doc was missing in the wiki page, I just fixed it, but I'm not sure what you mean by the other bullet point or sentence..

**Comment by kchatpar** [comment]
Thanks Dave I updated the PR to include the broken link in the markdown file(CONTRIBUTING.md).

**Comment by christinerogers** [comment]
@kchatpar  this issue is resolved -- please close at your leisure, thanks.
