### ISSUE TITLE
"Start Next Stage" will crash when instrument does not exist

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4368]
Error-handling should be improved so that an error message is displayed to the user instead of crashing.

Example stack trace (on `major` branch):
>PHP Fatal error:  Uncaught Exception: Instrument does not exist in /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc:208\nStack trace:\n#0 /var/www/loris/php/libraries/NDB_BVL_Battery.class.inc(195): NDB_BVL_Instrument::factory('tsi', '', '')\n#1 /var/www/loris/php/libraries/NDB_BVL_Battery.class.inc(156): NDB_BVL_Battery->addInstrument('tsi')\n#2 /var/www/loris/modules/next_stage/php/next_stage.class.inc(128): NDB_BVL_Battery->createBattery(2, 'Visit', 'M1', 2, true)\n#3 /var/www/loris/php/libraries/NDB_Form.class.inc(162): LORIS\\next_stage\\Next_Stage->_process(Array)\n#4 /var/www/loris/php/libraries/LorisForm.class.inc(1436): NDB_Form->_save(Array)\n#5 /var/www/loris/php/libraries/NDB_Form.class.inc(133): LorisForm->process(Array)\n#6 /var/www/loris/php/libraries/NDB_Form.class.inc(190): NDB_Form->save()\n#7 /var/www/loris/src/Middleware/UserPageDecorationMiddleware.php(173): NDB_Form->handle(Object(Zend\\Diactoros\\ServerRequest))\n#8 /var/www/loris/src/Middleware/PageDecorationMiddleware.php(49): LORIS\\Middleware\\UserPageDecor in /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc on line 208, referer: https://jsaigle-dev.loris.ca/next_stage/?candID=575139&sessionID=2153&identifier=2153

**Comment by driusan** [comment]
When what instrument does not exist?

**Comment by johnsaigle** [comment]
My VM is using a Raisinbread and some study refers to the `tsi` instrument which is apparently not installed correctly. When going through the `next_stage` module and clicking the Start Next Stage button, LORIS crashed with the above stack trace. 

I'm not sure if the specific instrument or visit matters. We need to catch the Exception when it's thrown and handle it with the decorator etc.

**Comment by johnsaigle** [comment]
This can be tested on Raisinbread by clicking the link in my bug report and replacing the base URL with your own VM.

**Comment by johnsaigle** [comment]
This will probably be resolved by #6076
