### ISSUE TITLE
[tasks] imaging_browser Single image column format, header info table open by default

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#4380]
See the PR #3323 
[Imaging Browser] Single Image column format, Header Info table open by default

Tasks needed to be completed:
1) Module needs to be updated to es6
2) Remove Smarty
3) Rasinbread needs to have data added that's missing (see PR #4120)
4) Image files are missing (see status of issue #4381 for progress on that front).

@cmadjar @ridz1208 please add anything I missed.

**Comment by cmadjar** [comment]
@maltheism should this issue be closed or there are things still missing? I see 2 PRs have been merged.
