### ISSUE TITLE
Create a valid imaging dataset in raisin bread

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#4381]
Current PR for the next raisin bread dataset: https://github.com/aces/Loris/pull/4120/files

1) source the SQL tables for the raisin bread dataset
https://github.com/aces/Loris/blob/eea3a211654bbb40a378a432d6b4a275a409d120/.travis.yml#L56
- source all the schema tables from the branch https://github.com/aces/Loris/pull/4120/files 
- source the instrument aosi.sql, bmi.sql, medical_history.sql, mri_parameter_form.sql and radiology_review.sql 
- source all the RB_files in the PR

2) ask Pam access to the raisin bread files or demo files

3) create a script to populate the parameter_file table of the files or delete all scans and insert a few properly using the imaging pipeline

**Comment by driusan** [comment]
For both this and #4382, maybe it would be a good idea to look into creating a raisin bread git annex repo for hosting the files?

**Comment by cmadjar** [comment]
MRI PR merged for RB so closing this.
