### ISSUE TITLE
Update "Code Review Checklist"

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4390]
Our code review checklist (https://github.com/aces/Loris/wiki/Code-Review-Checklist) does not do a good job at communicating to developers what is required when reviewing code. 
For examples _in practice_ 

* no code gets merged unless it is both `Approved` AND has the `Passed Manual Tests` label AND has no requested changes from other developers. It's not clear
* It's not clear what these labels actually signify or how one should apply them unless you work at the MNI for a while
* It's doubtful that people are using `make checkstatic` before merging PRs which would cut down on the RTT between submitting a PR, checking Travis, resubmitting, etc. (Though to be fair this is a recent feature)
* Common troubleshooting tips are not well documented, for example that `make dev` must be run every time a developer switches to a branch based on `major`. 
* A brief overview of our linters could be useful (php, phan, phpcs, npm)
* Magic numbers should not be used (replacing #5432)
* Dates should use DateTime objects #5003 
* singleton() declarations must use the Factory class

This document can also be better organized generally.

We will need to decide whether this should be updated in the Wiki or if it should be tracked in the repo as part of the "revamp"

**Comment by johnsaigle** [comment]
Tagged as Beginner Friendly -- hopefully other developers can comment further on what can be made more clear.

@kchatpar let me know if I missed anything from our discussion earlier.

**Comment by johnsaigle** [comment]
@christinerogers This is one possible solution for making test instructions more clear as we discussed in today's meeting.

**Comment by driusan** [comment]
I hope you're not counting your own comment as activity, stalebot.

**Comment by johnsaigle** [comment]
I added

> Magic numbers should not be used (replacing #5432)

to the description which it counts as activity.

**Comment by johnsaigle** [comment]
#6105 has revised the Code Review Checklist but I think many of these points would be better served by a "PHP Style Guide" similar to what we use for React and SQL. 

This should make a passing reference to the Automated Testing guide but in general should avoid being an explainer of phpcs, phan etc. Instead it should cover things that are not validated by automated testing, such as DateTimes, magic numbers, etc.
