### ISSUE TITLE
[login: request account]: Revamp logic 

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#4396]
See the full discussion : #4372

Consider this scenario...

Because we allow for it, User X has the following:
`UserID = A@email.com`
`Email = B@email.com`

X forgets that they have an account with LORIS.

- If X uses B@email.com for the request: Success message for security reasons.

- If X uses A@email.com for the request: Used to give 500 error because of duplication. #4372 addresses this issue. But we still need to revamp the logic.

**Proposed solutions:** 
1. Do not pre-populate the `UserID` column, leave it empty and only fill in when the request is being approved. In this case the checkbox for using the same email for userID can be utilized.
2. Ask user for userID when they request an account.

**Comment by ridz1208** [comment]
@jesscall  can this be closed ?
