### ISSUE TITLE
Instrument creation / installation workflow is broken

### ISSUE THREAD

**Issue by driusan** [aces/Loris#4405]
In order to install a NDB_BVL_Instrument style instrument the following steps are required:
1. Use lorisform_parser to generate the ip_output.txt
2. Use generate_tables_sql_and_testNames with ip_output.txt to generate the SQL
3. Source the SQL file to create the instrument table and populate the test names table.

However, lorisform_parser seems to call getFullName(), which does a select on test_names to get the testname, resulting in step 1 being broken because of a circular dependency between steps 1 and 3.

**Comment by zaliqarosli** [comment]
this issue can be closed now right? @driusan

**Comment by driusan** [comment]
I thought it should have been autoclosed by #4407.
