### ISSUE TITLE
Users at single site create invalid sessions

### ISSUE THREAD

**Issue by driusan** [aces/Loris#4414]
When a user is affiliated with a single site, the timepoint creation is broken and the session has no CenterID set.

This was broken by #4049, which incorrectly set the type hints for the visit label and centre to nullable strings in the `TimePoint::createNew` function (presumably because that was the default value prior to type hinting, even though the doc comment was correct and it shouldn't be valid to have a session with no site or visit label.) When a user is affiliated with multiple sites, the new visit page prompts them to select which site the session is for, and the field is populated based on that. When a user is only affiliated with a single site, it does not get set at all and ends up being passed as null by the create_timepoint page.

The API also appears to not pass the center to createNew (even though it validates it, it doesn't pass it to create new.)  (The create timepoint page also doesn't check for the case where a user has no site affiliations, while the API does.)

The nullable visit label code in createNew() appears to be written with the intend of allowing the possibility of having visits created consecutively (V1, V2, V3, etc) by passing a "null" value as the visit label. This is probably valid, but should also probably be validated by the caller checking the config settings before calling createNew, not by createNew assuming that's the case based on a null parameter.

**Comment by maltheism** [comment]
Fixed in #4358 if I'm not mistaken.

**Comment by johnsaigle** [comment]
@driusan Can this be closed now that #4416 is merged?

**Comment by driusan** [comment]
Not sure why it didn't autoclose when that was merged since the commit message says it fixes it..

**Comment by johnsaigle** [comment]
Yeah I've had the same thing happen with a few PRs I've marked with Fixes or Resolves.
