### ISSUE TITLE
API 0.0.3-dev and 0.0.2 Bug on Handling Invalid Project Name 

### ISSUE THREAD

**Issue by dyt811** [aces/Loris#4427]
API Candidate creation has a bug with handling unanticipated ProjectName (e.g. non-existent, case unmatched project name).

Example JSON: 
- Input: 
```{"Candidate": {"Project": "INVALIDPROJECT", "EDC": "1986-11-21", "DoB": "1986-11-21", "Gender": "Male", "Site": "CHU_STJ"}}```
- Assuming everything is correct with the exception of the PROJECT name. 
- Expected return: 400 with reason. 

API POST to /api/v0.0.3-dev/candidates/:

* return 201 creation success with empty JSON. Expected 400. 

   * Subject is created

* Same JSON, POST to  /api/v0.0.2/candidates/:
 
   * Return 500 error with empty JSON. Expected 400. 

   * Subject is created

* Same JSON, POST to Candidate creation API call to /api/v0.0.3-dev/Candidates/ 
   * return 200 okay. 
   * no subject created.

* Same JSON, POST to Candidate creation API call to /api/v0.0.2/Candidates/ 
   * return 200 okay.
   * no subject created.

**Comment by xlecours** [comment]
API 0.0.2 is no more. 
In API 0.0.3, POST /candidates now returns 400 Bad Request
```
{
  "error": "No project named: INVALIDPROJECT"
}
```
