### ISSUE TITLE
Move functions from Utility class to appropriate library or module

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4428]
There are various comments in the file `php/libraries/Utility.class.inc` that suggest moving a function from there to a more appropriate location in the code base.

**Comment by driusan** [comment]
Do you have a list of functions to add to this issue?

**Comment by johnsaigle** [comment]
There are a handful:
* getTestNameByCommentID
* structureToPCRE
* getTestNameUsingFullName
* getSourcefields
* columnsHasNull
* getVisitInstruments

Each of them is documented with the module or modules (max 2) that use them and this is where they should be moved.

**Comment by johnsaigle** [comment]
#6173 and #6205 have both been issued to do Utility cleanup. Only one of them should be merged as they will likely conflict.
