### ISSUE TITLE
Print labels from the biobank module

### ISSUE THREAD

**Issue by kchatpar** [aces/Loris#4441]
This issue is a feature of the biobank module. The biobank module tracks specimen inventory. Labeling each biospecimen with a unique barcode is important to track the specimen as it gets processed and stored. The printer will be used to print the barcode is a Zebra printer located in the CBIG repository.

**Comment by johnsaigle** [comment]
As we discussed a few weeks ago, this will involve at some point a call to the shell using a function such as `exec()`. When a PR is sent for this issue it should be thoroughly reviewed from a security perspective.

This may also need to be added as an optional configuration setting within LORIS as networking issues could arise when communicating with a printer from a LORIS instance. For an example of how this could work see #3961 as it does the same thing in the context of querying an external API.

**Comment by johnsaigle** [comment]
@kchatpar Can this be closed?

**Comment by kchatpar** [comment]
Done in biobank repo
