### ISSUE TITLE
reCapcha Plan: Implement Test and Fix with latest updates.

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#4450]
# Waiting on #4395 to be merged before addressing the proceeding issue..

## Issue:
Goggle reCapcha apparently has changed since reCapcha was integrated into Loris. I noticed this when I was updating the login module to react on Major. I'm assuming not one installation of Loris has enabled reCapcha and otherwise an issue would have been reported by now.

See @johnsaigle [comment](https://github.com/aces/Loris/pull/4404#discussion_r267100321) and discussion [here](https://github.com/aces/Loris/pull/4395#discussion_r265660761) for further details.

### Steps:
1) Rewrite & Cleanup unnecessary old reCapcha code.
2) Implement tests to spot if reCapcha ever becomes broken.

**Comment by johnsaigle** [comment]
recaptcha is fixed in #6344 but it doesn't not have automated tests to detect whether or not it's working.

Further work here would be to take the code introduced in that PR and create a new React component so that the code can be encapsulated and re-used.

**Comment by driusan** [comment]
I think this is stale and, at any rate, bots are more effective than humans at solving captchas these days, so there's little value in spening a lot of time on this.
