### ISSUE TITLE
Candidate's date of birth can be selected for dates past the current date.

### ISSUE THREAD

**Issue by kchatpar** [aces/Loris#4451]
When creating a new candidate the date of birth selected can be selected for a date past the current date. Ex. Today is April 8, 2019 I am able to select April 9, 2019 as the date of birth. It's impossible for the candidate to be born.

Fix: Implement a method that checks if the DOB selected happens before today's date.

**Comment by johnsaigle** [comment]
Duplicate of #5733. I'm going to close this because the other PR has more attention, even though this one was issued first.
