### ISSUE TITLE
Update Ubuntu version number in install.sh

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4460]
## Problem: 
When running [install.sh](https://github.com/aces/Loris/wiki/Installing-Loris-in-Depth) in the "Running the Install Script" section, step 5, the question "Would you like to automatically create/install apache config files? (Works for Ubuntu 14.04 default Apache installations)" is asked. The Ubuntu version number should be updated to 16.04 since the installation guide is for 16.04.

## Fix:
In [install.sh](https://github.com/aces/Loris/blob/minor/tools/install.sh), line number 199 should be updated to 16.04 from 14.04, given the installation guide is for 16.04.

## Note:
I've run the [install.sh](https://github.com/aces/Loris/blob/minor/tools/install.sh) script on Ubuntu 18.04 and it worked but further testing is needed.

**Comment by christinerogers** [comment]
Thanks @coreyAbout for reporting this issue.   

Let us know - Will you have a PR fix for this?  

( cc @kchatpar )

**Comment by coreyAbout** [comment]
Yes, I will. 
(cc @christinerogers  @kchatpar )
