### ISSUE TITLE
File name duplication in document repository

### ISSUE THREAD

**Issue by c-hoh** [aces/Loris#4462]
Dear maintainer, 

when uploading files using the document repository file names are duplicated in the user uploads directory. 

So, assuming user _jrandom_ uploads a file called _catpicture.jpg_ the resulting file name on the server will be `/path/to/loris/modules/document_repository/user_uploads/jrandom/catpicture.jpgcatpicture.jpg`

Which does not seem to be the intended behaviour. 

I believe that this is caused by first, lines 55f. in documentEditUpload.php

```
        $fileName = $_FILES["file"]["name"];
        $fileType = pathinfo($_FILES['file']['name'], PATHINFO_EXTENSION);

        $uploadPath = "$base/modules/document_repository/user_uploads/$name/";
        $fullPath   = $uploadPath . $fileName;
```

And subsequently line 82f:

```
        if (!move_uploaded_file(
            $_FILES['file']['tmp_name'],
            $fullPath . $fileName
        )) 
```

Which appends the filename to the full path again. 

Changing the latter piece to

```
        if (!move_uploaded_file(
            $_FILES['file']['tmp_name'],
            $fullPath 
        )) 
```

leads to the expected behaviour at least on my machine.

**Comment by driusan** [comment]
thanks @koyangi-ssi ... is this only on the major branch, or is it in the latest release too?

**Comment by koyangi-ssi** [comment]
I am running 20.2.1 locally, I checked the repo and this seems to be present in the 20.3 branch as well.
