### ISSUE TITLE
Message for IE not supported

### ISSUE THREAD

**Issue by PapillonMcGill** [aces/Loris#4470]
Imaging Uploader does not work with IE, perhaps we can put a message somewhere on the page that clearly says IE is not supported (on every page, or a pop up on log-in when IE is detected

**Comment by christinerogers** [comment]
Banner message at the top would be ideal.

**Comment by driusan** [comment]
Browser sniffing is almost always a bad idea compared to feature detection. What does "does not work" mean? What doesn't work? Given that Edge is switching to a Blink based rendering engine, I don't see why it should have problems.

**Comment by johnsaigle** [comment]
Are we going to implement this? The login page already displays `A WebGL-compatible browser is required for full functionality (Mozilla Firefox, Google Chrome)`

**Comment by driusan** [comment]
I don't see any reason we would implement this. If there's an actual known bug in modern versions of IE/Edge, file a bug report for that.
