### ISSUE TITLE
Remove PHP Mess Detector from testing pipeline?

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4475]
I was excited to use this tool more extensively in our workflow but it looks like it's not maintained. https://github.com/phpmd/phpmd/

The last release was over two years ago and its Issue Tracker is full of people raising problems that it has with more recent versions of PHP.

I ran into problems with PHP Mess Detector when working on #4404. I ran into this issue https://github.com/phpmd/phpmd/issues/601 and I fear it won't be patched. Suppressing the warning doesn't appear to work either.

It may be best to remove this tool given that it has problems that are unlikely to be fixed.

What do others think?

**Comment by johnsaigle** [comment]
It was decided in a recent LORIS meeting that we should remove PHPMD for the above reasons as long as some other static analysis tool covers what it can do.

**Comment by johnsaigle** [comment]
Phan indeed has rules to cover this: we can pass in the flags `--unused-variable-detection` `--dead-code-detection` and/or `--redundant-condition-detection` and that should cover at least what PHPMD does.

We should keep PHPMD until these flags are incorporated into our static testing.

**Comment by driusan** [comment]
Can equivalents to those be set in `.phan/config.php`?

**Comment by johnsaigle** [comment]
I'll look into it. From what I understand though these flags were "Extensions" which is different from the Phan rules. 

I think we could add the flags to the scripts executed in the `Makefile`.

**Comment by driusan** [comment]
If that's the only way to do it, yes, but it would be better if they came directly from the config so that it's what phan does with no arguments.

**Comment by johnsaigle** [comment]
Agreed, but I don't think it's possible unfortunately.

**Comment by johnsaigle** [comment]
Ah wait I'm wrong! I think we can do it by declaring `plugins` like this:
https://github.com/phan/phan/blob/1.2.1/.phan/config.php#L593-L613

**Comment by johnsaigle** [comment]
PHPMD will be removed when the relevant phan rules are enabled

**Comment by johnsaigle** [comment]
Nevermind! PHPMD has a new maintainer team
