### ISSUE TITLE
Password requirements

### ISSUE THREAD

**Issue by glatard** [aces/Loris#4490]
Hi,

Using password `z2XtUOHc[&Rw^cK` in the new password prompt on https://openpreventad.loris.ca results in being logged off and not being able to log in again using this password or the old one. Trying from the same environment with a simpler password works.

**Comment by driusan** [comment]
@cmadjar @Jkat

**Comment by Jkat** [comment]
Did some preliminary debugging, I think the `&` symbol is causing the issue. Will have to dig deeper.

**Comment by Jkat** [comment]
Should be fixed now on `https://openpreventad.loris.ca`

**Comment by johnsaigle** [comment]
This issue is present across LORIS atm. HTML entities cause this issue when used in passwords. See https://github.com/aces/Loris/pull/4491
