### ISSUE TITLE
[User_account] when add a new user, it shows admin user's info.

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#4501]
![Screen Shot 2019-05-13 at 10 31 42 AM](https://user-images.githubusercontent.com/9876007/57629797-6865dc80-756a-11e9-88d3-2e3d72dad748.png)

**Comment by driusan** [comment]
Is it the admin user or the user you're logged in as?

**Comment by ridz1208** [comment]
@kongtiaowang it looks like the chrome autofill
try in an incognito window or disable autofill

**Comment by kongtiaowang** [comment]
It is a chrome autofill issue.
