### ISSUE TITLE
[document_repository] can't upload a file. 500 error

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#4504]
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to NDB_Notifier_Abstract::_hasNotificationPermission() must be of the type integer, string given, called in /var/www/loris/php/libraries/NDB_Notifier_Abstract.class.inc on line 261 and defined in /var/www/loris/php/libraries/NDB_Notifier_Abstract.class.inc:277\nStack trace:\n#0 /var/www/loris/php/libraries/NDB_Notifier_Abstract.class.inc(261): NDB_Notifier_Abstract->_hasNotificationPermission('11')\n#1 /var/www/loris/php/libraries/NDB_Notifier_Abstract.class.inc(131): NDB_Notifier_Abstract->_get2DListToNotify()\n#2 /var/www/loris/php/libraries/NDB_Notifier.class.inc(47): NDB_Notifier_Abstract->__construct('document_reposi...', 'edit', Array, false)\n#3 /var/www/loris/modules/document_repository/ajax/documentEditUpload.php(31): NDB_Notifier->__construct('document_reposi...', 'edit')\n#4 /var/www/loris/htdocs/AjaxHelper.php(112): require('/var/www/loris/...')\n#5 {main}\n  thrown in /var/www/loris/php/libraries/NDB_Notifier_Abstract.class.inc on line 277, referer: https://wangshen-dev.loris.ca/document_repository/

**Comment by kongtiaowang** [comment]
https://github.com/aces/Loris/pull/4551

**Comment by johnsaigle** [comment]
Note that this issue only occurs if the user has notifications enabled under `My Preferences`
