### ISSUE TITLE
[acknowledgements] End Date can be earlier than Start Date

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#4509]
When adding an acknowledgement the End Date can be earlier than Start Date. 
https://github.com/aces/Loris/projects/19#card-21438166

**Comment by zaliqarosli** [comment]
https://github.com/aces/Loris/pull/4528

**Comment by ridz1208** [comment]
@maltheism closing the issue since the PR has been merged. please reopen if issue is still occuring
