### ISSUE TITLE
[Candidate List] Open Profile Form is not redirecting to Candidate Timepoint List.

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#4516]
When a user does not have the 'access_all_profiles' permission, there is no way to access any of the candidate's timpoint lists. This is because a) there is no hyperlink to the candidates available via clicking on the PSCID, and b) there open profile form which allows you to type in the pscid to access the candidate timepoint list is not functional.

The open profile form needs to be fixed.

**Comment by ridz1208** [comment]
@HenriRabalais while looking into this we realised that the open profile form was moved to a modal window which is good, the only problem is the form in the modal window doesnt work... sooo still an issue

**Comment by HenriRabalais** [comment]
Okay! I will update the issue to reflect these findings.

**Comment by coreyAbout** [comment]
[Permissions](https://github.com/aces/Loris/tree/minor/modules/candidate_list):
`Accessing the candidate_list module requires either the data_entry permission and at least one study site, or the access_all_profiles permission. `
[Interactions with LORIS](https://github.com/aces/Loris/tree/minor/modules/candidate_list):
`Clicking on the cell in the PSCID column ... The link is only clickable if the user does not have the data_entry permission.`

Remove access_all_profiles permission means data_entry permission need to be selected, which will make the PSCID link not clickable.

Thus, the [TestPlan](https://github.com/aces/Loris/blob/minor/modules/candidate_list/test/TestPlan.md) 17 also need to be changed as well.

**Comment by ridz1208** [comment]
The open profile modal window needs to be fixed !

**Comment by maltheism** [comment]
Can a picture be posted here of the required permissions for a user account to replicate this bug.

**Comment by ridz1208** [comment]
@maltheism you should be able to replicate if you only have the data_entry permission

**Comment by maltheism** [comment]
Well I'm confused because the Open Profile form worked for me. I have my user set as Data entry for permissions. Sites are all selected if that matters and the user is an Examiner at all sites as well.

**Comment by ridz1208** [comment]
can you replicate this on test.loris.ca

**Comment by ridz1208** [comment]
seems like it working for me as well on test.

will see if this pops back up in the next testing round
