### ISSUE TITLE
[Timepoint List] Candidate Information Leaked When Accessing Candidate Not From User's Site Via URL

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#4518]
When accessing a candidate timepoint list from a site other than the user's, candidate information (DoB, etc.) is leaked. This should be replaced with a large 'Permission Denied' with a hyperlink to return to the previous page. The test plan should be updated to reflect this: #4529

**Comment by johnsaigle** [comment]
Hm I think the test plan may be out of date for this one. I think that users shouldn't be able to see user data from other sites and so the code is working correctly here.

Maybe @christinerogers knows?

**Comment by HenriRabalais** [comment]
I just clarified with @ridz1208 and I think the testplan needs to be updated. The page is still leaking candidate information, so I will update this issue to reflect this.

**Comment by driusan** [comment]
fixed by #4666
