### ISSUE TITLE
[acknowledgements] Start Date and End Date share same input when typing

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#4519]
The Start Date & End Date field apparently share the same input when user types.
https://github.com/aces/Loris/projects/19#card-21438166

**Comment by zaliqarosli** [comment]
https://github.com/aces/Loris/pull/4528

**Comment by jftunteng** [comment]
@maltheism  closing this issue since the PR is merged. Feel free to reopen if this is still an issue.
