### ISSUE TITLE
[Candidate Parameters] Editing is not available.

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#4520]
When Clicking on the 'Edit Candidate Info' button in Timepoint List, the hyperlink points to a page that simply displays the candidate info. Editing options are not available even when the 'Edit Candidate Parameters' permission is enabled. A PR has been made to address this issue: #4455.

**Comment by driusan** [comment]
Should be resolved, but will need to be re-tested in the next testing round..
