### ISSUE TITLE
[instrument_manager] Type error when uploading/installing an instrument

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4522]
When uploading the `test_all_fields.linst` file, a TypeError occurred and the module crashed.

This bug only occurs when the the Certification config setting is used.

Stack trace:
> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Utility::associativeToNumericArray() must be of the type array, string given, called in /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc on line 872 and defined in /var/www/loris/php/libraries/Utility.class.inc:431\nStack trace:\n#0 /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc(872): Utility::associativeToNumericArray('\\n              ...')\n#1 /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc(921): NDB_BVL_Instrument->_getCertificationConfig()\n#2 /var/www/loris/php/libraries/NDB_BVL_Instrument_LINST.class.inc(95): NDB_BVL_Instrument->_getExaminerNames()\n#3 /var/www/loris/php/libraries/NDB_BVL_Instrument_LINST.class.inc(476): Loris\\Behavioural\\NDB_BVL_Instrument_LINST->_addMetadataFields()\n#4 /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc(240): Loris\\Behavioural\\NDB_BVL_Instrument_LINST->loadInstrumentFile('/var/www/loris/...')\n#5 /var/www/loris/modules/instrument_manager/php/instrument_manager.class.inc(215): NDB_BVL_Instrument::fa in /var/www/loris/php/libraries/Utility.class.inc on line 431, referer: https://jsaigle-dev.loris.ca/instrument_manager/

**Comment by zaliqarosli** [comment]
PR merged
