### ISSUE TITLE
[instrument_manager] Upload fails due to `Loris/Http/Response` not being found

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4525]
Generic `\Loris\Http\Response` must be changed to use a 409 conflict response.

Stack Trace
> PHP Fatal error:  Uncaught Error: Class 'Loris\\Http\\Response' not found in /var/www/loris/modules/instrument_manager/php/instrument_manager.class.inc:172\nStack trace:\n#0 /var/www/loris/modules/instrument_manager/php/instrument_manager.class.inc(102): LORIS\\instrument_manager\\Instrument_Manager->handlePOST(Object(Zend\\Diactoros\\ServerRequest))\n#1 /var/www/loris/php/libraries/NDB_Page.class.inc(649): LORIS\\instrument_manager\\Instrument_Manager->handle(Object(Zend\\Diactoros\\ServerRequest))\n#2 /var/www/loris/php/libraries/Module.class.inc(341): NDB_Page->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\instrument_manager\\Instrument_Manager))\n#3 /var/www/loris/src/Middleware/ResponseGenerator.php(49): Module->handle(Object(Zend\\Diactoros\\ServerRequest))\n#4 /var/www/loris/src/Middleware/AuthMiddleware.php(62): LORIS\\Middleware\\ResponseGenerator->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\instrument_manager\\Module))\n#5 /var/www/loris/src/Router/ModuleRouter.php(97): LORIS\\Middleware\\AuthMiddleware->process(O in /var/www/loris/modules/instrument_manager/php/instrument_manager.class.inc on line 172, referer: https://jsaigle-dev.loris.ca/instrument_manager/

**Comment by zaliqarosli** [comment]
PR merged
