### ISSUE TITLE
[Timepoint List] Update Testplan item 2. i.

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#4529]
Once issue #4518 is addressed, the testplan for timepoint list should be updated. 

Item 2. i. should be changed
FROM:
'For a candidate of a different site than your user, ensure that the only button available is "View Imaging datasets".'
TO:
'For a candidate of a different site than your user, attempt to access the timepoint list via the url. The page should load with a message of 'Permission Denied' which redirects the user back to the homepage.

**Comment by driusan** [comment]
Fixed by #4676
