### ISSUE TITLE
[user_accounts + my_preferences] bug with submission of reset field

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#4530]
this bug is is being reported for both `user_accounts` and `my_preferences`.

To reproduce the error:
1. Delete an entry for a required field (example: first name, last name, email, etc) and then submit --> you should get an error (this is expected).
2. Click `Reset` and try submitting the form again.

You should now see an error saying that the field is required (even though it is filled in).

**Comment by ridz1208** [comment]
removed from 21 as this is very low priority for now

**Comment by sruthymathew123** [comment]
Couldn't reproduce the error; so closing the issue.
