### ISSUE TITLE
[survey_accounts] Unable to fillout any surveys in survey accounts

### ISSUE THREAD

**Issue by sruthymathew123** [aces/Loris#4534]
[Tested on test.loris.ca](https://test.loris.ca/)

On clicking save and continue on first page of the instrument; it is giving me error;
"Attempt to use pselectRow on a query that returns multiple rows"
This is happening only when trying to fill instrument in survey mode (Instrument is  working as expected in the data entry mode)

**Comment by driusan** [comment]
Fixedby #4648
