### ISSUE TITLE
[Candidate List] Advanced filters are not expanded on refresh when an advanced filter is set

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4540]
[TestPlan](https://github.com/aces/Loris/blob/minor/modules/candidate_list/test/TestPlan.md) 6. Verify advanced filters are expanded on page load when an advanced filter is set, and collapsed otherwise.

Problem: When one advanced filter is selected, the advanced filter section is still collapsed when refresh the page or returning to the page from another page.

**Comment by kongtiaowang** [comment]
@coreyAbout We need to update this test plan after this module reactified.

**Comment by kongtiaowang** [comment]
https://github.com/aces/Loris/pull/4636

**Comment by HenriRabalais** [comment]
PR Sent to resolve this issue by introducing a query param that tracks the advanced filter.
#4650

**Comment by zaliqarosli** [comment]
@coreyAbout @kongtiaowang @HenriRabalais i can't figure it out .. is this issue fixed now?

**Comment by kongtiaowang** [comment]
@zaliqarosli It has been fixed.
