### ISSUE TITLE
[data integrity flag] can't filter for user other than admin

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#4542]

**Comment by zaliqarosli** [comment]
https://github.com/aces/Loris/issues/4542

**Comment by jesscall** [comment]
Instrument does not appear in table 
![image](https://user-images.githubusercontent.com/34260251/58193356-cb552300-7c90-11e9-93dc-370a5d7a95a8.png)

**Comment by zaliqarosli** [comment]
@jesscall even after running ‘make’?

**Comment by zaliqarosli** [comment]
PR merged
