### ISSUE TITLE
[Dicom Archive] Clicking on Acquisition ID does not show violated scans.

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#4549]
I'm not sure if this is because there aren't any violated scans, but when click on the Acquisition ID, nothing happens. Item 7 of the test plan seems to imply something should:

`Under 'View Details' Click on 'Acquisition ID' to view the violated scans (if there are any) if permission 'Violated Scans: View all-sites Violated Scans' is granted [Manual Testing]`

If nothing is supposed to happen when clicking on the link, then it shouldn't be a hyperlink.

**Comment by ridz1208** [comment]
@nicolasbrossard is this issue resolved ?

**Comment by nicolasbrossard** [comment]
I issued PR #4637 for this. Who should confirm that the fix works? Henri or me?

**Comment by jftunteng** [comment]
@HenriRabalais closing this issue since the PR is merged. Feel free to reopen if this is still an issue or if it reoccurs.
