### ISSUE TITLE
[statistics] update TestPlan to hint the useProject Config setting 

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4550]
[TestPlan](https://github.com/aces/Loris/blob/minor/modules/statistics/test/TestPlan.md#behavioural-statistics) 1. Click on the Behavioural Statistics tab. Try using the project filter Data Entry Statistics table. Does it work? Does it change what appears in both the top table and bottom table?

Problem:
Cannot find project filter under Behavioural Statistics tab

**Comment by ridz1208** [comment]
did you enable useProjects in the configuration module ?

**Comment by coreyAbout** [comment]
Now I've checked the use project option and tested it. I think a hint should be added to this test point.

**Comment by ridz1208** [comment]
rejected, useprojects has been removed entirely
