### ISSUE TITLE
[Dicom Archive] Clicking on 'View Details' Returns Error.

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#4553]
Item 5 of the Test Plan:
`Click on 'View Details' under Metadata to view the Details of MRI Scan [Manual Testing]`

When clicking on 'View Details' of some of the rows of the datatable, it leads to a `500` error. This possibly occurs when there is no imaging data for that specific row. Regardles, it should not be returning a `500` error with a blank page. The user should be warned when there are no details to be viewed, or the 'View Details' button should not be accessible.

**Comment by ridz1208** [comment]
@nicolasbrossard please add the Pr sent label when you fix an issue

thx

**Comment by zaliqarosli** [comment]
PR merged
