### ISSUE TITLE
[Dicom Archive] The regex for `Patient Name` is not working.

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#4554]
Item 7 of the test plan:
`Make sure that the value of 'Patient ID' column is 'INVALID-HIDDEN' if the PatientID does not match the regex set in the Configuration module under the 'Imaging Modules' submenu. Repeat the same operation for 'Patient Name' [Manual Testing]`

Currently the regex check works for PatientID. However, it does not work for 'Patient Name'.

**Comment by driusan** [comment]
I think the testplan might be poorly worded.. there are 2 regexes, one for PatientID and one for PatientName. Did you change them both or just one?

**Comment by HenriRabalais** [comment]
I changed it for both! When I changed the regex for PatientID, the display value for PatientID became 'INVALID-HIDDEN'. However, when I changed the regex for Patient Name, the display value for Patient Name remained the same.

**Comment by nicolasbrossard** [comment]
I think there are no bugs here. The regex actually specifies the pattern that the field has to match in order to be displayed. If it does not match the regex, then 'INVALID - HIDDEN' will be displayed instead of the real value. I tested the behaviour on the test VM and LGTM.

**Comment by ridz1208** [comment]
@HenriRabalais helo ?

**Comment by HenriRabalais** [comment]
@nicolasbrossard sounds good!
