### ISSUE TITLE
[Dicom Archive] Clicking on the Archive Location link always results in a 404

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#4556]
Testplan item 11:
`Ensure that clicking on any row in the 'Archive Location' column triggers a download of the corresponding archived DICOM study. Make sure that the copy of the file downloaded to your system is prepended with the Patient Name field. [Manual Testing]`

When testing the module, clicking on a `Archive Location` hyperlink with real imaging data at that location downloaded the file WITHOUT the patient name prepended, as stipulated by the test plan.

**Comment by johnsaigle** [comment]
Is there imaging data installed at that path on that server? This may be working correctly.

**Comment by HenriRabalais** [comment]
After testing this again while making sure that the imaging data existed, it downloads the file but does not prepend the patient name, as stipulated by the testplan item. I will update the issue to reflect this.

**Comment by nicolasbrossard** [comment]
Make sure that the file exists __and__ that the config setting 'Path to Tarchives' (Imaging Pipeline section) is set.

**Comment by ridz1208** [comment]
@nicolasbrossard is this issue resolved

**Comment by nicolasbrossard** [comment]
PR #4651 issued for this. Who should confirm that the fix works? Henri or me?

**Comment by nicolasbrossard** [comment]
Closing issue as PR was merged (and most likely tested).
