### ISSUE TITLE
[Configuration] Buttons are not aligned with text field

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4557]
![Screenshot from 2019-05-13 15-38-08](https://user-images.githubusercontent.com/4022790/57649045-3322b400-7595-11e9-8486-2efa2a287d35.png)

**Comment by driusan** [comment]
@zaliqarosli is this the same issue as #4506 ? (If so, can you test #4507 @johnsaigle?)

**Comment by zaliqarosli** [comment]
PR https://github.com/aces/Loris/pull/4507

**Comment by zaliqarosli** [comment]
fixed!
