### ISSUE TITLE
[Dicom Archive] When File Does Not Exist, The User Is Not Told

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#4558]
Item #11 of the Test Plan:
`Ensure that clicking on any row in the 'Archive Location' column triggers a download of the corresponding archived DICOM study. Make sure that the copy of the file downloaded to your system is prepended with the Patient Name field. [Manual Testing]`

When a file does not exist and the user attempts to download it, they are led to a blank page and are not told that the file could not be found. Ideally, files that do not exist should not be hyperlinked, or the user should be warned after click on the link that the file could not be found.

**Comment by nicolasbrossard** [comment]
When I tested this on the test VM for a file that does not exist, I get an HTTP 404 error page (not a blank page). I agree that if the file does not exist it should not be clickable but there could technically be other reasons why the file cannot be downloaded (permission issues, file size limit, possible others...) So instead of checking all things that could go wrong, I'd be in favour of displaying the 404 page. I __am__ open to discussions though. @HenriRabalais Let me know what you think

**Comment by HenriRabalais** [comment]
@nicolasbrossard 
I completely agree! If the 404 page displays properly, and the user is told that the file cannot be found, then I think the bug can be resolved! 

For some reason I wasn't getting that error message displayed.

**Comment by maltheism** [comment]
@HenriRabalais @nicolasbrossard I'm not getting the 404 page displayed on my workstation either. I'm just seeing a white page after clicking on one of the files.

**Comment by nicolasbrossard** [comment]
@maltheism what do you get when you click on archive 2009/DCM_2009-06-09_ImagingUpload-14-14-qM69wJ.tar?

**Comment by maltheism** [comment]
@nicolasbrossard On safari & firefox I'm getting a white page. On Chrome: The page can't be found with an no webpage was found for the webaddress that shows http://localhost/mri/jiv/get_file.php?file=2009/DCM_2009-06-09_ImagingUpload-14-14-qM69wJ.tar. and then it say's Search Google for localhost mri jiv get file.

**Comment by coreyAbout** [comment]
This problem still exist as of Test round 2.

TestPlan Item 11. `Ensure that clicking on any row in the 'Archive Location' column triggers a download of the corresponding archived DICOM study. Make sure that the copy of the file downloaded to your system is prepended with the Patient Name field. [Manual Testing]`

Problem:
Click on record MTL022_300022_V1 lead to error:
`This test.loris.ca page can’t be found No web page was found for the web address: https://test.loris.ca/mri/jiv/get_file.php?file=2009/DCM_2009-06-09_ImagingUpload-14-14-qM69wJ.tar&patientName=MTL022_300022_V1
HTTP ERROR 404`

**Comment by johnsaigle** [comment]
This seems like a Test VM issue. Now that Raisinbread contains MRI files to be downloaded the test VM seems to download these files without issue.

This issue could still occur if a file is deleted from the back-end without the DB table being updated. In this case a decorated 404 page should be displayed.

**Comment by johnsaigle** [comment]
I can't replicate test this on my VM. 

The files are stored on a read-only filesystem and I don't believe my user account has permission to change this.

**Comment by cmadjar** [comment]
@johnsaigle I guess if you change the path in the config module to a different path than /data-raisinbread/ for the image path, that should replicate the tarchive files not being found. A bit hacky but as long as it works.

**Comment by johnsaigle** [comment]
True, I'll try that

**Comment by johnsaigle** [comment]
This should be addressed by #6076

**Comment by johnsaigle** [comment]
The crashing should be resolved by #6076 but I have not actually done the verification I said I would earlier... I hope to get to it after the release.
