### ISSUE TITLE
[statistics] back end database access for testing and testing tools

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4560]
[TestPlan](https://github.com/aces/Loris/blob/minor/modules/statistics/test/TestPlan.md)

Demographic Statistics
`1. Click on the Demographic Statistics tab. For the general statistics table, compare the data in the table to that in the database to ensure that it is being queried correctly.`
`4. For the sex breakdown:
compare the data in the table to that in the database to ensure that it is being queried correctly.`

Behavioural Statistics
`2. For both tables:
check that the data in the table matches what is stored in the database.`
`4. After following this link, check that the incomplete candidates are correct in comparison to the incomplete forms in the database.`
`9. After following this link, check that the candidates requiring double data entry are correct in comparison to the forms requiring double data entry in the database.`

Problem:
1. Cannot access to back end database.
2. The table names to look into and compared to need to be specified (to be beginner friendly).
3. Proper tools to acquire corresponding data from the database corresponding to the front end tables in a format that looks the same will greatly facilitate the comparison, otherwise it takes a long time to compare them.

**Comment by johnsaigle** [comment]
I think this might be something that the projects should test... as Corey mentioned we don't have access to the test VM data. My sandbox also doesn't have sufficient data for testing.

**Comment by driusan** [comment]
I believe the data on the test VM is supposed to be the raisinbread dataset. @ridz1208 can you confirm?

**Comment by ridz1208** [comment]
@driusan @johnsaigle @coreyAbout I confirm, sourcing RB on your VM should fix this issue for you, please close this ticket when you have successfully done so

**Comment by kchatpar** [comment]
@ridz1208 When comparing the backend to the frontend for the demographic tab in the statistics module. What defines a registered candidate? On the frontend, I'm seeing 326 candidates for Rome and on the backend 328 candidates.

**Comment by ridz1208** [comment]
@kchatpar your best bet to understand that is to look at the queries in the module. we should maybe add some documentation for it but for now the only place the info is available is in the query itself.

**Comment by ridz1208** [comment]
closing this issue as its no longer relevant
