### ISSUE TITLE
Email broken on Test VM until latest changes from major are merged

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4561]
The test VM seems to be missing a [bugfix](https://github.com/aces/Loris/pull/4331/files#diff-afc080cfab0a9186d9fd2cfb4f51aa5eR78) without which all emails seem to fail (see discussion in #4513)

This has resulted in several with release testing.

**Comment by kongtiaowang** [comment]
[[ Loris should send emails as "noreply@loris.ca".  If you use a gmail address, the email will not be able to be sent. ]] From Pam. 
you can test mail function on your own VM.

**Comment by johnsaigle** [comment]
That is also true (and we should check that the test VM uses that email) but I don't think that's the problem here.

The problem that most people are having is LORIS giving a blank page/500 error when using any kind of email functionality. This is caused by an old bug that was fixed in the above PR (#4331). This fix needs to be merged into the test.loris.ca VM or else many modules can't be properly tested on that VM.

Yes people can use their own workstations but this is a simple fix on the test VM so we might as well do it.

**Comment by kongtiaowang** [comment]
I will update the test.loris.ca with the bugfix.
