### ISSUE TITLE
[next_stage] test battery does not populate

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#4563]
Test battery does not populate when starting next stage.

**Comment by driusan** [comment]
Is the test battery set up properly on the VM that you're testing on?

**Comment by ridz1208** [comment]
it is. there seems to be an issue with the lookup function

**Comment by jesscall** [comment]
Here is the test_battery that is currently on the test VM: 
[test_battery](https://github.com/aces/Loris/files/3178148/-.txt)

I quickly looked into the issue last night, and Rida is right. It's an issue with the lookup function. 
It seems that the age variable being passed is empty and thus the query returns nothing. This is the case for `lookupBattery` and `selectBattery` (as far as I can tell). I'll be looking into this further at some point today.
