### ISSUE TITLE
[New Profile] YMd vs YM

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#4564]
Point 7 from the test plan, there are no differences in the questions when you change the DoB from YM YMd.

**Comment by kongtiaowang** [comment]
@charliehenrib 
Since the DoB column is defined as Date type in the table, YM is not working for this case. I will update the TestPlan.

**Comment by zaliqarosli** [comment]
this PR https://github.com/aces/Loris/pull/4729 makes it so that YMd vs YM matters. There is discussion surrounding the inability of Firefox to render a date picker for when date format is YM i.e. input type='month'

**Comment by zaliqarosli** [comment]
update: #4729 fully fixes this issue

**Comment by driusan** [comment]
Fixed by above PR

**Comment by cmadjar** [comment]
Closing the issue as fixed by the above PR.
