### ISSUE TITLE
[new profile] no error thrown when user generated PSCID does not respect expected format

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#4567]
If the configuration for PSCID generation in the config.xml file is set to `user`, and you try to input an incorrect PSCId, no error is returned to the user, a 500 error is thrown in the backend only

**Comment by ridz1208** [comment]
Several issues are happening here 
 1. The validation function from before the reactification was removed ! so there is currently only front end validation and that should not be the case (see #4088)
 2. There is no PSCID validation for when the `user` generation method is used
 3. errors returned from the backend when `user` PSCID generation is used appear as 500 errors in the console and are not returned in an alert message on the front end

Issues 1 and 3 above are necessary, Issue 2 is ideal but not critical for the release

**Comment by ridz1208** [comment]
Also, the test plan should probably be amended to include an item to test the backend validation independently from the front end

**Comment by driusan** [comment]
Added the Critical tag because of the lack of backend validation

**Comment by zaliqarosli** [comment]
new PR https://github.com/aces/Loris/pull/4834

**Comment by cmadjar** [comment]
Fixed by the above PR so closing the issue
