### ISSUE TITLE
[Imaging Uploader] - Incorrect 'Fields do not match filename' error message

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#4568]
I tried uploading a file named 'MTL001_300001_V2.txt' and setting Candid to '300001', PSCID to 'MTL001' and visit label to 'V2'. I got an error message saying 'Fields do not match filename' even though they do match. I should have gotten a message indicating that the file type (.txt) is incorrect.

**Comment by jesscall** [comment]
I also get this error

**Comment by driusan** [comment]
Fixed by above PR
