### ISSUE TITLE
[Imaging Uploader] - Incorrect behaviour when uploading a huge file 

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#4569]
The file size limit for file uploads has been set to 2Mb on the testing VM. I tried uploading a 1Gb file and I got the 'Submission error' popup, but there was no indication of what went wrong. When I clicked on the popup to dismiss it, the popup disappeared but the imaging uploader froze afterwards and the upload tab became unusable.

**Comment by jesscall** [comment]
Not able to recreate the issue. 
I get the proper error message, as follows:
(using max upload size of 1MB, and uploading a file that is 65.5MB)

<img width="999" alt="Screen Shot 2019-05-29 at 12 02 48 PM" src="https://user-images.githubusercontent.com/34260251/58572578-ed5b2200-8209-11e9-9e8e-7cc1a4fd71a0.png">

**Comment by driusan** [comment]
@nicolasbrossard what browser? Is it the same one as @jesscall?

**Comment by jesscall** [comment]
I was on Chrome Version 74.0.3729.169

**Comment by nicolasbrossard** [comment]
I was on Chrome also.

**Comment by cmadjar** [comment]
@nicolasbrossard I was not able either to reproduce your error as I got red box around the filename with a proper error message.

However, in the PR https://github.com/aces/Loris/pull/4796, I added the error message in the pop up window with Submission Error label so that it displays the correct error below the title. Let me know if that works for you.

**Comment by nicolasbrossard** [comment]
@jesscall @cmadjar I tried again on test.loris.ca and I get a submission error popup but no indication of what went wrong...I can dismiss the popup and continue using the upload tab though (progress is frozen at 16%). I am using Chrome 74.0.3729.169

**Comment by driusan** [comment]
@kongtiaowang is test.loris.ca updated with the most recent version of 21.0-release?

**Comment by jesscall** [comment]
On test.loris.ca I get the same behaviour as @nicolasbrossard 's most recent comment.
Upload size of 5.3G
I get pop-up indicating a submission error. Upon dismissal, the progress bar is stuck at 16%.

**Comment by driusan** [comment]
Should be fixed by #4569, can @jesscall or @nicolasbrossard confirm and close if applicable?

**Comment by cmadjar** [comment]
I retested this on the latest 21.0 code and it works so closing this issue.
