### ISSUE TITLE
[media] can't specify the name of the file

### ISSUE THREAD

**Issue by PapillonMcGill** [aces/Loris#4570]
After selecting a media file to upload (PDF or TXT), it is impossible to set the name to which upload the file.

Can select part of the (copied) filename with the mouse but keyboard input are just ignore thus can't properly rename the file

**Comment by HenriRabalais** [comment]
@PapillonMcGill I think by design the file can't be renamed on the LORIS interface, it takes the file name of the uploaded file. The ability to change the file name once uploaded seems more like a feature.

**Comment by driusan** [comment]
You've never been able to rename files or specify it in the media module frontend. The filenames need to be named as described in the instructions on top of the page before uploading.
