### ISSUE TITLE
[media] csv file not filtered

### ISSUE THREAD

**Issue by PapillonMcGill** [aces/Loris#4574]
When downloading the (uploaded files) table as a CSV, all the files are there, the filters that was applied do not reflect in the CSV file

**Comment by johnsaigle** [comment]
I think this is true of all CSV files? @Jkat I feel like this is what we experienced when doing the Open PREVENT-AD stuff and all of our extra query fields were included in the CSV.

See also https://github.com/Jkat/Loris/pull/21

Other people probably know better than me whether other CSV downloads work this way.

**Comment by driusan** [comment]
As @johnsaigle says, I think that's the behaviour of all CSV files in all filters in LORIS. Is there a test plan that's incorrectly saying the behaviour is otherwise?

**Comment by PapillonMcGill** [comment]
@driusan No, I didn't saw anything like that in the test plan. I just tried every possible thing (as much as I could) with the `limit test case` in mind. Will close this issues as it is more a feature than an bug.
