### ISSUE TITLE
[API] Warning: session_cache_limiter(): Cannot change cache limiter when session is active

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#4576]
The LORIS API displays a warning when calling the localhost/api/v0.0.3-dev/candidates

The warning:
Warning: session_cache_limiter(): Cannot change cache limiter when session is active in /Users/alizee/Development/GitHub/McGill/Loris/htdocs/api/v0.0.3-dev/APIBase.php on line 130

```
Call Stack
--

1 | 0.0013 | 399280 | {main}( ) | .../Candidates.php:0
2 | 0.0019 | 412376 | Loris\API\Candidates->__construct( ) | .../Candidates.php:258
3 | 0.0019 | 412376 | Loris\API\Candidates->__construct( ) | .../Candidates.php:44
4 | 0.0073 | 599368 | Loris\API\Candidates->handleRequest( ) | .../APIBase.php:87
5 | 0.0073 | 599368 | Loris\API\Candidates->handleETag( ) | .../APIBase.php:103
6 | 0.0073 | 599368 | session_cache_limiter ( ) | .../APIBase.php:130
```

https://github.com/aces/Loris/projects/19#card-21297183

**Comment by jftunteng** [comment]
@maltheism closing this issue since the PR is merged. Please reopen if this is still an issue or if it reoccurs.
