### ISSUE TITLE
[Issue Tracker] Unable to filter by the "Date Created" filter

### ISSUE THREAD

**Issue by Jkat** [aces/Loris#4583]
I'm not sure there's currently any proper implementation of a date filter in any module though.

**Comment by HenriRabalais** [comment]
@zaliqarosli 
@ridz1208 and @driusan are assigning people to testing bugs.

**Comment by zaliqarosli** [comment]
@HenriRabalais i know! i was just letting you know which other issues were open for the issue tracker in case you hadn't seen them and wanted to fix them too!

**Comment by ridz1208** [comment]
@maltheism can you take care of this one ?

**Comment by zaliqarosli** [comment]
this is because column header and row data are mismatched

<img width="561" alt="Screenshot 2019-05-28 19 00 48" src="https://user-images.githubusercontent.com/17415878/58518461-4b8df380-817d-11e9-90ce-cc6dc145ce9e.png">

**Comment by driusan** [comment]
@zaliqarosli's header issue is also reported as #4762

**Comment by zaliqarosli** [comment]
closing this issue so https://github.com/aces/Loris/issues/4762 can deal with header misalignment
