### ISSUE TITLE
Timepoint_list typing error when trying to access module

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#4585]
Only happens on a subset of candidates i.e. DCC090 after having completed all the instruments in V1

> [Tue May 14 15:17:56.435449 2019] [php7:error] [pid 28062] [client 132.216.56.251:53587] PHP Fatal error:  Uncaught TypeError: Return value of TimePoint::getApprovalStatus() must be of the type string, null returned in /var/www/loris/php/libraries/TimePoint.class.inc:495\nStack trace:\n#0 /var/www/loris/php/libraries/TimePoint.class.inc(618): TimePoint->getApprovalStatus()\n#1 /var/www/loris/modules/timepoint_list/php/timepoint_list.class.inc(146): TimePoint->getCurrentStatus()\n#2 /var/www/loris/php/libraries/NDB_Page.class.inc(668): LORIS\\timepoint_list\\Timepoint_List->setup()\n#3 /var/www/loris/src/Middleware/UserPageDecorationMiddleware.php(171): NDB_Page->handle(Object(Zend\\Diactoros\\ServerRequest))\n#4 /var/www/loris/src/Middleware/PageDecorationMiddleware.php(49): LORIS\\Middleware\\UserPageDecorationMiddleware->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\timepoint_list\\Timepoint_List))\n#5 /var/www/loris/php/libraries/NDB_Page.class.inc(653): LORIS\\Middleware\\PageDecorationMiddleware->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\timepoint_list\\Timepoint_List))\n#6 /var/www/loris/modules/ in /var/www/loris/php/libraries/TimePoint.class.inc on line 495, referer: https://test.loris.ca//candidate_list

**Comment by johnsaigle** [comment]
> Return value of TimePoint::getApprovalStatus() must be of the type string, null

Is this maybe an issue with the data? Does it make sense for Approval status to be `null`?

**Comment by ridz1208** [comment]
@johnsaigle the approval status is null up until a specific visit is "approved" as in it's last stage

**Comment by johnsaigle** [comment]
OK well the easy fix is to make the function signature nullable if that's a valid scenario. 

I'll make a PR to do this and request your review.

**Comment by johnsaigle** [comment]
Hm the function comment says it should be "'In Progress', 'Pass' or 'Failure'"... we can still make it nullable but it sounds like it maybe shouldn't be?

What do you want to do?

**Comment by ridz1208** [comment]
100% it's always null untill the visit stage is passed. then it takes one of these values

**Comment by driusan** [comment]
Resolved by #4621
