### ISSUE TITLE
[bvl_feedback] Amend test plan

### ISSUE THREAD

**Issue by leighevans** [aces/Loris#4586]
There is an error in the test plan for bvl feedback. "**Threads should be the thread number**" accidentally contains markdown header formatting and should be fixed to be regular text. 
![Screen Shot 2019-05-14 at 3 50 57 PM](https://user-images.githubusercontent.com/32552953/57727748-43539580-7660-11e9-8313-d50228b50451.png)

**Comment by driusan** [comment]
Fixed by above PR
