### ISSUE TITLE
[Publications] Main data table columns not populating

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#4594]
https://test.loris.ca/publication/#browse
- [ ] The last 5 columns the main data table do not populate properly
starting with column: `Description`... `Keywords`...

**Comment by maltheism** [comment]
Hi @christinerogers, when looking at the code it seems those columns are added to the hiddenHeaders and making them not display. Are those columns supposed to be shown and not be hidden?
@driusan @ridz1208

**Comment by christinerogers** [comment]
Thanks @maltheism that's v helpful -- hard to know the intention since David Blader made the module and we're missing him.  
If they're not being hidden properly that's great.  
Do you remember the code line you looked at, as a point of departure for more bug-fixing here? 

cc @nicolasbrossard

**Comment by christinerogers** [comment]
On the Test VM this is no longer an issue, it seems.  
Will close this issue, and re-open if it recurs.
