### ISSUE TITLE
[SQL] inexistant instruction in MySQL

### ISSUE THREAD

**Issue by PapillonMcGill** [aces/Loris#4595]
in script 2019-05-03-deprecate_useprojects.sql, there is a clause `WHERE NOT EXISTS` that is non-existant in MySQL

**Comment by driusan** [comment]
This doesn't make sense. `WHERE (NOT) EXISTS` is completely standard SQL going at least as far back as SQL92. The oldest MySQL documentation that I can find on their website supports it: https://dev.mysql.com/doc/refman/5.5/en/exists-and-not-exists-subqueries.html as well as the newest version: https://dev.mysql.com/doc/refman/8.0/en/exists-and-not-exists-subqueries.html and

**Comment by PapillonMcGill** [comment]
@driusan Have you tried it with an INSERT?  it is Ok with SELECT, but fail with INSERT (at least in my VM MySQL 5.5)

**Comment by driusan** [comment]
Subqueries and WHERE clauses syntax do not change between SELECTs and INSERTs. If you're trying it and it's failing, there's some reason other than the `WHERE NOT EXISTS`. We shouldn't be changing patches from ANSI standard SQL92 to MySQL-only language extensions (INSERT IGNORE) because of invalid assumptions.

**Comment by ridz1208** [comment]
@PapillonMcGill can you post the error message here ?

**Comment by PapillonMcGill** [comment]
@ridz1208 mysql> INSERT INTO Project (Name) SELECT 'loris' WHERE NOT EXISTS (SELECT * FROM Project);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT * FROM Project)' at line 1

@driusan 
from MySQL doc https://dev.mysql.com/doc/refman/5.5/en/exists-and-not-exists-subqueries.html:
SELECT column1 FROM t1 WHERE EXISTS (SELECT * FROM t2);

from Mariadb  https://mariadb.com/kb/en/library/subqueries-and-exists/ :1234: 
Syntax

SELECT ... WHERE EXISTS <Table subquery>

In this case, it is not available with an INSERT statement

**Comment by driusan** [comment]
The `WHERE` isn't  in any insert statement at all. The `WHERE` clause is part of the SELECT statement part of `INSERT .... SELECT`. MySQL doesn't have 2 separate query parsers that arbitrarily throw away part of the SQL standard if the SELECT is in a subselect that happens to be executed as part of a parent INSERT statement.

If you run the `SELECT` part of the statement on its own you'll get the exact same error. If you change it to `WHERE 1=1` you get an error about invalid syntax near "WHERE 1=1". Does MySQL also not support the `=` operator in WHERE clauses, but only for insert statements? (One way to test that might be to run the SELECT part of it with `WHERE 1=1` as the condition outside of an insert statement and see what happens.)

**Comment by jftunteng** [comment]
@PapillonMcGill closing this issue since the PR is merged. Feel free to reopen if this is still an issue.
