### ISSUE TITLE
[instrument_builder] Load Tab UI is not aligned

### ISSUE THREAD

**Issue by atspahr** [aces/Loris#4606]
The Browse button and the folder path text box is not aligned properly on Chrome browser

**Comment by johnsaigle** [comment]
I believe this was fixed by #4506. Can you confirm whether this issue exists on the latest version of `aces/21.0-release`? The button is aligned for me on this branch.

**Comment by atspahr** [comment]
@zaliqarosli  do I need to do anything special to get on the latest version of aces/21.0-release? I'm using the testing VM and it's showing me this.

![image](https://user-images.githubusercontent.com/48061979/57803611-d5be6c80-7726-11e9-8320-6ae5c47bf182.png)

**Comment by zaliqarosli** [comment]
@atspahr no thats okay, i can close this issue for you if it has in fact been fixed (which I think it has)

**Comment by zaliqarosli** [comment]
fixed by #4507
