### ISSUE TITLE
[instrument_builder] Clicking "Edit" on a Header crashes the system

### ISSUE THREAD

**Issue by atspahr** [aces/Loris#4608]
This only works if you save an instrument and then load it back in to re-edit it.

![image](https://user-images.githubusercontent.com/48061979/57785516-e6a7b780-76ff-11e9-9e9d-66e4fab19446.png)

**Comment by atspahr** [comment]
This also happens when trying to edit "Scored Field"

![image](https://user-images.githubusercontent.com/48061979/57785709-40a87d00-7700-11e9-814a-962fac342922.png)

**Comment by atspahr** [comment]
This also happens when trying to edit "Label"

![image](https://user-images.githubusercontent.com/48061979/57785805-69307700-7700-11e9-9c6e-f2dfd28c2a32.png)

**Comment by atspahr** [comment]
Same thing happens on Microsoft Edge browser

![image](https://user-images.githubusercontent.com/48061979/57786660-e6102080-7701-11e9-91e7-ab137b0d27ff.png)

**Comment by driusan** [comment]
Resolved by #4652
