### ISSUE TITLE
[Acknowledgements] Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#4611]
https://github.com/aces/Loris/projects/19#card-21438166
The FilteredDataTable needs to be fixed for changing Maximum rows to display for the table.

Error:
`Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.`

**Comment by zaliqarosli** [comment]
PR merged
