### ISSUE TITLE
Issue Tracker PR breaks 21.0-release

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#4626]
#4112 changed things that it shouldn't have on `21.0-release`, causing errors that don't currently exist on test.loris.ca

1. Fix DataTable UI @zaliqarosli https://github.com/aces/Loris/pull/4629 - merged
2. Fix pagination functionality @HenriRabalais https://github.com/aces/Loris/pull/4632 - merged
3. Fix maximum number of rows option error @maltheism https://github.com/aces/Loris/pull/4612 - merged

**Comment by HenriRabalais** [comment]
Pagination Bug Fix PR has been merged #4632

**Comment by zaliqarosli** [comment]
all PRs merged
