### ISSUE TITLE
Quality control module does not load at all

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#4627]
> [Wed May 15 13:08:11.110209 2019] [php7:warn] [pid 13012] [client 132.216.56.93:39870] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'm.T1_Scan_done' in 'field list' in /var/www/loris/php/libraries/Database.class.inc on line 704, referer: https://test.loris.ca/quality_control/

> [Wed May 15 13:08:11.112575 2019] [php7:notice] [pid 13012] [client 132.216.56.93:39870] Could not execute SELECT PSCID, SessionID, cand_id, site, project, subproject, visit_label, scan_type, mri_parameter_form, scan_done, tarchive_loc, scan_location, qc_status, uploaded_by, selected, CommentID, TarchiveID FROM (  SELECT DISTINCT\n           c.PSCID,\n           s.ID as SessionID,\n           s.CandID as cand_id,\n           (SELECT name FROM psc WHERE CenterID=s.CenterID) as site,\n           s.Visit_label as visit_label,\n           't1' as scan_type,\n           t.TarchiveID as tarchiveID,\n           CASE\n              WHEN EXISTS(\n                  SELECT\n                      *\n                  FROM\n                      tarchive_series ts\n                  LEFT JOIN mri_protocol mp ON mp.Scan_type=44\n                  WHERE\n                      ts.TarchiveID = t.TarchiveID\n                      AND (ts.EchoTime BETWEEN mp.TE_min AND mp.TE_max)\n                      AND (ts.RepetitionTime BETWEEN mp.TR_min AND mp.TR_max) ) THEN 'In DICOM' ELSE 'Missing'\n           END as tarchive_loc,\n           (SELECT Name FROM Project WHERE ProjectID=c.ProjectID) as project, (SELECT title FROM subproject WHERE SubprojectID=s.SubprojectID)\n           as subproject, CASE\n              WHEN m.Data_entry_completion_status='Incomplete' THEN 'Incomplete'\n              ELSE 'Complete'\n           END AS mri_parameter_form,\n           CASE\n              WHEN m.T1_Scan_done IS NULL THEN ''\n              WHEN (m.T1_Scan_done = 'Complete'\n              OR m.T1_Scan_done = 'Partial') THEN 'Yes'\n              ELSE 'No'\n           END as scan_done,\n           CASE\n              WHEN (fi.fileID IS NULL AND mvl.PatientName IS NULL) THEN 'Missing'\n              WHEN fi.fileID IS NOT NULL THEN 'In Imaging Browser'\n              WHEN mvl.PatientName IS NOT NULL THEN 'In MRI Violated Scans'\n           END as scan_location,\n           CASE\n              WHEN qc.Selected = '' THEN 'False'\n              WHEN qc.Selected = 'true' THEN 'True'\n           END as selected,\n           qc.QCStatus as qc_status,\n           mu.uploadedBy as uploaded_by,\n           f.CommentID as CommentID  FROM flag f\n        JOIN session s ON (f.SessionID=s.ID)\n        JOIN candidate c ON (s.CandID=c.CandID)\n        LEFT JOIN mri_parameter_form m ON (m.CommentID=f.CommentID)\n        LEFT JOIN tarchive t ON (t.SessionID=s.ID)\n        LEFT JOIN files fi ON (fi.SessionID=s.ID AND\n        fi.AcquisitionProtocolID=44)\n        LEFT JOIN mri_violations_log mvl ON\n        (mvl.CandID = s.CandID AND mvl.Scan_type=44\n        AND mvl.PatientName LIKE CONCAT ('%', s.Visit_label,'%'))\n        LEFT JOIN files_qcstatus qc ON (qc.FileID = fi.FileID)\n        LEFT JOIN mri_upload mu ON (mu.SessionID = f.SessionID)  WHERE 1=1\n          AND NOT f.CommentID LIKE 'DDE%'\n          AND f.Test_name='mri_parameter_form'\n          AND c.Active='Y'\n          AND s.Active='Y'\n          AND s.CenterID <> '1' \n          UNION ALL\n           SELECT DISTINCT\n           c.PSCID,\n           s.ID as SessionID,\n           s.CandID as cand_id,\n           (SELECT name FROM psc WHERE CenterID=s.CenterID) as site,\n           s.Visit_label as visit_label,\n           't2' as scan_type,\n           t.TarchiveID as tarchiveID,\n           CASE\n              WHEN EXISTS(\n                  SELECT\n                      *\n                  FROM\n                      tarchive_series ts\n                  LEFT JOIN mri_protocol mp ON mp.Scan_type=45\n                  WHERE\n                      ts.TarchiveID = t.TarchiveID\n                      AND (ts.EchoTime BETWEEN mp.TE_min AND mp.TE_max)\n                      AND (ts.RepetitionTime BETWEEN mp.TR_min AND mp.TR_max) ) THEN 'In DICOM' ELSE 'Missing'\n           END as tarchive_loc,\n           (SELECT Name FROM Project WHERE ProjectID=c.ProjectID) as project, (SELECT title FROM subproject WHERE SubprojectID=s.SubprojectID)\n           as subproject, CASE\n              WHEN m.Data_entry_completion_status='Incomplete' THEN 'Incomplete'\n              ELSE 'Complete'\n           END AS mri_parameter_form,\n           CASE\n              WHEN m.t2_Scan_done IS NULL THEN ''\n              WHEN (m.t2_Scan_done = 'Complete'\n              OR m.t2_Scan_done = 'Partial') THEN 'Yes'\n              ELSE 'No'\n           END as scan_done,\n           CASE\n              WHEN (fi.fileID IS NULL AND mvl.PatientName IS NULL) THEN 'Missing'\n              WHEN fi.fileID IS NOT NULL THEN 'In Imaging Browser'\n              WHEN mvl.PatientName IS NOT NULL THEN 'In MRI Violated Scans'\n           END as scan_location,\n           CASE\n              WHEN qc.Selected = '' THEN 'False'\n              WHEN qc.Selected = 'true' THEN 'True'\n           END as selected,\n           qc.QCStatus as qc_status,\n           mu.uploadedBy as uploaded_by,\n           f.CommentID as CommentID  FROM flag f\n        JOIN session s ON (f.SessionID=s.ID)\n        JOIN candidate c ON (s.CandID=c.CandID)\n        LEFT JOIN mri_parameter_form m ON (m.CommentID=f.CommentID)\n        LEFT JOIN tarchive t ON (t.SessionID=s.ID)\n        LEFT JOIN files fi ON (fi.SessionID=s.ID AND\n        fi.AcquisitionProtocolID=45)\n        LEFT JOIN mri_violations_log mvl ON\n        (mvl.CandID = s.CandID AND mvl.Scan_type=45\n        AND mvl.PatientName LIKE CONCAT ('%', s.Visit_label,'%'))\n        LEFT JOIN files_qcstatus qc ON (qc.FileID = fi.FileID)\n        LEFT JOIN mri_upload mu ON (mu.SessionID = f.SessionID)  WHERE 1=1\n          AND NOT f.CommentID LIKE 'DDE%'\n          AND f.Test_name='mri_parameter_form'\n          AND c.Active='Y'\n          AND s.Active='Y'\n          AND s.CenterID <> '1'  ) as tmp GROUP BY PSCID,\n            SessionID,\n            cand_id,\n            site,\n            project,\n            subproject,\n            visit_label,\n            scan_type,\n            mri_parameter_form,\n            scan_done,\n            tarchive_loc,\n            scan_location,\n            qc_status,\n            selected,\n            uploaded_by,\n            CommentID,\n            TarchiveID   ORDER BY PSCID. Stack trace#0 /var/www/loris/php/libraries/Database.class.inc(739): Database->execute(Object(PDOStatement), Array)\n#1 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(846): Database->pselect('SELECT PSCID, S...', Array)\n#2 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(782): NDB_Menu_Filter->_getFullList()\n#3 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(811): NDB_Menu_Filter->toArray()\n#4 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(684): NDB_Menu_Filter->toJSON()\n#5 /var/www/loris/php/libraries/NDB_Page.class.inc(670): NDB_Menu_Filter->display()\n#6 /var/www/loris/php/libraries/NDB_Page.class.inc(649): NDB_Page->handle(Object(Zend\\Diactoros\\ServerRequest))\n#7 /var/www/loris/php/libraries/Module.class.inc(341): NDB_Page->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\quality_control\\Quality_Control))\n#8 /var/www/loris/src/Middleware/ResponseGenerator.php(49): Module->handle(Object(Zend\\Diactoros\\ServerRequest))\n#9 /var/www/loris/src/Middleware/AuthMiddleware.php(62): LORIS\\Middleware\\ResponseGenerator->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\quality_control\\Module))\n#10 /var/www/loris/src/Router/ModuleRouter.php(97): LORIS\\Middleware\\AuthMiddleware->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\quality_control\\Module))\n#11 /var/www/loris/src/Router/BaseRouter.php(99): LORIS\\Router\\ModuleRouter->handle(Object(Zend\\Diactoros\\ServerRequest))\n#12 /var/www/loris/src/Middleware/ResponseGenerator.php(49): LORIS\\Router\\BaseRouter->handle(Object(Zend\\Diactoros\\ServerRequest))\n#13 /var/www/loris/src/Middleware/ContentLength.php(51): LORIS\\Middleware\\ResponseGenerator->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\Router\\BaseRouter))\n#14 /var/www/loris/htdocs/index.php(48): LORIS\\Middleware\\ContentLength->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\Router\\BaseRouter))\n#15 {main}, referer: https:

> [Wed May 15 13:08:11.112888 2019] [php7:error] [pid 13012] [client 132.216.56.93:39870] PHP Fatal error:  Uncaught DatabaseException: Unknown column 'm.T1_Scan_done' in 'field list' in /var/www/loris/php/libraries/Database.class.inc:707\nStack trace:\n#0 /var/www/loris/php/libraries/Database.class.inc(739): Database->execute(Object(PDOStatement), Array)\n#1 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(846): Database->pselect('SELECT PSCID, S...', Array)\n#2 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(782): NDB_Menu_Filter->_getFullList()\n#3 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(811): NDB_Menu_Filter->toArray()\n#4 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(684): NDB_Menu_Filter->toJSON()\n#5 /var/www/loris/php/libraries/NDB_Page.class.inc(670): NDB_Menu_Filter->display()\n#6 /var/www/loris/php/libraries/NDB_Page.class.inc(649): NDB_Page->handle(Object(Zend\\Diactoros\\ServerRequest))\n#7 /var/www/loris/php/libraries/Module.class.inc(341): NDB_Page->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\quality_control\\Quality_Control))\n#8 /var/www/loris/src/Middleware/R in /var/www/loris/php/libraries/Database.class.inc on line 707, referer: https://test.loris.ca/quality_control/

**Comment by johnsaigle** [comment]
Seems related to #4545 as its issue is with the column `DTI_scan_done` not existing.

Were these columns changed recently?

**Comment by driusan** [comment]
I think the README for the module needs to be updated* to describe the requirements. As far as I know, it requires an mri_parameter_form instrument which includes an X_Scan_done for the scan types in the scan_type table (I haven't looked in the code to confirm, but that's what I remember of the design.. @llevitis might be able to shed some light.)

* It doesn't seem to exist at all, actually.
