### ISSUE TITLE
[RaisinBread] missing Config setting: EnvironmentFile

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#4630]
Issue with **RaisinBread** - 20.2 Config setting was missing on TestVM: 
- [ ] `EnvironmentFile` missing from [RB `ConfigSettings` table](https://github.com/aces/Loris/blob/major/raisinbread/RB_files/RB_ConfigSettings.sql#L91)
- [ ] insert statement missing from RB `Config` table for this ConfigSetting

The actual 20.2 release [Schema](https://github.com/aces/Loris/blob/major/SQL/0000-00-03-ConfigTables.sql#L153) and [Patch](https://github.com/aces/Loris/blob/major/SQL/Release_patches/20.1_To_20.2_upgrade.sql#L18) correctly added them, so it's **Not a 21.0 release issue**.

This was causing a 500 error on the Server Process Manager on Test VM. Nic fixed the TestVM (see below). 
**Do not run this on TestVM or RaisinBread**  Just manually edit RaisinBread's schema files for `ConfigSettings` and `Config` tables, or else the ConfigSettings will be out of order.
 
```mysql
INSERT INTO ConfigSettings
  (Name, Description, Visible, AllowMultiple, DataType, Parent, Label, OrderNumber)
  SELECT
    'EnvironmentFile',
    'Name of the environment file that need to be sourced for the imaging pipeline',

INSERT INTO Config
  (ConfigID, Value)
  SELECT ID, 'environment' FROM ConfigSettings cs WHERE cs.Name="EnvironmentFile";
```

**Comment by ridz1208** [comment]
Done
