### ISSUE TITLE
[Imaging Browser] Sequence type filter doesn't seem to work at all

### ISSUE THREAD

**Issue by irodriquez** [aces/Loris#4635]
when I select a sequence type, it does not show the sequence with the option selected, with the column Links. 

![test1](https://user-images.githubusercontent.com/50679442/57810562-aeb76900-772d-11e9-80dc-743174f13854.png)

![test2](https://user-images.githubusercontent.com/50679442/57810586-c7c01a00-772d-11e9-8f4c-b7e39bdf2c6b.png)

**Comment by driusan** [comment]
Fixed by above PR
