### ISSUE TITLE
[ImgBrowser] download dicom missing in ViewSession sidebar

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#4657]
In the sidebar of the View Session page within the Imaging Browser 
on the test VM 
There's no link/button to download the dicom archive package. 
This seems like a significant bug, probably a very minor issue at root.

[this is a placeholder ticket]

**Comment by kongtiaowang** [comment]
@christinerogers 
Please re-test the image data with visit_label  like V1, V2, V3. It is the testing set-up issue.

**Comment by christinerogers** [comment]
Hi Shen,  thanks - 
It works (sidebar Dicom download button + actual download) for:
* [OTT324 V1 ](https://test.loris.ca/imaging_browser/viewSession/?sessionID=324)

Dicom button and/or Download still broken for:
* MTL002 
* MTL0022 (V2, i think i tried)

**Comment by kongtiaowang** [comment]
@christinerogers On the testing VM, There are only 2 Dicom files in the " /data/loris-mri/data/tarchive".
MTL022_300022_V1
MTL135_300135_V1

**Comment by cmadjar** [comment]
I just tested this functionality on the new RB with proper imaging dataset and it works. Closing the ticket since the issue came from the dataset and not the code.
