### ISSUE TITLE
[issue_tracker] Notice: Undefined index: userID in issuewatchermapper.class.inc

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#4674]
Steps to reproduce: Install of LORIS and import RB. Visiting issue_tracker will result in the module not loading.

**Comment by driusan** [comment]
Why is a notice (a message of less severity than warning, let alone error) stopping the page from loading?

**Comment by maltheism** [comment]
@driusan the frontend makes a request for json data to populate all the UI elements and the response returned is corrupted by the undefined key in the array.

**Comment by jftunteng** [comment]
@maltheism closing this issue since the PR is merged. Feel free to reopen if this is still an issue or if it reoccurs.
