### ISSUE TITLE
[RB_session] one candidate has multiple values with same visitNo 

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#4677]
to test run "php assign_missing_instruments.php "
there is no error massage like :

Fatal error:  Uncaught DomainException: Attempt to use pselectRow on a query that returns multiple rows in /var/www/loris/php/libraries/Database.class.inc:835
Stack trace:
#0 /var/www/loris/php/libraries/Database.class.inc(973): Database->pselectRow('SELECT Visit_la...', Array)
#1 /var/www/loris/php/libraries/Candidate.class.inc(619): Database->pselectOne('SELECT Visit_la...', Array)
#2 /var/www/loris/tools/assign_missing_instruments.php(93): Candidate->getFirstVisit()
#3 /var/www/loris/tools/assign_missing_instruments.php(148): populateVisitLabel(Array, 'V1')

**Comment by kongtiaowang** [comment]
@ridz1208 
ex. 300299 ....     in session table.

**Comment by ridz1208** [comment]
fixed
https://github.com/aces/Loris/pull/4614
