### ISSUE TITLE
[help_editor] can't edit the content

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#4705]
second round testing
can't edit the content

**Comment by maltheism** [comment]
Hi @kongtiaowang after talking to @zaliqarosli about the help_editor last week. She said the help_editor just uses the readme found in the module. I'm not sure but I think the help_editor isn't supposed to be able to edit the content.

**Comment by kongtiaowang** [comment]
@maltheism You are right, all the modules' help from the readme files, but not for the each instrument.

**Comment by zaliqarosli** [comment]
yes exactly! instruments should be able to edit via the edit button in the 'help' dropdown on the instrument page

**Comment by kongtiaowang** [comment]
been merged
