### ISSUE TITLE
[Dicom Archive] user cannot access module after gave permission

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4706]
TestPlan Item 1. `Access the 'DICOM Archive' under 'Imaging' Tab and check to see if the user has permission [Automation Testing]`

Problem
After grant user `Across all sites view Dicom Archive module and pages` access, user cannot access the module.
Error message: 
`An error occured while loading the page.`
`Failed to load resource: the server responded /dicom_archive/?format=json:1 with a status of 500 (Internal Server Error)`

**Comment by kongtiaowang** [comment]
This is an RB testing data issue.  I will update the RB_data on test.loris.ca

**Comment by kongtiaowang** [comment]
https://github.com/aces/Loris/pull/4767

**Comment by driusan** [comment]
PR merged

**Comment by coreyAbout** [comment]
Great! Thanks @kongtiaowang @driusan
