### ISSUE TITLE
[Dicom Archive] 'Selection Filter' unclickable

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4707]
TestPlan Item 2. `Click on 'Selection Filter' to show and hide the Filter options [Manual Testing]`

Problem:
'Selection Filter' is un-clickable.

**Comment by cmadjar** [comment]
Looks like this is a bug general to all modules using selection filters

**Comment by driusan** [comment]
I think we should just update the test plan to not mention that anymore, since the new UI doesn't support it and it's not a major/important feature.

**Comment by driusan** [comment]
Test plan updated.
