### ISSUE TITLE
[Dicom Archive] Click on  'View Details' not working for one record

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4709]
TestPlan Item 5. `Click on 'View Details' under Metadata to view the Details of MRI Scan [Manual Testing]`

Problem:
Record with `MTL022_300022_V1`, click on `View Details` leads to a blank page. Other records seems fine.

**Comment by cmadjar** [comment]
This should be resolved once testing is updated with the newest imaging entries. @coreyAbout Would you mind retesting this once @kongtiaowang has updated RB on testing? 

Thanks!

**Comment by cmadjar** [comment]
Just tested for that candidate and this is working now that proper imaging datasets have been inserted into RB. Closing the issue.
