### ISSUE TITLE
[Dicom Archive] After fixing #4706, item 10 need to be tested.

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4711]
TestPlan Item 10. `Click on 'View Images' to acess the Imaging-Browser for the given subject if 'View all-sites Imaging Browser pages' or 'View own-site Imaging Browser pages' permission is set [Manual Testing]`

Problem: Cannot tested until #4706 has been fixed.

**Comment by cmadjar** [comment]
#4706 PR was merged two hours ago. Issue not blocked anymore.

**Comment by cmadjar** [comment]
@coreyAbout Can you test this again?

**Comment by coreyAbout** [comment]
Hi I re-tested this and it looks fine! Thanks @cmadjar @johnsaigle 

However, accidentally I found TestPlan Item `13.Ensure that clicking on any row in the 'Archive Location' column triggers a download of the corresponding archived DICOM study [Manual Testing]` is failing, not record can be downloaded. Should I make another issue for 13.?

**Comment by cmadjar** [comment]
@coreyAbout It looks like a server issue. The raisin-bread imaging dataset is not mounted. I will create a redmine ticket to the sys admins so they can fix it. Will let you know when this is done.

Thank you!!!

**Comment by cmadjar** [comment]
FYI: https://redmine.cbrain.mcgill.ca/issues/16519

**Comment by cmadjar** [comment]
@coreyAbout The imaging dataset was mounted on the test VM. I tested the download link and it worked. Feel free to test it on your end and close this issue as it looks like everything works according to the test plan. Thank you!

**Comment by coreyAbout** [comment]
OK Great! It works. Thanks @cmadjar !
