### ISSUE TITLE
[imaging_browser] Filter "Pending new" Blank option not working

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4713]
TestPlan Item A3. `Test that all Filters work. Upon first loading, Site filter should be set to 'All User Sites' (with the dropdown menu populated with the sites the logged on user is affiliated with) IFF user does not have permission imaging_browser_view_allsites nor imaging_browser_phantom_allsites, and is set to 'All' otherwise.`

Problem:
When click on the blank option of `Pending new`, which should includes all the options, but it functions the same as selection the `new` option.

**Comment by driusan** [comment]
Since it's a multiselect, I think the solution here is to 1. Fix #4794 and 2. Remove the blank option.

I'm not sure what it means to choose explicitly "blank" in a multiselect filter.

**Comment by cmadjar** [comment]
This got fixed by the referenced PR and merged so closing the ticket
