### ISSUE TITLE
Maximum rows per page for displaying data in any table bug

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#4715]
There is a bug that may confuse users when viewing data in a table. If the user navigates to the second page of the table and then change the maximum rows per page to be something large.. Everything in the table disappears, similar to the navigation and the actual data in the table. I'm assuming the logic is still showing page 2 of the table but everything is now on page 1 and the controls for navigating the table pages are gone because there is no need when everything is on page 1.

Example (On page 2 and setting maximum rows to 10000):
![table_bug_page2](https://user-images.githubusercontent.com/16293415/58507265-52a60900-815f-11e9-85c0-3d6689baebcf.png)

Before changing Maximum rows:
![tablebug2before](https://user-images.githubusercontent.com/16293415/58507424-c21bf880-815f-11e9-8852-f6fef22e5631.png)

I think the solution would be to check if there is more than 10000 rows or whatever the maximum rows per page is set and switch to page 1 if under or equal to the maximum rows.

**Comment by driusan** [comment]
@HenriRabalais can you tackle this?

**Comment by driusan** [comment]
merged
