### ISSUE TITLE
[imaging_browser] all images are not displaying

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4716]
TestPlan Item A6. `Test that Links work, to correct dataset (selected/native)`

Problem:
No images are display for all the links.

**Comment by coreyAbout** [comment]
@kchatpar verified the problem is real.

**Comment by coreyAbout** [comment]
See also TestPlan Item 21. `Longitudinal View button launches BrainBrowser with images of the chosen modality for that specific candidate across visits/timepoints`

Problem:
Longitudinal not displaying images.

**Comment by johnsaigle** [comment]
This could be just the way to test VM is configured.

**Comment by driusan** [comment]
@cmadjar can you test this on a machine that you know is setup properly?

**Comment by cmadjar** [comment]
@driusan I just tested the links to the native, selected and all types pages. I can see the pic in the imaging browser.

Regarding brainbrowser, for some reason, it fails with the following error in the console:
![Screen Shot 2019-06-03 at 3 01 29 PM](https://user-images.githubusercontent.com/1402456/58827256-93df6280-8610-11e9-8c1e-9d94121132b2.png)

Is BrainBrowser working on 21.0 and this is just my VM that is not working?

**Comment by cmadjar** [comment]
Nevermind. The issue was my VM setup....

**Comment by cmadjar** [comment]
Regarding the longitudinal view button, it is also working on the latest version of 21.0-release branch.

It looks like everything works as it should when you have proper image setup. @driusan I'll let you decide what to do with this issue but it can probably be closed.

**Comment by driusan** [comment]
@coreyAbout can you confirm/close this if applicable?

**Comment by driusan** [comment]
or @kchatpar, since the above comment says you were able to reproduce too

**Comment by driusan** [comment]
@coreyAbout @kchatpar ping

**Comment by coreyAbout** [comment]
We've double checked, it should be a test server setting issue. I am closing it right now. @driusan @kchatpar @cmadjar
