### ISSUE TITLE
[examiner] Examiner link broken permissions

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#4717]
I'm not able to replicate this bug on test.loris.ca and it only occurs after installing LORIS with importing the Rasinbread data. Basically, when clicking on a link for an examiner from the Examiner column of the table. The result is the "You do not have access to this page." and this happens while being logged into an admin account.

**Comment by ridz1208** [comment]
this module has a custom `_hasAccess` function. it seems to be intentional.

@driusan I guess we should just add IF SUPERUSER RETURN TRUE ALWAYS ?

**Comment by zaliqarosli** [comment]
@maltheism do you have certification enabled?

**Comment by maltheism** [comment]
@zaliqarosli I'm not sure, can you clarify that a bit more?

**Comment by driusan** [comment]
@ridz1208 hasPermission should already incorporate "IF SUPERUSER RETURN TRUE ALWAYS"

**Comment by ridz1208** [comment]
Sold

Task: add return true if superuser

**Comment by zaliqarosli** [comment]
@maltheism you should have `<Certification><EnableCertification>1</EnableCertification> ` in your `project/config.xml` file

**Comment by johnsaigle** [comment]
@ridz1208 This already happens? Not sure what you're referring to exactly. 
https://github.com/aces/Loris/blob/21.0-release/php/libraries/UserPermissions.class.inc#L112-L116

**Comment by ridz1208** [comment]
@johnsaigle ma bad I misread Dave's comment.

**Comment by johnsaigle** [comment]
So the question is should `superuser`s be able to access edit examiner page even if Certification is disabled in the config file?

**Comment by zaliqarosli** [comment]
i wouldn't think so? good question. so far, they haven't been able to with certification disabled

**Comment by ridz1208** [comment]
No I dont think so either, but there should be an error message saying this feature is not in use. because technically "editing examiners" is nothing more then giving certifications. Maybe we should change it to "Certify examiner" or something.

**Comment by driusan** [comment]
Is the examiner module in the menus in the default LORIS install? If so, I think we should incorporate a check of the config/error message (I don't think it would be a complicated check to add..), if not, amending the test plan might be easier.

In either case I don't think it's a blocker for 21.0.0 if it's just a case of trying to use the module while the config is disabled.

**Comment by ridz1208** [comment]
@suzanne-lee add a configuration exception if feature is disabled.

Thanks

**Comment by suzanne-lee** [comment]
PR sent : #4895

**Comment by cmadjar** [comment]
Should be fixed by #4895 so closing the issue
