### ISSUE TITLE
[Issue tracker] Create new issue console error

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#4727]
when clicking 'New Issue' and it taking you to 'Create New Issue' page, you get console error <img width="768" alt="Screenshot 2019-05-28 19 22 02" src="https://user-images.githubusercontent.com/17415878/58518693-31084a00-817e-11e9-8ae8-853291194a42.png">

**Comment by maltheism** [comment]
Hey @zaliqarosli, I think this PR: https://github.com/aces/Loris/pull/4690 fixes that issue.

**Comment by zaliqarosli** [comment]
the last error still not fixed in the above PR. will link the PR with this issue once PR is updated to include change for the error

**Comment by zaliqarosli** [comment]
PR #4690

**Comment by driusan** [comment]
Fixed by above PR
