### ISSUE TITLE
[User Account] Test plan needs to be updated

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#4741]
- Step 4: there is no 'Examiner' field in the search filter anymore.
- Step 16, 17 and 18: fields 'Examiner at' and 'Examiner Status' are only available if you have permission 'Across all sites add and certify examiners' or if you have 'Across all sites add and certify examiners'.
- Add steps to validate the 'Valid from/to' behaviour.
- Modify step that validates the search by site: if you do not have the multi-site permission, you should not be able to see users that are associated to another site than yours (even if both users have one site in common).
- Add a step to validate the 'Check pwned password' feature.
- Add step to check 'Reject user' button behaviour.

**Comment by nicolasbrossard** [comment]
Fixed by [PR#4786](https://github.com/aces/Loris/pull/4786)

**Comment by driusan** [comment]
PR merged
