### ISSUE TITLE
[UserSiteMatch] can't find exist method

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#4746]
When user login Issue_tracker and Dicom_archive modules get the error without Across all sites.

 PHP Fatal error:  Uncaught LorisException: Can not implement SiteMatchFilter on a resource type that has no sites. in /var/www/loris/src/Data/Filters/UserSiteMatch.php:60\nStack trace:\n#0 /var/www/loris/src/Data/ProvisionerInstance.php(124): LORIS\\Data\\Filters\\UserSiteMatch->filter(Object(User), Object(LORIS\\dicom_archive\\DICOMArchiveRow))\n#1 [internal function]: LORIS\\Data\\ProvisionerInstance->LORIS\\Data\\{closure}(Object(LORIS\\dicom_archive\\DICOMArchiveRow), 13, Object(class@anonymous))\n#2 [internal function]: CallbackFilterIterator->accept()\n#3 /var/www/loris/src/Data/Table.php(82): FilterIterator->next()\n#4 /var/www/loris/src/Data/Table.php(97): LORIS\\Data\\Table->toArray(Object(User))\n#5 /var/www/loris/modules/dicom_archive/php/dicom_archive.class.inc(96): LORIS\\Data\\Table->toJSON(Object(User))\n#6 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(684): LORIS\\dicom_archive\\Dicom_Archive->toJSON()\n#7 /var/www/loris/php/libraries/NDB_Page.class.inc(670): NDB_Menu_Filter->display()\n#8 /var/www/loris/php/libraries/NDB_Page.c in /var/www/loris/src/Data/Filters/UserSiteMatch.php on line 60,

**Comment by driusan** [comment]
I believe this is "fixed" by #4765.. it is finding the method, it's just that the if statement is falling through (the PR adds a more explicit exception). The data where this is occurring should be fixed to not have null CenterIDs

**Comment by jftunteng** [comment]
@driusan Closing this issue since the PR is merged. Feel free to re-open if needed
