### ISSUE TITLE
[Data Team Helper] Incorrect initial settings of the search filter (site)

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#4748]
According to the test plan, the initial setting of the 'Site' for the search filter should be all study sites only if the user has the access all profiles permissions. My user did not have that permission but 'Site' was set to all study sites anyway.

**Comment by ridz1208** [comment]
I think we should update the test plan not the module, its seems like something left over from before the user multisite changes

**Comment by driusan** [comment]
I agree with @ridz1208

**Comment by ridz1208** [comment]
@driusan thats a first

**Comment by cmadjar** [comment]
PR merged so closing the ticket
