### ISSUE TITLE
[Genomic Browser] Test Plan has incomplete sections

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4753]
There is no information for `Tooltips` or `Data Upload`; both just say under Construction.

Someone with knowledge of these modules should flesh this out.

**Comment by driusan** [comment]
The README also has incomplete sections that need to be fleshed out since #5827 was merged

**Comment by ridz1208** [comment]
@christinerogers will you be able to fix this ?

**Comment by christinerogers** [comment]
Xavier has the most knowledge of these but yes, I'll be able to take a stab.

**Comment by ridz1208** [comment]
@christine please do and take a stab at the linked issue #6301

**Comment by christinerogers** [comment]
@ridz1208 this and #6301 are addressed in #6391 - just needs the requested reviewers to look at it. They've been sent a reminder today.
