### ISSUE TITLE
Issue Tracker columns do not match headers

### ISSUE THREAD

**Issue by driusan** [aces/Loris#4762]
After fixing #4759 and #4761 when I load the issue tracker main page the columns are not aligned under the correct header. PSCID contains the Visit, Visit Label contains a timestamp, Last Update contains a session ID, etc..

**Comment by driusan** [comment]
@HenriRabalais Can you tackle this one?

**Comment by zaliqarosli** [comment]
PR https://github.com/aces/Loris/pull/4806

**Comment by driusan** [comment]
Fixed by above PR
