### ISSUE TITLE
Brainbrowser

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#4766]
Brain browser Canvas size drop down changes the size of the images but the drop down label never changes from "300 Pixels (Default)" 

Below is the error I get in the Console:
![Screen Shot 2019-06-03 at 4 57 14 PM](https://user-images.githubusercontent.com/1402456/58834176-ac577900-8620-11e9-8acd-ea5a4128b14d.png)

@ridz1208 @driusan I have no idea how to fix this...

**Comment by driusan** [comment]
@maltheism can you look into this?

**Comment by driusan** [comment]
Fixed by above PR
