### ISSUE TITLE
[configuration] wrong error message

### ISSUE THREAD

**Issue by PapillonMcGill** [aces/Loris#4770]
in the project section of configuration, when entering a specifying a value that is not numerical for target, either for a new project or modifying an existing one, the error message is:
` Failed to save, same name already exist!` and disappear fast,  in about 1 second.

in that case, text should be ` Failed to save, value not integer` and should also stay a few more seconds to let user time to read.

Also entering float value do not generate error and only the integer part is saved in the DB.

**Comment by driusan** [comment]
Fixed by above PR
