### ISSUE TITLE
[configuration] subproject not related to project

### ISSUE THREAD

**Issue by PapillonMcGill** [aces/Loris#4771]
When clicking on the subproject link in the project tab, we get all the subproject, not only the one releated to the project we came from. 
Step 4 of the project section of the configuration module.

**Comment by ridz1208** [comment]
that is expected behaviour. if the test plan does not reflect it, it should be updated

**Comment by driusan** [comment]
yeah, I don't think there's ever been a feature implemented where it filters by the project that you came from.

**Comment by cmadjar** [comment]
@PapillonMcGill Any chance you could updated the test plan and send a PR for it? Thanks!!

**Comment by PapillonMcGill** [comment]
will work on it

**Comment by driusan** [comment]
PR merged
