### ISSUE TITLE
LORIS incorrectly uses Gender instead of Sex

### ISSUE THREAD

**Issue by gdevenyi** [aces/Loris#4775]
For demographics information about subjects LORIS incorrectly uses the term ``Gender`` instead of the biologically relevant term ``Sex``

There are two places this is most relevant
1. Animal data
- animals do not express gender
2. Studies involving trans individuals
- we have previously worked with datasets from collaborators where there is a difference between Sex and Gender of subjects

**Comment by driusan** [comment]
This was fixed by #3897 (which will be incorporated in the upcoming 21.0 release)

**Comment by gdevenyi** [comment]
Thanks. Sorry I didn't check the PR list.
