### ISSUE TITLE
[MRI violations] Scan appears three times in 'resolved' tab

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#4781]
1. I access the MRI violations module and search for scans for which the type of problem is 'Could not identify scan type'.
2. I select a resolution type (any) and click 'Save'
3. I browse the 'Resolved' tab of the MRI and I see the scan I edited in step 2 repeated three times.

**Comment by cmadjar** [comment]
The same kind of changes than this PR https://github.com/aces/Loris/pull/3860/files should probably be applied on the resolved tab

**Comment by cmadjar** [comment]
PR merged
