### ISSUE TITLE
[imaging_browser] Drop down QC MRI comments not saving

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#4784]
Test Plan section D. MRI-QC: 
23. Comments save, checkboxes save, dropdown values save

=> After testing the QC comment box on my sandbox I noticed that the drop down in the MRI QC pop up window does not save. Everything else saves.

**Comment by cmadjar** [comment]
@driusan I put the Critical to release tag here as saving the comments seem like something quite important. Feel free to change it if you don't agree.

**Comment by cmadjar** [comment]
Note to self. This is indeed an issue with 21.0 code as this is working on demo with the same dataset and 20.3.

**Comment by driusan** [comment]
@cmadjar seems like a critical bug to me too.

**Comment by driusan** [comment]
Digging into it a little, it looks like they're saving in the backend, they're just not loading/being displayed

**Comment by cmadjar** [comment]
indeed, it got saved in the backend. Your PR fixed the frontend. Thanks!

**Comment by driusan** [comment]
Fixed by above PR
