### ISSUE TITLE
[imaging_browser] QC info not viewable if do not have permission to edit the QC

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#4785]
Test Plan section D. MRI-QC:
22. Viewable by all, editable IFF permission imaging_browser_qc

=> When trying to view the QC information with a user that do not have permission imaging_browser_qc, we get a 403 error.

This error got inserted here: https://github.com/aces/Loris/commit/16bb75f7cd813915d43bb61c9bd08329c8b7203c#diff-44bcdd7c78b4cad3c9529f51aa8598f9

**Comment by driusan** [comment]
Fixed by above PR
