### ISSUE TITLE
[Instrument List] Unable to change the Visit Stage

### ISSUE THREAD

**Issue by kchatpar** [aces/Loris#4807]
When testing the Instrument list, I'm not able to switch the candidates past the "In progress" stage.

**Comment by sruthymathew123** [comment]
@kchatpar  I cannot reproduce this issue on my VM.  Can you explain more on this issue?
Also, I think Instrument data entry and DDE should be complete for all instruments in the instrument list to switch the  visit stage. Can you check that as well?
![pass_screen](https://user-images.githubusercontent.com/23702452/59117324-74e81580-891b-11e9-9412-ed2c3e936e57.png)

**Comment by driusan** [comment]
@kchatpar ping

**Comment by kchatpar** [comment]
@sruthymathew123 I double checked - the only two conditions to move to the next stage are that DDE and data entry are solved. I'm not able to move a timepoint from In Progress to Pass once data entry and DDE are completed. The option doesn't become clickable.
![Screenshot from 2019-06-10 17-42-33](https://user-images.githubusercontent.com/15351191/59229205-c9072a00-8ba7-11e9-954b-1e384cd15653.png)

**Comment by sruthymathew123** [comment]
@kchatpar Also there should not be any conflicts between single entry and DDE forms. I assume that you tested this on test.loris.ca. So when I checked the candidate MTL001 on conflict resolver, I could see lot of conflicts. So if you need to move a visit stage to Pass; there should not not be any conflicts as well. Sorry; I missed to mention that in the above comments.
![conflicts](https://user-images.githubusercontent.com/23702452/59280459-9e62b300-8c33-11e9-9554-478e658cfe1b.png)

I tested with another visit on test.loris.ca and completed all the form without any conflicts. Then I could see 'Pass' option as clickable
 [Ref](https://test.loris.ca/instrument_list/?candID=300135&sessionID=2084)

**Comment by driusan** [comment]
@kchatpar The "Medical History" instrument in your screenshot also isn't complete yet.

**Comment by kchatpar** [comment]
My mistake - this does work.
