### ISSUE TITLE
[Instrument List] UI inconsistency when switching between instruments

### ISSUE THREAD

**Issue by kchatpar** [aces/Loris#4808]
When testing the instrument list I noticed that in the navigation history at the top of the page. Instead of listing the name of the instrument with the correct capitalization and spaces the name of the instrument is lowercase and has underscores to represent spaces. Ex: The instrument "MRI Parameter Form" is represented as "mri_parameter_form" in the navigation history at the top of the page.

**Comment by PapillonMcGill** [comment]
need to change breadcrumb construction to use "fullName" instead of "testName"

**Comment by zaliqarosli** [comment]
PR https://github.com/aces/Loris/pull/4844

**Comment by driusan** [comment]
Fixed by above PR
