### ISSUE TITLE
[Issue Tracker] Issues Duplicated in Issue Tracker Menu

### ISSUE THREAD

**Issue by driusan** [aces/Loris#4813]
While testing that adding an issue works for #4812, I noticed that issues I created were being duplicated on the menu issue page after being redirected. The rows only exist 1 time in the backend, so this is solely a display issue and not because the PR breaks things in a way that inserts the issue twice.

**Comment by zaliqarosli** [comment]
I also noticed that if an issue is watched by n number of people, it will display n number of times in the data table

**Comment by driusan** [comment]
That might be what's happening here.. is there another issue that I didn't see which this is a duplicate of, then?

**Comment by driusan** [comment]
Fixed by above PR
