### ISSUE TITLE
[Statistics] Breakdown table missing

### ISSUE THREAD

**Issue by kchatpar** [aces/Loris#4816]
The breakdown table under the demographic and behavioral tabs in the statistics module is not present. The message on the front end is: Oops
It seems like the scan type selected does not have a corresponding column in the mri_parameter_form table in the database.
In order to display the statistics for the scan type, make sure the mri_parameter_form table contains a column in the exact format SCANTYPE_Scan_done

**Comment by driusan** [comment]
Do you have an mri_parameter_form with columns of that form?

**Comment by ridz1208** [comment]
@kchatpar that is intended behaviour, the error message tells you that your mri_parameter_form instrument does not have the necessary data for your scan types

@kongtiaowang 's #4800 should allow you to load the table, or you could do it yourself by adding the missing columns and some data in them

edit: you could also add this in the stats testplan, we should make sure this error message gets displayed properly when columns are missing from the table

this comment was copied over from #4546

**Comment by ridz1208** [comment]
@kchatpar also behavioural tab does not have a breakdown, did you mean to say MRI ?

**Comment by kchatpar** [comment]
breakdown table is now present - closing issue.
