### ISSUE TITLE
[Issue Tracker] Assignee should not be required when creating a new issue

### ISSUE THREAD

**Issue by driusan** [aces/Loris#4818]
An average user submitting a bug is unlikely to know who to assign to, that's the coordinator's job. They just want to report the bug.

**Comment by driusan** [comment]
Taking the 21.0 label off this since it's more of a design issue than a testing issue, and that's the way it's always worked.

**Comment by johnsaigle** [comment]
@maltheism Tagging you since you're doing some issue tracker refactoring. This seems like it shouldn't be too difficult to fix.

**Comment by cmadjar** [comment]
Resolved by #8301. Not sure why this did not auto-close...
