### ISSUE TITLE
[timepoint_list] no direct way to access timepoint_list if no permission

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4842]
TestPlan Item `1. Module access permissions: 
For a candidate of the same site as your user, accessing the timepoint_list module should not require any permission.`

Problem:
If there is no permission, there is no access to Candidate list, which means that there is no direct way to access the timepoint_list module.
If there is data entry permission which provides access to the Candidate list, the link of the participant is not clickable, thus can not access to the timepoint_list.

**Comment by zaliqarosli** [comment]
@coreyAbout did you try accessing the timepoint_list url directly?

**Comment by driusan** [comment]
You should be able to click the "Open Profile" button and enter the DCCID/PSCID in order to access a candidate if you have the data_entry permission.

**Comment by coreyAbout** [comment]
@zaliqarosli I did tried the url, which works. That's why I said no "direct" access. 
@driusan , that is one way to access. Ideally, from a user experience point of view, it should be clickable as in the other conditions. But if this is not the priority, I think I will update the TestPlan, and close this issue after.

**Comment by driusan** [comment]
The reason it's not clickable with the data entry permission is to avoid someone accidentally clicking on the wrong row, and then entering data for the wrong candidate without realizing it. Requiring them to enter the DCCID and PSCID acts as a form of double data entry to make sure they're entering it at the right place.

**Comment by coreyAbout** [comment]
OK @driusan That's sounds great. I will update the test plan a bit.
