### ISSUE TITLE
[timepoint_list] buttons not appear for regular user

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4843]
TestPlan Item `2. Action buttons:`
`For a candidate of the same site as your user, there should be 2 additional buttons:
"Create time point". (links to create_timepoint module for that candidate)`
`One of "Edit Candidate Info" or "View Candidate Info" according to your user permissions :`
`"Edit Candidate Info" if your user has the candidate_parameters_edit permission.`
`"View Candidate Info" if your user has the candidate_parameters_view permission.`

Problem:
Using the regular user, For a candidate of the same site as your user, only `View Imaging datasets` button appeared, no other button appeared.

**Comment by cmadjar** [comment]
those buttons appear depending on the user's permission.

- "Create timepoint" appears only if the user has `data_entry` permission (updating the test plan for this as it was not specified)

The Edit or View candidate info button do not appear to unless your user belong to the same site as the candidate you are accessing. Modifying the test plan accordingly.

**Comment by driusan** [comment]
Fixed by above
