### ISSUE TITLE
[Survey Module] Failed to retrieve data

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#4848]
<img width="1280" alt="Screenshot 2019-06-11 16 45 01" src="https://user-images.githubusercontent.com/17415878/59306595-95410880-8c6a-11e9-9cb8-c4c928e00298.png">

i get the above noticed for almost every survey link

**Comment by driusan** [comment]
On test.loris.ca or your sandbox? If the former, do you have specific instances that *don't* get the error?

**Comment by zaliqarosli** [comment]
this is on test.loris.ca .. either its 'Data has already been submitted' if status = 'complete' (https://test.loris.ca/survey.php?key=40ea01ebd8be4c4f) or 'Failed to retrieve data for timepoint' otherwise (https://test.loris.ca/survey.php?key=9*8u@5^l)

**Comment by johnsaigle** [comment]
@ridz1208 Is this a Raisinbread issue?

**Comment by ridz1208** [comment]
closing since 21 testing round seems stale
