### ISSUE TITLE
[Dashboard] My tasks doesn't represent the number of new scans

### ISSUE THREAD

**Issue by kchatpar** [aces/Loris#4858]
9. Verify that for a user with 'Edit imaging browser QC status' permission the My Tasks panel reports the number of new scans (i.e. the number of scans on the MRI browser page for which QC status has not been set). Check that site displayed is always 'All'. Click on this task and verify that you go to the MRI Browser page. [Automate Test on Travis_CI]

According to my New Tasks, on the test VM there are 3 'new and pending imaging sessions'. According to imaging browser, there are 6 new scans where the QC status has not been set.

**Comment by cmadjar** [comment]
In the dashboard query, we exclude all visits that have CenterID set to 1 (the DCC Center). In the 6 visits displayed on testing without QCStatus, 3 are from the DCC Center and therefore are not counted in the dashboard.

I think we should keep it as is and we should probably update the RB dataset to not have any data for the DCC? Or should the query of the imaging browser be changed to exclude the DCC Center as well? @driusan what do you think?

**Comment by driusan** [comment]
Can't we just update the test plan to include that information?

**Comment by cmadjar** [comment]
Sure. Updating the test plan.
