### ISSUE TITLE
[Dashboard] Conflict resolver count on dashboard is not accurate

### ISSUE THREAD

**Issue by kchatpar** [aces/Loris#4859]
Test plan item - 10. Verify that for a user with 'Resolving conflicts' permission the number of data entry conflicts is reported in the My Task panel. 

According to my New Tasks in the test VM, I have 579 data entry conflicts. The conflict resolver says I have 669 unresolved conflicts - this count should be the same. 

When the user has the "Across all sites access candidates profiles" permission the amount of data entry conflicts is accurate

**Comment by ridz1208** [comment]
Check if the missing conflicts are associated with a a candidate with active=no or a session active=no or candidates from the dcc centerid =1

**Comment by cmadjar** [comment]
Indeed, the difference comes from the 90 DCC conflicts. Will also update the test plan to mention that DCC conflicts are not counted in the dashboard
