### ISSUE TITLE
[Dashboard] Edit and create user accounts does not show up in dashboard 

### ISSUE THREAD

**Issue by kchatpar** [aces/Loris#4862]
12. Verify that if a user has 'Across all sites create and edit user accounts' permission, the number of pending account approvals is displayed in the My Task panel.

When the permission - 'Across all sites create and edit users' is selected the number of pending account approvals is not listed in the My Task panel and when the permission is de-selected the user accounts tab does not go away.

The permission listed in the test plan - Across all sites create and edit user accounts' should be changed to 'Across all sites create and edit users' to match the permission in Loris.

**Comment by cmadjar** [comment]
Updating the test plan to the correct permission name.

For me, adding or removing the 'Across all sites create and edit users'  permission does not do anything (I don't see the menu Admin -> User accounts when the permission is set and I don't see the listed tasks either). Will try to take a closer look into it later.

**Comment by cmadjar** [comment]
OK. The "User management" permission is also needed in conjunction with 'Across all sites create and edit users'. Updated the test plan accordingly.
