### ISSUE TITLE
[Dashboard] Across all sites access candidate profiles does not propagate reports tab

### ISSUE THREAD

**Issue by kchatpar** [aces/Loris#4863]
13. Verify that if a user has 'Across all sites access candidate profiles' permission, the reports works and even more important to check without this permission. [Automate Test]

When the permission 'Across all sites access candidate profiles' is selected it does not make the reports tab viewable, the candidate tab becomes viewable. Maybe another permission is required here. The test plan needs to be updated to represent the permissions needed.

**Comment by cmadjar** [comment]
It looks like it needs the "Data entry" permission (not the across all sites access candidate profiles) in order to have the number of incomplete forms listed in the task list and have the reports menu tab showing. Will update the test plan accordingly.
