### ISSUE TITLE
[DQT] Cannot Load Results

### ISSUE THREAD

**Issue by suzanne-lee** [aces/Loris#4864]
After defining fields and running the query, the DQT gets stuck trying to load the results, and no network call is made 

<img width="1007" alt="Screenshot 2019-06-13 11 59 36" src="https://user-images.githubusercontent.com/29237731/59448250-bfadd580-8dd2-11e9-8729-318720383645.png">

**Comment by suzanne-lee** [comment]
https://github.com/aces/Loris/projects/19#card-21296649

**Comment by xlecours** [comment]
Let me know when a PR is sent please.

**Comment by driusan** [comment]
@xlecours a PR seems to be sent.

**Comment by driusan** [comment]
PR merged
