### ISSUE TITLE
[DQT] Remove All Button Broken

### ISSUE THREAD

**Issue by suzanne-lee** [aces/Loris#4865]
The Remove All button under the "Define Fields" tab doesn't do anything (but the Add All button works fine) 
This is also broken on demo.loris.ca

<img width="353" alt="Screenshot 2019-06-13 12 16 12" src="https://user-images.githubusercontent.com/29237731/59449465-203e1200-8dd5-11e9-8bd4-241a5625ac00.png">

**Comment by johnsaigle** [comment]
@laemtl You have a working DQT right? Would you be able to verify whether this is still an issue?

**Comment by laemtl** [comment]
Yes sure!

**Comment by johnsaigle** [comment]
Awesome, thank you

**Comment by laemtl** [comment]
Works fine on Chrome and Firefox.

**Comment by johnsaigle** [comment]
@ridz1208 What do you think? Can this be closed?

**Comment by SantiagoTG** [comment]
Closing as error no longer present in demo.loris.ca.
