### ISSUE TITLE
[New Profile] DoB format in config module not taken into account

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#4868]
1. In the config module, I set the DoB format to YM
2. When I access the New Profile module, I am still prompted to enter the DoB in format YYYY-MM-DD.
3. If I enter a valid date and create the candidate, his/her DoB is still displayed in YYYY-MM-DD format in the Access Profile module, column DoB.

**Comment by cmadjar** [comment]
I believe this bug will be fixed by the following PR #4729 from @zaliqarosli

**Comment by cmadjar** [comment]
Closing this issue as this was resolved by PR #4729.
