### ISSUE TITLE
[Candidate Parameters] Breadcrumbs Lead to Unexpected Behaviour

### ISSUE THREAD

**Issue by suzanne-lee** [aces/Loris#4874]
Clicking on the Candidate Parameters breadcrumbs causes the page to no longer be associated to any candidate (see screenshot, DCCID = undefined). As a result, if you click time point list, you'll get a 404

Clicking on the candidate parameters breadcrumbs should maybe be disabled or the page should refresh but still be associated with the candidate 

<img width="678" alt="Screenshot 2019-06-14 15 07 46" src="https://user-images.githubusercontent.com/29237731/59532343-6c14b800-8eb6-11e9-846d-f2694cea3c65.png">

**Comment by johnsaigle** [comment]
This seems to be resolved on v23.
