### ISSUE TITLE
[Candidate Parameters] Typo in Test Plan

### ISSUE THREAD

**Issue by suzanne-lee** [aces/Loris#4875]
"Check Permissions:

- candidate_parameter_view (Edit Candidate Parameters) permission (you should be able to edit fields)

- candidate_parameter_edit (View Candidate Parameters) permission (you should not be able to edit fields)"

should read: 

"- candidate_parameter_view (View Candidate Parameters) permission (you should not be able to edit fields)

- candidate_parameter_edit (Edit Candidate Parameters) permission (you should be able to edit fields)"

**Comment by suzanne-lee** [comment]
PR sent: #4900

**Comment by driusan** [comment]
PR merged
