### ISSUE TITLE
[Candidate Parameters] Outdated Test Plan (Consent Status Tab)

### ISSUE THREAD

**Issue by suzanne-lee** [aces/Loris#4876]
1. Cannot set Consent Status = No without setting Date of Consent (According to Test plan, you should be able to set consent status = no and leave everything else blank)

2. Date of Withdrawal of Consent is disabled when Consent Status = Yes 

3. Test plan says "Tab should render with only one consent type" but the tab has 3 (consent to study, consent to raisin, consent to bread)

<img width="655" alt="Screenshot 2019-06-14 15 19 47" src="https://user-images.githubusercontent.com/29237731/59533018-47b9db00-8eb8-11e9-8a94-f5f9bd78cc28.png">
<img width="647" alt="Screenshot 2019-06-14 15 19 01" src="https://user-images.githubusercontent.com/29237731/59533019-48527180-8eb8-11e9-9fc4-4424db904482.png">
<img width="436" alt="Screenshot 2019-06-14 15 24 01" src="https://user-images.githubusercontent.com/29237731/59533067-67e99a00-8eb8-11e9-8d82-548bcf3c41e0.png">

**Comment by sruthymathew123** [comment]
@driusan @zaliqarosli Correct me if I am wrong in the below statements

Regarding issue1:_Cannot set Consent Status = No without setting Date of Consent (According to Test plan, you should be able to set consent status = no and leave everything else blank)_
I think IBIS used to add the date when a 'NO' consent is also given. So I think in the last major release or so, we made the Date of Consent required for Yes/No consents, right?
(In that case, no more an issue; but may be need to amend the test plan)

Regarding Issue 2 _Date of Withdrawal of Consent is disabled when Consent Status = Yes_
I think it is supposed to be in that way- Date of Withdrawal is enabled when a consent is changed from YES to NO, right? (Not an Issue in that case)

Regarding Issue 3 _Test plan says "Tab should render with only one consent type" but the tab has 3 (consent to study, consent to raisin, consent to bread)_
I am not clear on this one- Consents are supposed to populate all together, right?

**Comment by zaliqarosli** [comment]
@sruthymathew123 @suzanne-lee yeah i see no issues here, this is how its supposed to be! looks like the test plan needs updating though. i thought i have done that along with the last changes, but i guess not!

**Comment by zaliqarosli** [comment]
the PR that made these last major changes for reference https://github.com/aces/Loris/pull/4034

**Comment by sruthymathew123** [comment]
PR merged; so closing.
