### ISSUE TITLE
[Candidate List] PSCID Not Clickable When access_all_profiles Permission Disabled

### ISSUE THREAD

**Issue by suzanne-lee** [aces/Loris#4884]
From Test Plan:

"17. Remove access_all_profiles permission and ensure that PSCID links are still clickable."

When you remove access_all_profiles permission, the PSCID is no longer clickable but the timepoint list of a candidate is still accessible through the address bar (url.com/dccid)

**Comment by driusan** [comment]
That test plan is wrong. The link isn't supposed to be clickable without access all profiles.

**Comment by suzanne-lee** [comment]
@driusan should a candidate's timepoint list still be accessible via the address bar?

**Comment by driusan** [comment]
You should still be able to get there by clicking "Open Profile" and entering both the PSCID and DCCID.. which I guess means it would also be accessible through the address bar, but I doubt any user would do that.

**Comment by suzanne-lee** [comment]
PR sent: #4898

**Comment by driusan** [comment]
PR merged
