### ISSUE TITLE
[Candidate List] Open Profile Gets Stuck Validating

### ISSUE THREAD

**Issue by suzanne-lee** [aces/Loris#4887]
Open profile works fine when the DCCID and PSCID match, but sometimes gets stuck validating when inputs are invalid 

<img width="730" alt="Screenshot 2019-06-17 14 15 15" src="https://user-images.githubusercontent.com/29237731/59626834-e63d7a80-910a-11e9-8b9b-b1b687e1ca64.png">
<img width="722" alt="Screenshot 2019-06-17 14 14 55" src="https://user-images.githubusercontent.com/29237731/59626836-e63d7a80-910a-11e9-925a-af8fc4333c4d.png">

**Comment by driusan** [comment]
Is there any response in the network tab when it gets stuck?

**Comment by suzanne-lee** [comment]
@driusan 500 error

**Comment by ridz1208** [comment]
I ran into this, but its not consistent....

**Comment by suzanne-lee** [comment]
PR sent #4893

**Comment by driusan** [comment]
Fixed by above PR
