### ISSUE TITLE
[Candidate Parameters] Candidate variables table missing

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#4891]

**Comment by johnsaigle** [comment]
Can you provide more detail here?

**Comment by zaliqarosli** [comment]
this table used to be at the top of candidate parameters page:

<img width="984" alt="Screenshot 2019-10-31 12 58 36" src="https://user-images.githubusercontent.com/17415878/67968717-43c7f480-fbde-11e9-9c70-f8d45acefffd.png">

now: 
<img width="840" alt="Screenshot 2019-10-31 12 58 43" src="https://user-images.githubusercontent.com/17415878/67968740-4de9f300-fbde-11e9-9b04-3e8594d25849.png">

**Comment by zaliqarosli** [comment]
did we say that this is no longer an issue?

**Comment by johnsaigle** [comment]
There is still no table for me on the candidate parameters page on `aces/master`

<img width="776" alt="Screen Shot 2020-01-07 at 14 40 46" src="https://user-images.githubusercontent.com/4022790/71923754-b8c62600-315b-11ea-888f-8e07d9169c69.png">

**Comment by zaliqarosli** [comment]
i think we might have said that the table not being there is no longer an issue and that it was in fact intentionally left out?

**Comment by johnsaigle** [comment]
Yeah I'm not sure. We could bring it up in a meeting or just close the ticket. Up to you
