### ISSUE TITLE
[DQT] jStat crash when all values of a given field are null

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#4908]
When all the values of a given queried field are null, jStat crashes in the render function of `StatsVisualizationTabPane`.

**Comment by johnsaigle** [comment]
Is this also addressed by #4910 or is this a separate issue?

**Comment by xlecours** [comment]
@johnsaigle It is a separate issue

**Comment by driusan** [comment]
Stale, no longer relevant to newest DQT
