### ISSUE TITLE
[SQL/Release_patches] 20.3_To_21.0_upgrade.sql error on 21.0-release

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4931]
ERROR 1075 (42000) at line 4: Incorrect table definition; there can be only one auto column and it must be defined as a key.

**Comment by driusan** [comment]
The 20.3_To_21.0_upgrade.sql should have a bunch of lines that print "Running: SQL/New_patches/[...]".. what was the most recent one before the error message?

**Comment by coreyAbout** [comment]
As the error code said, at line 4 of 20.3_To_21.0_upgrade.sql. I think it is caused by dropping a primary key which has a property of auto_incr
line 1
line 2 SELECT 'Running: SQL/New_patches/2018-01-17-normalisation_visit.sql';
line 3
line 4 ALTER TABLE project_rel DROP PRIMARY KEY;

**Comment by ridz1208** [comment]
@coreyAbout I think I ran into somethink similar, which mysql/mariadb version are you on ?

**Comment by ridz1208** [comment]
@PapillonMcGill you were the one who had issues with that statement and you submitted a commit to changeit.

https://github.com/aces/Loris/pull/4493/commits/ffd22af12621e73063e9308c5f502547f1c605e6

**Comment by PapillonMcGill** [comment]
@coreyAbout Could you provide the definition of the `project_rel` table **before** the upgrade process (`show create table project_rel`) and the output of the DB after manually running the 'ALTER TABLE project_rel ...' and of course which version of DB you are executing it on.

**Comment by PapillonMcGill** [comment]
pinging @coreyAbout

**Comment by coreyAbout** [comment]
@ridz1208  MySQL version I am using:
mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using  EditLine wrapper

**Comment by coreyAbout** [comment]
@PapillonMcGill 
| project_rel | CREATE TABLE `project_rel` (
  `ProjectSubprojectRelID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ProjectID` int(2) NOT NULL,
  `SubprojectID` int(2) NOT NULL,
  PRIMARY KEY (`ProjectSubprojectRelID`),
  UNIQUE KEY `UK_project_rel_ProjectID_SubprojectID` (`ProjectID`,`SubprojectID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 |

mysql Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using EditLine wrapper

**Comment by coreyAbout** [comment]
@PapillonMcGill 
Running the line `ALTER TABLE project_rel DROP PRIMARY KEY;` 
Produced:
`ERROR 1075 (42000): Incorrect table definition; there can be only one auto column and it must be defined as a key`

I think it is caused by dropping a primary key which has a property of auto_incr

**Comment by coreyAbout** [comment]
@driusan @ridz1208 @PapillonMcGill 
I will make a pull request in a few minutes.

**Comment by PapillonMcGill** [comment]
@coreyAbout  No need for a PR.

It seem, you already have applied the patch from Rida's PR (possibly for testing) to modify this table.

Your table do not have the definition of V20.x but already have definition of v21.0

Closing this issue.
