### ISSUE TITLE
Update 21.0 release notes to include info on how to deal with plaintext password security issue

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4942]
The release notes should be updated to include details about the plaintext password issue from #4021. They should be told how to execute the included script and what it does.

**Comment by johnsaigle** [comment]
Also @driusan I think we discussed putting out a Security alert for this. We should probably find a time to do that.

**Comment by driusan** [comment]
added to the script to the upgrade section of the release notes in the final release
