### ISSUE TITLE
[UI/Tablet] Can't deselect menu item once selected

### ISSUE THREAD

**Issue by leighevans** [aces/Loris#4951]
On Apple tablet:

Once a menu item is selected you can't unselect it unless you navigate to another menu item. For example (pictured) if Reports is selected, you can't deselect the menu item and if you wanted to access say, the Admin menu, which is covered by the expanded Reports menu, you'd have to select one of the higher menu items such as Candidate or Clinical to reveal it. 
![42FEE13C-D3B6-45C8-BDFD-28D220142FFD](https://user-images.githubusercontent.com/32552953/61324010-64ab3c00-a7df-11e9-9c38-3174a5f33703.png)

**Comment by driusan** [comment]
Tried with a Firefox window in tablet mode and it doesn't seem to be the case anymore. Clicking a second time de-selects.
