### ISSUE TITLE
[Install]Loris Installation: Errors in Installation guide

### ISSUE THREAD

**Issue by T-Clark-D** [aces/Loris#5001]
**In depth Ubuntu installation.**
https://github.com/aces/Loris/wiki/Installing-Loris-in-Depth

**Section**: Getting the Loris codebase
    -Step 2 should be run first before proceeding to step 1.

**Section**: Running the Install Script
    -Step 2 Run cd loris/tools 
        - The 'l' in loris should be capitalized since that is how the directory is created by default.

**Comment by christinerogers** [comment]
Thanks Clark.  Re your second point, We should suggest instead people rename or softlink `ln -s ./Loris loris` since the lowercase convention is our current standard - despite the repo name, as you point out.

**Comment by johnsaigle** [comment]
A better solution that we should use is:
`cd /var/www`
`git clone git@github.com:aces/Loris.git loris`

This will create `/var/www/loris/...` instead of `/var/www/loris/Loris` which is the result of our current instructions.

**Comment by johnsaigle** [comment]
I think this will be resolved by #5253.
