### ISSUE TITLE
[install] `sudo ./install.sh` will fail, but won't tell you 

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5008]
Since #4109 is new in Release 21 : 
If the install script is called w sudo (per the current wiki install guides, links below) - `project/config.xml` is not owned by lorisadmin --
The install script gives a success message, but Loris itself will be incompletely(non-functionally) set up, and the user can't proceed.  The manual troubleshooting is a little complicated. 

It's occurring because #4109 introduced a new script called by install.sh which is run basically as root (when the install script is sudo'd by lorisadmin) not as lorisadmin 

Graceful fix: 
- [ ] Fix tools/create-project.sh so that it sets the permissions appropriately in case of sudo 

less graceful: 
- [ ] Check/Abort/Warn install.sh if run with sudo.  -> update:  PR #5008

Also to do: (in either case) remove the `sudo` from the install.sh instruction in :
- [x] Update the [Brief Install guide here](https://github.com/aces/Loris/wiki/Installing-Loris-in-Brief#running-the-install-script)
- [x] Update the [Detailed install guide here](https://github.com/aces/Loris/wiki/Installing-Loris-in-Depth#running-the-install-script)

**Comment by christinerogers** [comment]
Resolved by @driusan's PR #5008 which is now linked. 

Thanks @johnsaigle for also making a PR to resolve this.

**Comment by gdevenyi** [comment]
tools/install.sh needs
```
set -euo pipefail
```

http://redsymbol.net/articles/unofficial-bash-strict-mode/

**Comment by christinerogers** [comment]
Thanks @gdevenyi !
 -- @driusan do want to add this to #5010 ?

**Comment by driusan** [comment]
This is done
