### ISSUE TITLE
[install] Update CentOS install Readme for the 21 release

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5018]
21.0.0 is out;  the CentOS readme (#3946) should get some specific updates for the next bugfix release. 
- [ ] NodeJS version mention
- [ ] make ? //  remove `composer --no-dev` mention 
- [ ] remove mentions of release 17, 18
- [ ] See other dependency/formatting updates mentioned in issue #3946 

Should this be labelled `bugfix`, `Critical to release` ? , or with Milestone 21.0.1?

**Comment by johnsaigle** [comment]
I believe this is resolved by #5250
