### ISSUE TITLE
[LORIS21.0] [instrument] Saving data to a simple instrument produces loris error

### ISSUE THREAD

**Issue by ycAbout** [aces/Loris#5027]
For LORIS 21.0
1. Create a simple instrument using instrument builder (.linst file) only including a note field.
![Screenshot from 2019-08-16 16-20-47](https://user-images.githubusercontent.com/34487370/63289628-90618c00-c28d-11e9-8514-00995d081bdf.png)
2. Install the instrument according to https://github.com/aces/Loris/wiki/Behavioural-Database
3. Fill out the instrument and click save data through the candidate visit components.
4. Check the loris-error.log under /var/log/apache2, the following error occurred (the data seems saved, thus not sure whether a serious problem).
>[Mon Aug 19 11:53:09.310200 2019] [php7:notice] [pid 18937] [client 206.167.200.2:38904] PHP Notice:  Undefined index: Date_taken in /var/www/loris/php/libraries/NDB_BVL_Instrument_LINST.class.inc on line 156, referer: http://cobra-lab-dev.loris.ca/instruments/mri_parameter_form/?commentID=448711DIC00001111565989375&sessionID=1&candID=448711
[Mon Aug 19 11:53:09.310319 2019] [php7:notice] [pid 18937] [client 206.167.200.2:38904] PHP Notice:  Undefined index: Examiner in /var/www/loris/php/libraries/NDB_BVL_Instrument_LINST.class.inc on line 156, referer: http://cobra-lab-dev.loris.ca/instruments/mri_parameter_form/?commentID=448711DIC00001111565989375&sessionID=1&candID=448711
[Mon Aug 19 11:53:09.310355 2019] [php7:notice] [pid 18937] [client 206.167.200.2:38904] PHP Notice:  Undefined index: note_status in /var/www/loris/php/libraries/NDB_BVL_Instrument_LINST.class.inc on line 156, referer: http://cobra-lab-dev.loris.ca/instruments/mri_parameter_form/?commentID=448711DIC00001111565989375&sessionID=1&candID=448711
[Mon Aug 19 11:53:09.310376 2019] [php7:notice] [pid 18937] [client 206.167.200.2:38904] PHP Notice:  Undefined index: candID in /var/www/loris/php/libraries/NDB_BVL_Instrument_LINST.class.inc on line 156, referer: http://cobra-lab-dev.loris.ca/instruments/mri_parameter_form/?commentID=448711DIC00001111565989375&sessionID=1&candID=448711
[Mon Aug 19 11:53:09.310393 2019] [php7:notice] [pid 18937] [client 206.167.200.2:38904] PHP Notice:  Undefined index: sessionID in /var/www/loris/php/libraries/NDB_BVL_Instrument_LINST.class.inc on line 156, referer: http://cobra-lab-dev.loris.ca/instruments/mri_parameter_form/?commentID=448711DIC00001111565989375&sessionID=1&candID=448711
[Mon Aug 19 11:53:09.310410 2019] [php7:notice] [pid 18937] [client 206.167.200.2:38904] PHP Notice:  Undefined index: commentID in /var/www/loris/php/libraries/NDB_BVL_Instrument_LINST.class.inc on line 156, referer: http://cobra-lab-dev.loris.ca/instruments/mri_parameter_form/?commentID=448711DIC00001111565989375&sessionID=1&candID=448711
[Mon Aug 19 11:53:09.310427 2019] [php7:notice] [pid 18937] [client 206.167.200.2:38904] PHP Notice:  Undefined index: test_name in /var/www/loris/php/libraries/NDB_BVL_Instrument_LINST.class.inc on line 156, referer: http://cobra-lab-dev.loris.ca/instruments/mri_parameter_form/?commentID=448711DIC00001111565989375&sessionID=1&candID=448711
[Mon Aug 19 11:53:09.310444 2019] [php7:notice] [pid 18937] [client 206.167.200.2:38904] PHP Notice:  Undefined index: page in /var/www/loris/php/libraries/NDB_BVL_Instrument_LINST.class.inc on line 156, referer: http://cobra-lab-dev.loris.ca/instruments/mri_parameter_form/?commentID=448711DIC00001111565989375&sessionID=1&candID=448711
[Mon Aug 19 11:53:09.310463 2019] [php7:notice] [pid 18937] [client 206.167.200.2:38904] PHP Notice:  Undefined index: subtest in /var/www/loris/php/libraries/NDB_BVL_Instrument_LINST.class.inc on line 156, referer: http://cobra-lab-dev.loris.ca/instruments/mri_parameter_form/?commentID=448711DIC00001111565989375&sessionID=1&candID=448711
[Mon Aug 19 11:53:09.310480 2019] [php7:notice] [pid 18937] [client 206.167.200.2:38904] PHP Notice:  Undefined index: fire_away in /var/www/loris/php/libraries/NDB_BVL_Instrument_LINST.class.inc on line 156, referer: http://cobra-lab-dev.loris.ca/instruments/mri_parameter_form/?commentID=448711DIC00001111565989375&sessionID=1&candID=448711
[Mon Aug 19 11:53:09.310501 2019] [php7:warn] [pid 18937] [client 206.167.200.2:38904] PHP Warning:  Invalid argument supplied for foreach() in /var/www/loris/php/libraries/LorisForm.class.inc on line 1326, referer: http://cobra-lab-dev.loris.ca/instruments/mri_parameter_form/?commentID=448711DIC00001111565989375&sessionID=1&candID=448711

**Comment by johnsaigle** [comment]
Did this happen while building your own instrument and clicking 'Save', or trying to load an instrument?

Can you also post the linst file generated?

**Comment by christinerogers** [comment]
HI Corey - to followup on John's questiosn above -- can you include a screenshot from your data entry (for candID=448711 )

Could you also post the mysql table schema for this instrument - to show it was loaded successfully in your database.

**Comment by coreyAbout** [comment]
@johnsaigle The error does NOT occur when you are building the instrument and clicking save, or loading an instrument. 
It happens after you installed the instrument to LORIS, set up projects & sub project, start the visit stage for the candidate, then filled out the instrument for a candidate, then click on save data for that candidate. Then check your apache2 error log.
Here is the linst file.
>table{@}mri_parameter_form
title{@}mri_parameter_form
date{@}Date_taken{@}Date of Administration{@}2006{@}2012
static{@}Candidate_Age{@}Candidate Age (Months)
static{@}Window_Difference{@}Window Difference (+/- Days)
select{@}Examiner{@}Examiner{@}NULL=>''
textarea{@}note{@}note
select{@}note_status{@}{@}NULL=>''{-}'not_answered'=>'Not Answered'

**Comment by coreyAbout** [comment]
@christinerogers 
![Screenshot from 2019-08-21 14:22:21](https://user-images.githubusercontent.com/34487370/63457526-385a8f00-c41f-11e9-8689-27f9aa8c7528.png)

![Screenshot from 2019-08-21 14-25-26](https://user-images.githubusercontent.com/34487370/63457883-c6367a00-c41f-11e9-99d2-bea67517ed87.png)

**Comment by christinerogers** [comment]
Thanks Corey.  Can you help us isolate if this is truly an issue with the 21 release, or with your form generation?   Please follow the instrument installation steps using our [bmi.linst](https://github.com/aces/Loris/tree/20.3-release/docs/instruments) from the *20.3* release branch (they've been moved in 21), and accompantyng bmi.score file.  Can you reproduce the error on this instrument?

**Comment by coreyAbout** [comment]
I do not think there is anything to do with BMI.linst. Whether BMI.linst will work or not have nothing to do with the issue. Even if BMI.linst is successful, it means, the issue is either 1. LORIS21.0 instrument generation error, or 2. the instrument installation error for simple instruments. This is not new information for this issue.
The issue is, using LORIS21.0, create a simple instrument, save it and install it, added it to participant, fill in the data, save data, then there is apache2 error. 
Can you try it on your instance, exactly like what I did? This could provide new information on whether it is a issue on my instance, or is it a issue everyone has.

**Comment by johnsaigle** [comment]
> apache2 error

What error do you get?

**Comment by coreyAbout** [comment]
@johnsaigle  the whole error log was in my first post above. `PHP Notice: Undefined index:`

**Comment by johnsaigle** [comment]
Sorry, my mistake

**Comment by christinerogers** [comment]
this process and instructions have been tested for 23.0+  : Issue no longer exists given table is sourced properly.
