### ISSUE TITLE
Deletion/archiving of "Contributing to the Code" wiki page

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5029]
https://github.com/aces/Loris/wiki/Contributing-to-the-Code

Most of the information on this page is already contained in the [CONTRIBUTING.md](https://github.com/aces/Loris/blob/minor/CONTRIBUTING.md) file. It makes sense to archive/delete this Wiki page rather than havea  duplication of information.

**Comment by johnsaigle** [comment]
I'll review this and remove it from the deprecated Wiki if the information is no longer relevant.

**Comment by driusan** [comment]
Can we just link that page to the CONTRIBUTING.md?

**Comment by ridz1208** [comment]
@johnsaigle the labels part of the contributing to the code section is no longer required as the description were added to the labels themselves on the repo.

just FYI

**Comment by johnsaigle** [comment]
The page contents have been removed and now link to CONTRIBUTING.md.

The page was quite out of date (descriptions of labels, references to branches and workflows that do not exists)
