### ISSUE TITLE
[New Module] Electrophysiology browser

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#5031]
List of bugs found in the current set up:
- Task Name seems to be hardcoded to FaceHousCheck. Fix that so it takes that information from the physiological_parameter_file table (TaskName is one of the JSON file field). In jsx/components/eeg_session_panels.js and js/eeg_session_view.js

**Comment by cmadjar** [comment]
The PR associated to this issue is in active review phase.

**Comment by johnsaigle** [comment]
@cmadjar Can this be closed now that the module is merged? Or is this issue still present?

**Comment by cmadjar** [comment]
Indeed.
