### ISSUE TITLE
[Imaging Uploader] Add an "Upload Update" column to the imaging uploader

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#5032]
Discussed during the imaging meeting of August 16th, 2018.

Since re-upload overwrites existing rows in the `mri_upload` table, perhaps it is good idea to add columns about `UploadUpdateDate` (the current `UploadDate` can be renamed to `InitialUploadDate`). 
Maybe even add an `UpdatedBy` column in case someone else re-uploaded the scan?

**Comment by johnsaigle** [comment]
This feels similar to #5256. Would love to know your thoughts on this PR and whether to rename the column or to add a second one.

**Comment by johnsaigle** [comment]
Copying Cecile's reply from the other PR:

> Renaming the column to Last Modified makes a lot of sense since this is what it actually stores. Just wondering, is there a value in having an Initial Upload Date field? Is that a useful information to have?

**Comment by cmadjar** [comment]
Actually, when reuploading a scan, a new UploadID (hence a new row) is created even though we select to overwrite the upload. Not sure why this ticket was opened in the end ;). Closing the issue.
