### ISSUE TITLE
[tools] fix_timepoint_data_problems: hardcoding issues

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#5040]
The script `tools/fix_timepoint_date_problems.php` hardcodes the feedback thread type to `5` on line 512 (when the default schema does not have it) and the subproject ID to `1` and `2` on line 467 which clearly is not consistent across projects using LORIS.

**Comment by cmadjar** [comment]
@ridz1208 I know you went through the tool scripts. Is that issue still relevant? Copied it from redmine https://redmine.cbrain.mcgill.ca/issues/13195

**Comment by johnsaigle** [comment]
I looked quickly and the subprojectID at least it still hard-coded in the script.

**Comment by cmadjar** [comment]
subprojectID and feedback types are still hardcoded in the tool so still a valid issue.
