### ISSUE TITLE
[Brainbrowser] add permission check to view the file

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#5047]
This was raised by Jordan at the Loris meeting of Feb 7, 2017 and raised again at the Imaging meeting of Feb 10, 2017:
Brainbrowser is currently accessible without permissions (if the user knows the URL and ID of the MINC file).

The solution proposed by Dave, and this applies not only to brainbrowser, but other modules such as the DQT is to implement permissions at the file retrieval level (`getfile.php`)

**Comment by cmadjar** [comment]
@johnsaigle I know you worked on `getfile.php`. Do you know if this was done?

I copied over the redmine ticket created by Mouna on Github which is why this comes up (https://redmine.cbrain.mcgill.ca/issues/11966)

**Comment by johnsaigle** [comment]
There's no permission checks in the get_file class. Anything `lorisadmin` can access on the back-end can be accessed via typing in the correct path as long as it falls through the switch-case.

There is protection against path traversal (e.g. a user can't go grab /etc/passwd or sensitive files).

I'm not sure exactly what "at the file retrieval level " means. We don't have a layer in LORIS for our users to access specific files. We have only the module-level permissions and the file system permissions. Put another way, once you have access to a module, you get everything from a files perspective (after site/project filtering in the DB).

It may be possible to edit the query in `modules/brainbrowser/ajax/getImageName.php ` to have site-based restrictions if that helps.

**Comment by cmadjar** [comment]
This has been done and can be closed
