### ISSUE TITLE
[Instrument list] visit window values not correct

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#5054]
#### For IBIS:
Within Optimal and Within Permitted are always "No", even if the visit occurs within the desired window. This is a bug.

#### For CCNA:
This isn't a bug, but since visit windows are not relevant for CCNA (they don't have specific ages at which subjects must visit), it would be nice to have "not applicable" or "N/A" show up in the metadata table under Within Optimal and Within Permitted, rather than "No".

From redmine ticket https://redmine.cbrain.mcgill.ca/issues/14922

**Comment by ridz1208** [comment]
@cmadjar the most useful for CCNA is a feature where the optimal window is not determined by age but rather by time since last visit. the age is not a criteria but the visits must happen withing 3 months of each other. not sure if other projects have that need

**Comment by driusan** [comment]
Is this still relevant and/or true?

**Comment by ridz1208** [comment]
@GeorgeMurad can you check if this is still an issue for IBIS ??

**Comment by GeorgeMurad** [comment]
@ridz1208 Yes, I will check it now.

**Comment by GeorgeMurad** [comment]
@ridz1208 there's no issue for IBIS, all good.

**Comment by ridz1208** [comment]
thanks @GeorgeMurad
