### ISSUE TITLE
[Media] Content does not update after a new file is uploaded

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#5055]
After uploading a file, going back to the browse tab does not refresh/reload the data with the uploaded file, and the page must be manually refreshed to load the new content. Similarly, when trying to upload the same content without refreshing the page it does not detect that the file has been already uploaded, and so does not prompt to confirm overwriting the file.

From redmine https://redmine.cbrain.mcgill.ca/issues/14559

**Comment by ridz1208** [comment]
@maltheism this seems to come back regularly, could you tackle it on the sooner side please ?
