### ISSUE TITLE
Mac-Arthur Bates CDI Words and Gestures - Check version for Section F

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5059]
The examiner does not have a Section F on their physical form. but LORIS, in the Part II subpage, does. Could this be from a different version? Check with Leigh.

**Comment by johnsaigle** [comment]
I think this is IBIS specific and should probably go in that repo.

**Comment by SantiagoTG** [comment]
Hi John, 
Thanks for the comment. I am unable to find the IBIS repository, and not sure if there is one or how this has worked in the past. If possible, could you please point out for me where this repository is located? If there is no repository, how have IBIS specific issues been handled before (Should I create an IBIS specific label)?

**Comment by LeighMac** [comment]
Definitely IBIS specific.

L

**Comment by LeighMac** [comment]
I can show you at 2pm today if you are available, Santiago.

L

**Comment by cmadjar** [comment]
@SantiagoTG here is the URL for the IBIS repo. It is a private repo.

https://github.com/aces/IBIS

**Comment by SantiagoTG** [comment]
Yes, that would be great. I will hold creating any new issues until then (I
will still look through them in the meantime).

Thanks!!
