### ISSUE TITLE
[DQT/CouchDB] Candidate/timepoint no longer in SQLDB present in DQT

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#5071]
DQT still shows results for candidates and/or timepoints that are already deleted from mySQL even after running CouchDB_Import_Demographics.php script

*by 'delete' , it means hard delete, not inactive candidate*

original redmine: https://redmine.cbrain.mcgill.ca/issues/14118

**Comment by zaliqarosli** [comment]
also related redmine, somewhat duplicate https://redmine.cbrain.mcgill.ca/issues/13967

**Comment by ridz1208** [comment]
duplicate of #6566
