### ISSUE TITLE
[mri_violations] data table bugs

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#5075]
1. impossible to scroll to the right of the data table when the browser is smaller than the data table (jumps back to the left when scrolling to the right). Happens 9 times out of 10. [Chrome and sometimes Firefox]
2. same bug as describe above but for page MRI Protocol Violations, second data table [Chrome]

original redmine: https://redmine.cbrain.mcgill.ca/issues/14891

**Comment by SantiagoTG** [comment]
This issue still occurs for specific results and not others. ie. when searching for 'Visit label Visit1 does not exist in Visit_Windows', the table jumps back to left when scrolling right. This does not happen in other cases (ie. when searching for 'Protocol violations', table can be scrolled to the left).

**Comment by SantiagoTG** [comment]
https://github.com/aces/Loris/issues/7203
