### ISSUE TITLE
Data Entry Breadcrumb - Redirects to Dashboard instead of Top page of instrument

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5077]
When within an instrument, if you click the title of the instrument (most recent breadcrumb), it should redirect to the Top page of the instrument, but instead redirects to the Dashboard.

**Comment by sruthymathew123** [comment]
@SantiagoTG  I cannot recreate the issue; Is it still the case?

**Comment by SantiagoTG** [comment]
This is no longer an issue.
