### ISSUE TITLE
[Media] Update file does not refresh page or bring you to main Media page

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5079]
~If you hit the "Update file" button while editing an uploaded file, it does not refresh the page to confirm a successful update or send you to the main page.~

NEW ISSUE: see comment below 

Related issue: https://github.com/aces/Loris/issues/5055

**Comment by ridz1208** [comment]
It now displays a swal confirmation and automatically updates the menu filter however the message is incorrect...

![image](https://user-images.githubusercontent.com/15268287/149342853-ba7cf1e9-a7f5-409a-a9cf-b22481f02133.png)

NEW ISSUE: 
 1. Upon clicking Update File the swal diplayed says "Upload successful" which could be very confusing to a user.
 2. As @SantiagoTG mentions above, the intuitive next step would be to auto-close the edit window after clicking the Update File submit button. I think it should go as follows upon a successful submission, close the editing window then display the swal instead, then closing the swal should take us back to the table directly
