### ISSUE TITLE
[Instruments] Autosave forms 

### ISSUE THREAD

**Issue by Jkat** [aces/Loris#5080]
Apparently this has something to do with caching the data locally

**Comment by ridz1208** [comment]
apparently this is already on the roadmap or something

**Comment by xlecours** [comment]
Thanks @Jkat ! 
There is now https://github.com/orgs/aces/projects/2/views/4?pane=issue&itemId=2485060 on the roadmap

**Comment by Jkat** [comment]
Progress 🙏
