### ISSUE TITLE
[Data Dictionary] - Search keyword filter does not return any rows for multiple words

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5083]
When filtering with Search keyword using multiple words, no results are returned. Also, search is very slow.

https://redmine.cbrain.mcgill.ca/issues/12910

**Comment by johnsaigle** [comment]
I'm not able to reproduce this on Raisinbread.

My steps:

1. Freshly install Raisinbread
2. Go to data dictionary
3. Type "Comments about" in the `Search keyword` field
4. Data filters correctly.


<img width="1372" alt="Screen Shot 2019-10-08 at 17 09 52" src="https://user-images.githubusercontent.com/4022790/66433525-7b33ee80-e9ee-11e9-8b52-34d1945d20aa.png">

**Comment by johnsaigle** [comment]
@HenriRabalais Can you verify whether this is an issue during v22 testing?

**Comment by johnsaigle** [comment]
Closing this due to lack of feedback and because I wasn't able to reproduce it.
