### ISSUE TITLE
Change front-end display so users do not see modules for which they do not have any permissions (inconsistent display)

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5088]
If a user has no permissions relating to a given module (no view, no edit, no related permissions), they should not see that module in their drop-down menus.

Currently (test.loris.ca - version 18.03), it appears that this is the behavior for some modules, but not all (see screenshots).

Test: "Data Query Tool" under "Reports" menu is one module that remains visible in the menu despite removing permission. If navigating to the module, user gets a message regarding not having access and to contact administrator. It should be consistent in what happens when removing a permission.

It is preferable for users to just not see the module as opposed to getting an error message because if they do need access, they'd have to contact the coordinator regardless. So if there is no difference, best not to clutter up user menus with modules they don't need to see.

![1-Module_Display_Change_Admin-UserAccounts](https://user-images.githubusercontent.com/54332302/63615278-f7937f00-c5b2-11e9-9862-23cceba4df53.jpg)

![2-Module_Display_Change_Meaghan-UserAccounts](https://user-images.githubusercontent.com/54332302/63615293-024e1400-c5b3-11e9-84e6-1437a9f2e8ed.jpg)

![3-Module_Display_Change_Meaghan-ToolsMenu](https://user-images.githubusercontent.com/54332302/63615298-05e19b00-c5b3-11e9-8f5d-acc09f881115.jpg)

![4-Module_Display_Change_Meaghan-ReportsMenu](https://user-images.githubusercontent.com/54332302/63615311-09752200-c5b3-11e9-89f0-2af97f955f99.jpg)

https://redmine.cbrain.mcgill.ca/issues/13631

**Comment by johnsaigle** [comment]
<img width="1424" alt="Screen Shot 2019-10-22 at 14 43 12" src="https://user-images.githubusercontent.com/4022790/67318996-505f9500-f4da-11e9-81f4-55e0c939620f.png">


A new user on v. 21 of LORIS with no permissions sees no menu items - so this is resolved
