### ISSUE TITLE
[Dashboard] truncated site names in "incomplete tests"

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#5097]
When a user is affiliated with 30+ sites, as of the 30th the names of the sites are no longer displayed in the list

see image both the HTML and what it looks like

![Screenshot from 2019-08-23 17-34-41](https://user-images.githubusercontent.com/15268287/63625052-6f21d800-c5cc-11e9-8e38-31d7edd2bd83.png)

**Comment by driusan** [comment]
@ridz1208 is this still an issue? I know some things were fixed for large amounts of sites on the dashboard but I don't know about this one in particular.

**Comment by ridz1208** [comment]
@CamilleBeau @jesscall this used to be an isue on CCNA, can you check if it's still the case ?

**Comment by jesscall** [comment]
With all sites permission:
<img width="458" alt="Screen Shot 2021-11-01 at 9 46 34 AM" src="https://user-images.githubusercontent.com/34260251/139681764-8bb7711f-7645-4526-8b63-4ec034112c54.png">


Without all sites permission:
<img width="467" alt="Screen Shot 2021-11-01 at 9 46 19 AM" src="https://user-images.githubusercontent.com/34260251/139681794-e7be1b1a-3bf9-4b8c-8471-ae676ca73073.png">

**Comment by driusan** [comment]
@jesscall did you comment on the right issue? Those screenshots don't look like they're related to the screenshot/description in the issue description.

**Comment by jesscall** [comment]
pretty sure it's about the incomplete forms in 'My tasks' 
@ridz1208 can you confirm ?

**Comment by driusan** [comment]
Oh, I see. And you're saying it was switched from a list to just the words "All User Sites" or "All"? In that case it sounds like we can close this?

**Comment by ridz1208** [comment]
@jesscall there used to be a way to expand the list of sites, is that gone ?

**Comment by jesscall** [comment]
@ridz1208 clicking the chevron arrow or the user sites text both bring me to the statistics page
<img width="1418" alt="Screen Shot 2021-11-01 at 2 05 29 PM" src="https://user-images.githubusercontent.com/34260251/139719115-b2134dc5-c045-4049-bfba-acda1a80dc56.png">

**Comment by ridz1208** [comment]
https://github.com/aces/Loris/blob/d2f5f581e4b95d38848e6d7de07fdd259ed40f7e/modules/dashboard/php/taskquerywidget.class.inc#L73

This seems to suggest that the full list has been removed. Issue closed
