### ISSUE TITLE
Expand 'How to create Loris module' wiki

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#5103]
How to make a LORIS module page should be expanded to cover the following parts of adding a new module to Loris:

JavaScript: use getJSDependencies() - see example in PR#1632 )
Add Permissions
Recommend View and Edit.
Consider site interactions: Should users only be able to see content from other sites if they have Access All Profiles permission?
How to modify hasAccess().
Add to the LorisMenu and LorisMenuPermissions table.
Adding Configuration settings: How to add to ConfigSetting table and then how to populate the value in the Config table (Patch and schema change).
Adding dropdown help text
How to do the SQL for this (patch and schema change)
Caveats like: "Note interactions in with key configuration variables like $useProject, when coding your queries"

**Comment by johnsaigle** [comment]
Much of the information about structure can come from the README in modules:

https://github.com/aces/Loris/blob/master/modules/README.md

**Comment by johnsaigle** [comment]
Some of these are covered by #6048. I'll add the missing points.

**Comment by driusan** [comment]
@LeighMac can you confirm that #6048 covers the problems you were having?
