### ISSUE TITLE
Form not set in new module structure

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#5104]
Dave introduced new module structure in https://github.com/aces/Loris/pull/2166
The current version works in modules that don't actually use LorisForm data (i.e dicom_archive).

However, when trying to use new module structure in a module that relies on $this->form, I discovered that this var is not properly populated, hence breaks the module's formForm not set in new module structure

**Comment by johnsaigle** [comment]
Was this migrated for Redmine?

**Comment by johnsaigle** [comment]
@LeighMac I'm going to close this issue because I'm not aware of any broken modules. If I've made an error please re-open this issue and let us know how the problem occurs.
