### ISSUE TITLE
[instrument_list] jquery.dynamictable.js error

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#5105]
The browser console shows an error when viewing the "TimePoint Details" in the instrument_list module.
The error is produced when the user scrolls down or up and causing the table header to move.

Error output: TypeError: undefined is not an object (evaluating '$(thead).offset().top') jquery.dynamictable.js:266

Observed in Loris version 20.0

**Comment by driusan** [comment]
I'm unable to reproduce this, can someone else try to confirm it's been fixed?

**Comment by driusan** [comment]
Version of LORIS reported with isn't supported, and this doesn't seem to be reproducible with the latest version.
