### ISSUE TITLE
[Documentation] Add support policy to Readmes (Ubuntu/CentOS install)

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5109]
Add the LORIS Support policy to both: 
- [ ] main (Ubuntu) install readme
- [ ] CentOS install readme

> The LORIS team provides support for the last 2 releases of LORIS (including minor releases), and does not support pre-release development branches.

And Remove from the wiki pages: 
- [ ] [Updating your Loris](https://github.com/aces/Loris/wiki/Updating-your-LORIS) 
- [ ]  [Setup](https://github.com/aces/Loris/wiki/Setup)

moved from RM 14480

**Comment by johnsaigle** [comment]
This may be good idea to add to the issue template, maybe even instead of the install READMEs.
