### ISSUE TITLE
[DocRepo] [Documentation] missing from Readme - My Preferences email/notifications

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5110]
Add to module readme for DocRepo: 
This Readme should mention:
- [ ] My Preferences: "The history of Notifications from the Document Repository is visible in the My Preferences page.  The email address to which notifications on this module are sent is also stored in the My Preferences page."  
- [ ] Opt-in/out, i.e. : Can users can opt in/out of Doc Repo notiications?  How?

Moved from RM 1191

**Comment by h-karim** [comment]
This issue seems to be resolved through #6662 .
