### ISSUE TITLE
[DQT] Autofills email address in 'Search within instrument"

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5114]
The 'Search within instrument:' text box autofills email addresses when using the DQT. This autofilling removes all fields from being displayed in the DQT. In order to display fields, email has to be deleted, though often it autofills it again. We have to do this multiple time for each query. 
Chrome Version 75.0.3770.100. 
Issue both on MACs and PCs

**Comment by johnsaigle** [comment]
Thanks for the bug report. We should disable autofilling for these inputs.

In the meantime, you could consider disabling Chrome's autofill feature while entering DQT information: https://support.iclasspro.com/hc/en-us/articles/218569268-How-to-Disable-and-Clear-AutoFill-Info-in-your-Browser

Working in a private browser session will also prevent this from happening. 

This is an imperfect solution but it may save you a little frustration between now and when we issue a fix.

**Comment by johnsaigle** [comment]
This can probably be solved using a change similar to #6330. Because this is (hopefully) a one-line HTML fix, I'm adding Beginner Friendly.

**Comment by ridz1208** [comment]
@SantiagoTG can you confirm if this is still an issue? I dont get that problem anymore on chrome

**Comment by SantiagoTG** [comment]
Closing as no longer appears to be an issue on chrome or Firefox.

**Comment by ridz1208** [comment]
@SantiagoTG thank you for checking
