### ISSUE TITLE
[Survey Module] Fix Repetitive messages in Review page 

### ISSUE THREAD

**Issue by sruthymathew123** [aces/Loris#5116]
The text 'Unanswered questions are highlighted in red' is repeated (once in a paragraph and again in a single line underneath
![Screenshot from 2017-06-05 10_36_45](https://user-images.githubusercontent.com/23702452/63699245-6e688c00-c7ee-11e9-9efc-f158cc7c9178.png)

**Comment by VictorVermeulen** [comment]
I think I fixed this under #5532

**Comment by VictorVermeulen** [comment]
I did send a pull request for this again in PR #5543.
