### ISSUE TITLE
[Behaviour QC] Instrument Filter Not Holding the value once it is applied

### ISSUE THREAD

**Issue by sruthymathew123** [aces/Loris#5117]
Instrument Filter  not holding/displaying the values once it is applied.

**Comment by sruthymathew123** [comment]
Still an issue

**Comment by regisoc** [comment]
Cannot reproduce on my end. Looks like it was solved.
@sruthymathew123 do you remember if it was on one specific tab?
![image](https://github.com/aces/Loris/assets/25327259/cae9736a-64eb-4d97-babe-fc5901104e9d)

**Comment by sruthymathew123** [comment]
@regisoc No more an issue I think; you can close this.
