### ISSUE TITLE
[Issue Tracker] Enable markup language in comments

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5121]
Enable comments to use markup

https://redmine.cbrain.mcgill.ca/issues/11055

**Comment by johnsaigle** [comment]
* Markdown. 😄 

@maltheism tagging you just in case you're interested

**Comment by maltheism** [comment]
@johnsaigle I'm guessing this will be done similar to how the dashboard will implement markdown. I'll assign myself so I don't forget.

**Comment by driusan** [comment]
This was done in #6138
