### ISSUE TITLE
[API] Create Candidate with Wrong Project returns 500

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5131]
When creating a candidate via the api using a project that doesn't exists gives the end user a 500 Internal Error. This should instead return a 400 Bad Request error.

https://redmine.cbrain.mcgill.ca/issues/12951

**Comment by johnsaigle** [comment]
@xlecours Do you know if this is still the case as of #4244 ?

**Comment by xlecours** [comment]
It will be fix when https://github.com/aces/Loris/pull/4244 gets merged. The create candidate endpoints is still in htdocs on minor.
The new error is :
HTTP 1.1 400 Bad Request
`{"error":"No project named: $projectname"}`
