### ISSUE TITLE
[Configuration] [Study] - 'Instrument Resetting' Field Disappears

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#5133]
Testing Process:
- Inputted random string into 'Instrument Resetting' Field.
- Pressed Submit
- Refreshed Page
- 'Instrument Resetting' Input Field disappeared.

This is likely caused by an invalid value for 'Instrument Resetting'. Validation should be applied so that no value that would break the field can be submitted.

**Comment by johnsaigle** [comment]
I think that's because this field is a boolean on the back-end.

@ridz1208 Is this addressed by your fix from this week?

**Comment by ridz1208** [comment]
@johnsaigle it should be yes

**Comment by ridz1208** [comment]
https://github.com/aces/Loris/pull/5592
