### ISSUE TITLE
[Media] Testing Plan Says Instrument is Required field when it shouldn't be.

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#5136]
The instrument Field in the Upload Form of the Media Module is meant to be a required field, according to the testing plan. However, there is no front-end measure to prevent submission of the form without an instrument selected. A PR needs to be issued to fix this. Or, if the instrument field is not meant to be required, the documentation must change in the Media Module Testing plan.

**Comment by HenriRabalais** [comment]
PR Sent #5577

**Comment by driusan** [comment]
I don't think the test plan is correct. The media module is for media tied to a candidate, it shouldn't be required that it's tied to an instrument.

**Comment by ridz1208** [comment]
@HenriRabalais could you highlight where it says that the instrument should be required ?

that was never a part of the design and if thats what it says then the documentation is erroneous

**Comment by HenriRabalais** [comment]
@ridz1208 

![Required](https://user-images.githubusercontent.com/7550451/68883402-f750de80-06de-11ea-995b-bf993198295a.png)

**Comment by HenriRabalais** [comment]
New PR Sent: #5649

**Comment by driusan** [comment]
+1 for literally highlighting it.
