### ISSUE TITLE
[URL] issue on timeout/log in

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5141]
Steps to recreate:
1. Logout from Loris
2. Access xxx.loris.ca/$MODULE$
3. When presented with login page, log in
4. Note that URL is now xxx.loris.ca/main.php?test_name=$MODULE$

The modules still work as intended but this does not seem like the intended use case to append that path to

https://redmine.cbrain.mcgill.ca/issues/13520

**Comment by johnsaigle** [comment]
I don't think LORIS behaves this way anymore. This is what happens when I try the above.

1. Logout from LORIS
2. Access xxx.loris.ca/$MODULE$
3. 403 Response with link back to login page
4. Login
5. I am directed to the dashboard with `https://jsaigle-dev.loris.ca` and no params afterward.
