### ISSUE TITLE
[New Profile] refreshing the page can cause multiple candidates to be created

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5142]
When PSCID is set to sequential or random:
Steps:
1. Go to new profile
2. Fill in details
3. Hit 'Create'
4. On confirmation page, refresh, and press continue if prompted

At this point 2 candidates have been made with the same DoB and other details, but with different IDs
If possible we shouldn't allow form resubmission, theres also no way this is useful because all of the candidates won't have the same DoB.

It is possible this behaviour also exists on other forms throughout LORIS

Update by Dave McFarlane - To fix this we may need to add a CSRF token middleware, which probably isn't going to happen for this release [20.0].

https://redmine.cbrain.mcgill.ca/issues/14725

**Comment by driusan** [comment]
This was fixed by #5808
