### ISSUE TITLE
[Timepoint List] Inactive tests still show up on timepoint instrument list

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5143]
Tests marked as inactive in the test_battery table are still showing up on candidate's batteries.

https://redmine.cbrain.mcgill.ca/issues/15168

**Comment by ridz1208** [comment]
@SantiagoTG still showing up on existing batteries? or still being populated on new batteries ?

the former is normal and actually the desired behaviour, test should be manually deleted if there is a need for it. the latter is a bug

**Comment by SantiagoTG** [comment]
@ridz1208 unfortunately I only migrated this ticket from redmine to Github, so I am not sure of the particular intent when the issue was created by Zain. As you mention, I would presume you would manually delete tests to avoid having them in the battery.

**Comment by driusan** [comment]
Seems to be the former
