### ISSUE TITLE
[Behavioral Feedback] Display issues with long field names

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5144]
When feedback is provided for a given instrument for a field with a long name, the action tab overflows off the screen and closing threads becomes impossible from the front end
Proposition to move away from the table formats in BHV Feedback and instead render items in a collapsible list

https://redmine.cbrain.mcgill.ca/issues/14523

**Comment by miladheshmati** [comment]
I tried to find the issue with different instruments but the feedback is fine now and no similar issue occurred.
