### ISSUE TITLE
[Timepoint List] Cannot see View/Edit Candidate Parameters & Create Timepoint buttons even with correct permissions

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5146]
When in timepoint_list, cannot see View/Edit Candidate Parameters & Create Timepoint buttons for candidates at other sites even with correct permissions (Across All Sites view candidates + Edit Candidates/Candidate Parameters). Adding highlander permission makes them appear but should not be required.

This was replicated on IBIS-dev, CCNA-dev and test.loris

Update by Xavier Lecours - There is no permission that allow to do that. The only ways to have the buttons appear is to be highlander OR be of the same site and have candidate_parameter_view/edit.

Update by Rida - It sounds like its like that by design but users with accross all sites should logically be able to access

https://redmine.cbrain.mcgill.ca/issues/14912

**Comment by driusan** [comment]
In testing 23.0 I had the opposite problem: the buttons appeared for a user with no permissions at all. I believe this issue is no longer valid.
