### ISSUE TITLE
[Behavioral Feedback] Cannot view existing feedback threads & Difficulty saving new feedback on test.loris (20.0)

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5147]
[bvl_feedback] Cannot view existing feedback threads & Difficulty saving new feedback on test.loris (20.0)

1. Cannot view threads of previously entered feedback either in the summary table or in the level-specific threads list at the bottom of the inline pane

2. When trying to enter new feedback (any level), if the Feedback Type menu is on the default "Input Errors", new thread does not save (Save button remains highlighted with blue outline but no action is taken). If you switch the Feedback Type to the other options "Scoring Errors" or "Other", you can save the thread with the different Feedback Type or switch back to "Input Errors" and the thread then saves.

3. To Be Confirmed If Bug Or Design Flaw Cannot see profile level feedback thread count in Open Thread Summary table at top of inline Behavioural Feedback pane when opened in a timepoint or an instrument (whereas you can see all levels in the summary table when on the candidate page or instrument pages)
Initially thought bug but appears to also be the case on ibis production which is on 19.0.1 so have to verify if behaviour is expected (although I don't think it is logical behaviour)

https://redmine.cbrain.mcgill.ca/issues/15216

**Comment by johnsaigle** [comment]
I'm going to close this ticket since we're not using that VM for testing anymore.
