### ISSUE TITLE
[DQT] Implement permissions on data access

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#5152]
Users that have access to the DQT are not limited to the data of the sites and projects they belong to.

These permissions should be applied on data returned to the browser

Redmine: #10851

**Comment by ridz1208** [comment]
Will be resolved by @driusan's revamp

**Comment by driusan** [comment]
It's still an issue until thats done.

**Comment by driusan** [comment]
Permissions are enforced in the backend by #8268 but since no one will use that until there's a new frontend I think this needs to stay open.

**Comment by driusan** [comment]
The frontend was merged in #8907. The new DQT still needs to be iterated on to incorporate all the information from the old CouchDB import scripts, but I think this can be closed as resolved now.
