### ISSUE TITLE
View Imaging Data Set button should not always be displayed

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#5162]
The 'View Imaging Data' button should only be displayed on the Timepoint list page if the user has access to the imaging browser module (the exact rules will have to be determined). This would be consistent with the behaviours of buttons 'Create Time Point' and 'Edit Candidate Info', which are only displayed if the user has access to these features.

Original Redmine ticket: https://redmine.cbrain.mcgill.ca/issues/11229

**Comment by driusan** [comment]
Dupe of #5132
