### ISSUE TITLE
Imaging uploader - Incremental search in filter does not work

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#5164]
Found on IBIS during version 20.0 tests:

1. Access the imaging uploader
2. Go to, say, page 6.
3. Try using the filter to search for a CandID that you know has a scan in the search table. It should return nothing. It is as if the incremental search only works when you are initially on page 1.

Original Redmine ticket: https://redmine.cbrain.mcgill.ca/issues/14925

**Comment by johnsaigle** [comment]
This seems to work properly as on aces/minor at LORIS v 21
