### ISSUE TITLE
Access Profile - Sorting for column PSCID is flaky

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#5165]
This was found during testing of IBIS 20.0 on IBIS staging:

I logged in as a user with all the permissions. When I accessed the candidate page and tried to sort the result table according to column PSCID, the three candidates with PSCID '0000', '1' and '2' were always the first three, irrespective of the sorting order.

Original Redmine ticket: https://redmine.cbrain.mcgill.ca/issues/15902

**Comment by johnsaigle** [comment]
Not sure about IBIS, but this seems to be fixed on demo and my VM as of LORIS 21.

If this issue reappears, please reopen the ticket.
