### ISSUE TITLE
MRI Protocol checks - Filter values not set properly

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#5166]
I go to the MRI violations page and search for violations with type of problem set to 'Protocol Violations'. I click on one of the links in the search result table and I am taken to the MRI protocol checks page. The search results on that page are displayed properly but the values that are set in the filter are wrong: the patient name and DICOM series UID are OK but the Tarchive ID and CandID are always empty (they should be filled with the appropriate values according to what was clicked on the MRI violations page).

Original Redmine ticklet: https://redmine.cbrain.mcgill.ca/issues/15909

**Comment by driusan** [comment]
mri_violations module was completely rewritten for 25, so this shouldn't be an issue anymore.
