### ISSUE TITLE
MRI protocol checks - Edit of mri_protocol table not bulletproof

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#5167]
When on the MRI protocol checks page, one can enter invalid values when editing the mri_protocol table: I was able to edit the ID of one of the lines and set it to an already existing ID (the system accepted the edit but silently set the new ID to 0...) I was also able to change the scan type ID value to a scan type ID that does not exist.

Original Redmine ticket: https://redmine.cbrain.mcgill.ca/issues/15912

**Comment by cmadjar** [comment]
I think this issue does not apply anymore since that table is not editable through the front end anymore.
