### ISSUE TITLE
Configuration - Setting can be deleted without clicking 'Save'

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#5168]
When a setting can have multiple values, you have to click 'Add' to add a new setting to the set but it will only be saved after you click 'Save'. When deleting, the delete occurs immediately without having to 'Save'. Inconsistent?

Found during testing of version 20.0 on IBIS stg.

Original Redmine ticket: https://redmine.cbrain.mcgill.ca/issues/15916

**Comment by CamilleBeau** [comment]
Related to #5132

**Comment by nicolasbrossard** [comment]
The inconsistency described in this ticket is still there as of 2024SEP17 but does that really need fixing? tagging as 'Discussion required'

**Comment by racostas** [comment]
This was resolved already !
