### ISSUE TITLE
[Issue tracker] - Build "Related issues" algorithm

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5173]
Caitrin's plan was to use an ML/associative algorithm to detect "Related or similar tickets" based on search terms. Akin to Related issues on search bar on Github.

Implementation to be determined

https://redmine.cbrain.mcgill.ca/issues/11061

https://redmine.cbrain.mcgill.ca/issues/11064

**Comment by driusan** [comment]
I doubt this will ever happen
