### ISSUE TITLE
[Configuration] Should be able to assign a Project from the Subproject Configuration screen

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5176]
e Subproject Configuration screen should allow the user to select the Project it relates to.

We need a drop down box with the current list of Projects.

https://ibis-stg.loris.ca/configuration/subproject/

This will avoid having to do this extra step as mentioned in the help section.

Define all projectID-subprojectID relationships by populating the project_rel table, e.g.

INSERT INTO `project_rel` VALUES (1,1),(1,2),(2,3);

https://redmine.cbrain.mcgill.ca/issues/10850

**Comment by ridz1208** [comment]
@SantiagoTG given the hierarchy of projects/subprojects it was implemented in a different way where the project config allows you to select subprojects. nonetheless, you dont need to do it manually anymore.

closing issue
