### ISSUE TITLE
[UI] UI Bug in lost_password.php page

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5177]
The 'navbar-brand' class exposes an faulty UI behaviour on lost_password.php. It has been tested both on my localhost and on the test.loris.ca VM (both Chrome and Firefox browsers). See attached images

![lostpass](https://user-images.githubusercontent.com/54332302/63873454-a2c67e80-c98d-11e9-806f-84fc19c26a90.png)
![lostpass2](https://user-images.githubusercontent.com/54332302/63873455-a2c67e80-c98d-11e9-86cb-7d60021235a3.png)

https://redmine.cbrain.mcgill.ca/issues/8550

**Comment by johnsaigle** [comment]
This does not reflect the current LORIS UI
