### ISSUE TITLE
[Instrument Manager] - Improvements

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5178]
When uploading *.linst file there is no user feedback, so it appears to user that nothing happened.
once instrument was installed: display a success message (might want to highlight the added row in instrument list table)
if existing instrument is added notify user instrument already exists
if invalid file format is uploaded display error message
Other issues:
cannot sort list of instruments by column other than "Instrument" (example: sorting by "Instrument Type" does not work)

https://redmine.cbrain.mcgill.ca/issues/7299

**Comment by johnsaigle** [comment]
I believe this is resolved by #4181 and Reactification.
