### ISSUE TITLE
[Genomic Browser] No data in GWAS, CNV, and Methylation tabs for testing

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5180]
There is no data in the GWAS, CNV, and Methylation tabs of the Genomic Browser.
We need to add data so that we can properly test these tabs (e.g. data filtering, data tables, data download)

https://redmine.cbrain.mcgill.ca/issues/14819

**Comment by christinerogers** [comment]
Will be covered in part by @AlexandraLivadas  in #6881

**Comment by driusan** [comment]
#6881 is merged
