### ISSUE TITLE
[Help Editor] Put Last Updated date back at bottom of inline help pages

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5185]
Put Last Updated date updated back at bottom of inline help pages - No longer appears since switch to populate content from Git markdown files

https://redmine.cbrain.mcgill.ca/issues/14827

**Comment by laemtl** [comment]
We need to discuss if we prefer to put back the last edited date or edit the Test plan to remove its mention instead.

**Comment by ridz1208** [comment]
#6969

**Comment by ridz1208** [comment]
resolved (see linked issue)
