### ISSUE TITLE
Create user UI not showing mandatory fields.

### ISSUE THREAD

**Issue by racostas** [aces/Loris#5218]
Hi Loris team,

This is a minor issue I think could be quickly solved as it is properly addressed in other modules.

**Description:**
When creating a new user the mandatory fields are not explicitly highlighted. Please see the image attached. I do notice that in other modules (create candidate for example) this was already addressed. It will be very nice if this 'feature' could be included on this module also.

Thanks and congrats for the nice job.

![cretateUser_notShowingMandatoryFields](https://user-images.githubusercontent.com/37309344/64620915-bec91780-d3b2-11e9-8860-1c1f2ffe8118.png)

![cretateCandidate_showingMandatoryFields](https://user-images.githubusercontent.com/37309344/64620940-cbe60680-d3b2-11e9-8c09-4bd141218636.png)

**Comment by johnsaigle** [comment]
I think this module isn't yet Reactified and so doing the field highlighting may not be possible until after that point.

**Comment by laemtl** [comment]
Is this something we want to solve before rectification? 
It can be easily fixed with label editing.

**Comment by johnsaigle** [comment]
If you feel it's an easy fix then I think there's no harm in going for it! 

It may get replaced by React code at some point but as far as I know that won't be happening for a while anyway. So it's probably worth fixing in the meantime.
