### ISSUE TITLE
[Feature] Support international languages in LORIS

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#5223]
### Feature Suggestion (Multiple Languages Support)

The [react-intl](https://github.com/formatjs/react-intl) would help with the task of making the user interface in LORIS have multiple language support.

Every LORIS frontend module in react will need to be wrapped by the component:
`
<IntlProvider
                locale={languageKey}
                defaultLocale={defaultLanguage}
                key={languageKey}
                messages={translations[languageKey]}
            >
                <ModuleComponent/>
</IntlProvider>
`

Inside the LORIS package.json scripts:
`
"locales": "node ./translationRunner.js",
 "translate": "npm run messages; npm run locales"
`

Lastly needed is additional directory structure in LORIS "translations/messages/fr.json", "translations/messages/whitelist_fr.json" and "translations/locales.js" that will handle the frontend translated text.

Example inside react component:
`
<FormattedMessage id='app.footer.logout' defaultMessage='Logout' />
`

Example inside translations/messages/fr.json
`
  {
     "app.footer.logout": "Déconnexion"
  }
`

Note: As discussed with @ridz1208 this will not help much with the instruments but will be great for the rest of LORIS.

**Comment by driusan** [comment]
We have no plans to add this dependency, but languages are slowly being implemented as of #4976
