### ISSUE TITLE
[API] Have the EEG queryable via the API

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#5235]
Need to modify the API to be able to query electrophysiology datasets.

**Comment by cmadjar** [comment]
@xlecours maybe we could meet some time next week or the week after to see what would need to be done for this?

Thanks!

**Comment by xlecours** [comment]
@cmadjar The obvious answer would be : "The same way it is done in the EEG module ( #5230 )"
Let's have a quick chat about it.

**Comment by cmadjar** [comment]
PR still in review...

**Comment by cmadjar** [comment]
Yahoooo! Tigidoooo!! It's merged!!! :-D
