### ISSUE TITLE
[docs][GoogleSoD] Update Help text : Phase 1

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5241]
Phase 1 of updating all the Help text (#5211) : High priority edits/updates: 
     * All changes should be made to the `minor` branch (TBC w Rida) 
     * recommended to do 1 PR per file/module for `a`/`b` so you can assign individual (module-expert) reviewers
      * Point `d` (and maybe `c`) might be postponed phase 2, because changes across many modules can be painful to review/rebase/merge.

Tips: 
* Especially for readability/formatting points `c` and `d`, the Dashboard's Help is a decently formatted example (headers not too big, linebreaks exist, so text is decently readable)
* Checking/Testing how the help text renders requires working with a dev and their sandbox 
* Testing how the markdown actually renders in the front-end Help Dropdown is key - we'll find a sandbox/VM you can work with 
* Ideally we'll set you up to use the Help Editor module in a Loris sandbox - the fastest way to both edit and check the front-end rendering for Help markdowns.  

`a.` Add Help content for new modules (or any other modules missing content)
- [x] _Imaging_QC module: Add help content for this brand-new module #5672
- [x] Survey module : #5671
     * recover old/lost Help text if possible currently no help text (but did it ever? first, check old history on GitHub
    *  the module spec was previously (erroneously) displayed as help text, removed by #5207

`b.` Improve readability, spacing, simplify language -- see recent DQT help commits by CR
- [x] DQT :  #5697
- [x] Access Profiles / candidate_list : #5606

`c.` Remove references to "Show data" (button taken out when Reactifed)
- [x] [These 11 Help markdowns (see this search)](https://github.com/search?p=1&q=%22Show+Data%22+repo%3Aaces%2FLoris++language%3AMarkdown+-filename%3A%22TestPlan.md%22+language%3AMarkdown+language%3AMarkdown&type=Code) refer to a "Show Data" button for filters.  
     * Remove this reference if the Demo module does not have a "Show Data" button in the module's selection filter panel.
    * Some un-reactified modules may still have a `Show Data` button at release 22, e.g. DICOM archive

`d.` Make the formatting consistent: 
- [x] add linebreaks and/or bolding to give visual structure to run-on paragraphs like Conflict Resolver / User Accounts 
- [x] Change H2 headers to H3 to make the markdowns more readable. 
(updates from late Sept:)
- [x] update the voice (e.g. `you`) 
- [x] Draft a **Style guide** : to be committed to this repo as a markdown. 
     * a few brief bullet-point guidelines on how to style/write Help text

For @knoll-alex // Google Season of Docs

**Comment by johnsaigle** [comment]
I'm going to close this as it's written more as an email for a specific person and role rather than as a general issue.

`a.` is covered by existing issues and PRs

`b` and `d` can be condensed into a general "Cleanup markdown and make sure it renders well" issue

`c`has its own issue in #5410

**Comment by christinerogers** [comment]
re-opening.  will be tied and closed as it gets covered and resolved with PRs sent, with input from @knoll-alex

**Comment by christinerogers** [comment]
early november updates: Help commits should go to `22.0-release` branch through Nov. 15 (at least)

**Comment by christinerogers** [comment]
Closing, almost all deliverables Merged and resolved. 
See #5576 for outstanding...
