### ISSUE TITLE
[tools/install.sh] not working like before

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#5244]
I've been using the tools/install.sh to generate the config.xml inside the project directory. 

Changes have been made to install.sh and now the script will stop before making the config.xml file unlike before. 

Basically if a "user_uploads" directory already exists and this can be in the document_repository or the data_release module. I would prefer the script to just skip the create directory commands if the directories already exists. Otherwise I have to manually delete the directories before I can run the script again and unlike before.

Also the script is reporting:
> mkdir: cannot create directory ‘../modules/document_repository/user_uploads’: File exists
Note: user_uploads is not a file.

**Comment by johnsaigle** [comment]
Related-ish: #5062

**Comment by johnsaigle** [comment]
Opened #5245 to address this.

I'm confused about where your config file went though. Why do you need to regenerate it?

**Comment by maltheism** [comment]
@johnsaigle I usually delete project and then run the install.sh before the install

**Comment by christinerogers** [comment]
Why do you need to regenerate it though?  e.g. Are you working on a cloned VM?
