### ISSUE TITLE
Add install make, npm to LORIS 21.0 installation documentation.

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#5250]
Installing Loris in Depth:
Running the Install Script section
step 9: `Run make (for production instances) or make dev (for development sandboxes)`
Problems:
1. Run make requires `sudo apt install make` first
2. Run make requires `sudo apt install npm' first
3. make command need to be run under loris instead of under loris/tools

**Comment by christinerogers** [comment]
Thanks @coreyAbout  - Is `sudo` really required?  

we're debating it in the #5203 comments. 

cc @kongtiaowang 

To do: 
- [ ] add these points into #5203

**Comment by coreyAbout** [comment]
@christinerogers 
Ubuntu16
I think install most of, if not any, software through apt would need sudo. If I'm wrong please correct me.

**Comment by johnsaigle** [comment]
Right now we don't go "in depth" into how to get the LORIS system dependencies installed, including PHP, Apache, MariaDB/MySQL, Composer, and npm. We also don't describe how to install `apt` package such as `zip`, `make`, etc.

The process of getting an environment ready to run software is referred to as "bootstrapping" and there are many approach to this, such as containerization (e.g. Docker, Vagrant), package managers (e.g. a `sudo apt install loris` Debian package, etc.

This is a long-standing issue. See #4433. 

To respond to the above points:
* `sudo` should not be required for anything in the `install.sh` script. 
* `apt install ...` will always require sudo. I believe the same is true for e.g. CentOS with `yum` but I don't have experience with those systems.

**Comment by coreyAbout** [comment]
@johnsaigle Thanks for the comment. Right now we DO have guidelines on how to get LORIS system dependencies installed. Check it out here: https://github.com/aces/Loris/wiki/Installing-Loris-in-Depth#getting-prerequisites
All those are how to install dependencies and are well documented, except for the make and npm.
Anyway, you have a nice idea to have bootstraps packed up there.

**Comment by johnsaigle** [comment]
You're right, there is that Wiki page. It's incomplete though, and out of date as you've noted.

**Comment by johnsaigle** [comment]
This should now be clarified by the new install documentation.
