### ISSUE TITLE
Add bullet points to React Markdown rendering in LORIS

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5259]
@knoll-alex 
> Does all of markdown work within LORIS?

No, at this time only a subset of Markdown works within LORIS:

https://github.com/aces/Loris/blob/3d6d2a060e349b34093146134e13caff440747e3/jsx/Markdown.js#L7-L12

So it looks like we don't support formatted bullet points at this time.

I'll create a new issue proposing that we add bullet points. I think it would be useful.

_Originally posted by @johnsaigle in https://github.com/aces/Loris/pull/5258#issuecomment-537563146_

**Comment by maltheism** [comment]
I'll try to implement this feature.

**Comment by knoll-alex** [comment]
Hello! Wondering what sort of timeline this might be on? I'm going to be updating all the helptext over the next couple weeks and this feature would be super helpful. Thanks.

**Comment by johnsaigle** [comment]
Hi @knoll-alex! @maltheism will have to answer ultimately but development could potentially be delayed since we are in the middle of release testing. That means that new features will probably get pushed until the next release -- but with luck perhaps we can sneak this in.

**Comment by maltheism** [comment]
@knoll-alex the issue might get held back as @johnsaigle mentioned it being release testing. I'll try to work on the bullet feature when time permits. I suggest you write Markdown with bullets when needed and the PRs can be merged in after this feature has been implemented.

**Comment by johnsaigle** [comment]
I agree; go ahead and format it with bullet points for now and we'll make sure they work later.

**Comment by johnsaigle** [comment]
@knoll-alex A pull request has been opened to add this feature. It will likely be released in LORIS version 23... so not for (likely at least a few months) unfortunately.

https://github.com/aces/Loris/pull/5542
