### ISSUE TITLE
[tools/install.sh] broken on macOS

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#5262]
Latest changes to the install.sh script on minor has broken the script on macOS.

Output after running the script:

> ./install.sh: line 156: hostnamectl: command not found

**Comment by johnsaigle** [comment]
Since which change? `hostnamectl` has been used since January in #4113. Before that was `lsb_release` for 5 years (#1025) which also doesn't exist on macOS. 

It's possible that the fall through case doesn't work anymore?

**Comment by maltheism** [comment]
@johnsaigle I'm guessing the fail through case isn't working anymore.

**Comment by johnsaigle** [comment]
> As a side note my IDE says "Don't quote right-hand side of =~, it will match literally rather than as a regex " on lines 157, 167, 185, 187, and 231.

Fixed by #5204.

Otherwise not sure.

**Comment by maltheism** [comment]
@johnsaigle I just checked out her PR and I'm still getting the error:

> ./install.sh: line 158: hostnamectl: command not found

I'll see if I can find a workaround for a fix.

**Comment by johnsaigle** [comment]
Yes that error still exists because `hostnamectl` is not a program that exists in macOS. It should fix what I quoted about your IDE warnings.
