### ISSUE TITLE
[Dashboard] Investigate discrepancies for total displayed for "Incomplete Forms" and "Violated Scans" in Dashboard

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5289]
Please investigate discrepancies found in dashboard display for Incomplete Forms and MRI Violation.

Violated scans - Total displayed 10,828. Total in MRI Violated Scans module = 16,834, minus 5,953 for phantom scans, minus 32 for non-phantom DCC entries = 10,859. Unsure of where difference of 31 scans is coming from. 

Migrated from: https://redmine.cbrain.mcgill.ca/issues/14106

**Comment by SantiagoTG** [comment]
This issue is still relevant for v23.0 release.
Dashboard MRI Violated Scans Count = 198
MRI Violated Scans Module Count = 206

**Comment by driusan** [comment]
PR merged
