### ISSUE TITLE
Remove cat command in raisinbread README

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5294]
Done, thanks!

It turns out that `cat`-ing the files together makes everything WAY slower, like several minutes on my VM.

The for loop executes in a few seconds though. 

We should consider just recommending the for loop method in the README since it also gives error handling in addition to being faster.

_Originally posted by @johnsaigle in https://github.com/aces/Loris/pull/5260_

**Comment by johnsaigle** [comment]
As we talked about in person I think it's because each and every line from the SQL files must be `cat`-ed together in memory and that takes a really long time.

If you test #5260 you'll see that it's much faster and it uses the for loop method instead.

**Comment by johnsaigle** [comment]
Nevermind I was wrong, my script wasn't working 😅

**Comment by ridz1208** [comment]
................ @johnsaigle you gave me so much hope :disappointed:
