### ISSUE TITLE
On The Subject of Sudo -- a brief essay discussing UNIX permissions for LORIS

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5297]
There has been a lot of discussion across various pull requests on the subject of `sudo` in LORIS, specifically during the install process.

Since the conversation is getting a little lost within the PR threads and somewhat hidden as new commits get added, I thought it would be best to summarize what's going on here.

### Sudo and why to avoid it

* This command originally stood for "superuser do"; effectively, anything that is executed with sudo is the same as running it as `root`.
* This gives a user with sudo privileges, _or a process running with these privileges_, **full control** to do whatever they want on a system
* For this reason it's considered bad to use `sudo`/`root` unless absolutely necessary because you can accidentally break things and subvert *nix systems' warnings not to take risky action.
    * It also violates the [security principle of least-privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege) 
        * > "every module (such as a process, a user, or a program, depending on the subject) must be able to access only the information and resources that are necessary for its legitimate purpose"

### LORIS and Sudo

Currently `sudo` is used somewhat in order to install LORIS. Usage falls into one of a few categories:

1. Changing file permissions (e.g. `chmod` to change smarty folders to be writeable/readable by the Apache user)
2. Configuring Apache (e.g. `a2enmod` to enable an Apache module)
3. Installing a package (e.g. `sudo apt install make`)

#### Current approach

Right now our documentation will tell you to do the following: 

- As `root` create `lorisadmin` then give `lorisadmin` sudo privileges
- Run install.sh as `lorisadmin`
- As `lorisadmin`, use `sudo` to do any task of 1-3 above
- Also, the script will fail when run as root

The last step was added recently because running as  `root` would create files that only `root` could access, breaking them from being read by `lorisadmin` or Apache.
On CentOS, even running the install script with sudo will create subdir with `root` ownership, thus only accessible by `root`

#### My proposed approach

I believe our requirements are the following:
* No files should be owned by root
* Root is needed during the install only
* All files should be readable/writable by `lorisadmin`
* Some files should be selectively readable/writable by the Apache user
    * Currently: `user_uploads/` under document_repository and data_release; `project/`; `logs/` (unused); and `smarty/templates_c`.

### So here's what we need to do:

- [ ] Do not give `lorisadmin` sudo.

- [ ] `root` account should be used only during install. This means it SHOULD run `install.sh` as well as related commands. (This also goes for the bootstrap script if it ever gets merged.)

- [ ] The install script should be patched to properly `chmod`/`chgrp` all the files it touches so that we don't encounter the error where files are owned by root and therefore inaccessible. 

- [ ] All of this must be reflected in the install documentation.

---

Related topics:

Discussions in install documentation rewrite: #5203 

More UNIX permissions to fix: #5057 

Bugs related to this: #5008 

This should also be updated if this goes through: #5253

**Comment by ridz1208** [comment]
@johnsaigle my name is Rida Abou-Haidar and I support this message.

Item #1 from your checkboxes is the current practice for production environments and staging I believe.

**Comment by johnsaigle** [comment]
@ridz1208 Good to know. It would be good to clarify this in our documentation for external developers though because they may not have that same IT policy in place.

**Comment by christinerogers** [comment]
This should be applied to Loris-MRI too.

**Comment by PapillonMcGill** [comment]
I do support this approach even if I am not running for any political appointment.

**Comment by johnsaigle** [comment]
I think this was more or less implemented in the linked PRs.
