### ISSUE TITLE
[modules/data_team_helper] table links broken for instruments

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#5312]
The Data Team Helper module appears to have broken links for instruments when clicking the links on the table. I'm using the RasinBread Setup for testing and I'm on the major branch.

**Comment by ridz1208** [comment]
@maltheism could you reproduce on demo and post the broken links here

**Comment by maltheism** [comment]
@ridz1208 seems to work on demo. I'll debug my sandbox some more.
