### ISSUE TITLE
Add phan rule `PhanTypeArraySuspiciousNullable` and make pselect return an array

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5318]
I'm readding the phan rule `PhanTypeArraySuspiciousNullable` for this PR. It's causing a ton of errors and isn't worth holding up the release schedule.

The majority of them come from the user of `pselect()` because it has a mixed return type. When code tries to access array values from its results, phan complains because `pselect` could in theory return null.

In another PR soon we can add an array return type to `pselect` and re-add the `PhanTypeArraySuspiciousNullable` rule in one go. This will be much easier to manage and review than doing so here.

_Originally posted by @johnsaigle in https://github.com/aces/Loris/pull/5304#issuecomment-542395196_

**Comment by driusan** [comment]
The phan rule is currently enforced.
