### ISSUE TITLE
[make checkstatic ] ERROR: Phan 2.x requires php-ast 1.0.1+ 

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#5335]
I'm getting the error below on major when running the command: make checkstatic

> ERROR: Phan 2.x requires php-ast 1.0.1+ because it depends on AST version 70. php-ast 0.1.5 is installed.
> Exiting without analyzing files.
> make: *** [checkstatic] Error 1
>

**Comment by johnsaigle** [comment]
You'll have to install `php-ast`. It's a developer dependency.

**Comment by maltheism** [comment]
thanks @johnsaigle, I guess I do have it installed but v0.1.5 is now not good enough. I'll try installing the latest one and see from there.
