### ISSUE TITLE
Create Utility function for checking User and TimePoint share a site

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5343]
```php
                || ((in_array(
                    $timePoint->getData('CenterID'),
                    $user->getData('CenterIDs')
                ))
```

We should create a Utility function for this idiom. It's used in a lot of places and doesn't look very good in the code.

_Originally posted by @johnsaigle in https://github.com/aces/Loris/pull/5230_

**Comment by johnsaigle** [comment]
e.g.

`Utility::shareSite(\User $user, \TimePoint $timepoint);`

A `shareProject()` may be useful too...

**Comment by driusan** [comment]
I don't think it makes sense to do this in Utility instead of just adding appropriate getters to the User or TimePoint class.. what's wrong with using `$user->hasCenter($timePoint->getCenterID())`? (both of those functions already exist.)

**Comment by johnsaigle** [comment]
Good point, hadn't considered it.
