### ISSUE TITLE
[Access Profile] Links to Candidate/Subject profiles generated improperly on major

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5346]
Every link in the `candidate_list` table is `https://whatever.loris.ca/undefined/`.

Visiting a candidate/subject directly, e.g. with `https://whatever.loris.ca/676061/` still works.

**Comment by driusan** [comment]
What branch is this on? @HenriRabalais said something about the DataTable optimization work breaking something that formatColumn uses, which might be this. @HenriRabalais, can you chime in?

**Comment by johnsaigle** [comment]
It's on the major branch. Just updated the ticket title for clarity.

**Comment by johnsaigle** [comment]
@driusan @HenriRabalais The same issue is also occurring for all links in the Issue Tracker.

**Comment by johnsaigle** [comment]
Actually I think it's happening for all links in tables... It seems like the JavaScript for most of these modules assume the existence of an array containing string keys but they instead contain numeric indices.

**Comment by johnsaigle** [comment]
This was resolved at some point during the 22.0 release testing.
