### ISSUE TITLE
[21.0] [access_profile] "Visit Label" in Selection Filter no longer a dropdown

### ISSUE THREAD

**Issue by leighevans** [aces/Loris#5359]
it's now a textbox instead of a dropdown which could be an issue for users since the visits have backend naming conventions
![Screen Shot 2019-10-22 at 1 53 54 PM](https://user-images.githubusercontent.com/32552953/67409626-d0dccf00-f588-11e9-9ed6-95d2f589ee6c.png)

**Comment by driusan** [comment]
merged
