### ISSUE TITLE
[21.0] [access_profile] Can't open any candidate profile without "across all sites access candidate profiles"

### ISSUE THREAD

**Issue by leighevans** [aces/Loris#5360]
Unable to access any candidate profile, despite having all site affiliations, without "Across all sites access candidate profiles". The PSCID is un-clickable and you cannot open the candidate's profile to see their timepoints/do data entry etc. without this permission. 

![67125451-cd30fd00-f1c2-11e9-91be-01be6334549e](https://user-images.githubusercontent.com/32552953/67409888-35982980-f589-11e9-93c8-cd55aec8fa5f.png)

**Comment by driusan** [comment]
This is a behaviour change, not a bug, but Samir approved the change of behaviour.
