### ISSUE TITLE
[21.0] [data_team_helper] Pagination issues

### ISSUE THREAD

**Issue by leighevans** [aces/Loris#5377]
The ellipses between the button for page 4 and the last page is unresponsive and thus cannot access any pages in between. Also clicking on pages 2,3,4 etc. doesn't highlight in dark blue to indicate which page you are currently on (as it does for page 1), even though the page does change content.

**Comment by maltheism** [comment]
@leighevans I think this is fixed in https://github.com/aces/Loris/pull/5330

**Comment by maltheism** [comment]
@johnsaigle I think the data_team_helper is the module the issue is referring about pagination issues. I know that was a problem when I was rewriting the module.

**Comment by johnsaigle** [comment]
Oops sorry I totally misread the title. 😆

**Comment by driusan** [comment]
@maltheism that PR has conflicts and isn't going to the release branch
