### ISSUE TITLE
[Install] Remove is-writable check for logs/ directory 

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5382]
As I noted above I'm not sure why the `tools/logs/` directory wouldn't be writable since it's created by the install script. However, we can punt this to another issue so that this PR isn't delayed anymore.

_Originally posted by @johnsaigle in https://github.com/aces/Loris/pull/5205/review_comment/create_

**Comment by maltheism** [comment]
@johnsaigle I'm getting `-rw-rw-r-- 1 lorisadmin lorisadmin 1455 Oct 22 14:36 install-2019-10-22T14:36:16.log` and I don't see what the problem is here?

**Comment by johnsaigle** [comment]
Since the script creates the log directory in the first place, I don't see why the same script wouldn't be able to write to it.

**Comment by maltheism** [comment]
@johnsaigle do you know if this is still an issue. I don't believe it is and I'm wondering if I should close.

**Comment by johnsaigle** [comment]
We can probably close it. The check is probably unnecessary but it's not doing any harm either.
