### ISSUE TITLE
Accessing loris via IP breaks interface if configured via hostname and vice-versa if configured via hostname

### ISSUE THREAD

**Issue by gdevenyi** [aces/Loris#5395]
Main login page is okay but after logging in page rendering is broken in various ways:
![image](https://user-images.githubusercontent.com/3001850/67804810-13f5e100-fa66-11e9-9758-6cf2445d1e1b.png)

Furthermore, my existing authentication done against one host connection doesn't translate to the other connection.

Seems like something hard-coded somewhere based on the backend configuration, other web-based systems I've used don't seem to have this sort of limitation.

**Comment by thomasbeaudry** [comment]
Maybe it's because the site is hardcoded in the config table ?

**Comment by driusan** [comment]
looks like it's not loading the CSS properly

**Comment by gdevenyi** [comment]
CCing @coreyAbout who did the install here.

**Comment by coreyAbout** [comment]
The configuration is here:
select * from Config WHERE ConfigID=(SELECT ID FROM ConfigSettings WHERE Name='url');
if this url is set to IP, the IP address will work, if this url is set to FQDN, the FQDN address will work. It would be nice if both ways work at same time. 
@gdevenyi  
Can you be more specific on 
Furthermore, my existing authentication done against one host connection doesn't translate to the other connection.
like an example?

**Comment by johnsaigle** [comment]
It looks like you need to fix the `url` or `base` config settings. @coreyAbout 

For reference, on my VM:

`base` = `/var/www/loris/` (your LORIS root folder)
`url` = `https://jsaigle-dev.loris.ca`. Note that httpS is important if you're using SSL (You should be.)

It could also be the `host` setting which I think should be your IP.

**Comment by johnsaigle** [comment]
This may also be helpful: https://github.com/aces/Loris/wiki/Project-Customization#1-database-configuration-settings

**Comment by gdevenyi** [comment]
> @gdevenyi Can you be more specific on
> Furthermore, my existing authentication done against one host connection doesn't translate to the other connection.
> like an example?

I can login via the IP instance and if I then open the hostname instance I get a login screen again, rather than the main page.

**Comment by coreyAbout** [comment]
@gdevenyi I see. It's a second stage problem after LORIS has the capacity to work via FQDN and IP at the same time.

**Comment by ridz1208** [comment]
@coreyAbout why do you want both ways to work ? cant you choose one and stick with it ?

**Comment by gdevenyi** [comment]
@ridz1208 its less I want it to work both ways, and more, "this indicates hard coded paths somewhere" which shouldn't be the case.

Other web-based things such as OwnCloud don't seem to have this issue with accessing via host vs IP, everything is transparent, so I would consider this a defect.
