### ISSUE TITLE
Remove references to "Show Data" buttons in documentation

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5410]
Reactified modules no longer have a "Show Data" button as filters are applied dynamically.

### Task

Run the command below to find occurrences the words "Show Data" in Markdown files.

```bash
git grep -n "Show Data" -- '*.md' | cut -d ":" -f1,2
```

Evaluate whether these modules still have this button; if not, update the documentation files.

---

Results of the above command on aces/master:

>modules/acknowledgements/test/TestPlan.md:7
modules/candidate_list/help/candidate_list.md:22
modules/candidate_list/help/candidate_list.md:35
modules/conflict_resolver/help/conflict_resolver.md:4
modules/conflict_resolver/test/TestPlan.md:34
modules/conflict_resolver/test/TestPlan.md:44
modules/data_integrity_flag/help/data_integrity_flag.md:4
modules/data_team_helper/help/data_team_helper.md:4
modules/data_team_helper/help/data_team_helper.md:5
modules/datadict/help/datadict.md:5
modules/document_repository/help/document_repository.md:8
modules/examiner/help/examiner.md:7
modules/genomic_browser/help/genomic_browser.md:9
modules/genomic_browser/test/TestPlan.md:80
modules/genomic_browser/test/TestPlan.md:95
modules/genomic_browser/test/TestPlan.md:110
modules/genomic_browser/test/TestPlan.md:124
modules/genomic_browser/test/TestPlan.md:141
modules/genomic_browser/test/TestPlan.md:157
modules/genomic_browser/test/TestPlan.md:174
modules/genomic_browser/test/TestPlan.md:190
modules/genomic_browser/test/TestPlan.md:208
modules/imaging_browser/help/imaging_browser.md:15
modules/mri_violations/help/mri_violations.md:4
modules/user_accounts/help/user_accounts.md:4

**Comment by cmadjar** [comment]
Note, the show data occurence of the acknowledgements module will be removed by https://github.com/aces/Loris/pull/5405

**Comment by christinerogers** [comment]
This should be linked to issue #4995

**Comment by christinerogers** [comment]
bump for an updated re-count -- since most of these should be removed merged by now (#5576)

**Comment by johnsaigle** [comment]
>modules/conflict_resolver/test/TestPlan.md:34
modules/conflict_resolver/test/TestPlan.md:44
modules/genomic_browser/test/TestPlan.md:80
modules/genomic_browser/test/TestPlan.md:95
modules/genomic_browser/test/TestPlan.md:110
modules/genomic_browser/test/TestPlan.md:124
modules/genomic_browser/test/TestPlan.md:141
modules/genomic_browser/test/TestPlan.md:157
modules/genomic_browser/test/TestPlan.md:174
modules/genomic_browser/test/TestPlan.md:190
modules/genomic_browser/test/TestPlan.md:208
modules/imaging_browser/help/imaging_browser.md:15

**Comment by johnsaigle** [comment]
Based on a quick look:

* Genomic Browser is fine because it has the Show Data button. 
* The other two still need updating.

**Comment by johnsaigle** [comment]
Imaging browser got cleaned up at some point. #5942 removes the final leftover occurrence of Show Data.
