### ISSUE TITLE
[install centOS] No package MariaDB-client available.

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#5411]
See installation instructions found here:
https://github.com/aces/Loris/blob/master/README.CentOS7.md

Output from copying the `sudo yum install MariaDB-client MariaDB-server` command:
> $ sudo yum install MariaDB-client MariaDB-server
> Loaded plugins: fastestmirror, langpacks
> Loading mirror speeds from cached hostfile
>  * base: rep-centos-ca.upress.io
>  * epel: epel.mirror.constant.com
>  * extras: rep-centos-ca.upress.io
>  * remi-php72: repo1.ash.innoscale.net
>  * remi-safe: repo1.ash.innoscale.net
>  * updates: rep-centos-ca.upress.io
> No package MariaDB-client available.
> No package MariaDB-server available.
>   * Maybe you meant: mariadb-server
> Error: Nothing to do

**Comment by cmadjar** [comment]
PR got merged so closing the issue
