### ISSUE TITLE
[install centOS] php: command not found...

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#5415]
The documentation for installing centOS found here:
https://github.com/aces/Loris/blob/master/README.CentOS7.md

The installation documentation doesn't inform the user to system link "php" after installing it. So when the user gets to the install "PHP Composer" command: `sudo curl -sS https://getcomposer.org/installer | php` the user will see the output:
```
$ sudo curl -sS https://getcomposer.org/installer | php
bash: php: command not found...
curl: (23) Failed writing body (0 != 16133)
```

Solution would be telling the user after installing php to use the command for system linking php:
`sudo ln -s /usr/bin/php72 /usr/bin/php`

**Comment by johnsaigle** [comment]
Could this be solved by 

`sudo curl -sS https://getcomposer.org/installer | php72`

?

**Comment by maltheism** [comment]
Hey @johnsaigle I just tested and still will be similar output:
`bash: php72: command not found...`

**Comment by johnsaigle** [comment]
That's weird, I figured it would be in the path.

**Comment by maltheism** [comment]
Hey @johnsaigle your comment made sense and I retested it again. php72 works and we should go with your solution. I think it didn't work for me because I removed php incorrectly and it messed up testing when I reinstalled php.

**Comment by cmadjar** [comment]
@maltheism @johnsaigle Is this still an issue or can it be closed?

**Comment by maltheism** [comment]
@cmadjar it can be closed.
