### ISSUE TITLE
[MRI Violations] No Series UID column

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5419]
There is a filter in the form called Series UID but there is no corresponding column.

Entering data in the filter still causes columns to be hidden.

Not sure if this is a code issue or something to do with Raisinbread.

Testing on `test-dev-loris.ca`.

**Comment by cmadjar** [comment]
I just tried on testing with the following SeriesUID and it returned one row: 1.3.12.2.1107.5.2.32.35412.2013121311111335572611230.0.0.0

I guess you were just not entering correct data to try it out?

Not sure if the seriesUID should be shown in the data table. It might get messy to add it.

**Comment by johnsaigle** [comment]
I found it later on a subpage of the module but it doesn't appear on the same page as the filter which is confusing.

**Comment by driusan** [comment]
Fixed by above
