### ISSUE TITLE
[MRI Violations] "Type of problem" data missing from Raisinbread

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5420]
Test Plan

> Filter for scans that violate MRI Protocol violation (For each type of Problem : Could not identify scan type, Visit Label does not exist,
Protocol Violation, CandID and PSCID do not match and CandID does not exist).

The only types that exists in the dataset are:
* Could not identify scan type
* Protocol Violation

**Comment by cmadjar** [comment]
right. I guess I'll have to insert some failed Visit label and CandID/PSCID do not match. Assigning to me for now.

**Comment by cmadjar** [comment]
@johnsaigle It took forever to do it but this is finally done! (meaning the PR #5639 was sent)

**Comment by driusan** [comment]
PR merged
