### ISSUE TITLE
[MRI Violations] Request for help with imaging testing tasks

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5422]
> 8. Verify one or two of the scans in the second table and ensure it indeed violates the MRI protocol. [Manual Testing]

> 12. Upload scan that violates the mri_protocol table and ensure it shows up in the module as 'Could not identify scan type' [Manual Testing]

> 13. Upload scan that violates the mri_protocol_checks table and ensure it shows up in the module as Protocol Violation [Manual Testing]

I am not familiar enough with imaging to test these points.  Could someone help with this?

**Comment by cmadjar** [comment]
@johnsaigle do you want to look at it with me tomorrow? This way you will know for next time :)

**Comment by johnsaigle** [comment]
I'm not in tomorrow or Friday but we could do it next week?

**Comment by cmadjar** [comment]
Sure! So far I have no other item on my calendar for Tuesday PM so your time will be mine if Tuesday PM works for you :).

**Comment by cmadjar** [comment]
@xlecours we assigned you to fix the issues with MRI violations. We can talk on Monday if you have any questions regarding this module :). Thank you!

**Comment by cmadjar** [comment]
@xlecours  oups, this one is on me. I'll sit with @johnsaigle to go over the module. You are welcome to tag along. I'll assign you other MRI violation issues though.

**Comment by johnsaigle** [comment]
The conclusion of our meeting was that these items aren't appropriate for LORIS testing and instead indicate an issue with LORIS-MRI.

**Comment by driusan** [comment]
Fixed by above
