### ISSUE TITLE
[Examiner] Saving the New Examiner certification details giving 500 error 

### ISSUE THREAD

**Issue by sruthymathew123** [aces/Loris#5423]
Testing Platform: [https://test-loris-dev.loris.ca/](https://test-loris-dev.loris.ca/)

On adding and saving certification details on a newly created examiner is giving a 500 error page.
Cases throwing Error
1) When trying to save with no certification data (500 error)
2) When trying to save data with one instrument details (500 error)

**Comment by driusan** [comment]
Fixed by above
