### ISSUE TITLE
[Test] Remove Reliability tags from test/config.xml

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5431]
This module was deleted so we don't need this information in that file.

**Comment by VictorVermeulen** [comment]
Let me try to fix this please.

**Comment by VictorVermeulen** [comment]
I forgot step 1, to fork. I did create a pull request now.

**Comment by VictorVermeulen** [comment]
I tried to delete everything and start over. I discovered that in my fork the right file is showing: https://github.com/VictorVermeulen/Loris/tree/major/docs/deprecated_wiki/Setup/Initial%20Setup/Security

However, after I fork, that file turned into a simple security file without the .md extension or any content inside. This is before I made any changes to the confix file to be clear.

A friend of mine who did run it in Ubuntu server can see the file as it should work. Can anyone with Windows see if he/she has the same problem? Thank you.

**Comment by johnsaigle** [comment]
@VictorVermeulen thanks for checking again.

In any case is it possible to make the change to the config file without adding the others to your commit on git?

`git add test/config.xml`
`git commit`
...

Let me know if I'm missing something.

**Comment by johnsaigle** [comment]
@VictorVermeulen I forgot that I actually issued a fix for this last week and I didn't link it properly.

As a result, you don't need to issue another PR.

If you're still up for it, there are other Beginner Friendly issues open that we'd really appreciate your help with. Thanks for the work you've already done.

**Comment by VictorVermeulen** [comment]
Thank you. I appreciate the patience you guys all have.

**Comment by johnsaigle** [comment]
We appreciate your contribution!
