### ISSUE TITLE
[Testing] Remove magic numbers in integration and unit tests in favor of class constants

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5432]
Many integration tests are getting stuck when data in Raisinbread changes. Part of this has to do with magic numbers.

This issue would be mitigated somewhat by changing [magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)#Unnamed_numerical_constants) into class constants so they can be updated in one place.

**Comment by ridz1208** [comment]
can you link to examples ? and @cmadjar why is this 22.0.0 testing ?

**Comment by cmadjar** [comment]
no idea why I did that... I removed the 22.0.0 testing label...

**Comment by johnsaigle** [comment]
@ridz1208 This came to mind when you were trying to get a PR relating to projects to pass travis. In that case a NUM_CANDIDATES class constant would've been more useful than a magic number in the text.

**Comment by ridz1208** [comment]
@johnsaigle thats what I thought.

In that particular case, yes constants would make it clearer but what would also be useful is for the different asserts to be split into different tests so they can all fail at once and be fixed at once rather then one at a time.

**Comment by johnsaigle** [comment]
This ticket is probably too general to be useful. I think this should be more of a guiding principle that we incorporate during code review.
