### ISSUE TITLE
[user_accounts] Can set new password to be the same as current password

### ISSUE THREAD

**Issue by leighevans** [aces/Loris#5439]
Test plan: 
15. Check that when editing a user account it is not possible to set the password to its actual value (i.e. it needs to change).

There no currently no validation on this; you can set and save a new password to be the same as the current one

**Comment by johnsaigle** [comment]
This was fixed in https://github.com/aces/Loris/pull/5370 but the PR got merged into `major`... not sure what the test VM is based off of right now.

**Comment by johnsaigle** [comment]
Also @leighevans did this occur in Edit User or My Preferences?

**Comment by driusan** [comment]
According to @johnsaigle this was fixed by #5426

**Comment by johnsaigle** [comment]
I gave @driusan bad information. This issue is actually addressed by https://github.com/aces/Loris/pull/5514/files

**Comment by driusan** [comment]
According to @johnsaigle this was fixed by #5514
