### ISSUE TITLE
[instruments] Console Output error for BMI Calculator

### ISSUE THREAD

**Issue by leighevans** [aces/Loris#5448]
Getting a console output error when trying to save BMI

![Screen Shot 2019-10-31 at 2 42 28 PM](https://user-images.githubusercontent.com/32552953/67976677-ebe4ba00-fbec-11e9-8ffb-73c6d06d49a4.png)

**Comment by cmadjar** [comment]
@kongtiaowang could this be related to the testing VM? Would you mind investigating this one? Thanks!

**Comment by kongtiaowang** [comment]
It has been fixed.

**Comment by kongtiaowang** [comment]
It has been fixed.
