### ISSUE TITLE
[document_repository] duplicate file uploading 

### ISSUE THREAD

**Issue by 3design** [aces/Loris#5453]
11. Add two files with the same name. You should get a 'duplicate file name' error. [Manual Testing]

expected results: 
when uploading two files with the same name, i get a 'duplicate file name' error' message

actual results:
when uploading two files with the same name, there is no error message. the form clears and i am still on the upload page

**Comment by cmadjar** [comment]
@zaliqarosli we assigned you the document repository issues to resolve for 22.0. If you can work on them on Monday that would be awesome! Thanks!

**Comment by cmadjar** [comment]
PS: feel free to talk with Derek (@3design) if you have questions about the design and functionality of the document repository

**Comment by driusan** [comment]
PR merged
