### ISSUE TITLE
[document_repository] user a edits while user b deletes

### ISSUE THREAD

**Issue by 3design** [aces/Loris#5456]
13. User A edits a file. User B tries to delete the same file in the meantime. Check that he can't. [Manual Testing]

expected results:
when one user edits a file, another user cannot delete the file

actual results:
while user a is in the edit screen, user b can delete the file as normal

**Comment by johnsaigle** [comment]
I think the documentation needs to be updated for this one. There aren't (maybe never have been) user permissions on the document repository to restrict a user from deleting another user's file.

**Comment by zaliqarosli** [comment]
^ yes i agree

**Comment by driusan** [comment]
Documentation updated by above.
