### ISSUE TITLE
[JSX - DataTable] Not all filtered items included in .csv when table is downloaded

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5458]
When downloading the table as a .csv, it only downloads items on the current page, instead of all items available in the filtered search. Downloaded data should include all items from the filtered search. 

Related: https://github.com/aces/Loris/issues/4574

**Comment by driusan** [comment]
@HenriRabalais can you look into this?

**Comment by HenriRabalais** [comment]
This seems to be a LORIS-wide issue. I will look into the Datatable to resolve this. I'm just going to change the Issue name to reflect my findings.

**Comment by HenriRabalais** [comment]
After looking into this more, I think it's also linked to why the pagination is not working (#5566). The fix for this should also resolve that issue.

I will look into it more next week.

**Comment by HenriRabalais** [comment]
PR Sent: #5600

**Comment by driusan** [comment]
PR merged
