### ISSUE TITLE
[Statistics] Minor UI issue in dropdown in < 900px wide screens

### ISSUE THREAD

**Issue by dyt811** [aces/Loris#5460]
Minor readability problem in background color with regard to the current module. See screenshots below on the submenu of the statistics. 
See https://drive.google.com/open?id=1EccOPCozGncsCtwx_hPcXvS9jrBTtujh and 
https://drive.google.com/open?id=1dtkygdVtT-rH5ffLIdaStowyNhdqaiga

**Comment by sruthymathew123** [comment]
I think this is a test VM specific case as I cannot regenerate on my VM
On my VM
![on_my_VM](https://user-images.githubusercontent.com/23702452/68235126-afd89d00-ffd0-11e9-9034-75106d84a24b.png)

On test VM
![on_test_VM](https://user-images.githubusercontent.com/23702452/68235147-b9620500-ffd0-11e9-844d-e517407b750c.png)

**Comment by sruthymathew123** [comment]
@cmadjar I am leaving this to your court for the decision making as I cannot regenerate the issue on my VM.

**Comment by sruthymathew123** [comment]
This is just happening for the initial page load of statistics. In my opinion, this not a blocking issue for 22.0 release.

**Comment by driusan** [comment]
Fixed by above PR
