### ISSUE TITLE
[Dashboard] New and pending imaging sessions are unclickable

### ISSUE THREAD

**Issue by kchatpar** [aces/Loris#5461]
Step 9. Verify that for a user with 'Edit imaging browser QC status' permission the My Tasks panel reports the number of new
   scans (i.e. the number of scans on the MRI browser page for which QC status has not been set. Note DCC scans are not
   counted in the query as for most projects this is not an acquisition site). Check that site
   displayed is always 'All'. Click on this task and verify that you go to the MRI Browser page.
   [Automate Test on Travis_CI]

The new and pending imaging sessions leads me to the permission being denied even on the admin account.

**Comment by cmadjar** [comment]
@Jkat can you please look into this on Monday? Thank you!

**Comment by Jkat** [comment]
Need the testing VM to be updated with https://github.com/aces/Loris/pull/5444, otherwise Imaging Browser is in an unloadable state.

**Comment by cmadjar** [comment]
Actually, it needs #5528 to be reviewed, merged and pulled on testing for the imaging browser to load on testing... Just fixed a separate issue than the one I fixed on #5444...

**Comment by ridz1208** [comment]
I added PR sent but i think it should be closed if its resolved by the 2 PRs above, they are now merged

**Comment by cmadjar** [comment]
Just tested it and it is working on testing now :).
