### ISSUE TITLE
[Media] Unable to download files

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5462]
Unable to download files when clicking on it. I get a 'Failed - No file' error message.

**Comment by ridz1208** [comment]
Thats normal, the files displayed there are fake. When the upload issue gets fixed you will be able to test by uploading and then downloading the file you uploaded

**Comment by SantiagoTG** [comment]
Great, that sounds good. I'll test this once upload function is live. Thanks

**Comment by cmadjar** [comment]
@kongtiaowang Related to #5455

**Comment by kongtiaowang** [comment]
It has been fixed.

**Comment by driusan** [comment]
@SantiagoTG can you confirm and close?

**Comment by SantiagoTG** [comment]
Download is functional.
