### ISSUE TITLE
[Statistics] Minor issue: Total Age Average (months) not calculated 

### ISSUE THREAD

**Issue by dyt811** [aces/Loris#5466]
Total Age Average (months) not calculated. See the N/A in the Total Column for the Row "Age Average (months)": https://drive.google.com/open?id=1dtkygdVtT-rH5ffLIdaStowyNhdqaiga

**Comment by sruthymathew123** [comment]
@dyt811 @driusan 

Total Age Average is not calculated and marked as N/A. It is the default existing code behavior in Loris for that column(Verified the statistics code as well). So this is not a bug.  Closing this issue.
