### ISSUE TITLE
[BVL Feedback] Issues with display and closing of threads after hitting 'Close' button

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5467]
Once a thread has been initiated, the "Open/Close" button will display as open, and a new thread will appear for the visit. If you "Close" the thread, it will display as closed, while not actually being closed. 
Additionally, if you try to change the "closed" thread to "Open" again, it will continue to display as closed. Thus, closing a thread does not really close it, instead it only changes the display of the "Open/Close" button. 
Refreshing the page or opening a new thread will then change all threads displayed to "Open". The "Open threads summary" will always display all threads as open.

**Comment by cmadjar** [comment]
@xlecours can you please look into this one? Thanks!

**Comment by driusan** [comment]
Fixed by above PR
