### ISSUE TITLE
[BVL Feedback]  should display information of threads open in other visits

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5468]
The "Open threads summary" does not display any information of threads open in other visits. This would be valuable to see the total number of threads without having to toggle between visits, as well as to see how much feedback has been provided to a given visit for each candidate.

**Comment by cmadjar** [comment]
@xlecours if you have time, could you look into this one? Thanks!

**Comment by xlecours** [comment]
@cmadjar This do not seems to be a bug. It is more like a feature request.

**Comment by SantiagoTG** [comment]
Indeed it is.
