### ISSUE TITLE
[Brainbrowser] Minor UI improvement on Overlay Panel

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#5469]
The overlay control panel does not have a border like the remainder of the panels on the same page

see examples
![Screenshot from 2019-10-31 16-58-36](https://user-images.githubusercontent.com/15268287/67985747-e93f9000-fbff-11e9-837f-163e5a459f9d.png)
![Screenshot from 2019-10-31 16-58-26](https://user-images.githubusercontent.com/15268287/67985751-eb095380-fbff-11e9-8913-2ad09a89438a.png)

**Comment by driusan** [comment]
PR merged
