### ISSUE TITLE
[brainbrowser] Loading slowness and lack of clarity

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#5474]
When brainbrowser is loading multiple volumes, after the first volume loads, the second takes a bit of time (sometimes longer 15-20 seconds, sometimes faster 2-4 seconds)

Also There is no clear sign that a second volume is loading (no `LOADING...` message loading under the first volume)

example [link](https://test-loris-dev.loris.ca/brainbrowser/?minc_id=[134,135]&overlay=true)

**Comment by cmadjar** [comment]
This one is very weird. Sometimes it loads the 2 volumes + overlay, sometimes it loads only the first one... 
When the 2 volumes + overlay are displayed, the `LOADING...` message appears for all volumes, one after the other. It is only when only 1 volume out of the 2 is displayed in the page. No idea why the other done does not get displayed. 

Try hitting refresh on the link attached and you will see what I mean. Sometimes, it loads everything, sometimes it loads only the first volume...

No idea why this is doing that or how to debug this... :(

**Comment by driusan** [comment]
PR merged to fix this
