### ISSUE TITLE
[QC module] BVL tab seems to be missing a status?  

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5482]
This module just lists instruments. it seems like a status column may be missing --
Not clear to the user (or maybe just missing documentation?)  are these completed?  valid?   fully administered? 
*  passed DDE - no conflicts?  
* passed visual/hardcopy QC? 
* passed the approval stage? 
* columns like SessionID to make it congruent Imaging tab?
- [ ] Verify with existing module specs, what should be showing here. 

There is no test plan or documentation merged for this module, so hard to tell... e.g. #5481

**Comment by cmadjar** [comment]
@johnsaigle @christinerogers can you both work together on the QC module issues on Monday to resolve the problems found? Thanks!

**Comment by driusan** [comment]
Can this be closed now that the qc module was changed to remove the tab?

**Comment by christinerogers** [comment]
Yes. closing. 
It's still missing a Test plan #5481
