### ISSUE TITLE
[instrument builder] Add "Blank Line" does not work

### ISSUE THREAD

**Issue by ycAbout** [aces/Loris#5486]
Test plan Item 1
1.j Add Blank Line

In instrument builder, nothing changes when you add a "Blank Line" field. Keeping adding field, there is no evidence showing the blank line.

If you download the linst file, there is no blank line in the file.

**Comment by cmadjar** [comment]
@christinerogers @coreyAbout can you guys work together in clarifying the test plan for that module please? Thanks!

**Comment by cmadjar** [comment]
Weird... I just looked into this one and it looks like this is broken on test-loris-dev.loris.ca but not when I test the code on my different sandboxes...

@kongtiaowang @driusan any idea why?

**Comment by cmadjar** [comment]
ok. It looks like sometimes the Blank Line is working, and sometime it isn't. No message in the JS console or the apache error log. Not ideal for debugging...

**Comment by driusan** [comment]
IIRC someone brought it up in a LORIS meeting and it works the first time but not after that, or something along those lines.

**Comment by cmadjar** [comment]
that would be consistent with my observations :)

**Comment by maltheism** [comment]
@driusan @cmadjar I'm not running into the "nothing changes" problem on 22.0-release. Basically the blank line is working for me.

**Comment by christinerogers** [comment]
@maltheism If I understand you, you're having trouble reproducing the bug?

**Comment by coreyAbout** [comment]
Please check this out. It is still there! Click it to make it larger if you can see clearly. @maltheism 

![screen-capture](https://user-images.githubusercontent.com/34487370/68702748-51bf3300-0557-11ea-9d36-cbe4f063135c.gif)

**Comment by maltheism** [comment]
@coreyAbout please test my PR to see if it solves the bug you encountered.

**Comment by zaliqarosli** [comment]
@maltheism i've change my assignment to you as you've issues a PR for this. let me know if i should revert this. thanks for looking into this issue!

**Comment by johnsaigle** [comment]
Duplicate #4604

**Comment by zaliqarosli** [comment]
@johnsaigle any reason you removed the PR sent tag? The PR is still open

**Comment by johnsaigle** [comment]
That tag doesn't exist anymore. When you delete a tag GitHub displays it the same as when you remove an existing tag.

**Comment by driusan** [comment]
What? Why doesn't the tag exist anymore? The tag should not have been deleted.

**Comment by johnsaigle** [comment]
We talked about it in the LORIS meeting on Feb 18th and I removed it after that. The idea is to use GitHub's Linked PRs feature instead.

**Comment by maltheism** [comment]
I'm not sure what to do with this issue if the PR I made would alter the linst spec. Is there another way of going about it? I would be happy to trying whatever would fix this issue but I cannot think of anything besides the existing PR.

**Comment by driusan** [comment]
@johnsaigle it was talked about, but there was never any decision/agreement to remove it that I recall.

@maltheism it works in the instrument builder the first time it's clicked as per the thread above. The bug is just that the frontend stops working after that.

**Comment by johnsaigle** [comment]
@driusan We remember it differently. Are you opposed to using Linked PRs instead? If so maybe it would be good to create an agenda item and discuss it tomorrow

**Comment by maltheism** [comment]
@driusan last time I looked at the code the empty line wasn't doing anything. Whomever takes the linst file and attempts to load the instrument won't have an empty line between other elements. I'm wondering if there is any purpose of the empty line if it cannot be added to the linst file. I might be confused by your other comment but my impression is if I fix the frontend for still working after whatever is making it stop working.. well it won't have empty lines when the user loads the instrument from the linst file that was created by the frontend.

**Comment by zaliqarosli** [comment]
@driusan adding the blank line doesn't work at all when I tested, not even the first time. if there's no such blank line option in linst, could the solution to fix the bug be just to remove the blank line option?
