### ISSUE TITLE
[issue_tracker] Test Plan needs to be updated

### ISSUE THREAD

**Issue by 3design** [aces/Loris#5495]
Some tests cannot be completed based on previous changes made to the module

**Comment by cmadjar** [comment]
@coreyAbout could you please update the test plan of this module?

**Comment by coreyAbout** [comment]
Have requested more detail form Derek, and will update when possible.

**Comment by 3design** [comment]
@christinerogers advised that the navigation refers to a sidebar which is not currently shown in the issue tracker. The following tests cannot be completed as a result:

Issue Tracker Create New Issue [Manual Testing]
7. Navigation bar should lead you back to list

Issue Tracker Edit Existing Issue [Manual Testing]
7. Check that the navigation bar bring you to the next issue in your previously filtered list of issues.

**Comment by johnsaigle** [comment]
As Christine pointed out, these actually refer to outdated features. This issue should be resolved by #5540 which updates the test plan

**Comment by christinerogers** [comment]
"not currently shown" because "feature was expressly deleted" is the context which was discussed, but not included in this issue description

**Comment by driusan** [comment]
Can this be closed now that #5540 is merged?

**Comment by christinerogers** [comment]
Yes. closing.
