### ISSUE TITLE
[dataquery] 'Remove All' button from the Define Fields tab is not working

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#5500]
Clicking on the "Remove All" button from the "Define Fields" tab does not remove fields previously selected for an instrument.

**Comment by jesscall** [comment]
There is already a PR for this issue: #5399

**Comment by ridz1208** [comment]
This has a PR going to 21.0-release. once merged the code will be pushed forward to 22

**Comment by cmadjar** [comment]
Perfect. Added the PR sent label then.

**Comment by driusan** [comment]
Can someone confirm this is fixed?

**Comment by ridz1208** [comment]
tested on TEST
