### ISSUE TITLE
[Configuration] multiple entry fields broken

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#5506]
> 5. Go through each of the fields in the configuration module that have the 
> "Add field" button are configuration values that allow multiple entries. For each of 
> these fields:
>    - try clicking the "Add field" button to see that this adds a new field to enter 
>    data. Enter data and press save at the bottom of the page. Refresh the page, check
>    that the data saved
>    - try deleting a field with the 'X' button. Press save at the bottom of the page. 
>    Refresh the page and check that the field was in fact deleted

for both deletion of an entry or addition. I get in the console:

```
jquery-1.11.0.min.js:4 POST https://test-loris-dev.loris.ca/configuration/ajax/process.php 400 (Bad Request)
```

**Comment by driusan** [comment]
This should be resolved by the above PR, according to the people who tested and reviewed it.
