### ISSUE TITLE
[behavioural_qc] Error in test plan

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#5507]
Step 4 says:

> Make sure that the user accessible site data is only populated with the step 4 condition.

is should be:

> Make sure that the user accessible site data is only populated with the step **3** condition.

-------------------------------------

step 8 says:

> Click on a field label and ensure that it downloads CSV of the data.

What does that mean?

**Comment by maltheism** [comment]
@xlecours step 8 is nonsensical for me as well. Maybe best option would be to remove it?

**Comment by ridz1208** [comment]
PR created
