### ISSUE TITLE
[data_team_help] Missing features

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#5508]
1. There is no 'clear' button for the filters
2. The datatable can't be sorted (usually clicking on a column header would sort the table by that column values.)
3. The test plan says : 

> Click on a field label and ensure that it downloads CSV of the data.

What does that mean? Which field label?

**Comment by johnsaigle** [comment]
Sounds like the documentation needs to be updated too

**Comment by driusan** [comment]
There is no more data_team_helper.
