### ISSUE TITLE
[Configuration] configurations of type boolean show up as text when no default value is added

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#5509]
The perfect example is the `Instrument Resetting` configuration under `Study`.

The `Instrument Resetting` is in the `ConfigSettings` table with type boolean. it shows up as text on the front end because no default value was entered for it in the `Config` table. When an entry is added in the `Config` table with value `true` or `false`, the field starts showing up as radio buttons as it should.

Not sure what the behaviour is in the control panel (where the configuration is actually used) @leighevans should test the behaviour with the instrument control panel

**Comment by johnsaigle** [comment]
Related to #5169?

**Comment by johnsaigle** [comment]
This may also be a Raisinbread issue. Should these settings always be defaulted to either true or false? What causes them to be blank?

**Comment by ridz1208** [comment]
when someone needs to add a configuration option, we genrally only require them to cheate the `ConfigSettings` entry in an SQL patch.

I never realized that boolean configurations that are added only into `ConfigSettings` get displayed as text fields. @driusan did you know ?

Its obviously ideal if the dev who submitted the PR also adds an entry into the `Config` table to include a default behaviour, otherwise the behaviour could be unexpected in the code using that config option.

In either case, a boolean configuration should not be displayed as a text regardless of it's value or lack there of.

**Comment by driusan** [comment]
No, they should be displayed as false. It seems to be a bug.

**Comment by johnsaigle** [comment]
> Its obviously ideal if the dev who submitted the PR also adds an entry into the Config table to include a default behaviour, otherwise the behaviour could be unexpected in the code using that config option.

I think this is normally done, at least since we've started requiring Raisinbread updates. We can be more strict about it during code review.

**Comment by ridz1208** [comment]
@johnsaigle I agree thats why I will issue a default for that specific value but i reported the bug anyways to keep track of it

**Comment by driusan** [comment]
Fixed by above
