### ISSUE TITLE
[Quality Control] Is it a thing?

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#5510]
Can we remove the Quality_Control module from 22.0 ?

1. There is no readme.md
2. There is no test plan
3. The page loads 2 tabs, one with data that seems to be a list of all instruments in the flag table. The other tabs seems to be a list of all imaging sessions with various links but no proper information (added value)

**Comment by johnsaigle** [comment]
Tagging @llevitis in case she wants to fight for its survival

**Comment by christinerogers** [comment]
Also reported in:
* #5482 
And related to:
* #5581

**Comment by johnsaigle** [comment]
Closing this because yes it turns out that it's a thing, now the "Imaging Quality Control" module

**Comment by christinerogers** [comment]
To tie all the threads together:   (placeholders below) 
* Readme is committed in : #
* Test plan will be committed by Liza (i just spoke with her) 
* Help text is... ?
