### ISSUE TITLE
[Testing] Strict bash flags cause docker scripts to fail locally

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5515]
`test/dockerized-unit-tests.sh` checks if the `$DEBUG` variable is given a certain value to determine how it should run.

This doesn't work after #5051  because the script will fail when this variable is not set.

**Comment by johnsaigle** [comment]
The same thing happens with the `SELENIUM_REQUIRED` variable.

**Comment by driusan** [comment]
merged
