### ISSUE TITLE
[Conflict_resolver/Instruments] Resolving conflicts does not recalculate score

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#5516]
resolving conflicts does not recalculate score. even though the value of the field in the instrument that you resolved correctly updates, you have to manually go into the instrument and click on 'save data' to get the updated score for the newly resolved value. this breaks the last point of the conflict resolver test plan

**Comment by driusan** [comment]
Are there any errors or anything? Last time I looked at it (which was quite a while ago) the conflict resolver called "save" on the instrument after it was done to make sure scores were recalculated.

**Comment by zaliqarosli** [comment]
no errors. it just shows new value for field, old value for score. and then when you click 'save data', new value for score shows up

**Comment by zaliqarosli** [comment]
@driusan you're right! i checked again and it doesn't work if i'm on the instrument page whilst resolving the conflict. but if i enter the instrument page only after resolving, then the score does update. closing issue
