### ISSUE TITLE
[Instruments] Completed data entry does not save values

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#5517]
On saving data entry in an instrument, some values do not auto-populate when you refresh / revisit the page i.e. Date of Administration or MRI Site Name on page 1 of MRI parameter form. The input field renders empty value / placeholder

**Comment by driusan** [comment]
@zaliqarosli can you look into this? If it's a testing VM thing you might need to talk to @kongtiaowang

**Comment by zaliqarosli** [comment]
it looks to only be the MRI parameter form and only the two fields reported in the description above

**Comment by zaliqarosli** [comment]
@ridz1208 where was the raisinbread MRI parameter form instrument taken from? i'm trying to find a history

**Comment by ridz1208** [comment]
@zaliqarosli as discussed in person, the MRI PF was taken from the old version stored in the docs directory. In an attempt to shorten the instrument for demo purposes while simultaneously keeping the minimum required fields to allow statistics and QC module to work, the instrument seems to be corrupt and should be fixed, however this is not critical for the release as it is a demonstration instrument not intended to be used by any projects

**Comment by ridz1208** [comment]
Issue is specific to the instrument and was fixed by PR above

**Comment by johnsaigle** [comment]
Closing this as it appears to be resolved
