### ISSUE TITLE
Missing .linst file(s) for proper Instrument Manager testing

### ISSUE THREAD

**Issue by Jkat** [aces/Loris#5527]
TestPlan says:
```
4. Take the sample .linst instrument file `test_all_fields.linst` in `docs/instruments` and upload it in Instrument Manager.
```
but this file has since been removed.
Further down the test plan, it asks for another sample instrument file, but the contents should either be more explicit or perhaps the exact contents should be included with the whole raisinbread dataset.

**Comment by driusan** [comment]
@kongtiaowang do you have a copy of this instrument to add back?

**Comment by driusan** [comment]
Fixed by above
