### ISSUE TITLE
[Issue Tracker] add planed items as a reminder

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#5548]
These items were in the test plan, was told to remove them but create a issue ticket as a reminder:
See Pull request #5540
Issue Tracker Create New Issue [Manual Testing]
7. Navigation bar should lead you back to list
Issue Tracker Edit Existing Issue [Manual Testing]
7. Check that the navigation bar bring you to the next issue in your previously filtered list of issues

**Comment by christinerogers** [comment]
Hi @coreyabout --  I think we have a miscommunication here. 
Please confer with Derek - I would prefer to see a complete update to the Issue Description of #5495 to clarify the root issue.

Note -- (cc @3design )
The NavigationBar feature was **removed** : see PR #4855 -- called `[issue_tracker] Remove navigation control panel` 

So any Test Plan items regarding the Navigation bar should either be updated (e.g. if the element/button was moved elsewhere) or deleted. 

(Unless I'm mis-understanding this and someone has requested adding this removed feature back to the Issue tracker - let me know)
