### ISSUE TITLE
[Imaging Uploader] Fields always disabled? (PSCID, CandID, Visit Label)

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5562]
From my understanding when Phantom Types is selected as the scan, the fields should be editable whereas for non-phantom scans they should be auto-populated.

#5520

**Comment by driusan** [comment]
That was fast.

**Comment by johnsaigle** [comment]
lol yeah I realized that this was already discussed in the issue I linked but that I read it incorrectly
