### ISSUE TITLE
Create value object for Alias

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5565]
Use `src/StudyEntities/Candidate/ValidatableIdentifier.php` as a template

#### Class properties

protected const MAX_LENGTH;
protected const MIN_LENGTH;
protected string $value;

#### Functions

`private function _validate(): void();` verifies:
* $value is alphabetical (no numbers or special characters)
* length of $value is between MAX_LENGTH and MIN_LENGTH

`public function __toString(): string;`
Same content as template.

`private final __constuct;`
Same content as template.

### Create child classes `SiteAlias` and `ProjectAlias`

Should extend `Alias` changing only the length values if necessary.

It's possible that these classes won't actually need to change the value but it would be good to decouple them right away just in case.

**Comment by johnsaigle** [comment]
@ridz1208 mentioned there's also something called an MRI alias so the above design may need to be modified depending on its needs

**Comment by thomasbeaudry** [comment]
What exactly is this class for ./ how will it be used in LORIS?

**Comment by johnsaigle** [comment]
It will be used as a Value Object, basically a way to move beyond primitive types and create something that's self-validating.

The goal is to be able to do something like

```php
$alias = new ProjectAlias($_POST['new_alias']);
```

Upon creation, ProjectAlias will internally verify that it has e.g. a length of 4 and is an alphabetic string. If not, it will throw an exception.

The alternative way to validate is doing something like:

```php
$alias = $_POST['new_alias'];
if (! strlen($alias) > 4 && ctype_alpha($alias)) {
 // handle exception
}
```

which is boilerplate code that needs to be used in every single instance where some kind of Alias is used. This isn't ideal because it encourages copy-pasting and makes everything harder to manage.


Similar things have been done with CandID (#4350) and SessionID (#5352). Many more will come.
