### ISSUE TITLE
[JSX - DataTable] Button with double arrows filters out every entry in the table?

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5566]
The Examiner menu filter has a button with two small arrows beside the "Download Table as CSV" button and under the Certification column.

Clicking these seems to remove all entries in the table. What is it supposed to do?

I couldn't find any info in the help text or the test plan.

**Comment by maltheism** [comment]
@johnsaigle also found in the imaging_browser. I think a change with the pagination of the table is broken.

**Comment by HenriRabalais** [comment]
This is likely related to this issue #5458 

The PR to resolve it will likely address both issues.

**Comment by HenriRabalais** [comment]
PR Sent: #5600

**Comment by driusan** [comment]
PR merged
