### ISSUE TITLE
[Raisinbread] Incomplete testing data for examiner certification

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5567]
There are no certification instruments for examiners in Raisinbread. As a result it's not possible to properly test all features of the module.

The README for `examiner` mentions that instruments have to be configured in the config.xml file. However, there are no examples of this in `project/config.xml` or in `test/config.xml`.

Ideally these should be configuration settings and not in the XML file also.

**Comment by ridz1208** [comment]
@johnsaigle the RB config.xml contains 2 certification instruments
https://github.com/aces/Loris/blob/22.0-release/raisinbread/config/config.xml#L103

**Comment by johnsaigle** [comment]
Oh I didn't realize it had its own config file...

**Comment by ridz1208** [comment]
my guess is test.

I defenetly think we should consolidate those 2 but iremember it creating some trouble back when I added the RB one.

The RB one should stay because it's the config.xml that matches the data
