### ISSUE TITLE
'First Visit' setting in table test_battery not taken into account

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#5569]
On the testing VM, instrument `medical_history` is set to be part of visit V06 iff it's not the first visit. I created visit V06 for a candidate that had no visit so far and `medical_history` was added to the list of instruments for that (first) visit.

Found during testing of 22.0.

**Comment by driusan** [comment]
It seems like this type of thing should be caught by unit tests

**Comment by nicolasbrossard** [comment]
Indeed. PR coming up.

**Comment by driusan** [comment]
Adding discussion required because there's a thread in #5573 about expected behaviour..

**Comment by ridz1208** [comment]
closed as per related issue. waiting on refactoring
