### ISSUE TITLE
[Media] Edit metadata window not loading

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5581]
When you try to open the edit metadata window, the window gets stuck loading, and thus can't edit data.

![Screen Shot 2019-11-08 at 11 44 08 AM](https://user-images.githubusercontent.com/54332302/68494981-4e593e00-021d-11ea-954d-6b53fba3b464.png)

**Comment by ridz1208** [comment]
@SantiagoTG good catch. I'm adding this here for more details
![Screenshot from 2019-11-08 13-14-35](https://user-images.githubusercontent.com/15268287/68500482-cded0a00-0229-11ea-8f8b-67e527ed574f.png)

**Comment by HenriRabalais** [comment]
PR Sent: #5585

**Comment by HenriRabalais** [comment]
Resolved
