### ISSUE TITLE
[BVL Feedback] Can't reopen thread once it has been closed

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5583]
Once a thread has been closed, it can't be reopened.

**Comment by johnsaigle** [comment]
Why is this marked as Discussion Required? Are you wondering whether this is intentional?

**Comment by SantiagoTG** [comment]
Yes, that is correct. I would presume it would be better to have the ability to re-open a thread, but as you mention, not sure if perhaps there is a reason to want to keep the thread closed.

**Comment by xlecours** [comment]
Should be fixed by https://github.com/aces/Loris/pull/5522

**Comment by xlecours** [comment]
Adding PR sent but it is merged
