### ISSUE TITLE
[Dicom Archive] Dicom download throws a 404 error

### ISSUE THREAD

**Issue by kchatpar** [aces/Loris#5587]
Item 11 on the dicom archive test plan - Ensure that clicking on any row in the 'Archive Location' column triggers a download of the corresponding archived DICOM study. Make sure that the copy of the file downloaded to your system is prepended with the Patient Name field. [Manual Testing]

When clicking on the archive location it throws a 404 error and the scan is not downloaded.

**Comment by driusan** [comment]
This is likely because of the test VM, @kongtiaowang can you look into this?

**Comment by cmadjar** [comment]
@kongtiaowang Maybe you will need to modify php.ini to allow for larger files to be downloaded. I think I noticed that once and had to modify it. Hopefully the pointer will help...

**Comment by driusan** [comment]
Since it's a 404 I was assuming the files themselves aren't on the test VM..

**Comment by johnsaigle** [comment]
This is working fine on my VM with a fresh Raisinbread install so I think we can close this and assume it's a test VM issue.
