### ISSUE TITLE
[Candidate Module] Orphaned, Project-Unattached Candidate Created

### ISSUE THREAD

**Issue by dyt811** [aces/Loris#5595]
In the 22 test VM, I managed to produce a subject that is invisible to myself for some reason?  

Go visit https://test-loris-dev.loris.ca/969362, the subject exist, belong to Project BLABLA. 

Now search: https://test-loris-dev.loris.ca/candidate_list/?dccid=969362
The subject is NOT FOUND.

Steps to Reproduce ([Video](https://drive.google.com/open?id=1PFjFmGT1vCJ3bLD-glerlYDEZUtymgOa)): 

- Reproduced subject with same problem: https://test-loris-dev.loris.ca/131772
- Site use: MTL 
- Project use: BLABLA

I think it has something to do with the specific site/project combo as I was using a different site (Ottawa Site & Challah Project) and was not able to reproduce the bug. 131772 was reproduced with MTL & BLABLA.

**Comment by ridz1208** [comment]
I'll take a look

**Comment by maltheism** [comment]
@dyt811 @ridz1208 I'm seeing the subject when visiting https://test-loris-dev.loris.ca/candidate_list/?dccid=969362

**Comment by dyt811** [comment]
@maltheism @ridz1208 Yup. Confirm no longer reproducible. I wonder what changed. Either way, no more issue.
