### ISSUE TITLE
Should Raisinbread be its own repository?

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5641]
Right now the Raisinbread data files are bigger than the rest of LORIS combined.

<img width="556" alt="Screen Shot 2019-11-13 at 16 27 00" src="https://user-images.githubusercontent.com/4022790/68805775-7805d100-0632-11ea-88fe-a6dbf3fd9ca4.png">

Also the way we have things structured, the entire Raisinbread directory is being included into our release archive files which is entirely unnecessary.

We can include the new repository as a submodule within git so that we can still keep it up-to-date with the rest of the code.

**Comment by christinerogers** [comment]
Agreed, 
and syncing submodules is a massive pain, from memory of `dicom-archive-tools`.
I'd bet it will definitely happen that Loris is released linked to a wrong/old version of RB.
It could just be a side repo, like Loris-MRI.

**Comment by johnsaigle** [comment]
What does the website have to do with Raisinbread?

Yeah I don't mind if it's a submodule or not.

**Comment by christinerogers** [comment]
sorry i meant demo project

**Comment by ridz1208** [comment]
I dont mind as long as RB still gets used by travis to run the tests and fails if the developers dont make the necessary adjustments to RB when issuing a PR.

Keep in mind that every time a dev sends a PR to loris they will send an equivalent PR to the separate repo and interlink the PRs ank make sure travis tests with the RB version on that PR because code changes can affect the RB dataset

**Comment by ridz1208** [comment]
FYI the separate repo would then be https://github.com/aces/loris-demo-project

**Comment by johnsaigle** [comment]
> Keep in mind that every time a dev sends a PR to loris they will send an equivalent PR to the separate repo and interlink the PRs ank make sure travis tests with the RB version on that PR because code changes can affect the RB dataset

Yeah that's why I was thinking a submodule might be helpful as a solution

**Comment by driusan** [comment]
There doesn't seem to be much discussion or passionate advocacy one way or the other, can we close this? (I vote for keeping it because otherwise it'll be very hard to keep the submodule in sync with PRs that require changes.)

**Comment by johnsaigle** [comment]
Sure. If my passion rises again I'll re-open
