### ISSUE TITLE
Standardize name of "Publications" module

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5656]
Note - in the menu at the top of LORIS, this module is labelled Publications, but labelled as Publication (no s) everywhere else

_Originally posted by @knoll-alex in https://github.com/aces/Loris/pull/5653#issuecomment-554037549_

**Comment by driusan** [comment]
I don't know where "Everywhere else" is, but I believe this should be resolved now that we have the Module->getLongName() function which is used to get module names?

**Comment by johnsaigle** [comment]
Yeah I think you're right and without more detail about specific occurrences I think we can close this.
