### ISSUE TITLE
[docs] update Issue tracker Readme - better permissions/roles description

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5668]
The following text was removed from the Help text and should be integrated (in terms of the details it covers) into the module spec readme: 

- Permissions are in accordance with the data permissions granted to that user - if a user can not see data outside of their site, they will only be able to view issues relevant to their site. 
- If a user has DCC permission they will be able to see issues relevant to all sites. 
- Additionally, users can be designated reporters or developers. 
- Reporters can add issues, edit their own issues, and comment on all issues. 
- Developers can additionally edit all issues, and mark them as resolved. 
- Most users of Loris should be designated as reporters.

**Comment by johnsaigle** [comment]
@maltheism Do you think you could incorporate these changes into #5394? It would be good to explain which permissions interface with adding attachments also.

**Comment by johnsaigle** [comment]
Resolved by #5394
