### ISSUE TITLE
[Install] Is Git a dependency for production installs?

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5682]
This error was reported on the dev mailing list.
```
root@ubuntu-s-1vcpu-2gb-tor1-01:/var/www/loris# make
git describe --tags --always > VERSION
fatal: not a git repository (or any of the parent directories): .git
Makefile:8: recipe for target 'VERSION' failed
make: *** [VERSION] Error 128
```

Even for non-developer installs, git seems to be required in order to generate the VERSION file or else the make command will fail.

Does this mean git is a dependency for LORIS?

**Comment by driusan** [comment]
Discussion from LORIS meeting:

We will write a script which checks if git/.git directory exists and use the git command if it has the prerequisites, otherwise create a VERSION of "Unknown" if it can't determine the VERSION.

**Comment by driusan** [comment]
PR merged.
