### ISSUE TITLE
[Cleanup] behavioral -> behavioUral

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5683]
as of Nov. 2019, we're keeping the U in `behaviour` and `behavioural` and would like to make this consistent across all module names / display text / docs

Fresh search links:
* https://github.com/aces/Loris/search?q=behavioral&unscoped_q=behavioral
* https://github.com/aces/Loris/search?q=behavior&type=Code

Biggest examples are probably: 
* Publication form option which users are asked to select  -> SQL patch needed?
*  Instrument List, bold table header: "Behavioral Battery..."

more innocuous examples exist (but should still be fixed) e.g.: 
- Statistics `Behavioral Feedback` etc...

**Comment by johnsaigle** [comment]
Command to find occurrences of `behavior` (case-insensitive):

```bash
git grep -n -i "behavior" | cut -d ":" -f1,2
```

Occurrences on aces/22.0-release as of November 19, 2019:
>SQL/0000-00-03-ConfigTables.sql:200
SQL/Archive/Pre-14.10/2014-09-26-DefaultConfig.sql:102
docs/SQLModelingStandard.md:102
htdocs/acknowledgements/acknowledgements.php:9
htdocs/js/c3.min.js:2
htdocs/js/c3.min.js:4
htdocs/js/d3.min.js:3
htdocs/js/d3.min.js:4
htdocs/js/jquery/datepicker/jquery.datepicker.js:89
htdocs/js/modernizr/modernizr.js:374
htdocs/js/shims/excanvas.js:1
htdocs/vendor/js/react/react-dom.development.js:92
htdocs/vendor/js/react/react-dom.development.js:100
htdocs/vendor/js/react/react-dom.development.js:106
htdocs/vendor/js/react/react-dom.development.js:183
htdocs/vendor/js/react/react-dom.development.js:592
htdocs/vendor/js/react/react-dom.development.js:714
htdocs/vendor/js/react/react-dom.development.js:2045
htdocs/vendor/js/react/react-dom.development.js:2149
htdocs/vendor/js/react/react-dom.development.js:3184
htdocs/vendor/js/react/react-dom.development.js:4998
htdocs/vendor/js/react/react-dom.development.js:5540
htdocs/vendor/js/react/react-dom.development.js:5792
htdocs/vendor/js/react/react-dom.development.js:6154
htdocs/vendor/js/react/react-dom.development.js:7727
htdocs/vendor/js/react/react-dom.development.js:7729
htdocs/vendor/js/react/react-dom.development.js:8779
htdocs/vendor/js/react/react-dom.development.js:8780
htdocs/vendor/js/react/react-dom.development.js:9343
htdocs/vendor/js/react/react-dom.development.js:9346
htdocs/vendor/js/react/react-dom.development.js:9957
htdocs/vendor/js/react/react-dom.development.js:9958
htdocs/vendor/js/react/react-dom.development.js:12825
htdocs/vendor/js/react/react-dom.development.js:14767
htdocs/vendor/js/react/react-dom.development.js:14797
htdocs/vendor/js/react/react-dom.development.js:15517
htdocs/vendor/js/react/react.development.js:213
htdocs/vendor/js/react/react.development.js:216
htdocs/vendor/js/react/react.development.js:691
htdocs/vendor/js/react/react.development.js:1409
htdocs/vendor/js/react/react.development.js:1703
modules/dashboard/help/dashboard.md:31
modules/imaging_qc/js/qualityControlIndex.js:1
modules/imaging_uploader/test/TestPlan.md:57
modules/instrument_list/php/instrument_list.class.inc:172
modules/instrument_list/php/instrument_list_controlpanel.class.inc:459
modules/instrument_list/templates/menu_instrument_list.tpl:175
modules/instrument_list/test/instrument_listTest.php:57
modules/instrument_list/test/instrument_listTest.php:75
modules/instrument_list/test/instrument_listTest.php:93
modules/publication/ajax/getData.php:60
modules/publication/ajax/getData.php:76
modules/publication/jsx/projectFields.js:300
modules/publication/jsx/projectFields.js:310
modules/publication/jsx/projectFields.js:311
modules/statistics/help/statistics.md:5
modules/statistics/php/stats_behavioural.class.inc:132
modules/statistics/test/TestPlan.md:28
php/libraries/CouchDB.class.inc:299
php/libraries/NDB_Factory.class.inc:324
php/libraries/NDB_Form.class.inc:110
php/libraries/NDB_Menu_Filter.class.inc:167
raisinbread/RB_files/RB_Config.sql:38
test/unittests/CandidateTest.php:113
test/unittests/CandidateTest.php:935
test/unittests/NDB_ConfigTest.php:70
test/unittests/SettingsTest.php:264
test/unittests/UserTest.php:196
tools/assign_missing_instruments.php:27
tools/fix_timepoint_date_problems.php:158


The occurrences in `htdocs/vendor` can be ignored as they come from 3rd-party code. `SQL/Archive` can also be ignored.
