### ISSUE TITLE
[Raisinbread/Instrument Manager] No data in the `test_names` table

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5685]
I'm not sure if this is intentional or not. However, raisinbread comes with some instruments so I think that this table should be populated.

Without this data, the Instrument Manager module is empty and therefore difficult to test.

**Comment by ridz1208** [comment]
https://github.com/aces/Loris/blob/22.0-release/raisinbread/RB_files/RB_test_names.sql

It's def populated, otherwise nothing instrument related would work

**Comment by johnsaigle** [comment]
Oops
