### ISSUE TITLE
Create data integrity check script to detect issues in the database

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5689]
We should have a database integrity checker script and consistently add checks to it when we detect these kind of issues. I guarantee you EVERY project has orphaned rows, illogical and inconsistent data. a while back justinNG had started a script that covered several base cases, it was never merged and eventually closed. I think it's very valuable to start that up again. It speaks to the health of the project.

_Originally posted by @ridz1208 in https://github.com/aces/Loris/issues/5684#issuecomment-555620075_

Check #2764 for some preliminary work  on this script.

**Comment by christinerogers** [comment]
quick notes: 
* (As john saigle mentioned ^^)  #1053 is important
* Date of birth should make sense, should not 
* check for duplicates - 1 participant with same instrument populated twice for 1 visit label (it happens)
* DDE - over/under population

**Comment by johnsaigle** [comment]
> (As john saigle mentioned ^^) #1053 is important

I don't remember mentioning this. What about this PR is important?

**Comment by johnsaigle** [comment]
Feature requests for this script should be added to #5096 instead of this issue.
