### ISSUE TITLE
[conflict_resolver] 'Correct Answer' in resolved conflicts does not retain value

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#5695]
The field `correct answer` under the resolved conflicts tab does not retain values from recently resolved conflicts. The correct value is updated in the actual instrument but does not display in the conflict resolver table. 

**Conflicts are being resolved:**

![conflict-resolver](https://user-images.githubusercontent.com/34260251/69190347-340d4300-0aee-11ea-8ee7-1fe5162435ad.png)

**`Correct Answer` values don't appear for all entries:**

![conflict-resolver-empty-val](https://user-images.githubusercontent.com/34260251/69190371-47b8a980-0aee-11ea-8d47-8382591143ab.png)

**However, instrument is updated correctly:**

![instr-conflict-fixed](https://user-images.githubusercontent.com/34260251/69190397-51daa800-0aee-11ea-8efd-1724f2194bb0.png)

**Comment by driusan** [comment]
Does it appear if you reload the page?

**Comment by kongtiaowang** [comment]
@jesscall In this module, the conflict data comes from Raisin bread data, most of the data are fake, If there is no correct value, probably it means this instrument has no conflict.

**Comment by driusan** [comment]
PR merged
