### ISSUE TITLE
[instrument_list] "Delete instrument data" button leads to 500 error

### ISSUE THREAD

**Issue by leighevans** [aces/Loris#5700]
Clicking the "Delete instrument data" button in the top lefthand corner of the page of an instrument leads to a 500 error.
Also what is this new button supposed to do (with two ambiguous checkboxes next to it)? Is it permission based? It's not in the test plan so not sure how it's supposed to function...

![Screen Shot 2019-11-20 at 11 05 12 AM](https://user-images.githubusercontent.com/32552953/69255506-ee9c5480-0b85-11ea-973c-29449aac9b0d.png)

**Comment by driusan** [comment]
Should be fixed by #5712
