### ISSUE TITLE
[genomic_browser] Files upload fails on Testing VM

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#5702]
Unable to upload a file on the GenomicBrowser File Uploader.

I believe the problem happens to be that the Testing VM hasn't configured the directory for the files to be uploaded to but I could be mistaken.

https://test-loris-dev.loris.ca/genomic_browser/genomic_file_uploader/

**Comment by johnsaigle** [comment]
Yeah, the file path is `/PATH/TO/Genomic-Data/` which won't work.

**Comment by kongtiaowang** [comment]
@maltheism I have changed the config. Please try again.

**Comment by maltheism** [comment]
File now uploads
