### ISSUE TITLE
[DQT] Load Query -> Delete -> Load Query (Broken)

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#5703]
The DQT has a bug when the user loads a query such as "admin_" on the Testing VM, then proceeds to delete the filter for the query, and attempts to load the "admin_" query again to recover the filter that was deleted. The filter that was deleted doesn't get updated on the second load of the "admin_" query and the user has to refresh the browser & reload for then being able to load the "admin_" query.

**Comment by driusan** [comment]
I don't understand.. how do you load a query that was deleted?

**Comment by maltheism** [comment]
@driusan 

Load Query "admin_" and get this:
![1](https://user-images.githubusercontent.com/16293415/69261788-39bb6500-0b90-11ea-8e55-07bf013bd5f8.png)

Click the red delete button and get this:
![2](https://user-images.githubusercontent.com/16293415/69261795-3de78280-0b90-11ea-8029-8211ca0f533b.png)

Load Query "admin_" and get this:
![3](https://user-images.githubusercontent.com/16293415/69261800-4213a000-0b90-11ea-80a3-7ca01e621e37.png)

**Comment by driusan** [comment]
I see.. I misunderstood that you were deleting the query itself, not the filter on your current query.

**Comment by ridz1208** [comment]
This issue will be resolved by module redesign
