### ISSUE TITLE
[DQT] Download Data as ZIP (button not working)

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#5704]
The DQT button "Download Data as ZIP" is not working and is found in the View Data tab of the DQT.

See screenshot:
![4](https://user-images.githubusercontent.com/16293415/69262250-22c94280-0b91-11ea-819e-794f8005dc4e.png)

**Comment by driusan** [comment]
It doesn't look like you selecting any imaging file columns.. that button downloads the images, not the data table (which is handled by "Download Table as CSV")

**Comment by maltheism** [comment]
@driusan thanks, my misunderstanding.
