### ISSUE TITLE
[imaging_browser] Empty dropdown for "Overall" in QC Comments

### ISSUE THREAD

**Issue by leighevans** [aces/Loris#5705]
Might be a non-essential cosmetic issue, but the dropdown menu for "Overall" at the bottom of the QC Comments window is empty. On CCNA at least (currently 20.1.2), there is no dropdown for Overall, only checkboxes (screenshot attached), so maybe a dropdown accidentally got added when there shouldn't be one?

LORIS 22.0
![Screen Shot 2019-11-20 at 1 51 21 PM](https://user-images.githubusercontent.com/32552953/69268378-0206ea00-0b9d-11ea-9624-455ce9432b9c.png)

CCNA on 20.1.2
![Screen Shot 2019-11-20 at 1 54 13 PM](https://user-images.githubusercontent.com/32552953/69268670-996c3d00-0b9d-11ea-92ad-8cc0879ec029.png)

**Comment by cmadjar** [comment]
PR merged.
