### ISSUE TITLE
Remove outdated configuration settings

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5706]
* Issue tracker URL -- it should always be `/issue_tracker/` no need to customize
* File Group for uploads -- is this used?
* Table rows per page -- overridden by module code, I believe
* Logs -- not used by any module #4100 
* CSS -- A FIXME in the middleware says that it's not actually supported

**Comment by johnsaigle** [comment]
> Table rows per page -- overridden by module code, I believe

This setting seems to be used in the NDB_Menu_Filter.class.inc file but doesn't correspond to the number of rows in some tables. My feeling is that it is still used for Smarty but not React. 

Maybe someone else can clarify this?

For now I'll leave it as-is.

**Comment by christinerogers** [comment]
Re removing the Issue tracker setting -- Where/when was this feature discussed/decided as no longer relevant? @johnsaigle 
The intention was to let this be the default, but allow links to outside issue trackers.   
(linked) from the Imaging Browser : View Session page.

**Comment by johnsaigle** [comment]
I didn't know the context was to link out to other issue trackers.

My understanding of this setting was that it was leftover from the Mantis days. Maybe we could discuss it in a LORIS meeting?

**Comment by ridz1208** [comment]
As indicated on the linked PR, config settings are in use
