### ISSUE TITLE
[Data Release] Can't remove permissions under Manage Permissions

### ISSUE THREAD

**Issue by Jkat** [aces/Loris#5708]
Unchecking permissions and saving doesn't do anything

**Comment by ridz1208** [comment]
@Jkat could you give steps to reproduce ?
i just tried it out and it seems to be working

**Comment by Jkat** [comment]
I uncheck one of the checked boxes under Manage Permissions for a user and it doesn't seem to save this change. Looks like unchecking both(/all) boxes works...

**Comment by ridz1208** [comment]
@Jkat nice catch !! 

it was a edge case when the version file is 0

**Comment by driusan** [comment]
PR merged
