### ISSUE TITLE
Subtab/page Help text is not displaying

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5709]
Help text markdown files for subpages is not displaying in the front end. These files are separate markdowns in the codebase. 

* Imaging Browser : View Session  
* My preferences show the User accounts Help (not ok!) at http://demo.loris.ca/user_accounts/my_preferences/#

_To confirm_: likely also in (but not sure if reactification is relevant?)
* MRI Violations 
* DICOM archive
* more modules with sub-pages... 

Similar to: https://github.com/aces/Loris/issues/5676

**Comment by christinerogers** [comment]
tagging `Release Critical` -- @driusan @ridz1208 pls untag if not... 

Credit goes to @knoll-alex

**Comment by driusan** [comment]
That definitely used to work. I think it should be critical.

**Comment by johnsaigle** [comment]
It seems to be happening because `subtest` is not being passed as a request parameter.

**Comment by johnsaigle** [comment]
@christinerogers 
> MRI Violations

While MRI Violations does have subpages, it seems like only one help file exists in the repo for this module. So I don't think it applies here unless there used to be files and they've been deleted somehow.

**Comment by christinerogers** [comment]
> While MRI Violations does have subpages, it seems like only one help file exists in the repo for this module. So I don't think it applies here unless there used to be files and they've been deleted somehow.

Hey john, good point - looks like there was never Help for this subpage.  Only one file was commited in #3266  I'll make a new issue.
