### ISSUE TITLE
Remove main.php file

### ISSUE THREAD

**Issue by driusan** [aces/Loris#5710]
Instrument loading (now done by the instruments module) and the API (now done by the API module) were the last 2 stragglers to be converted to LORIS modules. As of LORIS 22.0, the main.php file should no longer be required (and the `.htaccess` file makes no reference to it) and it can be removed.

This should have probably been done early for 22.0, but removing it implies that a full testing round should be done, so for the next release we should get rid of main.php.

**Comment by christinerogers** [comment]
what an epic `beginner friendly` issue!

**Comment by driusan** [comment]
I don't think this is beginner friendly.. you would need to verify that there's no outstanding references to it and nothing unexpected broke.
