### ISSUE TITLE
[Docs] Help text missing for 2 MRI Violations subpages

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5714]
For 2 subpages in MRI violated scans module: 
* MRI Protocol Violations  : http://demo.loris.ca/mri_violations/mri_protocol_violations
This subpage shows the contents of the `mri_protocol` table and makes it editable in the front end (and therefore highly dangerous) so -- yes, needs help text. 
as well as: 
* MRI Protocol Check Violations : http://demo.loris.ca/mri_violations/mri_protocol_check_violations

discovered in the hunt for #5709 : 

> While MRI Violations does have subpages, it seems like only one help file exists in the repo for this module. So I don't think it applies here unless there used to be files and they've been deleted somehow.

> Hey john, good point - looks like there was never Help for this subpage, only one file was committed in #3266  I'll make a new issue.

_Originally posted by @christinerogers in https://github.com/aces/Loris/issues/5709#issuecomment-556488283_

**Comment by johnsaigle** [comment]
This is still a problem as of the 23.0-release testing.

**Comment by christinerogers** [comment]
@nicolasbrossard have you had any time start looking into this?  If not, we could possibly re-assign for Monday.

**Comment by nicolasbrossard** [comment]
@christinerogers Unfortunately no...Q1K is keeping me busy these days...

**Comment by ridz1208** [comment]
@nicolasbrossard how's your time now ?

**Comment by nicolasbrossard** [comment]
Issue still there as of 2022-12-12
