### ISSUE TITLE
"Behavioural Quality Control" and "Imaging Quality Control" modules should have distinct permissions

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5718]
Currently both use a single permission "quality_control". It would be better to have two separate permissions to allow for more granular configuration of a project.

Neither of them appear to have any editing functionality so I think it's safe to have a single "view" permission and no "edit" permission, but let me know if I'm wrong on this point.

**Comment by racostas** [comment]
strongly agree @johnsaigle.
