### ISSUE TITLE
[genomic_browser] Progress bar broke

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#5720]
Even the file was uploaded successfully, It  still shows Error.
![Screen Shot 2019-11-21 at 12 07 18 PM](https://user-images.githubusercontent.com/9876007/69360256-38ee0600-0c58-11ea-9452-007e4fbf0051.png)

**Comment by maltheism** [comment]
@kongtiaowang I'm not able to debug the test VM but I'm not able to get this error on my setup of LORIS. I think you need the directory /data/genomic_uploader and the error will go away.

**Comment by johnsaigle** [comment]
@maltheism Do you know whether this is still a bug in your PR #5835 ?

**Comment by maltheism** [comment]
@johnsaigle should be resolved.
