### ISSUE TITLE
[install centOS] need to update instruction on node npm install

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#5725]
Following guide line by line: 
https://github.com/aces/Loris/blob/22.0-release/README.CentOS7.md
When running line:
`sudo yum install nodejs`

afterwards, check `node --version` shows `v6.17.1`

But LORIS needs:
`NodeJS 8.0 or higher`

npm the same thing.

Test environment: 
Virtualbox 6.08
CentOS 7

**Comment by johnsaigle** [comment]
Seems to be fixed on 22.0-release:
https://github.com/aces/Loris/blob/22.0-release/README.CentOS7.md

**Comment by coreyAbout** [comment]
no @johnsaigle 
See the section titled with `Nodejs`.

**Comment by johnsaigle** [comment]
Sorry about that. 

@maltheism Can you comment on this since you recently went through the install process?

**Comment by maltheism** [comment]
@coreyAbout @johnsaigle I didn't run into into an issue when using the `sudo yum install nodejs` command but it does indeed show v6.17.1. Nothing complained about nodejs being v6.17.1 and I did get LORIS working. I'm guessing if Nodejs needs to be a higher version there should be a way to install from a more updated repo.

**Comment by coreyAbout** [comment]
I think we can just update the documents, it should be fine.

**Comment by johnsaigle** [comment]
I think the reason v8 is required is because webpack has issues building with older versions.

I think it would be good to update the documentation.

**Comment by ridz1208** [comment]
@maltheism could you do the changes
