### ISSUE TITLE
[MyPreferences] Restore/Update lost Help text (last seen in 17.1)

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5727]
https://github.com/aces/Loris/blob/7865d9c645473b4f3b696d4077eb604f5a994ef1/SQL/0000-00-04-Help.sql#L58

User Accounts: My Preferences subpage (where users can reset their own pasword)
* https://test-loris-dev.loris.ca/user_accounts/my_preferences/#

The above Help content was last in LORIS 17.1 
* lost in the Great Help Markdownization of 19.0 #3437
* ideally should be restored and updated for 22 as part of  #5576 : Help updates, phase 2

- [x] should be committed as a markdown under `modules/user_accounts/help` and named after... the subpage name (see frontend url)
- [x] Update text to current/new Help style
- [x] Update for accuracy

Related
* Impacted by bugfix #5713

**Comment by knoll-alex** [comment]
addressed in PR #5745

**Comment by christinerogers** [comment]
#5745 is merged.  closing this issue.
