### ISSUE TITLE
[HelpEditor:EditContent] Restore/update lost Help text (from 17.1)

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5729]
https://github.com/aces/Loris/blob/7865d9c645473b4f3b696d4077eb604f5a994ef1/SQL/0000-00-04-Help.sql#L62

Help Editor subpage: _Edit Help Content_ 
* http://test-loris-dev.loris.ca/help_editor/edit_help_content

The above Help content was last in LORIS 17.1 
* lost in the Great Help Markdownization of 19.0 #3437
* ideally should be restored and updated for 22 as part of  #5576 : Help updates, phase 2

- [x] should be committed as a markdown under `modules/user_accounts/help` and named after... the subpage name (see frontend url)
- [x] Update text to current/new Help style
- [x] Update for accuracy

Related
* Impacted by bugfix #5713

**Comment by knoll-alex** [comment]
addressed in PR #5746

**Comment by christinerogers** [comment]
closing because PR is sent and this page needs Help... in more than one way. 
Either this will get merged or shelved (#5776).
