### ISSUE TITLE
[New Profile] Limit date of birth to present date.

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5733]
When creating a new profile, the date of birth should not exceed today's date. However, I had no issue creating a profile whose date of birth is far ahead in the future. On the lower range, the current threshold is set to restrict if the date is before to year 1917.

**Comment by zaliqarosli** [comment]
this is not necessarily a bug, but a configuration that needs to be set

**Comment by driusan** [comment]
Doesn't seem to be an open issue based on @zaliqarosli's comment?
