### ISSUE TITLE
[Instruments/instrument_list] Instrument set to in progress as soon as it is accessed

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#5736]
When you access the instrument from the instrument list, it is automatically set as "In Progress" this is normal when it is the first time the instrument is opened.

Issue: the same behaviour is happening when the instrument is already set to complete. As soon as you access it it goes back to in progress

**Comment by christinerogers** [comment]
@ridz1208 are you sure the first point is really a bug? 
This first part is normal behaviour I think, based on my recollection over too many years of LORIS -- (unless it was changed recently?)
> When you access the instrument from the instrument list, it is automatically set as "In Progress" this is normal when it is the first time the instrument is opened.


However on the second point: IMO definitely a bug.  : 

> Issue: the same behaviour is happening when the instrument is already set to complete. As soon as you access it it goes back to in progress


cc: @maltheism, who already submitted a fix #5737

**Comment by maltheism** [comment]
@christinerogers I think the second part is a bug because a user could click on the instrument to view details and navigate back without realizing the instrument is now set to in progress. @ridz1208 thoughts?

**Comment by christinerogers** [comment]
got it -- sorry i missed the "this is normal" part. 
only the second part is the bug report, cool. 
i think i read your fix PR title too early before reading Rida's details.  thanks!

**Comment by driusan** [comment]
merged
