### ISSUE TITLE
[Publication] Test #8 fails

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#5751]
`Propose a project under another account, and try accessing it given that you have the "Publication - Access to module" permission. You should be able to view a static version of the project proposal and be able to download the uploaded files.`

The uploaded file can't be downloaded.
It could be because the `/data/publication_uploads/` do not exists. I do not have access to the backend; I can't tell for sure.

**Comment by johnsaigle** [comment]
Yeah I think this is most likely a VM issue and not a code issue. Many modules have had troubel with downloading because the paths or files don't actually exists.

**Comment by xlecours** [comment]
I more think to add to the list of pros in favor of having the dowload path un der `$LORIS_BASE/project/...`

**Comment by johnsaigle** [comment]
You mean in the `config.xml` file?

**Comment by xlecours** [comment]
no, I mean

- project/uploads/document_repo
- project/uploads/publication
- project/uploads/...

At least, something that can be created by the install script without sudo

**Comment by ridz1208** [comment]
@kongtiaowang could you investigate

**Comment by kongtiaowang** [comment]
https://github.com/aces/Loris/tree/master/modules/publication
## Configurations

- `publication_uploads`: This configuration determines the directory where file uploads
 get stored. By default, this directory will be `/data/publication_uploads/` **but
  it is not automatically created.**

**Comment by johnsaigle** [comment]
Can this ticket be closed? It sounds like this was caused by an set up problem on the test VM and doesn't have anything to do with the core repo.
