### ISSUE TITLE
[SQL] `candidate.sex` column type does not match `tarchive.PatientSex` column

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5759]
The candidate.sex column is an enum with `Male` and `Female` as possible values.

The tarchive.PatientSex column is a varchar(255). Raisinbread contains values `M`, `F`, and `O`.

The second case implies an "Other" value for sex which may have impact on study ontologies. 

These columns should be made consistent.

**Comment by maltheism** [comment]
Just my thoughts but I think there is actual use for a third option in research studies. There are people that are intersex and hermaphrodites while rare as well would not fit in the M or F category.

**Comment by johnsaigle** [comment]
For sure, and it also covers cases when the value is unknown or could not have been collected for whatever reason. Not sure of the needs of projects though.

**Comment by maltheism** [comment]
@ridz1208 @driusan thoughts?

**Comment by johnsaigle** [comment]
I put it in the LORIS meeting agenda so we can discuss it as a group. It's more of a research-based decision than a software architecture decision.

**Comment by johnsaigle** [comment]
The result of the discussion is to add an `Other` option to the enum in the `Candidate` table.
