### ISSUE TITLE
[User account] Removing sites at which a user is an examiner does not seem to work

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#5768]
I created a user on the test VM that is an examiner at all the sites (MTL, OTT, ROM and DCC). I then edited the user profile so that he was only an examiner at DCC, with 'Radiologist' set to 'Yes'. When I access the examiner module, there is no indication that the user has been inactivated at sites MTL, OTT and ROM. In fact the table shows that the user os a Radiologist at every site. I also checked the backend examiner_psc_rel table and it did not contain any inactive examiners.

**Comment by kchatpar** [comment]
@ridz1208 said to close the issue and there's no current solution

**Comment by ridz1208** [comment]
@nicolasbrossard I did say that !!

however while re-reading the issue, the last part might be an actual bug. the backend table should show the inactive flag.

@kchatpar please investigate that part
