### ISSUE TITLE
[My Preferences] Notification sent to user from which the action originates

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#5772]
I created a user that had the notification 'Document Repository: New Document Uploaded' enabled. Logged as that user, I uploaded a new document in the document repository. I logged out and logged back in. There was a notification on the dashboard indicating that a new document was uploaded. I should not have gotten any according to the test plan since I was the one who uploaded the file.

**Comment by driusan** [comment]
Why was this closed?

**Comment by nicolasbrossard** [comment]
The test plan specifies that the user triggering the event is notified *but* does not get an email, unlike the other users who registered to receive an email. Current behaviour is OK then.
