### ISSUE TITLE
[Survey module] Survey was not emailed to participant 

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#5773]
I added a survery in the survey module. Every field was valid, including the email address. I clicked the 'Email' button and entered an email text in the popup window but when when I clicked Send I never received the survey (and no errors were shown).

**Comment by driusan** [comment]
Where did you do this and was email configured properly on the VM that was used?

**Comment by johnsaigle** [comment]
I'm able to replicate this on Raisinbread with the following POST body:

CandID: 587630
PSCID: DCC090
VL: V2
Test_name: medical_history
Email: `$myemail`
Email2: `$myemail`
email_dialog: ggg
send_email: true


The module can return silently when an instrument exists for the given session:

https://github.com/aces/Loris/blob/553165cb2c737d20f1fa4a074691767f5081726d/modules/survey_accounts/php/addsurvey.class.inc#L165-L187

I'm not sure why this is the case; I haven't used the module much.

This could be a bug? If not, a better message should be displayed that indicates to the user what's going on.

**Comment by johnsaigle** [comment]
@ridz1208 @driusan This might be nice to fix for the release? Surveys seem sort of important.

**Comment by ridz1208** [comment]
@johnsaigle this need to be retested. It might have something to do with the RB fixes I made for another issue reported by @driusan https://github.com/aces/Loris/issues/6229

**Comment by sruthymathew123** [comment]
@nicolasbrossard  I couldn't recreate the issue; Can you see if it is still an issue now?

**Comment by sruthymathew123** [comment]
Couldn't recreate the issue; so closing the issue.
