### ISSUE TITLE
[Survey Module] IsDirectEntry in table test_names ignored?

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#5775]
I tried setting column IsDirectEntry of table test_names to 1 for all tests but only one of the 5 tests on the test VM seems to be avaiable in the survey module.

**Comment by coreyAbout** [comment]
I have followed up with Nicolas, and I have tried it on my VM. 
check git: HEAD detached at aces/22.0-release
Created and installed 6 test instruments,
change IsDirectEntry to 1

>mysql> select * from test_names;
+----+--------------------+--------------------+-----------+---------------+
| ID | Test_name          | Full_name          | Sub_group | IsDirectEntry |
+----+--------------------+--------------------+-----------+---------------+
|  1 | mri_parameter_form | mri_parameter_form |         1 |          NULL |
|  2 | test               | test               |         1 |             1 |
|  3 | test2              | test2              |         1 |             1 |
|  4 | test3              | test3              |         1 |             1 |
|  5 | test4              | test4              |         1 |             1 |
|  6 | test5              | test5              |         1 |             1 |
|  7 | test6              | test6              |         1 |          NULL |
+----+--------------------+--------------------+-----------+---------------+
7 rows in set (0.00 sec)

Then click on `survey module`, `add survey`, they all showed under instrument.
see here:
![imglykit-export](https://user-images.githubusercontent.com/34487370/71042291-51d3c500-20f9-11ea-909c-372c8cef4aa6.jpeg)

Thus this might be a test VM issue.

**Comment by miladheshmati** [comment]
I've checked this on my VM as well and I think we can close this issue
