### ISSUE TITLE
[Help Editor] parent and subtopics?

### ISSUE THREAD

**Issue by Jkat** [aces/Loris#5784]
Do the concepts of `parent` and `subtopic` still apply? Since modules are taking markdowns and the Help Editor is only for instruments now - there is no notion of `parent` nor `subtopic` for instruments.

**Comment by driusan** [comment]
No, I don't think they have any relevance any more (if they ever did)

**Comment by christinerogers** [comment]
I have a vague memory that `subtopic` used to populate links "Here's a related topic"

**Comment by ridz1208** [comment]
#6969
