### ISSUE TITLE
[Imaging_qc] Does not load

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#5793]
The imaging quality control module is not loading on test due to discrepancies between the mri_parameter_form scan done columns and the scan types stored in the database.

This is a constant issue that has been popping up for imaging_qc and statistics for the past couple years.

**Comment by ridz1208** [comment]
@cmadjar I think we should discuss this one once and for all

**Comment by johnsaigle** [comment]
Is this the same as https://github.com/aces/Loris/issues/5325? 

There'a some background discussion there. My understanding was that it wasn't possible to provide a standard mri_parameter_form in Raisinbread because it's different for every study

**Comment by ridz1208** [comment]
@johnsaigle the other ticket is to make the error message better in the event that a project has a badly configured mri_parameter_form

this is more to fix the raisinbread MPF to work with stats in imaging _qc

No we cant have a standard MPF but within a single project like Raisinbread, we should have the MPF work with both the stats module and the imaging_qc

**Comment by christinerogers** [comment]
@AlexandraLivadas Give this a shot and message me/rida/cecile if/when you get stuck. 
1. Highlight here exactly which columns are causing the issue for the imaging_qc module and statistics. 
2. suggest here what the code fix options are, and which might make more sense, (a) a tweak in Stats? (b)  imaging_qc module, or if the change would be (c) on the mri_parameter_form mri_scan_type table side (less likely)

**Comment by ridz1208** [comment]
way old
