### ISSUE TITLE
[Issue Tracker] Raisinbread issues 

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#5794]
The issues that are closed can't be changed back to an other status. The POST request to `https://test-loris-dev.loris.ca/issue_tracker/ajax/EditIssue.php?action=edit` is responded with a 500.
The php error log on the test server should have more info about the cause of the error.

**Comment by ridz1208** [comment]
why is this tagged as an RB issue not a bug ?

**Comment by xlecours** [comment]
Because it's working on my VM without any extra care given to the database updates

**Comment by ridz1208** [comment]
@xlecours can you detail how to reproduce ?
which issue did you click on ?

**Comment by xlecours** [comment]
1. Go to https://test-loris-dev.loris.ca/issue_tracker/issue/14 as a user with both `Can add a new issue, edit own issue, comment on all` and `Can re-assign issues, mark issues as closed, comment on all, edit issues.` and with Montreal as its only site.
Change the the issue status to something else than Closed. 
Nothing happen; network log shows a 500 for the POST request.

**Comment by xlecours** [comment]
More details:
```
PHP Warning:  PDOStatement::execute(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'CenterID' in 'where clause' in php/libraries/Database.class.inc on line 699, referer: https://test-loris-dev.loris.ca/issue_tracker/issue/14
```
