### ISSUE TITLE
[Raisinbread] Visit_Windows table should be populated

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5818]
The table has no data on Raisinbread so whatever features this table supports are not easily testable.

**Comment by christinerogers** [comment]
Raisinbread looks like it uses V1... V6 - this is encoded in the imaging files too. 
For a quick sanity check -
 @AlexandraLivadas ensure that all the visit labels in teh session table are represented in Visit_Windows.  
No values need to be associated with the min/max/optimum window/days columns -- they can stay Null for now. .

**Comment by AlexandraLivadas** [comment]
Both the Visit_Windows and session table in RB have the visit labels V1-V6. @christinerogers I believe this is enough to mark this issue as closed?
