### ISSUE TITLE
[Data Release] File upload fails silently for large files

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5843]
Back-end log:

>[Fri Dec 06 16:10:48.196409 2019] [php7:warn] [pid 28727] [client 192.168.122.1:60390] PHP Warning:  POST Content-Length of 56173016 bytes exceeds the limit of 8388608 bytes in Unknown on line 0, referer: https://jsaigle-dev.loris.ca/data_release/
[Fri Dec 06 16:10:48.274852 2019] [php7:notice] [pid 28727] [client 192.168.122.1:60390] PHP Notice:  Undefined index: action in /var/www/loris/modules/data_release/ajax/FileUpload.php on line 18, referer: https://jsaigle-dev.loris.ca/data_release/
[Fri Dec 06 16:10:48.724921 2019] [php7:notice] [pid 24309] [client 192.168.122.1:60392] PHP Notice:  Trying to get property 'page' of non-object in /var/www/loris/src/Middleware/UserPageDecorationMiddleware.php on line 92, referer: https://jsaigle-dev.loris.ca/data_release/ajax/FileUpload.php

The module should be updated with a proper failure message if the uploaded file exceeds the max file size allowed by the server. 

To replicate, try uploading a large file.

**Comment by johnsaigle** [comment]
@cmadjar Do you know whether #5061 fixes this?

**Comment by cmadjar** [comment]
PR #5224 fixes the issue
