### ISSUE TITLE
Document how to handle larger file uploads

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5849]
We could create a brief page in the wiki describing how to configure PHP for larger files, i.e. setting values in the php.in file.

Currently this is documented a few times over in several of the modules that have file uploading features. it would be good to instead centralize this in one place and link to it if necessary.

**Comment by christinerogers** [comment]
Thanks for opening this separate issue -- Could you link this to the ticket/PR where i suggested this?

**Comment by johnsaigle** [comment]
#5827
