### ISSUE TITLE
Introduce 'First-Timers Only' label

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5863]
**Is your feature request related to an existing module?**
Nope!

**Describe the solution you'd like**
I'm echoing @christinerogers's suggestion to rename Beginner Friendly to "First-Timers Only". I believe this is more-or-less how we implicitly use this label anyway. 

**Additional context**
It would be an improvement in helping new developers get started with LORIS. It signals to new developers that we have the willingness to help them get started. The change should also discourage (or forbid) experienced developers from taking on very easy issues that would be better used as an opportunity to onboard new folks.

**Comment by christinerogers** [comment]
Per : https://www.firsttimersonly.com/
It's important to note that it's not the same as `Beginner-friendly` -- so if we do rename the label we'd want to carefully revisit everything flagged with this label. 
For that reason, I'd suggest a new label, and starting small on 1-2 really well-documented issues (why? [see the link](https://www.firsttimersonly.com/))

**Comment by johnsaigle** [comment]
That's for providing the context that I missed before.

Maybe we could introduce "First Timers Only" and apply it only to issues that and very small and very well-documented. At the same time, we can gradually phase out "Beginner Friendly" (because it will probably be redundant) and provide additional instructions on those issues that are marked as Beginner Friendly.

**Comment by johnsaigle** [comment]
I think this is a good idea but I'm going to close it for now because it doesn't seem like we have the bandwidth to properly support this initiative at this time. We should revisit this when more resources are available.
