### ISSUE TITLE
 [acknowledgements] public facing link broken - 500 error

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#5885]
Example public facing link: 

https://<YOUR-BASE-STUDY-URL>/acknowledgements/acknowledgements.php?date=2017-11-17

error msg
[Mon Dec 23 14:59:38.240020 2019] [php7:notice] [pid 7451] [client 132.216.236.87:62741] Could not execute SELECT full_name, citation_name, title, affiliations, degrees, roles, start_date, end_date, present FROM acknowledgements\n    WHERE start_date <= :publication_date\n    ORDER BY ordering ASC. Stack trace#0 /var/www/loris/php/libraries/Database.class.inc(734): Database->execute(Object(PDOStatement), Array)\n#1 /var/www/loris/htdocs/acknowledgements/acknowledgements.php(47): Database->pselect('SELECT full_nam...', Array)\n#2 {main}
[Mon Dec 23 14:59:38.240080 2019] [php7:error] [pid 7451] [client 132.216.236.87:62741] PHP Fatal error:  Uncaught DatabaseException: Unknown column 'title' in 'field list' in /var/www/loris/php/libraries/Database.class.inc:702\nStack trace:\n#0 /var/www/loris/php/libraries/Database.class.inc(734): Database->execute(Object(PDOStatement), Array)\n#1 /var/www/loris/htdocs/acknowledgements/acknowledgements.php(47): Database->pselect('SELECT full_nam...', Array)\n#2 {main}\n  thrown in /var/www/loris/php/libraries/Database.class.inc on line 702

**Comment by driusan** [comment]
PR merged
