### ISSUE TITLE
Remove "System Requirements" folder from ReadTheDocs

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5901]
**Describe the solution you'd like**
As discussed with @ridz1208 in #5253, this folder isn't needed as System Requirements are outlined in detail in the "Install section". 

**Describe alternatives you've considered**
We agree that it's preferable to have one detailed install document (per supported OS) rather than separate the system prerequisites from the other install instructions

**Additional context**
Discussion in #5253

**Comment by ridz1208** [comment]
@johnsaigle i dont mind doing it if you havent done it yet

**Comment by johnsaigle** [comment]
Works for me

**Comment by ridz1208** [comment]
closing because that directory is no longer there
