### ISSUE TITLE
[installDB.php] Broken on master

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#5903]
**Describe the bug**
Tested the installDB.php on master and the installation seems to end with pointing to url/installDB.php

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. LORIS_URL/installDB.php
2. Install LORIS
3. After installation the link pointing to LORIS is wrong and includes installDB.php
4. Also LORIS is broken in general after going to the homepage

**Comment by kongtiaowang** [comment]
I can't reproduce this bug, It works for me on master branch. Could you send more details?

**Comment by maltheism** [comment]
I tested it again on my VM and seems to be working.
