### ISSUE TITLE
Create Wiki document providing troubleshooting help for the most common install issues

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5920]
**Describe the solution you'd like**
> I'd like to see here quick links to top 3 troubleshooting questions we get right after Install, which aren't script errors. i.e. What to do if :
front end doesn't load -> check/fix config paths via the mysql back-end
css looks busted (if that is still happening) -> check/fix config paths via the mysql back-end
you need to reset your admin password -> run the tools script

-- @christinerogers in #5253 

Instead of adding troubleshooting instructions to the end of the Ubuntu install instructions, we should create an OS-agnostic guide to fixing the above issues and add it to ReadTheDocs

**Describe alternatives you've considered**
Troubleshooting in general relates to our application, not the underlying OS. Adding troubleshooting instructions to the OS-specific installation documents isn't very precise and requires us to duplicate the information across multiple documents, which requires a higher maintenance burden.

**Comment by christinerogers** [comment]
These are currently in the Wiki setup guide (the actual wiki).  let's ensure we keep them in the new set of docs.

**Comment by christinerogers** [comment]
@laemtl will contribute this together with Alex's #6475 efforts to put the install guide markdowns on the 23 branch. 
Keep in mind that these markdowns are targeted to production installs by default.  Note clearly anything for dev context (and of course don't hesitate to ask for input in your PR)
