### ISSUE TITLE
Rename the "project/" directory (containing config.xml, overrides, etc.)

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5931]
**Is your feature request related to an existing module?**
No

**Describe the solution you'd like**
As discussed in the LORIS meeting, it would be good to disambiguate the word "project". Currently we have a Project class which represents the idea of a study project that is being managed by LORIS. At the same time we have the `project/` directory which contains configuration files and custom modules, instruments, etc.

We need to rename this folder and update the hard-coded paths in LORIS accordingly.

**Comment by johnsaigle** [comment]
Blocked by #6022 by Dave's request.

**Comment by ridz1208** [comment]
closing because... thats too far down
