### ISSUE TITLE
[issue_tracker] error when editing issue

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#5938]
**Describe the bug**
The module issue_tracker is broken when editing an issue on master branch. 

See https://github.com/aces/Loris/pull/5394#issuecomment-575281470

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to issue_tracker
2. Click on an issue to edit.
3. See error

**Comment by johnsaigle** [comment]
I believe this error is occurring because the module's queries are hard-coded to refer to the `LorisMenu` table which was deleted by #5839

**Comment by driusan** [comment]
@johnsaigle yes, EditIssue seems to still have a reference to it.

**Comment by driusan** [comment]
@maltheism can you test that #5963 fixes this?

**Comment by maltheism** [comment]
@driusan it fixes it.
