### ISSUE TITLE
[Module] lorisform_parser is no longer working in v22 master branch after recent commits

### ISSUE THREAD

**Issue by lingma** [aces/Loris#5940]
**Describe the bug**
With new update to Module or some related modules, the lorisform_parser is no longer working.

**To Reproduce**
Go to tools/, `ls` any instrument to feed `lorisform_parser`, the system will report

PHP Fatal error:  Uncaught Error: Cannot instantiate abstract class Module in tools/lorisform_parser.php:57

**What did you expect to happen?**

There should be no problem like this, at least before Module or related program was modified recently.

**Server Environment (if known):**
- LORIS Version: [e.g. 22.0.0] 22.0.0
- MySQL/MariaDB Version: [e.g. MySQL 5.7]
MySQL 5.7

**Comment by driusan** [comment]
the line mentioned needs to be updated to use `new NullModule()` instead of `new Module("", "")`

**Comment by johnsaigle** [comment]
I think this is resolved by the linked PR
