### ISSUE TITLE
[user_accounts] admin created account information not precise

### ISSUE THREAD

**Issue by lingma** [aces/Loris#5951]
**Describe the bug**
An administrator created an account, then user received an email saying that 
"Account **Changes** - Example Study"
...
Your account details have **changed**:
password: IPsCkodaKT6z9z7ll7mcSSeXCyO4UEJcJDYeV59c2hycK9VRQbUsy4awil7ZxnQt

After login, the site has a `Admin` and a drop down half showing, strange to see, check the attached image.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'User manager'
2. Click on 'add', then choose "generate password", 
4. See emails got.

**What did you expect to happen?**
A clear and concise information, also the drop down should not show, if shown, should not be showing a little bit.

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]

**Server Environment (if known):**
- LORIS Version: [e.g. 21.0.0] 22
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by lingma** [comment]
![image](https://user-images.githubusercontent.com/5295785/73020537-d2ba6680-3df3-11ea-8da2-36affad757d8.png)

**Comment by johnsaigle** [comment]
What permissions does the user have?

**Comment by lingma** [comment]
No much permission, just data entry or a few, so there is no permission of Admin. In this case, I think the Admin drop down or Admin itself should not show up to confuse people.

**Comment by johnsaigle** [comment]
I think it show sup depending on the permissions the user has. Can you take a screenshot of the permissions that user has assigned to them? It might help in figuring out the bug.

**Comment by lingma** [comment]
I also wanted to say that "Account Changes - Example Study" ...Your account details have changed:" whch is not true. This is a new account, and the password is way too long.

**Comment by johnsaigle** [comment]
> Account Changes - Example Study" ...Your account details have changed:

You're right this is not precise and should be fixed.

> the password is way too long

It's a one-time password so the idea is just to copy and paste it. If I remember correctly the user is forced to change their password when they login anyway.

**Comment by lingma** [comment]
permID | code                        | description                                          | categoryID |
+--------+-----------------------------+------------------------------------------------------+------------+
|      3 | user_accounts_multisite     | Across all sites create and edit users               |          2 |
|      5 | bvl_feedback                | Behavioural QC                                       |          1 |
|     10 | access_all_profiles         | Across all sites access candidate profiles           |          2 |
|     11 | data_entry                  | Data entry                                           |          1 |
|     12 | examiner_view               | Add and certify examiners                            |          2 |
|     13 | examiner_multisite          | Across all sites add and certify examiners           |          2 |
|     25 | dicom_archive_view_allsites | Across all sites view Dicom Archive module and pages |          2 

I don't know what happened, I could not access the user permission page right now, after the weekend, weird, but I get the data from DB as shown above

**Comment by johnsaigle** [comment]
> | 3 | user_accounts_multisite | Across all sites create and edit users | 2 |

This is an admin permission (under Admin > User Accounts) so the dropdown should be there and should contain 'User Accounts'. 

I'll try testing on my VM and figure out why `User Accounts` doesn't show up in that menu.

**Comment by driusan** [comment]
What branch is this on? (ie. is it on master with the modules taking care of the menus or a branch with the LorisMenus table?)

**Comment by lingma** [comment]
22.0 master branch

**Comment by driusan** [comment]
Can you test #5955? It seems to be because of the hack to make 'Admin' the last category not considering the possibility of it being empty..

**Comment by lingma** [comment]
OK, later when I got time. By the way, just mention that the error message for my user accounts page not showing anything is
`Undefined index: filter in /php/libraries/NDB_Menu_Filter.class.inc on line 598, referer: https:/user_accounts/`

I have not checked yet.

**Comment by johnsaigle** [comment]
The Admin empty being hidden seems like a different bug. From the permissions posted above it looks like the correct behaviour here should be that the Admin menu does appear with User Accounts as the only option.

**Comment by johnsaigle** [comment]
I've found a fix ⬆️ Issuing a PR in a second
