### ISSUE TITLE
[22.0.0 - new profile] Empty drop down with only 1 site affiliation

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#5969]
**Describe the bug**
When a user entering a new candidate is only affiliated with 1 site, the site dropdown on the user profile page is empty

this bug was found by @thomasbeaudry

**Comment by lingma** [comment]
This issue has already been addressed in PR #5892

**Comment by ridz1208** [comment]
closing because fix is in the wrong place, new PR will be issued soon. the error is in the JS not hiding the site field
