### ISSUE TITLE
Change eslint rule for requiring JS docs to error from warning

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5973]
**Is your feature request related to an existing module?**
React/JS in general

**Describe the solution you'd like**
I think it would be a good idea to require JS code going forward to add annotations. We do this for PHP and as JS is becoming a bigger and bigger part of LORIS, it would be good to tighten up the code standards here as we're doing on the PHP side.

**Describe alternatives you've considered**
Currently it is set to warning level - however, these warnings don't get cleaned up --> #4138 

**Additional context**
I don't do any JS work really so if there are strong, reasonable objections to JS docs this can be closed.

**Comment by driusan** [comment]
I think everything that's currently a warning from eslint should be an error, but there's a lot of cleanup to do of existing code before that's even theoretically possible to enable in Travis.

**Comment by laemtl** [comment]
Replaced by #6750
