### ISSUE TITLE
[Installdb] hostname as a choice to be entered, the default as the visiting hostname

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6007]
**Is your feature request related to an existing module?**

It would be nice that the installdb have a hostname field, default to be the current visiting hostname, editable to be any other hostname.

**Describe the solution you'd like**

Add a text field, copy the current hostname as the default value. Make the field editable, then insert the value from this field instead of only the installer's hostname. This could give user a choice as to what the expected visiting hostname should be, instead of going into DB to modify.

**Describe alternatives you've considered**
You can also put the hostname in the config.xml file, so that it is much easy to modify the value for different purpose.

**Additional context**
A customer Sotirios Nikoloutsopoulos is creating Loris on dockered environment, which could be much easy if the field hostname is editable.
The raisinbread will be installed as `localhost`, which could be much better if we don't need to modify Config table each time after the raisinbread db loading.

**Comment by driusan** [comment]
The setting no longer exists as of #6019
