### ISSUE TITLE
[bug] pageclass object null warning

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6009]
**Describe the bug**
Each page loading of timepoint list, instrument list and instrument will trigger a warning "PHP Notice: Trying to get property 'page' of non-object in UserPageDecorationMiddleware.php", which is not pleasant to see when you are working with them every day.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):

Load a timepoint list, instrument list and instrument page, then check web server log.

**What did you expect to happen?**
The warning should not happen

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
- LORIS Version: [e.g. 21.0.0] 22.0
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

A PR #5937 has been created, the fix seems too simple. I don't know whether there is a good fix for this problem, might need time to investigate. The processing logic seems good for most other other modules, only exceptions are a few I listed above.

**Comment by johnsaigle** [comment]
Is this fixed by https://github.com/aces/Loris/pull/6013?

**Comment by lingma** [comment]
> Is this fixed by #6013?

I think so
