### ISSUE TITLE
modifying a date portion clear others field in Firefox

### ISSUE THREAD

**Issue by PapillonMcGill** [aces/Loris#6010]
**Describe the bug**
When trying to modify a date (at least in DoB module, see https://github.com/aces/Loris/pull/4915) , when entering a new year, month of day, other parts of the date reset to default
i.e. trying to change 2020-05-01 to 2020-01-01 by replacing the 5 with a 1, will change to yyyy-01-dd.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Use Firefox to log in LORIS
1. Go to Candidate -> acces profile
2. Click on a candidate PSCID link
3. Click `Candidate info`
4. Select `Change DoB`
5. try to change the date  by entering a new date (using number) directly in the field. 

**What did you expect to happen?**
That the portion of the text not modified stay the same 

**Browser Environment (please complete the following information):**
- OS: Linux (Debian and Ubuntu)
- Browser Firefox
- Version 68.4.1esr and 72.0.2

**Server Environment :**
- LORIS Version: Using PR #4915, reportedly the same in other place
- Linux distribution and Version:  Ubuntu 16.04
- MySQL/MariaDB Version:  MySQL 5.7

**Comment by CamilleBeau** [comment]
@kongtiaowang Can you please check if this is still an issue?

**Comment by kongtiaowang** [comment]
This issue is not a bug in Loris but rather a feature of Firefox. When entering a date, month, or year, if it starts with '0', Firefox automatically sets all other fields to empty.

**Comment by kongtiaowang** [comment]
This issue is not a bug in Loris but rather a feature of Firefox. When entering a date, month, or year, if it starts with '0', Firefox automatically sets all other fields to empty.
