### ISSUE TITLE
[user account] can't change self data

### ISSUE THREAD

**Issue by PapillonMcGill** [aces/Loris#6012]
**Describe the bug**
A user trying to modify it's own personnal data will fail with the message ` Please set pending approval Yes or No`

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Log in as a user with modify user_account permission 
2. Change some setting
3. Click on save

**What did you expect to happen?**
That the modification is accepted and no need to enter a confirmation that is not present.
The user can't confirm themself which is Ok but that should not block user modifying other parameters (like personnal data)

**Browser Environment (please complete the following information):**
- OS: Linux (Debian)
- Browser FireFox
- Version 68.4.1

**Server Environment (if known):**
- LORIS Version: 22
- Linux distribution and Version:  Ubuntu 16.04
- MySQL/MariaDB Version: MySQL 5.7

**Additional context**
User have ALL permission except Highlander

**Comment by johnsaigle** [comment]
I'm not able to reproduce this:

1. On `aces/master`, create new user `john` with "User Management" permission
2. As `john`, go to `User Accounts` (Edit User) module
3. Change name to `a brand new name`
4. Changes saved successfully, no error.

**Comment by PapillonMcGill** [comment]
Just confirmed that the bug is still there using current aces/master. 
Tried on Firefox 68.4.1 on Debian and 72.0.2 on MacOS

**Comment by PapillonMcGill** [comment]
More info:
This bug is present only when the user as the `Across all sites add and certify examiners` permission.
As user can't certify themself, the `pending approval` box is not displayed. It should then use the current value in the DB to pass in the POST.

**Comment by johnsaigle** [comment]
Hmmm should a user be able to change their own Examiner status? Probably not, I would think?

**Comment by johnsaigle** [comment]
Maybe we should fix that bug and then this one disappears.
