### ISSUE TITLE
Create object to represent a LORIS Instance

### ISSUE THREAD

**Issue by driusan** [aces/Loris#6022]
There is currently no concept of an installed LORIS instance for LORIS. Things that would logically belong in such a class tend to be scattered across the codebase in static functions or pseudo-globals (ie. the utility class, singletons, various factories) or be hardcoded with no canonical source of truth (ie. the `project/` directory.)

We should create a class to represent the installed LORIS instance, pass it around where appropriate, and use it.

**Comment by ridz1208** [comment]
:+1:

**Comment by driusan** [comment]
Blocked by #6023
