### ISSUE TITLE
A user should always have access to My Preferences

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6040]
**Describe the bug**
A "user management" permission is needed to edit one's preferences on LORIS since it is the same module as edit_user.

This is silly because it means a user can't update their own password, username, etc. easily.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Create a user with no permissions
2. On the top right, above logout, click My Preferences
3. You will be forbidden

**What did you expect to happen?**
You should be able to access the page whenever.

**Server Environment (if known):**
- LORIS Version: `aces/master`

**Comment by driusan** [comment]
Do you know when this started happening?

**Comment by johnsaigle** [comment]
Maybe around when the Module class was added? Or it could be due to the LorisMenu changes.

**Comment by johnsaigle** [comment]
We should add an integration test for this in the same bug fix PR.

**Comment by johnsaigle** [comment]
I traced some of the execution for this. The issue is coming from 

https://github.com/aces/Loris/blob/d8855fcb919b17672929c44115090f5b2cab42cd/modules/user_accounts/php/module.class.inc#L36-L39

Without `user_accounts`, a user cannot access either the My Preferences or Edit User endpoints.

This public Module::hasAccess() function call gets handled before the private `my_preferences->_hasAccess()`. Effectively this masks the subtleties in permission handling in My Preferences.

There's a chance that this affects other modules as well.

**Comment by driusan** [comment]
fixed by above PR
