### ISSUE TITLE
[data_release] manage permission modal window modification

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#6056]
**Is your feature request related to an existing module?**
data_release

**Describe the solution you'd like**
Display the data release versions in columns in the manage permission modal window instead of having one version per line, as shown in the image below:
![image](https://user-images.githubusercontent.com/1402456/74367222-7f5a8900-4d9f-11ea-8e03-3c2e913aaeb6.png)

**Comment by HenriRabalais** [comment]
PR Issued #6375
