### ISSUE TITLE
[API] Can not access visit through v0.0.2 of API

### ISSUE THREAD

**Issue by driusan** [aces/Loris#6058]
When attempting to access the URL http://localhost:8000/api/v0.0.2/candidates/965327/V06 on my sandbox I get an error "Unsupported Version".

The URL  http://localhost:8000/api/v0.0.3-dev/candidates/965327/V06 works properly.

However, the documentation for v0.0.2 says that the endpoint should be available in version 2 of the API, so both the released and development version of the API should be equivalent.

**Comment by spell00** [comment]
Candidate 965327 does not currently exist in raisinbread. Here is an alternative URL that currently should exist using PR https://github.com/aces/Loris/pull/7081 : http://localhost:8000/api/v0.0.2/candidates/300001/V1

**Comment by ridz1208** [comment]
@driusan the issue is still happening but is it worth supporting at this stage ?

**Comment by driusan** [comment]
I think it should be.. the code is there and working and we haven't removed v0.0.2 of the API. APIs are supposed to be stable and shouldn't suddenly stop working without notice.

**Comment by ridz1208** [comment]
@driusan okai, we should assign someone to this and have it in the next bugfix release then

**Comment by driusan** [comment]
0.0.2 no longer exists.
