### ISSUE TITLE
[tools] raininbread_refresh try to use unix user for BD access

### ISSUE THREAD

**Issue by PapillonMcGill** [aces/Loris#6060]
**Describe the bug**
running raisinbread_refresh script try to use local unix user to connect to BD instead of the user in config.xml
```
...
Checking connection via project configuration file...
Array
(
    [0] => ERROR 1045 (28000): Access denied for user 'lorisadmin'@'localhost' (using password: NO)
    [1] => mysql: [Warning] Using a password on the command line interface can be insecure.
)

[*] Dropping LORIS tables.
...
```
the script was able to complete.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. run `php raisinbread_refresh.php`

**What did you expect to happen?**
script run flalessly

**Server Environment (if known):**
- LORIS Version: [aces/master, latest commit at date]
- Linux distribution and Version: [e.g. Ubuntu 16.04]
- MySQL/MariaDB Version: [e.g. MySQL 5.7]

**Additional context**
adminUser and adminPassword properly set in config.xml
Possible that a commit was lost in a rebase of https://github.com/aces/Loris/pull/5260

**Comment by PapillonMcGill** [comment]
Message from exception displayed on the screen.  Script work around this. 

Not a bug

**Comment by PapillonMcGill** [comment]
Redirection problem.

**Comment by johnsaigle** [comment]
Yep I think it should be fixed by the above PR. It's trying to connect via a DB configuration file and the error message should be hidden if it doesn't exist.
