### ISSUE TITLE
[Document Repository] Module broken, does not load

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6066]
**Describe the bug**
When loading the module, the table and filters load briefly then disappear, leaving a blank page. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to aces/master
2. Go to the Document Repository

**What did you expect to happen?**
The module should load.

**Browser Environment (please complete the following information):**
- OS: macOS Catalina 
- [x] Tested on Chrome and Firefox
- Version aces/master

**Additional context**
There is a lot of information in the browser console.log so a UI person should look here.

**Comment by driusan** [comment]
PR merged
