### ISSUE TITLE
[media] Downloading file with special characters in name leads to error: Failed - no file

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#6136]
**Describe the bug**
There is an error when downloading files from media module that contain special characters in its name (ex: '&').  Error message that appears says "Failed - No File". This is likely occurring because SQL changes such characters to their html encoding. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to media module.
2. If no file with special characters (&, >, <, etc) is available, upload one yourself.
3. Try downloading that file now.
4. See error - Failed, no file.

**What did you expect to happen?**
File should download normally.

**Browser Environment (please complete the following information):**
- OS: Ubuntu
- Browser: Chrome

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: 21.0 and (i suspect) onward
- Linux distribution and Version: Ubuntu 16.04
- MySQL/MariaDB Version: MySQL 5.7

**Comment by johnsaigle** [comment]
There's a chance that this affects other modules with file download capabilities too.
