### ISSUE TITLE
electrophysiology_browser SQL table not installed automatically

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6163]
new installation won't have access to `electrophysiology_browser` because the installer doesn't include the SQL of `electrophysiology_browser`

**Comment by cmadjar** [comment]
What installer?

**Comment by lingma** [comment]
> What installer?

The Loris installer. I checked, nothing mentioned, I will create a PR soon.

**Comment by johnsaigle** [comment]
Resolved by linked PR
