### ISSUE TITLE
NDB_BVL_Instrument variable declarations not clear or wrong

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6178]
In the declartion of NDB_BVL_Instrument, we have
   /**
     * Array of required fields to check
     *
     * @access private
     */
    var $_requiredElements = array();
@access private should be wrong, in fact $_requiredElements is public as declared, it could be protected. In both case, _ is not necessary. There are other variables with the similar issues in the same file.

The description should be more clear as to what this variable is to be used, what values are expected. The issue has been seen before, but noticed in the PR #5949, we need to address the issue once the PR has been merged to avoid merge conflicts.

**Comment by johnsaigle** [comment]
> In both case, _ is not necessary.

This is required by PHPCS for variables declared as `private`.

**Comment by lingma** [comment]
They should in fact "protected", declared as "public", documented and declared as "private"

**Comment by johnsaigle** [comment]
> They should in fact be "protected", but declared as "public"

I'm confused by this. If something is declared public, it's public, not protected.

**Comment by lingma** [comment]
If it is public, then say it public in the document zone, instead it is said to be "private"

It is OK to be public, but better to be protected
