### ISSUE TITLE
Candidate Profile [Beta] does not have a test plan

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6207]

**Comment by johnsaigle** [comment]
@driusan I removed your assignment since I took care of this already.

**Comment by driusan** [comment]
I already wrote a test plan since it was assigned to me.

**Comment by driusan** [comment]
Related issues for modules that register widgets which have an out of date test plan: #6433, #6434, #6436, #6437, #6438, #6439, #6440, #6441, #6443
