### ISSUE TITLE
[electrophysiology_browser] Breadcrumbs Broken in EEG Browser

### ISSUE THREAD

**Issue by driusan** [aces/Loris#6212]
After clicking on a link to a session in the EEG browser, the URL is `$LORIS/electrophysiology_browser/sessions/$sessionID`. The breadcrumb for the word "Sessions" on the Page goes to `$LORIS/electrophysiology_browser/sessions`. However, the latter URL is a 404 page with the error "Invalid session".

**Comment by cmadjar** [comment]
Is there a reason why this is not closed? Looks like the linked PR has been merged but maybe I am missing something...

**Comment by driusan** [comment]
I think the autoclose keyword only works on master
