### ISSUE TITLE
[issue tracker] Add raisinbread data for issue tracker attachments

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#6215]
**Describe the bug**
the attachments should have mock data to be easily testable

**Comment by driusan** [comment]
Can't you just upload an attachment? The uploading needs to be tested too..

**Comment by maltheism** [comment]
I think this would require a place to store the mock files from rasinbread on the development system. Where would be the best place to store besides making a folder in the root directory of loris?

**Comment by ridz1208** [comment]
fine by me... i tried
