### ISSUE TITLE
[Instrument List] Mysterious checkboxes require documentation

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6218]
**Describe the bug**
See the image attached: 
![image](https://user-images.githubusercontent.com/5295785/78158254-feb72100-740e-11ea-8d2a-6780d830b40c.png)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to instrument list of any candidate
2. Click on "double data entry"
3. Look at the left top corner

**What did you expect to happen?**
There should be a text to explain what those buttons are

**Browser Environment (please complete the following information):**
- Chrome

**Server Environment (if known):**
- LORIS Version: 23-release

**Comment by lingma** [comment]
It is better to have a help text which could popup when putting the mouse over there.

Another way to do is that the concept of the 2 checkbox has to be modified to be simple.

**Comment by christinerogers** [comment]
Update: To be resolved in a new PR by @pierre-p-s 

in order to implement the solution discussed in #6225 by @driusan and @pierre-p-s


-- including [this update for swal2](https://github.com/aces/Loris/pull/6225#issuecomment-613476175) suggested by @haoweiqiu (Thanks Haowei!) :

> However, I think we are turning to use SweetAlert2 now. Here's my tweak on your code.
```
<script>
    function swalFunction() {
    Swal.fire({
      title: 'Please confirm deletion',
      text: 'The instrument data will be deleted',
      type: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, delete the data'
    }).then((result) => {
  if (result.value) {
    Swal.fire(
      'Deleted!',
      'The instrument data has been deleted.',
      'success'
    )
  }
});
  }
</script>
 ```
