### ISSUE TITLE
[instrument battery] imaging data button

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6219]
**Describe the bug**
See the image:
![image](https://user-images.githubusercontent.com/5295785/78161656-ccf48900-7413-11ea-850d-16b561f7cce1.png)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. click on the candID 587630, V2
![image](https://user-images.githubusercontent.com/5295785/78161551-9f0f4480-7413-11ea-9ccc-e8f4b369bdd7.png)

2. Click on 'View Imaging data"'
3. See error 502

**What did you expect to happen?**
If error, say what happened.

**Server Environment (if known):**
- LORIS Version:23

**Comment by lingma** [comment]
This behavior comes probably from the fact that some instruments are not in the list, this behaviour could probably be fixed in the imaging browser module

**Comment by lingma** [comment]
I copied the following text from PR#6221:

The Imaging Browser is set to be anywhere at instrument list, at the same time if some instruments are not present, then the Imaging Browser module will report that fact as an exception, clearly the overall design logic is not correct somewhere.

**Comment by lingma** [comment]
A new commit has been submitted, this will solve the link status 500 error.

**Comment by johnsaigle** [comment]
This seems to be resolved based on the linked PRs
