### ISSUE TITLE
facebook module version in composer.json

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6220]
**Describe the bug**
If you do `composer install` then `make`, you will have
![image](https://user-images.githubusercontent.com/5295785/78163749-cb789000-7416-11ea-8085-7d7fec06c3d7.png)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Do `make dev` or `composer install`
2. Do `make` you will have an error

**What did you expect to happen?**

**Server Environment (if known):**
- LORIS Version: 23

**Comment by maltheism** [comment]
I believe @johnsaigle has fixed this in one of his PRs I reviewed.

**Comment by johnsaigle** [comment]
This should be resolved by #6187.
