### ISSUE TITLE
[test VM] candidate_profile module not installed on VM

### ISSUE THREAD

**Issue by driusan** [aces/Loris#6227]
In the `module_manager` module there is no `candidate_profile` on the test VM. As a result, the candidate info card doesn't show up when choosing `New Access Profile (beta)` from the menu on the test VM (other module's cards do, but there's no way to access a visit from the candidate info card, since it's part of the `candidate_profile` module.)

**Comment by kongtiaowang** [comment]
@driusan It works now.
