### ISSUE TITLE
[survey_accounts] Insufficient data in RB/test VM for test plan

### ISSUE THREAD

**Issue by driusan** [aces/Loris#6230]
Item 2 of test plan:

```
2.  Selection Filter:  try filtering by PSCID, Visit, and Instrument.
    [Automation Testing]
```

There is only one instrument configured, so the instrument filter can not be tested. Whether filtering for that instrument or all instruments gives the same result..

**Comment by ridz1208** [comment]
@driusan for testing purposes you can just enable any other istrument (set as directentry) and remove it after

**Comment by driusan** [comment]
@ridz1208 As far as I know it's not possible to do that without backend access.

**Comment by ridz1208** [comment]
true

**Comment by johnsaigle** [comment]
@ridz1208 Did the linked PR fix this?

**Comment by ridz1208** [comment]
@johnsaigle yes
