### ISSUE TITLE
[acknowledgements] "Present" option in module unclear

### ISSUE THREAD

**Issue by driusan** [aces/Loris#6231]
There is a column "Present" in the acknowledgement table. It's a boolean. Neither the help text nor test plan describe what it is supposed to mean. It doesn't appear to be used for anything other than displaying "Present: Yes/No" in the table.

It works properly (in that it saves), but it's confusing. Can it just be removed?

**Comment by cmadjar** [comment]
A little background about that confusing column. This is a field to mention whether the person to acknowledge is still actively working on the project.

The naming could be changed to something clearer, I agree, but I would not remove this option.

**Comment by driusan** [comment]
What's the difference between "Present" and "today's date is between start date and end date"?

**Comment by cmadjar** [comment]
Plan discussed during roadmap call of Jan 10, 2023
Remove the column "Present" and instead derive this information depending if there is an end date. If there is an end date, person is not present, if there is no end date, person is still present.
