### ISSUE TITLE
[Login] request account does not request an account

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#6233]
**Describe the bug**
When requesting a new account, the account does not show in the list of the admin user accounts. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to login -> request account
2. Fill all the fields and submit
3. Login as admin
4. The newly requested account does not appear in the list of user-accounts

I have a suspicion that it might be related to the project permission. I.e. the account is there but not visible.

**Comment by ridz1208** [comment]
If the suspected issue is correct. 

- Admin account should be able to view all users regardless of permissions
- request account should get a mandatory project field

**Comment by johnsaigle** [comment]
Request account displays a Success message even when account creation fails. It's possible that there was another processing error that you can view in the error log.

**Comment by johnsaigle** [comment]
I got this error when trying to load user_accounts after using request_account:

`PHP Fatal error:  Uncaught TypeError: explode() expects parameter 2 to be string, null given in /var/www/loris/modules/user_accounts/php/useraccountrowprovisioner.class.inc:48`

**Comment by johnsaigle** [comment]
@ridz1208 is this resolved?
