### ISSUE TITLE
[UI] on mobile devices once a menu tab is open it cannot be closed

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#6235]
**Describe the bug**
When one opens any of the menus, there is no way to re-close it to select another menu item.

![Screenshot_20200402-130930_Chrome](https://user-images.githubusercontent.com/15268287/78278056-7a829d80-74e3-11ea-8759-321c6fc0a094.jpg)

**Comment by maltheism** [comment]
@ridz1208 Although I assume this css behaviour is from bootstraps. I think this can be fixed. We just should disable the onclick css styling for the row and have onhover handle the styling change. I'm curious if the menu even works on mobile devices because the menu isn't staying open onclick.
