### ISSUE TITLE
[Data release] should a user ever lose acces to his own upload ?

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#6237]
**Describe the bug**
When a user uploads a file, they associate it with a version. An administrator can then grant access to files based on their versions to different users. Which means an admin can lock a user out of their own upload...

Should that be the case?

**Comment by johnsaigle** [comment]
It's a little strange in this case but in general I think it makes sense that the admin can restrict user permissions if necessary.

**Comment by maltheism** [comment]
Why would the same file that was uploaded require a new version if nothing has been changed in the file content? I'm wondering how this would ever happen.

**Comment by driusan** [comment]
I think I agree with @johnsaigle .. if an admin wants to restrict access, why not?

**Comment by ridz1208** [comment]
Okai, just checking
