### ISSUE TITLE
[Data release] Downloaded csv has #### instead of dates

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#6241]
**Describe the bug**
when you download the CSV representing the release list, all upload dates show up as `####` in the downloaded file

![SmartSelect_20200402-165743_Excel](https://user-images.githubusercontent.com/15268287/78299976-bbd77500-7504-11ea-86c7-0e15df4ca513.jpg)

**Comment by HenriRabalais** [comment]
Cannot Replicate Issue.

<img width="386" alt="Screen Shot 2020-04-14 at 15 19 21" src="https://user-images.githubusercontent.com/7550451/79264936-53bd5300-7e63-11ea-9036-17f00fdd1199.png">

**Comment by ridz1208** [comment]
I just tried it again and you are correct.

**Comment by lingma** [comment]
Oh, you can replicate the issue for sure. But the issue is not Loris problem. You can just move that Upload Date column small to replicate
