### ISSUE TITLE
[Data release] Manage permission form persistence issues

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#6242]
**Describe the bug**
when assigning version permissions to users from the manage permissions form, after checking boxes, saving and reloading the form, the checked boxes are back empty

**To Reproduce**
Steps to reproduce the behaviour (attach screenshots if applicable):
1. go to data release -> manage permissions
2. Check some boxes
3. save
4. reload form

Step 2
![Screenshot_20200402-171442_Chrome](https://user-images.githubusercontent.com/15268287/78300844-29d06c00-7506-11ea-9903-831b04ca17ca.jpg)

Step 3
![Screenshot_20200402-171448_Chrome](https://user-images.githubusercontent.com/15268287/78300843-2937d580-7506-11ea-92d4-f3c43f20128c.jpg)

Step 4
![Screenshot_20200402-171510_Chrome](https://user-images.githubusercontent.com/15268287/78300841-2937d580-7506-11ea-8cf1-f8db7f482063.jpg)

**Comment by HenriRabalais** [comment]
PR Issued #6375
