### ISSUE TITLE
[dashboard] Pending approval link error page 

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#6245]
**Describe the bug**
When some user accounts are still pending approval, an entry in the `My Tasks` panel on the dashboard appears "X Pending account approval"

clicking on that link leads to a loris error page

<img width="1680" alt="Screen Shot 2020-04-02 at 5 36 29 PM" src="https://user-images.githubusercontent.com/15268287/78302343-95b3d400-7508-11ea-8fc8-be3e0df4cbb6.png">
<img width="516" alt="Screen Shot 2020-04-02 at 5 36 39 PM" src="https://user-images.githubusercontent.com/15268287/78302345-964c6a80-7508-11ea-9635-a01d086af307.png">

**Comment by ridz1208** [comment]
Most probably related to #6233

**Comment by johnsaigle** [comment]
@jesscall @ridz1208 Can this be closed?
