### ISSUE TITLE
[dataquery] incorrect pagination after search

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#6247]
**Describe the bug**
In the dataquery tool, whensearching WITHIN an instrument, under the search result the pagination is incorrect. It does not get updated after the search results are returned.

In the image below, I search for `q9` which returns 3 search results but the pages under go up to 8

<img width="1680" alt="Screen Shot 2020-04-02 at 5 47 38 PM" src="https://user-images.githubusercontent.com/15268287/78303334-76b64180-750a-11ea-9d46-65bec1cb9e92.png">

**Comment by HenriRabalais** [comment]
PR Issues #6400

**Comment by cmadjar** [comment]
@HenriRabalais @driusan is this issue resolved? I see the PR has been merged but the issue is not closed. Just wanted to follow up. Thanks!

**Comment by HenriRabalais** [comment]
Yes, it's resolved!
