### ISSUE TITLE
[dicom_archive] Archive Location broken?

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#6248]
**Describe the bug**
Visiting the dicom_archive module and clicking on links in the table of the "Archive Location" will not do anything. I'm not sure if this is a bug or files don't exist on the testing VM.

**Comment by kongtiaowang** [comment]
@maltheism 
Base on the test plan : "Ensure that clicking on any row in the 'Archive Location' column triggers a download of the corresponding archived DICOM study. Make sure that the copy of the file downloaded to your system is prepended with the Patient Name field. "
I have tested it, the download function works. I don't think this is a bug.

**Comment by maltheism** [comment]
Thanks @kongtiaowang, I'm closing this issue then.
