### ISSUE TITLE
Broken Links in documentation

### ISSUE THREAD

**Issue by ridhishjain** [aces/Loris#6254]
**Describe the bug**
The link for the unit testing guide in [testing guide](https://github.com/aces/Loris/blob/master/docs/wiki/99%20-%20Developers/Automated%20Testing.md) is broken

**To Reproduce**
1. Go to `CONTRIBUTING.md`
2. Click on testing guide link given in section **Some things to keep in mind**
3. See error

**What did you expect to happen?**
Unit testing guide was supposed to open

**Additional information:**
I am working on this issue

**Comment by laemtl** [comment]
Resolved in #6192
