### ISSUE TITLE
Broken Links in documentation

### ISSUE THREAD

**Issue by ridhishjain** [aces/Loris#6256]
**Describe the bug**
The link for raisinbread readme is broken in contributing.md

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `CONTRIBUTING.md`
2. Click on detailed steps link given under **Some things to keep in mind** (fifth part under the first point)
3. See error

**What did you expect to happen?**
RsaisinBread readme was supposed to open

**Additional context**
I am working on this issue

**Comment by laemtl** [comment]
Solved in #6546
