### ISSUE TITLE
[Dashboard] 'Incomplete Forms' link leads to error page

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#6258]
Clicking on the 'Incomplete Forms' link found in the 'My Tasks' menu leads to a non existent page and thus gives you an error. 

Link is: https://test-loris-dev.loris.ca/statistics/statistics_site/

![Screen Shot 2020-04-04 at 6 57 18 PM](https://user-images.githubusercontent.com/54332302/78463051-88cce700-76a6-11ea-8fed-6f1c51cbcbca.png)

![Screen Shot 2020-04-04 at 6 57 44 PM](https://user-images.githubusercontent.com/54332302/78463054-91bdb880-76a6-11ea-9a02-44ece6bae5d4.png)

**Comment by kongtiaowang** [comment]
When I tested the instrument_manager, I uploaded a file named "test.linst.linst" by accident. It created a wrong table named "test.linst" into database. It works fine after I removed the wrong table.
