### ISSUE TITLE
[Data Dictionary] Empty field in 'Source From' dropbox

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#6260]
When opening the 'Source From' dropbox to filter results by source, the second option is an empty field. If you click on it it leads to no results. The first field could include the 'All' text to indicate it shows all entries.

![Screen Shot 2020-04-04 at 8 17 55 PM](https://user-images.githubusercontent.com/54332302/78463976-b3706d00-76b1-11ea-99e1-b7688066cb16.png)

**Comment by ridz1208** [comment]
@SantiagoTG issue was only on test VM due to an instrument with no name in the table.

it's solved now
