### ISSUE TITLE
Data Dictionary Page not Working

### ISSUE THREAD

**Issue by ShubhamDhingra96** [aces/Loris#6261]
When opening a Data dictionary page in order to fill the credentials It is not working.

![Untitled (2)](https://user-images.githubusercontent.com/54913662/78464645-cedf7600-76b9-11ea-9e42-c2ce92de8553.png)

**Comment by christinerogers** [comment]
Thanks, which version?   Is this on the master branch or the 23 release branch ?

**Comment by ShubhamDhingra96** [comment]
Yes it was previously on the 23 release but now it's working fine. Thanks

**Comment by johnsaigle** [comment]
The data dictionary seems to be loading fine on `master` and `23.0-release`. This is probably an issue of the JS not being compiled, especially if ti started working soon after.

@christinerogers I'm going to close this for now but feel free to re-open it if you test this and the module appears broken.

**Comment by ShubhamDhingra96** [comment]
Yes john I have checked it it's working fine now.
