### ISSUE TITLE
"Issue Tracker" Priority Dropdown Issue

### ISSUE THREAD

**Issue by ShubhamDhingra96** [aces/Loris#6262]
On the Issue tracker page while sorting the issue on the basis of priority, The dropdown doesn't have field "Low"  while in the displayed issues The priority column has value Low.

![Issue](https://user-images.githubusercontent.com/54913662/78465717-289a6d00-76c7-11ea-9661-e5cce649ef30.png)

**Comment by christinerogers** [comment]
@laemtl thanks for tackling this for the 23 release -- your new issue specifically for 23 should reference this Issue and also PR #6263
