### ISSUE TITLE
[instrument] AOSI

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6269]
**Describe the bug**
The instrument itself is not clear, as an example this is not a problem but not optimised.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'profile'
2. Click on 'AOSI on any V2 timepoint'
3. See the screenshot.
![image](https://user-images.githubusercontent.com/5295785/78567778-30553100-77ef-11ea-9374-e46cb20a078f.png)

**What did you expect to happen?**
"(Circle one)" is the paper version term, this should be adapted to the computer version term

**Server Environment (if known):**
- LORIS Version: 23.0

**Comment by cmadjar** [comment]
@nicolasbrossard @driusan is this issue closed? I see the PR has been merged so wondering...
Thanks!

**Comment by nicolasbrossard** [comment]
@cmadjar Yeah, I fixed this.
