### ISSUE TITLE
[Media] File Upload Page not getting refreshed

### ISSUE THREAD

**Issue by ShubhamDhingra96** [aces/Loris#6270]
**Describe the bug**
While uploading a file on the media page, The site field is not getting refreshed when we change the "PSCID"

 For Example: When I select OTT186 as my PSCID, and for the site Ottawa will come as a option in dropdown on the basis of my PSCID But when I re-select my PSCID as ROM230 it is still showing me Ottawa in the site box, The page is not getting refreshed.

**What did you expect to happen?**
The page should get refreshed when the PSCID is reselected. 

![image](https://user-images.githubusercontent.com/54913662/78519538-b6db2580-7791-11ea-92a7-39e9221d5026.png)

**Comment by christinerogers** [comment]
Possibly a bug for 23 release, ? 

not found during our loris team testing, but found by this GSOC applicant.

**Comment by ridz1208** [comment]
https://github.com/aces/Loris/issues/6309
https://github.com/aces/Loris/issues/5055

multiple duplications

**Comment by ShubhamDhingra96** [comment]
Yes It was indeed in that version

**Comment by ridz1208** [comment]
@ShubhamDhingra96 According to #5577 The site field no longer exists in the media upload form as of LORIS version 22.

as you can see on our instance of LORIS (see image) that field does not appear. It seems like you might be on an older version of LORIS or have dated compile JS files. try recompiling your files or re-installing a more up to date version.

<img width="1131" alt="Screen Shot 2020-04-08 at 9 45 33 AM" src="https://user-images.githubusercontent.com/15268287/78791544-041bea80-797e-11ea-99e8-c117979fad51.png">

A new issue has been created to update the testplan https://github.com/aces/Loris/issues/6336

**Comment by ShubhamDhingra96** [comment]
Okay I will check it once  Thanks for the update
