### ISSUE TITLE
[candidate_parameters] extra slash after clicking Candidate Info

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#6273]
**Describe the bug**

Clicking on the "Candidate Info" button while viewing a PSCID from access profile.

Will result in `https://test-loris-dev.loris.ca//candidate_parameters/?candID=115788&identifier=115788`

**Comment by lingma** [comment]
this should be the same as #6271

**Comment by maltheism** [comment]
Sorry @lingma I didn't see. I'll update the Testing 23.0 card.

**Comment by lingma** [comment]
> Sorry

Oh, maybe I tested your part, I just saw that on timepoint list, then reported it.

**Comment by maltheism** [comment]
@lingma thanks for testing it anyways. More eyes on the module is better than just mine!
