### ISSUE TITLE
[User Accounts] Module Manager permissions do not appear when editing user

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6274]
**Describe the bug**
There doesn't seem to be a way to edit a user's permissions for Module Manager from the front-end.

**To Reproduce**
Steps to reproduce the behaviour (attach screenshots if applicable):
1. Edit a user in `user_accounts`. The Module Manager permissions do not appear.

The permissions are sorted alphabetically by description, so the Module Manager should appear here.

### Screenshot 1 - Permissions should appear

<img width="470" alt="Screen Shot 2020-04-06 at 11 08 39" src="https://user-images.githubusercontent.com/4022790/78573897-4109a500-77f7-11ea-8004-0ec598db152a.png">

### Screenshot 2 - Permissions with descriptions in back-end.

<img width="620" alt="Screen Shot 2020-04-06 at 11 10 53" src="https://user-images.githubusercontent.com/4022790/78573938-4f57c100-77f7-11ea-9798-8af535988fac.png">

**What did you expect to happen?**
The Module Manager permissions should appear as checkboxes.

**Browser Environment (please complete the following information):**
- OS: MacOS
- Browser: Chrome

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 23.0.0]
- Linux distribution and Version: Ubuntu 18.04
- MySQL/MariaDB Version: MySQL 5.7

**Additional context**
* Tested on my VM as `user_accounts` is currently inaccessible from the Test VM.
* Tested on 23.0-release. I used `tools/raisinbread_refresh.php` and `make dev` on the branch.

**Comment by johnsaigle** [comment]
https://github.com/aces/Loris/blob/ce4ee70d87e5f6adff71b48a8ca1ecd6c886ec59/raisinbread/RB_files/RB_permissions.sql#L64-L65

https://github.com/aces/Loris/blob/ce4ee70d87e5f6adff71b48a8ca1ecd6c886ec59/raisinbread/RB_files/RB_user_perm_rel.sql#L64-L65

@ridz1208 I think you're right. It looks like `user_perm_rel` is missing some entries.

**Comment by ridz1208** [comment]
Indeed
