### ISSUE TITLE
[breadcrumbs] hidden breadcrumbs when browser width resized

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#6278]
**Describe the bug**
Breadcrumbs becomes hidden under the menu and when browser width is resized as the image illustrates:

![breadcrumbs_missing](https://user-images.githubusercontent.com/16293415/78577798-9dbb8e80-77fc-11ea-9f88-d03663448ab2.png)

**Comment by johnsaigle** [comment]
Closing this because the linked PR is merged
