### ISSUE TITLE
[Imaging Browser] No Caveat List Link

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6280]
**Describe the bug**
> Caveat List link is viewable with the Violated Scans: View all-sites Violated Scans permission

-- Test Plan

When testing the module, I couldn't find anything that was labelled "Caveat List" with any permission.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to Imaging Browser and try to follow this item in the test plan. 

**What did you expect to happen?**
I think there's supposed to be some link labelled Caveat Link but I couldn't find one.

**Browser Environment (please complete the following information):**
- OS: Ubuntu
- Browser: Chrome

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 23.0.0]
- Linux distribution and Version: Ubuntu 18.04
- MySQL/MariaDB Version: MySQL 5.7

**Comment by nicolasbrossard** [comment]
The caveat link is only displayed if you set the Caveat status of a specific image to 'True':

![image](https://user-images.githubusercontent.com/6844033/79015726-6241fc80-7b3b-11ea-811c-ca0671391fd9.png)

**Comment by johnsaigle** [comment]
Thanks, I'll try that. I'll also update the test plan to make that more clear.

**Comment by ridz1208** [comment]
@johnsaigle was the testplan update done ?

**Comment by johnsaigle** [comment]
Nope I haven't been able to do this task yet. It'll won't be done until Monday at the earliest.

**Comment by ridz1208** [comment]
@nicolasbrossard could you take care of this one ?
