### ISSUE TITLE
[imaging_uploader] Uploading phantom scan unsuccessful

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#6285]
**Describe the bug**
On trying to upload a phantom scan (no requirements for file name), the progress bar goes to 100%, but nothing happens (success swal doesn't pop up, page not redirected). In console log, we get a 500 error and a JS uncaught type error:

<img width="1190" alt="Screenshot 2020-04-06 13 32 52" src="https://user-images.githubusercontent.com/17415878/78588450-a6b45c00-780c-11ea-8c88-2b0acbc3aeb5.png">

Additionally, this issue happens: https://github.com/aces/Loris/issues/6288

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'Imaging Uploader' module
2. Click on 'Upload' tab
3. Fill in the form: 'Phantom Scans': Yes
4. Upload a file into 'File to Upload' field, with any name but with correct file types .tgz or tar.gz or .zip
5. Click 'Submit' 
6. See console log errors as in the screenshot above. No swal pops up where it should.

**What did you expect to happen?**
On clicking 'Submit', the upload should be successful, or if not, a swal with the corresponding error should pop up to notify the user.

**Comment by ridz1208** [comment]
You can contact @cmadjar
