### ISSUE TITLE
"Dicom Archive" Sex Filter doesn't have Dropdown.

### ISSUE THREAD

**Issue by ShubhamDhingra96** [aces/Loris#6286]
**Describe the bug**
In Dicom Archive page, the sex field doesn't contain any dropdown which will contain the values Male and Female it is just having normal text field in which a user can type anything 

For Example, You can see in the screenshot that in the displayed data the sex entered is O which is a duplicate value.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'Imaging Tab'
2. Click on 'Dicom Archive'
3. In Selection filter 
4. See Sex Filter

**What did you expect to happen?**
There should be a dropdown in place of a text field. So that user can select Male or Female from the dropdown.

Browser Environment (please complete the following information):

OS: Ubuntu
Browser: Chrome

Server Environment (if known):
Note: We only support the most recent release of LORIS.
LORIS Version: [e.g. 23.0.0]

![Dicom](https://user-images.githubusercontent.com/54913662/78589357-1a0a9d80-780e-11ea-80ca-02a797e30ae5.png)

**Comment by christinerogers** [comment]
Thanks for spotting this.  @ShubhamDhingra96 Was this on the master branch or on the 23.0-release branch?

**Comment by johnsaigle** [comment]
@christinerogers I checked it out after the issue was reported and it's on both. It should be fixed by #6292

**Comment by ShubhamDhingra96** [comment]
@christinerogers  I have checked it was in 23.0 release
