### ISSUE TITLE
[Configuration Module] Usability: error could be more specific and the field with the error is not highlighted.

### ISSUE THREAD

**Issue by racostas** [aces/Loris#6287]
**Is your feature request related to an existing module?**
Configuration Module.

**Describe the solution you'd like**
When having a duplicate entry the error shown is always "ERROR: Duplicate Value In The Instrument Form". The specific field with the issue  is not highlighted making a bit harder to the user to find were the error is.

**Describe alternatives you've considered**
To clarify the error message according to the field were is was issued and possible highlight it for facilitating the user fix.

**Additional context**
<img width="869" alt="ConfigMod-error_message" src="https://user-images.githubusercontent.com/37309344/78615493-ac776500-783f-11ea-9dcd-733c69c53ed9.png">

**Comment by johnsaigle** [comment]
I issued a PR to improve the error message but this is more of a feature enhancement than a bugfix for the release. I'd suggest keeping this issue open but removing the 23 label @ridz1208

**Comment by xlecours** [comment]
Hi @racostas. Since https://github.com/aces/Loris/pull/6419 is merged, is this issue fixed?
