### ISSUE TITLE
[imaging_uploader] Test plan #5 fails

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#6288]
**Describe the bug**
Test plan #5:
`Ensure that the 'Upload' tab has the CandID, PSCID, and Visit Label greyed out. These greyed out fields remain empty if the 'Phantom Scans' is set to Yes, and are properly filled based on the uploaded filename if 'Phantom Scans' is set to No.
[Manual Testing]`

The bug: The greyed out fields do not remain empty if the 'Phantom Scans' is set to Yes. On uploading a file, the greyed out fields are filled out according to the file name (this auto-filling should only happen if 'Phantom Scans' is No)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'Imaging Uploader' module
2. Click on 'Upload' tab
3. Fill in the form: 'Phantom Scans': Yes
4. Upload a file into 'File to Upload' field, with any name but with correct file types .tgz or tar.gz or .zip
5. You will see that the CandID, PSCID, and Visit Label fields are auto-populated according to the file name (this shouldn't be the case).

**What did you expect to happen?**
See #5 of test plan

**Comment by ridz1208** [comment]
linked PR was merged
