### ISSUE TITLE
[Configuration/Subproject] Wrong error message.

### ISSUE THREAD

**Issue by racostas** [aces/Loris#6290]
**Describe the bug**
When Editing / Crating a new sub-project if the field "Recruitment Target" is filled with a non numerical value the error issued is bit confusing: "Failed to save, same title already exist!"  In place the error should be Failed to save, value not integer.

**To Reproduce**
Steps to reproduce the behaviour (attach screenshots if applicable):
1. Go to Configuration -> Subproject
2. Create or Edit a subproject
3. Enter a non numerical value on the Recruitment Target field

**What did you expect to happen?**
 In place the error should be Failed to save, value not integer.

**Related issue**
 #4770

![image](https://user-images.githubusercontent.com/37309344/78591364-512e7e00-7811-11ea-9d4b-1e81a0444021.png)

**Comment by xlecours** [comment]
Fixes #4770

**Comment by ridz1208** [comment]
@xlecours this issue does not resolve the other issue you linked...

PR 6335 resolves this issue
