### ISSUE TITLE
[instruments] There is no test plan

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#6293]
**Describe the bug**
There is no test directory, TestPlan.md of instruments_Test.php for the instruments module

**Comment by driusan** [comment]
I believe raisinbread and the `$LORIS/test` directory has some tests for instruments, they might be able to be repurposed for the instruments module.

**Comment by ridz1208** [comment]
@PapillonMcGill will you be able to address this ?

**Comment by jesscall** [comment]
Reminder to @PapillonMcGill to add the following in the instrument test plan:

> Check that filling out any instrument with a _Date of Administration_ later than the DoD changes the age displayed to the candidate's age at death (in months).
