### ISSUE TITLE
[User Accounts] Test Plan #5 Failed

### ISSUE THREAD

**Issue by sruthymathew123** [aces/Loris#6294]
**Describe the bug**
`Verify that if the editor does not have permission 'Across all sites add and edit users' then the site drop-down list is populated with the editor's associated sites, otherwise all sites are displayed.`
This is failing

**To Reproduce**
1. Create a user with one site affiliation '...'
2. Make sure the created user has 'User Management' Permission
3. Verify that the created user does not have permission 'Across all sites add and edit users' 
4. Login as that created user and now that user's site drop-down list is populated with all sites.

**Comment by johnsaigle** [comment]
I'm not able to reproduce this on my VM.

1. On Raisinbread, 23.0-release:
* Create a user `john` with permission "User Management", site "Ottawa", Project "Rye" and no other permissions, sites, or projects
2. As `john`, go to User Accounts > Add User
3. On the `edit_user` page, this is displayed as Site and Project options for a new user:

#### Screenshot 1 - Add User from point of view of `john`

<img width="383" alt="Screen Shot 2020-04-06 at 14 58 08" src="https://user-images.githubusercontent.com/4022790/78594862-0ca5e100-7817-11ea-9f4e-6b14463fca05.png">


#### Screenshot 2 - Possible Sites and Projects from point of view of super user `admin`

<img width="468" alt="Screen Shot 2020-04-06 at 14 56 04" src="https://user-images.githubusercontent.com/4022790/78594838-01eb4c00-7817-11ea-80d5-9d4925def73e.png">

**Comment by johnsaigle** [comment]
I did notice that the Site filter from the `user_accounts` page displays all users across sites, however. Is that what you meant?

**Comment by sruthymathew123** [comment]
@johnsaigle Yes, that is what I meant.

**Comment by johnsaigle** [comment]
It looks like this line should be deleted from the test plan.

It was added here https://github.com/aces/Loris/pull/4786/files to fix this issue https://github.com/aces/Loris/issues/4741. However, the issue doesn't mention anything about the Site field being pre-populated with the user's sites and I'm not sure this was ever a feature.

I also don't know if this is possible to do given the way the filter works. It's a dropdown, not a multi-select. So if a user has two sites, Montreal and Ottawa, there is no way to populate both of them at once within the site dropdown.

**Comment by sruthymathew123** [comment]
@johnsaigle In that case, as you mentioned the line should be deleted from test plan. Otherwise it will be confusing.

**Comment by johnsaigle** [comment]
I can remove it now

**Comment by johnsaigle** [comment]
This can be closed when #6320 is merged.
