### ISSUE TITLE
[Genomic Browser] Subproject Column displayed as Integer instead of Label

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#6295]
**Describe the bug**
A. In the Profiles tab of the Genomic Browser, when downloading the Table as a CSV, the SubProject is displayed as an integer instead of a string label.

B. In the SNP tab of the Genomic Browser, the SubProject is displayed as an integer in the table instead of a string label

Test Plan Reference: https://github.com/aces/Loris/blob/master/modules/genomic_browser/test/TestPlan.md#data-download

**To Reproduce**
Steps to reproduce the behaviour (attach screenshots if applicable):
A.
1. Go to Profiles Tab of Genomic Browser
2. Click on Download as CSV.
3. Look at Subproject column of downloaded CSV.

B.
1. Go to SNP Tab of Genomic Browser
2. Look at Subproject column datatable.

A.
![image](https://user-images.githubusercontent.com/7550451/78593395-90120300-7814-11ea-88bb-9c2d8845b6b7.png)

B.
![image](https://user-images.githubusercontent.com/7550451/78593439-a029e280-7814-11ea-83e7-2f909720ddbc.png)

**Comment by ridz1208** [comment]
@xlecours will you be able to address this ?

**Comment by xlecours** [comment]
@ridz1208 It would be low on my priorities list.
