### ISSUE TITLE
[Genomic Browser] Instructions unclear regarding requirements for file upload.

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#6297]
**Describe the bug**
The requirements that need to be met for the file to uploaded in the Files Tab of the Genomic Broswer are unclear. For this reason, it is difficult to successfully upload a file.

Test Plan Reference: https://github.com/aces/Loris/blob/master/modules/genomic_browser/test/TestPlan.md#data-upload

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to Files Tab of Genomic Browser
2. Click on Upload File.

Front-end Instructions:
<img width="600" alt="Screen Shot 2020-04-06 at 14 45 30" src="https://user-images.githubusercontent.com/7550451/78593839-45dd5180-7815-11ea-887d-e8c3c0e875b6.png">

Test Plan Instructions:
<img width="975" alt="Screen Shot 2020-04-06 at 14 46 39" src="https://user-images.githubusercontent.com/7550451/78593937-6e654b80-7815-11ea-886e-040b04b6ee86.png">

**Comment by ridz1208** [comment]
@christinerogers will you be able to address this ?

**Comment by christinerogers** [comment]
@ridz1208 this is addressed in #6391 - just needs the requested reviewers to look at it.  They've been sent a reminder today.
