### ISSUE TITLE
[Genomic Browser] No Raisinbread Data for GWAS, CNV and Methylation Tabs

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#6298]
**Describe the bug**
There is no raisinbread Data for the GWAS, CNV and Methylation Tabs of the Genomic Browser module, which makes it in impossible to test the module's filters according to the Test Plan.

Test Plan Reference: https://github.com/aces/Loris/blob/master/modules/genomic_browser/test/TestPlan.md#data-filtering

**Comment by ridz1208** [comment]
@xlecours I could use your help with this one. Not sure how to populate that data

**Comment by christinerogers** [comment]
This issue is a re-report of #5180 which is still open.

**Comment by HenriRabalais** [comment]
@christinerogers Oops! Should I close this one then?

**Comment by HenriRabalais** [comment]
closing because duplicate
