### ISSUE TITLE
""

### ISSUE THREAD

**Issue by ShubhamDhingra96** [aces/Loris#6299]
**Describe the bug**
A clear and concise description of what the bug is

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):

**What did you expect to happen?**

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by johnsaigle** [comment]
I'm closing this because the ticket hasn't been filled out
