### ISSUE TITLE
[MRI violations] MRI Protocol Checks Violations filter not completely filled out

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#6300]
**Describe the bug**
I access the MRI violations module and search for violations of type "Protocol Violations". In the search result table, I click on the "Protocol Violations" link (`Problem` column) and this takes me to the MRI Protocol Check Violations page. The filter is not completely filled out but it should be according to the test plan: only fields `Patient Name` and `Series UID` are set.

**Comment by ridz1208** [comment]
linked PR merged
