### ISSUE TITLE
[Genomic Browser] Instructions in Test Plan do not match Module.

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#6301]
**Describe the bug**
In the SNP tab of the Genomic browser, the columns of the datatable do not match the columns in Testing Plan for both "Summary Fields" and "All Fields".

Test Plan Reference: https://github.com/aces/Loris/blob/master/modules/genomic_browser/test/TestPlan.md#snp-tab

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to Test Plan for the Genomic Browser under section Filtering->SNP Tab
2. Go to SNP Tab of Genomic Browser
3. Compare columns listed in Test Plan and columns in the module.

**Comment by johnsaigle** [comment]
Related to #4753

**Comment by ridz1208** [comment]
@christinerogers will you be able to address this ?

**Comment by christinerogers** [comment]
@ridz1208 this is addressed in #6391 - just needs the requested reviewers to look at it. They've been sent a reminder today.
