### ISSUE TITLE
[Document Repository] Non Global Filtering

### ISSUE THREAD

**Issue by pierre-p-s** [aces/Loris#6306]
Test Plan: 10 

From the test plan, I understand that for example when I search for pdf files, I should only get categories that contain one or more pdf files. However it is not the case. The non global filter only filters the files that are on the working directory.

**Comment by kongtiaowang** [comment]
<img width="523" alt="屏幕快照 2020-04-07 14 18 47" src="https://user-images.githubusercontent.com/9876007/78704983-c31eca00-78da-11ea-878a-c157f0f1c72f.png">
The flobal filter is below the browser tab.

**Comment by pierre-p-s** [comment]
> <img alt="屏幕快照 2020-04-07 14 18 47" width="523" src="https://user-images.githubusercontent.com/9876007/78704983-c31eca00-78da-11ea-878a-c157f0f1c72f.png">
> 
> The global filter is below the Browse tab.

Yes that is what I used but I was still not getting the results expected from the test plan.

**Comment by kongtiaowang** [comment]
I know your point, don't use filter under root folder, there is no file under Root folder. Please try to choose one category (for example: PDF) then use the filter again. It will works for you.

**Comment by pierre-p-s** [comment]
> I know your point, don't use filter under root folder, there is no file under Root folder. Please try to choose one category (for example: PDF) then use the filter again. It will works for you.

My issue is that in the test plan, for test number 10, it says: "Check that when performing a search without global filtering, the categories containing the resulting files (and only those) are shown in a list format.". From this I understood that for example if there is a pdf file call test.pdf in the category: 'Test Category', when searching for 'test.pdf', only the category 'Test Category should appear'. Im guessing this is an error in the test plan but I was unsure that is why I reported this issue.

**Comment by ridz1208** [comment]
@johnsaigle can you investigate that and determine if the testplan needs fixing or there is an issue in the code ?

**Comment by kongtiaowang** [comment]
@ridz1208 @johnsaigle It is not the error of test plan. I have fixed it.

**Comment by kongtiaowang** [comment]
compare it with https://demo.loris.ca/document_repository/

**Comment by kongtiaowang** [comment]
@pierre-p-s @johnsaigle It is my mistake, this is a test plan error.

**Comment by cmadjar** [comment]
@kongtiaowang @driusan From what I understand this issue is resolved. Could you confirm and close the issue if that is the case. Otherwise comment on what still needs to be done. Thanks!
