### ISSUE TITLE
[Publications] File upload

### ISSUE THREAD

**Issue by pierre-p-s** [aces/Loris#6308]
Test Plan : 11

File upload goes through but when I try to download the file afterwards, it is not there, there is only an arrow to delete the file

**Comment by ridz1208** [comment]
@pierre-p-s  can you append a screenshot please

**Comment by ridz1208** [comment]
<img width="1676" alt="Screen Shot 2020-04-06 at 9 57 22 PM" src="https://user-images.githubusercontent.com/15268287/78621891-ab4f3380-7851-11ea-8f93-92a06b1f8ce7.png">

**Comment by johnsaigle** [comment]
@ridz1208 what are you trying to show with that screenshot?

**Comment by pierre-p-s** [comment]
> @ridz1208 what are you trying to show with that screenshot?

I had this issue while testing. Do you see the arrow on the right to "Other"? It should be the file uploaded by Rida however the file does not appear and if you click on the arrow, you can delete it but never download it.

**Comment by sruthymathew123** [comment]
PR merged; so closing
