### ISSUE TITLE
[Media] File Upload Issue

### ISSUE THREAD

**Issue by ShubhamDhingra96** [aces/Loris#6309]
**Describe the bug**
On the media page, When I am uploading the file by filling out the required credentials It is showing me a pop-up of File uploaded succesfully but when I am browsing that the particular file through my details it is not showing me any file in the records.

**To Reproduce**
![image](https://user-images.githubusercontent.com/54913662/78595586-3ca1b400-7818-11ea-9c4c-dd55dba65516.png)

![image](https://user-images.githubusercontent.com/54913662/78595633-5c38dc80-7818-11ea-8b24-e831bbe6548f.png)

![image](https://user-images.githubusercontent.com/54913662/78595670-72469d00-7818-11ea-9920-ea740a73e18f.png)

1. Go to Clinical Tab.'
2. Click on 'Media and upload your file first'
3. And then browse that file file through your details which you have used while uploading
4. You will not see your particular file

**What did you expect to happen?**
Uploaded file should be added in the displayed data

**Browser Environment (please complete the following information):**

OS: Ubuntu
Browser: Chrome

**Server Environment (if known):**
Note: We only support the most recent release of LORIS.
LORIS Version: [e.g. 23.0.0]

**Comment by johnsaigle** [comment]
@ridz1208 @kongtiaowang Are file uploads and downloads configured on the VM? See also #6308 and #6304

**Comment by ridz1208** [comment]
@ShubhamDhingra96 are you using your own VM ?

did you try refreshing the page ? I dont believe media auto refreshes after upload

**Comment by ShubhamDhingra96** [comment]
Heyy

Yes I tried using my own VM, The issue is basically when I upload the file it upload it successfully and when I go to browse tab in order to view the file which I uploaded,  It doesn't show me the uploaded file in the displayed data When I try to find through selection filter using my details which I used during the upload of file as shown in the screenshot.

**Comment by ridz1208** [comment]
Dis you try refreshing the module after the upload ?

**Comment by ShubhamDhingra96** [comment]
Yeahh It works when I refresh the page,

 I think it should not work like that without refreshing also the details has to be shown in the displayed data

**Comment by ridz1208** [comment]
multiple duplications

https://github.com/aces/Loris/issues/6270
#5055

**Comment by cmadjar** [comment]
Closing the issue as this is a duplicated issue. #6270 and #5055
