### ISSUE TITLE
[Imaging_uploader] Uploading file bigger than 1024MB doesn't throw error swal

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#6314]
**Describe the bug**
Test plan item 7: 'A file that exceeds the max upload size' fails for both 'Phantom Scans' Yes and No, giving different errors

Phantom Scans No:
<img width="1194" alt="Screenshot 2020-04-06 15 49 52" src="https://user-images.githubusercontent.com/17415878/78599870-e20c5600-781f-11ea-8121-90379b149204.png">

Phantom Scans Yes:
<img width="1193" alt="Screenshot 2020-04-06 15 51 52" src="https://user-images.githubusercontent.com/17415878/78599892-eb95be00-781f-11ea-9f5e-b3950b695a5b.png">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'Imaging Uploader' module
2. Click on 'Upload' tab
3. Fill in the form: 'Phantom Scans': Yes/No
4. Upload a file into 'File to Upload' field that is larger than 1024MB
5. Click 'Submit' 
6. See console log errors as in the screenshot above. No swal pops up where it should.

**What did you expect to happen?**
A swal with 'Please make sure files are not larger than 1024M' warning should pop up and progress bar should not start

**Comment by johnsaigle** [comment]
I wasn't able to reproduce this.

Steps on my VM:
1. `git fetch aces`, `git checkout aces/23.0-release`, `make dev`
2. Created a file `MTL007_300007_V1.tar.gz` that is 100 MB.
3. My VM server upload limit is set to 2M(B).
4. Using both Phantom scans yes and no, the swal appeared saying the file was too big.

Where is the value `1024MB` coming from? That's a GB which is pretty large for a front-end uploader anyway. I didn't see this value in `modules/imaging_uploader/test/TestPlan.md`.

#### My gzipped tar file

<img width="374" alt="Screen Shot 2020-04-08 at 12 21 41" src="https://user-images.githubusercontent.com/4022790/78809131-71d31100-7994-11ea-878a-bb59499fc7fa.png">

#### Phantom scans yes

<img width="875" alt="Screen Shot 2020-04-08 at 12 22 14" src="https://user-images.githubusercontent.com/4022790/78809153-77305b80-7994-11ea-8275-c6354ff3bfe2.png">


#### Phantom scans no

<img width="874" alt="Screen Shot 2020-04-08 at 12 23 28" src="https://user-images.githubusercontent.com/4022790/78809167-7bf50f80-7994-11ea-9cb5-4791598c2cc8.png">


#### Chrome network tab, 400 response

<img width="1072" alt="Screen Shot 2020-04-08 at 12 27 41" src="https://user-images.githubusercontent.com/4022790/78809183-80212d00-7994-11ea-912c-623463c7f562.png">

**Comment by johnsaigle** [comment]
I couldn't duplicate the error. When I change my limit to 1024 M, or higher, the SWAL blocks me when my file is over the limit or allows it as long as it's under the limit, even for large files.

Which VM did you test on? What was the size of the file you uploaded?

<img width="870" alt="Screen Shot 2020-04-08 at 12 57 58" src="https://user-images.githubusercontent.com/4022790/78811957-a5b03580-7998-11ea-9afe-134cde0b8b3f.png">

**Comment by ridz1208** [comment]
@zaliqarosli could you take a couple minutes and give more details to john please ?

**Comment by zaliqarosli** [comment]
hi @johnsaigle, could you simplify how I can help at this stage? I've read your last few comments and I am a bit confused. You had mentioned that 1GB (the limit on the test VM, where I tested and got the error described in this issue) was too big of a file to upload onthe front-end anyways, but then you actually demonstrated a successful upload of a 1GB file. 

could you try reproduce this error on the testing VM as described in this issue's description? I had uploaded a file with size larger than 1GB, and format .tar.gz i believe. files below 1GB I was able to upload successfully, but that's not the issue here

**Comment by zaliqarosli** [comment]
this issue is a VM configuration issue - due to `post_max_size` and `upload_max_filesize` being the same value (1024M). the 413 error needs to be resolved by having upload_max_filesize < post_max_size. @kongtiaowang could you either make `upload_max_filesize` < 1024M or post_max_size > 1024M in `/etc/php/7.3/apache2/php.ini`?

**Comment by driusan** [comment]
I don't understand.. why would it be a problem that they're the same value?

**Comment by zaliqarosli** [comment]
@driusan hmm rightt.. i tried putting it the same values on my dev VM and it didn't trigger the 413. i'm not sure, it was the answer i found when i looked the error up. it's definitely an issue with some configuration with the test VM though but now i'm not sure what. either way, the 413 case is considered in my PR linked above

**Comment by lingma** [comment]
`post_max_size` should be > `upload_max_filesize`, the PHP configuration is not correct. But 413 should already have been triggered with a file of 1G, so no difference whether  `post_max_size` vs `upload_max_filesize`

**Comment by johnsaigle** [comment]
Yeah I'm still not sure how to replicate it. In short, the module seems to be operating as per usual (at least on my VM). I'm not sure what about the test VM would cause it to give a 413. It could be any one of a number of `php.ini` settings.
