### ISSUE TITLE
[user_accounts] Remove line 5 from User Accounts Test plan

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6316]
**Describe the bug**
> Verify that if the editor does not have permission 'Across all sites add and edit users' then the site drop-down list is populated with the editor's associated sites, otherwise all sites are displayed.

This line is out of date and doesn't reflect the functionality of the module. it should be deleted from the test plan.

**TODO**

Edit the file `modules/user_accounts/test/TestPlan.md` and remove step 5. 
Update the line numbers of the remaining steps accordingly.

**Additional context**
See discussion in #6294.

**Comment by cmadjar** [comment]
Duplicate issue with #6294

**Comment by johnsaigle** [comment]
@cmadjar I'm re-opening this one and closing the other one because this is more accurate.

**Comment by ridz1208** [comment]
PR merged
