### ISSUE TITLE
[LORIS Install] Several Issues while trying to install LORIS

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#6317]
**Describe the bug**
I followed these instructions to install LORIS and ran into the following issues (https://github.com/aces/Loris/wiki/Installing-Loris-in-Brief#installing-the-database---1-of-2):

1. Testing says to `cd var/www/` but that directory hasn't been created yet in the instructions. https://github.com/aces/Loris/wiki/Installing-Loris-in-Brief#downloading-loris
2. Running the command `make` did not work, I had to use `make dev`. It also doesn't mention from which directory it needs to be run.
https://github.com/aces/Loris/wiki/Installing-Loris-in-Brief#running-the-install-script
<img width="488" alt="Screen Shot 2020-04-06 at 16 11 47" src="https://user-images.githubusercontent.com/7550451/78602369-5943e900-7824-11ea-9f7a-cd8e3c3e6b91.png">
3. Attempting to install database but getting message that LORIS already appears to be installed and that project/config.xml already exists. However, it does not exist. Cannot proceed with Install.
https://github.com/aces/Loris/wiki/Installing-Loris-in-Brief#installing-the-database---1-of-2
<img width="1044" alt="Screen Shot 2020-04-06 at 16 25 03" src="https://user-images.githubusercontent.com/7550451/78602379-5d700680-7824-11ea-9b92-d1c672204bee.png">

**Comment by ridz1208** [comment]
I think the most recent install instructions for ubuntu are the ones on the branch it self

here is a link. https://github.com/aces/Loris/tree/master/docs/wiki/00%20-%20SERVER%20INSTALL%20AND%20CONFIGURATION/01%20-%20LORIS%20Install/Ubuntu

can you start from a fresh VM and try them out ?

**Comment by johnsaigle** [comment]
Rida is right. The "in brief" instructions on the Wiki are out of date. I'll edit the page to indicate that it's deprecated. 

In addition to the README instructions, check out this Ubuntu install document from the new wiki that I wrote. https://acesloris.readthedocs.io/en/latest/wiki/00%20-%20SERVER%20INSTALL%20AND%20CONFIGURATION/01%20-%20LORIS%20Install/Ubuntu/

It has a lot more information and it would be great to know that it's accurate.

**Comment by johnsaigle** [comment]
I updated the Wiki page you referenced to say that it's out of date.

**Comment by ridz1208** [comment]
@johnsaigle the only problem is that that file is merged on master not in 23-release

**Comment by johnsaigle** [comment]
@johnsaigle The (old) Wiki isn't tied to the release either. Both are served online apart from the versioned code. Might as well use the newest and most accurate version.

**Comment by HenriRabalais** [comment]
Closing because the issue was made for deprecated instructions.
