### ISSUE TITLE
[User accounts] Usability: Proposal, not to force to change passwords every time a user info is edited.

### ISSUE THREAD

**Issue by racostas** [aces/Loris#6319]
**Is your feature request related to an existing module?**
User accounts

**Description of the issue**

It seems that every time a profile for a given user is updated (permission added/deleted, etc) the module user_accounts force the editing admin to change the password for a the edited user.

While I'm not sure if forcing this password change have some advantage from the security perspective, it does make the testing process a bit tedious when having to test different combinations of permissions and every time a new password should be filled before saving the configuration.

Although in real environments is most not likely to a user permission been changing to often I'm not sure yet if is convenient to set up a new password when this happen (assuming is a way to alert the end user something changed in its account) or to send an email to the user notifying it the configurations that were changed and which admin user did it and when.

**Comment by johnsaigle** [comment]
There is no password change enforced when you change a user's account details.

What might happen is that your saved password gets auto-filled in the password input field. Then, when you submit, the system believes you are trying to create a new password. When it sees your input, it correctly says that your submitted password is identical to your own password.

If I'm right then I believe this is the same kind of issue as #5114.

It's an annoying result of the way the module functions. The UI of edit_user is very clunky and needs a rework.

**Comment by johnsaigle** [comment]
This should be resolved by the linked PR (if I understood the issue correctly).

**Comment by racostas** [comment]
solved by #6330

**Comment by johnsaigle** [comment]
I'm going to reopen this for now but we can close it when the PR gets merged.
