### ISSUE TITLE
[api] Discrepancies from API doc spec

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#6321]
**Describe the bug**
The following unexpected results were returned on the testing VM:

1. `GET /projects/$ProjectName/images/` returns "File" key (not in spec)
2. `GET /candidates/$CandID/$VisitLabel` returns value {} for 'Project' key
3. `https://test-loris-dev.loris.ca/api/v0.0.3/projects/Pumpernickel/instruments/radiology_review` returns null
4. `GET /candidates/$CandID/$VisitLabel/images/$Filename/format/raw` returns `{"error":"minctoraw not installed"}`
5. `GET /candidates/$CandID/$VisitLabel/images/$Filename/headers` does not return 'TimeDimension' key
6. `GET /candidates/$CandID/$VisitLabel/recordings/$Filename` returns 500
7. All GETs under '6.7 Download BIDS Files Associated To The Recording' section returns 500 or 404
8. I tried to POST but no calls worked? Unsure if I was doing this right.

**Comment by ridz1208** [comment]
@xlecours will you be able to address this ?

**Comment by xlecours** [comment]
1. Should be addressed by https://github.com/aces/Loris/pull/6401

2. Should be addressed by https://github.com/aces/Loris/pull/6401

3. There is something wrong with JSON rendering of non-linst instruments. I need to dig.

4. The version `1.9.16` was missing in the config.xml `MINCToolsPath` entry ; FYI @kongtiaowang 

5. TimeDimension is only available for 4d images. @cmadjar could you check this please?

6. Allowed memory size of 134217728 bytes exhausted (tried to allocate 79360000 bytes) @kongtiaowang  please raise the php.ini value. 

7. same as 6.

8. Not sure I understand. Can you (@zaliqarosli ) add the command you used?

**Comment by cmadjar** [comment]
@xlecours indeed, TimeDimension is the fourth dimension in an image, hence only available for 4d datasets. Does that answer your question?

**Comment by zaliqarosli** [comment]
@xlecours i can't find the command that I had tried to run. Could you provide me the command that I should be using and I can test again?

**Comment by xlecours** [comment]
Hi, @kongtiaowang would you be able to increase the `memory_limit` in php.ini ?

**Comment by zaliqarosli** [comment]
POST isn't working for me when I test on my dev VM on 23.0-release

<img width="950" alt="Screenshot 2020-04-27 10 11 42" src="https://user-images.githubusercontent.com/17415878/80381922-a4737980-886f-11ea-93e1-79d2f96ecf94.png">
