### ISSUE TITLE
[api] Module needs TestPlan.md

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#6322]

**Comment by driusan** [comment]
I don't know if we need to spend time writing a test plan for this.. the spec is basically the test plan. It tells you each route and what the expected return value is.

**Comment by zaliqarosli** [comment]
@driusan ^ if that's the case, then it should be stated instead of implied. i was assigned the module and it wasn't clear to me how i should be testing it until i asked someone. and even then, i wasn't sure if i was testing the calls correctly when looking at the API spec. for example, none of my POST calls were successful. and it's difficult to know whether that was because of me or because of a bug, given i have no experience with the module. i could imagine this being the case with other people who may be assigned the module in the future.

i don't think we should expect everyone to know what to do to test this module if there aren't explicit instructions somewhere.

**Comment by ridz1208** [comment]
TODO: add a test plan simply stating something like
`The API should be tested by following the API specs and making sure every command works`

**Comment by xlecours** [comment]
@zaliqarosli I just sent https://github.com/aces/Loris/pull/6397
Please tell me if it is a good start. Thanks

**Comment by cmadjar** [comment]
@xlecours @zaliqarosli @driusan is this issue resolved by the merged PR? If so, could you please close the issue? Otherwise could you give a summary of what still needs to be done. Thank you!
