### ISSUE TITLE
Move ReadTheDocs root to be the same as the LORIS root

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6329]
**Describe the bug**
ReadTheDocs has issues accessing files outside of `docs/` as that is where it is served from. This causes problems if we want to, for example, serve a module README in the wiki, because that file will be under `modules/` which RTD can't access.

**To Reproduce**
e.g. #6209 

**Additional context**
There might be a problem with doing this. I remember when initializing this that there was an issue with `mkdocs.yml` being in the same folder as the RTD root. I think that's why it's in `docs/` in the first place.

If this is the case, then we may have to move documents from other places in the codebase into `docs/` when we desire them to be in the Wiki.

**Comment by christinerogers** [comment]
fyi @AlexandraLivadas -- If you can investigate this ReadTheDocs issue, that would be sweet.
