### ISSUE TITLE
[media] Update test plan to remove mention of "site" field

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#6336]
**Describe the bug**
The site selection has been removed in https://github.com/aces/Loris/pull/5577 but the test plan was never updated.

**Comment by ridz1208** [comment]
@racostas this should have been caught during testing

**Comment by racostas** [comment]
@ridz1208 yes, at the time of testing I wasn't aware the update plan should be updated as well. Noted, thanks.

**Comment by racostas** [comment]
@ridz1208, I also noted the instrument field was not mandatory during the "media creation" and at the time of edition it appears as "gray not editable" with makes that this field will not be filled if not done at the creation time. At the same time the when uploading a media it says the name of the file should have the instrument name. But if the field is leaved in blank and try to upload a media, it does work. Not reported this neither as not sure if it is a bug or is intentionally in the case there is not instrument a given media?

**Comment by ridz1208** [comment]
@racostas thats intended behaviour
