### ISSUE TITLE
[user_accounts] error_log pollution when removing pending approval

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#6353]
**Describe the bug**

I receive the following errors in error_log when the admin is removing `pending approval` from a request account. 

`Notice: Undefined index: permID in /Users/alizee/Development/GitHub/McGill/Loris/modules/user_accounts/php/edit_user.class.inc on line 216`

`Warning: array_keys() expects parameter 1 to be array, null given in /Users/alizee/Development/GitHub/McGill/Loris/modules/user_accounts/php/edit_user.class.inc on line 216`

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Request account
2. Go to user_accounts change user from pending approval and check the box Generate new password and Send email to user.
3. See error

**Comment by johnsaigle** [comment]
I'm not able to test this properly right now because request accounts is buggy. I will look into fixing this after #6233 is resolved.

**Comment by cmadjar** [comment]
@johnsaigle #6233 has been resolved. Back to you :).

**Comment by ridz1208** [comment]
@maltheism can you adress this please ?
