### ISSUE TITLE
[user_account] Permission control problem

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6355]
**Describe the bug**
I created one user with the following permission, 
![image](https://user-images.githubusercontent.com/5295785/78934537-1b8bce00-7a79-11ea-924e-45bf12549319.png)

The permission list in text is:
+--------+-----------------------------+-------------------------------------------------------+
| permid | code                        | description                                           |
+--------+-----------------------------+-------------------------------------------------------+
|      1 | superuser                   | There can be only one Highlander                      |
|      3 | user_accounts_multisite     | Across all sites create and edit users                |
|      5 | bvl_feedback                | Behavioural QC                                        |
|     10 | access_all_profiles         | Across all sites access candidate profiles            |
|     11 | data_entry                  | Data entry                                            |
|     12 | examiner_view               | Add and certify examiners                             |
|     13 | examiner_multisite          | Across all sites add and certify examiners            |
|     25 | dicom_archive_view_allsites | Across all sites view Dicom Archive module and pages  |
|     61 | battery_manager_edit        | Add, activate, and deactivate entries in Test Battery |
+--------+-----------------------------+-------------------------------------------------------+
9 rows in set

This is a random user to test, then logout from the admin user to login with the new user, you have the following interface:

![image](https://user-images.githubusercontent.com/5295785/78934738-6f96b280-7a79-11ea-9b90-695b3db55e7c.png)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Add a user as above
2. Login as the new user
3. You are practically the administrator

**What did you expect to happen?**
What is going on in permission control?

**Server Environment (if known):**
- LORIS Version: 23.0

**Comment by lingma** [comment]
Is this because of the "There can be only one Highlander"? I don't know what this phrase means, but it seems that the problem is due to the `superuser`

**Comment by ridz1208** [comment]
The admin user can create other admin users

the "There can be only one Highlander" is a quote from a movie... its not literal.

This is normal behaviour

**Comment by maltheism** [comment]
> "There can be only one" is the belief and motto among the immortals in the original Highlander film, its sequels and spin-offs. It implies that all immortals must fight and kill one another until only one remains standing; this "one" shall receive The Prize.

**Comment by lingma** [comment]
But still, the Configuration setting is not chosen, as you can see from my screenshot, the Configuration  setting page is opened without problem

**Comment by lingma** [comment]
Does admin user have all the other permission? I feel this is a little confusing. If yes, then that highlander should be distinguished out.

**Comment by ridz1208** [comment]
@lingma yes, admin has all access

**Comment by ridz1208** [comment]
@maltheism please... too easy

**Comment by maltheism** [comment]
@ridz1208 I already lost to the little dog in tug a war.

**Comment by johnsaigle** [comment]
@lingma I agree that the super user permission should come with an extra "warning" or info of some kind ideally.

**Comment by ridz1208** [comment]
TODO: rename description to `Superuser`

**Comment by johnsaigle** [comment]
@ridz1208 Maybe something like `Superuser - grants all permissions`
