### ISSUE TITLE
[module manager] Features doesn't meet the name

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6360]
**Describe the bug**
The Module manager doesn't do what a module manager should do, it is actually a menu manager as I can conclude.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Disable any modules, the module will disappear from the menu,
2. Access that module with the original link, all works fine just as before

**What did you expect to happen?**
The function observed is not module manager, but menu manager. The functions should be enforced.

**Server Environment (if known):**
- LORIS Version: 23.0

**Comment by lingma** [comment]
We can see what to do depending on the feedback on the PR #6365 or other propositions.

**Comment by johnsaigle** [comment]
@driusan Can you comment on this since you created the module?

**Comment by lingma** [comment]
The module manager itself looks OK for the general users as long as there is no link to other modules since the module does disappear from the menu, currently there is no way to stop those modules to be available even if the module is disabled. PR #6365 method could be a way but this might slow down the page rendering.

**Comment by driusan** [comment]
This ticket doesn't make any sense. The module manager manages lists modules that are installed and let's you set them to active or inactive. It doesn't do any managing of menus at all and the only connection to menus is that LORIS doesn't display inactive modules in the menu.

**Comment by johnsaigle** [comment]
That is my understanding also but I didn't have time to look at the code or try to reproduce.

**Comment by lingma** [comment]
The menu calls the module manager's method to get the active module list, and the menu might be the only item to do so. Other modules are all available no matter the module is active or not. The only difference is that they disappear from the menu since this might be the only implementation.

**Comment by johnsaigle** [comment]
> Other modules are all available no matter the module is active or not. The only difference is that they disappear from the menu

@driusan This sounds like it might be a bug

**Comment by driusan** [comment]
Off the top of my head the menus only display items from active modules, the dashboard only displays widgets from active modules, and the candidate_profile only displays widgets from active modules. Both the candidate_profile and dashboard have subwidgets which only display information from active modules.. but even if the menus were the only place currently using it, the module still does nothing to manage menus.

If other modules have bugs, then file bug reports for those modules.
