### ISSUE TITLE
[Doc Repo] Can't access the module with only the "Doc Repo delete" permission

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6373]
These lines in the module need to be updated to also grant access to a user with the delete permission.

https://github.com/aces/Loris/blob/dde77f89cf3683955f0193265ed67aa02fa40b31/modules/document_repository/php/module.class.inc#L36-L40

I tested this and just having the "Delete files in Document Repository" does not seem to grant access to the module.

_Originally posted by @pierre-p-s in https://github.com/aces/Loris/pull/6331_

**Comment by johnsaigle** [comment]
#6331 was linked to close this PR but that PR does not solve the issue.

**Comment by ridz1208** [comment]
@johnsaigle the PR linked is going to master. I will remove the 23 label from this issue accordingly
