### ISSUE TITLE
[Genomic Browser]  README has incomplete sections 

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#6389]
The README also has incomplete sections that need to be fleshed out since #5827 was merged

_Originally posted by @driusan in https://github.com/aces/Loris/issues/4753#issuecomment-571168909_

**Comment by haoweiqiu** [comment]
Hi @christinerogers, I've been trying to learn LORIS recently and I also found 2 broken links in README.md. I fixed them in my local repository. Should I help to fix the links? Thanks!

**Comment by christinerogers** [comment]
Hi @haoweiqiu - Could you email them to me, if they're not already addressed in #6296 ? thanks

**Comment by haoweiqiu** [comment]
Hi @christinerogers, the problem was found in the main branch, however, I just noticed that it has been fixed for Release 23.0 in #6296. Sorry for the confusion.
