### ISSUE TITLE
[Docs] Remove spaces from markdown filenames (and section headers?)

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#6415]
For both internal Github linking to work, and ReadTheDocs to work - replace spaces with underscores.  

Currently any spaces in a Markdown filename will make for a broken link when reading a Markdown file in GitHub.   See John's description of the issue below.

To do - For all markdown files in the codebase: 
- [x] in the Filename: replace any spaces with underscores (and delete the old file)
- [x] in the content of the file: update links to documents with underscores (replacing spaces) 
This second check must be performed on the content of all markdown files even if the filename is fine e.g. `Contributing.md` may contain old markdown links with spaces. 

- [ ] To verify: does this apply to subsection of documents, e.g. headers within a Markdown document we want users to be able to link/jump to specifically? 

_Originally posted by @johnsaigle in https://github.com/aces/Loris/pull/6390#issuecomment-616246536_

@christinerogers Yeah internal GitHub linking seems to conflict with ReadTheDocs linking. One needs spaces and the other needs URL-encoded spaces (`%20`) to work. We should probably just remove the spaces from the file names at some point. It will be a fairly quick clean up when we get around to it.

**Comment by johnsaigle** [comment]
AFAIK this doesn't apply to headers but we can test it out.

**Comment by laemtl** [comment]
@christinerogers @johnsaigle Is si something we want for v23.0?

**Comment by christinerogers** [comment]
it should be resolved for `23`  by #6510 already - please feel free to double-check

**Comment by laemtl** [comment]
#6510 specifies it was fixed for docs/wiki only. 
Do we need to fix only those markdown files?

**Comment by christinerogers** [comment]
Good point. What else is going to be rendered by RTD?

**Comment by laemtl** [comment]
The only missing section is API. I take care of it.

**Comment by christinerogers** [comment]
> The only missing section is API. I take care of it.

thank you!  for the API docs -- Could you please make a separate PR (and issue) to update these, and tag / request review Simon @spell00 and Xavier so that they are aware. merci.

**Comment by laemtl** [comment]
@christinerogers No changes required for the API section. Everything is good!

**Comment by christinerogers** [comment]
great.  the last point to be verified in this issue is whether section headers need / should be updated. to be continued...
