### ISSUE TITLE
[instruments] administration panel not working with Firefox

### ISSUE THREAD

**Issue by PapillonMcGill** [aces/Loris#6417]
**Describe the bug**
Can't change administration of data entry status for an instruments with Firefox (not tested with others)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to an instrument for a visit/candidate
2. Click on any administration or data entry item in the left pane. 
3. Clicking on 'delete instrument data' is not working 
4. screen look like not properly set (checkbox at the right place?)

**What did you expect to happen?**
change to the administration or data entry status.

**Browser Environment (please complete the following information):**
- OS: Debian 10  Fully patched
- Browser: Firefox 68.6.0esr
- Version 68.6.0esr

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: 23.0-release  test-loris
- Linux distribution and Version: 
- MySQL/MariaDB Version:

**Additional context**
Add any other context about the problem here

![image](https://user-images.githubusercontent.com/34311645/79775040-a4202f00-8301-11ea-98c9-6bb988c61003.png)

**Comment by ridz1208** [comment]
@PapillonMcGill I'm not sure about step 2

> Click on any administration or data entry item in the left pane.

It seems like the broken functionality is the instrument deletion, not sure why step 2 is necessary to reproduce. this is making the issue slightly confusing. does the instrument not get cleared if no administration is set either ?

**Comment by PapillonMcGill** [comment]
I can save the data but I can't change any admin setting. Not sure what is the desired behavior of this pane.

**Comment by ridz1208** [comment]
@PapillonMcGill each section of this pane has a different purpose.

- The delete instrument data is one function to clear an instrument
- the administration and completeness sections are interdependent as explained on the PR
- valididty is also it's own section and can be checked unchecked depending on a flag set in the instrument file itself

this particular issue touches on 2 different functionalities. It's not clear to me which one is currently not working. the clearing instrument data ? or setting the administration to none/partial/all ?

**Comment by johnsaigle** [comment]
Is this related to https://github.com/aces/Loris/issues/6218? The screenshots look similar

**Comment by johnsaigle** [comment]
Also see #6378

**Comment by johnsaigle** [comment]
Also see #6378

**Comment by pierre-p-s** [comment]
> I think the PR from @pierre-p-s should address the checkboxes like @johnsaigle points out.

Yes my PR changes the instrument data deletion button however the old one worked with the 2 checkboxes on chrome.

**Comment by johnsaigle** [comment]
@PapillonMcGill Maybe you could review and test @pierre-p-s's PR? That seems like an efficient way to figure out if this is a duplicate issue as well as to move the PR along.

**Comment by PapillonMcGill** [comment]
Effectively, @pierre-p-s PR #6378 cleared the problem.
