### ISSUE TITLE
[imaging_browser] Test plan does not test widgets

### ISSUE THREAD

**Issue by driusan** [aces/Loris#6436]
The imaging browser test plan does not include tests for the widgets that the module registers on the candidate dashboard.

**Comment by ridz1208** [comment]
@pierre-p-s could you take care of this one please

**Comment by pierre-p-s** [comment]
@driusan Not sure what you mean by candidate dashboard. Is it the one that appears in the new access profile module?

**Comment by maltheism** [comment]
@pierre-p-s yes that's correct. There are new widgets visible after clicking on a candidate from within the New Access Profile (Beta) page.
