### ISSUE TITLE
[mri violations] MRI Violations module does not describe or test widgets

### ISSUE THREAD

**Issue by driusan** [aces/Loris#6440]
The MRI violations module registers widgets to the candidate dashboard, but the README does not describe them and the test plan does not test them.

**Comment by maltheism** [comment]
Hey @driusan just to make sure I'm on the same page. I just see under the "My Tasks" widget, a row for Violated scans and I don't think there is anything else?

**Comment by maltheism** [comment]
note to self: for regular dashboard "my tasks"

**Comment by driusan** [comment]
Yeah, sorry, I created these tickets by doing a `git grep getWidgets` and got the wrong dashboard for this one.. but we should still be updating the test plan to test for it and README to note the interaction.

**Comment by driusan** [comment]
(We should also be creating an MRI Violations candidate dashboard widget eventually..)
