### ISSUE TITLE
[Download CSV] the Download CSV is broken throughout LORIS

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#6448]
**Describe the bug**
Noticed first in the DQT but after testing throughout LORIS, the Download CSV is broken throughout LORIS.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to genomic_browser module
2. Click Download CSV
3. Open CSV that wa sdownloaded

**Additional context**
The CSV data is missing.

**Comment by lingma** [comment]
I tried, all works fine with me on my installation
