### ISSUE TITLE
[Dashboard] Update Readme post-refactor for 23 release 

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#6467]
Module readme needs an update since it was refactored in jan 2020 #5896

Several issues linked below have been created to update the widget modules' testplans to add test cases for the their respective widgets.

After all issues are resolved and PRs merged, the dashboard readme and testplan should undergo a sanity check to make sure it is up to date with the new widget structures.

The below text could be handy -- This change was partially described by Dave's [comment quoted below](https://github.com/aces/Loris/pull/6464#discussion_r418694673) on #6464

> The dashboard test plan was written before the module used any widgets, and no longer houses the code being tested. There are many things you can do now which affect what shows up in the dashboard without the dashboard knowing anything about it.. write a new module for a project which has widgets, disable/enable an existing module in the module manager, override a (non-dashboard) module which is one of the ones that provides widgets.. it's also easier to have someone test the related functionality to a module in the dashboard when testing that module than have someone setup and test (effectively) every module in LORIS at the same time for the "dashboard" test.
> 
> The tickets came up when I made tickets for the `candidate_profile` widgets that are missing documentation since the `dashboard` and `candidate_profile` use the same `getWidgets()` function.

_Originally posted by @driusan in https://github.com/aces/Loris/pull/6464_

**Comment by johnsaigle** [comment]
I didn't know you could make issue titles this long

**Comment by christinerogers** [comment]
> I didn't know you could make issue titles this long

it was auto-generated by github lol

**Comment by ridz1208** [comment]
Below are a list of issues created for this. I can see that updating the testplan of dashboard was missed in a couple of them. We should create specific issues to make sure the testplan sections are transferred to the proper module and the dashboard testplan is updated.

https://github.com/aces/Loris/issues/6443
https://github.com/aces/Loris/issues/6441
https://github.com/aces/Loris/issues/6440
https://github.com/aces/Loris/issues/6438
https://github.com/aces/Loris/issues/6437
https://github.com/aces/Loris/issues/6436
https://github.com/aces/Loris/issues/6434

**Comment by ridz1208** [comment]
I think at this stage we should wait to get all the remaining PRs in and do a sanity check after to remove what is left over.

I added some details to the issue description

**Comment by ridz1208** [comment]
@SantiagoTG @HenriRabalais you are both assigned to the dashboard testing in this round. As part of your testing can you make sure the dashboard test_plan and readme are up to date in reference tot the widgets which were moved to their respective modules ?

**Comment by HenriRabalais** [comment]
Added two new issues relating to adding documentation for the widgets in their respective modules:
#6631 
#6630 

These issues, along with the ones listed by Rida should cover all modules that have widgets that are used in the dashboard.

For reference, here is the full list of issues still open:
#6438
#6437
#6631 
#6630
