### ISSUE TITLE
[issue_tracker] If Issue has centerID of NULL, error is thrown.

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#6470]
**Describe the bug**
When navigating to the issue tracker module with a user who does not have permission to all centers, if one of the issues has a centerID of `NULL` in the database, an error thrown since the dataprovisioner's usersitematch filter expects getCenterID to return a non-null value.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Set the centerID of one of the issues to NULL
2. Load Issue Tracker module with user who is not admin.

Error:
```
[Mon May 04 15:51:57.413901 2020] [php7:error] [pid 31367] [client 10.31.6.189:53417] PHP Fatal error:  Uncaught LorisException: getCenterID on resource returned null in /var/www/loris/src/Data/Filters/UserSiteMatch.php:62\nStack trace:\n#0 /var/www/loris/src/Data/ProvisionerInstance.php(130): LORIS\\Data\\Filters\\UserSiteMatch->filter(Object(User), Object(LORIS\\issue_tracker\\IssueRow))\n#1 [internal function]: LORIS\\Data\\ProvisionerInstance->LORIS\\Data\\{closure}(Object(LORIS\\issue_tracker\\IssueRow), 3, Object(class@anonymous))\n#2 [internal function]: CallbackFilterIterator->accept()\n#3 [internal function]: FilterIterator->rewind()\n#4 /var/www/loris/src/Data/Table.php(83): IteratorIterator->rewind()\n#5 /var/www/loris/src/Data/Table.php(98): LORIS\\Data\\Table->toArray(Object(User))\n#6 /var/www/loris/modules/issue_tracker/php/issue_tracker.class.inc(166): LORIS\\Data\\Table->toJSON(Object(User))\n#7 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(698): LORIS\\issue_tracker\\Issue_Tracker->toJSON()\n#8 /var/www/loris/php/libraries/NDB_Page.class.inc(718): NDB_Menu_Filter->display()\n#9 /var/www/loris/php/libraries/NDB_M in /var/www/loris/src/Data/Filters/UserSiteMatch.php on line 62, referer: http://hrabalais-dev.loris.ca/issue_tracker/
```

**What did you expect to happen?**
The page to load and only issues that are associated with the user's center to be displayed.

**Comment by driusan** [comment]
The problem is that the UserSiteMatch filter doesn't know if getCenterID=null means that a user should have access to the resource or a user shouldn't have access to the resource in the data framework.

We either need a consistent policy throughout LORIS for if null means "any" or "none" or we need to split it into UserSiteMatchExclusive and UserSiteMatchInclusive (or maybe just include a constructor parameter) and a way for the DataFrameworkMenu to indicate which one to use.

**Comment by HenriRabalais** [comment]
@ridz1208 any thoughts?
