### ISSUE TITLE
[Readme] Update dependency impacting ubuntu dev install - minor tweak

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#6473]
php7.3-curl specifically is required for the 23 release 
- [ ] change `curl` -> `php7.3-curl` in the main LORIS readme

**Comment by laemtl** [comment]
Christine, is it possible that both curl and php7.3-curl are needed?

**Comment by johnsaigle** [comment]
This package is only needed for development installs, not production, and it's required because of the change introduced here: https://github.com/aces/Loris/pull/6187.

Just mentioning it for the record. The linked PR looks good.

**Comment by christinerogers** [comment]
thanks John.  
Is it still recommended that production instances stick to `curl`?  
Since this breaks the install for sandboxes, I think we should mention the package for development - which means we should update related documentation not yet covered by #6187.

**Comment by christinerogers** [comment]
Updating issue title to be better: 
- this issue scope covers only the main Loris Readme on the 23 branch
- other install docs shoujld be added to the 23 branch and similarly update via # 6475

**Comment by johnsaigle** [comment]
> Is it still recommended that production instances stick to curl?

`curl` is always needed AFAIK. `php7.3-curl` is needed for development environments.

**Comment by ridz1208** [comment]
@johnsaigle so we just don't know why curl is required ?

**Comment by johnsaigle** [comment]
No I don't know the reason. On the other hand I don't know if I could tell you why we need all of the other dependencies either. We could try to set up a prod environment without `curl` and wait to see if it breaks - otherwise I'm not sure how to test this.

**Comment by ridz1208** [comment]
@johnsaigle I think I can justify some of them but curl... never knew why or if it's a new thing or always been like that. 

maybe we should run a test if it's a 23 thing. if it was there from before, we can actually see if all existing PRODs have curl

**Comment by driusan** [comment]
It's likely that all existing prods have curl even if LORIS doesn't require it because it's such a common tool.

**Comment by johnsaigle** [comment]
@ridz1208 It's been there for a very long time. I grabbed it from https://github.com/aces/Loris/wiki/Installing-Loris-in-Depth and I think that section was last edited by Justin Ng. It's possible that Guzzle uses it? But I'm not positive.

As Dave said it's a very common tool, similar to `software-properties-common` or `zip` which we also have as a requirement.

**Comment by ridz1208** [comment]
@driusan @johnsaigle alright then... both it is

**Comment by ridz1208** [comment]
changes done
