### ISSUE TITLE
[Core] NDB_BVL_Instrument class - Clean debug code

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6481]
**master branch**
 [php/libraries/NDB_BVL_Instrument.class.inc:save()](https://github.com/aces/Loris/blob/master/php/libraries/NDB_BVL_Instrument.class.inc#L600)
Check and remove the below code if it's not necessary.

```
if (!empty($error)) {
    // FIXME: Why is this here? The body of this if
    // statement does nothing.. -- Dave
    $element = $this->form->getElement($key);
    if (method_exists($element, "getLabel")) {
        // print "<font color='red'>"
        // .$element->getLabel()
        // .": $error</font><br>\n";
    }
}
```
See #5687 for more details

**Comment by lingma** [comment]
I think you can either remove the whole block or do nothing, instead of removing comments.

```
//print all the field error messages in one block
foreach
...
```

**Comment by laemtl** [comment]
Thanks for your suggestion. 
I try to tackle #5687. I was thinking to migrate the comments to issues and cleaning the comments first, and then in a second phase, fixing/cleaning some of the issues.

**Comment by lingma** [comment]
I don't think a note from Dave should be removed, he is likely the main developer of this project, so I doubt he will let you remove his notes. By the way, the code section seems obsolete to me unless someone wants to implement something, so I believe they could be removed.

**Comment by laemtl** [comment]
Thanks, I updated the issue description.

**Comment by driusan** [comment]
The code block referenced predates me but I'm more confident that we can just remove it now than I was whenever I wrote the comment.
