### ISSUE TITLE
[Utilities] Issue with getSiteList function

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#6489]
**Describe the bug**
When calling the function `getSiteList(false, true)`, I get the following error:

>[Thu May 07 11:43:26.167770 2020] [php7:warn] [pid 23155] [client 132.216.238.74:58908] PHP Warning:  PDOStatement::execute(): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND CenterID &lt;&gt; 1' at line 1 in /var/www/loris/php/libraries/Database.class.inc on line 691, referer: http://hrabalais-dev.loris.ca/issue_tracker/
[Thu May 07 11:43:26.168696 2020] [php7:notice] [pid 23155] [client 132.216.238.74:58908] Could not execute SELECT CenterID, Name FROM psc  AND CenterID <> 1. Stack trace#0 /var/www/loris/php/libraries/Database.class.inc(726): Database->execute(Object(PDOStatement), Array)\n#1 /var/www/loris/php/libraries/Utility.class.inc(143): Database->pselect('SELECT CenterID...', Array)\n#2 /var/www/loris/modules/issue_tracker/php/issuerowprovisioner.class.inc(100): Utility::getSiteList(false, false)\n#3 /var/www/loris/src/Data/Provisioners/DBRowProvisioner.php(118): LORIS\\issue_tracker\\IssueRowProvisioner->getInstance(Array)\n#4 [internal function]: class@anonymous->current()\n#5 [internal function]: FilterIterator->rewind()\n#6 /var/www/loris/src/Data/Table.php(83): IteratorIterator->rewind()\n#7 /var/www/loris/src/Data/Table.php(98): LORIS\\Data\\Table->toArray(Object(User))\n#8 /var/www/loris/modules/issue_tracker/php/issue_tracker.class.inc(166): LORIS\\Data\\Table->toJSON(Object(User))\n#9 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(698): LORIS\\issue_tracker\\Issue_Tracker->toJSON()\n#10 /var/www/loris/php/libraries/NDB_Page.class.inc(718): NDB_Menu_Filter->display()\n#11 /var/www/loris/php/libraries/NDB_Menu_Filter_Form.class.inc(112): NDB_Page->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#12 /var/www/loris/php/libraries/NDB_Page.class.inc(697): NDB_Menu_Filter_Form->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#13 /var/www/loris/php/libraries/Module.class.inc(412): NDB_Page->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\issue_tracker\\Issue_Tracker))\n#14 /var/www/loris/src/Middleware/ResponseGenerator.php(50): Module->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#15 /var/www/loris/src/Middleware/AuthMiddleware.php(63): LORIS\\Middleware\\ResponseGenerator->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\issue_tracker\\Module))\n#16 /var/www/loris/src/Router/ModuleRouter.php(75): LORIS\\Middleware\\AuthMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\issue_tracker\\Module))\n#17 /var/www/loris/src/Router/BaseRouter.php(105): LORIS\\Router\\ModuleRouter->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#18 /var/www/loris/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#19 /var/www/loris/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\Router\\BaseRouter))\n#20 /var/www/loris/htdocs/index.php(47): LORIS\\Middleware\\ContentLength->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\Router\\BaseRouter))\n#21 {main}, referer: http://hrabalais-dev.loris.ca/issue_tracker/
[Thu May 07 11:43:26.168866 2020] [php7:error] [pid 23155] [client 132.216.238.74:58908] PHP Fatal error:  Uncaught DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND CenterID <> 1' at line 1 in /var/www/loris/php/libraries/Database.class.inc:694\nStack trace:\n#0 /var/www/loris/php/libraries/Database.class.inc(726): Database->execute(Object(PDOStatement), Array)\n#1 /var/www/loris/php/libraries/Utility.class.inc(143): Database->pselect('SELECT CenterID...', Array)\n#2 /var/www/loris/modules/issue_tracker/php/issuerowprovisioner.class.inc(100): Utility::getSiteList(false, false)\n#3 /var/www/loris/src/Data/Provisioners/DBRowProvisioner.php(118): LORIS\\issue_tracker\\IssueRowProvisioner->getInstance(Array)\n#4 [internal function]: class@anonymous->current()\n#5 [internal function]: FilterIterator->rewind()\n#6 /var/www/loris/src/Data/Table.php(83): IteratorIterator->rewind()\n#7 /var/www/loris/src/Data/Table.php(98): LORIS\\Data\\Table->toArray(Object(User))\n#8 /var/www/loris/modules/issue_tracker/php/issue_tracker.class. in /var/www/loris/php/libraries/Database.class.inc on line 694, referer: http://hrabalais-dev.loris.ca/issue_tracker/

**Comment by ridz1208** [comment]
if you look at the code of that function you can see that the `WHERE` is part of one of the if statements, that should be brought out of the if statement to avoid a syntax error.

@christinerogers this is an easy one for GSOCs

**Comment by christinerogers** [comment]
thanks @ridz1208 I'll take you off and re-assign it quickly

**Comment by laemtl** [comment]
Does this error happen only when the second param is false: getSiteList(false, false)?

**Comment by ridz1208** [comment]
the error occurs when the first `if` statement is skipped and the second is entered. but for testing, all combinations should be tested

**Comment by laemtl** [comment]
Sure, I tested them all.

**Comment by driusan** [comment]
I'd say we should update the unit tests but it looks like the getSiteList unit test works by mocking pselect, so it wouldn't have caught this error even if all possibilities were tested..
