### ISSUE TITLE
[Raisinbread] Add instructions about sourcing SQL to the Raisinbread README

### ISSUE THREAD

**Issue by AlexandraLivadas** [aces/Loris#6495]
The Raisinbread installation instructions in the [README.md](https://github.com/aces/Loris/blob/23.0-release/raisinbread/README.md) (23.0-release branch) do not specify that all tables must be dropped from a database before the raisinbread files can be sourced. It should also be clarified that there are potential foreign key constraints that can be mitigated.

- [ ] Clarify that all tables should be dropped from the DB pre-installation.

- [ ] Add a warning about foreign key constraints and alternative instructions for this case.

**Comment by ridz1208** [comment]
@AlexandraLivadas the only mention of it is the note at the bottom of this section
https://github.com/aces/Loris/tree/23.0-release/raisinbread#sourcing-sql

I think it could/should be more emphasized as long as there is a clear warning that doing so will delete all the data in the current database loaded. Also, there should not be any foreign key issues when using the 999-99-99 scripts. if there are, then it's a bug and should be fixed.

**Comment by AlexandraLivadas** [comment]
@ridz1208 I was planning on making a bug fix issue for that either this afternoon or tomorrow morning. Myself and some of the other GSOC students noticed this problem when we were installing raisinbread.

**Comment by johnsaigle** [comment]
@AlexandraLivadas I would recommend using the script `tools/raisinbread_refresh.php` as it includes functionality to automatically drop all tables as well as sourcing the RB data.
