### ISSUE TITLE
[ImagingBrowser] Fix typo in the Selection Filter

### ISSUE THREAD

**Issue by spell00** [aces/Loris#6507]
There is a typo in the Filters; 'Vist' should read 'Visit'

**To Reproduce**
1. Go to Imaging/Imaging Browser.
2. See the typo in the Filters and the column names of the table below.

**Comment by lingma** [comment]
Similar as #6493, not the same module

**Comment by lingma** [comment]
The same problem exists in 21.x and 22.x.
