### ISSUE TITLE
[RaisinBread] Remove personal emails from raisinbread tables

### ISSUE THREAD

**Issue by h-karim** [aces/Loris#6515]
**Description**
It seems as one of the maintainers' email (Leigh Evans) is placed as one of the candidates' emails in the raisinbread database:

**To Reproduce**
1. From home, navigate to 'Survey Accounts' by clicking on the 'Admin' tab on the top right
2. Observe the following:
![image](https://i.imgur.com/sYf4Pec.png)
One of the emails is not identical to the rest.

**What did you expect to happen?**
All of the emails to have been the same, or alternatively aren't real emails.

**Comment by driusan** [comment]
For testing purposes all of the emails probably shouldn't be the same, but I'm not sure what value(s) would be appropriate.

**Comment by johnsaigle** [comment]
I think the values can just be updated to something like `new.user@example.com`. I agree the current emails should be removed from the DB.

**Comment by ridz1208** [comment]
if we have some sort of a "real" fake gmail address something like `demo@mcin.ca` then we can use the `+` operator to mimic different email addresses

`demo+12345@mcin.ca`

**Comment by johnsaigle** [comment]
Maybe we can ask a sysadmin what the best option is? We had #4303 to sort of discuss this already.

**Comment by driusan** [comment]
unless I'm mistaken the emails in that table are "placed that email was sent" not "places to send email while testing", so I think `@example.com` is probably suitable for RB.

**Comment by ridz1208** [comment]
@driusan my only concern would be that people testing the module would copy paste one of the emails and then we get in trouble again with IT

**Comment by driusan** [comment]
Copy and paste it where?

**Comment by ridz1208** [comment]
copy the email from an existing row in the table to create a new survey. in which case it would actually send the email.

**Comment by driusan** [comment]
I don't think that's a problem with most IT departments. The email address entered by the user is used as the "To" for an email, it's not a configuration for the "From".

**Comment by christinerogers** [comment]
@h-karim I think the discussion above gives enough guidance to go on. 
Can you take this on?  
Consider changing emails that are currently distinct to something like person01@example.com,  person02@example.com

@ridz1208 there should be a patch + schema change committed for this right?

**Comment by ridz1208** [comment]
@h-karim I don't believe any schema changes are necessary but the RB data will need to be updated
