### ISSUE TITLE
[issue_tracker] Update validation to allow NULL Site

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6518]
#6480 suggests this as a feature, which is broken

> Testing instructions (if applicable)
    Create an issue with no CenterID

In the Issue Tracker, when creating a new issue, the form can't be submitted with a NULL Site field.
Issues without a site assignment are viewable by users with restricted site permission, so we need to allow such issues to be created.

Updating the validation rules should solve the issue.

To reproduce:
 * Open the Issue Tracker
 * Click on New Issue
 * Submit the form with Site empty

Related to #6480

**Comment by laemtl** [comment]
@christinerogers would you like me to try working on this?

**Comment by christinerogers** [comment]
let's chat ...

**Comment by driusan** [comment]
The PR for this was merged
