### ISSUE TITLE
[issue_tracker] Module filter has entry [object Object]

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6519]
In the Issue Tracker v 23.0, the module filter contains an entry labeled [object Object]

To reproduce:
* Open the Issue Tracker
* Click on the Module filter

**Comment by christinerogers** [comment]
Good catch!  This bug doesn't exist on demo so it's likely that it was introduced in this release or (less likely) it's a RaisinBread issue.
  Can you easily find and link in the Issue description the line of code where the problem originates?
