### ISSUE TITLE
[Documentation] mention RB refresh script in RB readme 

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#6528]
The raisinbread refresh script and its uses should be documented in the Raisinbread readme. 
For 23 if possible.  Ideally should have been added in #5260 when the script was committed. 

Per [@johnsaigle 's comment in #6495](https://github.com/aces/Loris/issues/6495#issuecomment-626763538) -- 

> @AlexandraLivadas I would recommend using the script `tools/raisinbread_refresh.php` as it includes functionality to automatically drop all tables as well as sourcing the RB data.

Related to #6498

**Comment by johnsaigle** [comment]
I don't know if this is a huge priority for 23.0-release because anyone interesting in Raisinbread data will be working on something based off of `master`, not the release branch.

Still a good thing to document though.

**Comment by christinerogers** [comment]
Agreed that it should definitely go on master too, and is not the burningest priority. The script was added for the 23 release and is clearly useful, let's try to document it properly in the same release given it seems we have the time.   
Moreover I think anyone who installs the release and wants to kick LORIS' tires with raisinbread dataset could find this info useful. (why else release raisinbread)

**Comment by johnsaigle** [comment]
I realized just now that I already have a PR to do this but it's going to master https://github.com/aces/Loris/pull/6153/files

We can probably just go ahead with Alex's though and I'll update mine later.
