### ISSUE TITLE
[Issue Tracker] Broken tab UI on page reload

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6532]
In Issue Tracker v23, after a filter is selected, if the user reload the page, the filter has no more effect (all results are shown) and no tab is active anymore.

1. Go to Issue Tracker
2. Select a tab to filter the results (ex: Closed Issues)
3. Notice how the tab UI looks like: one tab is always active
4. Reload the page
5. No tab is active in the tab UI, and all issues are displayed.

![Screenshot from 2020-05-13 16-16-17](https://user-images.githubusercontent.com/32041423/81863303-fe936080-9538-11ea-911b-f02cdee02643.png)

**Comment by laemtl** [comment]
@HenriRabalais, do you have any suggestion?

**Comment by HenriRabalais** [comment]
It seems that the first issue occurs only applying filters by clicking on the tabs that load preset filters. These filters are applied to the data, but are not updating the URL query params, so when the page is reloaded, there's no way access the previous filters.

My first impression is that this can likely be resolved by introducing some functionality to the `Filter` component which migrates most of the functionality from the onFieldUpdate function to the `componentDidUpdate` library function which would be triggered every time the `filter` props is changed.

For the second issue, it appears the URL is tracking the active tab, but for some reason it isn't activating it on refresh. I would have to do some digging and debugging to figure out exactly why that is.

**Comment by laemtl** [comment]
@HenriRabalais  Is it something that should be documented as a know issue after reactification?

**Comment by HenriRabalais** [comment]
@laemtl Sure! I can send a PR to try and fix this tomorrow.

**Comment by christinerogers** [comment]
whoa -- nice idea.  It does look great.  I think we'd rather keep a tabbed design for consistency with the rest of the LORIS modules, no?  (this kind of menu appears so far only for DQT load queries i think) Or perhaps a change in the direction of the new Candidate module's tab/card GUI model might work.

**Comment by HenriRabalais** [comment]
#6541 partly addresses this issue - although it now includes other changes that still need to be discussed.
