### ISSUE TITLE
[Codebase] html lint errors

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6540]
After noticing a few html glitches in the source code, I parsed the code base with an html linter ([htmllint-cli](https://github.com/htmllint/htmllint-cli)).

**I suggest to solve all the issues in the category tag is not closed:**

- modules/configuration/templates/form_project.tpl: line 106, col 17, tag is not closed 
- modules/dicom_archive/templates/form_viewDetails.tpl: line 14, col 5, tag is not closed
- modules/dicom_archive/templates/form_viewDetails.tpl: line 18, col 5, tag is not closed
- modules/dicom_archive/templates/form_viewDetails.tpl: line 84, col 16, tag is not closed
- modules/genomic_browser/templates/form_view_genomic_file.tpl: line 39, col 25, tag is not closed
- modules/genomic_browser/templates/form_view_genomic_file.tpl: line 48, col 26, tag is not closed
- modules/help_editor/templates/form_edit_help_content.tpl: line 1, col 1, tag is not closed
- modules/configuration/templates/form_project.tpl: line 15, col 1, tag is not closed
- modules/instrument_list/templates/menu_instrument_list.tpl: line 198, col 6, tag is not closed
- modules/login/templates/form_requestaccount.tpl: line 24, col 5, tag is not closed
- modules/mri_violations/templates/menu_resolved_violations.tpl: line 5, col 9, tag is not closed
- modules/mri_violations/templates/menu_resolved_violations.tpl: line 74, col 1, tag is not closed
- modules/statistics/templates/form_stats_behavioural.tpl: line 84, col 9, tag is not closed
- modules/statistics/templates/menu_statistics_mri_site.tpl: line 31, col 21, tag is not closed
- modules/survey_accounts/templates/form_addSurvey.tpl: line 66, col 5, tag is not closed
- smarty/templates/directentry.tpl: line 84, col 9, tag is not closed
- smarty/templates/instrument_default.tpl: line 11, col 5, tag is not closed
- smarty/templates/instrument_default.tpl: line 46, col 21, tag is not closed
- modules/user_accounts/templates/form_edit_user.tpl: line 63, col 9, tag is not closed
- modules/user_accounts/templates/form_edit_user.tpl: line 92, col 6, tag is not closed
- modules/user_accounts/templates/form_edit_user.tpl: line 125, col 5, tag is not closed
- modules/user_accounts/templates/form_edit_user.tpl: line 142, col 5, tag is not closed
- modules/user_accounts/templates/form_edit_user.tpl: line 259, col 5, tag is not closed
- modules/user_accounts/templates/form_edit_user.tpl: line 277, col 5, tag is not closed
- modules/user_accounts/templates/form_edit_user.tpl: line 295, col 5, tag is not closed
- modules/user_accounts/templates/form_edit_user.tpl: line 312, col 9, tag is not closed
- modules/user_accounts/templates/form_edit_user.tpl: line 330, col 5, tag is not closed
- modules/user_accounts/templates/form_edit_user.tpl: line 349, col 5, tag is not closed
- modules/user_accounts/templates/form_edit_user.tpl: line 385, col 3, tag is not closed
- modules/user_accounts/templates/form_edit_user.tpl: line 397, col 3, tag is not closed
- smarty/templates/install.tpl: line 39, col 17, tag is not closed
- smarty/templates/install.tpl: line 42, col 17, tag is not closed
- smarty/templates/install.tpl: line 45, col 17, tag is not closed
- smarty/templates/install.tpl: line 65, col 17, tag is not closed
- smarty/templates/install.tpl: line 68, col 17, tag is not closed
- smarty/templates/install.tpl: line 110, col 9, tag is not closed
- smarty/templates/instrument_html.tpl: line 182, col 1, tag is not closed
- smarty/templates/instrument_html.tpl: line 214, col 9, tag is not closed
- smarty/templates/instrument_html.tpl: line 249, col 10, tag is not closed
- smarty/templates/instrument_html.tpl: line 280, col 8, tag is not closed
- smarty/templates/instrument_html.tpl: line 325, col 10, tag is not closed
- smarty/templates/instrument_html.tpl: line 360, col 11, tag is not closed
- smarty/templates/main.tpl: line 115, col 30, tag is not closed
- smarty/templates/main.tpl: line 265, col 13, tag is not closed
- vendor/smarty/smarty/libs/debug.tpl: line 128, col 13, tag is not closed
- vendor/smarty/smarty/demo/templates/header.tpl: line 1, col 1, tag is not closed
- vendor/smarty/smarty/demo/templates/header.tpl: line 5, col 1, tag is not closed
- vendor/smarty/smarty/demo/templates/index.tpl: line 50, col 5, tag is not closed

**All duplicate id issues:**

- modules/configuration/templates/form_project.tpl: line 79, col 68, the id "form{$ProjectID}" is already in use
- modules/login/templates/form_requestaccount.tpl: line 36, col 22, the id "helpBlock" is already in use
- modules/login/templates/form_requestaccount.tpl: line 44, col 22, the id "helpBlock" is already in use
- modules/login/templates/form_requestaccount.tpl: line 52, col 22, the id "helpBlock" is already in use
- modules/login/templates/form_requestaccount.tpl: line 60, col 22, the id "helpBlock" is already in use
- modules/login/templates/form_requestaccount.tpl: line 79, col 26, the id "helpBlock" is already in use
- modules/mri_violations/templates/menu_mri_violations.tpl: line 97, col 103, the id "mri_violations" is already in use
- smarty/templates/directentry.tpl: line 125, col 24, the id "goback" is already in use
- smarty/templates/directentry.tpl: line 133, col 40, the id "key" is already in use
- smarty/templates/directentry.tpl: line 138, col 40, the id "key" is already in use
- modules/statistics/templates/table_statistics.tpl: line 33, col 31, the id "showVL" is already in use
- modules/statistics/templates/table_statistics.tpl: line 41, col 31, the id "showVL" is already in use
- modules/statistics/templates/table_statistics.tpl: line 171, col 14, the id "visitrow" is already in use
- smarty/templates/main.tpl: line 267, col 21, the id "footer" is already in use

If that seems a good idea to someone I can take care of it.

**Comment by johnsaigle** [comment]
I love linters ❤️ We should consider adding this to our automated test suite at some point.

**Comment by driusan** [comment]
Some of those are in the vendor directory and it doesn't say what tags they are. Did you verify that they're tags that are supposed to be closed in HTML5 and that it's not somehow getting confused by smarty directives embedded in the HTML?

**Comment by driusan** [comment]
I just looked at the first 3 and all 3 of them are tags which are closed properly

**Comment by laemtl** [comment]
@driusan I briefly test a few, and noticed missing / (<p><p> pairs)

**Comment by driusan** [comment]
`<p>` tags are self-closing tags in HTML.

**Comment by laemtl** [comment]
I see your point. There are some false positives because of smarty tags. I can check if I can find a workaround. Some problems are present though. For example, the first file has an unclosed div.
