### ISSUE TITLE
[docs] Migrate 23 branch edits to master

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#6547]
Last release, we made some changes on 22 that should also have been applied to `master`
Adding an issue here to explicitly cover this step for the 23 release. 
* [example edit to Contributing.md here](https://github.com/aces/Loris/issues/6537#issue-618394933)

For discussion -- 
Going forward, it would be good to check master _before_ the next release branch is created, so that we don't have to do this at every release -- i.e. a pre-check for each release : 
* Are there any obvious changes to the codebase that should be updated on `master`? 
e.g. broken links, dependency versions mentioned in the Readme, Contributing.md updates 

cc @ridz1208

**Comment by johnsaigle** [comment]
> Last release, we made some changes on 22 that should also have been applied to master

(from linked issue)
>Contributing.md contains a broken link on the 23 branch.
this was fixed on 22 in #5549 but not on master at the time it seems.
This should be fixed on master as well [if that pr exists already, find and link here]

It looks like there were two different broken links in Contributing based on the discussion you linked to. I don't think there was a `master`/release branch sync issue.

**Comment by christinerogers** [comment]
the intention is to avoid what happened with 22.  this is just a ticket to double-check after 23 is released. 

> Adding an issue here to explicitly cover this step for the 23 release.

**Comment by johnsaigle** [comment]
> the intention is to avoid what happened with 22.

Based on what you linked I don't think anything happened in 22. There were two different instances of broken links in 22. There doesn't seem to have been any branch sync issue.

**Comment by christinerogers** [comment]
closing this, and will try to keep an eye on this for 25
