### ISSUE TITLE
[meta/docs] Clarify Support in Issues template and Readme

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#6548]
We've gotten an install support request in the GitHub Issues, so it would be good to clarify our process in a few easy places. 
Both the main Loris Readme and the Issues template in our GitHub 
could be more explicit in directing users experiencing difficulties with the install :
* (update in both) for any questions, please contact loris-dev mailing list - don't file a github issue. 
* (readme only) - mention new Install guide and Troubleshooting markdowns in the codebase - on the 23 branch. 

This might be split into 2 tickets depending on where the Issues template should be committed.

**Comment by johnsaigle** [comment]
> (update in both) for any questions, please contact loris-dev mailing list - don't file a github issue.

I think a GitHub Issue is the preferable avenue. Issues are always automatically archived publicly. When working with other open source software I'll often search their old issues before creating a new one because very often the question has been asked and answered already. We lose this if people are directed to the mailing list first. 

At the same time, if a bug is reported in the mailing list we'll need to create an issue for it anyway. We may as well avoid the "middleman" when possible since all roads lead to GitHub.

**Comment by christinerogers** [comment]
@johnsaigle , do you want to raise your proposal here for re-discussion at the next meeting ? 
Agreed, current downfalls still include search, and lack of linkage between the channels (in search as you mention). 
And the reasons why we support Instances and particularly Installs through the mailing list still include: the value of a community mailing list, github clutter, our issue response time, and instance-specific install details. Slack me to chat further on the side if you like.

To re-recap 3 years of data, most mailing-list bug reports are actually install mis-steps or addressed in the documentation. The last time a true bug report came in via the mailing list, it helped to have us clarify the actual cause/effect for the GitHub Issue, and was resolved in a fraction of the time for a typical bug in our GitHub.

**Comment by johnsaigle** [comment]
Summarizing the meeting from memory:

Essentially, having a mailing list be a primary avenue of support allows for greater community management.

* We can reach and be reached by people without GitHub accounts 
* Mailing list contents can be analyzed for common troubleshooting issues
* Generally good response time

On the other hand, GitHub Issues has the following advantages:

* Integrates code, releases, documentation, ticketing, and support in one place
* Is publicly searchable: users can Google error codes and be led here
* Allows for cross-linking of PRs and Issues
* Mailing list discussions identifying bugs will eventually make their way here anyway.

As of now no decision has been reached one way or the other as to how to direct users -- meaning that the status quo will continue for the time being.

It would be valuable to dig a little bit into the GitHub API or other tools to determine if it's possible to analyze the content of GitHub Issues like we do with the mailing list for the purpose of identifying our most common support requests.

I imagine this will likely be revisited after the release at some point so I'm adding Discussion Required for now.

**Comment by christinerogers** [comment]
@johnsaigleLove the idea of a script to analyze bug reports -- an example of one that goes several days unnoticed in our Issues is #6566
I mostly agree on your notes about how the discussion unfolded, thanks for your efforts here.
The decision to continue with the status quo means directing _installation_ support questions to the mailing list, which means resolving this ticket (not just shelving or closing it).  So I'd like to see `Discussion Required` removed and this issue resolved for 23,  and a new issue opened for 24 or as soon as we'd like to revisit this discussion. That's what I took from the meeting.

**Comment by johnsaigle** [comment]
> resolving this ticket (not just shelving or closing it).

Resolving and closing are kind of the same thing on GitHub. I'm not really sure what you mean here.
