### ISSUE TITLE
Travis failing due to updated Config Setting

### ISSUE THREAD

**Issue by AlexandraLivadas** [aces/Loris#6562]
**Describe the bug**
Travis is failing on multiple PRs due to multiple integration test errors:
`ConfigurationException: Config setting url does not exist in database`

This is potentially related to PRs #6019, #6444, #6549, where the BaseURL config setting was removed from the database. 

A potential fix will be to change any instances of `$config->getSetting('url');` to `\NDB_Factory::singleton()->settings()->getBaseURL();` in integration tests (this was done in #6019)

**To view this issue:**
You can view PR #6510 which failed Travis with this error.

**Comment by christinerogers** [comment]
Travis is failing for everyone because an Integration test contains a straggling reference to the 'url' config setting removed in #6019. It was passing before on RaisinBread which was only recently updated in #6549.
