### ISSUE TITLE
[Issue Tracker] Add attachment triggers a 500 error

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6564]
In Issue tracker, if you try to attach an attachment in Edit/Add issue, 
the operation will fail with an error 500.

`ajax/EditIssue.php?action=edit 500 (Internal Server Error)`

Possible permission issue with IssueTrackerDataPath.

**Comment by ridz1208** [comment]
@kongtiaowang can you make sure the paths are valid ?

**Comment by laemtl** [comment]
This bug seems to be specific to the test VM.

**Comment by kongtiaowang** [comment]
It has been fixed on testing VM.
