### ISSUE TITLE
[Issue Tracker] Missing Help on Issue Add/Edit

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6565]
If you navigate on https://test-loris-dev.loris.ca/issue_tracker/issue/42
And select the help option, it displays:
No help available for issue (/var/www/Loris/modules/issue_tracker/help/issue.md)

The same behaviour occurs if you create a New Issue.

**Comment by christinerogers** [comment]
great!  was there ever any?  could you check both the 17.1 and 19 branches  It would have been lost somewhere in there.  
You can see similar issues we found last fall about missing help text on other sub-modules, documenting how/why it happened.

**Comment by laemtl** [comment]
@christinerogers I looked into the history, the file issue.md was never created.
Adding a markdown file with help content in modules/issue_tracker/help/issue.md should solve that issue.
