### ISSUE TITLE
[imaging_uploader] bug with auto-fill visit label

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#6569]
**Describe the bug**
The auto-fill feature on the imaging_uploader is only populating part of the visit label name. 
Ex: Visit label = `Initial_MRI`, auto-fill is only inputing `Initial` and there is no way to correct it since fields are disabled. I presume it's just a regex thing.

<img width="1326" alt="Screen Shot 2020-05-21 at 3 06 44 PM" src="https://user-images.githubusercontent.com/34260251/82596238-f9579680-9b74-11ea-93f3-565e423e0666.png">

**What did you expect to happen?**
Proper population of the visit label.

**Browser Environment (please complete the following information):**
- OS: 
- Browser: Chrome 
- Version: 23.0

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: 23.0
- Linux distribution and Version: Ubuntu 16.04.6
- MySQL/MariaDB Version: MySQL 5.7

**Comment by johnsaigle** [comment]
It seems like it wants different values in the filename to split on underscores which could cause problems if Visit Labels contain underscores.

**Comment by jesscall** [comment]
I'm not entirely sure how i should implement this fix... 
@johnsaigle @nicolasbrossard @cmadjar any suggestions ?

**Comment by johnsaigle** [comment]
@jesscall If you modify these lines you could issue a quick bug fix

https://github.com/aces/Loris/blob/1f98c1596872adc965d1977f1a2cd23210451363/modules/imaging_uploader/jsx/UploadForm.js#L55-L59

If you remove the second argument to `.split()` on line 56, you should get an array with 4 elements in this case. After assigning CandID and PSCID, you could take any elements at index 2 or higher and glue them together to represent the Visit_label.
