### ISSUE TITLE
[API] Dicom and Recording downloads broken

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#6570]
**Describe the bug**
`GET /candidates/$CandID/$VisitLabel/dicoms/$Tarname` and `GET /candidates/$CandID/$VisitLabel/recordings/$Filename` return 500 error.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'https://test-loris-dev.loris.ca/api/v0.0.3/candidates/587630/V1/dicoms/DCM_2018-04-20_ImagingUpload-13-42-zcoZR0.tar'. The tar file does not download and you get a 500 error in your browser console log.
2. Go to 'https://test-loris-dev.loris.ca/api/v0.0.3/candidates/300166/V1/recordings/sub-OTT166_ses-V1_task-faceO_eeg.edf'. The edf file does not download and you get a 500 error in your browser console log.

**What did you expect to happen?**
Files to download in my browser

**Comment by johnsaigle** [comment]
@kongtiaowang Can you check whether these files exist in the backend?

**Comment by zaliqarosli** [comment]
@johnsaigle they do exist because you can access them at e.g. `candidates/$CandID/$VisitLabel/recordings/$Filename/$header`

**Comment by spell00** [comment]
Both links are not working on the test VM, but it is working using my own VM (_e.g._ 'https://\<your-hostname\>.loris.ca/api/v0.0.3/candidates/587630/V1/dicoms/DCM_2018-04-20_ImagingUpload-13-42-zcoZR0.tar' instead of 'https://test-loris-dev.loris.ca/api/v0.0.3/candidates/587630/V1/dicoms/DCM_2018-04-20_ImagingUpload-13-42-zcoZR0.tar')

**Comment by ridz1208** [comment]
@kongtiaowang is it possible that it is caused by some sort of file permissions on the testing VM ? can you check ?

**Comment by kongtiaowang** [comment]
I restarted apache service. I tested it on Chrome with Incognito window. It works for me.

**Comment by driusan** [comment]
@zaliqarosli can you confirm?

**Comment by zaliqarosli** [comment]
downloads work!
