### ISSUE TITLE
[Statistics / Behavioural Statistics] query by project not working.

### ISSUE THREAD

**Issue by racostas** [aces/Loris#6573]
**Describe the bug**
In `Reports-> Statistics -> Behavioural Statistics`, query by project seems not to by working.

**To Reproduce**
1. Go to `Reports-> Statistics -> Behavioural Statistics`
2. Choose a project on the project's comboBox.
3. Click on Submit Query
4. **Issue:** The results table is not updated except for "All projects" or "DCP" choices

**What did you expect to happen?**
The results table updated accordingly.

**Browser Environment (please complete the following information):**
- OS: Windows
- Browser: Firefox
- Version: 76

**Comment by driusan** [comment]
the PR for this was merged
