### ISSUE TITLE
[MRI Violations] Incorrect permission in test plan

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#6574]
**Describe the bug**
The test plan still mentions permission `violated_scans_edit`. All occurence should be replaced by `violated_scans_view_ownsites`.

**To Reproduce**
N/A

**Comment by johnsaigle** [comment]
@nicolasbrossard I'll take this one

**Comment by nicolasbrossard** [comment]
@johnsaigle Thanks John.
