### ISSUE TITLE
[User Accounts]Test Plan # 36(widget Registration to Dashboard) Failed

### ISSUE THREAD

**Issue by sruthymathew123** [aces/Loris#6577]
**Describe the bug**
Widget registration on the dashboard page cannot be tested/failed. 
The number of pending account approvals that should be displayed in the My Task panel of the dashboard page is not visible/seen even if Pending Approval set to 'Yes' users are there in user accounts

**Steps to reproduce the behavior (attach screenshots if applicable):**
Go to user accounts and Site set to the user's site and Pending Approval set to 'Yes'.  Check to see if the number of pending account approvals is displayed in the My Task panel of the dashboard page.

**Comment by laemtl** [comment]
@sruthymathew123  @ridz1208 @kongtiaowang 
Unable to replicate on my dev instance. Everything works well.
I confirm the problem on the test VM.
