### ISSUE TITLE
[document_repository] Question

### ISSUE THREAD

**Issue by pierre-p-s** [aces/Loris#6579]
This is not so much an issue but rather 2 questions about the module:

- Why do we have a global filteringoption since all the files appear in the root directory?
- Why do all thefiles appear in the root directory?

**Comment by kongtiaowang** [comment]
Question1: If you are under a sub category and you want to filter other files under another category. You can use it.
Question2: This module was developed mainly for the needs of the IBIS project. We had sevrial meetings to discuss it. All the files appear in the root directory, It could help users quickly browse folders and files.

**Comment by johnsaigle** [comment]
@pierre-p-s if satisfied would you mind closing the issue?
