### ISSUE TITLE
[document_repository] Notification emails

### ISSUE THREAD

**Issue by pierre-p-s** [aces/Loris#6580]
New category and edit file notification (email)do not work

**Comment by johnsaigle** [comment]
Can you add some more info about how to reproduce? Was there any message displayed in the error log?

**Comment by pierre-p-s** [comment]
> Can you add some more info about how to reproduce? Was there any message displayed in the error log?

Im "My Preferences" I added the email notifications for the "new category" and "file edited" notification email however I did not receive an email when creating a category or deleting a file.
I do not have access to the error log for this test VM.

**Comment by johnsaigle** [comment]
Would you mind trying to replicate this on your own VM? It's possible that the email isn't properly configured on the test VM.

**Comment by ridz1208** [comment]
@kongtiaowang can you make sure it's not a test VM environment issue ? and investigate further

**Comment by pierre-p-s** [comment]
Also I forgot to mention, I was getting emails when a document was created or deleted.

**Comment by ridz1208** [comment]
@kongtiaowang so I don't think its a configuration issue with the mail server. can you try to find if any errors were generated ?

**Comment by CamilleBeau** [comment]
Comment from closed duplicate issue #6688:

**Describe the bug**
No e-mail notifications are sent when a different user makes changes on document_repository after having the notifications enables in My Preferences.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):

1. Go to My Preferences
2. Enable all of the notifications relevant to document repository (make sure to save)
3. Make another user with a different email and edit document repository from that user by:
4. Uploading new file
5. Deleting file
6. Editing file
7. making a new category
8. Monitor whether you get email notifications for this.

**What did you expect to happen?**
I expected to receive an e-mail for the changes made by the new user.

Note: Email for file deletion and file upload received, not for modification or new category.
