### ISSUE TITLE
[DQT] Field - Some text barely visible

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6584]
In DQT > Define field tab, if you click on a field, the text switches to white on a light background.
If you click on the instrument dropdown, the background switches to a dark color (Chrome only).

**To reproduce**
    Go to Reports > Data Query Tool
    Select the Define field tab
    Select an instrument
    Select a field

![Screenshot from 2020-05-22 11-12-23](https://user-images.githubusercontent.com/32041423/82682496-560e8c00-9c1d-11ea-8930-7611f6457eb9.png)

![Screenshot from 2020-05-22 11-37-22](https://user-images.githubusercontent.com/32041423/82684865-498c3280-9c21-11ea-8554-6cb755987a06.png)

**Comment by christinerogers** [comment]
@3design hey Derek -- see this issue on newly hard to read colour-contrasts in menus 
Do you remember what was supposed to happen with the new design scheme ? 
 Is this likely a Chrome mis-fire, or maybe just an oversight in this module?

**Comment by 3design** [comment]
@christinerogers That's a tough one to answer. I would assume that it's missing a class somewhere to change the text to the contrast colour. Perhaps take a look at other modules with similar functionality.

When I inspect the Access Candidate drop down, the elements in <datalist><options> have a class of .form-control that comes from bootstrap.min.css. When I look a the dqt (on DEMO) this is not there. Maybe a starting point for why things are mixing up?

**Comment by laemtl** [comment]
@3design @christinerogers No problem, I can check!

**Comment by laemtl** [comment]
The dropdown issue can be ignored, it seems to occur only on my chrome instance. Can be caused by a module or a change in my configurations.

**Comment by 3design** [comment]
@laemtl this is still interesting though. Are you using dark mode or a custom colour theme for your browser?

**Comment by laemtl** [comment]
I had a one year old chrome version (75.x.x). It is  solved with an update to the most recent one.
