### ISSUE TITLE
[DQT] Download Data as ZIP button not working

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6586]
In the View Data tab, once the query as run, the Download Data as ZIP button does not have any effect.

**To Reproduce**
In DQT, Define Fields and Filters
Go to View Data
Run the Query
Click Download Data as ZIP

**Comment by ridz1208** [comment]
@laemtl can you open the inspector and see if you get any errors in the console ?

**Comment by laemtl** [comment]
@ridz1208 I did and no errors.

**Comment by ridz1208** [comment]
The download data as zip is only useful when the query contains files that need to be downloaded. (imaging, media, ...)

If the results do not contain files, this might be expected

**Comment by laemtl** [comment]
How can I get results with such files? I will test for this case and update the test plan.

**Comment by ridz1208** [comment]
in the define fields try the mri_data category and use "search within instruments" for the key word `selected`

the displayed options should have a dowloadable symbol next to the field name. these are usually files.

keep in mind if your resulting query contains alot of files, the download data as zip button might take a little while to react to the click. it has to compress the files in the query and set them up for download

**Comment by laemtl** [comment]
No MRI data was imported to the DQT module in the test VM. This test is reported,

**Comment by johnsaigle** [comment]
@laemtl Do you mean that this is an issue with the configuration of the VM and not the code?

**Comment by laemtl** [comment]
Yes, according to @ridz1208, the download button does not produce any effect if the query does not contains files. I think an improvement to avoid the confusion I had can be to disable/hide the button in such cases.

**Comment by ridz1208** [comment]
closing this issue in favour of #6610
