### ISSUE TITLE
[survey_accounts] Can't complete surveys in Firefox

### ISSUE THREAD

**Issue by AlexandraLivadas** [aces/Loris#6587]
**Describe the bug**
On a **Firefox** browser, once the last page of a survey is completed and the button "Save and Finalize" is pressed, the next page (to submit) does not load. A screenshot is included with the exact error message that appears and the Developer Console message. This error occurs both when the URL is selected from the Survey Accounts page and when the URL is selected from the e-mail sent to the user. The same error occurs for all types of instruments. The survey is (correctly) updated to "In Progress", but cannot be completed.
**Note:** The error message says that it could be caused due to disabling cookies. Cookies were enabled on the browser and the error still appeared. 
**Note:** When the URL is copied to a Chrome browser, the page loads correctly

<img width="1281" alt="Screen Shot 2020-05-22 at 12 12 45 PM" src="https://user-images.githubusercontent.com/35467361/82687666-95d97180-9c25-11ea-824c-c5ab6bc5260c.png">

**To Reproduce (on a Firefox Browser)**
1. Create a user account on the testing VM with the "User management" permission.
2. Go to the Survey Accounts page for this user. 
3. Select the URL for a survey that has either "In Progress" or "Created" status
4. Fill out the survey until the option to "Save and Finalize" appears. Click on this button.
5. See error. 

**What did you expect to happen?**
The next page should show the completed survey, a "Survey Comments" section, and the button "Submit Data"

**Browser Environment:**
Firefox 76.0.1

**Comment by johnsaigle** [comment]
Does anything appear in the error log when you try this?

**Comment by AlexandraLivadas** [comment]
When I run this on my personal VM (with 23.0-release checked out), I get this error in `/var/log/apache2/loris-error.log`:
```
[Mon May 25 12:13:02.238463 2020] [php7:warn] [pid 22511] [client 192.168.122.1:34280] PHP Warning:  A non-numeric value encountered in /var/www/loris2020/htdocs/survey.php on line 128, referer: https://alivadas-dev.loris.ca/survey.php?key=%pt%up31&pageNum=3
```

This error is printed many times and the error that appears before it is:
```
[Mon May 25 12:11:47.175348 2020] [php7:warn] [pid 22511] [client 192.168.122.1:34150] PHP Warning:  Invalid argument supplied for foreach() in /var/www/loris2020/php/libraries/LorisForm.class.inc on line 1319, referer: https://alivadas-dev.loris.ca/survey.php?key=%pt%up31&pageNum=3
```
I will continue to look into these errors :)
