### ISSUE TITLE
[DQT] Nan values in Statistics

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6592]
In DTQ > Statistical Analysis
Some NaN are displayed in statistics values, possibly due to the presence of NULL values in the records, and nothing appears in the plot canvas.

**Cross-sectional**
![Screenshot from 2020-05-22 12-28-10](https://user-images.githubusercontent.com/32041423/82689247-303ab480-9c28-11ea-8764-c9d651f49593.png)

**Longitudinal**
![Screenshot from 2020-05-22 12-26-19](https://user-images.githubusercontent.com/32041423/82689250-32047800-9c28-11ea-8358-3a603af5222e.png)

![Screenshot from 2020-05-22 12-37-19](https://user-images.githubusercontent.com/32041423/82689808-12218400-9c29-11ea-88fb-274fd87e320e.png)

**Comment by christinerogers** [comment]
this is normal.  not a issue - can be closed.
