### ISSUE TITLE
[DQT] Run Query get stuck on loading

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6594]
In DQT, if you skip the step Define Fields, Define filters aosi | Candidate_Age <= 20 All Visits, and run the query in View Data,

> We are currently working hard to load your data. Please be patient.

stays on screen after the ajax query has completed (Response of the ajax query available in the console) and never disappears. This problem occurs on very simple query too (i.e with Candidate_Age = 33 where only 1 result is returned).

**To reproduce**
Do not define any Fields
Define Filters aosi | Candidate_Age <= 20 All Visits
Go to View Data
Run the Query

**Comment by christinerogers** [comment]
this issue needs more information - please update the description above 
* What query were you running?  Was it simple or complex? 
* does this bug replicate on a very simple query  that is only returning a small dataset?  (e.g. try Dob = a very specific date matching only 1 candidate)

**Comment by ridz1208** [comment]
@laemtl I think @maltheism has already identified this bug.

It will not likely be fixed for this release but will be part of the bigger redesign.

**Comment by laemtl** [comment]
Related to PR #6018

**Comment by maltheism** [comment]
@laemtl & @ridz1208 the dqt redesign does disable the "Run Query" button unless a field has been selected. So the bug found won't occur on my redesign branch. I'm not sure if that should be fixed for release?

**Comment by laemtl** [comment]
Thank you @maltheism! I think @ridz1208 is the best person to take that decision.

**Comment by christinerogers** [comment]
Issue is closed for now -- @ridz1208 up to you i guess whether we look into fixing the DQT for 23. 

cc @cmadjar

**Comment by maltheism** [comment]
@ridz1208 it seems this is a different bug that needs to be fixed. I'll look into fixing it but I'm going to keep it separate from the redesign PR.
