### ISSUE TITLE
[DQT] JS Error on View Data > Longitudinal view

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6595]
**To reproduce**
Define Fields: aosi | Candidate_Age
Define Filters: aosi | Candidate_Age = 33 All Visits
View Data > Run Query
Switch to Longitudinal

> 
> react_devtools_backend.js:6 TypeError: Cannot read property '0' of null
>     at StatsVisualizationTabPane.render (react.tabs.js:651)

**Comment by ridz1208** [comment]
@maltheism can you look into a quick fix for this one ?

**Comment by maltheism** [comment]
@ridz1208 okay.
