### ISSUE TITLE
[Login] Password reset - 403 with some passwords

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6607]
On the reset password screen, enter an email address in the password field triggers a 403 error

**To reproduce**
Change Password_expiry for a given user in the database for a date in the past
Login with that user
Type laetitia.fesselier@mail.mcgill.ca in the password field.

**Comment by johnsaigle** [comment]
Very weird. Is there more detailed information in the 403 response?

**Comment by laemtl** [comment]
[Tue May 26 10:56:09.411272 2020] [php7:notice] [pid 27241] [client ::1:51760] PHP Fatal error:  Uncaught InvalidArgumentException: Password cannot be set to email in /var/www/html/loris/php/libraries/User.class.inc:496

It seems to be caused by an uncaught exception.

**Comment by johnsaigle** [comment]
Yeah it looks like validation is not being done properly in the login module, so the User class is reporting that something has gone wrong.
