### ISSUE TITLE
[Issue Tracker] Missing Low value in Priority filter (for 23)

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6608]
In Issue tracker, the priority filter is missing the Low value, preventing to filter issues with Low priority. This a duplicate of #6262, but for the 23.0 release.

Related to #6262 
May be fixed with PR #6263

**Comment by christinerogers** [comment]
This bug duplicates #6262 specifically for the 23 branch.  
@laemtl could you add in your Issue description and title `for 23`, for clarity ? that was the intention here, thanks
