### ISSUE TITLE
[DQT] Hide ZIP download button when query contains no data

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6610]
Yes, according to @ridz1208, the download button does not produce any effect if the query does not contains files. I think a future improvement to avoid the confusion I had might be to disable/hide the button in such cases.

_Originally posted by @laemtl in https://github.com/aces/Loris/issues/6586#issuecomment-633624639_

**Comment by laemtl** [comment]
@maltheism I think this is something you addressed?
