### ISSUE TITLE
[issue_tracker] Special characters in description

### ISSUE THREAD

**Issue by pierre-p-s** [aces/Loris#6614]
**Describe the bug**
Special characters appear as &amp;, etc... after saving (See screenshot below)

![Screen Shot 2020-05-26 at 12 55 13 PM](https://user-images.githubusercontent.com/57676906/82928596-63df4c80-9f50-11ea-8905-2e013e752f1f.png)

**Comment by johnsaigle** [comment]
@ridz1208 @driusan It seems that this should be fixed by #6158. Have the changes been pushed from the 22 bugfix release to 23.0?
