### ISSUE TITLE
[imaging browser] Columns not appearing when adding some scan types

### ISSUE THREAD

**Issue by h-karim** [aces/Loris#6619]
**Additional context**
This fails step 7 of the "main page" section of the test plan.

**Describe the bug**
When adding a scan type via the Config module, new columns don't appear on the front page of the imaging browser for the particular scan

**To Reproduce**
1. Go to Admin>Configuration>Imaging Modules
2. Next to "Imaging Browser Tabulated Scan Types" add a "flair" field
3. Click on submit
4. Navigate to the imaging browser front page
5. observe no new column appears
**What did you expect to happen?**
A new table column with the name "flair". 

Field values tested that reproduce this bug are (list is not exhaustive): 
- flair
- pd
- mrs
- dti
- -defaced (NOT "t1-defaced" and "t2-defaced")
- NA
- pve

**Browser Environment (please complete the following information):**
- OS: Ubuntu 18.04 LTS
- Browser:
    firefox 76.0.1
    Chrome 83.0.4103.61

**Server Environment (if known):**
Tested using the loris testing VM.

**Comment by johnsaigle** [comment]
How does this interact with https://github.com/aces/Loris/issues/6616? Were you able to get the module to load with these new scan types?

**Comment by h-karim** [comment]
@johnsaigle Yes, the module loads successfully. The only problem is that a new column is not observed (as per the test plan step) on the front page.

**Comment by johnsaigle** [comment]
So is #6616 not a problem anymore? I'm just wondering how you got around that issue when you've enabled the -defaced scans

**Comment by h-karim** [comment]
#6616 occurs specifically for the values "t1-defaced" and "t2-defaced", it's still a problem. 

On this issue, I haven't added "t1-defaced" and "t2-defaced", just "-defaced" (it's a separate value in the selection menu. "-defaced" (along with the rest of the values mentioned in this issue) doesn't cause a loading issue, it just doesn't display an expected column for it in the front page table. For correct behaviour, adding "fMRI" scans shows you the expected behaviour, a column with the fMRI scan status:

![screenshot of correct behaviour](https://i.imgur.com/zAu1Llc.png) 

The values mentioned here don't add a column as expected.

**Comment by johnsaigle** [comment]
Ah OK I didn't know that `-defaced` was its own thing. Thanks for clarifying.

**Comment by h-karim** [comment]
I think I got it. 
https://github.com/aces/Loris/blob/a5304c762454fa8241ce0699af94b2da15f8879d/modules/imaging_browser/php/imagingbrowserrowprovisioner.class.inc#L42-L46
According to the comment on line 45,  `\Utility::getScanTypeList()` was used to get all the different scan types, however in reality, that function was only getting an intersection of all the scan types with some files, which excludes a lot of modalities:

  
https://github.com/aces/Loris/blob/a5304c762454fa8241ce0699af94b2da15f8879d/php/libraries/Utility.class.inc#L1001-L1018

Modifying `getScanTypeList` optionally disable the inner join should fix this issue. 
cc @johnsaigle @christinerogers

**Comment by christinerogers** [comment]
@h-karim I think the most problematic of these is `dti` and `mrs` -- can you investigate these 2 -- is it the same source problem for these 2?  
e.g. just enabling `-defaced` doesn't make sense to me, if I understand you right. 

Next step will be i will cecile to weigh in, after you investigate this a little further karim

**Comment by h-karim** [comment]
Following [this comment](https://github.com/aces/Loris/pull/6634#issuecomment-636200304), it seems the issue is with the selection menu displaying unnecessary scan types, rather than the columns not appearing in the module's table. As such, This is a non issue.
