### ISSUE TITLE
[Imaging Uploader] Got HTTP 500 even though upload was valid

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#6620]
**Describe the bug**
When uploading a file that already exists, I get an HTTP500 error even though I confirmed that I wanted to overwrite the existing file.

**To Reproduce**
Note that this requires the use of two different user accounts (say A & B):
1. Log in as user A and upload a file that has not already been uploaded. The file should upload successfully and should appear in the result table.
2. Log out and log in as user B. Upload a file with the same base name as the file that was uploaded in step 1.
3. When the system asks you if you'd like to overwrite the existing file, answer 'Yes'.
4. The upload progress will go up to 100% but you'll get an error message afterwards saying that the server responded with an HTTP 500 error.

**What did you expect to happen?**
The file uploaded in step 2 should have overridden the one uploaded in step 1 and no errors should have been reported.

**Browser Environment (please complete the following information):**
This bug will occur on any browser.

**Server Environment (if known):**
This bug will occur on any server

**Comment by johnsaigle** [comment]
Were there any more details about the 500 error in the response or in the error log? It's possible that the exception message contains more information.

**Comment by nicolasbrossard** [comment]
Nope, just an HTTP 500 error.

**Comment by johnsaigle** [comment]
Even in the back-end? There's usually a message in the error log if PHP crashes

**Comment by nicolasbrossard** [comment]
In PHP's error log you see that there was an uncaught exception that occurred:

```
[Tue May 26 15:53:52.503593 2020] [php7:error] [pid 20338] [client 192.168.122.1:58960] PHP Fatal error:  Uncaught DomainException: Attempt to use pselectRow on a query that returns multiple rows in /var/www/Loris/php/libraries/Database.class.inc:818\nStack trace:\n#0 /var/www/Loris/php/libraries/Database.class.inc(956): Database->pselectRow('SELECT \\n       ...', Array)\n#1 /var/www/Loris/modules/imaging_uploader/php/imaging_uploader.class.inc(415): Database->pselectOne('SELECT \\n       ...', Array)\n#2 /var/www/Loris/php/libraries/File_Upload.class.inc(210): LORIS\\imaging_uploader\\Imaging_Uploader->isValid(Object(File_Upload), Array)\n#3 /var/www/Loris/php/libraries/File_Upload.class.inc(103): File_Upload->callFileHandler('mriFile', 'verify')\n#4 /var/www/Loris/modules/imaging_uploader/php/imaging_uploader.class.inc(252): File_Upload->processFiles()\n#5 /var/www/Loris/modules/imaging_uploader/php/imaging_uploader.class.inc(149): LORIS\\imaging_uploader\\Imaging_Uploader->_saveFile(Array)\n#6 /var/www/Loris/php/libraries/NDB_Menu_Filter_Form.class.inc(82): LORIS\\imaging_uploader\\Imaging_Uploader->_process(Array)\n#7 /var/w in /var/www/Loris/php/libraries/Database.class.inc on line 818, referer: https://test-loris-dev.loris.ca/imaging_uploader/
```

**Comment by johnsaigle** [comment]
OK so based on that message it looks like there's a problem in the SQL query.

Would you mind including the exact values you used to get this error? It'll help with reproducing and fixing the SQL command.

**Comment by nicolasbrossard** [comment]
The problem lies with this query
```
"SELECT 
                IF (InsertionComplete=0 AND 
                (ISNULL(Inserting) OR Inserting=0), UploadID, NULL) as UploadID 
                FROM mri_upload WHERE UploadLocation LIKE :ul"
```

in `imaging_uploader.class.inc`. It will blow up if there is more than one file with the same base name as the file we are uploading, which is what will happen: an exception will be thrown by `pselectOne` since it found more than one match.

**Comment by jesscall** [comment]
Hi @nicolasbrossard, I just tried replicating the issue and I do not get a 500 error. I was able to successfully overwrite the file without errors

**Comment by jesscall** [comment]
<img width="1400" alt="Screen Shot 2020-06-03 at 11 07 49 AM" src="https://user-images.githubusercontent.com/34260251/83654345-f7d19980-a58a-11ea-897f-52253af2137b.png">


<img width="1436" alt="Screen Shot 2020-06-03 at 11 10 42 AM" src="https://user-images.githubusercontent.com/34260251/83654349-fa33f380-a58a-11ea-9a12-60f6d109f84b.png">

**Comment by nicolasbrossard** [comment]
Tired to reproduce but couldn't...Had to be some sort of inconsistent/bad state on the test VM that triggered this. Closing.
