### ISSUE TITLE
[RTD] Page broken on 404 errors

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6622]
On the ReadTheDocs documentation, the 404 page is broken:
[example](https://acesloris.readthedocs.io/en/latest/fsdf)

**Comment by driusan** [comment]
Is this a bug with us or with RTD itself?

**Comment by laemtl** [comment]
It's something we can fix on our side. I'm not sure on the cause yet.

**Comment by christinerogers** [comment]
It's rendering now without CSS. @laemtl can you update this issue and advise on the fix?

**Comment by laemtl** [comment]
@christinerogers This has been fixed in PR #6667
https://loris-dev.readthedocs.io/en/latest/
