### ISSUE TITLE
Stale bot broken

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6627]
**Describe the bug**
Stale bot doesn't seem to be adding or removing labels anymore.

@driusan @ridz1208 was this disabled manually?

If not it might be the result of the access changes made recently. This should be investigated so that we can make use of it again.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to an Issue or PR labelled Stale
2. Interact with it (e.g. leave a comment)
3. Observe that Stale bot does not remove the Stale label.

**Comment by ridz1208** [comment]
@johnsaigle thanks fort he info. I'll add it to the list

**Comment by driusan** [comment]
It was disabled

**Comment by johnsaigle** [comment]
Will it be re-enabled?
