### ISSUE TITLE
[User Accounts] user_accounts_multisite does not allow module access

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6657]
According the the test plan, the User Accounts page should only load if a user has the `user_accounts` or `user_accounts_multisite` permission.

Currently, a user with `user_accounts_multisite` and without `use_accounts` permission gets a `You do not have access to this page` on User Accounts page. This causes users to see the user approval widget on the dashboard, but the widget link redirects to a dead end, as users get a permission error.

**Comment by johnsaigle** [comment]
This came up in https://github.com/aces/Loris/issues/5951 and will be resolved by https://github.com/aces/Loris/pull/5958.

I can rebase this PR onto 23
