### ISSUE TITLE
[timepoint_list] Candidate Info and View Imaging Datasets buttons always appear

### ISSUE THREAD

**Issue by driusan** [aces/Loris#6673]
While accessing a same-site candidate as a user with no permissions, the  "Candidate Info" and  "View Imaging Datasets" links always appear. They do not require the permissions required in the test plan (though clicking on them gives a permission denied error, so the modules linked to are properly enforcing permissions.)

(ie "Action Buttons" step 2 and 3 of the test plan fail.)

**Comment by ridz1208** [comment]
@CamilleBeau please fix for 23.0-release

**Comment by CamilleBeau** [comment]
From what I understand in the test plan, only "Candidate Info" and "Create time point" require the data entry permission to appear, but not "View Imaging datasets". What permissions are required for the "View Imaging Datasets" button to show?

> - For a candidate of the same site as your user, there should be up to 3 additional buttons:
> a. "Create time point" (links to create_timepoint module for that candidate) if your user has permission data_entry
> b. "Candidate Info" (links to candidate_parameters module for that candidate) if your user has permission data_entry
> c. "View Imaging Datasets" (links to the imaging_browser module menu page filtered for that candidate)

**Comment by driusan** [comment]
The PR was merged
