### ISSUE TITLE
[candidate_parameters] Date format does not match dates specified in config

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#6678]
**Describe the bug**
Altering the _DOB format_ or the _DOD format_ fields in the configuration module do not change how the dates are displayed / stored on the front-end or back-end for this module. The TestPlan for this module specifies that it should : 
> 35. Check that the date stored matches the DOB Format specified in the configuration module.

> 40. Check that the date stored matches the DOD Format specified in the configuration module.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. From admin user, modify the values for _DOD format_ and _DOB format_ in the config module.
2. Navigate to a candidate's profile on the candidate parameters module and see that the dates remain the same.
3. Get the information in the back-end from the `candidate` table and see that the dates are stored in the same way.

**What did you expect to happen?**
The format of the dates to change in the `candidate_parameters` module.

**Comment by johnsaigle** [comment]
Maybe related to #6561

**Comment by driusan** [comment]
It's unrelated to that, the config for DoB format was added in #2617

**Comment by jesscall** [comment]
@CamilleBeau The display on front-end isn't supposed to change or anything. 

Expected behaviour when DOB / DOD format is 'Ym'
- If user enters `2020-05-24`, what is actually saved is `2020-05-01`. The day of the month gets set to `01`.

**Comment by CamilleBeau** [comment]
@jesscall Retested. After saving the configuration settings to Ym format for DoB and DoD, the date format remained the same after refreshing and navigating away in the candidate parameter page, as well as in a query to the database.

These examples show DoB but the same was true for DoD.


![image](https://user-images.githubusercontent.com/51176779/84194567-34116800-aa6b-11ea-893e-ad4ef4514311.png)

![image](https://user-images.githubusercontent.com/51176779/84194600-412e5700-aa6b-11ea-83a7-a042538d6f66.png)

![image](https://user-images.githubusercontent.com/51176779/84194621-4be8ec00-aa6b-11ea-83cf-9b6be65603c9.png)

**Comment by jesscall** [comment]
@CamilleBeau querying DB? are you using raisinbread or the CCNA project? if CCNA: likely candidate_parameters override on CCNA is interfering and accounts for the unexpected behaviour. I quickly checked on the test vm and functionality seems to be as expected. Maybe you can confirm?

**Comment by jesscall** [comment]
also side note: the date format from your image `Ym` indicates using month names (Jan, Feb, etc). `YM` would be numeric month format. 

Not sure if that's the reason for discrepancy in behaviour

**Comment by ridz1208** [comment]
Removing critical to release as this has always been the case.
