### ISSUE TITLE
[candidate_parameters] Titles cut off in widget for Candidate Info card

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#6679]
**Describe the bug**
Fields added in the `parameter_type_category` table for Name='Candidate Parameters' show up on the Candidate Info card in the Candidate Profile page, but those with long titles overlap and are legible. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Modify the `parameter_type_category` table so that "Candidate Parameters" is linked to a `ParameterTypeCategoryID`. 
2. Go to a candidates profile and enter values in the `Candidate Information` tab for the fields added from the previous step.
3. Access the Candidate Profile page for that candidate.
![image](https://user-images.githubusercontent.com/51176779/84054366-50d17100-a981-11ea-95b3-8f8de06c73f2.png)

**What did you expect to happen?**
To see the fields displayed without titles overlapping.

**Comment by driusan** [comment]
Did you add those for testing? It seems weird that "X magically created by Y" entires are in the category which is for things that are automatically editable by users in the frontend.

**Comment by CamilleBeau** [comment]
@driusan The fields were already in the DB and I reassigned them to Candidate Parameters on my VM for step 5 of the TestPlan.
