### ISSUE TITLE
[candidate_parameters] Consent card visible in candidate_profile

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#6680]
**Describe the bug**
The consent card appears in the Candidate Profile page even if `Use Consent` setting is set to no in configuration module, contrary to what is specified by the TestPlan. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. From admin, set `Use Consent` to yes in configuration module
2. Navigate to Candidate Profile page from non-admin account and see the consent card there as it should be.
3. Now set `Use Consent` to no in the configuration module.
4. Refresh the candidate profile page (or navigate away and back again) and see that the consent card is still there. 

**What did you expect to happen?**
The consent card to only be visible if it is set to 'yes' in config module.

**Comment by driusan** [comment]
The test plan says consents need to be configured (ie. there are entries in the `consent` table), it doesn't say anything about any "Use Consent" configuration.

**Comment by CamilleBeau** [comment]
@driusan my mistake! Closing this issue.

**Comment by driusan** [comment]
I don't think this should be closed, we should either update the test plan to be more clear pr either update the code to check the config.

Personally, I don't really see the point of the useConsent option. It can be easily derived from whether any consents are configured. If there are none, then it obviously isn't being used.

**Comment by driusan** [comment]
Decision: add the useConsent check in a bugfix release, but not critical for the release. Look into deprecating  "useConsent" as a whole later.

**Comment by ridz1208** [comment]
@zaliqarosli can you take this on ?

**Comment by driusan** [comment]
The PR for this was merged, not sure why the issue wasn't autoclosed..
