### ISSUE TITLE
[battery_manager] View permission

### ISSUE THREAD

**Issue by pierre-p-s** [aces/Loris#6682]
**Describe the bug**
When giving only view permission to a user, an error occurs when they try to access the module.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Create a user account 
2. Give it view permission for the battery manager module
3. Access the user account
4. The module should be clickable in tools but when you access it, an error should appear 

Note:
I couldn't test the module from a user account because I cannot access module at all except with admin

**Comment by ridz1208** [comment]
@pierre-p-s could you add the error log error on this ticket ?

**Comment by pierre-p-s** [comment]
![Screen Shot 2020-06-08 at 12 41 51 PM](https://user-images.githubusercontent.com/57676906/84190736-6750f880-aa65-11ea-924c-d1f32f60a2dc.png)

**Comment by ridz1208** [comment]
@HenriRabalais when you have a minute can you check it out ?

**Comment by HenriRabalais** [comment]
@ridz1208 should I be addressing this?

**Comment by ridz1208** [comment]
@HenriRabalais it doesnt have anyone assigned. if you have time why not

**Comment by driusan** [comment]
resolved by #6858 above
