### ISSUE TITLE
Help content becomes detached after scrolling

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6686]
**Describe the bug**
If you open help content in a module and scroll down, the help content scrolls with you and appears to float or become detached from the top of the screen.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to any module
2. Click on help
3. Scroll down

**What did you expect to happen?**
The help should close - or maybe the menu bar could become "frozen" and scroll along with the help.

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser: Firefox
- Version 78.03b

**Additional context**
<img width="1279" alt="Screen Shot 2020-06-08 at 15 34 56" src="https://user-images.githubusercontent.com/4022790/84072921-f0046180-a99d-11ea-99a5-f0aecd297e9d.png">

**Comment by christinerogers** [comment]
Only in Firefox, not Chrome right? @johnsaigle

**Comment by johnsaigle** [comment]
I just tested it and it also happens on Chrome.

**Comment by christinerogers** [comment]
nice catch @johnsaigle
