### ISSUE TITLE
[User Accounts] User with superuser privilege cannot modify permissions for other users or own account

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6687]
**Describe the bug**
Even when a user that is not `admin` has `superuser` permission, they are limited in their ability to modify user accounts.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Using `admin`, create a new user `User1` that has only the permission `superuser`.
2. Login as `User1` and go to `user_accounts`
3. You will see that `User1` is not able to edit any of their permissions.
4. As `User1`, create a new user account.
5. `User1` will not be able to give any permission except for `superuser`.

**What did you expect to happen?**
Since superuser short-circuits every other permission, having this permission should allow a user to fully modify their own account, as well as others.

Right now it seems that if a user other than `admin` has `superuser` they still do not have full rights to modify user accounts.

**Server Environment (if known):**
- LORIS Version: 23.0-release branch

**Additional context**

<img width="1394" alt="Screen Shot 2020-06-08 at 15 50 14" src="https://user-images.githubusercontent.com/4022790/84074797-1ed00700-a9a1-11ea-858e-604126c330a8.png">

---

<img width="1384" alt="Screen Shot 2020-06-08 at 15 52 07" src="https://user-images.githubusercontent.com/4022790/84074796-1ed00700-a9a1-11ea-9131-e9d9d40349f7.png">

**Comment by christinerogers** [comment]
@laemtl would you have time to verify this today/tomorrow?

**Comment by laemtl** [comment]
The main user, admin, does not have the ability to edit its own permission either. I may be wrong, but it does not seem to be a bug but a design decision.
