### ISSUE TITLE
[MRI Violations] Navigation issue on "/mri_protocol_violations/" page

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6689]
**Describe the bug**
The page `whatever.loris.ca/mri_violations/mri_protocol_violations/` contains two tabs under the menu filter. 

The second tab appears as active on this page. 

Clicking the first tab takes the user to `whatever.loris.ca/mri_violations/` which removes both tabs.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `mri_violations/mri_protocol_violations/`
2. Click on the first tab (marked "Protocol Violations")
3. After the page loads, the tabs are gone

**What did you expect to happen?**
The tabs shouldn't disappear. A user should be able to alternate between them.

**Comment by nicolasbrossard** [comment]
The issue does not describe the intended behaviour. Closing and opening new issue #6839.
