### ISSUE TITLE
[document_repository] No error message for uploading large files

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#6690]
**Describe the bug**
When uploading a file that exceeds the max upload limit, the page remains stagnant and no error message is displayed after waiting. In this case the file was 1.54 GB.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `document_repository` -> `upload`
2. Attempt to upload a large file.
3. Wait
4. See that no error message is displayed and the upload does not go through 

**What did you expect to happen?**
An error message explaining that the file is too large.

**Comment by johnsaigle** [comment]
This sound very similar to https://github.com/aces/Loris/issues/6314. Can you look into that thread and see whether you think the same thing is happening?

**Comment by johnsaigle** [comment]
Also was this on the test VM or your own set up?

**Comment by CamilleBeau** [comment]
> Also was this on the test VM or your own set up?

@johnsaigle I tried on both. It does look like the same thing is happening to issue #6314, although I am not getting an error in the console.

**Comment by johnsaigle** [comment]
Are you getting any response in the Network tab?

**Comment by johnsaigle** [comment]
Thanks for the screenshot. it looks like the upload is just hanging

**Comment by CamilleBeau** [comment]
An error swal is now displayed. It does not specify that the file is too large, but I think this is still a sufficient fix to this issue.
