### ISSUE TITLE
[Imaging Browser / View Session ] unstable behaviour when saving the QC status.

### ISSUE THREAD

**Issue by racostas** [aces/Loris#6692]
**Describe the bug**
An unstable behaviour was observed when saving the` QC status`. For some of the subjects once the button `Save ` is clicked the server gives an ERROR 500 answer, and for others do work fine.

**To Reproduce**
1. Go to Imaging -> Imaging Browser

2. Take the subject `DCCID = 587630 and Visit Label V1`  click on links -> all types. 
3. Changes some values on the QC ComboBoxes and click Save or just click save once the page is loaded. The Save button on the right panel.
4. All works fine.

5. Take the subject `DCCID = 947103 and Visit Label V3`  click on links -> all types. 
6. Changes some values on the QC ComboBoxes and click Save or just click save once the page is loaded. The Save button on the right panel.
7. See error 500

8. Randonly repeat this steps for other subjects. For some of the server will echo a 500 error and for other the process will do work as expected.

**Note**
So far I don't find a pattern that makes fails for a set of subjects and for others no. Maybe a more experienced person with this module could bring more light to the issue.

**What did you expect to happen?**
All subjects properly loaded and QC saved.

**Comment by ridz1208** [comment]
@racostas could you do it again while talking to @kongtiaowang  so he can copy the error in this ticket

**Comment by driusan** [comment]
This might be critical for the release depending on if it turns out to be a raisinbread/test VM issue or if it's a general problem with the code.

**Comment by kongtiaowang** [comment]
It has been fixed by https://github.com/aces/Loris/pull/6520. This PR got merged yesterday. I run the new patch, it solved the issue.
