### ISSUE TITLE
[Candidate List] PSCID link clickable even though I don't have access_all_profiles

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#6694]
**Describe the bug**
I can click on the PSCID link in the search result table even though I do not have the `access_all_profiles` permission.

**To Reproduce**
Access the candidate list with a user that does not have the `access_all_profiles` permission and click on any PSCID link in the search result table.

**What did you expect to happen?**
The PSCIDs should be labels, not links according to item 17 in the Candidate List test plan.

**Comment by ridz1208** [comment]
@nicolasbrossard test plan should be updated

**Comment by cmadjar** [comment]
Test plan should be updated as this is the intended behaviour.
