### ISSUE TITLE
[Issue Tracker] Incorrect filter content for 'My Issues' and 'Closed Issues' tabs

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#6695]
**Describe the bug**
In the issue tracker module, tab 'My Issue', there is an assignee drop-down in the filter section. In the 'Closed Issues' tab, there is a status drop-down in the filter section.

**To Reproduce**
Access the issue tracker module and look at the filter contents for tabs 'My Issues' and 'Closed Issues'.

**What did you expect to happen?**
According to item 4 of the test plan there should not be any assignee drop-down in the 'My Issues' tab and no 'Status' drop-down in the 'Closed Issues' tab.

**Comment by HenriRabalais** [comment]
PR #6636 appears to be merged!

**Comment by laemtl** [comment]
@HenriRabalais is right, #6636 has been merged since my reply.

**Comment by driusan** [comment]
Can this be closed, then?
