### ISSUE TITLE
[module_manager] UI carousel scrollers never disappear regardless of zoom level

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#6697]
**Describe the bug**
When accessing the module_manager with EDIT permission, regardless of the zoom level, the carousel scrollers (left and right) are always displayed even though the is nothing to scroll sideways... they just make the interface glitchy when the mouse accidentally hovers over them. see screenshots

<img width="1680" alt="Screen Shot 2020-06-09 at 9 11 21 AM" src="https://user-images.githubusercontent.com/15268287/84151779-d4e33180-aa31-11ea-901a-2ba6c6cffa5d.png">
<img width="1675" alt="Screen Shot 2020-06-09 at 9 11 32 AM" src="https://user-images.githubusercontent.com/15268287/84151787-d876b880-aa31-11ea-89fa-7cbd8587dd1b.png">

**Comment by laemtl** [comment]
Resolved bt #6717
