### ISSUE TITLE
[User Accounts] Password can be the username

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6699]
In the Password Rules intro text (/user_accounts/edit_user/):
* The password must be at least 8 characters long.
* The password cannot **be your username** or email address.
* No special characters are required but your password must be sufficiently complex to be accepted.

The password validation does not check for the username case. We should edit the intro text or add a validation rule.

**Comment by johnsaigle** [comment]
Probably adding a rule is good. We don't want to allow this.
