### ISSUE TITLE
[MRI Violations]   violated_scans_edit permission should be removed

### ISSUE THREAD

**Issue by driusan** [aces/Loris#6723]
The default schema includes the permission:

    (20,'violated_scans_edit','Violated Scans: Edit MRI protocol table','2'),

This appears to have only one reference in `resolved_violations.class.inc`

```
        $this->tpl_data['violated_scans_modifications']
            = $user->hasPermission('violated_scans_edit');
```

However, the `violated_scans_modifications` template variable is not referenced in any template. The code and permission can be removed.

**Comment by christinerogers** [comment]
this sounds like a bug to me.  
@driusan Did we remove the ability to edit the MRI protocol table via the front end?  If that feature exists and it's not governed by his permission... then what happened...

**Comment by christinerogers** [comment]
this is a followup cleanup task from making the mri_protocol table read-only in #6372

**Comment by mohadesz** [comment]
I kind of liked the editing option for MRI_protocol table via front-end

**Comment by christinerogers** [comment]
our condolences @mohadesz  :)
