### ISSUE TITLE
22.0_To_23.0_upgrade.sql attempts to insert into modules table before creating the table

### ISSUE THREAD

**Issue by ejoh1101** [aces/Loris#6726]
**Describe the bug**
Upgrade script attempts to insert row into `modules` table before creating table. Attempted insert is at line 72, table creation is at line 308. 

**To Reproduce**
Upgrade mySQL database from v22 to v23 using SQL/Release_patches/22.0_To_23.0_upgrade.sql

**Comment by driusan** [comment]
Hi @ejoh1101, can you verify if #6728 fixes this?

**Comment by ejoh1101** [comment]
I can confirm that #6728 fixed the issue. It ran without any errors.
