### ISSUE TITLE
Phan issue on main branch: PhanTypeInstantiateAbstract Instantiation of abstract class \Module

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6734]
This may only occur with newer versions of phan.

On my VM when I check out `aces/master` and run `make checkstatic` there is a phan issue.

**Comment by laemtl** [comment]
Cannot reproduce on my system with the last version of Phan (3.0.4)

**Comment by johnsaigle** [comment]
When I do `make clean; make dev` on master it installs `2.5.0` which is the version creating the notice.

Anyway it doesn't appear to be affecting Travis builds or anything so I don't think this is really a big deal.

**Comment by laemtl** [comment]
@johnsaigle I also was unable to reproduce with 2.5.0.
