### ISSUE TITLE
DQT Import script breaks if visit label contains spaces

### ISSUE THREAD

**Issue by driusan** [aces/Loris#6751]
After investigating why the DQT demographics import was failing for a project, it was determined to be caused by a test visit where the visit label contained spaces. This should be confirmed and fixed.

**Comment by johnsaigle** [comment]
Might be a good idea to create a value object for Visit Labels. We've also had issues when they contain underscores. Restricting them to alphanumeric would probably save a lot of headaches.

**Comment by ridz1208** [comment]
@maltheism wasnt this fixed in your latest DQT ?

**Comment by maltheism** [comment]
@ridz1208 I'm unsure because I don't remember touching the couchdb import script but I believe you did. I do remember you having me fix visit labels with underscores.

**Comment by ridz1208** [comment]
@maltheism sorry I misread the issue, I thought the bug was in the DQT not the import script

**Comment by ridz1208** [comment]
@driusan we tackled this back when we were bugfixing CBIGR. I'll see if the fix was submitted to LORIS

**Comment by driusan** [comment]
@ridz1208 did you ever look into it?

**Comment by driusan** [comment]
@ridz1208 can this be closed?
