### ISSUE TITLE
[Document_repository] Clicking on a file link returns PHP Exception 

### ISSUE THREAD

**Issue by h-karim** [aces/Loris#6759]
This bug was reproduced on the 23.0 release and the master branch

**Describe the bug**
When clicking on a file link, one of two errors is logged, either:

>PHP Fatal error:  Uncaught DomainException: Attempt to use pselectRow on a query that returns multiple rows in /var/www/loris/php/libraries/Database.class.inc:843\nStack trace:\n#0 /var/www/loris/php/libraries/Database.class.inc(984): Database->pselectRow('SELECT uploaded...', Array)\n#1 /var/www/loris/modules/document_repository/php/files.class.inc(119): Database->pselectOne('SELECT uploaded...', Array)\n#2 /var/www/loris/src/Middleware/UserPageDecorationMiddleware.php(233): LORIS\\document_repository\\Files->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#3 /var/www/loris/src/Middleware/PageDecorationMiddleware.php(56): LORIS\\Middleware\\UserPageDecorationMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\document_repository\\Files))\n#4 /var/www/loris/php/libraries/NDB_Page.class.inc(696): LORIS\\Middleware\\PageDecorationMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\document_repository\\Files))\n#5 /var/www/loris/php/libraries/Module.class.inc(412): NDB_Page->process(Object(Laminas\\Di in /var/www/loris/php/libraries/Database.class.inc on line 843

or 

>PHP Fatal error:  Uncaught InvalidArgumentException: Invalid stream reference provided in /var/www/loris/vendor/laminas/laminas-diactoros/src/Stream.php:345\nStack trace:\n#0 /var/www/loris/vendor/laminas/laminas-diactoros/src/Stream.php(59): Laminas\\Diactoros\\Stream->setStream('/data/document_...', 'r')\n#1 /var/www/loris/modules/document_repository/php/files.class.inc(129): Laminas\\Diactoros\\Stream->__construct('/data/document_...')\n#2 /var/www/loris/src/Middleware/UserPageDecorationMiddleware.php(233): LORIS\\document_repository\\Files->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#3 /var/www/loris/src/Middleware/PageDecorationMiddleware.php(56): LORIS\\Middleware\\UserPageDecorationMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\document_repository\\Files))\n#4 /var/www/loris/php/libraries/NDB_Page.class.inc(696): LORIS\\Middleware\\PageDecorationMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\document_repository\\Files))\n#5 /var/www/loris/php/libraries/Module.class.inc(412): NDB_ in /var/www/loris/vendor/laminas/laminas-diactoros/src/Stream.php on line 345, 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to the front page of the module
2. Click on one of the files
3. See error

**What did you expect to happen?**
For the file to open or download.

**Comment by christinerogers** [comment]
Hi @h-karim  which branch/version of Loris are you on? 
e.g. will this be an issue in Loris 23.0.1?

**Comment by h-karim** [comment]
@christinerogers I was able to reproduce this bug on the master and the 23.0 release branches (I'll add this to the description)

**Comment by christinerogers** [comment]
Thanks @h-karim  for confirming the branches it's on.  Does it occur on Chrome & Firefox both, after clearing cache etc? 
What have you found in investigating the source and its recency --
* Was this a bug found in 23 testing?  ([e.g. here](https://github.com/aces/Loris/projects/19#card-21296699)). or in previous issues? 
* If yes - was there a fix and did it fail? 
* If no, check test plan: should it have been caught?  (yes)
* Can you reproduce it on the Test VM?  
If no, would make it a new bug (but if yes, double-check when the Test VM was last updated). 
* What's changed around this code on the branch -- since the last testing round

**Comment by h-karim** [comment]
This issue needs to be further broken down. 

1. The first error log message mentioned in the description is because the query here :  
https://github.com/aces/Loris/blob/master/modules/document_repository/php/files.class.inc#L116-L120 is returning multiple rows for a single file.
 The possibility of uploading more than one file with the same name is problematic. Currently on my sandbox, I have the following files uploaded: 
uploaded_by | record_id | File_name
------------------|--------------|------------------
admin       |         1 | bread-breakfast-knife.jpg        
admin       |         2 | bread-food-healthy-breakfast.jpg 
 admin       |         3 | bread-food-healthy-breakfast.jpg 
 admin       |         4 | test.txt                         
 admin       |         5 | test.pdf                        
 admin       |         6 | test.pdf                        
 admin       |         7 | test.pdf                        
 admin       |         8 | test.txt                         
 admin       |        10 | test_test.txt                    
 admin       |        11 | test_test.txt                    
 admin       |        12 | test_test.txt                    
  
Validation needs to be introduced to prevent duplicate filenames if we want to use the filename as a uniquer identifier in the query.

I'm still investigating the second error log message (invalid file stream exception).

**Comment by h-karim** [comment]
The duplicate file names are due to the raisinbread install. I'm closing this issue and opening one for raisinbread. I'm also opening one for the invalid file stream exception.
