### ISSUE TITLE
Error creating LORIS user when generating a password

### ISSUE THREAD

**Issue by ejoh1101** [aces/Loris#6802]
**Describe the bug**
When adding a new LORIS user, page returns error "Your password cannot be your email" when both "Make user name match email address" and "Generate new password" are checked.  

**To Reproduce**
Create new user from User Accounts module. Check options "Make user name match email address" and "Generate new password". Fill the rest of the candidate information and click "Save". 

![Error Screenshot](https://user-images.githubusercontent.com/23503259/86173687-f772e280-bae5-11ea-8217-0afe9c1118c6.png)

**What did you expect to happen?**
username should become email and a random password should be generated. 

**Browser Environment (please complete the following information):**
- OS: Mac
- Browser: Chrome Version 83 

**Server Environment (if known):**
- LORIS Version: 23.0.1
- Linux distribution and Version: RHEL 7
- MySQL/MariaDB Version: MariaDB 10.3

**Additional context**
If I manually enter the email as the username it will generate a password and save successfully.

**Comment by laemtl** [comment]
This should be fixed with PR #6803
