### ISSUE TITLE
Fix "doubleDataEntryDiffIgnoreColumns" class variable reference

### ISSUE THREAD

**Issue by driusan** [aces/Loris#6808]
A reference to `_doubleDataEntryDiffIgnoreColumns` variable was incorrectly renamed in #6179. (See comment from @lingma). It should be fixed.

**Comment by lingma** [comment]
#6809 will fix this issue

**Comment by christinerogers** [comment]
@driusan should this be closed?

**Comment by lingma** [comment]
The fix #6179 has been merged long ago. I think yes, the issue should be
closed.

**Comment by driusan** [comment]
Fixed by #6809
