### ISSUE TITLE
OutputWrapper will always throw an exception when checking the Log config setting

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6811]
The code should check the full path, not the partial path.

**Comment by driusan** [comment]
what do you mean "full path" and "partial path"?

**Comment by johnsaigle** [comment]
Right now it's checking if the config setting `Log` is a dir. It never will be because `Log` is meant to be a partial path e.g. `tools/logs/`. In the linked PR the check is changed to check `base` concatenated to `Log` which should fix the issue.
