### ISSUE TITLE
[Permissions] Update project filter based on  user access

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6829]
The way the project filter is populated should be modified accross all modules, to display project in the filter only if the current user has access to it (See #6729 for an example).

**Comment by laemtl** [comment]
./tools/CouchDB_Import_Demographics.php:        $projects = \Utility::getProjectList();
./modules/electrophysiology_browser/php/electrophysiology_browser.class.inc:        $projectList      = \Utility::getProjectList();
./modules/api/php/endpoints/projects.class.inc:                \Utility::getProjectList()
./modules/media/php/media.class.inc:            'projects'      => \Utility::getProjectList(),
./modules/conflict_resolver/php/resolved_conflicts.class.inc:        $projectList      = \Utility::getProjectList();
./modules/conflict_resolver/php/conflict_resolver.class.inc:        $projectList      = \Utility::getProjectList();
./modules/statistics/php/stats_behavioural.class.inc:        $allProjectList = \Utility::getProjectList();
./modules/statistics/php/stats_mri.class.inc:        $allProjectList = \Utility::getProjectList();
./modules/statistics/php/stats_demographic.class.inc:        $allProjectList = \Utility::getProjectList();
./modules/statistics/php/module.class.inc:            $projects = \Utility::getProjectList();
./modules/imaging_qc/php/imaging_qc.class.inc:        $projectList  = \Utility::getProjectList();
./modules/user_accounts/php/user_accounts.class.inc:            'projects'         => \Utility::getProjectList(),
./modules/user_accounts/php/edit_user.class.inc:        $projects       = \Utility::getProjectList();
./modules/configuration/php/project.class.inc:        $projectList    = \Utility::getProjectList();
./modules/configuration/ajax/updateProject.php:$ProjectList   = Utility::getProjectList();
./modules/behavioural_qc/php/behavioural_qc.class.inc:        $projectList = \Utility::getProjectList();
./modules/imaging_browser/php/imaging_browser.class.inc:        $projectList      = \Utility::getProjectList();
./modules/candidate_list/php/candidate_list.class.inc:        $list_of_projects = \Utility::getProjectList();
./modules/new_profile/php/new_profile.class.inc:        $projects = \Utility::getProjectList();
./modules/login/php/requestaccount.class.inc:            ["" => "Choose your project:"] + \Utility::getProjectList(),
./modules/login/php/requestaccount.class.inc:            $projectList = \Utility::getProjectList();
./modules/mri_violations/php/mri_violations.class.inc:        $list_of_projects = ['' => 'Any'] + \Utility::getProjectList();
./modules/mri_violations/php/resolved_violations.class.inc:        $list_of_projects = \Utility::getProjectList();
./test/unittests/UtilityTest.php:            Utility::getProjectList(),
./php/libraries/Candidate.class.inc:        $ProjectList = Utility::getProjectList();

**Comment by laemtl** [comment]
@christinerogers It seems like Utility::getProjectList(); is used  to get a list of all the project.
What about an optional parameter \User user, which, if provided, filter projects the user has permission to?

**Comment by charliehenrib** [comment]
@driusan I don't think this is an issue anymore. It should be closed.

**Comment by driusan** [comment]
ok
