### ISSUE TITLE
[permission] Fatal error when user is missing some permissions

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6830]
TODO: find which missing permission causes the problem

[Thu Jul 09 19:46:16.914426 2020] [php7:notice] [pid 12719] [client 127.0.0.1:44886] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to LORIS\\Middleware\\PageDecorationMiddleware::__construct() must be an instance of User, null given, called in /var/www/html/loris/src/Middleware/ExceptionHandlingMiddleware.php on line 47 and defined in /var/www/html/loris/src/Middleware/PageDecorationMiddleware.php:18\nStack trace:\n#0 /var/www/html/loris/src/Middleware/ExceptionHandlingMiddleware.php(47): LORIS\\Middleware\\PageDecorationMiddleware->__construct(NULL)\n#1 /var/www/html/loris/htdocs/index.php(49): LORIS\\Middleware\\ExceptionHandlingMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\Router\\BaseRouter))\n#2 {main}\n  thrown in /var/www/html/loris/src/Middleware/PageDecorationMiddleware.php on line 18

**Comment by driusan** [comment]
How did you determine this is caused by permissions?

**Comment by laemtl** [comment]
Because it happened after editing permissions. It 'ssolved, I was missing new permssions in my DB.
