### ISSUE TITLE
[UserAccounts] auto-generated password is way too long

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#6843]
Found on an instance running LORIS 23. 
The password sent to users when an account-request is granted,  is... exceptionally long. 

To reproduce: 
* Request an account, wait for an admin to approve it, get the auto-generated credential in the welcome email (below).

Probably also reproducible by trying: 
- create a new user account and send their auto-generated password by email
- auto-update a user's password from the User Accounts module
- Use the "forgot your password?" feature from the login page. 

```
Your account details have changed:
User name: -redacted-
Password:  qnGA51dOjI1rY7JW5e60Wqb9E6bM7wQ22u0cY81nzVRnOIswV6ZajjUmKpLyITi6

You may log in at -redacted-

You will be prompted to change your password after logging in.

Thank you,

LORIS Team
```

**Comment by ridz1208** [comment]
16 chars or 100 chars... I doubt anyone is typing it !

**Comment by christinerogers** [comment]
ok closing this
