### ISSUE TITLE
router doesn't work well in master branch

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6850]
**Describe the bug**
When I tried to access any link when I worked on some code in the master branch, the site will report the URL not found. I ever tried to reinstall the site, but then the installer failed. I fixed the installer, still no access to pages except the base url.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to any link from menu, like candidate_list, it will report error.

**What did you expect to happen?**
Normal behavior for a site

**Browser Environment (please complete the following information):**
- OS: Ubuntu 20.04
- Browser [e.g. chrome, firefox] both
- Version: master

**Server Environment (if known):**
- MySQL/MariaDB Version: MySQL 8

**Comment by driusan** [comment]
Might be related to #6846 .. did you run make to ensure the autoloader is up to date with any classes that need to be found?

**Comment by lingma** [comment]
Yes, make was run every time.

**Comment by lingma** [comment]
Found the problem, the config file has missed item.
