### ISSUE TITLE
New profile "create" button will never go ahead with 500 error reported

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6851]
**Describe the bug**
Create a new profile, then the "Create" button will stay there, with 500 error reported in fact.

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to LORIS\\Http\\Response\\JSON\\Created::__construct() must be of the type array, string given, called in modules/new_profile/php/new_profile.class.inc on line 111 and defined in src/Http/Response/JSON/Created.php:42

**What did you expect to happen?**
I remember the creation will return to a list, instead of staying there.

**Server Environment (if known):**
- LORIS Version: master branch

**Comment by lingma** [comment]
PR created

**Comment by driusan** [comment]
Duplicate of #6821
