### ISSUE TITLE
[user_accounts] Can't access the module user_accounts

### ISSUE THREAD

**Issue by spell00** [aces/Loris#6893]
**Describe the bug**
The User Accounts module in Admin -> User Accounts can't be accessed.

**To Reproduce**
1. Go to `https://<your-hostname>/user_accounts`
2. The page doesn't load and display the message `"An error occured while loading the page."`

![user_accounts_error](https://user-images.githubusercontent.com/32504294/89852479-ed201b80-db5c-11ea-9467-9e9c9a508b4a.png)

**What did you expect to happen?**
The User Accounts page should be displayed

**Comment by ridz1208** [comment]
@spell00 could you give more details on the error ? what do you see in the inspector of the browser? what do you see in the apache error_log?

**Comment by spell00** [comment]
I found the error, I had to refresh raisinbread. It seems I had to refresh raisinbread because of #6191.
Closing the issue.
