### ISSUE TITLE
Adapt libraries to allow for NULL date of birth

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#6894]
PR #5758 removed the soft validation making date of birth always required when creating a candidate. That change was approved by the LORIS group. Even though the changes to the new_profile module were made, other libraries and modules might still expect DOB to be a date rather than NULL.

Someone should investigate all the usages of the Date Of Birth and make sure that no errors get thrown when it is NULL.

Example: the Instrument class Calculate age function assumes that the DOB is not NULL, the function should be amended accordingly

**Comment by ridz1208** [comment]
@pierre-p-s why don't you take a stab at this

**Comment by pierre-p-s** [comment]
Issue: Battery does not get populated
=> Samir: Cant populate a battery without date of birth, send an error message

**Comment by ridz1208** [comment]
Issues:
 - Battery lookup will always return NO instruments (see query https://github.com/aces/Loris/blob/main/php/libraries/NDB_BVL_Battery.class.inc#L447)
 - IF we manage to get past battery population, Every instrument will get this:
     ![image](https://user-images.githubusercontent.com/15268287/141987676-163c8a0f-7106-4b26-9277-782394f27d2a.png)
    because of https://github.com/aces/Loris/blob/caab2a9843dce96e2f087f0c8712810b99ede89b/php/libraries/Utility.class.inc#L46
 - other potential errors
    ![image](https://user-images.githubusercontent.com/15268287/141988625-fbc9ab6d-673c-4c7f-9f6d-7b1806124899.png)

**Comment by ridz1208** [comment]
Critical to release removed by request of the roadmap meeting attendees

**Comment by driusan** [comment]
It has been 3 years. Bugs for places that are affected should have been filed individually if found. This ticket isn't really actionable.
