### ISSUE TITLE
[Help Doc] No help document for the instruments module

### ISSUE THREAD

**Issue by AlexandraLivadas** [aces/Loris#6906]
There is no help document for the instruments module. 

When you navigate to a data entry page for a specific timepoint's instrument and click on the `?` button, there is a `No help available for instruments` message:
<img width="1434" alt="Screen Shot 2020-08-12 at 6 00 57 PM" src="https://user-images.githubusercontent.com/35467361/90072843-1dcf9480-dcc6-11ea-8c14-955227318d39.png">

**Comment by driusan** [comment]
The instruments module is just a module that delegates to the instrument, the help on it should be using the help from the help module. Is it working correctly when there's help content added in the help editor?

**Comment by AlexandraLivadas** [comment]
@driusan My other PR #6907 adds data to the help editor for the BMI instrument. However, when I go to data entry for a BMI instrument even with data in the help editor, the same "No help available for instruments" message appears here.
