### ISSUE TITLE
[docs:UserAccts] Password rules as displayed in the front end for users need updating

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#6914]
Passwords are required to be significantly longer since the 23 release, and the Password rules displayed in User Accounts for the (Admin)user haven't been updated. 

The poor admin who tries to follow the rules printed in User Accounts Add/Edit User page will not successfully be able to save a password. 

Haven't checked but I would also suspect the password rules printed in the Reset Password feature would need an update too.

**Comment by christinerogers** [comment]
Haowei i think this could be a nice easy bug in the text we show front-end users. 

@laemtl can you guide him through the process? 

First steps in looking into this bug will include: 
-[ ] find the recent PRs that modified the password rules, but forgot to actually update what we *say* the password rules are in the front-end. 
-[ ] dig a little into those PRs, and test yourself what the current password rules actually are
-[ ] Update the password rules we display in the User Accounts module, keeping in mind they should be simple and clear for the user/reader
-[ ] Triple-check (with our help) for any other places in LORIS where password rules are (or maybe should?) be printed -- e.g. User/My Preferences (where users reset their own passwords), or the "Forgot my password" feature off the Login page.

**Comment by laemtl** [comment]
One easy way to understand the different rules is to look at the code [here](https://github.com/aces/Loris/blob/62a09948d516c3aed3c88022f545240cf2457516/modules/my_preferences/test/my_preferencesTest.php#L299), [here](https://github.com/aces/Loris/blob/62a09948d516c3aed3c88022f545240cf2457516/php/libraries/Password.class.inc#L33) and [here](https://github.com/aces/Loris/blob/62a09948d516c3aed3c88022f545240cf2457516/modules/my_preferences/php/my_preferences.class.inc#L11).

**Comment by haoweiqiu** [comment]
Hi @christinerogers and @laemtl,
Based on your instructions, I looked into the password rules.
The recent PRs relating to password rules changes (for Release 23.0.0) are: #6705, #6615, #6611, #6510, #6341, #6330, #5974, and #5958. However, I did not find any PRs relating to password rules changes for Release 23.0.1, 23.0.2, and 23.0.3 so far.
The recent PR that modified the password rules is #5974. 
The classes that mentioned the password rules (for LORIS Frontend) are: [form_passwordexpiry.tpl](https://github.com/aces/Loris/blob/main/modules/login/templates/form_passwordexpiry.tpl), [form_my_preferences.tpl](https://github.com/aces/Loris/blob/main/modules/my_preferences/templates/form_my_preferences.tpl), and [form_edit_user.tpl](https://github.com/aces/Loris/blob/main/modules/user_accounts/templates/form_edit_user.tpl).
Based on #5974 and my personal experience add/edit the password in LORIS, I think that the current password rules listed in Frontend generally explain all the password rules. However, I found that the current LORIS password rules did not mention the use of Zxcvbn library, should I improve and mention this?
Thank you very much!

**Comment by laemtl** [comment]
If the error message is self explanatory I think it's fine.

**Comment by haoweiqiu** [comment]
@laemtl I think that this issue could be closed?

**Comment by christinerogers** [comment]
Hi Haowei, just to clarify -- 
What is the new length of password that must be entered when changing a password in User Accounts? 
Does the password-rule  instructions to usersaccurately reflect this? 

That's what this issue is asking to resolve.

**Comment by haoweiqiu** [comment]
@christinerogers I tried to add a new user and the minimum length of password was 8. I think that the current password rules to users generally reflect the actual password rules.

**Comment by christinerogers** [comment]
Hi @haoweiqiu -- you think or you're sure?  if you're sure, we can close this issue.

**Comment by laemtl** [comment]
@christinerogers I confirm.

**Comment by haoweiqiu** [comment]
@christinerogers I think I'm sure.

**Comment by christinerogers** [comment]
closing this issue.

**Comment by laemtl** [comment]
@christinerogers, @haoweiqiu  After further investigation, [zxcvbn](https://lowe.github.io/tryzxcvbn/) can reject passwords of length 8 or longer if their score is not at least 3. Less rejection happens with password of length 10. What about increasing the suggested length to 10?
