### ISSUE TITLE
[candidate dashboard] Unable to access any candidate dashboard

### ISSUE THREAD

**Issue by HenriRabalais** [aces/Loris#6951]
**Describe the bug**
When trying to access the candidate dashboard via `New Access Profile (Beta)`, I am unable to access any candidate's information.

<img width="1861" alt="Screen Shot 2020-09-02 at 13 49 44" src="https://user-images.githubusercontent.com/7550451/92018468-31997400-ed23-11ea-94db-1fa0fba4b9f5.png">

This was found while trying to test the widgets for the Media module.

**Comment by driusan** [comment]
Can you turn on sandbox mode so that it uses the non-minified React and gives you the actual error?

**Comment by HenriRabalais** [comment]
I'm not familiar with how to do that. Are there instructions somewhere I can reference?

**Comment by driusan** [comment]
in `project/config.xml` change the value of the `<sandbox>` tag from "0" to "1" (or add `<sandbox>1</sandbox>` somewhere in the config).. how do you usually debug react problems if React doesn't give you the error?

**Comment by HenriRabalais** [comment]
Thanks! 

Ummm when I'm developing I usually try and trace the last changes I've made and sift through all my code to see where I've done something that React would be mad about lol.
