### ISSUE TITLE
API can't login with curl  --- "error": "Unacceptable JWT key"

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#6953]
**Describe the bug**
A clear and concise description of what the bug is

**To Reproduce**
$ curl https://<your-hostname>/api/v0.0.3/login -d '{"username": "<your-username>", "password": "<your-password>"}'
The expected response is:
{"token": "<a-really-long-string>"}

But the response is :
"error": "Unacceptable JWT key"

**Comment by ridz1208** [comment]
@kongtiaowang you need to fix the configuration of the JWT in the config table.

set it to `This is not S3cret anymore!` if you want

**Comment by kongtiaowang** [comment]
@ridz1208 I have tried to remove S3cret. There is no expected response.

**Comment by driusan** [comment]
how long is the JWTKey that you changed it to?

**Comment by ridz1208** [comment]
I have just tested it on test and it's working fine
