### ISSUE TITLE
[User Accounts] Unclear step in TestPlan

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#6954]
**Describe the bug**
The testplan specifies to `Ensure adding a new user with the same name as an existing user fails.` What is meant by this is that no users with the same **username** should be added succesfully.

**Comment by driusan** [comment]
I think the test plan is referring to the username, not the first/last name.. this might just need a test plan update to clarify.

**Comment by CamilleBeau** [comment]
> I think the test plan is referring to the username, not the first/last name.. this might just need a test plan update to clarify.

Thanks! I edited this issue to reflect that.
