### ISSUE TITLE
[Battery Manager] Min Age and Max age validation

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6955]
- Min age can be greater than max age.
- When a negative Min/Max age is entered, the error message is too vague (Could not add entry to the Test Battery)

## To reproduce
* Click on New Test
*  Fill in a Max Age and Min age such that Min is greater than Max
* Notice the absence of errors

## Expected behaviour
We expect an error to notify the user that the values are not valid.

**Comment by HenriRabalais** [comment]
Will take a look!
