### ISSUE TITLE
[Battery Manager] Console errors

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6957]
A few errors are logged in the console, without breaking any functionality:
- Warning: Failed prop type: Invalid prop `onSubmit` of type `function` supplied to `Modal`, expected `object`.
    in Modal (created by BatteryManagerIndex)
    in BatteryManagerIndex react.development.js:1641:17
- Uncaught (in promise) Could not add entry to the Test Battery (when error in form)
- Uncaught (in promise) undefined when submit the form with no filled fields
- Error 500 with testendpoint/ when submit the form with Instrument order > 127

**Comment by ridz1208** [comment]
i'm seeing a 500, how did that not break functionality ?

what value did you submit for instrument order ? cause i see the error is that instrument order > 127

**Comment by laemtl** [comment]
I think it,s because the 550 error happens in a async call. I submitted 300 for the instrument order I think.

**Comment by HenriRabalais** [comment]
Will take a look!
