### ISSUE TITLE
[Battery Manager] Form validation problem

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6958]
If someone submits a new empty entry (no data filled in), it triggers red marks on form inputs. 
They do not disappear if another entry is loaded by clicking the edit button, reloading the same form with the red marks with the new data which is valid.
<img src="https://user-images.githubusercontent.com/32041423/92124231-8264a780-edcb-11ea-9369-ddc71af424e5.png" width="400" />

**Comment by HenriRabalais** [comment]
Seems like the object holding the errors is the reset upon form closure...
