### ISSUE TITLE
[login] Test instructions

### ISSUE THREAD

**Issue by pierre-p-s** [aces/Loris#6960]
In the request account test plan: 
- Instruction 6: instead of user_accounts and user_accounts_multisite use the name on the front end (User Management and Across all sites create and edit users) or mention it in parentheses
- Instruction 12: typo at the end of instruction

**Comment by ridz1208** [comment]
add it in parenthesis

**Comment by driusan** [comment]
What is the "typo at the end of instruction"? There are 3 markdowns in the test directory and I'm not sure which one you're talking about.
