### ISSUE TITLE
[login] pending accounts at DCC do not show on the dashboard (they should)

### ISSUE THREAD

**Issue by pierre-p-s** [aces/Loris#6962]
**Describe the bug**
In the instruction 6 of the request account test plan, it says that the new account request should appear in the dashboard but I am not seeing anything

Edit(Rida) the `DCC<>1` condition should be removed

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Request an account
2. On the admin account, go to the dashboard, I could not see the request for the account being listed

**Comment by driusan** [comment]
Where are you looking? I believe it should be under "Pending Accounts" (or something along those lines..) in the My Tasks widget.

**Comment by pierre-p-s** [comment]
No it doesnt appear in my task I checked. Attached a screen shot of the admin account home page after I requested an account

![Screen Shot 2020-09-03 at 9 27 28 PM](https://user-images.githubusercontent.com/57676906/92189298-4d3c7180-ee2c-11ea-983f-29123e0ed35a.png)

**Comment by driusan** [comment]
Yeah, that definitely looks like it's missing..

It looks like the query in the code is:

```
SELECT COUNT(DISTINCT users.UserID) FROM users
                        LEFT JOIN user_psc_rel as upr ON (upr.UserID=users.ID)
                    WHERE users.Pending_approval='Y'
                        AND (upr.CenterID <> 1 OR upr.CenterID IS NULL)"
```

What CenterID is the requested account at?

**Comment by pierre-p-s** [comment]
Oh I used the Data coordinating center I think it has ID 1

**Comment by driusan** [comment]
We should probably either remove that restriction or remove the option from the request account page to select DCC.

**Comment by ridz1208** [comment]
@pierre-p-s have you retested this with another site ?

**Comment by pierre-p-s** [comment]
> @pierre-p-s have you retested this with another site ?

@ridz1208 I retested with other sites and it worked.

**Comment by ridz1208** [comment]
This used to be expected functionality, not anymore

**Comment by driusan** [comment]
We should remove the not DCC from the query.
