### ISSUE TITLE
[datadict] Clear filters

### ISSUE THREAD

**Issue by pierre-p-s** [aces/Loris#6965]
**Describe the bug**
Instruction 6 of test plan: the clear filters button just clears the filters. The test plan should be updated I think except if it is not the behavior expected

**Comment by driusan** [comment]
?

**Comment by pierre-p-s** [comment]
> ?

Instructions do not match the behaviour of the module but it gives the correct result.

**Comment by ridz1208** [comment]
@pierre-p-s 

step 6 reads: `Check that pushing the Clear button sets the Description search field to 'All', the Instruments search field to 'All instruments', clears the search keyword text field and performs a search with these criteria. Validate the results.`

Can you clarify which part of this doesn't happen ? does it not `performs a search with these criteria` ? and what do you mean by `but it gives the correct result`

**Comment by pierre-p-s** [comment]
> @pierre-p-s
> 
> step 6 reads: `Check that pushing the Clear button sets the Description search field to 'All', the Instruments search field to 'All instruments', clears the search keyword text field and performs a search with these criteria. Validate the results.`
> 
> Can you clarify which part of this doesn't happen ? does it not `performs a search with these criteria` ? and what do you mean by `but it gives the correct result`

It does not perform the check with these criteria. Instead of setting the description field to 'All', the instrument search field to 'All instruments', it just clears them and sets them to null. The wording in test plan is confusing compared to the actual behaviour of the search filter.
