### ISSUE TITLE
[datadict] Edit description

### ISSUE THREAD

**Issue by pierre-p-s** [aces/Loris#6966]
**Describe the bug**
~~When giving myself the edit permission, there was no edit button as mentionned in instruction 7 of the test plan~~
After talking to @ridz1208, he showed me how to edit the description (by clicking on the text of the description). However, the test instruction are not very clear, maybe we should mention how to edit or change the description in the table to a text field that is more visible.

**Comment by christinerogers** [comment]
question @pierre-p-s  -- should the Help text for the module also include this update?
