### ISSUE TITLE
[Help editor] Test plan update

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6969]
`17. Check filter expansion. [Manual Testing] `is obsolete and needs to be removed.
Also, depending on what will be decided in #5185, mentions about `Last Updated date` may be obsolete too.
 
Related to #5185

**Comment by ridz1208** [comment]
@laemtl can you check if you can deal with 5784 as well ?

**Comment by driusan** [comment]
#6970 (merged) says it fixes this
