### ISSUE TITLE
[user_accounts] New user not sent email / prompted for new password

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#6971]
**Describe the bug**
Written in TestPlan:

> 12. Check that if creating a new user an email is sent to him/her (requires email server). Also check that when a new user is logging in for the first time he/she is asked to change his/her password.

An email is only sent if the "Send email to user" button is selected. When a new user is logging in for the first time, they are not prompted to change their password. This is either a bug, or an outdated testplan.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Create a new user without selecting "Send email to user"
2. See that no email is sent to user
3. Create a new user using an email that you have access to and select "Send email to user" (an email should be sent)
4. Log in as this new user for the first time. Notice that you are not prompted to change password.

**Comment by driusan** [comment]
I think the not being prompted is a bug.

**Comment by laemtl** [comment]
@CamilleBeau I just tested and get redirected to the Update password page.

**Comment by laemtl** [comment]
@CamilleBeau  I just tested and was redirected to the `Update password` page.

**Comment by CamilleBeau** [comment]
@laemtl Strange! On my dev I am still getting no password prompt

**Comment by laemtl** [comment]
@CamilleBeau Can you paste the `users` table entry here?

**Comment by CamilleBeau** [comment]
This is from the `users` table after making a new user and before logging in with that user
![image](https://user-images.githubusercontent.com/51176779/94034553-28cf1780-fd90-11ea-9719-8ac3ce9cebcc.png)

**Comment by laemtl** [comment]
Id the user with ID=2 is the one you request an account for, I noticed 2 problems: PasswordChangeRequired is not set to 1, and account_request_date is NULL. Not sure exactly why, but I do not have that issue on my local VM. I will try on the test VM to be sure.

**Comment by laemtl** [comment]
Tested and it also works on the test VM.

**Comment by CamilleBeau** [comment]
@driusan Is the new user supposed to be prompted for a new password when logging in _always_ or only when "generate password" is selected while creating the user?

**Comment by CamilleBeau** [comment]
I just tested this again on the updated code. This issue is persisting in that a new user is not always sent an email (only when if "Send email to user" is selected). I'm not sure if this is intended or not?

**Comment by ridz1208** [comment]
given the name of that checkbox, I'm gonna say yes its intended. but if I remember correctly if you check the generate password box, you have to select the send email to user to be able to save

**Comment by CamilleBeau** [comment]
> @CamilleBeau Do you have time to take care of this?

Yes, no problem!
