### ISSUE TITLE
[user_accounts] Examiners with same name removed from table

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#6973]
**Describe the bug**
If a new user is set as an examiner who has the same first and last name as an examiner that already exists, the pre-existing examiner is removed from the `examiners` table, replaced by the new one.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Create a new user with the exact same first / last name as a pre-existing examiner, and set this user as an examiner
2. look at the examiners table and notice that the first examiner is no longer there, but the newly created examiner is.

**Comment by ridz1208** [comment]
@jesscall don't start working on this just yet, let's discuss it first.

**Comment by CamilleBeau** [comment]
Resolved
