### ISSUE TITLE
[user_accounts] Conflicting Steps in TestPlan

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#6974]
**Describe the bug**
Testplan has two steps that contradict each other:

> Step 2. The User Module should display only users belonging to the same site as the active user, unless they have the permission Across all sites create and edit users.
> Step 5. The empty option in the site filter should display users from all sites, even if they are different from the active user.

Step 5 does not reflect the current intended functionality.

**Comment by driusan** [comment]
FYI, because it's markdown GitHub automatically renumbered your step 5 to "3".. I'm not sure if there's any way to fix that.

**Comment by CamilleBeau** [comment]
> FYI, because it's markdown GitHub automatically renumbered your step 5 to "3".. I'm not sure if there's any way to fix that.

Thank you! I added in "Step" before.
