### ISSUE TITLE
[module_manager] Able to edit without permission

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#6976]
**Describe the bug**
Specified in testplan:

> 8. With the edit permission, access the page. From the backend or another tab, remove the edit permission and modify the "Active" status of a module. Verify that instead of a success message you received an error message and the module status was not modified.

Following these steps, no error message was received, and the module status was changed in the `modules` table. Furthermore, the user still had access to edit the modules (without the edit permission) continuously after reloading the page from the success message.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. With Edit permission, access module manager
2. From the admin in another browser or in the back end, remove the edit permission for this user and leave the view permission (if in browser, make sure to save)
3. Continue to edit the "Active" status from the user who no longer has edit permission (don't reload)
4. See that no error message is given, and that you are successfully able to edit & continue editing other modules.

**Comment by ridz1208** [comment]
@CamilleBeau step 4 reads `See error`

but above you say `no error message was received` ?

**Comment by CamilleBeau** [comment]
> @CamilleBeau step 4 reads `See error`
> 
> but above you say `no error message was received` ?

Yes, no error message was received. I edited to be more clear.

**Comment by driusan** [comment]
I'm not able to reproduce this.. are you sure you don't have the superuser permission?

**Comment by CamilleBeau** [comment]
> I'm not able to reproduce this.. are you sure you don't have the superuser permission?

I tested this again and it did not happen. I will close the issue.
