### ISSUE TITLE
[module_manager] TestPlan needs detail

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#6977]
**Describe the bug**
TestPlan should include steps on testing the filters, ordering, page navigation, downloading CSV, rows displayed.

**Comment by christinerogers** [comment]
> steps on testing the filters, ordering, page navigation, downloading CSV, rows displayed

Adding more details for @haoweiqiu :  
Copy/adapt from [Imaging QC test plan](https://github.com/aces/Loris/blob/main/modules/imaging_qc/test/TestPlan.md) the following points : 3, 4, 5, 6, 7, 8, 10, 11.  
These points will cover the testing points @CamilleBeau is requesting.

**Comment by christinerogers** [comment]
@CamilleBeau - very few test plans actually include all these steps.  i'll bring it up for loris meeting discussion, i think we removed data table basic functionality testing points at some point.

**Comment by christinerogers** [comment]
per discussion today in the Loris meeting -- I'll close this ticket and instead create an issue for a generic manual test plan across all modules. 
this generic one can be added as a link at the top of every module's test plan.
