### ISSUE TITLE
[dataquery] TestPlan needs updated

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#6980]
**Describe the bug**
Testplan 1) describes `data_dict` permission that doesn't exist in database.

**Comment by driusan** [comment]
I don't see any references to it in step 1?

"1. Ensure the DQT module loads only for a user that has the permission 'View Data Query Tool' (`dataquery_view`)"

**Comment by maltheism** [comment]
Unsure what happened since it's not there.
