### ISSUE TITLE
[Issue Tracker] watching checkbox doesn't work 

### ISSUE THREAD

**Issue by jftunteng** [aces/Loris#6985]
**Describe the bug**
I'm unable to check the 'Watching' checkbox in the issue tracker module

**Comment by ridz1208** [comment]
Can you provide more info, what do you mean "unable" did the batteries in your mouse die ? did your computer shut down? does the checkbox suddenly move when you try to click it?

**Comment by jftunteng** [comment]
@ridz1208 the checkbox was there but it wasn't clickable. if I tried clicking on it it wouldn't do anything so the actual checkbox functionality wasn't working
