### ISSUE TITLE
[instrument_manager] Bug when uploading instrument.

### ISSUE THREAD

**Issue by racostas** [aces/Loris#6986]
**Describe the bug**
An error is triggered when trying to upload an instrument. 

**To Reproduce**
1. Log into the system with a user with enough privileges to upload an instrument.
2. Go to `MainMenu-> Admin -> Instrument Manager`
3. Go to the` Upload tab.`
4. Try to upload and instrument file (for example: https://github.com/aces/Loris/blob/main/test/instruments/test_all_fields.linst)
5. An error is triggered.

![image](https://user-images.githubusercontent.com/37309344/92285584-a65ee080-eed2-11ea-95e8-bb470d63c80b.png)

**What did you expect to happen?**
The instrument to be uploaded.

**Additional context**
Issues and PRs that could be related:
#5352
#6913
#6932

**Comment by driusan** [comment]
Can you confirm that #6932 fixed this and close if appropriate?

**Comment by racostas** [comment]
fixed by #6932
