### ISSUE TITLE
[Candidate parameter] Current consent does not show up

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#6992]
**Describe the bug**
I accessed the consent tab of the candidate parameter module for MTL001. When I checked the consent history, I saw that the latest modification done was setting the study consent to 'Yes' on 2015-12-31 but all the fields on the tab are empty...

**Comment by ridz1208** [comment]
@nicolasbrossard this might be an RB inconsistency between the history and the dat table. if the data is in the SQL table but does not show up then its a bug. but if theres just inconsistencies between the history table and the candidate_consent table then its an RB issue.
