### ISSUE TITLE
[Candidate parameter] DoB and DoD formats ignored

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#6994]
**Describe the bug**
In the configuration module, I set both the DoB and DoD formats to `dMY`. When I edit the DoB and DoD in the candidate parameter module, the dates are always saved and displayed in YMd format.

**Comment by ridz1208** [comment]
thats because not all formats are supported. last itme we spoke about it we had decided to convert that into a dropdown. I dont think it was ever done

**Comment by ridz1208** [comment]
@jesscall can you investigate this with Nic ?

**Comment by jesscall** [comment]
@ridz1208 @nicolasbrossard There was already a change that turned the date format to a dropdown #6719

**Comment by SantiagoTG** [comment]
This is still an issue. If the 'Date format' is change to d-m-Y in the 'Configuration' module, the date format does not change for any of the dates on the 'Candidate Information' tabs.
