### ISSUE TITLE
[Behavioural Quality Control] Behavioural Feedback tab displays incorrect cases

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#6999]
When accessing the 'Behavioural Quality Control' module, there will be 46 cases under the 'Behavioural Feedback' tab. However, when filtering for a given instrument, the 'Behavioural Feedback' tab will no longer display any of the initial, instead will display 'fixed' cases that do not correspond to the filtered instrument. ie. The 'Behavioural Feedback' will display cases for the 'BMI Calculator' regardless of the filter used for instrument ( in particular 3 'Roma' cases). 

Cases are unique to site 'Roma' (selecting any other site won't display cases for other sites and will filter out the 'Roma' cases). Filtering by site, visit label or project will filter the above-mentioned cases, but does not display any other cases (zero cases being displayed). When selecting the filter for 'BMI Calculator', there will be 2 more Roma cases added that correspond to 'BMI Calculator'.

All feedback level displayed are at the instrument level and for the 'BMI Calculator'. When checking on a given candidates, feedback level for all cases (initial and 'Fixed' cases) are found at the profile page, even though the 'Behavioural Feedback' tab has the feedback level at the instrument level. 

Any new feedback created at the visit level is not displayed or counted when accessing the 'Behavioural Quality Control' module (only moment where 'All instruments' is set as instrument filter). No new feedback can be created at the instrument level (#6998). Given there is no pagination tool for the 'Behavioural Feedback' tab (#6997), as well as the 'All instruments' filter leading to an error (#6946), can't explore further details of this bug.

**Comment by maltheism** [comment]
@ridz1208 the PR https://github.com/aces/Loris/pull/5836 should be merged because I think this issue is corrected by it.
