### ISSUE TITLE
[Document Repository] Unable to upload files  

### ISSUE THREAD

**Issue by jftunteng** [aces/Loris#7001]
**Describe the bug**
Getting an error (screenshot below) when trying to upload a file in Document Repository. I've tried uploading jpg, pdf, and txt documents. 
![Screen Shot 2020-09-07 at 4 47 26 PM](https://user-images.githubusercontent.com/22081216/92416383-339c7200-f12b-11ea-8e31-9ce02c8ddeda.png)

**Comment by kongtiaowang** [comment]
Please check that your upload folder has corrent write permisson or exists.
<img width="756" alt="屏幕快照 2020-09-23 上午10 24 29" src="https://user-images.githubusercontent.com/9876007/94026138-4ba8fe00-fd87-11ea-8abd-81622eefab19.png">
