### ISSUE TITLE
[publication] File deletion not working

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#7007]
**Describe the bug**
Testing item 11 of test plan fails. Deleting a file triggers swal. On clicking 'Yes, I am sure!', the file link remains. On clicking 'Submit' on the main form, and then refreshing, the link remains still.

<img width="796" alt="Screen Shot 2020-09-07 at 5 47 42 PM" src="https://user-images.githubusercontent.com/17415878/92418045-867a2780-f133-11ea-9807-c8e99b118bee.png">

**Comment by SantiagoTG** [comment]
No delete option available in new Publication module. Files selected can be removed by hitting 'Cancel' on the 'Browse' window.

Related to:  https://github.com/aces/Loris/issues/7877

**Comment by sruthymathew123** [comment]
Issues were fixed with PR referred in https://github.com/aces/Loris/pull/7091
