### ISSUE TITLE
[instrument_list] 'Start Visit Stage' successful but throws 404

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#7015]
**Describe the bug**
Starting a Visit Stage throws a 404 even though going back to instrument_list shows that the visit was indeed started

<img width="1192" alt="Screen Shot 2020-09-08 at 12 04 24 PM" src="https://user-images.githubusercontent.com/17415878/92500931-defd0380-f1cb-11ea-8cd3-c1ae784a1da9.png">

**To Reproduce**
Steps to reproduce the behaviour (attach screenshots if applicable):
1. Go to a visit with status 'Not Started'. 
2. Click on 'Start Visit Stage' in the left control panel
3. Fill in the form, and click on 'Start Visit'. You will get a 404: Not Found error page.
4. Click on your browser back button to return to instrument_list page for that visit. Hit refresh and you will see that the visit was started.

**What did you expect to happen?**
On successful visit started, you should get a 200 OK and this page

<img width="613" alt="Screen Shot 2020-09-08 at 12 14 23 PM" src="https://user-images.githubusercontent.com/17415878/92501802-06080500-f1cd-11ea-9b01-571ecb003218.png">

**Comment by driusan** [comment]
Can you remove the try/catch in src/Middleware/ExceptionHandlingMiddleware.php and see if you get the same error? I find that middleware often eats an exception and gives the wrong error page when I need to debug things.

**Comment by ridz1208** [comment]
@driusan could this have anything to do with #7019??

**Comment by driusan** [comment]
It's possible, or it's possible that it's similar exceptions thrown by different causes that are getting convert to a 404 by the middleware.

**Comment by xlecours** [comment]
Solved by https://github.com/aces/Loris/pull/6929
