### ISSUE TITLE
[bvl_Feedback] 500 error when create a feeback in an instrument

### ISSUE THREAD

**Issue by haoweiqiu** [aces/Loris#7029]
**Describe the bug**
I got a 500 internal service error when I tried to create a feedback in an instrument.
![image](https://user-images.githubusercontent.com/42322196/93087016-fcb3e800-f665-11ea-9763-66478ccd9b29.png)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'Access Profile'
2. Click on PSCID 'DCC090' in the list.
3. Click on Visit Label 'V1' in the list.
5. Click on 'MRI Parameter Form' instrument.
6. Create a feedback.
7. See 500 internal service error from console.

**What did you expect to happen?**
The feedback should be created.

**Comment by laemtl** [comment]
Thanks @haoweiqiu. Can you also add the related error_log line if any?

**Comment by haoweiqiu** [comment]
The related error log is shown below.
![image](https://user-images.githubusercontent.com/42322196/93142573-4deac880-f6b4-11ea-8901-3e9c436bbb09.png)

**Comment by laemtl** [comment]
Related to #5352
