### ISSUE TITLE
[instrument_list] gives DDE link when instrument is DDE: Null

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#7033]
Error on point 5 of this test plan: 
https://github.com/aces/Loris/blob/main/modules/instrument_list/test/TestPlan.md
There is a DDE link for an instrument for which DDE is not enabled. 

The aosi is marked `isDirectEntry : NULL` (not 1) in the `test_names` table: https://github.com/aces/Loris/blob/main/raisinbread/RB_files/RB_test_names.sql#L8

However a DDE link appears in the instrument_list for the aosi : 
https://test-loris-dev.loris.ca/instrument_list/?candID=587630&sessionID=1053

**Comment by driusan** [comment]
DDE has nothing to do with isDirectEntry. DirectEntry means it's a survey, DDE means it has Double Data Entry enabled.
