### ISSUE TITLE
[user_accounts] Requesting an account for a email already in use has no effect

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#7039]
If a user which has already an account (same email address) requests an account, a confirmation message is thrown (Thank you!
Your request for an account has been received successfully.) but nothing happens on the admin side. I such cases, I think we should notify the user than an account already exists (and suggests him to reset his password if forgotten).

**Comment by driusan** [comment]
This is by design for security reasons. A third party shouldn't be able to use the request account page to determine who has an account.
