### ISSUE TITLE
[MySQL patches] Tools to report missing patches / revert patches 

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#7060]
MySQL patches are convenient to submit database changes but LORIS lacks (to my knowledge) 2 important features:
- (1) report missing patches for a specific branch and apply them;
- (2) revert patches on branch change.

I would like to open a discussion on the possible solutions. One possible way to solve (1) is to log applied patches on a file and compare this log file with MIGRATION.md. (2) is more complex and requires the use of backups to be sourced for reversion, maybe with an additional file to submit with patches to list the name of altered tables. Sourcing all RB is an easier but not perfect solution as it takes a really long time. A really promising path is the use of [snapshots](https://mettle.io/blog/database-snapshots-via-homestead).

Related to #7059

**Comment by driusan** [comment]
I don't think this feature request is feasible.
