### ISSUE TITLE
[Instrument list] Send to DCC does nothing

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#7064]
Example: /instrument_list/?candID=696846&sessionID=2146
Clicking on Send to DCC does not produce any effect. The page reloads with the checkbox unchecked and no updated data.

--edit
I figured that it was missing required steps. In such case, validation errors should be displayed  to inform the user of the issue.

**Comment by zaliqarosli** [comment]
i think this ticket can also be closed? I found no bugs when testing #7786

**Comment by driusan** [comment]
Closing as per testing not finding the bug.. if it comes up again, feel free to re-open
