### ISSUE TITLE
[docs/RTD] fix auto-number bullets

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#7080]
Auto-numbered bullet points work [fine in GitHub](https://github.com/aces/Loris) but are not rendering ok in RTD : they start over and over as 1.. 2.. then later 1 .. 2...  
* Compare: how the install steps render in ((https://acesloris.readthedocs.io/en/latest/README.html)) vs. [in GitHub](https://github.com/aces/Loris)

This is important e.g for the install docs on RTD - users should be able to tell us the step number they got stuck at - as well as for the flow of our docs in general.

To do:
Investigate why the auto-numberering bullets aren't rendering in RTD.  
Is there any way to encode them in the markdowns so that they'll render ok in **both** GH and RTD? 
If you can find a solution (like an RTD plugin or alternate md styling), then: 
- [ ] propose, discuss, implement it --  if it's a styling update this means updating all the markdown files
- [ ]  write it up in a in a "how to write the docs" style guide for our markdowns (we'll work on this collaboratively)  

If there's no solution found, then as a last resort: 
- [ ] remove all the auto-number bullets across our markdowns and replace with manual numbering (hard-coded).
- [ ] make this a big visible guideline in a "how to write the docs" style guide 

Changes should apply across all the docs rendered in RTD including module specs.  Possibly only testplans are excluded.   This should be done for all the  (excluding probably only testplans).  Not ideal by any means, and painful to maintain. 

@haoweiqiu Would you have time to look into this in the coming week? 

cc @laemtl just fyi

**Comment by laemtl** [comment]
I fixed this issue for Alex.

**Comment by christinerogers** [comment]
Thanks @laemtl -- 
 Does this mean the fix is just to ensure the main Readme is [added to mkdocs.yml](https://github.com/aces/Loris/pull/6910/files#diff-305740239a690de1ec34b1235c87379e)?   
 
> Code block (```) are not supported in list items by the mkdocs version RTD uses. Return + Indenting fixed the issue.

Could you add this to the RTD Guide googledoc we've started in?  plus Anything else to know - Styling to avoid, known issues with bullets, indentation, etc.

**Comment by laemtl** [comment]
@christinerogers The Readme needs to be edited. See my commit above to see what needs to be changed.

**Comment by christinerogers** [comment]
@laemtl yes i saw the readme edit you linked fixed indentation but not numbered bullets

**Comment by laemtl** [comment]
It is fixed on the [RTD dev version here](https://loris-fork.readthedocs.io/en/2020-08-13-developersguidemarkdown/docs/wiki/99_Developers/Developers_Guide.html), and will fix the main documentation when #6910 will be merged.

**Comment by laemtl** [comment]
Should we close this?
