### ISSUE TITLE
[Survey Module] If survey instruments are created before the visit is started, instruments will not populate automatically once the visit is started.  

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#7127]
If survey instruments are created before the visit is started, clinical instruments will not populate automatically once the visit is started.  

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Create a timepoint for a given candidate, but do not start the visit.
2. Create a survey instrument in the survey module for the given candidate and timepoint.
3. Go to candidate's timepoint and start the visit.
4. Instruments that would normally populate once the visit is started will no longer automatically populate.

Can we please ensure that instrument populating is not blocked if a survey instrument has been created before starting the visit.

**Comment by ridz1208** [comment]
@driusan I submitted a while back https://github.com/aces/Loris/pull/7163 as a fix for IBIS for this issue (The PR is based on 21).

There are 100 ways to fix this particular issue, this PR is the solution i could find with the least number of line of codes (to avoid large overrides on the project...)

If this fix works for LORIS in general I can submit it for 23. if you prefer going in a different directiion let me nkow and I can submit something along those lines

**Comment by driusan** [comment]
PR merged
