### ISSUE TITLE
[23.0][instrument_manager] Write permissions not being used

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7129]
**Describe the bug**
The `instrument_manager_write` permission is not really being used. If you do not have the permission, you can still see and access the upload tab. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `Instrument Manager`
2. Remove `instrument_manager_write`, and refresh the module. Nothing changes.

**What did you expect to happen?**
For permissions to be more granular and affect the usage of the module.

**Comment by driusan** [comment]
PR was merged
