### ISSUE TITLE
Loris API documentation page leads nowhere

### ISSUE THREAD

**Issue by vfonov** [aces/Loris#7131]
The wiki page [API](https://github.com/aces/Loris/wiki/API), points to `https://github.com/aces/Loris/blob/main/modules/api/docs/LorisRESTAPI_v0.0.3.md` , which does not exist. 

**To Reproduce**
1. Go to https://github.com/aces/Loris/wiki
2. Click on `Technical pages`
3. Click on `API links` 
4. Click on `To access full API documentation for the most recent release click here.`
5. You will get 404 page from github

**What did you expect to happen?**
I expected that after 10+ years of development and me nagging about documentation to the LORIS API, it will be available.

**Comment by christinerogers** [comment]
Thanks Vlad - the version was changed very recently.  Wiki link is fixed now, and points here : https://github.com/aces/Loris/blob/main/modules/api/docs/LorisRESTAPI.md
