### ISSUE TITLE
[23.0][help_editor] Update documentation

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7135]
**Edit:** 
Test plan needs update. The bug below, is actually intended behaviour. You need to override the module if you want changes to appear. See @ridz1208's comment below.
 ____
**Describe the bug**
When you update the contents of the help text using the help editor module, the changes are not reflected in the contextual pull down.

<img width="1308" alt="Screen Shot 2020-11-20 at 11 51 29 AM" src="https://user-images.githubusercontent.com/34260251/99826923-fd19a500-2b26-11eb-95a2-6f10f3eed50b.png">
<img width="1432" alt="Screen Shot 2020-11-20 at 11 51 40 AM" src="https://user-images.githubusercontent.com/34260251/99826928-fee36880-2b26-11eb-8c4a-32e899a2789e.png">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `Help Editor`
2. Make a modification to the contents of any module's help text.
3. Save and navigate to the module in question.
4. Open the help pull down, notice no change.

**What did you expect to happen?**
For my changes to be reflected in the contextual pull-down

**Comment by ridz1208** [comment]
@jesscall from what I understand this is by design. overrides on the help docs are no longer supported and you need to override the full module to change the help text

**Comment by jesscall** [comment]
@ridz1208 If that is the case documentation should be updated

**Comment by driusan** [comment]
which documentation are you referring to? The only relevant part of the test plan I see says:

```
4.  Test Steps 1-3 for various pages, including instruments. All modules should take help content from their respective help.md files in their directory, while instruments’ help content is created and edited in the Edit Help section.
```

**Comment by jesscall** [comment]
Thanks for clarifying. 
Closing ticket
