### ISSUE TITLE
[PHP Error] Problem in module.class.inc

### ISSUE THREAD

**Issue by ramsys28** [aces/Loris#7141]
Dear all,

I hope you are well... After a loris v23.0.2 installation in Ubuntu 16.04, I managed to run the logon screen. However, when I log in I got a blank page and from the loris-error.log I got these:

[Tue Nov 24 13:22:23.464655 2020] [php7:error] [pid 10711] [client 192.168.56.1:59260] PHP Parse error:  syntax error, unexpected ')' in /var/www/loris/modules/dashboard/php/module.class.inc on line 159, referer: http://192.168.56.10:8080/
[Tue Nov 24 13:27:08.766853 2020] [php7:warn] [pid 10712] [client 192.168.56.1:59345] PHP Warning:  session_start(): Setting option 'cookie_samesite' failed in /var/www/loris/php/libraries/NDB_Client.class.inc on line 147, referer: http://192.168.56.10:8080/
[Tue Nov 24 13:27:09.434676 2020] [php7:error] [pid 10712] [client 192.168.56.1:59345] PHP Parse error:  syntax error, unexpected ')' in /var/www/loris/modules/dashboard/php/module.class.inc on line 159, referer: http://192.168.56.10:8080/
[Tue Nov 24 13:27:42.779069 2020] [php7:warn] [pid 10708] [client 192.168.56.1:59351] PHP Warning:  session_start(): Setting option 'cookie_samesite' failed in /var/www/loris/php/libraries/NDB_Client.class.inc on line 147
[Tue Nov 24 13:27:56.808491 2020] [php7:warn] [pid 10712] [client 192.168.56.1:59360] PHP Warning:  session_start(): Setting option 'cookie_samesite' failed in /var/www/loris/php/libraries/NDB_Client.class.inc on line 147, referer: http://192.168.56.10:8080/
[Tue Nov 24 13:27:57.540019 2020] [php7:error] [pid 10712] [client 192.168.56.1:59360] PHP Parse error:  syntax error, unexpected ')' in /var/www/loris/modules/dashboard/php/module.class.inc on line 159, referer: http://192.168.56.10:8080/

Could you please help me to overcome this issue? 

Kind Regards
Manos

**Comment by ridz1208** [comment]
@ramsys28 What is your PHP version ?

In my experience this issue happens when you are using an older PHP version that does not support trailing commas which are present in the code.

**Comment by ramsys28** [comment]
I have 7.2 as in the installation instruction. However, I tried 7.3 main php (I haven't updated the modules) and the even the login page wasn't loading. What php version should I have?

**Comment by ridz1208** [comment]
7.3 should work fine. what error do you get when you tried upgrading to 7.3 ? did you take a look in your apache error log ?

**Comment by ramsys28** [comment]
sudo nano /var/log/apache2/loris-error.log

[Tue Nov 24 18:07:30.062927 2020] [php7:notice] [pid 22763] [client 192.168.56.1:62639] Could not execute . Stack trace#0 /var/www/loris/php/libraries/Database.class.inc(106): Database->co$
[Tue Nov 24 18:07:30.063008 2020] [php7:error] [pid 22763] [client 192.168.56.1:62639] PHP Fatal error:  Uncaught DatabaseException: Could not establish a PDO object using the following va$

**Comment by ramsys28** [comment]
fixed it...  I need to update also php7.3-mysql...

I don't understand why in the instruction says to install 7.2 :/

**Comment by ridz1208** [comment]
@ramsys28 could you point me towards the instructions for 7.2 ?

the readme on the main page https://github.com/aces/Loris specifies 7.3

**Comment by ramsys28** [comment]
https://github.com/aces/Loris/wiki/Installing-Loris-in-Depth

**Comment by ridz1208** [comment]
@ramsys28 thank you I added a deprecation message to that page
