### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#7156]
LORIS currently breaks when PHP 8.0.0 is being used. Would be nice to get it working for the latest upgrade to PHP.

**Comment by driusan** [comment]
What breaks?

**Comment by maltheism** [comment]
@driusan composer wouldn't create the vendor directory because of the dependencies not supporting php 8. Once updating composer dependencies which is not as easy as composer update. Smarty shows a lot of errors about undefined variables and $baseurl doesn't seem to be passed to all modules. Unsure if smarty warnings are just being shown because of my apache configuration for them to display.

**Comment by driusan** [comment]
It currently works, but `make checkstatic` fails because phpmd doesn't support php8 yet. We need to either wait for an update or remove it from our build process.
