### ISSUE TITLE
[23.0][behavioural_qc] Link does not redirect to conflict resolver

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7159]
**Describe the bug**
Link to conflict resolver does not work.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `Behavioural Quality Control` module
2. Click on `Data Conflicts` tab
3. Click on any instrument

**What did you expect to happen?**
Should redirect to the `Conflict Resolver` with filters set to show the specific instrument / candidate you clicked on.

**Comment by HenriRabalais** [comment]
It looks like the link is redirecting to the conflict resolver using the loris object function called `[loadFilteredMenuClickHandler](https://github.com/aces/Loris/blob/11e6780c0d0e2f4e33ee915f8258f9222c314892/htdocs/js/loris.js)`. 

My plan to resolve this issue would be to replace the function call with a simple url redirect. 

@driusan do you think this is a good idea? Or is better to update the loris object function to better reflect the way that reactified modules filter data?

**Comment by driusan** [comment]
I think changing it to a simple link is better (if it works.).. that function was from when all the filtering was being done on the PHP side and the values had to be POSTed in order to be applied.

**Comment by driusan** [comment]
PR merged
