### ISSUE TITLE
delete_candidate.php doesn't delete from consent table

### ISSUE THREAD

**Issue by ejoh1101** [aces/Loris#7184]
**Describe the bug**
delete_candidate.php throwing error if candidate has any rows in candidate_consent_rel table. Error below

```
PHP Warning:  PDO::exec(): SQLSTATE[23000]: 
Integrity constraint violation: 
1451 Cannot delete or update a parent row: 
a foreign key constraint fails (`icd`.`candidate_consent_rel`, CONSTRAINT `FK_candidate_consent_rel_CandidateID` FOREIGN KEY (`CandidateID`) REFERENCES `candidate` (`CandID`)) 
in /swadm/var/www/elab_loris/php/libraries/Database.class.inc on line 623
```

**To Reproduce**
Attempt to delete a candidate who has consent information

**What did you expect to happen?**
Should delete candidate including any rows in candidate_consent_rel

**Server Environment (if known):**
- LORIS Version: v23.0.2
- Linux distribution and Version: RHEL 7
- MySQL/MariaDB Version: MariaDB 10.3
- PHP version: 7.3.11

**Comment by ridz1208** [comment]
@ejoh1101 good catch. Will issue a fix

**Comment by ejoh1101** [comment]
@ridz1208 fix submitted. I also noticed issue with tosql when i was testing. I haven't used that feature but am getting `PHP Fatal error:  Uncaught Error: Call to a member function _implodeWithKeys()`

**Comment by ridz1208** [comment]
I think that might need to be changed to `implode`

**Comment by ridz1208** [comment]
@ejoh1101 after taking a deeper look i'm not sure why you would get that `_implodeWithKeys()` error. that function should exist in the database class

**Comment by ridz1208** [comment]
reopening until we confirm the `_implodewithKeys()` situation

**Comment by ejoh1101** [comment]
Figured it out, appears to be an error on my edit. Missed the $ in $DB

**Comment by ridz1208** [comment]
perfect !!
