### ISSUE TITLE
[23.0][bvl_feedback] bvl_feedback panel not allowing access to User Menu while open

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7188]
Issue originally reported by @racostas on CCNA Repo during release candidate testing of `LORIS 23.0.2`
aces/CCNA#4271

____

(This is a minor issue)

How to test:
1. `MainMenu->Canditate-> Access Profile`.
2. Click on a candidate of choice.
3. Open the  `bvl_feedback `panel clicking on the notepad icon in the left part of the Main Menu bar (at the left of the help button sign) 
4. If the user now (while `bvl_feedback` panel is open) try to access the `User option Menu` (top right with the name of the user your logged in)  it will not be able to access it (possible is been render behind the `Feedback panel`) it will need to close it first and then it will be accessible.
<img width="278" alt="image_bvl_feedback_blockingAccess2UserMenu" src="https://user-images.githubusercontent.com/37309344/102099256-1ba55000-3df6-11eb-9a6a-ee4be75ebb6f.png">

-- tested on Mozilla Firefox and Google Chrome --

**Comment by jesscall** [comment]
Same issue occurs when the Help Text panel is open

**Comment by driusan** [comment]
PR merged
