### ISSUE TITLE
[23.0][bvl_feedback] Once a feedback is closed could not be opened again (even if this option is shown in the user interface)

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7189]
Issue originally reported by @racostas on CCNA Repo during candidate release testing of `LORIS 23.0.2`
aces/CCNA#4270

____

(not sure if the expected behaviour, but it seems a bit strange).

How to test:
(`with superadmin user`, they same is true also for not superadmin but issue #7190 depending on permissions will not make possible to test )

1. Go to `MainMenu->Canditate-> Access Profile.`
2. Click on a candidate of choice.
3. Open the ` bvl_feedback` panel clicking on the notepad icon in the left part of the Main Menu bar (at the left of the help button sign) 
4. Create a new feedback on the` New profile level feedback tab` (middle one)
5. In the` Feedback Threads tab` (bottom one) the new feedback will appear as open
6. Change state to close it (the state should correctly change to closed)
7. Tray to change then the state then to open (although the option is shown nothing happen when clicked)

<img width="253" alt="image_bvl_feedback_notAble2reopenThread" src="https://user-images.githubusercontent.com/37309344/102098376-1dbadf00-3df5-11eb-9445-f80da4c7d081.png">

 -- tested on Mozilla Firefox and Google Chrome --

**Comment by jesscall** [comment]
Console error:
<img width="1425" alt="Screen Shot 2020-12-16 at 1 08 02 PM" src="https://user-images.githubusercontent.com/34260251/102388441-be4d0280-3f9f-11eb-95b4-f4a1d08cce36.png">

Error log:
```
[Wed Dec 16 13:01:50.450741 2020] [php7:notice] [pid 24591] [client 192.168.122.1:48498] PHP Notice:  Undefined variable: feedbackID in /var/www/ccna/modules/bvl_feedback/ajax/open_bvl_feedback_thread.php on line 18, referer: https://ccna-dev.loris.ca/813353/
```

**Comment by driusan** [comment]
PR was merged
