### ISSUE TITLE
[23.0][imaging_qc] Downloaded CSV does not maintain row order

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7191]
Issue originally reported by @HenriRabalais on CCNA Repo during candidate release testing of `LORIS 23.0.2`
aces/CCNA#4265

_____

**Issue**
Testing Plan Point [#7](https://github.com/aces/Loris/blob/v23.0.2/modules/imaging_qc/test/TestPlan.md)

When re-ordering the Imaging QC datatable and then downloading it as a .csv, the row order established by column sorting is not maintained in the .csv. This likely applies to all datatables across LORIS.

I don't personally see this as a huge issue given how easy it is sort in any csv editor (and the fact that you can sort on multiple columns in a csv editor), but it was in the testing plan so I thought I would bring it up as an issue.

**Comment by driusan** [comment]
I think that point should be removed from the test plan, it dates from before reactification when the expected behaviour was different.

**Comment by driusan** [comment]
Merged PR
