### ISSUE TITLE
[23.0][imaging_qc] "Selected" filter: empty value in row should default to "False"

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7192]
Issue originally reported by @HenriRabalais on CCNA Repo during candidate release testing of `LORIS 23.0.2`
aces/CCNA#4264

____

I could be completely wrong on this, but it seems as though the "Selected" column in this table should have a value of `true` or `false`. However, I would imagine that an empty value would equate to `false`. However, when the filter for "Selected" is set to `false`, all the rows with empty values under the column "Selected" are filtered out.

**Comment by jesscall** [comment]
@cmadjar 
Do you know if this is the expected behaviour?

**Comment by cmadjar** [comment]
Not sure. The NULL value shows that the file has not been QCed I guess? I don't know, LOL. @jesscall could you add this to the LORIS meeting of tomorrow? Wouldn't mind having everyone's thought on this. Thank you :-)

**Comment by jesscall** [comment]
Discussed during LORIS Meeting on Dec. 15, 2020.

This is desired behaviour.
