### ISSUE TITLE
[Behaviour Quality Control] Update Test Plan

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7193]
Issue originally reported by @HenriRabalais on CCNA Repo during candidate release testing of `LORIS 23.0.2`
aces/CCNA#4259

_____

There are certain elements of the Test Plan that are unclear or not specific which slows down the testing process and makes it more prone to error.

**First Issue**
Point 3 states: `Remove the 'access all profiles' permission and test whether the site filter is now populated only with sites that are study sites and to which the user has access.`

There is no permission that is called `access all profiles`. I believe the permission that is being referred to is called `Across all sites access candidate profiles`

**Second Issue**
Point 5 states: `Ensure that Conflict/Incomplete Candidate/Link to BVL Feedback links point to the correct place.`

It is unclear what each of these listed items refer to, as they do not match the tab labels within the module. There are also many links that can be clicked on, and the testing plan point does not state what link should be tested.

**Third Issue**
Point 6 states: `Ensure that feedback status is correct.`

It is unclear what `feedback status` refers to in the context of this module, since the word `status` doesn't appear in the module.

**Fourth Issue**
Point 9 states: `Perform a query that returns a row with a link to BVL feedback. Click on the click to edit the feedback QC status and change its value. Save the data and close the popup. Make sure that the behavioural_qc result table has been updated for that row (i.e. reflect the new Feedback status). Click on the feedback link again and check that the QC status has also been updated in the popup window.`

Either I can't find it, or the ability to edit through a pop-up window is inaccessible or hidden. Whether it exists or not, this instruction is rather unclear and should probably be rewritten.

**N.B.** 
This may be coming from the perspective of someone who doesn't use the module, and this may be much clearer to a regular user, but I had a lot of trouble following these instructions!

**Comment by shonibare** [comment]
Having studied the test plan and followed the instructions for testing the module, I didn't see anything wrong in the test plan. I presumed the person that issued this ticket misinterpreted the test plan. We can close this issue. @cmadjar
