### ISSUE TITLE
[23.0][dashboard] Study Progression panel graphs only show data when zoomed out

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7196]
Modified version of issue originally reported by @racostas on CCNA Repo during candidate release testing of `LORIS 23.0.2`
aces/CCNA#4210
_____

There's a lot of data in the CCNA database and it seems that the graphs on dashboard's study progression panel are affected by this. 

### At 100%:

![image](https://user-images.githubusercontent.com/37309344/100107860-1cbb1100-2e38-11eb-8408-db4ade5317ee.png)

![image](https://user-images.githubusercontent.com/37309344/100108156-7cb1b780-2e38-11eb-8d7b-e1c6abe2cf42.png)

### At 75%:

<img width="961" alt="Screen Shot 2020-12-14 at 12 30 13 PM" src="https://user-images.githubusercontent.com/34260251/102114954-d50d2100-3e08-11eb-9525-ac781dfb1da8.png">

<img width="946" alt="Screen Shot 2020-12-14 at 12 30 24 PM" src="https://user-images.githubusercontent.com/34260251/102114959-d8a0a800-3e08-11eb-92bc-803601b945fd.png">

**Comment by ridz1208** [comment]
@maltheism because of the number of sites we were thinking... can you move the site names to the right hand side in a list format ? and leave the graph on the left hand side

I was thinking 80% width would be the graph and 20% the site names. and if possible make the sitenames scrollable (something similar to what you did for the visit labels in the DQT on CBIGR)

**Comment by driusan** [comment]
I'm not sure if it's possible with the library used to generate the graphs, just investigate if it's possible.. if it's not possible let us know.

**Comment by maltheism** [comment]
Seems to be possible by setting the `legend: {position: 'right}` before generating and example found here: https://c3js.org/samples/legend_position.html

**Comment by ridz1208** [comment]
@maltheism can you give it a try with the CCNA database ?

**Comment by maltheism** [comment]
@ridz1208 yah the legend.position = right doesn't work. Turns out the solution that works is found at https://stackoverflow.com/questions/42909827/scrollable-legends-on-c3-graphs

I'm almost done with the PR.

**Comment by maltheism** [comment]
@ridz1208 @jesscall please test the PR
