### ISSUE TITLE
[23.0][dashboard] Wrong login time in welcome panel

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7197]
Issue originally reported by @CamilleBeau on CCNA Repo during candidate release testing of `LORIS 23.0.2`
aces/CCNA#4272
____

In the welcome panel, the time of the last login is incorrect. For example, if I last logged in at 10:53, the welcome panel says I last logged in at 15:53.

[NOTE]: Timezone on ccna-dev is set to `EST`, so I'm not entirely sure that this is related to VM configuration.

**Comment by jesscall** [comment]
I checked the php.ini file and couldn't find anything relevant to timezone (that wasn't commented out).

Followed instructions from this link:
https://linuxize.com/post/how-to-set-or-change-timezone-on-centos-7/

I get the following:
```
$ timedatectl
      Local time: Wed 2020-12-16 14:11:09 EST
  Universal time: Wed 2020-12-16 19:11:09 UTC
        RTC time: Wed 2020-12-16 19:11:08
       Time zone: America/Toronto (EST, -0500)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: no
 Last DST change: DST ended at
                  Sun 2020-11-01 01:59:59 EDT
                  Sun 2020-11-01 01:00:00 EST
 Next DST change: DST begins (the clock jumps one hour forward) at
                  Sun 2021-03-14 01:59:59 EST
                  Sun 2021-03-14 03:00:00 EDT


$ ls -l /etc/localtime
lrwxrwxrwx. 1 root root 37 Jul 21  2016 /etc/localtime -> ../usr/share/zoneinfo/America/Toronto
```

So it seems it's already set to EST timezone on the VM... But still displaying UTC timezone on the frontend. 

@driusan you mentioned another location I could look to get more insight. Do you happen to remember what that was?

**Comment by driusan** [comment]
The OS timezone isn't used by PHP since PHP 5.4. See: https://www.php.net/manual/en/function.date-default-timezone-get

It uses the `date.timezone` setting from php.ini: https://www.php.net/manual/en/datetime.configuration.php#ini.date.timezone

**Comment by jesscall** [comment]
Updated `php.ini` file and restarted the apache service and still noticing same error...

<img width="414" alt="Screen Shot 2020-12-16 at 2 41 06 PM" src="https://user-images.githubusercontent.com/34260251/102398088-d37c5e00-3fac-11eb-8c50-169b6db1a6ea.png">

<img width="209" alt="Screen Shot 2020-12-16 at 2 41 57 PM" src="https://user-images.githubusercontent.com/34260251/102398110-dc6d2f80-3fac-11eb-8559-5e279ec95ccb.png">
(should be 14:25 not 19:25)

**Comment by driusan** [comment]
Did you check the value in the database? It might be saved with the incorrect timezone and won't show a new value until you login/logout..

**Comment by jesscall** [comment]
Ah, yes. That does the trick!

Thanks for your help Dave! 😄

**Comment by jesscall** [comment]
In that case, I'll close this issue as it's not a bug.
