### ISSUE TITLE
[23.0][dashboard] Number of Pending account approvals in My tasks panel inconsistent

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7198]
Issue originally reported by @CamilleBeau on CCNA Repo during candidate release testing of `LORIS 23.0.2`
aces/CCNA#4273

____

In the "My tasks" panel of dashboard, the number of `pending account approvals` does not match the number of rows in user accounts with `site` not set and `Pending approval` set to `yes` (as specified in TestPlan).

**Comment by ridz1208** [comment]
@CamilleBeau did you remove DCC requests ?

**Comment by CamilleBeau** [comment]
> @CamilleBeau did you remove DCC requests in your math?

What do you mean? Are you talking about requests from CCNA Testing Site?

**Comment by jesscall** [comment]
@CamilleBeau yes

**Comment by CamilleBeau** [comment]
@jesscall Yeah it still doesn't add up. The testplan specifies to have the **site not set** though, but either way when I filter for CCNA testing site there are 121 results which does not account for the discrepancy of 40.

**Comment by CamilleBeau** [comment]
@jesscall But maybe that is because there are some users who have CCNA testing site as well as several other sites, so 40 might be the number of rows with _only_ CCNA testing site.

**Comment by CamilleBeau** [comment]
Just checked, 615 is shown in dashboard, and 656 shown in user accounts. There are 41 users from _only_ CCNA testing site, so it does add up. In this case it is just a matter of the testplan being unclear.

**Comment by jesscall** [comment]
closing
