### ISSUE TITLE
[23.0][mri_violations] Filter issue

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7202]
Issue originally reported by @pierre-p-s on CCNA Repo during candidate release testing of `LORIS 23.0.2`
aces/CCNA#4279
____
When setting a filter, using show data and then leaving the module or refreshing, the filters dont reset

**Comment by xlecours** [comment]
Yes, LORIS does that. At least old Menu_filter modules. 
see: https://github.com/aces/Loris/blob/5166ada28fbb01ac020f03c6eb38766f2ff7e32a/php/libraries/NDB_Menu_Filter.class.inc#L310

**Comment by pierre-p-s** [comment]
So are we just leaving it this way?

**Comment by xlecours** [comment]
I don't know. Is there a need to change it?

**Comment by pierre-p-s** [comment]
The other filters reset so it s more intuitive if they all do. But maybe we can discuss it at the meeting
