### ISSUE TITLE
[23.0][my_preferences] Notifications not sent by email

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7204]
Issue originally reported by @CamilleBeau on CCNA Repo during candidate release testing of `LORIS 23.0.2`
aces/CCNA#4281

___
In my preferences, when notifications are selected, an email is not received. For example, from my account I selected to have notifications from both publication module and issue tracker module. From a separate account, I created new issues on issue tracker and proposed / accepted a new proposal on publication module. No email notifications regarding this activity was received.

**Comment by kongtiaowang** [comment]
Issue tracker doesn't have this function. The notification function only works on assigned and changed issue not for creating a new issue.  [Loris/smarty/templates/email/issue_assigned.tpl]  
                                           [Loris/smarty/templates/email/issue_change.tpl]
 If CCNA has the issue tracker notification in the my preferences panel, CCNA should customize the new notification function on it. https://github.com/aces/Loris/wiki/Notification-system
