### ISSUE TITLE
[23.0][Data Dictionary]Test Plan is outdated

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7205]
Issue originally reported by @sruthymathew123 on CCNA Repo during candidate release testing of `LORIS 23.0.2`
aces/CCNA#4286
___
Overall, the module works well I think.
But the test plan seems to be outdated in many points   as per LORIS 23.0 Release
_Ex: "Check that selecting multiple instruments returns all relevant results."
The multi select instrument dropdown no more exists in LORIS 23.0 Release._

The test plan is based on the previous data dictionary version available with LORIS 21.0 release or so.

**Comment by driusan** [comment]
I don't this is a test plan update.. I don't remember any decision to remove multiselects from filters.

**Comment by sruthymathew123** [comment]
@driusan I don't know much about the recent changes made; but looks different
As per 23.0, it looks like 
![Screen Shot 2020-12-15 at 1 53 34 PM](https://user-images.githubusercontent.com/23702452/102259341-f9d2c880-3edc-11eb-8615-036f76a38f60.png)

Previous version (21.0) taken from IBIS
![Screen Shot 2020-12-15 at 1 54 54 PM](https://user-images.githubusercontent.com/23702452/102259487-2a1a6700-3edd-11eb-872b-88eef69cec0e.png)

**Comment by driusan** [comment]
PR was merged
