### ISSUE TITLE
[23.0][media] File not displayed in data table even though upload was successful

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7206]
Issue originally reported by @nicolasbrossard on CCNA Repo during candidate release testing of `LORIS 23.0.2`
aces/CCNA#4287
____
I successfully uploaded a file in the media module and switched to the 'Browse' tab right after to see if the file was listed in the result table. It was not. I had to refresh the page in order for my file to be shown.

**Comment by maltheism** [comment]
@jesscall not having that issue on main and it was fixed awhile ago by me. See https://github.com/aces/Loris/pull/7027 for the past PR fixing it. I'm assuming on CCNA the media module must be using an override with old code?

**Comment by driusan** [comment]
How critical is it for CCNA's upgrade and is it broken on the release that's currently on CCNA's production server?

**Comment by jesscall** [comment]
Not critical.

**Comment by nicolasbrossard** [comment]
@ridz1208 @driusan @maltheism @jesscall I don't know what you guys want to do with this but I just want to say that I tested on `aces/main` (which includes @maltheism's PR#7027) and the bug is not there.

**Comment by ridz1208** [comment]
@driusan i'm closing this issue since its fixed in 24
