### ISSUE TITLE
[23.0][media] Incorrect error message after uploading a big file

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7207]
Issue originally reported by @nicolasbrossard on CCNA Repo during candidate release testing of LORIS 23.0.2
aces/CCNA#4288
___
I tried uploading a big (>1024M) file and got an error message saying that there was an upload error. The message said that some of the required fields were missing even though I filled out the PSCID and VLabel.

**Comment by xlecours** [comment]
@nicolasbrossard What is the error message? What is the HTTP status code in the response? Is there a message in php error log?

**Comment by xlecours** [comment]
The error message is sent because $_FILE is empty in:
https://github.com/aces/Loris/blob/main/modules/media/ajax/FileUpload.php#L117-L120

Most likely, $_FILE is empty because `post_max_size` in php.ini is too small.

Would a distinct message saying "The uploaded file is too big" be a good fix for this issue?

**Comment by driusan** [comment]
I thought the media module had a feature where the max size is sent via ajax and displayed/checked in javascript before being uploaded. (Or am I misremembering?)

**Comment by xlecours** [comment]
> I thought the media module had a feature where the max size is sent via ajax and displayed/checked in javascript before being uploaded. (Or am I misremembering?)

If it is the case then this issue deserves a deeper investigation.

**Comment by driusan** [comment]
I just had a quick look and it seems like it's only displayed, not used to restrict trying to upload things bigger..

**Comment by nicolasbrossard** [comment]
@xlecours You can have a look at the imaging uploader. I remember David Bladder implemented something to check that the uploaded file size did not exceed the max upload size.

**Comment by xlecours** [comment]
> @xlecours You can have a look at the imaging uploader. I remember David Bladder implemented something to check that the uploaded file size did not exceed the max upload size.

The changes in this PR is of 3 lines VS adding code that checks fro php.ini value, front-end validation plus those same tree lines. It would be a nice feature request I think.

**Comment by ridz1208** [comment]
@nicolasbrossard @xlecours I see a merged reference PR. does it fix the issue here? if not can a new clearer issue be made and this closed please ?

there is no clear action item here to me

**Comment by driusan** [comment]
I had a look at the diff and it looks like the merged PR intends to fix the bug as reported (though a separate issue to validate file size *before* uploading as a new feature would probably be a good idea.)

**Comment by ridz1208** [comment]
closing ticket since issue is fixed.

If someone wants to make a "proposal" issue for that feature, be my guest
