### ISSUE TITLE
[23.0][Publications] - Keywords and Collaborators not filtering

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7209]
Issue originally reported by @samirdas  on CCNA Repo during candidate release testing of LORIS 23.0.2
aces/CCNA#4295
____
Not only are these not filtering, they do not appear when you click on a given project. I am wondering if they are even being saved, when I enter them in Propose New Project? I am suspicious because they do not appear on the CSV when I download it.

**Comment by laemtl** [comment]
I retested on CCNA and it seems to work well, no problem detected.
- csv contains the keywords/collaborators (either the one I created or Samir's one)
- I can filter my publications or Samir's ones
- They do not appear on the data table but it seems to be a design decision, not a bug

**Comment by ridz1208** [comment]
@driusan i think this issue should be closed then

**Comment by driusan** [comment]
I don't really know much about the publications module, but why what do you mean about the not appearing in the data table being a design decision, not a bug? It seems like if that's the case users still find the design confusing..

**Comment by laemtl** [comment]
@driusan I agree, it's very confusing to filter on a value you don't see :) 
![Screenshot from 2020-12-16 14-37-18](https://user-images.githubusercontent.com/32041423/102397708-40432880-3fac-11eb-9e9a-32dd1df24124.png)

**Comment by driusan** [comment]
Oh, I see. That screenshot explains the confusion. What happens when you click on the link in Title? Does it take you somewhere that you see it?

**Comment by laemtl** [comment]
@driusan Yes!

**Comment by driusan** [comment]
I say we don't change it for the bug fix release but keep the issue open to fix the UI when we have more time.
