### ISSUE TITLE
[battery_manager] When loading the module with a predefined filter in the URL the filter is not applied

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7216]
**Describe the bug**
When the battery_manager is loaded using a link with predefined filters, the module loads fine but displays all the rows not just the ones that apply to the filter. the filter panel however does show the correct filters populated.

**To Reproduce**
1. open the battery_manager module and filter the data for some parameters. (notice these parameters are populated in the URL as you add them)
2. copy The URL (including the added filters) and open a new tab/window and paste the url
3. the page will load with the filters populated but not applied to the table rows below.

**Comment by HenriRabalais** [comment]
@ridz1208 I tried testing this but cannot replicate the issue. For me, the table is filtered correctly. Perhaps there is a specific case that is not working, could you give me an example of something you filtered for where you noticed the issue?

**Comment by ridz1208** [comment]
https://ccna-dev.loris.ca/battery_manager/?subproject=1&visitLabel=Clinical_Assessment
