### ISSUE TITLE
[23.0][Conflict Resolver] Resolved Conflicts > Correct answer displays values incorrectly

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7217]
Issue originally reported by @laemtl on CCNA Repo during candidate release testing of `LORIS 23.0.2`
aces/CCNA#4300
___
Some values appear as "array" when the field is of type select multiple.
![Screenshot from 2020-12-15 14-08-32](https://user-images.githubusercontent.com/32041423/102261171-4d461600-3edf-11eb-9ddb-07908dc664bb.png)

**Comment by driusan** [comment]
Likely "some values" are ones where there are multiple things selected for at least 1 of the conflicts..
