### ISSUE TITLE
[23.0][Document_repository] You are able to create categories with same name

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7232]
Issue originally reported by @zaliqarosli on CCNA Repo during candidate release testing fo `LORIS 23.0.2`
aces/CCNA#4303
___

You are able to create categories with same name.

**Comment by ridz1208** [comment]
To whomever is gonna fix this issue,

The category should be able to have the same name but only if it's not under the same parent!

basically the path to the category should be unique, but the category name doesnt have to be

**Comment by driusan** [comment]
PR merged
