### ISSUE TITLE
"Go to main page" not working

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7246]
**Describe the bug**
When a user gets timedout due to inactivity they get redirected to the page illustrated below. when clicking "Got to main page" the user should be redirected to the login page.

As you can see in the right panel in the image below, that link is empty. I suspect this has something to do with the removal of the URL configuration in the database

![Screenshot from 2020-12-17 21-14-57](https://user-images.githubusercontent.com/15268287/102566310-47059480-40ad-11eb-8424-93513cab64ec.png)

**Comment by driusan** [comment]
Is there a way to get to this page other than "timeout due to inactivity"?

**Comment by ridz1208** [comment]
I think of you sign out and then try to navigate to a specific module ?

**Comment by laemtl** [comment]
We can find this link in 3 templates: 403, 404, and 500.tpl.

**Comment by laemtl** [comment]
@ridz1208 Tested on my local environment and everything works.

**Comment by ridz1208** [comment]
@laemtl you are correct, the issue is on main, not 23.

The issue is because the tpl_data array is populated in an if statement that is never reached. 
https://github.com/aces/Loris/blob/main/src/Http/Error.php#L58

**Comment by laemtl** [comment]
@ridz1208 I can have a look, thanks !
