### ISSUE TITLE
[Publication] Lead Investigator Email not saving

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#7280]
The value entered for Lead Investigator email is not saved if the name used already exists in the collaborator's database.
This prevents any email changes, and in the particular scenario where the collaborator does not have any associated email, the mandatory Lead Investigator's email field remains empty.

**To Reproduce**
Create collaborator1 (not Lead) without an email in publication 1.
Create publication 2 and use the same name you used for collaborator1 for the Lead collaborator, with an email.
Save and load publication 2. The Lead Collaborator email is missing.

**Comment by laemtl** [comment]
@driusan @ridz1208 To solve this issue, should we make all collaborators' email mandatory?

**Comment by driusan** [comment]
I don't think I know enough about the publication module to understand the problem or have an opinion on the solution. From what I can gather your question is: should we allow the same person to use different email addressess on different publications? Or am I misunderstanding?

**Comment by laemtl** [comment]
@driusan The database design us definitely wrong and I have the 2 options described above to fix the issue. I think making the collaborator's email mandatory is an easy solution.

**Comment by cmadjar** [comment]
@miladheshmati can you look into this?

**Comment by miladheshmati** [comment]
@cmadjar, @laemtl, I checked the exact scenario described on the task and there was no issue found:

![Screenshot 2023-06-05 at 10 29 01 AM](https://github.com/aces/Loris/assets/51356424/f5b56e3c-84d4-4e04-bdd8-6e111586efe8)

**Comment by laemtl** [comment]
Retested and this now works. Closing.
