### ISSUE TITLE
[statistics] - Imaging Statistics error

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#7341]
![Screen Shot 2021-02-17 at 5 00 16 PM](https://user-images.githubusercontent.com/9876007/108273673-df69d500-7141-11eb-81f6-2277acd2d82f.png)

Fatal error: Uncaught TypeError: Illegal offset type in /var/www/html/modules/statistics/php/stats_mri.class.inc:239 Stack trace: #0 /var/www/html/php/libraries/NDB_Form.class.inc(132): LORIS\statistics\Stats_MRI->setup() #1 /var/www/html/src/Middleware/UserPageDecorationMiddleware.php(240): NDB_Form->handle(Object(Laminas\Diactoros\ServerRequest)) #2 /var/www/html/src/Middleware/PageDecorationMiddleware.php(56): LORIS\Middleware\UserPageDecorationMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(LORIS\statistics\Stats_MRI)) #3 /var/www/html/php/libraries/NDB_Page.class.inc(708): LORIS\Middleware\PageDecorationMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(LORIS\statistics\Stats_MRI)) #4 /var/www/html/php/libraries/Module.class.inc(412): NDB_Page->process(Object(Laminas\Diactoros\ServerRequest), Object(LORIS\statistics\Stats_MRI)) #5 /var/www/html/src/Middleware/ResponseGenerator.php(50): Module->handle(Object(Laminas\Diactoros\ServerRequest)) #6 /var/www/html/src/Middleware/AuthMiddleware.php(63): LORIS\Middleware\ResponseGenerator->process(Object(Laminas\Diactoros\ServerRequest), Object(LORIS\statistics\Module)) #7 /var/www/html/src/Router/ModuleRouter.php(74): LORIS\Middleware\AuthMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(LORIS\statistics\Module)) #8 /var/www/html/src/Middleware/ExceptionHandlingMiddleware.php(35): LORIS\Router\ModuleRouter->handle(Object(Laminas\Diactoros\ServerRequest)) #9 /var/www/html/src/Router/BaseRouter.php(112): LORIS\Middleware\ExceptionHandlingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(LORIS\Router\ModuleRouter)) #10 /var/www/html/src/Middleware/ResponseGenerator.php(50): LORIS\Router\BaseRouter->handle(Object(Laminas\Diactoros\ServerRequest)) #11 /var/www/html/src/Middleware/ContentLength.php(52): LORIS\Middleware\ResponseGenerator->process(Object(Laminas\Diactoros\ServerRequest), Object(LORIS\Router\BaseRouter)) #12 /var/www/html/htdocs/index.php(48): LORIS\Middleware\ContentLength->process(Object(Laminas\Diactoros\ServerRequest), Object(LORIS\Router\BaseRouter)) #13 {main} thrown in /var/www/html/modules/statistics/php/stats_mri.class.inc on line 239

**Comment by driusan** [comment]
Is this before or after #7339? If before, can you see if that PR fixed it? (If after, it probably caused it..)

**Comment by kongtiaowang** [comment]
it is after #7339
