### ISSUE TITLE
Working towards a common and cohesive code structure

### ISSUE THREAD

**Issue by mohadesz** [aces/Loris#7365]
Common and cohesive code structure can include the following:

- API
- Data Framework
- Semantic Consistency across modules
- Can reduce number of bugs
- Can make life easier in general for developers
- Similar to “common aesthetics” but for the backend
- Streamlining commands to create modules and views, etc (ie make PHP script that does a version module so you can turn into whatever you want) - See Shen for clarification
- Ie. a script that can create a basic module to be customized
- Do code generation

**Comment by ridz1208** [comment]
@mohadesz we miss you!
