### ISSUE TITLE
Unexpected response from loris api  on https://ipmsa-loris.bic.mni.mcgill.ca

### ISSUE THREAD

**Issue by vfonov** [aces/Loris#7374]
Today we noticed unexpected behaviour while working with LORIS API on https://ipmsa-loris.bic.mni.mcgill.ca 

A query script based on https://github.com/aces/Loris/blob/main/modules/api/docs/LorisRESTAPI.md used to work, but now it fails.

Investigating the error, following code reports an error:
```
login_info=json.load(open('auth.json'))
requests.post('https://ipmsa-loris.bic.mni.mcgill.ca/api/v0.0.3-dev/login', json=login_info).content
```
produces
```
{"error":"Unsupported version"}
```

**Comment by driusan** [comment]
I don't know what version of LORIS inmsa-loris.bic.mni.mcgill.ca is running, but in the latest version v0.0.3 is no longer a development version. Try taking out the -dev suffix in the URL.
