### ISSUE TITLE
[publication] Edit Permissions not assigned to creator of proposal

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7401]
**Describe the bug**
When a publication proposal is submitted, the user creating the issue should be able to go back and edit the form. This is currently not the case. I believe the permission for the creator is never inserted into `publication_users_edit_perm_rel`

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `Publication`
2. Create & submit a project proposal
3. Try accessing the created proposal and notice that you cannot edit the fields (other than status)

**What did you expect to happen?**
To be able to edit the form.

**Comment by ridz1208** [comment]
@cmadjar it seems like there was a Pr to fix the issue, can this be closed? or the issue is still happening ?

**Comment by cmadjar** [comment]
@ridz1208 has it been pulled on testing?

**Comment by ridz1208** [comment]
@cmadjar the merged PR is from March 30th, it should be on test

**Comment by cmadjar** [comment]
Just tested on the test VM. This can be closed. Thanks!
