### ISSUE TITLE
[Next_stage/battery] When instruments are using instrument permissions they can not be populated at the next_stage step

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7435]
**Describe the bug**
LORIS allows instruments to use instrument permissions where access to specific instruments can be checked based on a project-specific permission code. This works well to restrict access to a specific instrument in a timepoint but maintain access to the rest of the instruments in the same timepoint

**Issue:** If a user who does not have the instrument permission tries to "start next stage" the battery will still be populated but a 500 error will be displayed to the user. After a refresh the intrument_list module will be populated regardless...

**What did you expect to happen?**
The battery should be populated without error, it's only access to the instrument that should be restricted, not it's creation

**Comment by ridz1208** [comment]
might be fixed by https://github.com/aces/Loris/pull/8290

**Comment by ridz1208** [comment]
@miladheshmati  to test after above PR is merged

**Comment by miladheshmati** [comment]
@ridz1208, tested, no issue was found

**Comment by driusan** [comment]
Fixed according to above comment.
