### ISSUE TITLE
Certification Training 

### ISSUE THREAD

**Issue by Maurylette** [aces/Loris#7461]
Hi LORIS Team,

![LORIS NP Training](https://user-images.githubusercontent.com/85304252/120674964-a17b8d00-c462-11eb-8b61-78c484ac73f9.PNG)
![LORIS NP 404 Page](https://user-images.githubusercontent.com/85304252/120675075-c07a1f00-c462-11eb-9b2d-c485398e7676.PNG)
![LORIS NP 404 Page](https://user-images.githubusercontent.com/85304252/120675109-c839c380-c462-11eb-8e67-241ad46aaf5c.PNG)
![LORIS NP No Online Training](https://user-images.githubusercontent.com/85304252/120675111-c8d25a00-c462-11eb-809f-55e1abafa21a.PNG)
![LORIS NP Training](https://user-images.githubusercontent.com/85304252/120675113-c8d25a00-c462-11eb-9736-f432316af0a8.PNG)

I am in the process of training for my new role and LORIS is where the training certifications take place. When I'm on the training page and I click on one of the certifications to complete, it leads me to a blank page with the title of the testing session at the top. Additionally, when I click on the "reference manual" button, it leads me to a "404 Not Found" page. Mind you, I am using the Google Chrome browser. It's been four days now that I haven't been able to access the training modules. 

- Windows 10 
- Google Chrome 
- LORIS Version: [e.g. 22.0.0]

**Comment by jesscall** [comment]
@Maurylette 
Thanks for reporting this issue. We are currently working on a fix for this and will email you when it has been resolved.
For future support requests, you can email us at ccna@mcin.ca!

I will close this ticket as it is specific to the CCNA instance and not pertinent to LORIS core.

Thank you, 
Jessica
