### ISSUE TITLE
[mri_violations] Can not resolve violations if scan has multiple violations

### ISSUE THREAD

**Issue by driusan** [aces/Loris#7472]
When there are multiple violations for a scan in the mri_violations module, they can not be resolved. The page reloads without changing the data.

The hash for identifying the violation in the `_process` function is built as `md5(concat_WS( ':',MincFile,PatientName,SeriesUID,TimeRun))`. This is used in a pselectOne while trying to get the primary key for the resolution table. However, the values concatenated are not enough to uniquely identify a row if a scan has multiple violations, resulting in the `pselectOne` failing because of the multiple rows returned.

**Comment by ridz1208** [comment]
might be solved by #7473
