### ISSUE TITLE
[User] GROUP_CONCAT truncates site names

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#7480]
The `getSiteName()` function in the User class returns a truncated array of site names when a study has many sites. This is due to mysql GROUP_CONCAT that truncates the string to 1024 characters by default. The offending statement is at https://github.com/aces/Loris/blob/main/php/libraries/User.class.inc#L71 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Create 103 sites which names length are 10 characters
2. Assign them all to a user.
3. look at the output of `User::getSiteName()` 

**Server Environment (if known):**
- LORIS Version: >=17.01 

Reported by @alfredomp which runs an instance with 500+ sites.

**Comment by ridz1208** [comment]
PR merged
