### ISSUE TITLE
[Behavioral QC] - Filter dropdown selections don't remain after search (IBIS v23.0 Upgrade)

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#7493]
After doing a search, any selection done in the filter dropdowns are not conserved and are reset to the default. This is cumbersome if you want to perform continuous searches with some fixed parameters/selections.

Steps to replicate issue:
- Make a selection using the filter dropdowns and click on 'Show Data'.
- Selections are reset to default.

**Comment by ridz1208** [comment]
@SantiagoTG can you check if it's still the case with 24? if so please change label on this issue from 23 to 24. if not please close issue

**Comment by ridz1208** [comment]
just tested and the filter seems to have been reactified, no longer an issue
