### ISSUE TITLE
Behavioral QC - Can't arrange columns in alphabetical order (IBIS v23.0 Upgrade)

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#7495]
Can't arrange listed items in alphabetical order when clicking on any of the columns in the search results table.

**Comment by driusan** [comment]
I don't know what this means.

**Comment by ridz1208** [comment]
@driusan I think in the menu table if you click the header it should automatically change the sorting of the data alphabetically by the column header you click.

unless I misunderstood?

@SantiagoTG in this case what's broken ? can you provide an example?

**Comment by SantiagoTG** [comment]
Hi Dave, Rida, that is correct. This is a feature request to be able to sort the contents of the table when clicking on the header of a given column. This is a very useful feature for sorting through the table by organizing the content alphabetically based on a specific column content. This is not broken, simply is not a feature of the table, which is available in most other modules and would be of benefit to have.

**Comment by SantiagoTG** [comment]
Definitely not sorting when a header is clicked. Added the 'Bug' label.

**Comment by ridz1208** [comment]
just tested on tet-loris-dev and it is no longer an issue
