### ISSUE TITLE
Loris instrument help not working

### ISSUE THREAD

**Issue by jstirling91** [aces/Loris#7499]
**Describe the bug**
When viewing an instrument, which has a help section in the help editor, upon clicking the help icon the following message is shown instead of the help text identified in the help editor.

```
No help available for instruments (/var/www/loris/modules/instruments/help/instruments.md)
```

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Ensure a help section has been added for a specific instrument.
2. Navigate to the instrument.
3. Click the help icon in the menu bar.

**What did you expect to happen?**
The help description for thqt instrument to show.

**Browser Environment (please complete the following information):**
- chrome 

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: 23.0.3
- Linux distribution and Version: [Ubuntu 16.04
- MySQL/MariaDB Version: MariaDB 10.3

**Additional context**
In 21.0 when calling for the help description the instrument name was passed as the `test_name`. In 23.0 `instruments` is passed for all instrument help. The actual instrument is no longer passed.

**Comment by zaliqarosli** [comment]
this was fixed by https://github.com/aces/Loris/pull/6907
