### ISSUE TITLE
Bvl Feedback visible/accessible when de-activated in Module Manager

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#7521]
The pencil icon that opens Bvl Feedback is still visible in the top menu bar (next to the  Help "?" icon), when the module has been set to Active:No in the Module Manager.  Clicking on the pencil icon will open Bvl Feedback.

To reproduce: set Active=No for bvl_feedback.  The pencil icon in the top menu bar is still Visible and clickable - opening Bvl feedback - when viewing the following: 
* Timepoint List
* Instrument list
* from any instrument form

**Comment by AlexandraLivadas** [comment]
I am getting the same bug @christinerogers except that after I set `Active:No` for bvl_feedback, when I click on the pencil icon nothing appears.

**Comment by kongtiaowang** [comment]
This issue has been fixed by Dave.
