### ISSUE TITLE
Make ProjectID not nullable

### ISSUE THREAD

**Issue by driusan** [aces/Loris#7524]
In the candidate table the RegistrationCentreID is NOT NULL, but the RegistrationProjectID is nullable. All LORIS instances should have at least one project set up (the default LORIS install has one named "LORIS"), and as a result it would make more sense for the ProjectID to also be not nullable. The nullability takes from the time before there was a default project.

Similarly, in the session table the ProjectID should be NOT NULL.

**Comment by ridz1208** [comment]
done
