### ISSUE TITLE
survey accounts module incorrectly displays instrument labels

### ISSUE THREAD

**Issue by thomasbeaudry** [aces/Loris#7527]
When viewing a .linst instrument in the survey accounts module, labels are duplicated on the left and right side of the page (see screen shot).  Labels should only appear on the left side of the instrument and not the right side of it.

The behaviour has been observed on LORIS v23 using firefox and chrome.

![survey_accounts](https://user-images.githubusercontent.com/7085398/129057617-9bd8a79e-8132-4015-a3a8-1f06b17f3047.png)

**Comment by ridz1208** [comment]
@thomasbeaudry can we see a screenshot of the same section in the LINST file ?

**Comment by thomasbeaudry** [comment]
Here is a screenshot of the same instrument but viewed through access-profile
![pcs_access-profile](https://user-images.githubusercontent.com/7085398/129067977-eb7126aa-8d31-4627-8eba-dcec88c1f124.png)

And the code to the label part of the .linst file
`[lorisadmin@loris instruments]$ cat PCS.linst
table{@}PCS
title{@}PCS
date{@}Date_taken{@}Date of Administration{@}2006{@}2012
static{@}Candidate_Age{@}Candidate Age (Months)
static{@}Window_Difference{@}Window Difference (+/- Days)
select{@}Examiner{@}Examiner{@}NULL=>''
static{@}{@}Everyone experiences painful situations at some point in their lives. Such experiences may include headaches, tooth pain, joint or muscle pain. People are often exposed to situations that may cause pain such as illness, injury, dental procedures or surgery.
static{@}{@}We are interested in the types of thoughts and feelings that you have when you are in pain. Listed below are thirteen statements describing different thoughts and feelings that may be associated with pain. Using the following scale, please indicate the degree to which you have these thoughts and feelings when you are experiencing pain.
static{@}{@}WHEN I'M IN PAIN ...
select{@}q1{@}1. I worry all the time about whether the pain will end.{@}NULL=>''{-}'0'=>'0 - not at all'{-}'1'=>'1 - to a slight degree'{-}'2'=>'2 - to a moderate degree'{-}'3'=>'3 - to a great degree'{-}'4'=>'4 - all the time'{-}'not_answered'=>'Not Answered'
s`

**Comment by ridz1208** [comment]
@thomasbeaudry can you just try something for me
replace 
```
static{@}{@}Everyone experiences painful situations at some point in their lives. Such experiences may include headaches, tooth pain, joint or muscle pain. People are often exposed to situations that may cause pain such as illness, injury, dental procedures or surgery.
```

with
```
static{@}bla{@}Everyone experiences painful situations at some point in their lives. Such experiences may include headaches, tooth pain, joint or muscle pain. People are often exposed to situations that may cause pain such as illness, injury, dental procedures or surgery.
```

and show me the result please

**Comment by thomasbeaudry** [comment]
![survey_accounts](https://user-images.githubusercontent.com/7085398/129073908-8f94dc29-3431-4017-a914-e7cd4e1ef109.png)
It fixes the problem

**Comment by shonibare** [comment]
Bug fixed
