### ISSUE TITLE
[Instrument] Form is disabled / frozen on first access

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7529]
**Describe the bug**
When entering an instrument for the first time (when DataEntry == null), the form is frozen. Page needs to be reloaded in order for data to be entered.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to any unopened instrument (`DE != 'In Progress' && DE != 'Complete'`)
2. Notice that form is frozen

**What did you expect to happen?**
To be able to enter data in the form.

**Comment by ridz1208** [comment]
resolved by https://github.com/aces/Loris/pull/7426
