### ISSUE TITLE
Delete Surveys from Timepoint

### ISSUE THREAD

**Issue by ibissstudy** [aces/Loris#7557]
I added too many surveys to a timepoint.  I need to send the surveys to a research participant asap, but I must delete many of them first.  Can  you help?

Martha Cagley
marthac@uw.edu

**Comment by SantiagoTG** [comment]
Issue has been resolved. 

https://github.com/aces/IBIS/issues/1855 
Candidate: SEA0145 
Visit: VSA-Sleep
