### ISSUE TITLE
[Imaging Browser] `Sequence Type` filter not returning any results

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7563]
**Describe the bug**
The `Sequence Type` filter within the imaging browser is not returning any results.

<img width="1409" alt="Screen Shot 2021-09-09 at 1 52 39 PM" src="https://user-images.githubusercontent.com/34260251/132737368-a20a91ce-1408-4419-833d-ad92807b9622.png">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `Imaging Browser`
2. Select a value in the `Sequence Type` filter
3. Notice there are no results in the data table

**What did you expect to happen?**
For filtered results to appear in the data table.

**Browser Environment (please complete the following information):**
- OS: MacOS
- Browser : Chrome

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: 23.0.4
- Linux distribution and Version: Ubuntu 18.04
- MySQL/MariaDB Version: 5.7

**Comment by xlecours** [comment]
Side effect of merging https://github.com/aces/Loris/pull/7453 I would guess
