### ISSUE TITLE
[user_accounts] Email field should be marked as required, and give an error message if blank

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#7577]
main branch. Test VM. 
User accounts form: 

Email field needs 2 fixes: 
- [ ] add a red asterisk to indicate it's required
- [ ] add error messaging: if user leaves it blank and tries to save form, the field isn't highlighted.  a general error message `The form you submitted contains data entry errors` is displayed at top but nothing indicates where the error is in the form.

**Comment by ridz1208** [comment]
duplicata https://github.com/aces/Loris/issues/7746
