### ISSUE TITLE
[Manual Testing] media

### ISSUE THREAD

**Issue by driusan** [aces/Loris#7585]
## Tasks:
- [ ] Review issues from previous release testing
 
### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
- #7678
- #7679
- #7951
- #7970
  - #7207
   - #5464
   - #5135
   - #5134
   - #5079
   - #5055
   - #5046
   - #4956

## Comments
 - **insert comments here**
From Round 2: 
Followed the test plan and went through the issues. Didn't notice any issues when testing. Some comments on the following two issues:

https://github.com/aces/Loris/issues/5464

From what I can tell this has not been implemented but looking at the comments on the issue it did say this would be implemented for a future version
https://github.com/aces/Loris/issues/4956

Not tested (don’t have a tablet to test)
## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by jftunteng** [comment]
Followed the test plan and went through the issues. Didn't notice any issues when testing. Some comments on the following two issues: 

https://github.com/aces/Loris/issues/5464
* From what I can tell this has not been implemented but looking at the comments on the issue it did say this would be implemented for a future version 
https://github.com/aces/Loris/issues/4956
* Not tested (don’t have a tablet to test)

**Comment by suzanne-lee** [comment]
Module does not load due to timeout.

https://github.com/aces/Loris/issues/8033
