### ISSUE TITLE
[Manual Testing] BrainBrowser

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7592]
## Tasks:
- [ ] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - **list related issues/bugs here**
 - #8016

## Comments
 - **insert comments here**

## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by christinerogers** [comment]
works well.  will follow up on the fine points of the test plan shortly

**Comment by jesscall** [comment]
@jstirling91 I think it's related to the data that is mounted on CCNA-dev vm. Only a subset of the imaging files are there. Try for cand PKD2644

@CamilleBeau

**Comment by CamilleBeau** [comment]
> @jstirling91 I think it's related to the data that is mounted on CCNA-dev vm. Only a subset of the imaging files are there. Try for cand PKD2644
> 
> @CamilleBeau

@jesscall Jordan and I discussed that offline prior to this issue, I think he was already using PKD2644. Can you confirm @jstirling91 ?

**Comment by jstirling91** [comment]
@jesscall I was using that candidate. The issue seems to be an issue with permissions. I was able to navigate to the brain browser module, which would entail that I have the correct permissions, but the subsequent calls to load the data returned 403 forbidden
