### ISSUE TITLE
[Manual Testing] behavioural_qc

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7595]
## Tasks:
- [ ] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
**Previous reported issues**
- Help text should be updated #5504
- Update unclear test plan #7193 

**Newly reported issues**
- https://github.com/aces/Loris/issues/7926
- https://github.com/aces/Loris/issues/8037

## Comments
 - Was not able to follow test plan steps that required own site access (not all sites).

## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by charliehenrib** [comment]
@ridz1208 I can access all the sites even if I don't have permission for these sites 
(i.e. Make sure that the user accessible site data is only populated with the step 3 condition. - It is not the case).

**Comment by ridz1208** [comment]
@charliehenrib are you testing from the admin account ?

**Comment by charliehenrib** [comment]
@ridz1208 No, I created an account for myself using the admin account, and I am testing on a private window with chrome using my new account.

**Comment by ridz1208** [comment]
and you dont have the accross all sites permission ?

**Comment by charliehenrib** [comment]
@ridz1208 No, no access across all sites. 

#7926 Let me know if anything is missing for the ticket.
