### ISSUE TITLE
[Manual Testing] candidate_parameters

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#7607]
## Tasks:
- [ ] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - #7707 
 - #7708

## Comments
 - **Unable to fully test as I could not change permissions for my account. Will create a separate account with limited permissions and finish testing at a later date. However, inability to change permissions renders testing much more cumbersome.**

## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by xlecours** [comment]
Untestable item in testplan:
12. Remove the proband DoB. Check that the age difference field says that the age difference could not be calculated.

**Comment by xlecours** [comment]
I tested the features that does not require backend access.

**Comment by xlecours** [comment]
Not sure why this is still open.
