### ISSUE TITLE
Can not upload an attachment on Issue_Tracker : "PERMISSION DENIED"

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#7618]
**Describe the bug**
Testing for 24.0, created an issue, attached to a candidate and visit (DCC0103) V01. Submitted the issue succesfully, went back into the issue, to update and leave a comment and attach a doc. I got PERMISSION DENIED. I was using the admin account because I recieved an error trying to create my own account. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):

**What did you expect to happen?**

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)
- CHROME

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by ridz1208** [comment]
@kongtiaowang can you make sure this is not a filesystem misconfiguration (permissions writing into directory...)

**Comment by driusan** [comment]
@kongtiaowang can you reply to @ridz1208 ?

**Comment by kongtiaowang** [comment]
@driusan @ridz1208 @LeighMac it is a permisson issue. it has been fixed.
