### ISSUE TITLE
[Manual Testing] login

### ISSUE THREAD

**Issue by shonibare** [aces/Loris#7619]
## Tasks:
- [ ] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

###  First round testing issues
 - https://github.com/aces/Loris/issues/7577
 - https://github.com/aces/Loris/issues/7790

### Second round testing issues
**Request Account**
- [Test Case 2] #7897
- [Test Case 7] #7899

**Reset Password**
- [Test Case 9] #7723

## Comments
 - **insert comments here**

## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by ridz1208** [comment]
@shonibare have you finished testing this module ?

**Comment by shonibare** [comment]
Yes! @ridz1208

**Comment by ridz1208** [comment]
@shonibare can you please check the boxes that are done ?
