### ISSUE TITLE
[User Accounts] Unable to create new user 500 Error returned

### ISSUE THREAD

**Issue by jstirling91** [aces/Loris#7623]
**Describe the bug**
When creating a new user with all permissions, sites, and projects selected a 500 internal error is returned. 

**To Reproduce**
Steps to reproduce the behaviour (attach screenshots if applicable):
1. Login in as admin user
2. Go to User Accounts and select add user
3. Click  `Make user name match email address`
4. Click `Generate new password`
5. Enter valid First and Last Name
6. Enter and confirm valid email address
7. Select all Sites
8. Select all Projects
9. Select all Examiner At
10. Select Radiologist Yes Pending No
11. Select Pending Approval No
12. Select all Roles and Permissions

**What did you expect to happen?**
A new user to be created 

**Browser Environment (please complete the following information):**
- OS: Mac 11.5.2
- Browser Chrome
- Version 93.0.4577.82

**Server Environment (if known):**
- LORIS Version: 24.0.0
- Linux distribution and Version: on test vm
- MySQL/MariaDB Version: on test vm

**Additional context**
Example Payload:
```
NA_UserID: on
NA_Password: on
First_name: Jordan
Last_name: Stirling
Degree: 
Position_title: 
Institution: 
Department: 
Address: 
City: 
State: 
Country: 
Fax: 
Email: jordan.stirling@mcin.ca
SendEmail: on
__ConfirmEmail: jordan.stirling@mcin.ca
CenterIDs[]: 1
CenterIDs[]: 2
CenterIDs[]: 3
CenterIDs[]: 4
ProjectIDs[]: 1
ProjectIDs[]: 2
ProjectIDs[]: 3
ProjectIDs[]: 4
ex_1: on
ex_2: on
ex_3: on
ex_4: on
examiner_radiologist: Y
examiner_pending: N
Active: Y
active_from: 
active_to: 
Pending_approval: N
permID[1]: on
permID[2]: on
permID[3]: on
permID[4]: on
permID[5]: on
permID[6]: on
permID[8]: on
permID[9]: on
permID[10]: on
permID[11]: on
permID[12]: on
permID[13]: on
permID[17]: on
permID[18]: on
permID[19]: on
permID[22]: on
permID[23]: on
permID[24]: on
permID[25]: on
permID[28]: on
permID[29]: on
permID[31]: on
permID[32]: on
permID[33]: on
permID[34]: on
permID[35]: on
permID[36]: on
permID[37]: on
permID[38]: on
permID[39]: on
permID[40]: on
permID[41]: on
permID[42]: on
permID[43]: on
permID[44]: on
permID[45]: on
permID[46]: on
permID[47]: on
permID[48]: on
permID[49]: on
permID[50]: on
permID[51]: on
permID[52]: on
permID[53]: on
permID[54]: on
permID[55]: on
permID[56]: on
permID[57]: on
permID[58]: on
permID[59]: on
permID[60]: on
permID[61]: on
permID[62]: on
permID[63]: on
permID[64]: on
permID[65]: on
permID[66]: on
permID[67]: on
permID[68]: on
permID[69]: on
fire_away: Save
```

**Comment by PapillonMcGill** [comment]
In my case, I was not able to create an account with only a few permission.
Requested an account on the login page and went back in User Module with admin to give me permission and allow user.

**Comment by christinerogers** [comment]
Is this related to #7286 ?
