### ISSUE TITLE
User with no "Imaging Quality Control" permission can view the module

### ISSUE THREAD

**Issue by shonibare** [aces/Loris#7625]
**Describe the bug**
A clear and concise description of what the bug is

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Create a new user account with no “Quality Control access” permission.
2. login with the new user
3. Click on "Imaging Quality Control" and the user can view it

**What did you expect to happen?**
This module can be viewed if and only if the user has “Quality Control access” permission

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by suzanne-lee** [comment]
Bug cannot be reproduced; module was tested with superuser permission. Closing this ticket
