### ISSUE TITLE
[Manual Testing] bvl_feedback

### ISSUE THREAD

**Issue by AlexandraLivadas** [aces/Loris#7631]
## Tasks:
- [ ] Review issues from previous release testing

### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues

- #7665
- #7666
- #7190
- #7521 
- #7190
## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by xlecours** [comment]
Moving this one in the "Passed" column of Testing 24. The remaining issue https://github.com/aces/Loris/issues/7190 as been discussed in Testing 23 and the conclusion was that it would be a new feature instead of a bug fix.
