### ISSUE TITLE
[datadict] Missing automated tests

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#7648]
**Describe the bug**
- permission checks
- Description field is editable iff have edit permission
- Source From multiselect options contain all instruments
- filtering for Description Status = "Empty" returns rows all with no value in the Description column
- check column sorting
- check Clear Filter button
- data table pagination
- maximum rows per page selection

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):

**What did you expect to happen?**

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by racostas** [comment]
in testing round for 25.0 the aforementioned "automated test" are yet missing.

**Comment by regisoc** [comment]
@driusan I asked @kongtiaowang, he confirmed that this issue could be closed.
