### ISSUE TITLE
Make fails due to linting error

### ISSUE THREAD

**Issue by dmwelch** [aces/Loris#7651]
**Describe the bug**
Running `make` fails due to an unused variable in `jsx/Forms.jsx` line 1548 in Loris v23.0.6.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Start with a fresh system (e.g. Ubuntu 20.04.3 LTS)
2. Follow install steps from README
3. On the step 4 "Run the makefile (use make dev if you are setting up a development sandbox)", run `make`.
4. Output is: 
```
$ make: *** [Makefile:15: javascript] Error 2
```

**What did you expect to happen?**
Production builds should not fail for trivial linting errors.

**Browser Environment (please complete the following information):**
N/A

**Server Environment (if known):**
- LORIS Version: 23.0.6
- Linux distribution and Version: Ubuntu 20.04.3 LTS
- MySQL/MariaDB Version: N/A

**Additional context**
Running `npm run compile | grep "no-unused"` you can see that the error is due to an unused variable in Form.jsx.  Remove it and compiling completes.

**Comment by driusan** [comment]
Fixed by #7580.. I'll do a quick 23.0.7 release to make it more easily accessible

**Comment by driusan** [comment]
Can you try 23.0.7? It should fix this problem.

https://github.com/aces/Loris/releases/tag/v23.0.7

**Comment by christinerogers** [comment]
Hi @dmwelch  - Thanks very much for the bug report.  
We believe this issue has been resolved by the latest release: https://github.com/aces/Loris/releases/tag/v23.0.7

We'd love to have your confirmation - does this issue persist for you?  If so, please let us know here and we'll re-open the issue.  
Will close this issue for now, and keep tabs on this bug report.
