### ISSUE TITLE
[Candidate_profile] instrument link not working 

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#7652]
**Describe the bug**
click the link, got 500 error
**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'https://test-loris-dev.loris.ca/candidate_profile/******/' (***** as candID)
<img width="693" alt="截屏2021-09-29 下午5 34 20" src="https://user-images.githubusercontent.com/9876007/135351787-3ed68400-a5dd-4476-959f-189a9b7378f1.png">
2. Click on any 'instrument link'
3. See error

**What did you expect to happen?**
show the linstrument page
**Browser Environment (please complete the following information):**
- OS: mac
- Browser chrome
- Version pre-24 main branch

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: pre-24
- Linux distribution and Version: ubuntu 20
- MySQL/MariaDB Version: MariaDB 10.3

**Additional context**

**Comment by driusan** [comment]
This was fixed by #7725
