### ISSUE TITLE
[user_accounts] Missing error message when assigning permissions as superuser

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#7657]
**Describe the bug**
When a superuser, that only have the "highlander" permission, adds permissions to an other user, there is no error message even though nothing happens in the backend. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
0. As a superuser that only have the "highlander" permission.
1. Go to '/user_accounts/edit_user/{any_user_id}'
2. Add permissions
3. Scroll down to click Save.
4. See no error message

**What did you expect to happen?**
A message saying "Unable to add permission X; you don't have that permission."

**Browser Environment (please complete the following information):**
- On test vm, any browser.

**Comment by AlexandraLivadas** [comment]
Resolved by #7808
