### ISSUE TITLE
[bvl_feedback] Module cannot be accessed on instrument page

### ISSUE THREAD

**Issue by AlexandraLivadas** [aces/Loris#7665]
The "pencil" icon to open the behavioural feedback module does not appear on the sidebar of an instrument form, but it does appear on a candidate's profile page or on the timepoint page. 

**To Reproduce**
1. Go to a candidate's profile (one with pre-existing visits)
2. See that the pencil icon is in the top right corner and that it opens bvl_feedback
3. Click on a timepoint and then select an instrument
4. See that when on an instrument page, there is no pencil icon or option to open bvl_feedback

**What did you expect to happen?**
The bvl_feedback module should be accessible from an instrument form page

**Comment by driusan** [comment]
Should be fixed by #7761, can you test?
