### ISSUE TITLE
Running `make` fails due to missing dependency for EEG

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#7669]
**Describe the bug**
Running `make` or `make dev` fails because a dependency for EEG (https://github.com/aces/Loris/tree/main/modules/electrophysiology_browser/jsx/react-series-data-viewer) is missing:

```
Protocol Buffers To install the Protocol Buffers Compiler (protoc), run: apt install -y protobuf-compiler
```
Is this something that should be included outside the module at a higher level in LORIS?

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):

**What did you expect to happen?**

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by laemtl** [comment]
Fixed in #7676
