### ISSUE TITLE
[survey_accounts] Existing BMI surveys not appearing in survey_accounts

### ISSUE THREAD

**Issue by suzanne-lee** [aces/Loris#7672]
**Describe the bug**
When looking at the survey_accounts module, not all instances of the BMI survey appear in the list. Before testing, there appeared to be 0 BMI surveys. The few that appear were made by me during testing. However, if you look at candidates' test batteries through Access Profile, you can find some BMI surveys that don't appear in survey_accounts.

**To Reproduce**
1. Go to the survey_accounts module and filter for candidate DCC090 and BMI Calculator. Note that there is only one BMI survey listed (at V2). 
<img width="1304" alt="DCC090 on Survey Accounts" src="https://user-images.githubusercontent.com/29237731/135756064-e6cf7fb0-814d-408b-8a3e-8c04435eb140.png">

2. Go to Access Profile and click on candidate DCC090. It has the following timepoints: V1, V2, V3
3. Click on V1. You will see BMI Calculator listed in the battery. 

<img width="795" alt="DCC090 Instrument Battery" src="https://user-images.githubusercontent.com/29237731/135756111-5a83e9dc-3f84-4c33-927a-30aace21ab74.png">

**What did you expect to happen?**
When looking at the survey list on survey_accounts, I expected to see several existing BMI calculator surveys, however, there appeared to be none (before testing). Initially, I thought this was an issue of incomplete Raisinbread data, but found existing BMI surveys through Access Profile.

**Additional context**
This bug is reproducible on demo.loris.ca as well.

**Comment by suzanne-lee** [comment]
Confirmed that newly created surveys appear in both the `bmi` and `flag` tables

**Comment by ridz1208** [comment]
@driusan I think we should close this. I don't see a good way to recover the RB data nor do i see the need for it

**Comment by driusan** [comment]
can we delete the existing ones and add new ones to RB so that it's internally consistent doesn't come up again next testing round?

**Comment by ridz1208** [comment]
@driusan I think `assign_missing_instruemnts` will re insert all of them

**Comment by driusan** [comment]
But `assign_missing_instruments` shouldn't be inserting survey instruments, because survey instruments aren't supposed to be in the test battery with the current survey logic.

**Comment by SantiagoTG** [comment]
Did not have issue when testing for 'Mild Behavioral Impairment Checklist (MBI-C) (CTU)' in CCNA. All existing surveys for a given candidate appeared when making a search for the instrument.
