### ISSUE TITLE
[Data Query Tool (Beta)] Saved queries show fields for private but not for public queries

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#7684]
**Describe the bug**
Saved queries are displayed differently if saved privately or publicly. Private queries show all fields selected, whereas public queries do not.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'Data Query Tool (Beta)' module
2. Click on 'Load Existing Query' and compare 'User' and 'Shared' saved queries.

**What did you expect to happen?**
'User' and 'Shared' saved queries should be displayed in the same way.

**Browser Environment (please complete the following information):**
- Browser: Chrome

**Server Environment (if known):**
- LORIS Version: v24.0 testing

![Screen Shot 2021-10-04 at 7 56 11 PM](https://user-images.githubusercontent.com/54332302/135940488-2c4dffe2-95e5-4661-bb56-216841938106.png)

**Comment by maltheism** [comment]
@ridz1208 this was fixed on cbigr but I somehow forgot about it.
