### ISSUE TITLE
[DQT & Data Query Tool (Beta)] Running query with a filter shows results that should have been filtered out

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#7685]
**Describe the bug**
For both the older version of the DQT and the 'Data Query Tool (Beta)', running a query after defining a filter shows results that should have been filtered out.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to either the older version of the DQT and the 'Data Query Tool (Beta)'
2. On the 'Define Fields' tab create a query by selecting an instrument and fields (eg. AOSI, all fields)
3. On the 'Define Filters' tab, create a filter (eg. AOSI, 'Administration' = 'All')
4. Run the query. The results table will display results that should have been filtered out.

**What did you expect to happen?**
All results in the results table should correspond to the criteria established for the filter.

**Browser Environment (please complete the following information):**
- Browser: Chrome

**Server Environment (if known):**
- LORIS Version: v24.0 testing

**Comment by SantiagoTG** [comment]
![Screen Shot 2021-10-04 at 8 18 57 PM](https://user-images.githubusercontent.com/54332302/136074443-ad42f8f3-bff1-4771-ac3d-2059d23e4c3a.png)

![Screen Shot 2021-10-04 at 8 18 51 PM](https://user-images.githubusercontent.com/54332302/136074479-4686af59-d67f-44d7-8cf6-68f92130c45c.png)


![Screen Shot 2021-10-04 at 8 24 53 PM](https://user-images.githubusercontent.com/54332302/136074317-0c3a9457-27df-45a9-82bb-fece3b40e847.png)

![Screen Shot 2021-10-04 at 8 25 00 PM](https://user-images.githubusercontent.com/54332302/136074319-415c5e0b-9005-498c-b664-624d6a56b700.png)

**Comment by driusan** [comment]
Discussed at roadmap meeting. It's confusing to the users, and the easiest solution is probably to change "All Visits" to "At least one visit" in the dropdown for which visit the filter matches.

**Comment by maltheism** [comment]
@driusan @ridz1208 I've done the code for this change before of only the first visit in the dropdown selected.

**Comment by maltheism** [comment]
@driusan @ridz1208 solved in this PR: https://github.com/aces/Loris/pull/7516
