### ISSUE TITLE
[configuration|SQL] What is ConfigSettings ID #26 ?

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#7691]
**Describe the bug**
I don't know under which parent ConfigSettings should the `IssueTrackerDataPath` be. `paths`?

see: https://github.com/aces/Loris/blob/main/SQL/0000-00-03-ConfigTables.sql#L129

This makes that configuration not editable in the configuration modules because `ConfigSettings.ID = 26 ` might not be a "Parent". Or in the best scenario, it will show up under a random parent. On the testing vm, its parent is `usePwnedPasswordsAPI` which is not a Parent configsettings.

**Comment by driusan** [comment]
In my database (RB) 26 = "paths", so that seems like a safe guess.

**Comment by xlecours** [comment]
That line https://github.com/aces/Loris/blob/main/SQL/0000-00-03-ConfigTables.sql#L129
should be 
```
INSERT INTO ConfigSettings (Name, Description, Visible, AllowMultiple, DataType, Parent, Label, OrderNumber) SELECT 'IssueTrackerDataPath', 'Path to Issue Tracker data files', 1, 0, 'web_path', ID, 'Issue Tracker Data Path', 8 FROM ConfigSettings WHERE Name="paths";
```
