### ISSUE TITLE
[candidate_profile] Behavioural Data Instrument link doesn't work

### ISSUE THREAD

**Issue by jstirling91** [aces/Loris#7699]
**Describe the bug**
When view the instruments for a select visit in the Behavioural Data dashlet, the link directs you to the instruments URL but is missing the `candID` and `sessionID` in the URL so leads to a 500 error when launched.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to Beta version of the Access Profile
2. Select a candidate
3. In the Behavioural Data dashlet click on a visit card but not the visit label
4. Click on an instrument to open

**What did you expect to happen?**
Clicking on the instrument should have opened the selected instrument for the candidate's timepoint.

**Browser Environment (please complete the following information):**
- OS: Mac
- Browser Chrome

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: 23.0.6
- Linux distribution and Version: Ubuntu 18.04
- MySQL/MariaDB Version: MySQL 5.7

**Additional context**

**Comment by driusan** [comment]
I had the same problem with RB and it should be fixed by #7725
