### ISSUE TITLE
[my_preferences] default Notifications don't interact with Permissions 

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#7704]
Not critical for the release, but a bug in the Notifications feature : 

A user with no access to the Media module can see in the My Preferences module that they will get notifications about the Media module.   (Same happens for Publications and DocRepo module permissions/notifs)

2 bugs: 
- they shouldn't be able to see this. 
- By default they shouldn't have these notifications set. 

(also on TestVM these notifications don't seem to be working #7705 given proper permissions, so I can't test if they actually get a notification.)

**Comment by cmadjar** [comment]
@samirdas will think about this one.

**Comment by christinerogers** [comment]
Samir might still be thinking about this one... 
will likely be more important after Project Permissions #7415 - closing for now, clearly low priority as a bug
