### ISSUE TITLE
Some Notifications on Test VM aren't working : doc repo upload etc

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#7705]
Notifications for doc repo upload or media upload aren't working on the Test VM. 
(They should be set for my user accordign to the My preferences module)

But: User account notifications seem to be working fine (e.g. notifying an admin when another user's permissions are created, account request, etc) 

cc @kongtiaowang is this a known issue with the Test VM setup?

**Comment by kongtiaowang** [comment]
It all works on 24.0-release VM, I think this one was old issue for 23.0-release test.
