### ISSUE TITLE
[User Accounts] User not removed from Examiner List in Instrument

### ISSUE THREAD

**Issue by jstirling91** [aces/Loris#7722]
**Describe the bug**
When removing a user as an examiner from a site, the user still is present in the examiner list in the instrument

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to user accounts and select a user to edit
2. Add a them as an examiner to a site
3. In new window, open up a instrument for a candidate of the selected site in the step above
4. Ensure the user is in the examiner dropdown 
5. In previous window, remove the user as examiner from the site
6. Go to instrument window and open the dropdown
7. Examiner is still listed when it shouldn't be

**What did you expect to happen?**
When a user isn't an examiner for a specific site, they shouldn't be listed in the examiner dropdown

**Browser Environment (please complete the following information):**
- OS: MacOS
- Browser chrome

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by ridz1208** [comment]
@jstirling91 that is normal behaviour. We don't have a way currently to remove that examiner from prospective instruments without removing the examiner from previous ones.
