### ISSUE TITLE
[Configuration] Unable to set Pwned configuration

### ISSUE THREAD

**Issue by jstirling91** [aces/Loris#7723]
**Describe the bug**
When trying to set the Pwned configuration, there is no form input to set it. See screen shot
<img width="994" alt="Screen Shot 2021-10-18 at 8 46 33 AM" src="https://user-images.githubusercontent.com/2818503/137735290-b2c7604a-deeb-4b54-bf2c-7c98974c133f.png">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to configuration module
2. Select Study configuration tab
3. Scroll down to Pwned configuration
4. See screen shot above for UX error

**What did you expect to happen?**
Should see a radio button with options yes/no. See screenshot below

<img width="409" alt="Screen Shot 2021-10-18 at 9 08 51 AM" src="https://user-images.githubusercontent.com/2818503/137737439-65935c2a-4ce3-4030-b8f3-de4b3a902402.png">

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by laemtl** [comment]
Unable to reproduce
