### ISSUE TITLE
[User Accounts] No feedback on duplicate email error on new user

### ISSUE THREAD

**Issue by jstirling91** [aces/Loris#7724]
**Describe the bug**
When creating a new user with an email already associated to another user, the form says `The form you submitted contains data entry errors` but there is not indication on the form what is causing the error. See screen shot below

<img width="848" alt="Screen Shot 2021-10-18 at 9 14 15 AM" src="https://user-images.githubusercontent.com/2818503/137738290-11120be7-ef6a-4485-8186-76be25d57b2b.png">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to User Accounts
2. Select Add User
3. File out the form with new username and other required information
4. For the email fields, use an email already in use
5. Submit the form

**What did you expect to happen?**
A clear indication that the email is already in use

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by ridz1208** [comment]
@jstirling91 might have been fixed by https://github.com/aces/Loris/pull/7789

could you confirm?
