### ISSUE TITLE
[create_timepoint] First visit in list automatically selected

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7728]
**Describe the bug**
When creating a new timepoint, as soon as a subproject is selected, the first visit in the list of visits is automatically chosen in the drop down. This is very error prone behaviour. the user must explicitly select a visit instead and not risk relying on the preselected value.

@CamilleBeau have you noticed this behaviour in your testing ??

**Comment by maltheism** [comment]
@ridz1208 @CamilleBeau please see the following PR for the fix: https://github.com/aces/Loris/pull/7770
