### ISSUE TITLE
Clean up `Alias` vs `MRI alias`

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#7768]
from Nov.2 LORIS meeting discussion - 

This would be good to clean up for the 25 release.  

See Dave's comments https://github.com/aces/Loris/pull/7466#discussion_r737792262

Some background on these 2 columns from the `psc` table: 
* `Alias` is used by User Accounts, New Profile, Survey Accounts, TimepointList - [examples here](https://github.com/aces/Loris/pull/7466#discussion_r738439767)
** e.g. to populate the [site(s) dropdown when creating a new User](https://github.com/aces/Loris/blob/23.0-release/modules/user_accounts/php/edit_user.class.inc#L809)
* `MRI alias` is used extensively by the loris-mri pipeline (per Cecile) - [documented here](https://github.com/aces/Loris-MRI/blob/23.0-release/docs/02-Install.md#221-database)
   
Historically for some studies, not all sites are Imaging sites. That's why `MRI alias` was always a separate db field in the `psc` table.

**Comment by christinerogers** [comment]
still relevant but hasn't been a priority for years. ok to close @driusan @cmadjar ?

**Comment by cmadjar** [comment]
I feel like we have bigger fishes to fry ;). @driusan like you prefer. Happy to close the issue. We could always reopen it if this comes up again.

**Comment by driusan** [comment]
consensus seems to be to close this issue.

**Comment by christinerogers** [comment]
re-closing as not-planned
