### ISSUE TITLE
[Media] File duplicate detected even when extension is different

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7774]
**Describe the bug**
The Media uploader seems to only be matching the filename when checking for duplication. I don't see why 2 files with the same name but different extensions would not be accepted

Example: `DCC090_V1_bmi.txt` and `DCC090_V1_bmi.png`
![Screenshot from 2021-11-03 11-27-19](https://user-images.githubusercontent.com/15268287/140188866-78aa2853-5d2c-47b1-b7ff-11850bcbc9f4.png)
![Screenshot from 2021-11-03 11-27-39](https://user-images.githubusercontent.com/15268287/140188867-cc45f8d6-1516-4651-bfc8-a099eeded518.png)

**Comment by ridz1208** [comment]
@CamilleBeau @jesscall is that a usecase that occurs for CCNA ? should it be tagged critical to be fixed for this release ?

**Comment by jesscall** [comment]
@ridz1208  The screenshot of your error looks unrelated to the bug?

**Comment by ridz1208** [comment]
@you are right and I can't seem to be able to reproduce on test. will close until I reconfirm
