### ISSUE TITLE
[login/request account] Weird ordering of projects in dropdown

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7790]
**Describe the bug**
when requesting a new account the dropdown for projects displays the first option BEFORE the "choose you project:" placeholder (see image)
<img width="1172" alt="Screen Shot 2021-11-05 at 1 22 40 PM" src="https://user-images.githubusercontent.com/15268287/140553420-8d77807e-790a-4b35-a345-350e58333617.png">

**Comment by maltheism** [comment]
@ridz1208 that's because the dropdown order always ends up being alphabetical. I'm unsure what's causing it because I don't believe it's default behaviour of html select options.

**Comment by ridz1208** [comment]
First time I see this, and we need a solution, this looks super amateur

**Comment by maltheism** [comment]
Might be jquery doing it somehow.

**Comment by driusan** [comment]
There's a sortByValue prop in the SelectElement that defaults to true. Set it to false in `modules/login/jsx/requestAccount.js` (note: I didn't test this, but it should work..):

```
          <SelectElement
            name={'site'}
            options={this.props.data.site}
            value={this.state.form.value.site}
            onUserInput={this.setForm}
            emptyOption={false}
            required={true}
            sortByValue={false}
          />
          <SelectElement
            name={'project'}
            options={this.props.data.project}
            value={this.state.form.value.project}
            onUserInput={this.setForm}
            emptyOption={false}
            required={true}
            sortByValue={false}
          />
```

**Comment by ridz1208** [comment]
It would still be good to sort it by value... I just think the placeholder should be a placeholder and not a value

**Comment by maltheism** [comment]
@ridz1208 I think that can be done like:
```
<select>
    <option value="" disabled selected>Choose your project:</option>
    <option value="example project">example project</option>
</select>
```

**Comment by driusan** [comment]
I don't really see why "Choose your xxx" is a choice in the dropdown. The SelectElement React element doesn't have an option to sort only some options.

**Comment by ridz1208** [comment]
@maltheism make it happen !!

**Comment by maltheism** [comment]
@driusan that's because the login page has selection options without labels for the design of it. So the Choose your xxx is the label.
<img width="376" alt="Screen Shot 2021-11-05 at 1 52 16 PM" src="https://user-images.githubusercontent.com/16293415/140556187-00b4df03-a1c5-48f1-9b7e-5d4779615f02.png">
