### ISSUE TITLE
[user_accounts] Very strange organization of permissions on user_accounts page

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7791]
**Describe the bug**
While approving a new user, this is the list of permissions I get (see below)
<img width="1656" alt="Screen Shot 2021-11-05 at 1 32 26 PM" src="https://user-images.githubusercontent.com/15268287/140554025-8b08649d-9acb-4b05-9d72-a003a96f99ee.png">

**Comment by maltheism** [comment]
@ridz1208 that whole page is done in smarty. It probably should be converted to react.

**Comment by ridz1208** [comment]
@maltheism it should but i'm sure we can find a quick fix before that for this release
