### ISSUE TITLE
[Issue tracker] Can not access module

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#7799]
**Describe the bug**

The module loads normally with admin user or a user with super permissions. However, if I attempt to access the module from a user that has both issue tracker permissions and no other permissions, I get "An error occured while loading the page" as well as the following in my error log:

`[Mon Nov 08 11:20:12.936860 2021] [php7:error] [pid 4627] [client ::1:44026] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to User::hasCenter() must be an instance of CenterID, int given, called in /var/www/loris/src/Data/Filters/UserSiteMatch.php on line 48 and defined in /var/www/loris/php/libraries/User.class.inc:433\nStack trace:\n#0 /var/www/loris/src/Data/Filters/UserSiteMatch.php(48): User->hasCenter()\n#1 /var/www/loris/src/Data/ProvisionerInstance.php(129): LORIS\\Data\\Filters\\UserSiteMatch->filter()\n#2 [internal function]: LORIS\\Data\\ProvisionerInstance->LORIS\\Data\\{closure}()\n#3 [internal function]: CallbackFilterIterator->accept()\n#4 [internal function]: FilterIterator->rewind()\n#5 /var/www/loris/src/Data/Table.php(83): IteratorIterator->rewind()\n#6 /var/www/loris/src/Data/Table.php(98): LORIS\\Data\\Table->toArray()\n#7 /var/www/loris/modules/issue_tracker/php/issue_tracker.class.inc(203): LORIS\\Data\\Table->toJSON()\n#8 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(648): LORIS\\issue_tracker\\Issue_Tracker->toJSON()\n#9 /var/www/loris/php/libraries/NDB_Page.class.inc(753): NDB_Menu in /var/www/loris/php/libraries/User.class.inc on line 433, referer: http://localhost:8080/issue_tracker/
`

![image](https://user-images.githubusercontent.com/51176779/140781615-e669ceed-74a3-4ccf-acac-5448e2405498.png)

I found this bug while manually testing a PR and then noticed it is also a bug on main branch. Tested on my VM with raisinbread data as well as on test-loris-dev.loris.ca

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Create a user with only the issue tracker permissions
2. Log in with that user
3. Navigate to issue tracker module

**Comment by ridz1208** [comment]
@CamilleBeau already reported https://github.com/aces/Loris/issues/7798

**Comment by ridz1208** [comment]
Treating it as separate issue
