### ISSUE TITLE
[Issue tracker] No space before user in Comments & History

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#7800]
**Describe the bug**
There is no space between "Updated by" and the user name in the Comments and History section of the edit issue page.
![image](https://user-images.githubusercontent.com/51176779/140784563-43c7d6f8-d73a-42fa-a7c0-07b0ace90856.png)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to any issue
2. Update issue
3. Scroll down to look at comments and history section of recently updated issue

**Comment by driusan** [comment]
It looks like there's whitespace in the template, so I think it's just the CSS that needs to be fixed up.

https://github.com/aces/Loris/blob/main/modules/issue_tracker/jsx/CommentList.js#L87-L89
