### ISSUE TITLE
[document_repository] Step 17 of TestPlan inaccurate

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#7868]
**Describe the bug**
In Step 17 of the TestPlan, it is specified that clicking on a document from the document repository panel in the dashboard should open it in the browser. When I clicked on the row, it downloaded.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to Dashboard
2. Click on a row from the document repository panel
3. See that it is downloaded, not displayed

**What did you expect to happen?**
The TestPlan to specify that the document will be downloaded by clicking on it. 

**Browser Environment (please complete the following information):**
- Browser: Chrome
- Version 96

**Comment by kongtiaowang** [comment]
There are not uploaded files in the document_repository, all the data come from the RB data. 
You need to upload a new file then try to download it. 
<img width="740" alt="截屏2021-12-09 上午9 22 14" src="https://user-images.githubusercontent.com/9876007/145414028-afa688ae-e053-4e1e-b737-e7d04bb20792.png">
