### ISSUE TITLE
[next_stage] Instrument with firstVisit='N' inserted at first timepoint

### ISSUE THREAD

**Issue by AlexandraLivadas** [aces/Loris#7872]
**Describe the bug**
See test plan [step 8](https://github.com/aces/Loris/blob/main/modules/next_stage/test/TestPlan.md). When an instrument in the test_battery has `firstVisit = N`, the instrument still appears in the instrument list of a timepoint if it is the first timepoint.

**Expected Behaviour:** The instrument with `firstVisit=N` should not appear for the first visit.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to the Battery Manager module and search for a test_battery with `firstVisit=N`
2. Create a candidate with the same age range, subproject, and site as the test_battery
3. Create the first timepoint for this candidate and select the visit label that matches the test_battery
4. Start the visit stage
4. See that the instrument appears in the instrument list

**Comment by ridz1208** [comment]
@AlexandraLivadas The `FirstVisit` functionality seems to be working fine on my end. Here are the steps I used to test it

1. I chose the Medical History instrument in the battery manager
<img width="1566" alt="Screen Shot 2021-12-16 at 11 01 54 AM" src="https://user-images.githubusercontent.com/15268287/146405923-8f6b808f-e697-44dd-9e4f-55fab6158e6d.png">

2.  I chose a candidate with no timepoints
3. I created timepoint V3 with subproject "Fresh" to match medical history entry
4. Started the stage, no instruments populated
<img width="1470" alt="Screen Shot 2021-12-16 at 11 02 23 AM" src="https://user-images.githubusercontent.com/15268287/146406004-7cb01850-b856-4f17-94d1-d95fee40264d.png">
 
For additional testing, I switched the test_battery entry to firstvisit=NULL and ran assign_missing_instruments.php in the back end and got the following:
```
root@test-loris-dev:/var/www/Loris/tools# php assign_missing_instruments.php 

 CandID: 307082  Visit Label:  V3
Missing Instruments:
Array
(
    [0] => medical_history
)
```

Please test again and close the ticket if your test results match mine

**Comment by AlexandraLivadas** [comment]
@ridz1208 I got the same results as you. I'm going to test with a few more battery entries before closing the issue because I'm not sure how I found this bug.
