### ISSUE TITLE
[imaging_browser] The Download table as CSV is retrieving more information that's what's shown in the Web Browser.

### ISSUE THREAD

**Issue by racostas** [aces/Loris#7876]
**Describe the bug**
The Download table as CSV is retrieving more information that's what's shown in the Web Browser.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `MainMenu->Imaging->Imaging Browser`
2. Click on the `Download table as CSV` button.
4. The excel file downloaded have more (different columns) than the ones shown in the web browser. The last column is shown incorrect info. 
![image](https://user-images.githubusercontent.com/37309344/144879569-34adb96c-14e3-4471-99ee-4e2137f2dd1c.png)

**What did you expect to happen?**
The excel file to reflect the same info as the web browser. 

**Browser Environment (please complete the following information):**
- Microsoft Windows 10
- Google Chrome Version 96.0.4664.45 (Official Build) (64-bit)

**Server Environment (if known):**
- LORIS 24 official testing VM.

**Comment by laemtl** [comment]
Seing additional columns is expected if some are hidden in the data table. @cmadjar will look at the missing header issue.

**Comment by cmadjar** [comment]
Resolved by #8363. Not sure why this did not auto-close.
