### ISSUE TITLE
[Publication] Empty 'Browse' field can't be removed

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#7878]
**Describe the bug**
When creating a new proposal, after entering all the fields, selecting a file from the 'Browse' button will display publication fields. However, if the 'Browse' field is entered again and instead of selecting a file, the user cancels the browse window, the selected file and publication fields disappear. However, the new 'Browse' field ( if 2nd or 3rd 'File to upload') remains empty and can't be removed. Trying to submit leads to the following error:
- Attempt to use pselectRow on a query that returns multiple rows

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'Publication module and acces the propse a project tab. Enter all relevant fields and at the bottom select a file. Then open the browse option again and hit cancel (this can happen for the first or subsequent browse windows). The browse field appears empty but submitting the proposal leads to error'.

**What did you expect to happen?**
Clicking on cancel in the browser window should remove the selected file and clear the options and browse field (except if first field). Clicking on the 'Propose project' button should allow to create the proposal.

**Comment by SantiagoTG** [comment]
![Uploading Screen Shot 2021-12-06 at 11.15.25 PM.png…]()

**Comment by regisoc** [comment]
Cannot reproduce, tested on chromium (110.0.5481.77) and firefox (110.0).
