### ISSUE TITLE
[imaging_qc] Doesn't Sort by certain column headers (e.g. tarchive...)

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#7879]
imaging qc module in test-loris-dev 24 : Minor bug

For the following column headers: 
* MRI parameter form (see description below)
* Tarchive column

Example of how to reproduce / Description of issue: 
There are both Complete and Incomplete values in the MRI Parameter Form column in the data table. 
Clicking on the column header should toggle between sort order - but it doesn't, it just re-sorts so that "Incomplete" is at top all the time.

**Comment by ridz1208** [comment]
seems to have been fixed in 24.1 (see demo.loris.ca) @christinerogers can you confirm?

**Comment by christinerogers** [comment]
confirmed on https://test-loris-dev.loris.ca/imaging_qc/ -- looks resolved
