### ISSUE TITLE
[Issue Tracker] When updating the status of ticket, Error appears even though ticket is updated

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#7881]
**Describe the bug**
When trying to update or change the status of a ticket, clicking on 'Update Issue' displays a 'Failed to submit issue :('. However, the ticket is updated according to specifications. The user is lead to believe that information was not successfully submitted, but information does appear to be modified. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'Issue Tracker and create a ticket. After successful creation, access the ticket and change the 'Status' field (or any other field). When the 'Update Issue' is clicked, the error message is displayed.' 

**What did you expect to happen?**
A Success message should be displayed instead of the error message.

![Screen Shot 2021-12-06 at 11 58 36 PM](https://user-images.githubusercontent.com/54332302/144969826-5838d406-633b-49fa-ad07-61c39da4b1cc.png)

**Comment by maltheism** [comment]
Hi @SantiagoTG, I think the following PR will solve this issue. #7852
