### ISSUE TITLE
[instruments] The examiner dropdown in the Top page of the instruments in taking by default the value of the firth alphabetical available.

### ISSUE THREAD

**Issue by racostas** [aces/Loris#7885]
**Describe the bug**
When starting filling a brand new instrument the examiner dropdown in the Top page of the instruments is showing by default the value of the firth alphabetical examiner available.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to the` candidate_list` in the `MainMenu`
2. Click on a PSCID to get to the `timepoint_list `module
3. Click on a timepoint to get to the `instrument_list `module
4. Click on an instrument that have not been started yet (status field in blank) to access the instrument itself.
5. Notice the Examiner dropdown is filled with the first alphabetically available examiner. 

**What did you expect to happen?**
In step 5 the default dropdown value should be Null ( a blank in the dropdown).

**Browser Environment (please complete the following information):**
- Microsoft Windows 10
- Google Chrome Version 96.0.4664.45 (Official Build) (64-bit)

**Server Environment (if known):**
- LORIS 24 official testing VM.

**Comment by ridz1208** [comment]
solved by https://github.com/aces/Loris/pull/7967
