### ISSUE TITLE
[electrophysiology_browser][24.0 Testing] Changes to annotations reflected in download

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7890]
**Describe the bug**
Test Plan:
> 13. Test that if changes have been made to the session's annotations, the downloaded annotation files are correctly updated to match [Manual Testing]

This is not currently implemented in main, but there are 2 PRs open that can resolve this.
#7828 and #7829 need merge

**Comment by ridz1208** [comment]
PRs linked to the linked PRs have been merged
