### ISSUE TITLE
[instrument

### ISSUE THREAD

**Issue by racostas** [aces/Loris#7892]
**Describe the bug**
 The instrument page is not refreshing when the date from one instrument is deleted. When the instrument data is deleted the page is not refreshed. **IMPORTANT:** Please note that the data itself it is deleted. If the page is refreshed it will be notice that the info have been properly erased. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to the `candidate_list `in the `MainMenu`
2. Click on a PSCID to get to the `timepoint_list `module
3. Click on a timepoint to get to the `instrument_list `module
4. Click on any listed instrument
5. Click on the 'Delete instrument data' button on the left pane (only visible when the user has the 'Send to DCC' permission and appropriate config in the backend)
6. A message is prompt to confirm: please confirm. **Be careful Notice this will be erasing the data in the instrument.**
7.  Notice the data is already shown in the instrument. (but it was in facts deleted, if the page is refreshed no data will appear) 
![image](https://user-images.githubusercontent.com/37309344/145071142-e8f605ab-3a32-4c7c-baeb-c998549a9d4b.png)

**What did you expect to happen?**
The instrument to be refreshed. No data shown after deleting it.

**Browser Environment (please complete the following information):**
- Microsoft Windows 10
- Google Chrome Version 96.0.4664.45 (Official Build) (64-bit)

**Server Environment (if known):**
- LORIS 24 official testing VM.

**Comment by kongtiaowang** [comment]
PR is ready.
