### ISSUE TITLE
[data_release] Version column only sorts in 1 direction

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#7894]
**Describe the bug**
Every other column can be sorted in ascending and descending order by clicking on the column once or twice respectively. For the Version column, clicking on it once sorts it, and then clicking again sorts according to row number.

**After clicking once:**
![image](https://user-images.githubusercontent.com/51176779/145075985-b0dbba55-421d-4c81-bb30-cef15e6adf68.png)
**After clicking again:**
![image](https://user-images.githubusercontent.com/51176779/145076057-55158296-f403-467d-9068-ba2295295578.png)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to data release
2. Upload files with multiple versions: some that are only numbers, some that start with letters, and some with the same version
3. Click on "Version" column to sort it once, and then click again

**What did you expect to happen?**
The table to sort by version in ascending order by Version when clicked once, and then descending order when clicked again.

**Comment by kongtiaowang** [comment]
https://github.com/aces/Loris/pull/7907

**Comment by CamilleBeau** [comment]
resolved
