### ISSUE TITLE
[Login] Dashboard link to Pending account approval count does not match User accounts

### ISSUE THREAD

**Issue by jstirling91** [aces/Loris#7899]
**Describe the bug**
When clicking on the pending account approval task, which lists 1, launches the user accounts page. The user accounts page list is empty.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Request a new account to site DCC and project DCP
2. Using admin account, create new account with Site set to DCC and project Pumpernickel
3. Set permission of new user to `User Accounts: View/Create/Edit User Accounts - Own Sites`
4. Login as new user
5. Click on `Pending account approval`. This count should be at least 1

**What did you expect to happen?**
You should see the the same count as the dashboard but you don't see the one you requested in step 1 above.

**Browser Environment (please complete the following information):**
- OS: Mac
- Browser Chrome

**Server Environment (if known):**
Loris Test VM

**Additional context**

**Comment by racostas** [comment]
in 25.0 testing this issue was not found.

**Comment by racostas** [comment]
@driusan, we can close this one.
