### ISSUE TITLE
[user_accounts] Random "none" on the page when adding new user

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7912]
**Describe the bug**
The `None` displayed on the page (see screenshot) is normally adjacent to the `Account Request Date` label. for some reason on a new user the label does not show but the "none" does

<img width="505" alt="Screen Shot 2021-12-10 at 4 33 17 PM" src="https://user-images.githubusercontent.com/15268287/145645427-81bd6a7b-795c-4af0-b627-28b31d100c9a.png">

**Comment by maltheism** [comment]
Hi @ridz1208, I'm having trouble duplicating this bug. I made a new user from the login page and I even made a new user as admin using the user_accounts module. Both new users don't display the bug. Are you able to replicate it again and if so what are the steps different than what I did?

**Comment by ridz1208** [comment]
@maltheism it's while you are making the new user that the `none` is displayed (not from the login page but from the user_accounts module)

**Comment by kongtiaowang** [comment]
@ridz1208 @maltheism 
https://github.com/kongtiaowang/Loris/pull/330/files This PR maybe help.
