### ISSUE TITLE
[API] PUT request not updating image's QC values

### ISSUE THREAD

**Issue by AlexandraLivadas** [aces/Loris#7917]
**Describe the bug**
The PUT request `/candidates/{candid}/{visit}/images/{filename}/qc` is returning an error and not updating the corresponding image's qc values

**To Reproduce**
1. Go to the API documentation module and scroll down to the specified request section
2. Click on "Try it out" and enter a CandID, visit label, and filename. You can use the GET requests above this section to get the visit labels and filenames for a given candidate.
3. Fill in the request body section with updated QC values for the image.
4. Click on "Execute" and see error
5. Go to the corresponding GET `/candidates/{candid}/{visit}/images/{filename}/qc` section right above the PUT request and enter the same CandID, visit label, and filename. See that the QC values are not updated.

**What did you expect to happen?**
The QC values should be updated and there should be no error.

**Comment by driusan** [comment]
@xlecours @cmadjar seems important?
