### ISSUE TITLE
[DQT] Results header is stuck on initial query run when scrolling down and won't update when changing display modality (Cross sectional vs Longitudinal)

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#7929]
**Describe the bug**
For the Data Query Tool, when a query is run, the headers on the results table are consistent with the display modality selected, either cross sectional or longitudinal. However, if the display modality is change, the headers will change in the results table accordingly, but when scrolling down, the headers will revert back to those under which the query was initially run. This happens independent of initial modality. When scrolling down, the headers will thus not correspond to the values in the columns as these will be shifted.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to the Data Query Tool and create a query. The run the query in either 'Cross-sectional' or 'Longitudinal' modality.
2. Click on the alternate display modality.
3. Scroll down the results table.
4. Headers will revert to those of the initial query results (see screenshots).

![Screen Shot 2021-12-20 at 5 45 27 PM](https://user-images.githubusercontent.com/54332302/146843220-d9d43b7c-822e-4f72-81cc-e0e0236783b6.png)

![Screen Shot 2021-12-20 at 5 45 41 PM](https://user-images.githubusercontent.com/54332302/146843222-6ecb5b26-af1f-43e4-affc-3752219f0f37.png)

**Comment by maltheism** [comment]
Hi @SantiagoTG, I'm having trouble duplicating the bug on my local development setup. Maybe we can have a zoom call when you have time and you can help me reproduce it.
