### ISSUE TITLE
[user_accounts] Error page after creating a user

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#7931]
**Describe the bug**
I created a user with only the following fields filled:
![image](https://user-images.githubusercontent.com/51176779/147135195-6441365c-3498-464b-b9b5-c3c11d4a328b.png)
![image](https://user-images.githubusercontent.com/51176779/147135295-9fdd10e2-2c4e-40df-b88e-29f5864dc129.png)
![image](https://user-images.githubusercontent.com/51176779/147135318-de4e335a-7934-4d6a-92aa-bf03025d04e4.png)

After saving, I got the following page and the user was not created
![image](https://user-images.githubusercontent.com/51176779/147135357-7440e43e-ef69-4a49-a1ae-7dd0b02e9911.png)

The only message in the error_log was a PHP Notice 
`[Wed Dec 22 12:57:24.759931 2021] [php7:notice] [pid 4242] [client ::1:56322] PHP Notice:  Undefined index: NA_UserID in /var/www/loris/modules/user_accounts/php/edit_user.class.inc on line 1042, referer: http://localhost:8080/user_accounts/edit_user/
`

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to user accounts
2. Create user with only the basic fields filled out
3. Attempt to save

**What did you expect to happen?**
The user to be successfully created or a more specific error message to be shown. 

**Additional context**
Found on development VM from main branch with raisinbread data

**Comment by ridz1208** [comment]
@CamilleBeau you need to increase the error reporting level from the configuration module. The "notice" you reported here is unrelated to the issue you are having.  Try setting it to exception or even debug

**Comment by CamilleBeau** [comment]
> @CamilleBeau you need to increase the error reporting level from the configuration module. The "notice" you reported here is unrelated to the issue you are having. Try setting it to exception or even debug

Getting the following error when config logging settings are set to "Error": 
`[Tue Jan 04 13:43:52.346089 2022] [php7:notice] [pid 11143] [client ::1:55670] [ERROR] cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.pwnedpasswords.com:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.pwnedpasswords.com/range/50e12#0 /var/www/loris/vendor/php-http/guzzle7-adapter/src/Promise.php(62): Http\\Adapter\\Guzzle7\\Promise->handleException()\n#1 /var/www/loris/vendor/guzzlehttp/promises/src/Promise.php(204): Http\\Adapter\\Guzzle7\\Promise->Http\\Adapter\\Guzzle7\\{closure}()\n#2 /var/www/loris/vendor/guzzlehttp/promises/src/Promise.php(169): GuzzleHttp\\Promise\\Promise::callHandler()\n#3 /var/www/loris/vendor/guzzlehttp/promises/src/RejectedPromise.php(42): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()\n#4 /var/www/loris/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\\Promise\\RejectedPromise::GuzzleHttp\\Promise\\{closure}()\n#5 /var/www/loris/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(158): GuzzleHttp\\Promise\\TaskQueue->run()\n#6 /var/www/loris/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(183): GuzzleHttp\\Handler\\CurlMultiHandler->tick()\n#7 /var/www/loris/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\\Handler\\CurlMultiHandler->execute()\n#8 /var/www/loris/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\\Promise\\Promise->invokeWaitFn()\n#9 /var/www/loris/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#10 /var/www/loris/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()\n#11 /var/www/loris/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#12 /var/www/loris/vendor/php-http/guzzle7-adapter/src/Promise.php(94): GuzzleHttp\\Promise\\Promise->wait()\n#13 /var/www/loris/vendor/php-http/guzzle7-adapter/src/Client.php(51): Http\\Adapter\\Guzzle7\\Promise->wait()\n#14 /var/www/loris/src/Http/Client.php(52): Http\\Adapter\\Guzzle7\\Client->sendRequest()\n#15 /var/www/loris/php/libraries/Password.class.inc(165): LORIS\\Http\\Client->sendRequest()\n#16 /var/www/loris/php/libraries/Password.class.inc(118): Password->_pwned()\n#17 /var/www/loris/php/libraries/Password.class.inc(204): Password->_validate()\n#18 /var/www/loris/modules/user_accounts/php/edit_user.class.inc(1150): Password->__construct()\n#19 /var/www/loris/php/libraries/LorisForm.class.inc(1337): LORIS\\user_accounts\\Edit_User->_validateEditUser()\n#20 /var/www/loris/php/libraries/NDB_Form.class.inc(74): LorisForm->validate()\n#21 /var/www/loris/php/libraries/NDB_Form.class.inc(134): NDB_Form->save()\n#22 /var/www/loris/modules/user_accounts/php/edit_user.class.inc(621): NDB_Form->handle()\n#23 /var/www/loris/src/Middleware/UserPageDecorationMiddleware.php(241): LORIS\\user_accounts\\Edit_User->handle()\n#24 /var/www/loris/src/Middleware/PageDecorationMiddleware.php(57): LORIS\\Middleware\\UserPageDecorationMiddleware->process()\n#25 /var/www/loris/php/libraries/NDB_Page.class.inc(735): LORIS\\Middleware\\PageDecorationMiddleware->process()\n#26 /var/www/loris/php/libraries/Module.class.inc(398): NDB_Page->process()\n#27 /var/www/loris/modules/user_accounts/php/module.class.inc(42): Module->handle()\n#28 /var/www/loris/src/Middleware/ResponseGenerator.php(50): LORIS\\user_accounts\\Module->handle()\n#29 /var/www/loris/src/Middleware/AuthMiddleware.php(63): LORIS\\Middleware\\ResponseGenerator->process()\n#30 /var/www/loris/src/Router/ModuleRouter.php(74): LORIS\\Middleware\\AuthMiddleware->process()\n#31 /var/www/loris/src/Middleware/ExceptionHandlingMiddleware.php(55): LORIS\\Router\\ModuleRouter->handle()\n#32 /var/www/loris/src/Router/BaseRouter.php(126): LORIS\\Middleware\\ExceptionHandlingMiddleware->process()\n#33 /var/www/loris/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle()\n#34 /var/www/loris/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process()\n#35 /var/www/loris/htdocs/index.php(55): LORIS\\Middleware\\ContentLength->process()\n#36 {main}, referer: http://localhost:8080/user_accounts/edit_user/
`

**Comment by ridz1208** [comment]
@CamilleBeau this seems to be on your VM correct? is this issue happening on test ??

**Comment by CamilleBeau** [comment]
@ridz1208 Yes this is on my VM but it was a new issue. Am I just missing a new dependency or something?

**Comment by maltheism** [comment]
@CamilleBeau I think your VM didn't successfully communicate with `api.pwnedpasswords.com` if that helps.

**Comment by ridz1208** [comment]
@CamilleBeau have you resolved this ?

**Comment by CamilleBeau** [comment]
No longer getting this error.
