### ISSUE TITLE
Checkbox Element alignment could be better

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7934]
**Describe the bug**
As you can see in the screenshot, the checkbox and its label are not properly aligned, making lists like the permissions very confusing and difficult to select
<img width="1122" alt="Screen Shot 2022-01-04 at 9 44 17 AM" src="https://user-images.githubusercontent.com/15268287/148076386-67ec33ab-f7ff-4962-9912-08400205fc67.png">
<img width="718" alt="Screen Shot 2022-01-04 at 9 46 16 AM" src="https://user-images.githubusercontent.com/15268287/148076459-7b0d864c-af3d-4a61-aa97-8cc10afc608b.png">

**Comment by driusan** [comment]
Unassigning from me because this is turning into a much more complicated problem to fix than I expected and I don't have the time to fix it.
