### ISSUE TITLE
[DQT] Prevent Autofill in chrome

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7938]
**Describe the bug**
Several fields in the DQT module trigger the chrome username/password autofill (see screenshots) the currently identified locations are

 1. in define filters -> select a category -> select a field -> select an operator -> AUTOFILL username
    <img width="1670" alt="Screen Shot 2022-01-04 at 10 27 56 AM" src="https://user-images.githubusercontent.com/15268287/148082985-ed410963-8d07-435d-911f-85f8a97a107a.png">
 2. in the query SAVING functionality, the query name field is autofille
    <img width="1625" alt="Screen Shot 2022-01-04 at 10 26 59 AM" src="https://user-images.githubusercontent.com/15268287/148082947-0035f394-305d-4007-98fb-d887956c68a5.png">
d

**Comment by maltheism** [comment]
@ridz1208 do you have an idea of what's the preferred solution for this bug? I remember reading that this bug happens when chrome cannot find a password field and by creating one that's hidden to the user will prevent the bug from happening.

**Comment by ridz1208** [comment]
@maltheism no, I'm not sure what is best practice here. we might be able to use something along the lines of what I used in the user accounts module in #7933. 

However, there must be a reason chrome is identifying these fields are "usernames" and im not sure what it is... maybe because they dont have a "name" value (I might be wrong) or some other weird factor causing it to trigger the autofill
