### ISSUE TITLE
[media] No feedback provided when candidate has no sessions or instruments

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#7951]
**Describe the bug**
In the media module,s uploading functionality, if the user selectsa  PSCID for a candidate with no timepoints, the Visit Label dropdown is empty with no clear explanation or message. Ideally the empty field should read "No visits available for this candidate" or something along those lines, an overkill would be to pop a swal but it might be too intrusive in this case

Similarly when no instruments are available the dropdown should indicate so as well.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. TEST loris -> media -> updload
2. choose DCC435
3. see dropdowns for Visit Label and instrument

**Comment by ridz1208** [comment]
@shonibare please add message when the dropdown is empty

**Comment by shonibare** [comment]
PR #8334
