### ISSUE TITLE
[create_timepoint] Can not create timepoint

### ISSUE THREAD

**Issue by driusan** [aces/Loris#7959]
In the `create_timepoint` module at https://test-loris-dev.loris.ca/create_timepoint/ I'm unable to create a timepoint. The values in the dropdown change dynamically, but no matter what I choose I get an error message  "This visit label is not valid for this subproject."

(I'm attempting to create a time point for CandID 373060 as the admin user.

**Comment by ridz1208** [comment]
@driusan I think this should now be closed

**Comment by driusan** [comment]
when are we pushing 24 into main? It's fixed on 24 but still broken on main, I think..

**Comment by ridz1208** [comment]
@driusan as soon as it's stable, I have a fix to do on the SQL patch
