### ISSUE TITLE
MRI Notifications for incidental findings

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#7983]
Use Cases: 

**Closed Loop Notifications** 
1) Any variable in any instrument (ie: a 'Trigger' for suicidality - example: the candidate is filling out a form, in RedCAP to be imported to LORIS, or directly in LORIS - and answers "YES" to a question regarding suicidality. 

-->This needs to trigger an email to Site Personnel within 12 hours. 
--> That site personnel needs to Log Into LORIS, and acknowledge they have received the notification and are 'acting on this'.  
-->If the site personnel does not Log Into LORIS, X more (ie: 3 more) notifications are sent every X hours (ie: 24 hours). 
--> If after X times of sending the reminder, no log in is done, this email is elevated to the studies highest level. 

2) **Not Closed Loop Notifications** (is this open loop?)
--> A notification is sent when an action takes place (ie: an EEG file is uploaded). 
--> No action on the part of receiver of the email is required.

**Comment by jstirling91** [comment]
### Proposed Design

## Closed Loop
Any actionable item which requires a closed loop notification will have the following workflow:

1. When Trigger event happens, a new issue will be created and tracked via issue tracker (ideally loading BE class and calling the create method)
2. This issue creation will then trigger a notification to be sent to desired user (ideally this would be configured in a new table, but for the first pass user can be hardcoded)
3. A cronjob like process will iterate over unacknowledged issues and set reminder notifications to the user. If more then X notifications are sent without acknowledgement then the notification is escalated to the user's supervisor.
4. When a user opens the issue via Loris, the issue will trigger an event to flag that the user has opened the issue, ie. acknowledge they've seen it
