### ISSUE TITLE
[instruments] getVisitLabel() and getSubprojectID() are falling when there is not CommentID for a given instrument. 

### ISSUE THREAD

**Issue by racostas** [aces/Loris#7995]
The functions `getVisitLabel()` and `getSubprojectID()` in `php/libraries/NDB_BVL_Instrument.class.inc` are trying to retrieve data from an empty object when there is not `CommentID `for a given instrument.  This is leading to 500 error.

In the case of `getSubprojectID()` it seem to exist an outdated check for getSessionID() returning -1 but the new function getSessionID() well return now null in place of -1 in a similar situation.

https://github.com/aces/Loris/blob/5de9d0027c1654da95371ce18444dbadb696def5/php/libraries/NDB_BVL_Instrument.class.inc#L1425-L1472

**Comment by ridz1208** [comment]
It seems logical, could you just investigate (or have someone do it) when and where the -1 return was changed to NULL. There might be an explanation for it or some recommendations

**Comment by CamilleBeau** [comment]
> It seems logical, could you just investigate (or have someone do it) when and where the -1 return was changed to NULL. There might be an explanation for it or some recommendations

https://github.com/aces/Loris/pull/5352

**Comment by ridz1208** [comment]
@racostas the PR has been merged, could you please pull the latest changes  on a VM and make sure this issue is resolved (if it is please close this ticket)

**Comment by racostas** [comment]
LGTM.
