### ISSUE TITLE
[Create profile] - very limited # of years and month available when creating a new profile

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#7996]
**Describe the bug**
I was doing a general click around for the upgrade and when creating a new profile, only jan and feb of 1973 are available as date of birth.

**Comment by CamilleBeau** [comment]
To add: when a maximum DOB configuration is set, only the months of the _current year_ are available for the last year. For example, our maximum year set is 1973, and we are currently in February, so only January and February are available for 1973. Previous years / months are still available

**Comment by racostas** [comment]
Mozilla Firefox seems to be working fine: 
![image](https://user-images.githubusercontent.com/37309344/157959072-0a1cc0cf-07e6-492f-b3dd-c5f2a8a04fca.png)
Will do a research in chrome.

**Comment by driusan** [comment]
*merged PR
