### ISSUE TITLE
[Manual testing] - New timepoint

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#7998]
**Describe the bug**
When selecting a visit during the creation of a new timepoint, the proper visit name appears. however, you get to the list of visits, they appear as numbers (i.e. 1-250) instead of the visit name.

**Comment by CamilleBeau** [comment]
To add: I looked into the code and it appears the visit label is saved as the index in the session table instead of the actual visit label.

**Comment by driusan** [comment]
Fixed by #8000
