### ISSUE TITLE
[Issue Tracker] - every single sites appear in the sites column

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#8003]
**Describe the bug**
Check that they have the label All Sites in the Site column:
      - All the sites show up in the sites column which makes every issue extra long in the table. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to the issue tracker module and make sure to have across all sites permissions. 

**What did you expect to happen?**
the label all sites should appear instead of every single site.

**Comment by CamilleBeau** [comment]
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/51176779/206000070-14ea0347-c558-44f9-8d34-7ffce182a9e2.png">
I think this has been resolved, when testing I saw "All sites" in the site column.
