### ISSUE TITLE
[Issue tracker] - Delete attachment

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#8006]
**Describe the bug**
A clear and concise description of what the bug is
If a user does not have _Issue Tracker: Close/Edit/Re-assign/Comment on All Issues_, they cannot delete their own attachment. 
**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
grant permission to only Issue Tracker: Create/Edit Own Issues and Comment on All Issues and with that account add a screenshot. 

**What did you expect to happen?**
You should be able to delete the screenshot you added.

**Comment by kongtiaowang** [comment]
<img width="1010" alt="截屏2023-01-18 下午2 13 27" src="https://user-images.githubusercontent.com/9876007/213459545-f452fde3-e4bf-4fba-a8b3-cdb92b88f801.png">
I have tested on test-loris-dev, it works.

**Comment by kongtiaowang** [comment]
24.0 and 24.1 have the same issue. I will send a new PR to fix this issue.
