### ISSUE TITLE
[Issue tracker] - Dashboard widget

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#8007]
**Describe the bug**
A clear and concise description of what the bug is

- [ ] When clicking on Your assigned issues, it redirects you to the issue tracker module, but it DOESN't filter for all issues containing you as the assignee.

- [ ] The site also says all even though I only have access to one site. 
![image](https://user-images.githubusercontent.com/25854264/154984539-9ba650d6-356b-45f0-ad5d-40e021d289c4.png)

**Comment by ridz1208** [comment]
@driusan you should not have taken time off

**Comment by christinerogers** [comment]
@racostas if this is still an issue, may be good
