### ISSUE TITLE
[Brainbrowser] Constantly loading when accessing image

### ISSUE THREAD

**Issue by jstirling91** [aces/Loris#8016]
**Describe the bug**
When navigating to view 3D model from imaging_browser's viewSession, a new window launches but the page never fully loads. See attached screen shot:
![Screen Shot 2022-02-23 at 2 14 43 PM](https://user-images.githubusercontent.com/2818503/155391030-c779d198-6893-4e67-a3ea-08561f0eadfa.png)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Create new user and assign all Imaging Browser permissions
2. Login as new user
3. Navigate to imaging browser
4. Select `all types` for a given candidate
5. For one of the images, click the checkbox in the top left corner of the image panel
6. Click `3D Only` on the left panel of the page

**What did you expect to happen?**
A new browser page to open and the scan to load.

**Browser Environment (please complete the following information):**
- OS: Mac
- Browser [e.g. chrome, firefox] Chrome
- Version

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: 24
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by CamilleBeau** [comment]
I was not able to reproduce this error. Logged in with a user that only has imaging permissions, and access to a separate site than the candidate, the 3D only page was loading properly.
