### ISSUE TITLE
[survey_accounts] Can't add survey even though visit has been created

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#8022]
**Describe the bug**
When trying to add the 'Mild Behavioral Impairment Checklist (MBI-C) (CTU)' for candidate 9990156 under visit 'Clinical_Assessment', a message that the 'Visit Clinical_Assessment does not exist for given candidate' is displayed even though the visit does exist.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to the survey accounts module
2. Click on 'Add survey'
3. Enter information and select 'Clinical_Assessment' as a visit and 'Mild Behavioral Impairment Checklist (MBI-C) (CTU)' for the survey.
4. Click on 'Create Survey' or 'Email Survey'
5. Error is displayed

**What did you expect to happen?**
The survey should have been created. 

**Browser Environment (please complete the following information):**
- Chrome

![Screen Shot 2022-02-25 at 12 12 56 PM](https://user-images.githubusercontent.com/54332302/155760003-68d841bf-8673-4aaf-b89b-f7cdfc0b0b32.png)

![Screen Shot 2022-02-25 at 12 12 38 PM](https://user-images.githubusercontent.com/54332302/155760045-926e79cc-81c2-49e1-b4c2-bdc2e2783b93.png)

**Comment by SantiagoTG** [comment]
Noticed there appears to have been a previous 'Clinical_Assessment' visit created, so this may be source of error.


![Screen Shot 2022-02-25 at 12 12 56 PM](https://user-images.githubusercontent.com/54332302/155760240-2353d886-e985-4680-af50-35a11c7e560a.png)

**Comment by CamilleBeau** [comment]
Hi Santiago, this survey 

> Noticed there appears to have been a previous 'Clinical_Assessment' visit created, so this may be source of error.

Were you able to test whether this was the source of the error or not?

**Comment by SantiagoTG** [comment]
It appears this was the source of error, as I could not replicate this on other candidates or instruments. However, I did not close the ticket as the error is still present (A given candidate should not have two visits under the same visit label, even if the site is different). Thought I'd mention it though as it may have other implications.

**Comment by driusan** [comment]
Root cause is #8017 which is fixed separately.
