### ISSUE TITLE
[data_release] Test plan and module README need updating

### ISSUE THREAD

**Issue by AlexandraLivadas** [aces/Loris#8025]
Both the test plan and README of this module do not describe or handle the case of files with no version. The test plan should include steps to test adding Unversioned files, filtering by Unversioned files, adding/managing permissions for Unversioned files. The README should mention that files can be uploaded with no version and that when you add a version permission, the user will also be automatically granted permission to see any Unversioned files.

**Comment by christinerogers** [comment]
I've never worked with this module.  the contributors or folks from a project that uses it could do this far more efficiently. let me know if you need help writing it up --

**Comment by christinerogers** [comment]
@ridz1208 which project uses this module?  I don't mind helping someone co-write some of this but i've never used...

**Comment by ridz1208** [comment]
@charliehenrib does CCNA still use this ?

**Comment by charliehenrib** [comment]
@ridz1208 yes, COMPASS-ND does, but not CTU.

**Comment by ridz1208** [comment]
@christinerogers you found your person @charliehenrib

**Comment by christinerogers** [comment]
wonderful @ridz1208  - @charliehenrib  feel free to assign me for review (or co-assign)
