### ISSUE TITLE
[Statistics] - 500 error when clicking on view details for DE

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#8028]
**Describe the bug**
A clear and concise description of what the bug is
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/25854264/155790900-6adc0763-d765-423f-9d40-461441e2ca48.png">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to statistics module, behavioural tab
2. Click on view details 

**What did you expect to happen?**
Page to load

**Comment by CamilleBeau** [comment]
Could not reproduce 500 error
