### ISSUE TITLE
[Manual Testing] Publication - File not uploading when submitting a proposal

### ISSUE THREAD

**Issue by shonibare** [aces/Loris#8029]
**Describe the bug**
Getting the error "Something went wrong! Could not upload the file. Please try again!" when trying to upload a file along with a new publication.
<img width="554" alt="image" src="https://user-images.githubusercontent.com/51176779/156249049-5296cec4-e625-44e0-ba54-4e5318b21c44.png">

The following was in the error log: 

> [Tue Mar 01 16:02:20.052437 2022] [php7:warn] [pid 24546] [client 192.168.122.1:55926] PHP Warning:  move_uploaded_file(/data/publication_uploads/Screen_Shot_2022-02-15_at_3.08.31_PM.png): failed to open stream: Permission denied in /var/www/ccna/modules/publication/ajax/FileUpload.php on line 183, referer: https://ccna-dev.loris.ca/publication/
>[Tue Mar 01 16:02:20.052761 2022] [php7:warn] [pid 24546] [client 192.168.122.1:55926] PHP Warning:  move_uploaded_file(): Unable to move '/tmp/phpjmIFb2' to '/data/publication_uploads/Screen_Shot_2022-02-15_at_3.08.31_PM.png' in /var/www/ccna/modules/publication/ajax/FileUpload.php on line 183, referer: https://ccna-dev.loris.ca/publication/

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to Publication module
2. Click on 'propose a project'
3. Fill in all the form and upload a file then submit

**What did you expect to happen?**
The file to be uploaded successfully along with the publication. 

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by CamilleBeau** [comment]
To add to this, there seems to be a duplicate  "File to upload" field that may be related to this error
<img width="922" alt="image" src="https://user-images.githubusercontent.com/51176779/156197683-c74d2694-7211-48ef-b5b1-6b8ef8d44270.png">

**Comment by laemtl** [comment]
@shonibare Can you test if the bug happens in demo.loris.ca?

**Comment by shonibare** [comment]
It works @laemtl 
<img width="1440" alt="Screenshot 2023-01-24 at 2 19 36 PM" src="https://user-images.githubusercontent.com/47093379/214387981-4386513c-f78d-4194-b234-572543f90902.png">

**Comment by shonibare** [comment]
The bug has been fixed
