### ISSUE TITLE
[instruments] php instruments are not allowing set "Data Entry" status to "Complete".

### ISSUE THREAD

**Issue by racostas** [aces/Loris#8030]
**Describe the bug**
instruments are not allowing to set the "Data Entry" status to "Complete" after filling all the required fields.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to and instruments and fill all the required information in all the pages and save each one of they. 
2. At the left of the page click on **Administration** -> **all**
3. Then try to click in the section bellow **Data Entry** -> **Complete**
4. Will have a message stating **To enable the link, required fields must be filled in**
![image](https://user-images.githubusercontent.com/37309344/155994244-3802774b-f4eb-41dc-9ba6-84e6a732de52.png)

**What did you expect to happen?**
The corresponding checkbox allow to be checked. 

**Browser Environment (please complete the following information):**
- OS: Microsoft Windows 10.
- Browser: Chrome 
- Version 97.0.4692.71 (Official Build) (64-bit)

**Server Environment (if known):**
CCNA testing VM. 

**Additional context**
This issue seem to be new in the 24 build. Reproduced the same steps in the same instrument for the CCNA build 23 and was working fine. Several instruments were tested and all shown the same issue.

**Comment by ridz1208** [comment]
@racostas I was able to set Data-Entry to complete on my end for a `Screening_Candidate_Recruitment` instrument (I can tell you which candidate and timepoint on slack).

So I'm thinking this might be a permission issue, or if you were testing it with a different instrument maybe the instrument configuration ?

**Comment by CamilleBeau** [comment]
> @racostas I was able to set Data-Entry to complete on my end for a `Screening_Candidate_Recruitment` instrument (I can tell you which candidate and timepoint on slack).
> 
> So I'm thinking this might be a permission issue, or if you were testing it with a different instrument maybe the instrument configuration ?

Just looked into this. It is because "CommentID" is listed in the _requiredElements array for many of our CCNA instruments, but CommentID is not a part of the data returned by getInstanceData. We will have to remove this on CCNA instruments. I'm not sure where this stems from so I don't know if this is something that should be mentioned in the CHANGELOG / Release notes in case other projects have it, but I have taken note of the needed change and I am closing this issue since it is CCNA related.
