### ISSUE TITLE
[Document repository] - No upload tab

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#8032]
**Describe the bug**
I have both document repository permissions (Document Repository: View Documents; Document Repository: Delete Documents) and I don't see the upload tab.
![image](https://user-images.githubusercontent.com/25854264/156049286-7c3a34b3-6cc0-408e-8e40-10bfd41cfc88.png)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to document repository and make sure you have all the permissions available. 
4. See error: only browse and category are available.

**What did you expect to happen?**
There should be a tab to upload documents

**Comment by ridz1208** [comment]
@charliehenrib you need the  Document Repository: Edit/Upload Documents permission to view the tab

**Comment by charliehenrib** [comment]
@ridz1208 it is not available in the list of permissions at the moment.
