### ISSUE TITLE
[media] 504 Gateway Timeout + Unexpected Token in JSON 

### ISSUE THREAD

**Issue by suzanne-lee** [aces/Loris#8033]
**Describe the bug**

The media module does not load. 

When you navigate to the media module from the dashboard, the blue tail spin loader appears for on average 60 seconds before the "An error occurred while loading the page." message appears. The console shows a 504 Gateway Timeout message and a syntax err message that reads: "Syntax Error: Unexpected token < in JSON at position 0" 

<img width="1135" alt="Screen Shot 2022-02-25 at 4 11 38 PM" src="https://user-images.githubusercontent.com/29237731/156059712-ecf9926d-e40b-473e-9bae-400244476c36.png">

When you refresh the page, the following page occurs, with only the 504 error in the console: 

<img width="1077" alt="Screen Shot 2022-02-28 at 4 11 29 PM" src="https://user-images.githubusercontent.com/29237731/156059953-4546c7dc-025f-4689-93ce-dc4e66ad8533.png">

**Browser Environment (please complete the following information):**
- Chrome 98.0.4758.109
- Firefox 97.0.1

**Comment by ridz1208** [comment]
@CamilleBeau is that one of the modules you had issues with ?

**Comment by CamilleBeau** [comment]
> @CamilleBeau is that one of the modules you had issues with ?

Yes this is one of them!

**Comment by xlecours** [comment]
@CamilleBeau @suzanne-lee 
I can't reproduce the behavior on test VM
Can it be a permission issue?

Usually, `SyntaxeError: Unexpected token '<' in JSON at position 0` means that HTML was received instead of JSON. Can you look at the value returned? It migth contain additional information about the error. Also, is there something in apache error_log?

**Comment by ridz1208** [comment]
@xlecours I can help here. 

The reason that error is showing in the console s that the response to `https://ccna-dev.loris.ca/media/?format=json` is
```
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>
```

That's the HTML that is received instead of the JSON. Nothing in the apache error log or access log.

**Comment by xlecours** [comment]
ok thanks @ridz1208

**Comment by xlecours** [comment]
it's not the database, the query runs in in less than a second `31535 rows in set (0.36 sec)`.
Next thing to look at is what is done for each rows.

**Comment by xlecours** [comment]
Oh well...
https://github.com/aces/Loris/pull/7456#discussion_r738574069

I made the datatable load with the 30k+ rows by removing the Instrument instantiation per row.
Why would full_name in test_name be wrong?

**Comment by xlecours** [comment]
Tried it in https://github.com/aces/Loris/pull/8055
Didn't worked.
