### ISSUE TITLE
[document_repository] Can not upload file from non-admin user

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#8035]
**Describe the bug**
When trying to upload a file to document repository from a non-admin user, I get the following error:
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/51176779/156250855-67b1e89a-87ec-4ca7-bb4a-c7b12b78075d.png">
This happens even though the user has the document repository upload permission. The error does not occur from the admin user.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to document repository from a non-admin user who has the upload permission
2. Attempt to upload a file
3. See error
4. Try again with admin user, and see that you can successfully upload file.

**What did you expect to happen?**
To be able to upload the file without an error.

**Comment by ridz1208** [comment]
@CamilleBeau can we look at this one together ?

**Comment by CamilleBeau** [comment]
> @CamilleBeau can we look at this one together ?

Yes
