### ISSUE TITLE
[server_process_manager] not loading due to timeout

### ISSUE THREAD

**Issue by miladheshmati** [aces/Loris#8039]
**Describe the bug**
While loading the module, the page is not loading due to a timeout. There is nothing in the Apache error log about this error.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to module
2. see the error

**What did you expect to happen?**
the module must be loaded correctly 

![image](https://user-images.githubusercontent.com/51356424/157317625-9a356e4c-c3d5-4ec9-88aa-d9f4416ec6e1.png)

This bug found during #7601 testing

**Comment by xlecours** [comment]
This is probably the same issue than https://github.com/aces/Loris/issues/8039
On test VM, the modules loads fine.

**Comment by driusan** [comment]
How would it be the same problem as #8033? I don't think the `server_process_manager` does anything with instruments..

**Comment by xlecours** [comment]
@driusan The issue is that the backend fails to return content before the 1 minutes timeout. I think the issue is that the vm runs with 1.8G of RAM and it might be swapping. The modules are working fine when I reduce the amount of records returned.

**Comment by xlecours** [comment]
@driusan Do you know if these lines have side effects?
```
--- a/modules/server_processes_manager/php/server_processes_manager.class.inc
+++ b/modules/server_processes_manager/php/server_processes_manager.class.inc
@@ -49,11 +49,6 @@ class Server_Processes_Manager extends \NDB_Menu_Filter
      */
     function _setupVariables()
     {
-        // This will update all process informations in the database
-        // Must execute this before loading the form
-        $serverProcessesMonitor = new ServerProcessesMonitor();
-        $serverProcessesMonitor->getProcessesState();
-
         // Columns displayed in the result table
         $this->columns = [
             'pid',
```
Removing those lines made the module work.

**Comment by driusan** [comment]
I don't see any in the code but maybe @nicolasbrossard can confirm.

**Comment by nicolasbrossard** [comment]
@driusan @xlecours  I don't think these lines modify the database. Incorrect/outdated comment.

**Comment by CamilleBeau** [comment]
Re-tested with 3.7G of RAM and still getting a timeout.

**Comment by CamilleBeau** [comment]
Tested with Xavier's specified lines removed. It is working now!

**Comment by driusan** [comment]
Is someone sending a PR for this or should I send one?

**Comment by CamilleBeau** [comment]
> Is someone sending a PR for this or should I send one?

I can
