### ISSUE TITLE
[candidate_profile] module not loading when a candidate is selected.

### ISSUE THREAD

**Issue by racostas** [aces/Loris#8040]
**Describe the bug**
The module` candidate_profile `is given "blank page" when a candidate is clicked.  

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `MainMenu-> Candidate-> New Access Profile (Beta)`
2. The list of the candidates is shown.
3. Click on one of the Candidates to see the details. 
5. See error: the candidate info are not loaded. In place a blank page appears.

**What did you expect to happen?**
The correct info of the selected candidate to be shown.

**Browser Environment (please complete the following information):**
- OS: Microsoft Windows 10
- Browser: Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- CCNA official testing environment for 24 upgrade.

**Comment by racostas** [comment]
Hi @CamilleBeau. Hum, it seems to be a "Site permissions" issue. So far I think the issue happen when the user have permissions to one of the "site/subprojects" the candidate below to but not to all of then. 
This is the error I got in the console (but not in the UI):
![image](https://user-images.githubusercontent.com/37309344/158196670-219dc0a7-906b-466b-99ae-3ad1c2659479.png)

But if the candidate in question don't have any of the sites/subprojects. Then we got in the UI (which is the expected behavior I would say)
![image](https://user-images.githubusercontent.com/37309344/158203709-d1cfad08-c64f-4f62-a7e4-1507602b3fe8.png)

**Please note:**
Even with the super admin there is a least one candidate that is falling. My only guess it that there is some misconfiguration going on for this candidate in particular. A subproject that doesn't exist in the testing environment or something like that. I will sent you the candidate id via private chanel.

**Comment by racostas** [comment]
@CamilleBeau. I just retested in the test environment and yet got the blank page and the 403 in the console.

**Comment by driusan** [comment]
Fixed by above PR
