### ISSUE TITLE
[survey_accounts] Survey email being sent for both "Create survey" and "Email survey"

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#8041]
**Describe the bug**
When I click "Create survey" instead of "Email survey", a survey email is still sent to the participant.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to survey accounts module and click "Add survey"
3. Fill out information to add a survey, add your own email as the participant email
5. Click "Create survey" instead of "Email survey"
6. See that you receive an email

**What did you expect to happen?**
No email to be sent when "Create survey" is selected.

**Comment by driusan** [comment]
PR merged
