### ISSUE TITLE
[tools] delete_candidate failing

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#8059]
**Describe the bug**
The delete_candidate.php script is failing because it is using test_name as tableName. The script must instantiate an instrument and get tableName instead.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Run delete_candidate for a candidate that has an instrument with a different table name / test name
2. See error

**Comment by driusan** [comment]
fixed by merged PR
