### ISSUE TITLE
[tools] detect_duplicated_commentids.php

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#8060]
**Describe the bug**
The script is failing due to an SQL error for duplicate rows. This is happening when there is more than one session for the candidate.

`PHP Fatal error:  Uncaught DomainException: Attempt to use pselectRow on a query that returns multiple rows in /var/www/loris/php/libraries/Database.class.inc:858
Stack trace:
#0 /var/www/loris/tools/detect_duplicated_commentids.php(114): Database->pselectRow()
#1 {main}
  thrown in /var/www/loris/php/libraries/Database.class.inc on line 858`

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Run script as intended
2. See error

**Comment by GeorgeMurad** [comment]
Done! https://github.com/aces/Loris/pull/8305
