### ISSUE TITLE
[tools] php fix_timepoint_date_problems.php

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#8061]
**Describe the bug**
Script failing because of null return value in Timepoint::getScreeningStatus
`PHP Fatal error:  Uncaught TypeError: Return value of TimePoint::getScreeningStatus() must be of the type string, null returned in /var/www/loris/php/libraries/TimePoint.class.inc:507
Stack trace:
#0 /var/www/loris/tools/fix_timepoint_date_problems.php(661): TimePoint->getScreeningStatus()
#1 /var/www/loris/tools/fix_timepoint_date_problems.php(286): diagnose()
#2 {main}
  thrown in /var/www/loris/php/libraries/TimePoint.class.inc on line 507
`

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Run script as intended
2. See error

**Comment by miladheshmati** [comment]
I checked the fix_timepoint_date_problems tool for different modes, the fatal error was not happening.
