### ISSUE TITLE
[tools] Use CandID instance in generate_candidate_externalids.php

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#8062]
**Describe the bug**
The script is failing because a string is passed as CandID instead of a CandID instance in Site::singleton

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Site::singleton() must be an instance of CenterID, string given, called in /var/www/loris/tools/generate_candidate_externalids.php on line 81 and defined in /var/www/loris/php/libraries/Site.class.inc:21
Stack trace:
#0 /var/www/loris/tools/generate_candidate_externalids.php(81): Site::singleton()
#1 {main}
  thrown in /var/www/loris/php/libraries/Site.class.inc on line 21
`

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Run script as intended
2. See error

**Comment by shonibare** [comment]
PR - #8307

**Comment by driusan** [comment]
Why is this closed as completed? You closed that PR (unmerged) a week ago.

**Comment by shonibare** [comment]
@driusan I closed the issue because there was no error when I ran the script on 24.0.
