### ISSUE TITLE
[tools] Wrong path in recreate_conflicts.php

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#8063]
**Describe the bug**
Script failing because a slash is missing in the generic includes path
`PHP Warning:  require_once(/var/www/loris/toolsgeneric_includes.php): failed to open stream: No such file or directory in /var/www/loris/tools/recreate_conflicts.php on line 15`
`PHP Fatal error:  require_once(): Failed opening required '/var/www/loris/toolsgeneric_includes.php' (include_path='.:/usr/share/php') in /var/www/loris/tools/recreate_conflicts.php on line 15
`

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Run script as intended
2. See error

**Comment by driusan** [comment]
Path fixed by #8292
