### ISSUE TITLE
[tools] Unknown column error in populate_examiners_psc_rel.php

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#8065]
**Describe the bug**
The script is using the deprecated function `getAllInstruments`, and also yields an SQL error for unknown column:

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/51176779/158917527-f0a9c161-6682-4f94-b378-308f4d992ed9.png">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Run script as intended
2. See error

**Comment by sruthymathew123** [comment]
@ridz1208 Quick question; Is this script a single use one? I remember dropping the column CenterID after running this script during one old Release.

**Comment by ridz1208** [comment]
@sruthymathew123 yes I believe it is

**Comment by sruthymathew123** [comment]
Hi @CamilleBeau It is a single use single use script part of Release. I don't think we need to maintain it for new Releases. Let me know.

**Comment by CamilleBeau** [comment]
> Hi @CamilleBeau It is a single use single use script part of Release. I don't think we need to maintain it for new Releases. Let me know.

@sruthymathew123 Yes good point. Closing issue

**Comment by driusan** [comment]
If it's a single use script can you send a PR to move it to the appropriate directory so we don't come across this again?
