### ISSUE TITLE
[tools] Hard-coded date in DB_date_zeros_removal.php Patch

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#8066]
**Describe the bug**
Tool runs successfully, but the Patch generated always has the same name with the date "2016-06-01"
`The output file is SQL/Archive/18.0/2016-06-01-update_zero_fields_statements.sql and includes foreign key checks disabling and re-enabling.
`

The output should have a name with the current date.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Run tool as intended
2. Observe name of generated patch

**Comment by shonibare** [comment]
PR - #8277
