### ISSUE TITLE
[tools] manage_modules.php failing with --remove

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#8068]
**Describe the bug**
Getting the following output when using --remove:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51176779/159507129-fd3f0ab6-8df5-4b47-8461-21418bbb5924.png">

Script is running fine with --add

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Run script as intended with --remove and without --dry-run

**Comment by driusan** [comment]
I'm not sure what the expected behaviour is here. There's a foreign key in another module referencing the module but you don't have the module that is referenced.

**Comment by CamilleBeau** [comment]
> I'm not sure what the expected behaviour is here. There's a foreign key in another module referencing the module but you don't have the module that is referenced.

Would it be better to catch this error and give a warning & still let the rest of the script continue?

**Comment by CamilleBeau** [comment]
@driusan Pinging here for a response to the above question. This could perhaps be closed?

**Comment by driusan** [comment]
Yes, that would make sense, I think.
