### ISSUE TITLE
[Release 24] update Read The Docs

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#8088]
[Placeholder issue, should be organized elsewhere in the release roadmap]

 after March's Loris 24 release, the Read the Docs should be updated (currently on 23) : https://loristest.readthedocs.io/en/latest/README.html

@ridz1208 @driusan is there a Release Checklist we could add this point to for future releases, e.g. ?

**Comment by AlexandraLivadas** [comment]
Resolved. ReadTheDocs is updated to v24.1 and the "latest" docs version is pointing to the main branch of the Loris repo.
