### ISSUE TITLE
[dashboard / Study Progression] To show total of recruitments per day

### ISSUE THREAD

**Issue by racostas** [aces/Loris#8122]
**Is your feature request related to an existing module?**
Dashboard / Study Progression graph

**Describe the solution you'd like**
Currently the Study Progression graph in the Dashboard shows the recruitment per site per day. Some projects have requested if the total per day could be visualized as well.  

Discussed with two of then the following proposal was approved:
To have an extra row on the onhover for each day. 
![LORIS_GRAPH](https://user-images.githubusercontent.com/37309344/174099071-fa87baef-2944-4648-ae5b-b7faeefa04f3.png)

**Comment by satvik-tha-god** [comment]
Hello @racostas , I have a minor doubt

Should the graph line of total per day be visualised as well? Or are you only looking for a row of Total  on hover

**Comment by racostas** [comment]
Hi @satvik-tha-god , 
I will said let's keep just the onhover part, not the line. The issue is that when there are more much projects (which is not the case for the demo data but it is the real case for the existing projects, the lines for the projects are been squeezed by the Total one.
