### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Interface 'Psr\\Log\\LoggerAwareInterface' not found in /var/www/loris/php/libraries/Database.class.inc

### ISSUE THREAD

**Issue by spiketren** [aces/Loris#8129]
**Describe the bug**
I followed the Ubuntu Installation guide @ https://github.com/aces/Loris/blob/main/docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/Ubuntu/README.md .

Everything went great without errors. However, I failed at the last step, which was to access the Loris page. 

I saw nothing (i.e., empty page), checked /var/log/apache2/loris-error.log, and found the following error message:

[Wed Jun 29 02:48:19.915456 2022] [php7:error] [pid 376268] [client 123.195.138.16:54282] PHP Fatal error:  Uncaught Error: Interface 'Psr\\Log\\LoggerAwareInterface' not found in /var/www/loris/php/libraries/Database.class.inc:16\nStack trace:\n#0 /var/www/loris/vendor/composer/ClassLoader.php(478): include()\n#1 /var/www/loris/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()\n#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()\n#3 /var/www/loris/php/libraries/NDB_Factory.class.inc(168): spl_autoload_call()\n#4 /var/www/loris/php/libraries/NDB_Client.class.inc(59): NDB_Factory->database()\n#5 /var/www/loris/htdocs/index.php(34): NDB_Client->initialize()\n#6 {main}\n  thrown in /var/www/loris/php/libraries/Database.class.inc on line 16

Could you advice how to fix this problem?

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):

It's very robust to me.

I've used nvm to try different versions of Node.js/NPM for clean installations but none of them worked. Also, "make dev" instead of "make" didn't help, either.

**What did you expect to happen?**
I should be able to see a up & running website like http://demo.loris.ca .

**Browser Environment (please complete the following information):**
- OS: Ubuntu 20.04
- Browser: Chrome & Firefox 
- Version: 24.0.2

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: 24.0.2
- Linux distribution and Version: Ubuntu 20.04
- MySQL/MariaDB Version: MariaDB 15.1
- PHP: 7.4.3
- Node.js/NPM: 16.10.0 / 7.24.0

**Additional context**
I have a Nginx server set up to handle the ports 80 & 8080. So my Apache2 (v2.4.41) was set up at the port 8000 if this matters.

I have also tried adding " require_once '/var/www/loris/vendor/autoload.php'; " in /var/www/loris/php/libraries/Database.class.inc, but it did not help.

BTW, I don't have /var/www/loris/vendor/psr/log/Psr/Log/LoggerAwareInterface.php . I only got the following directories under  /var/www/loris/vendor :

http-client, http-message, http-server-middleware, http-factory, http-server-handler

**Comment by driusan** [comment]
Hi @spiketren sorry about the delay responding to this.. it somehow fell through the cracks. This was fixed by in 24.0.3 (in PR #8115), while your report was for 24.0.2, so updating should resolve it.

If that doesn't work and you're still having problems, please re-open.
