### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by kmilouh** [aces/Loris#8131]
**Describe the bug**
When I try to install there is an Error when run the command 'npm run compile'

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Run command 'make'

**What did you expect to happen?**
End the make command.

**Additional context**
It seems to be a problem with the React version. in the 'package.json' is set the dependencies using '^' so in the new version there are some breaking changes.

![image](https://user-images.githubusercontent.com/13699090/177110779-65a7375e-1750-48a0-827d-936c3029e182.png)

**Comment by laemtl** [comment]
Fixed by #8186
