### ISSUE TITLE
[Instrument template] each() is deprecated since php 7.2 and removed in php 8.0

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#8241]
https://github.com/aces/Loris/blob/1d3a4d0d971c0fa99323421fa89cf9c97b747294/docs/instruments/NDB_BVL_Instrument_UPLOADER_TEMPLATE.class.inc#L153

The each function is deprecated as of PHP 7.2.0, and REMOVED as of PHP 8.0.0. Relying on this function is highly discouraged.

**Comment by shonibare** [comment]
PR #8273
