### ISSUE TITLE
Candidate profiles for CandID shorter than 6 digits gives 404 error

### ISSUE THREAD

**Issue by tikal004** [aces/Loris#8249]
**Describe the bug**
A clear and concise description of what the bug is
Candidate profile is not found when CandID is shorter than 6 digits, unless leading zeros are added. The link from the candidate list does not add leading zeros.
![image](https://user-images.githubusercontent.com/95246814/205149949-e5244203-f646-4523-9d19-1e0bfab7e30e.png)
![image (1)](https://user-images.githubusercontent.com/95246814/205150193-2567dc0c-51aa-4c1d-b292-62d42a71226e.png)

**To Reproduce**

1. Create a candidate with a CandID shorter than 6 digits, e.g. 2081. (MySQL will drop the leading zeros, 002081 -> 2081)
2. From the candidate list, click on the candidate.
3. 404: error appears.

**What did you expect to happen?**
User should see the candidate's profile when clicking on the link from the candidate list.

**Browser Environment (please complete the following information):**
- OS:
- Browser: Chrome
- Version 107.0.5304.122 (Official Build) (64-bit)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: 24.0.0
- Linux distribution and Version: Ubuntu 20.04
- MySQL/MariaDB Version: mysql  Ver 8.0.30-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))

**Comment by driusan** [comment]
CandIDs shorter than 6 digits are never generated by LORIS. How did you come across one?

**Comment by tikal004** [comment]
No need to worry about this if that's the case.
I guess a previous data manager must have generated them with a script outside of LORIS.
We can look into changing the existing short CandIDs to fix this for our instance.
