### ISSUE TITLE
24.1-release[ issue track] - when a new user without accross all sites can't create a new issue.

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#8329]
**Describe the bug**
create a new user without access_all_profiles, then can't create a new issue (assignee option is empty)
**To Reproduce**
create a new user without access_all_profiles, then can't create a new issue (assignee option is empty)

**What did you expect to happen?**
create a new user without access_all_profiles, then user can create a new issue (assignee option is not empty)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

Fixed by #8301

**Comment by driusan** [comment]
An empty assignee should be valid. Why is it preventing issue creation?

**Comment by kongtiaowang** [comment]
@driusan if the empty assignee, we can't submit the form, the assignee fileld is required.
![截屏2023-01-24 上午9 06 26](https://user-images.githubusercontent.com/9876007/214316124-0794f5e4-e888-4ad1-8d48-507139fcd99a.png)

**Comment by driusan** [comment]
You should be able to save it with an empty assignee--can you review/test #8301?

**Comment by kongtiaowang** [comment]
This is a duplicate issue of https://github.com/aces/Loris/issues/4818 
This one will be close
