### ISSUE TITLE
[EEG/Wizard] support / infer standard electrode placement schemes. 

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#8373]
May be an issue for the Wizard repo if the pipeline will not handle it:    
Would it make sense to infer placement scheme even if not specified? 

from discussion on #8242.  The easy wins we could get from coordinate systems are lost because - though the electrodes are usually labelled clearly, the bids json file must be completed.  

> This PR #8242 does not cover these standards, it covers the way of saving multi-coordinate systems and electrodes encountered during parsing. This means it register all coordinate system types (e.g. fiducials, anatomical landmarks), names (e.g. CapTrak, CTF), units and modalities found inside a BIDS file, and their associated electrode information. 
> For what I can see, the BIDS format put standards like `10-20` and `10-10` into the `EEGPlacementScheme` attribute, which is [a recommended but not mandatory section for `_eeg.json` files](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#sidecar-json-_eegjson).
> I have looked into several BIDS archives we have, and only find this attribute to be not used , i.e. `"EEGPlacementScheme": "n/a"`. Maybe we can add this into another issue to include it? 
Even so, it must be present in the BIDS `_eeg.json` files to be saved.

_Originally posted by @regisoc in https://github.com/aces/Loris/issues/8242#issuecomment-1427131665_

**Comment by laemtl** [comment]
@christinerogers Can you reopen this issue on LORIS-MRI? I believe this feature makes more sense there.

**Comment by christinerogers** [comment]
closed and moved to https://github.com/aces/Loris-MRI/issues/895
