### ISSUE TITLE
React Guidelines not Showing

### ISSUE THREAD

**Issue by itshypon** [aces/Loris#8419]
**Describe the bug**
When we read Contributing Guidelines if we click on React Guidelines hypertext, it shows error that page is not found.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to Contributing.md
2. Click on 'React Guidelines' hypertext.
3. See error

**What did you expect to happen?**
It should open a page where guidelines for front-end developers is given.

**Browser Environment (please complete the following information):**
- OS: Windows
- Browser: Brave and Firefox both tested

![image](https://user-images.githubusercontent.com/30335924/222963719-65f5c257-707c-4534-82dd-a547c2796ac9.png)

**Comment by ridz1208** [comment]
Hi @itshypon,

Thank you for catching that. The decumentation has moved to https://github.com/aces/Loris/blob/main/docs/wiki/99_Developers/ReactJS_Guidelines.md.

We will update the link and close the issue when it is resoved
