### ISSUE TITLE
[timepoint_list] Visit / approval stage display is broken

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#8439]
**Describe the bug**
If you modify the visit or approval stage from the timepoint list once, the stage display in the table to the right does not change. In any subsequent modifications without reloading the page, the display shows whatever the stage previously was. If the page is refreshed, the stage shows the correct status again.
<img width="993" alt="Screen Shot 2023-03-13 at 1 34 57 PM" src="https://user-images.githubusercontent.com/51176779/224783414-21c9d00e-b3a3-4f2f-b477-0dd456a63cb6.png">
<img width="930" alt="Screen Shot 2023-03-13 at 1 35 37 PM" src="https://user-images.githubusercontent.com/51176779/224783462-027245f7-b192-42c2-b579-67b6b78d4350.png">
<img width="982" alt="Screen Shot 2023-03-13 at 1 36 08 PM" src="https://user-images.githubusercontent.com/51176779/224783495-20be6ca5-d2f6-4af7-8199-2972db23243b.png">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to a visit that is passed
2. Click on "In Progress" stage in the lefthand sidebar without refreshing the page.
3. Notice that the stage in the display table to the right has not changed.
4. Without refreshing, click back to a different stage. Notice that now the display changes to "In Progress" even though a different stage was selected.
5. Refresh the page, and notice that the stage in the display table is now the correct one.

**What did you expect to happen?**
The display stage to be modified to match what is selected in the sidebar, and what is in the database.

**Comment by CamilleBeau** [comment]
@christinerogers @driusan Yes, it's true that if you refresh it the correct value is shown. However, after selecting a new value, the whole page reloads and updates to the previously selected value. E.g. if it starts out as "Pass" and I select "In progress", it will reload as "Pass", and then if I select "Failure", it will reload as "In progress". 

So it seems to be dynamic since the page refreshes and the variable is modified, but it is not modified to the correct value.

**Comment by christinerogers** [comment]
Hi @racostas and/or @CamilleBeau  -- Could either of you please confirm:
Since this issue was resolved by [CCNA#7223](https://github.com/aces/CCNA/pull/7223), could it likely be quickly resolved in LORIS by the same fix ? 

Rolando --- if not, please 'remove' the GSOC tag I've just added.  thanks 

and generally, folks -- is it worth getting this bug fix in to the 26 release ?

**Comment by skarya22** [comment]
@christinerogers There are these two PRs that were merged into LORIS main. 
https://github.com/aces/Loris/pull/9040
https://github.com/aces/Loris/pull/9072

I believe that the issue duplicated and this instance of it was resolved but not closed
