### ISSUE TITLE
issue_tracker

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8498]
Tested again on May 11. This issue seems to be resolved.

**Comment by aarushichaudhry** [comment]
Tasks:
 [ ] Review issues from previous release testing
### Documentation Tasks
 - [ ] Update test plans
 - [ ] Review/update module READMEs (Interactions, configurations, permissions, widgets, …)
 - [ ] Check user help content for accuracy and formatting (front end)
### Testing Tasks
 - [ ] Follow test plan (SEPARATE TICKETS)
 - [ ] Check if automated tests are up to date
 - [ ] Make sure RB is complete
### Standards: Make sure the latest standards are upheld
*Check the boxes below only if the statements are true !*
 - [ ] No ajax dir
 - [ ] Data framework implemented
 - [ ] React (no templates directory)
 - [ ] Widgets (If module contains candidate information, at least 1 widget is implemented for the candidate profile module)

## Issues
 - **list related issues/bugs here**


## Comments
 - **insert comments here**


## Status
 - [ ] Testing COMPLETE
 - [ ] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

**Comment by aarushichaudhry** [comment]
[](url)
<img width="1428" alt="Screen Shot 2023-04-05 at 10 45 26 AM" src="https://user-images.githubusercontent.com/104917540/230120980-ac5806d1-5353-45e1-a607-9b9ede2e95f2.png">
