### ISSUE TITLE
[Survey Accounts]Cannot Access Survey URL

### ISSUE THREAD

**Issue by sruthymathew123** [aces/Loris#8546]
**Describe the bug**
When you click on the Survey URL link, the page is broken with error message **No such module: instruments**

**To Reproduce**
Create a  survey and try to access the survey link form survey accounts
![Screen Shot 2023-04-05 at 10 15 29 AM](https://user-images.githubusercontent.com/23702452/230125646-5cc40294-c043-4cbe-b4e0-481324b3ca48.png)

**Server Environment (if known):**
- LORIS Version: [e.g. 25.0.0]
- Issue Found on https://test-dev-250.loris.ca/

**Comment by zaliqarosli** [comment]
Resolved by https://github.com/aces/Loris/pull/8647 (merged)
