### ISSUE TITLE
[my_preference] - password rules not enforced

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#8548]
**Describe the bug**
A clear and concise description of what the bug is
The following step of the test plan is not respected:
Change the user’s password. Check that the password rules are enforced. [Automated]
Check that if password and confirmed password do not match you get an error. [Automated]
**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to my preferences.
2. Click on the password and change it to your username.
4. See that there is no error.

I also don't get an error for password and confirmed password when they don't match

**What did you expect to happen?**
You should receive an error saying you cannot use your username as a password.
You should receive an error saying that your passwords don't match

**Additional context**

**Comment by jeffersoncasimir** [comment]
@charliehenrib I was not able to reproduce this issue with the latest HEAD as of this comment of the 25.0-release branch.

Here are some screenshots of the errors being reported. 
Perhaps you can provide one as well of a case that fails so I can reproduce it.

<img width="1418" alt="Screenshot 2023-04-13 at 1 06 38 PM" src="https://user-images.githubusercontent.com/15801528/231834347-e0afbf9d-48bd-482d-baf6-a8263acd7aca.png">
<img width="1417" alt="Screenshot 2023-04-13 at 1 08 12 PM" src="https://user-images.githubusercontent.com/15801528/231834351-df6649ca-586e-4abb-a41c-ed8ba4222342.png">

**Comment by charliehenrib** [comment]
@jeffersoncasimir I just retested it on https://test-dev-250.loris.ca/ and It seems to be resolved now. Thank you
