### ISSUE TITLE
[my_preference] - missing error for invalid email syntax

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#8550]
**Describe the bug**
A clear and concise description of what the bug is

The following step of the test plan is not respected:
Check that if you do not enter an email address that is syntactically valid you get an error.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to my preference
2. Change your email to an invalid email 
3. See that there is no error.
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/25854264/230124181-f88cb2ff-aed7-46cf-8f88-fb415a78d8c4.png">

**What did you expect to happen?**
There should be an error message requiring you to enter a valid email

**Comment by ridz1208** [comment]
may or may not be related to https://github.com/aces/Loris/pull/8137
