### ISSUE TITLE
[my_preference] - modified information not showing in user account module

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#8551]
**Describe the bug**
A clear and concise description of what the bug is
When I modify my last name under my preference (user), I don't see the changes under the user account module when I am logged in as admin. 

test plan item: Modify any field on the page and save, and go to the User Account page. Check that the modifications are displayed when looking at the modified user account.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to my preferences
2. modify any information and save. Log in as admin and go see the account you modified using my preferences. 
3. You don't see the new information.

**What did you expect to happen?**
I would expect my last name to be modified or any other field that you modified using my preferences. 

Information I entered under my preferences:
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/25854264/230126431-02c2387b-f737-4c47-900c-7df5e45c3507.png">

Information that I see under the user account module:
<img width="962" alt="image" src="https://user-images.githubusercontent.com/25854264/230126567-c53983ba-ee1d-47df-bfdb-4ab0438eb8e9.png">

**Comment by GeorgeMurad** [comment]
Hi @charliehenrib, I have tested this issue and it seems working precisely. I can't see any issue with editing any field in My Preferneces.

![my_preferneces_1](https://user-images.githubusercontent.com/78069720/233151115-260da6f5-7480-4be6-a106-0fe908a6a7fe.png)
![my_preferneces_2](https://user-images.githubusercontent.com/78069720/233151130-94e39815-f428-4c93-9d2c-cb1feab6d710.png)

**Comment by charliehenrib** [comment]
@GeorgeMurad I just retested it on https://test-dev-250.loris.ca and It seems to be resolved now. Thank you
