### ISSUE TITLE
Issue Tracker 

### ISSUE THREAD

**Issue by aarushichaudhry** [aces/Loris#8552]
**Describe the bug**
Issues can be created with all of the required fields working as expected. However, when you get an issue assigned, the user(neither the assignee nor the reporter) is unable to look into its contents. Trying to open the issue opens up a blank page. Linking a screenshot for reference

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to Tools
2. Click on 'Issue Tracker'
3. Scroll down to any issue id. I have created ticket # 28 and 29
4. Try to open them by clicking the issue # or title

**What did you expect to happen?**
Ideally, you would expect to see the issue description with other relevant details such as PSCID, Visit Label, Category, Module, Attachments etc

**Browser Environment (please complete the following information):**
- OS: Mac)S Monterey version 12.6.3
- Browser : Chrome 

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by driusan** [comment]
PR merged
