### ISSUE TITLE
[DICOM Archive] archive not downloaded

### ISSUE THREAD

**Issue by regisoc** [aces/Loris#8554]
**Describe the bug**
When clicking on any of `Archive Location` column link, no download is triggered. We are only redirected to a blank page.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to menu > imaging > DICOM archive
2. Click on any link in the `Archive Location` column that should trigger a file download.

![Screenshot_2023-04-05_11-23-25](https://user-images.githubusercontent.com/25327259/230127926-cbc709fb-6228-4ceb-adfc-87d48cd9484b.png)

**What did you expect to happen?**
The file should be downloaded and its name should be prepended with the `Patient Name` field.

**Browser Environment (please complete the following information):**
- OS: 6.1.21-1-MANJARO
- Browser [e.g. chrome, firefox]: firefox
- Version [e.g. 22]: 111.0.1 (64-bit)

**Comment by regisoc** [comment]
@kongtiaowang This is resolved today, I can download without issue. 
It should be after the modifications Cecile did to the test vm.

**Comment by kongtiaowang** [comment]
@regisoc This is a RB_config data issue. I fixed this issue on the testing VM, I will send a PR to fix it.

**Comment by driusan** [comment]
PR merged
