### ISSUE TITLE
[examiner] Edit examiner bug

### ISSUE THREAD

**Issue by GeorgeMurad** [aces/Loris#8555]
- Edit the examiner is not showing even if the Enable the use of certification in the config.xml file.
- Steps to reproduce the behavior:
   1. Go to 'Examiner Module'
   2. Click on any Examiner name
   3. See that the `Edit Examiner` is not working and it's not clickable to edit
   
- After creating new `Examiner` we should be able to edit it by clicking on the name of that examiner. And then editing it.

Related to: https://github.com/aces/Loris/issues/8497

**Comment by GeorgeMurad** [comment]
Hi @driusan. I have re-tested the `Examiner` module after enable the use of certification under my config file and it works perfectly there's no issue anymore with that module. We are good to close this issue.

**Comment by nicolasbrossard** [comment]
This issue seems to have reappeared. Found again during the testing session for LORIS V25 on copn-stg.loris.ca.

**Comment by CamilleBeau** [comment]
Closing since it's a duplicate of #8764
