### ISSUE TITLE
[datadict] Source From filtering not working. 

### ISSUE THREAD

**Issue by racostas** [aces/Loris#8556]
**Describe the bug**
The "Source From" filter is not working. 

It seems the none of the "Source From" data that is actually populated in the table (with the RB data in the datadic) is "reflected" in the "Source From" filter.
At the same time it seem the `"Source From" filter` it is filled source fields that actually does not exist in the data (that is shown in the table).

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. MainMenu -> Tools -> Data Dictionary
2. Go to the "Source Form" filter and try to chose any of the "options" of even all together.
3. Nothing is show in the table (meaning it doesn't found coincidence) 
4. Click clear filters
5. You now see back the table populated.

Please see image for reference:
![image](https://user-images.githubusercontent.com/37309344/230132011-48e4c3f1-15d6-49a8-b94c-a9e75126fbc9.png)

**What did you expect to happen?**
The filter working properly. 
The data reflected in the filtering option for the "Source From" field to correspond with the data in the table and vice-versa.

**Browser Environment (please complete the following information):**
- OS: Microsoft Windows 10.
- Chrome 
- Version 111.0.5563.147 (Official Build) (64-bit)

**Server Environment (if known):**
25-0 official testing environment.  

**Additional context**
-

**Comment by zaliqarosli** [comment]
this is not an issue - the 'Source From' fitering works. the reason why no results are showing up on [the 25 test vm](https://test-dev-250.loris.ca/datadict/?) is because there are no fields available from instruments so its correct that no results appear. @driusan you can close this
