### ISSUE TITLE
[Brainbrowser] Intermittent failures

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#8562]
Half of the time, requesting the brainbrowser fails with those errors on https://test-dev-250.loris.ca/:

<img width="669" alt="Screenshot 2023-04-05 at 11 01 06 AM" src="https://user-images.githubusercontent.com/32041423/230139896-75999855-2f30-435d-be35-de9f9bd82a0d.png">

**Comment by driusan** [comment]
Does "half the time" mean on half the files or when loading the same files half the time?

It's possible the test VM doesn't have the images on the file system.

**Comment by xlecours** [comment]
Cecile, can you check if this can be a filesystem error?

**Comment by cmadjar** [comment]
@laemtl I just tried a couple of times opening brainbrowser and it seems to work now. Maybe you tested at a time where the filesystem was clunky or the config paths were changed making it impossible to find files at times. Once @kongtiaowang has updated test 25 with latest code changes of branch 25.0-release, you can probably resume testing brainbrowser as the bug where only one file was displayed on the imaging browser is resolved on 25.0-release.
