### ISSUE TITLE
[Conflicts Resolver] Making a selection on the 'Correct answer' dropdown does not do anything.

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#8563]
### Conflicts Resolver

Making a selection on the 'Correct answer' dropdown does not do anything. Nothing gets selected and no conflicts are resolved nor any changes take effect upon selecting a response. 

**To Reproduce**
1. Go to 'Conflicts Resolver'
2. Click on any of the dropdowns on the 'Correct answer' column
3. Make a selection for the 'Correct answer'
4. Nothing happens and selection is set back to 'Null'

**What did you expect to happen?**
Upon making a selection, the selected response would remain selected and be highlighted to indicate the selection for the change was made and that the change had been automatically made (Alternatively have a 'Save' button to confirm and enforce the implementation of selected responses). 

**Browser Environment (please complete the following information):**
- OS: Ventura 13.0.1 
- Browser: Chrome
- Version: Version 111.0.5563.64

**Additional context**

**Comment by SantiagoTG** [comment]
Conflicts can now be resolved and a selection is highlighted in light green, providing feedback on selection. 

However, upon changing the table page and returning to the page with the changes (say from page 1 to page 2 and back to page 1) will remove the highlighted changes, but the field remains in place, even though the previously made selection has already been set as a resolved conflict. 

Further, it would be a good idea to have a note or some instruction on the expected behavior of the module, as it may not be apparent at first how the module works and can lead to unintentionally resolving conflicts.

**Comment by kongtiaowang** [comment]
It works well as expect. after seting unresolved to resolved, the  unresolvered table will not has Resolved item once leave the current page. If you hope to has change history table, please create a proposal ticket.
