### ISSUE TITLE
[new_profile] the "Minimum candidate age" value for the 'Date of Birth' and 'Date of Birth Confirm' fields do not reflect the changes.

### ISSUE THREAD

**Issue by shonibare** [aces/Loris#8564]
**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to the 'Configuration' module, change the "Minimum candidate age" value
2. Then go to the 'New profile' module to create a new candidate
3. Enter DOB below the minimum age value entered in Step 1 and fill other fields
4. Then click submit

**What did you expect to happen?**
- It should pop-up error that the candidate's DOB entered is below the minimum age

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**
related to #8516

**Comment by xlecours** [comment]
Which changes should be reflected?

**Comment by shonibare** [comment]
> Which changes should be reflected?

When the date of birth below the minimum age is entered the form shouldn't save and pop an error message according to the test plan but it saves

**Comment by ridz1208** [comment]
@shonibare the minimum age is dependent on the enddate of the study
to check what the accepted range age you can inspect the date element and see it in the html

I recommend you go and play around the startdate/end date of the study as well as the ages to see how it works

**Comment by shonibare** [comment]
> @shonibare the minimum age is dependent on the enddate of the study to check what the accepted range age you can inspect the date element and see it in the html
> 
> I recommend you go and play around the startdate/end date of the study as well as the ages to see how it works

@ridz1208 I just understood how it works. I will close this issue. Thanks!
