### ISSUE TITLE
[battery_manager] Numbers larger than max not validated in form

### ISSUE THREAD

**Issue by jeffersoncasimir** [aces/Loris#8570]
The `BatteryManagerForm` component does not have proper validation for `Minimum/Maximum Age`, allowing values larger than the `NumericElement` component's maximum to be submitted, and leading to another bug described below.

When the value assigned to `Maximum Age` is larger than the form allows (99999), validation fails when trying to submit when the following sequence of actions is reproduced:

1. Navigate to the Battery Manager module, located under `Tools` in the menu as a user with the `battery_manager_edit` permission.
2. Press the `Edit` button on a row with a `Maximum Age` greater than 99999.
3. Increase the value of the `Minimum Age` by using the increment button of the `<input>` element and make sure it is set to a value greater than 1.
4. Press `Submit`.
5. Validation errors will display for `Minimum Age` and `Maximum Age`.

**Comment by driusan** [comment]
Fixed by #8672
