### ISSUE TITLE
[candidate_parameter] - Edit date of birth issue

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#8574]
**Describe the bug**
A clear and concise description of what the bug is
When I have permission to view candidate parameter and edit date of birth, I get an unspecific error that something went wrong and I cannot update the date of birth.  I don't get the error message when I have the following permission: Candidate Parameters: Edit Candidate Information
**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to candidate parameter
2. Click on date of birth
3. edit date of birth
4. See error below — the date still gets updated though

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/25854264/230174457-04462206-4a4f-456b-adf7-0feb12ae0d40.png">

**What did you expect to happen?**
the date of birth to be updated without getting an error message

**Comment by driusan** [comment]
PR merged
