### ISSUE TITLE
[instruments] 'Clear instruments' button not a button/clickable

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#8580]
**Describe the bug**
A clear and concise description of what the bug is

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):

**What did you expect to happen?**

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by miladheshmati** [comment]
@zaliqarosli could you please add more details about this issue and how to reproduce it?

**Comment by zaliqarosli** [comment]
@miladheshmati go to an instrument page and make sure you have the 'Instrument List: Send to DCC' permissiong.
on the left hand panel of the instrument page, you'll see 'Clear Instrument' at the top of the panel. This should be a clickable button but on the testing VM, it's only a text

<img width="1104" alt="Screenshot 2023-04-25 at 12 06 02 PM" src="https://user-images.githubusercontent.com/17415878/234337704-e9dc4b63-a115-4fab-a010-98ae2099c97f.png">

**Comment by zaliqarosli** [comment]
https://github.com/aces/Loris/pull/8681 fixes this issue by restoring the 'Delete instrument data' button

**Comment by zaliqarosli** [comment]
@driusan this can be closed

**Comment by driusan** [comment]
Fixed by above
