### ISSUE TITLE
[instruments] UI bug in control panel

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#8581]
**Describe the bug**

<img width="562" alt="Screenshot 2023-04-06 at 2 28 40 PM" src="https://user-images.githubusercontent.com/17415878/230470020-b0c69489-c2ea-4a96-a9a2-4d65ec4f69e7.png">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):

**What did you expect to happen?**

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by xlecours** [comment]
Can you look at why the `Instrument` section is diplayed even if there is no items in the list.

**Comment by zaliqarosli** [comment]
i think this is fixed by https://github.com/aces/Loris/pull/8681 and https://github.com/aces/Loris/pull/8573

**Comment by driusan** [comment]
@zaliqarosli in that case since you also created the issue can you verify and close this issue if so?
