### ISSUE TITLE
[candidate_profile] Media files not downloadable even if user has permission

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#8583]
**Describe the bug**
Media files appearing on candidate dashboard not downloadable even if user has permission "Media: View/Download Candidate Media Files". The file is only downloadable if the user has "Media: Edit/Upload/Delete Candidate Media Files" permission.

https://user-images.githubusercontent.com/17415878/230474259-af48d917-5c8a-4978-8f3e-86ce34c630c2.mov

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):

**What did you expect to happen?**

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by driusan** [comment]
Fixed by above PR
