### ISSUE TITLE
[Statistics] details links in behavioural statistics lead to improperly formatted data 

### ISSUE THREAD

**Issue by KLaFleur** [aces/Loris#8585]
**Describe the bug**
a number of links in the behavioural statistics page lead to data which renders in a lopsided way

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to the statistics module, then click ‘view details’ or 'Click here for breakdown per participant'
2. See error

**Browser Environment (please complete the following information):**
- OS: [osx]
- Browser: Chrome
- Version [111.0.5563.110]

**Comment by KLaFleur** [comment]
<img width="918" alt="Screen Shot 2023-04-06 at 3 21 45 PM" src="https://user-images.githubusercontent.com/35120091/230476898-3b1a46aa-d570-4a67-ad6d-b2852f9e51c9.png">

**Comment by driusan** [comment]
Fixed by above
