### ISSUE TITLE
Unable to create candidate because the date field doesn't allow inclusion of day of the month

### ISSUE THREAD

**Issue by KLaFleur** [aces/Loris#8586]
**Describe the bug**
unable to create candidate because the date field would not allow me to include the day of the month

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to new profile --> create new profile --> try to select DOB
2. Click on 'create'
3. See error (stopped because the date passed in is not complete

**What did you expect to happen?**
to be allowed to include a full dob

Browser Environment:

OS: [osx]
Browser: Chrome
Version [111.0.5563.110]

**Comment by driusan** [comment]
It is now merged
