### ISSUE TITLE
[candidate_list] Open Profile not working

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#8590]
**Describe the bug**
After entering PSCID and DCCID values (matching or not matching) in the Open Profile window and then clicking "Open Profile", the page get's stuck with the message `Validating...` and does display an error message or show results. 
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/51176779/231151402-dcebe32b-620e-4201-9395-ca886432d30a.png">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to Access Profile without the All Sites permission
2. Click on `Open Profile`
3. Enter values in PSCID / DCCID (Matching or not matching)

**What did you expect to happen?**
An error message if the PSCID / DCCID did not match, and results if they did.

**Comment by shonibare** [comment]
I tested this issue but no bug/error was found. It outputs an error if PSCID / DCCID does not match, and also load the candidate's profile if PSCID / DCCID match. 
<img width="1411" alt="Screenshot 2023-04-13 at 9 24 37 AM" src="https://user-images.githubusercontent.com/47093379/231773029-09080add-99c2-4d50-8e4b-f056ad8628c8.png">

**Comment by driusan** [comment]
@shonibare can you reproduce and fix now with @CamilleBeau's latest update?
