### ISSUE TITLE
[electrophysiology_uploader] Wrong message displayed when uploading a file with correct PSCID, incorrect CandID

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#8603]
**Describe the bug**

When trying to upload a file named with correct PSCID but incorrect CandID, get the following error:

![Screen Shot 2023-04-11 at 5 09 02 PM](https://user-images.githubusercontent.com/1402456/231288721-6beef56d-7407-4c0f-813a-1ff660fa86f8.png)

Instead, it should return an error saying that the CandID does not exist in the database or that there is a mismatch between PSCID and CandID in the filename.

**To Reproduce**

1.  Try uploading a file called `MTL001_3001_V1_bids.tar.gz` on RB database (should return a CandID does not exist error but it returns a visit does not exist error)
2. Try uploading a file called `MTL001_300002_V1_bids.tar.gz` on RB database (should return a PSCID/CandID mismatch error but it returns a visit does not exist error)
3. Try uploading a file called `patate_chaude_poilue_bids.tar.gz` on RB database (should return a candidate does not exist error but it returns a visit does not exist error)

**Comment by laemtl** [comment]
Also, adds validation for the file name (file is rejected after the upload is completed).
