### ISSUE TITLE
[electrophysiology_uploader] Can upload data to attach to inactive candidate

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#8604]
**Describe the bug**

Data can be uploaded even if a candidate is set to `Active='N'`. Not sure that it should be the case. Shouldn't an error be shown saying that the candidate is inactive?

**To Reproduce**

1. In RB database, set MTL001 candidate to inactive:
```
update candidate set Active='N' where PSCID="MTL001";
```

2. Upload a file named `MTL001_300001_V1_bids.tar.gz`

**Comment by xlecours** [comment]
The request should be responded with 404 Not found: candidate is not found.
