### ISSUE TITLE
[imaging_qc] table to CSV downloaded file also includes hidden columns

### ISSUE THREAD

**Issue by regisoc** [aces/Loris#8607]
**Describe the bug**

From test plan:
`Download the table as CSV. Make sure that the file downloads and that the contents of the file correspond exactly to the contents of the results table, including column and row order.` 

However, the CSV contains two more columns named `CommentID` and `TarchiveID` which are hidden fields. 
Do we want them in? It seems it appears for every hidden field in every module.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to menu > Imaging > Imaging Quality Control
2. Click on `Download table as CSV`
3. See the last two columns in the CSV

**What did you expect to happen?**

If the file is to `correspond exactly to the content of the results table`, then these two columns should be removed. 

**Browser Environment (please complete the following information):**
- OS: 6.1.21-1-MANJARO
- Browser: firefox
- Version: 111.0.1 (64-bit)

**Comment by laemtl** [comment]
Test plan needs to be updated.

**Comment by regisoc** [comment]
@charliehenrib can you add in the test plan that some hidden columns can be added in the CSV file?
