### ISSUE TITLE
[imaging_uploader] update test plan

### ISSUE THREAD

**Issue by regisoc** [aces/Loris#8609]
**Describe the bug**

Test plan needs to add/modify some points:

- `... Admin/Configuration module, ensure the 'ImagingUploader Auto launch' option is set to 'No'...` 
  - add the `study` config tab
- `Go in the profile details for the candidate found in step 13 and go into the visit table. Check that the MR Scan done column is set to 'Yes' for the visit at which the scan was done. Click on the Yes link and ensure you are taken to the Imaging Browser page with the valid scans performed for that candidate at that visit loaded in the result table. [Manual Testing]`
  - The `MR Scan done` column is set to `Y`, not `Yes`.
  - The link on `Y` does not exist, it is found at the bottom of the page, on the `View Imaging Data` button.

**Comment by xlecours** [comment]
This seems accurate. Can you send a PR with your suggestion?

**Comment by driusan** [comment]
Fixed by above
