### ISSUE TITLE
[configuration][dicom_archive] link error on config regex when trying to access dicom_archive

### ISSUE THREAD

**Issue by regisoc** [aces/Loris#8610]
**Describe the bug**

When any of these 4 regex configuration is empty (at least one): 
- Patient ID regex (`patientIDRegex`)
- Patient name regex (`patientNameRegex`)
- Lego phantom regex (`LegoPhantomRegex`)
- Living phantom regex (`LivingPhantomRegex`)

A permission error is raised trying to access the `dicom_archive` module.
Links can be found at least in `imaging_qc` table and `imaging_uploader` table.
The error message shown is not indicative of what is happening. 

![image](https://user-images.githubusercontent.com/25327259/231305662-80426927-e5c1-4232-8b6d-e64a5829c39e.png)

**To Reproduce**

Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to menu > admin > configuration
2. Click on 'imaging modules' and empty one of the regex fields:

![image](https://user-images.githubusercontent.com/25327259/231305523-92ed3eea-ffca-49d1-b456-4110b2d2cf06.png)

3. Go to menu > imaging > imaging quality control (could be `imaging uploader` too)
4. filter the table by `Tarchive = In DICOM Archives`
5. Click on one of the link `In DICOM` found in the table column `Tarchive`
6. See error
7. When putting at least the most basic regex inside these configurations (i.e. `.`), the link in the `imaging qc` table works.

**What did you expect to happen?**

A clear error message to target these configurations.

**Comment by xlecours** [comment]
This is expected when a config is missing.
