### ISSUE TITLE
[Imaging Browser] Scan not showing, loading up on Brainbrowser nor downloading

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#8612]
Scan in the imaging browser are not not showing in the Imaging Browser (see screenshot #1), loading up on Brainbrowser (See screenshot #2) nor downloading (See screenshot #3). 

**Screenshot #1:**
<img width="600" alt="Screenshot 2023-04-11 at 7 44 29 PM" src="https://user-images.githubusercontent.com/54332302/231312132-0c5b4dce-353d-48d4-9c61-bca42e1722e5.png">

**Screenshot #2:**
<img width="1027" alt="Screenshot 2023-04-11 at 7 44 36 PM" src="https://user-images.githubusercontent.com/54332302/231312075-0ef72e44-b382-41bd-8039-8f8766fba47f.png">

**Screenshot #3:**
<img width="824" alt="Screenshot 2023-04-11 at 10 42 05 AM" src="https://user-images.githubusercontent.com/54332302/231312178-00fdd1dd-2f82-4498-8a0b-d127d5943ea4.png">

**Related to:**
- https://github.com/aces/Loris/issues/8524

**Comment by cmadjar** [comment]
@SantiagoTG I am closing this since I believe this is resolved now that the image path config is set correctly
