### ISSUE TITLE
[help_editor] JS console error obtained during testing

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#8622]
Step to reproduce:
1. Log on the testing VM and click on the Help Editor menu (Admin section)
2. Click on the bmi link to edit the instrument's help text
This was displayed in the JS console afterwards:
```
Warning: Failed prop type: Invalid prop `helpid` of type `number` supplied to `HelpEditorForm`, expected `string`.
    at HelpEditorForm (https://test-dev-250.loris.ca/help_editor/js/helpEditorForm.js:14711:89)
    at bound createElementWithValidation
```

**Comment by GeorgeMurad** [comment]
I've tested the issue and it seems got fixed since the last update Shen solved. No bugs related to this [help_editor] anymore

**Comment by GeorgeMurad** [comment]
@nicolasbrossard, can we close this issue as soon as it is solved?
