### ISSUE TITLE
[help_editor] Test plan needs updating

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#8624]
1. Content not scrollable anymore (remove step 5).
2. No more "Return to" button (remove step 7).
3. Not sure step 15 is still relevant...
4. No more Reset button (remove step 16).
5. No more Preview button (adapt step 17 to cover behavior).

**Comment by ridz1208** [comment]
https://github.com/aces/Loris/issues/5776 consider these items as well
