### ISSUE TITLE
[mri_violations] Need space between patient name and series UID

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#8627]
When I click on a violations with status "Cannot identify scan type", I get a popup displaying the scan properties: there needs to be a bit of spacing added between the "Patient Name" and "Series UID" columns, otherwise they look like they were merged together (see screenshot)

<img width="1490" alt="Screen Shot 2023-04-12 at 12 46 55 PM" src="https://user-images.githubusercontent.com/6844033/231528290-894feaf0-4708-406f-815c-dcaeabfaf8e8.png">

**Comment by driusan** [comment]
Fixed by above PR
