### ISSUE TITLE
[Mri Violation] can't load mri violation on local inner integration test - ReactDOM.createRoot(container) is not a function

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#8630]
**Describe the bug**
can't load mri violation on local inner integration test - ReactDOM.createRoot(container) is not a function
**To Reproduce**
run intergration test local with node 12.

**What did you expect to happen?**
test function fail on step 8 9 10

**Browser Environment (please complete the following information):**
- OS: php 8.1 node 12
- Browser firefox 
- Version 25.0-release

**Comment by driusan** [comment]
Fixed by #8651 (which replaced the above PR)
