### ISSUE TITLE
[EEG] "physiological_electrode" schema missing PhysiologicalFileID column

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#8669]
**Describe the bug**
[EEG] "physiological_electrode" schema missing PhysiologicalFileID column

**To Reproduce**
  'https://test-dev-250.loris.ca/api/v0.0.3/candidates/300174/V1/recordings' 
will got 500 error

**Comment by regisoc** [comment]
#8658 updated SQL requests on recording class

**Comment by christinerogers** [comment]
@regisoc is this issue fully addressed?  if so, could you comment and close? thanks

**Comment by regisoc** [comment]
@christinerogers I think it is through #8658 merging yes.
@kongtiaowang can you confirm?
