### ISSUE TITLE
[module_manager] - My preferences still available after deactivation

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#8695]
**Describe the bug**
When I deactivate my preferences in the module manager, it still appears under my name and when I click on it, I get a 404 error:
<img width="1401" alt="image" src="https://github.com/aces/Loris/assets/25854264/9581ed16-c49b-4d4e-a0ad-1072d55880ca">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to module manager
2. Deactivate my preferences
3. Reload the page and click on my preferences
4. See error 404. 

**What did you expect to happen?**
when I click on my name, I should not see the option for my preferences module.

**Comment by driusan** [comment]
@jeffersoncasimir Usually the menu items come from the `module->getMenuItems()` call but that's only true for the main dropdown menu items. This one might need special casing in the smarty template. Let me know if you have any questions or problems fixing it or if you need help with it.

**Comment by driusan** [comment]
Fixed by above PR
