### ISSUE TITLE
[Imaging Browser] 'Reset view' button not working on 'Brainbrowser'

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#8698]
The 'Reset View' on the 'Brainbrowser' window is not resetting the view nor making any changes.

<img width="1383" alt="Screenshot 2023-05-11 at 10 47 10 AM" src="https://github.com/aces/Loris/assets/54332302/940a47ac-7485-4952-928c-f55138584208">

**Related to:**
- https://github.com/aces/Loris/issues/8524

**Comment by laemtl** [comment]
@SantiagoTG have you played with the coordinates first?

**Comment by SantiagoTG** [comment]
I have modified the 'World Coordinates', the 'Color map', the 'Voxel Coordinates', the 'Threshold', 'Intensity' and 'Brightness' and none of these are set back to the default values upon clicking 'Reset view'.

**Comment by SantiagoTG** [comment]
Upon review, the 'Reset View' button only resets the zoom view, and not any of the other parameters (i.e. 'World Coordinates', 'Color map', 'Voxel Coordinates', 'Threshold', 'Intensity', 'Brightness'). This is currently what the code is meant to do, so it seems the function is working as intended. It would be good idea to discuss if the 'Reset View' button should include resetting of the other parameters as well.
