### ISSUE TITLE
[[candidate_parameters] the module could be accessed without having candidate_parameters permissions if you have the access_all_profiles one.

### ISSUE THREAD

**Issue by racostas** [aces/Loris#8733]
**Describe the bug**
The module could be accessed without having `candidate_parameters `permissions if you have the` access_all_profiles` one.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
When a user have the candidate_parameters permission but not the access_all_profiles the following link is not shown **(as is intended)**
![image](https://github.com/aces/Loris/assets/37309344/b93e4f00-3db6-4f34-86b0-2868c55d4e46)
![image](https://github.com/aces/Loris/assets/37309344/543e2c41-293c-4e3b-8aa1-8f95b5e89b8f)

3. Nevertheless with this same "set of permissions" if you put in the URL something like:
`https://... lorsisInstance.../candidate_parameters/?candID=698301&identifier=698301`

5. The page shows 
![image](https://github.com/aces/Loris/assets/37309344/dbfd23c4-9667-4aa5-abfe-130bf866750f)

**What did you expect to happen?**
The correct in this case would be to show a permission denied message in place of the image in point 5.

**Browser Environment (please complete the following information):**
- Chrome -- 114.0.5735.110 (Official Build) (64-bit)

**Server Environment (if known):**
Loris 25 testing VM.

**Comment by driusan** [comment]
I don't understand why this would be changed. Why is the correct behaviour to have a permission denied message when you have access_all_profiles? Shouldn't you be able to access the profile?

**Comment by christinerogers** [comment]
sounds like this should come up for discussion in the loris meeting
