### ISSUE TITLE
[Media] - can't show hide file by current user.

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#8738]
**Describe the bug**
https://copn-stg.loris.ca/
Media - can't show hide file after current user set it to hide.
**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'media'
2. Click on 'edit'
3. Scroll down to 'YES' of Hide
4. See the file is gone. 

**What did you expect to happen?**
should see the file with red color

**Comment by driusan** [comment]
Why did you expect to see the file with red colour? The test plan says "Delete files. Deleting a file hides it from the frontend, but preserves a copy in the database." and "The file should no longer be displayed in the data table (unless the user has superuser permissions). - Note: only a person with direct database access could revert the hide file action."

**Comment by kongtiaowang** [comment]
It is not a bug, So I will close this issue.
