### ISSUE TITLE
[battery_manager] update test plan

### ISSUE THREAD

**Issue by regisoc** [aces/Loris#8739]
**Describe the bug**

Test plan needs an update.

1.

```
Testing Change Status column
    Press the Deactivate button in the Change Status column on an entry in the data table.
        Ensure that when you press "Yes", a success message appears and the table data refreshes.
```

No `Yes` confirmation option is shown. When clicking the deactivate button, the change is immediate.

2.

```
Instrument, Stage, Cohort, Visit Label, Site, First Visit, Instrument Order, and Active (as dropdown fields with blank default option).
```

This line should not include `Instrument Order` (not a dropdown field).

3.

```
Try to edit an entry so that it has the same values as another deactivated entry in the Test Battery. 
```

We cannot create an entry with the same values, so I am not sure how to test this.

**What did you expect to happen?**
Change the test plan

**Comment by driusan** [comment]
fixed by linked PR, wasn't autoclosed..
