### ISSUE TITLE
[data_release] "Unversioned" permissions granted with every version

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#8741]
**Describe the bug**
When adding version permissions for a user, the "Unversioned" permission is also granted to that user unintentionally.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to data_release
2. Make sure that there is at least one file uploaded without a version (version will show up as "Unversioned"), and at least one file uploaded under a specified version
3. Add permissions for a user to give them permission to the specified version
4. See that the user now has permission to both the specified version, and "Unversioned"

**What did you expect to happen?**
When adding permissions to one version for a user, that user should have permission to only that version, and not "Unversioned". "Unversioned" should only be granted to a user if it is added as a permission on its own.

**Comment by driusan** [comment]
PR was merged
