### ISSUE TITLE
[new_profile] Error popup "EDC must be specified" appears when useEDC = yes

### ISSUE THREAD

**Issue by charlottesce** [aces/Loris#8742]
**Describe the bug**
When trying to create a new patient with useEDC on, an error pop-up with "Error! EDC must be specified" appears, even if all fields are filled out. 
<img width="500" alt="image" src="https://github.com/aces/Loris/assets/75381352/5bdff19b-c6f0-4125-a068-d4a9ea83dbef">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Turn on useEDC in Configurations -> Study 
2. Go to Patients -> New Patient
3. Enter all fields 
4. Click on 'Create'
5. See error

**What did you expect to happen?**
When all fields are filled out, creating the new patient should be successful.

**Comment by driusan** [comment]
PR was merged,
