### ISSUE TITLE
[My Preferences] - Password change expected for  any change in preferences.

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#8745]
**Describe the bug**

When the 'My Preferences' module is accessed, if the user tries to modify one of the options, the module will ask for a password change. The first line of 'New password' is automatically entered, with the 'Confirm Password' empty. When looking to update any of the preference options, it will automatically assume the password is being updated (See screenshot).

<img width="863" alt="Screenshot 2023-06-08 at 10 47 58 AM" src="https://github.com/aces/Loris/assets/54332302/e24c6e3e-d4ac-455a-87d4-ccffbf8d8575">

**To Reproduce**
Access 'My preferences' and select some of the 'Notifications' checkboxes. Try to update. 

**What did you expect to happen?**
When opening 'My Preferences', either both password fields would be automatically populated or otherwise empty, so that the module does not assume a password change every time the user wants to update his/her preferences.

**Related to:**
- https://github.com/aces/Loris/issues/8538

**Comment by driusan** [comment]
@SantiagoTG What browser is this? I think it's auto-populating an entry into the first "new password" box which is causing it to not be empty (or match the second one)

**Comment by SantiagoTG** [comment]
@driusan This was on Chrome v113.0.5672.126.

**Comment by driusan** [comment]
Fixed (as much as it can be fixed, since it's the browser auto-filling the password) by #7933
