### ISSUE TITLE
[Login] Request Account Signature Date Can Be in the Future

### ISSUE THREAD

**Issue by skarya22** [aces/Loris#8752]
**Describe the bug**
When requesting a new user account, the signature date can be in the future which doesn't make much sense.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Logout if logged in
2. Press "Request Account"
3. Enter valid details for everything and set the date under the signature as something in the future
4. Request the account and watch as it goes through
<img width="418" alt="image" src="https://github.com/aces/Loris/assets/51128536/54c13563-9500-4d88-bfec-46c9ce1be26f">

**What did you expect to happen?**
A warning to appear that the signature date cannot be in the future

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: 25.0.0

**Comment by driusan** [comment]
@zaliqarosli is this a COPN override? I don't think we have that on LORIS?

**Comment by zaliqarosli** [comment]
yes, this is a C-OPN override. feel free to close, i'll open an issue on the project repo
