### ISSUE TITLE
[new_profile] Date of birth in 'YM' format - year 1894 defaults to 2023 

### ISSUE THREAD

**Issue by charlottesce** [aces/Loris#8753]
**Describe the bug**
If the DOB format is 'YM', when you click on the text box to enter a date, a date widget appears with defaulting at year 1894. When a date in year 1894 is chosen with this widget, the date entry then appears in the year 2023 in the text box. 
<img width="300" alt="image" src="https://github.com/aces/Loris/assets/75381352/7de050d7-f157-4249-9692-486891645af0">
<img width="300" alt="image" src="https://github.com/aces/Loris/assets/75381352/25551ec1-6b13-4ce1-9e20-e21554ab9add">

 However, when you click on the calendar next to the text box, this widget appears and selecting dates in the year 1894 is fine. 
<img width="400" alt="image" src="https://github.com/aces/Loris/assets/75381352/2fd04200-51ed-41c9-a01f-e9f723c2b736">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Set DOB format to 'YM' in Configuration 
2. Go to Patients -> New Patient 
3. Click on the text box for DOB 
4. Select a date in the year 1894
5. See error

**What did you expect to happen?**
When a date in 1894 is selected in the date widget, that date should then appear in the text box. 

**Browser Environment (please complete the following information):**
Tested in Chrome and Mozilla Firefox and the error appears in both

**Comment by skarya22** [comment]
@driusan @zaliqarosli 
Looks like this issue is not present on LORIS 25 release, and is caused by a COPN override, how should I proceed with that?
