### ISSUE TITLE
[document_repository] Improper error handling

### ISSUE THREAD

**Issue by jeffersoncasimir** [aces/Loris#8760]
**Describe the bug**
Certain errors are not properly reported. They return a generic "Please contact your administrator" message, caused by a `Syntax error` on the front-end due to the responses being invalid JSON. 

These errors were: `413 (Request Entity Too Large)` for test plan step 16 and a `403 (Forbidden)`, which occurred when initiating an upload, and logging out in another tab before completion.

Found during testing assignment #8519.

**Comment by driusan** [comment]
@kongtiaowang Can you look into fixing this? I think you just need to check resp.status and in the swal instead of saying "Please contact your administrator" have a permission denied (for 403) or file too large (for 413) error message.
