### ISSUE TITLE
[datadict] Buggy DataTable 

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#8769]
**Describe the bug**
<img width="1434" alt="Screenshot 2023-06-09 at 5 52 20 PM" src="https://github.com/aces/Loris/assets/17415878/c59bcda2-f1fa-4e86-a68d-80843ee0b395">

This is happening with other modules as well. The table extends passed the panel when it should overflow / be scrollable

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):

**What did you expect to happen?**

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by regisoc** [comment]
@driusan cannot reproduce.
