### ISSUE TITLE
[imaging_uploader] Visit Label populated from the entire end of the file name

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#8803]
Visit Label should only be populated by the third parameter in the file name, not the rest of the file name after CandID (as is what's happening)

The "Notes" below the uploader states "For files that are not Phantom Scans, file name must **begin** with [PSCID]_[CandID]_[Visit Label]", so anything after VisitLabel should be accepted, even if not a required parameter

i.e. in the screenshot (1), Visit Label is auto-populated as 'MRI02_MNI_20230428_105929723' when should just be 'MRI02'. The Visit Label incorrectly populating results in an error (2).

(1)<img width="685" alt="Screenshot 2023-06-20 at 6 37 33 PM" src="https://github.com/aces/Loris/assets/17415878/5f04b3f5-5ae7-4804-8072-4919b2a3ade6">

(2)<img width="858" alt="Screenshot 2023-06-20 at 6 41 09 PM" src="https://github.com/aces/Loris/assets/17415878/4754d176-ed1c-4b66-b8a3-191af1ea22b9">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):

**What did you expect to happen?**

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by ridz1208** [comment]
@zaliqarosli issues started here https://github.com/aces/Loris/pull/5306

**Comment by zaliqarosli** [comment]
PR merged
