### ISSUE TITLE
[imaging_uploader] A file that exceeds the max upload size doesn't give swal error warning

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#8807]
**Describe the bug**
When uploading a file that exceeds the max uploader size, the user should see a swal pop with the appropriate error. 
Instead, nothing pops up, but theres a 413 error in the console

<img width="1412" alt="Screenshot 2023-06-21 at 10 30 50 AM" src="https://github.com/aces/Loris/assets/17415878/edbe7cb2-1dae-42ef-97df-b6bd014b978d">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):

**What did you expect to happen?**

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by CamilleBeau** [comment]
On 26 I am getting a swal that is not specific to the error: 
<img width="1436" alt="image" src="https://github.com/aces/Loris/assets/51176779/002adee3-3ab3-4b6e-8d06-ffe8b46b5d5d">

**Comment by kongtiaowang** [comment]
It has been fixed. 
<img width="900" alt="截屏2024-04-04 下午5 51 45" src="https://github.com/aces/Loris/assets/9876007/1f5dcb6e-8391-497f-8351-8365b64acf79">
