### ISSUE TITLE
Add robots.txt file

### ISSUE THREAD

**Issue by driusan** [aces/Loris#8865]
There is no `robots.txt` file provided by LORIS. It probably doesn't make sense to index anything on a LORIS instance anyways, since a crawler can't get past the login page, so we could use a policy similar to the CBRAIN one at https://github.com/aces/cbrain/blob/master/BrainPortal/public/robots.txt by default in LORIS.

**Comment by divyakelaskar** [comment]
I would like to work on this. Where should I add the `robots.txt`?

**Comment by driusan** [comment]
The `htdocs` directory is served as the Apache root, so it should just go directly in there to be served as `/robots.txt`
