### ISSUE TITLE
[issue_tracker] The Assignee is not populated when updating and issue (also preventing the page to save)

### ISSUE THREAD

**Issue by racostas** [aces/Loris#8872]
**Describe the bug**
The assignee is not been populated when updating an issue. This is preventing the page to save without showing any error to the user or even in the log files.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. MainMenu->Tools->Issue Tracker
2. Click `New Issue` button to create a new issue.
3. When creating a new issue please assign it to one of the users (even if this field is not mandatory)
![image](https://github.com/aces/Loris/assets/37309344/c0774521-c7cc-4d91-9e94-e9b1a5ac2af6)
5. Save the page and all should be fine, even if now goes to the issue tracker list the issue will show the assignee.
![image](https://github.com/aces/Loris/assets/37309344/0d981c36-6d53-444f-9388-8daabd6cc886)
 
7.  **now the issue**
8. If you enter to this issue to edit it the `assignee` is not longer shown.  
![image](https://github.com/aces/Loris/assets/37309344/03e7cd3c-8129-41b1-970e-1ca31d9d7671)
9. If you try to save the page without assignee you got 500 error in the console but not error is shown to the user in the UI neither in the backend logs.

**What did you expect to happen?**
1. The assignee to be populated accordingly.
2.  If the assignee is removed on purpose when updating the issue ( this is other possible scenario) the page to save without assignee and properly reflected in the history table.

**Browser Environment (please complete the following information):**
- OS: Ubuntu 18 
- Browser Chrome Version 116.0.5845.97 (Official Build) (64-bit)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 25.0.0]
- Linux distribution and Version: Ubuntu 18 
- MySQL/MariaDB Version: MySQL 5.7

**Comment by charlottesce** [comment]
@racostas This should be fixed with #8850

**Comment by racostas** [comment]
Assigning @skarya22 since a PR coming from a CCNA override should solve it.

**Comment by christinerogers** [comment]
@racostas can this be closed since #8885 was merged?

**Comment by christinerogers** [comment]
Closing since #8885 was merged
