### ISSUE TITLE
[EEG pipeline] chunking data shift fix 

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#8892]
aiming for 25.1 loris & loris-mri release : Jefferson's OHBM hackathon fix to smooth the chunking boundaries. 
 per Loris-eeg meeting :   aim for 25.1 

Solution to smooth the gap between chunks -- pass the # of data points from the last chunk into the iteration for the next chunk. 

PR to come from Jefferson (for 25.1 ideally)

**Comment by jeffersoncasimir** [comment]
Closed by #8999
