### ISSUE TITLE
[Issue Tracker] Add ‘Instrument’ from a drop down of all instruments

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#8896]
For the Issue Tracker, add dropdown field to select the ‘Instrument’ from a drop down of all instruments.

**Related to:**
- https://redmine.cbrain.mcgill.ca/issues/11057
- https://github.com/aces/Loris/issues/4150
- https://github.com/aces/Loris/issues/8328

**Comment by racostas** [comment]
Agreed with @regisoc we are assigning this one to a GSoC student since looks something the can handle now.
