### ISSUE TITLE
[EEG] HED Tag Support

### ISSUE THREAD

**Issue by jeffersoncasimir** [aces/Loris#8910]
HED tag support, which is present in EEGNet, can be brought in to LORIS. This adds the ability to add and remove HED tags from event instances and attribute mappings (events.json).

This includes SQL patches and significant Loris-MRI changes.

This also includes the removal of "Annotations" in favour for "Events", in order to keep up with the latest BIDS specifications, and a CouchDB import.

**Comment by christinerogers** [comment]
I'm pretty sure this should be @jeffersoncasimir not @laemtl  (if you're talking about who makes the PR not testing?)
