### ISSUE TITLE
[DQT] Add function to toggle 'Instrument names' for field selection

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#8954]
For the DQT, when a user is on the 'Define Fields' section, a button or feature to toggle the 'Category' display between backend instrument names and 'Standard' instrument names would be very helpful (particularly in the context of more systematically and cryptic backend  instrument names as is the case for HBCD). 

As a related feature, perhaps a configurable mapping could be added in the 'Configuration' module to allow users with the adequate permission to edit the 'Front end' name of a given instrument. 

**Related to:**
- https://github.com/aces/Loris/issues/8886

**Comment by ridz1208** [comment]
@driusan 's DQT currently does this
