### ISSUE TITLE
No content displayed while using MariaDB

### ISSUE THREAD

**Issue by MaximeMulder** [aces/Loris#9016]
**Describe the bug**

I recently tried to install LORIS with both MySQL and MariaDB. While it works nicely with MySQL, I encountered a bug in the database installer with MariaDB, and even after applying a small localized fix in #9015, LORIS indicates that the installation is complete yet displays no content outside of the most basic interface :

![image](https://github.com/aces/Loris/assets/23308005/3f8c5768-690f-4813-b33d-2fc83b176f65)

**To Reproduce**

Follow the installation guide in a similar environment. The bug occurs consistently on my machine.

**Browser Environment (please complete the following information):**

- OS: Windows 11
- Browser: Mozilla Firefox 121 / Google Chrome 120
- Note: This does not look like a browser related bug

**Server Environment:**

- LORIS Version: 25.0.2
- Linux distribution and Version: Debian 12 via WSL2
- MySQL/MariaDB Version: MySQL 8.0.36 / MariaDB 10.11.4

**Additional context**

I found some unrelated issues with people mentionning MariaDB as their database. Does this mean this bug only happens in some specific environments ?

**Comment by driusan** [comment]
Most developers use MariaDB. It seems unlikely that that's the cause of your problem. It says you're using WSL2, so it seems much more likely that Windows is the source of your problem. I don't think anyone has run LORIS under Windows.

Can you try installing it in a VM on the same machine to try and pinpoint if that's the problem?

**Comment by MaximeMulder** [comment]
Closin in favor of #9101, which is going to be more descriptive.
