### ISSUE TITLE
Opinion on linter rules

### ISSUE THREAD

**Issue by MaximeMulder** [aces/Loris#9047]
Hello,

I just finished my first large pull request (#9046) and while running the linters, I found that there are a few lints that I think are either not very useful or sometimes harmful. I'd like to know if it would be ok to change them.

The lints in question are:

1. Line length limit: I think 80 or 85 characters is too short. It certainly made sense at a time were monitors were smaller. But anything under 100 characters (which is the limit I recommend) can comfortably sit on a modern monitor. This lint forces to split single lines into multiple ones, which makes the code takes too much space and decreases its readability imo. This one lint is my main concern.

2. Missing JSDoc: While it makes sense for a lot of functions to have a documentation. I find that types can often be enough of a documentation, especially when the code is very straigh forward like in React component, and especially when the function is internal to a module.

3. Empty arrow function: I needed a placeholder for my React context, I didn't think it would trigger an error.

4. Assignment alignment: Less sure about that one. On one hand I like it but on the other I find it to be troublesome in this kind of situation:

```php
$short     = foo($a)
$short_bis = foo($b) // It forces to unnecessarily lengthen these lines

$quite_a_long_variable = $bar->baz($c);
$maybe_long            = $bar->baz($d);
```

Does anyone have an opinion on these here ?

**Comment by driusan** [comment]
We are not weakening any lint rules, but we are *definitely* not removing the line length, alignment, or documentation rules, which ensure that the code is readable, in particular.

**Comment by MaximeMulder** [comment]
I am fine with that decision, but I'd just like to clarify that I was **not** advocating for a complete removal of the rules, at most change the parameters (line length) or put them as a warning. The argument that these rules ensure the code is readable is reasonable but is also a generalization that does not work in a 100% of cases imo.

(this comment does not serve as an argument to re-open the issue, but I simply wanted to clarify my point of view in this disagreement)
