### ISSUE TITLE
[electrophysiology_uploader] Only the Site filter is shown in the Browse page.

### ISSUE THREAD

**Issue by racostas** [aces/Loris#9059]
**Describe the bug**
A clear and concise description of what the bug is
Only the Site filter is shown in the Browse page.
![image](https://github.com/aces/Loris/assets/37309344/9b415dc4-29a3-4562-b58e-d8ecf6c9ebcf)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to MainMenu->Electrophysiology->Electrophysiology Uploader
2. Browse tab
3. Only site filtering is shown.

**What did you expect to happen?**
According to the test plan we should be able to filter for other fields as well. 
![image](https://github.com/aces/Loris/assets/37309344/00c696f0-97a4-48f0-9a17-78f58281ea2c)

**Browser Environment (please complete the following information):**
- MsWindows10
- Google Chrome Version 121.0.6167.184 (Official Build) (64-bit)

**Server Environment (if known):**
https://test-dev-260.loris.ca/

**Comment by kongtiaowang** [comment]
only happen on testing VM, it has been fixed.
