### ISSUE TITLE
[new_profile] Can't create a new profile

### ISSUE THREAD

**Issue by skarya22** [aces/Loris#9060]
**Describe the bug**
Can't create a new candidate profile. There is a 500 error due to an incorrect type of variable $ProjectID

**To Reproduce**
Steps to reproduce the behaviour (attach screenshots if applicable):
1. Go to New Profile
2. Enter valid details
3. Press Create

**What did you expect to happen?**
A candidate is created

**Server Environment (if known):**
- LORIS Version: 26.0

![image](https://github.com/aces/Loris/assets/51128536/8e3144bd-c830-43b2-9b1d-b62530106ab5)

**Comment by skarya22** [comment]
This was just a problem with the 26 testing vm

**Comment by kongtiaowang** [comment]
yes, it has been fixed on testing VM
