### ISSUE TITLE
[timepoint_list] Create timepoint issue

### ISSUE THREAD

**Issue by miladheshmati** [aces/Loris#9063]
**Describe the bug**
As we proceed to create a new time point, nothing happens after pressing "Create Time Point"

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to timepoint_list
2. try to create a new time point

<img width="1028" alt="Screenshot 2024-02-15 at 2 58 28 PM" src="https://github.com/aces/Loris/assets/51356424/4fa5f342-35b7-4959-8e6e-2a00c6635c71">

**Comment by kongtiaowang** [comment]
only on testing VM.

**Comment by kongtiaowang** [comment]
it has been fixed.
