### ISSUE TITLE
[user_accounts] Outdated TestPlan.md + potential permission issue

### ISSUE THREAD

**Issue by jeffersoncasimir** [aces/Loris#9064]
The [TestPlan.md](https://github.com/aces/Loris/blob/87a3dd5bde053728b99db49cc194de8a96886370/modules/user_accounts/test/TestPlan.md?plain=1#L44) says the following:

> 15. Verify that if the editor does not have permission 'Across all sites add and edit users' then the site drop-down list is populated with the editor's associated sites, otherwise all sites are displayed.

`Site` is now a multi-select and this should be reflected in the documentation.

Note: The above quoted item is only true for the `Edit User` page. When at the index, the `FilterableDataTable`'s `Site` filter contains all sites even if the user only has permissions for a single site and the `User Accounts: View/Create/Edit User Accounts - Own Sites` permission. This does not appear the be the case for other modules' `FilterableDataTable`.

**Comment by driusan** [comment]
This was discussed in the LORIS meeting and the decision was that it makes sense to see other sites as long as you have at least one in common with the user, therefore there's no reason to restrict the menu filter dropdown options to only your own sites (since there are others in the data you see.)
