### ISSUE TITLE
[dataquery] Bottom-right boxed arrow difficult to click

### ISSUE THREAD

**Issue by regisoc** [aces/Loris#9065]
**Describe the bug**

Not really a bug, more an enhancement.
Clicking the arrow of the bottom-right box is an eye-hand motor skill check when scrollbar appears.

![image](https://github.com/aces/Loris/assets/25327259/0093b44c-1ee6-4ccc-a14d-42a77a7c827b)
![image](https://github.com/aces/Loris/assets/25327259/36460d09-91fe-4e3b-a9cb-e1b738af3be9)
![image](https://github.com/aces/Loris/assets/25327259/8e5a3530-4d6e-465e-8f37-820f72f42ae8)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to https://test-dev-260.loris.ca/dataquery/
2. Try interacting with the bottom-right arrow.

**What did you expect to happen?**
Is the feature needed to hide the bottom-right box?
If so, maybe a small padding/margin should be enough.

**Browser Environment (please complete the following information):**
- OS: 6.6.10-1-MANJARO
- Browser: Firefox 121.0.1 (64-bit)

**Server Environment (if known):**
v26 test vm

**Comment by driusan** [comment]
Seems like the scrollbar is hiding it. What's your screen resolution?

**Comment by regisoc** [comment]
1920 x 1080
