### ISSUE TITLE
[dataquery] bottom panel collapse

### ISSUE THREAD

**Issue by regisoc** [aces/Loris#9067]
**Describe the bug**

Clicking the bottom panel to collapse closes the top one.

![image](https://github.com/aces/Loris/assets/25327259/d7acb025-981a-4c51-bf11-c9115c55a906)
![image](https://github.com/aces/Loris/assets/25327259/6e76335b-acb8-49fe-aa71-3771c4d4525f)
 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to https://test-dev-260.loris.ca/dataquery/
2. Click the "Recent queries" collapse panel header button.
3. see error.

**What did you expect to happen?**
The bottom panel should collapse.

**Browser Environment (please complete the following information):**
- OS: 6.6.10-1-MANJARO
- Browser: Firefox 121.0.1 (64-bit)

**Server Environment (if known):**
v26 test vm

**Comment by driusan** [comment]
I have a feeling this is related to jsx/Panel.js, not the dataquery module. Do we have any other modules with multiple panels?

**Comment by regisoc** [comment]
Good point. Not sure about it. I will try with another I can find one, else I will just create a dummy page to test it.

**Comment by driusan** [comment]
@kongtiaowang can you look into this? Like I said in the comment it's likely a problem with panel.js not the dataquery tool. If you need any help let me know.
