### ISSUE TITLE
[dataquery] stuck with strikethrough filters

### ISSUE THREAD

**Issue by regisoc** [aces/Loris#9076]
**Describe the bug**
In filter selection, when removing then adding back the same filter makes it still appear as `removed` (strikethrough).

![image](https://github.com/aces/Loris/assets/25327259/c0f28be9-3790-4dd7-8246-ea2470d3288e)

**To Reproduce**
1. Go to Tools > data query tools (alpha)
2. Go to the filter page.
3. Click `Add condition`.
4. Enter `category = candidate identifier`
5. Enter `Field = LORIS candidate identifier`
6. Enter `Operator = "="`
7. Enter `Value = 3`
8. Submit
9. Line added successfully. 
10. Click the `trashbin` icon on the right for that condition.
11. Then redo steps 3 to 8.
12. The line now appears as `to be removed` (strikethrough).

**What did you expect to happen?**
No strikethrough behaviour.

**Browser Environment (please complete the following information):**
- OS: 6.6.10-1-MANJARO
- Browser: Firefox 121.0.1 (64-bit)

**Server Environment (if known):**
v26 test vm

**Comment by driusan** [comment]
This is an annoying bug that I haven't been able to track down. The strike through is only supposed to happen when you hover over the trashbin icon, but for some reason it's sometimes there when you first add a criteria.
