### ISSUE TITLE
[battery_manager] maximum value in RB is too high.

### ISSUE THREAD

**Issue by regisoc** [aces/Loris#9079]
**Describe the bug**
RB maximum test value were set to db `MAX INT value (max int signed)` but an alert is raises with this value when activating/deactivating tests.

![image](https://github.com/aces/Loris/assets/25327259/603a0920-a803-46e7-9ff2-7243a38e78f7)

![image](https://github.com/aces/Loris/assets/25327259/0378feba-c9f7-463d-a1d9-d50758be7a48)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `battery_manager` with a user with at least edit permission.
2. Click on any `activate` or `deactivate` button in the table where `Maximum Age` values are > `99999`.
3. See error

**What did you expect to happen?**
The RB_test_battery file should be set to the max authorized value mentioned in the alert (i.e. `99999`).
The only record that has this value is [this one](https://github.com/aces/Loris/blob/991e3772e75897e00e50342df25824d9d4caedf6/raisinbread/RB_files/RB_test_battery.sql#L6). Other lines should be brought down to it **OR** the alert should be updated to match the db `MAX INT`.

**Browser Environment (please complete the following information):**
- OS: 6.6.10-1-MANJARO
- Browser: Firefox 121.0.1 (64-bit)

**Server Environment (if known):**
v26 test vm

**Comment by driusan** [comment]
@kongtiaowang since this is an RB data issue can you fix this too?

**Comment by ridz1208** [comment]
@driusan is this 99999 just some random number ? shouldnt it be derived from the amax age in the config or something ?

**Comment by driusan** [comment]
I believe it's an arbitrary number that was added with the assumption that the test battery won't be used on any candidates older than 273.96 years old.
