### ISSUE TITLE
[help] Help section extends past width of the page

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#9087]
**Describe the bug**
When you open the help section on a module (i.e. Battery manager) the UI is not ideal. The help section is long for this module is long and is displayed in a narrow box that extends very low below the filter and extends the width of the page making the user need to scroll sideways to read

![image](https://github.com/aces/Loris/assets/15268287/17c9cd07-b6f1-42c5-8476-b2051b7b14bc)

**Comment by shonibare** [comment]
PR - #9105
