### ISSUE TITLE
[Conflict Resolver]Module doesn't load properly, throws type error

### ISSUE THREAD

**Issue by KLaFleur** [aces/Loris#9095]
I began testing this last week and got about halfway through instructions before failing some of the tests. Now, when loading the module, I just get the error: 

```An error occured while loading the page.

TypeError: Cannot read properties of undefined (reading 'bmi_height_inches')
```

**Comment by driusan** [comment]
Where do you get that error? in the javascript console? In the Apache error log?

**Comment by ridz1208** [comment]
@KLaFleur try clearing your cache and trying again. I cant reproduce the error

**Comment by KLaFleur** [comment]
@driusan it appears in red right on the page 
<img width="1240" alt="Screen Shot 2024-02-27 at 11 04 53 AM" src="https://github.com/aces/Loris/assets/35120091/a0e5d4cc-ae81-4258-9f6f-a62bfd091059">

@ridz1208 I cleared my cache and got the same error again

**Comment by ridz1208** [comment]
@KLaFleur looks like the instruments got messed up. @kongtiaowang can you look into the instrument ?

**Comment by driusan** [comment]
what VM is this on? Testing or your sandbox? As Rida said I think this is related to the instrument not being setup on whichever VM it is.

**Comment by MaximeMulder** [comment]
I also have this bug on my dev VM, so it's not only Kevin.

**Comment by KLaFleur** [comment]
this was on the 26 testing vm!

**Comment by ridz1208** [comment]
@KLaFleur I'm not getting that error

![image](https://github.com/aces/Loris/assets/15268287/a58d20d2-def4-401f-b76a-a11206c61a31)

can you try to do some digging to see why you get it and not everyone? look at your inspector, where is it happening exactly? is it related to any permissions you have or dont have? after what step in the testing did it start failing exactly?

**Comment by KLaFleur** [comment]
@ridz1208 I also dont get that error on the admin account I'm realizing -- only on my user account. 

I'm getting a forbidden error at the console:
<img width="452" alt="Screen Shot 2024-02-29 at 10 14 09 AM" src="https://github.com/aces/Loris/assets/35120091/4a32b3f1-a7f5-4b05-8efb-6bd1d1096fb1">

further, I messed around with the permissions and had no luck (I also created a clean second testing account also with the same issues). Here are my permissions:
<img width="718" alt="Screen Shot 2024-02-29 at 10 17 01 AM" src="https://github.com/aces/Loris/assets/35120091/7ef3aeaa-ec03-4dde-8163-62a181c60a0b">


<img width="577" alt="Screen Shot 2024-02-29 at 10 17 11 AM" src="https://github.com/aces/Loris/assets/35120091/8d6f9e3d-f364-4d55-9576-aa825f6517a6">

**Comment by MaximeMulder** [comment]
I am actually not getting the same error message, inquiring on my side to see if it's related. My error is the following (on both resolved and unresolved):
```
TypeError: _this4.state.fieldsMeta[e.Instrument] is undefined
```

**Comment by KLaFleur** [comment]
I figured out my issue!  If I turn on the permission `Data Dictionary (Legacy): View Parameter Type Descriptions` my problem goes away -- is this a necessary permission for the conflict resolver? There is nothing about this in the testing instructions and it doesnt make a lot of sense to me @ridz1208 @driusan

**Comment by ridz1208** [comment]
@KLaFleur nice catch!! let me look into it

**Comment by ridz1208** [comment]
Action Item:
- block access to the module if user doesnt have Datadict permission
- update testplan and readme files

**Comment by MaximeMulder** [comment]
Okay, my error was not related, it was just that the `raisinbread/instruments` folder was not copied in `project/`. Thanks @ridz1208 !
