### ISSUE TITLE
[Config] Cannot delete an entry from a repeater

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#9096]
If a user create multiple entries form a repeater, those cannot be deleted despite the presence of a delete button:

<img width="939" alt="Screenshot 2024-02-27 at 10 50 10 AM" src="https://github.com/aces/Loris/assets/32041423/e5c3da69-1592-4b18-ad29-1db9204ae5b5">

Console output:
<img width="593" alt="Screenshot 2024-02-27 at 10 51 40 AM" src="https://github.com/aces/Loris/assets/32041423/96b1d6fa-1bb7-41fe-a3a2-faf74434f251">

**Comment by ridz1208** [comment]
seems to be related to https://github.com/aces/Loris/pull/7069
