### ISSUE TITLE
[login] Being logged as two different LORIS users does not seem to work properly

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#9100]
During V26 testing I had opened a tab on my Chrome browser where I was was logged as user `frank` and another one where I was logged as user `admin`. I observed the following:

1. I navigated to a menu on the `admin` tab (say user account).
2. Switched to the `frank` tab and navigated to menu `media`.
3. I am taken to the media module, but I now seem to be logged in as `admin` in my `frank` tab, as confirmed by the string `Admin account` that appears in the upper right corner of the LORIS front-end.

**Comment by driusan** [comment]
Were these incognito windows? How did you log in two times? If so, it sounds like it's more likely to be a bug in Chrome than LORIS.

Can you reproduce with Firefox?

**Comment by nicolasbrossard** [comment]
These were not incognito windows. Here's how to "log in" two times on the test VM:

1. Open a first tab in Chrome and access `https://test-dev-260.loris.ca/`. Log in as user A.
2. Open a second tab in Chrome and access `https://test-dev-260.loris.ca/`. Log in as user A.
3. Go to the first tab, logout, and log back in as user B.
4. Go to the second tab (it should still indicate that you are logged in as A, but you are not anymore) and access the media module. The page loads and you can see in the upper right corner that you are operating the front-end as user B.

The confusion stems from the fact that once user A logs out and you log back as B, the second tab does not reflect the fact that from now you have become B.

**Comment by driusan** [comment]
So you logged out as user A, logged in as user B, and it's acting as user B for future requests? That sounds like the expected behaviour?
