### ISSUE TITLE
[Data Query Tool (Alpha)] can't run the query

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#9127]
[Thu Mar 14 10:17:22.506762 2024] [php:notice] [pid 3325] [client 192.168.122.1:59834] [ERROR] Unhandled operator: notexists#0 /var/www/Loris/modules/dataquery/php/query.class.inc(686): LORIS\\dataquery\\Query->_candidateMatches()\n#1 /var/www/Loris/modules/dataquery/php/query.class.inc(547): LORIS\\dataquery\\Query->_candidateMatches()\n#2 /var/www/Loris/modules/dataquery/php/endpoints/queries/query/count.class.inc(62): LORIS\\dataquery\\Query->matchCandidates()\n#3 /var/www/Loris/modules/dataquery/php/endpoints/queries/query/count.class.inc(41): LORIS\\dataquery\\endpoints\\queries\\query\\Count->countResults()\n#4 /var/www/Loris/modules/dataquery/php/queries.class.inc(94): LORIS\\dataquery\\endpoints\\queries\\query\\Count->handle()\n#5 /var/www/Loris/src/Middleware/UserPageDecorationMiddleware.php(247): LORIS\\dataquery\\Queries->handle()\n#6 /var/www/Loris/src/Middleware/PageDecorationMiddleware.php(58): LORIS\\Middleware\\UserPageDecorationMiddleware->process()\n#7 /var/www/Loris/php/libraries/NDB_Page.class.inc(725): LORIS\\Middleware\\PageDecorationMiddleware->process()\n#8 /var/www/Loris/php/libraries/Module.class.inc(321): NDB_Page->process()\n#9 /var/www/Loris/src/Middleware/ResponseGenerator.php(50): Module->handle()\n#10 /var/www/Loris/src/Middleware/AuthMiddleware.php(63): LORIS\\Middleware\\ResponseGenerator->process()\n#11 /var/www/Loris/src/Router/ModuleRouter.php(74): LORIS\\Middleware\\AuthMiddleware->process()\n#12 /var/www/Loris/src/Middleware/ExceptionHandlingMiddleware.php(54): LORIS\\Router\\ModuleRouter->handle()\n#13 /var/www/Loris/src/Router/BaseRouter.php(132): LORIS\\Middleware\\ExceptionHandlingMiddleware->process()\n#14 /var/www/Loris/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle()\n#15 /var/www/Loris/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process()\n#16 /var/www/Loris/htdocs/index.php(73): LORIS\\Middleware\\ContentLength->process()\n#17 {main}, referer: https://test-dev-260.loris.ca/dataquery/
[Thu Mar 14 10:17:22.536943 2024] [php:notice] [pid 3330] [client 192.168.122.1:59836] [ERROR] Unhandled operator: notexists#0 /var/www/Loris/modules/dataquery/php/query.class.inc(686): LORIS\\dataquery\\Query->_candidateMatches()\n#1 /var/www/Loris/modules/dataquery/php/query.class.inc(547): LORIS\\dataquery\\Query->_candidateMatches()\n#2 /var/www/Loris/modules/dataquery/php/queryrun.class.inc(72): LORIS\\dataquery\\Query->matchCandidates()\n#3 /var/www/Loris/modules/dataquery/php/endpoints/queries/query/run.class.inc(61): LORIS\\dataquery\\QueryRun->insertCandidates()\n#4 /var/www/Loris/modules/dataquery/php/endpoints/queries/query/run.class.inc(41): LORIS\\dataquery\\endpoints\\queries\\query\\Run->runQuery()\n#5 /var/www/Loris/modules/dataquery/php/queries.class.inc(82): LORIS\\dataquery\\endpoints\\queries\\query\\Run->handle()\n#6 /var/www/Loris/src/Middleware/UserPageDecorationMiddleware.php(247): LORIS\\dataquery\\Queries->handle()\n#7 /var/www/Loris/src/Middleware/PageDecorationMiddleware.php(58): LORIS\\Middleware\\UserPageDecorationMiddleware->process()\n#8 /var/www/Loris/php/libraries/NDB_Page.class.inc(725): LORIS\\Middleware\\PageDecorationMiddleware->process()\n#9 /var/www/Loris/php/libraries/Module.class.inc(321): NDB_Page->process()\n#10 /var/www/Loris/src/Middleware/ResponseGenerator.php(50): Module->handle()\n#11 /var/www/Loris/src/Middleware/AuthMiddleware.php(63): LORIS\\Middleware\\ResponseGenerator->process()\n#12 /var/www/Loris/src/Router/ModuleRouter.php(74): LORIS\\Middleware\\AuthMiddleware->process()\n#13 /var/www/Loris/src/Middleware/ExceptionHandlingMiddleware.php(54): LORIS\\Router\\ModuleRouter->handle()\n#14 /var/www/Loris/src/Router/BaseRouter.php(132): LORIS\\Middleware\\ExceptionHandlingMiddleware->process()\n#15 /var/www/Loris/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle()\n#16 /var/www/Loris/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process()\n#17 /var/www/Loris/htdocs/index.php(73): LORIS\\Middleware\\ContentLength->process()\n#18 {main}, referer: https://test-dev-260.loris.ca/dataquery/

**Comment by driusan** [comment]
What was the query being run?

**Comment by kongtiaowang** [comment]
@driusan It only faild on the instrument section. I queried the BMI or Medical history instruments any admin or DOB is not today.

**Comment by kongtiaowang** [comment]
Problem solved.

**Comment by driusan** [comment]
This was not reproducible (even by @kongtiaowang on the same machine.) Might have been a problem with the instrument that was fixed on the test VM.
