### ISSUE TITLE
[login] Incorrect request account approvals count on dashboard

### ISSUE THREAD

**Issue by MaximeMulder** [aces/Loris#9130]
**Describe the bug**

The request account approvals count on the dashboard does not seem to take into account (pun intended) the project of the approving user. For instance, as a user with the `user_accounts` permission (own site), I see three pending accounts on the dashboard although they are not associated with my project and are therefore unavailable to me in the users table (this last part is expected, it is only the count that is wrong).

**Comment by ridz1208** [comment]
@CamilleBeau didnt you encounter something similar and it turned out to be due to the site/project access ?
