### ISSUE TITLE
[publication] Unable to download uploaded files

### ISSUE THREAD

**Issue by jeffersoncasimir** [aces/Loris#9133]
As stated in the TestPlan.md: `You should be able to view a static version of the project proposal and be able to download the uploaded files.`

I am unable to download the files currently associated with any project with uploaded files.

Examples:
https://test-dev-260.loris.ca/publication/view_project?id=2
https://test-dev-260.loris.ca/publication/view_project?id=4

**Comment by driusan** [comment]
Are these things you uploaded or things that were already there? It's possible the files aren't there on the test VM if it was just loaded from an RB dump.

**Comment by jeffersoncasimir** [comment]
I uploaded files and couldn't download them. I just double-checked now and it is still the case.
