### ISSUE TITLE
[statistics] issue in Behavioural Statistics

### ISSUE THREAD

**Issue by miladheshmati** [aces/Loris#9137]
**Describe the bug**
when clicking on "View Details" or "Click here for breakdown per participant" get 500 error

--

[View Details](https://test-dev-260.loris.ca/statistics/statistics_site/?CenterID=2&ProjectID=)

<img width="972" alt="Screenshot 2024-03-14 at 11 02 19 AM" src="https://github.com/aces/Loris/assets/51356424/c00adc63-84f0-45b0-864c-1c5bf208c836">

<img width="1326" alt="Screenshot 2024-03-14 at 11 02 32 AM" src="https://github.com/aces/Loris/assets/51356424/0eadcc77-5b9e-41b6-920b-ae1030a93006">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to statistics
2. go Behavioural Statistics
3. click on the reported fields

**What did you expect to happen?**

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by regisoc** [comment]
@kongtiaowang @miladheshmati Cannot reproduce this on test v26 VM nor mine.
The link in this issue points to
https://test-dev-260.loris.ca/statistics/statistics_site/?CenterID=2&ProjectID=
But this works. Do I miss something?

**Comment by regisoc** [comment]
The link with the 500 error page is
https://test-dev-260.loris.ca/statistics/statistics_site/?CenterID=2&ProjectID=1 though.
How do we access it?
When clicking on both "View Details" or "Click here for breakdown per participant" no 500 error is generated.

**Comment by regisoc** [comment]
Got it. 
When the dropdown is on "All projects", not error is generated, but there is a projectID missing in the URL for both links. 

![image](https://github.com/aces/Loris/assets/25327259/02953f64-735a-4018-a725-afb231bf8e22)

![image](https://github.com/aces/Loris/assets/25327259/5b2e75bc-de58-452d-96e2-ea4a29165553)

But selecting a project adds the projectID at the end of the URL.

![image](https://github.com/aces/Loris/assets/25327259/8af99a9d-ead4-4beb-9366-79fdbc54dc40)
