### ISSUE TITLE
[statistics] issue in checkboxes

### ISSUE THREAD

**Issue by miladheshmati** [aces/Loris#9140]
**Describe the bug**
The checkboxes seem to have alignment issues

<img width="821" alt="Screenshot 2024-03-14 at 11 11 01 AM" src="https://github.com/aces/Loris/assets/51356424/7e4d994c-6817-4456-a20a-d238aefd9beb">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to statistics
2. Click on Imaging Statistics

**Comment by ridz1208** [comment]
@miladheshmati what kind of issues?

**Comment by miladheshmati** [comment]
> @miladheshmati what kind of issues?

alignment issues, I updated the description
