### ISSUE TITLE
[new_profile] Min and max age do not seem to be taken into account

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#9147]
On the test VM, the min and max age for candidates are set to 10 and 100 y.o. respectively. I was able to create a candidate born on 01JAN1916 (~108 y.o.) and another born on 01JAN2018 (~6 y.o), which should not be allowed.

**Comment by ridz1208** [comment]
@nicolasbrossard can you sync up with @KLaFleur 

he opened https://github.com/aces/Loris/issues/9097 and then we established it was not an issue

**Comment by KLaFleur** [comment]
@nicholasbrossard are you able to create candidates with ages higher than
108 and less than 6? I forget the exact parameter, but there’s a number
that for “study year”( or something like that) which shifts the behavior of
the age check in a way that looks strange but is in fact desired behavior.

You should be able to find that if you go to the php code for the module.
If you can’t, or that doesn’t make sense, I’ll get in there and check it
out!

**Comment by ridz1208** [comment]
@KLaFleur thanks for the answer. I'm thinking we should update the test plan so this isnt confusing to others.

**Comment by KLaFleur** [comment]
Just updated with #9172 !

**Comment by driusan** [comment]
Was addressed by updating the test plan in #9172
