### ISSUE TITLE
[isntrument_builder] blank page when trying to add a score

### ISSUE THREAD

**Issue by regisoc** [aces/Loris#9152]
**Describe the bug**
At step `1.c. Add scored Field` in [module test plan](https://github.com/aces/Loris/blob/main/modules/instrument_builder/test/TestPlan.md), page breaks.

![image](https://github.com/aces/Loris/assets/25327259/db338e64-a98c-407e-aea8-63428f3f5b68)

Components are not detected in React (need import):
https://github.com/aces/Loris/blob/c0b193554fe8e8a44977ebf662561a68e3dfe573/modules/instrument_builder/jsx/react.questions.js#L60

**Comment by miladheshmati** [comment]
I am getting this error:

`[Thu Mar 28 12:40:25.323288 2024] [php:error] [pid 43698] [client 192.168.122.1:39712] PHP Fatal error:  Uncaught LorisNoSuchModuleException: No such module: electrophysiology_uploader in /var/www/loris/src/LorisInstance.php:147\nStack trace:\n#0 /var/www/loris/src/LorisInstance.php(79): LORIS\\LorisInstance->getModule()\n#1 /var/www/loris/src/LorisInstance.php(112): LORIS\\LorisInstance->getActiveModules()\n#2 /var/www/loris/src/Router/BaseRouter.php(108): LORIS\\LorisInstance->hasModule()\n#3 /var/www/loris/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle()\n#4 /var/www/loris/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process()\n#5 /var/www/loris/htdocs/index.php(55): LORIS\\Middleware\\ContentLength->process()\n#6 {main}\n  thrown in /var/www/loris/src/LorisInstance.php on line 147, referer: https://mheshmati-dev.loris.ca/instrument_list/?candID=417603&sessionID=11100
`
