### ISSUE TITLE
[Test Vm 26] EEG Browser major testing blockers, prob minor issues

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#9160]
These might just be Test VM issue -- @jeffersoncasimir  can you point @kongtiaowang to the patch that needs to be sourced maybe? 
Can't test the rest of the module otherwise. 

- [ ] Signal plot isn't plotting on the Test VM 
https://test-dev-260.loris.ca/electrophysiology_browser/sessions/167?outputType=raw
<img width="70%" alt="Screen Shot 2024-03-22 at 5 28 00 PM" src="https://github.com/aces/Loris/assets/827619/66a8023b-39d4-4cc5-b508-929cd8816ede">

- [ ] no HED/score schemas available -- can't use Dataset Tag Manager 
<img width="60%" alt="Screen Shot 2024-03-22 at 5 34 32 PM" src="https://github.com/aces/Loris/assets/827619/5bd2485f-67e8-4038-8b32-f506be374372">

- [ ] broken HED logo image in the Dataset Tag Manager modal top-left
 (because it's on images.loris.ca? @jeffersoncasimir ) 
<img width="70%" alt="Screen Shot 2024-03-22 at 5 30 59 PM" src="https://github.com/aces/Loris/assets/827619/d11b5b1f-ac4f-4b56-86b4-e3f05993367f">

**Comment by jeffersoncasimir** [comment]
@christinerogers All 3 issues have now been addressed

**Comment by driusan** [comment]
@jeffersoncasimir can this be closed then? Was it related to the VM or does it need code changes / PRs?

**Comment by christinerogers** [comment]
Partly resolved by #9161 
@jeffersoncasimir does #9159 need to be merged for this to be resolved in the release? (even tho it's fixed on the VM for now)

**Comment by jeffersoncasimir** [comment]
@driusan Yes this can be closed.

@christinerogers Yes it needs to be merged. It's a configuration-dependent issue that happens to affect the test VM.

**Comment by christinerogers** [comment]
> @driusan Yes this can be closed.
> 
> @christinerogers Yes it needs to be merged. It's a configuration-dependent issue that happens to affect the test VM.

great, please make sure 9159 is tagged `Critical to release` then if it's needed for the module to not break.
