### ISSUE TITLE
[media] Permission names need revising

### ISSUE THREAD

**Issue by jeffersoncasimir** [aces/Loris#9162]
The `media` module permissions are the following:

- `Media: Edit/Upload/Delete Candidate Media Files`
- `Media: View/Download Candidate Media Files`

Users with `Media: View/Download Candidate Media Files` are able to view files but do not have the option to download them; even their own uploads.

Only users with the `Media: Edit/Upload/Delete Candidate Media Files` can download. 
However, I do not see a `Delete` feature on the v26 VM. There is a `Hide File` feature which can be listed instead.

The current names are not accurately reflecting the permission scopes.

**Comment by racostas** [comment]
Some comments:

1. The issue of the user been able to see the "file name" and not to download it seems to be solved in 25 by PR.
https://github.com/aces/Loris/pull/8671
Let's try to merge it in the 26 code-base. 

2. I don't seen we can really "Delete" file. So the name of this permission needs to change to Edit/Upload/HIde.

**Comment by racostas** [comment]
Wil take care !

**Comment by driusan** [comment]
I tried to merge 25 into 26 and the diff did not include that PR.

It's possible that it was eatten by a previously badly resolved merge. can you just re-send the change to main?
