### ISSUE TITLE
EEG Browser : HED cosmetics to fix for release (important but minor)

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#9164]
Module is working pretty well there are things that look broken / buggy (even if they're not technically) and should be smoothed over for the Release.  (@jeffersoncasimir then for EEGNet too). 
This is keeping in mind most LORIS datasets won't have HED tags on them. 

- [x] spacing looks funny between `HED ... Dataset `when there's no pre-existing tags on an event  - see screenshot 1 
- [ ] #9165
- [x] ideally `reset` could be grayed out if you can't click it (like submit) 

in **Dataset Tag Manager**

- [x] When there are no `EventValue`s in the whole dataset, don't display it in the Dataset Tag Manager.  User can't do anything here, it looks like a bug.   -- see screenshot 2. 

- [x] Change `Enter Description (coming soon)` to `n/a` -- because it's wonky for a major release to say "coming soon" (like 2026 etc...) 

Otherwise: 

- [ ] HED tag image is still broken on Testing from #9160 but i'm not (yet) re-opening the ticket. 
@kongtiaowang maybe #9161 just needs to be pulled / sourced on the Test VM? 

#### screenshot 1 
<img width="60%" alt="Screen Shot 2024-03-25 at 4 47 05 PM" src="https://github.com/aces/Loris/assets/827619/11285b11-4222-46e4-899e-674f4adceb0c">

#### screenshot 2 
<img width="60%" alt="Screen Shot 2024-03-25 at 4 54 42 PM" src="https://github.com/aces/Loris/assets/827619/db09f3b8-187d-496c-ba3f-909528a0db1e">

#### screenshot 3
<img width="60%" alt="Screen Shot 2024-03-25 at 4 56 46 PM" src="https://github.com/aces/Loris/assets/827619/4b642b95-5121-45df-be31-155218a023c0">

**Comment by jeffersoncasimir** [comment]
All items have been addressed by #9166.

An issue was opened for the remaining actionable, as it is a significant feature.

**Comment by christinerogers** [comment]
Adding one issue that is a just a typo so I'll try to `suggest` it in #9166 : 
literally the user needs to select a column name AND value to see/add HED tags - the message in italics needs a tweak 
see screenshot -- they have selected column name as instructed and can't add a hed tag 
<img width="1259" alt="Screen Shot 2024-03-26 at 12 12 00 PM" src="https://github.com/aces/Loris/assets/827619/4f113d62-15c3-4cb3-888d-d6e41925046c">

**Comment by christinerogers** [comment]
confirming these are resolved in round 2 testing. 

Note that on many datasets the signal viewer plot isn't loading, alerted jefferson and Shen 
https://test-dev-260.loris.ca/electrophysiology_browser/sessions/2161?outputType=raw
