### ISSUE TITLE
EEG Signal display broken on TEst VM 

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#9185]
https://test-dev-260.loris.ca/electrophysiology_browser/sessions/2161?outputType=raw

@jeffersoncasimir - can you please assign this to whoever is following up? thanks.      

 suspect this is a Test VM setup issue but **the instructions should likely be documented for the release if it will break old data displays this easily.**      

     confirming these are resolved in round 2 testing. 

Note that on many datasets the signal viewer plot isn't loading, alerted jefferson and Shen 
https://test-dev-260.loris.ca/electrophysiology_browser/sessions/2161?outputType=raw

_Originally posted by @christinerogers in https://github.com/aces/Loris/issues/9164#issuecomment-2025685958_

**Comment by christinerogers** [comment]
marked this module as `bug that needs to be fixed` until this is resolved / clarified

**Comment by christinerogers** [comment]
This is still an issue for the release / on testing

**Comment by christinerogers** [comment]
@jeffersoncasimir can you please confirm the status here 
e.g. -- that this is a deliberate break, to show what happens to data when chunking isn't run ? thanks

**Comment by jeffersoncasimir** [comment]
After investigating, it appears the last 4 lines were not meant to be added to RB:  https://github.com/aces/Loris/blob/main/raisinbread/RB_files/RB_physiological_file.sql

The files do not appear to belong to the session they were assigned to. From our discussion in the Testing Blitz meeting on 11/04, I believe the best course of action is deleting the last 4 lines.
