### ISSUE TITLE
[cbig][instruments] Instrument resetting configuration

### ISSUE THREAD

**Issue by regisoc** [aces/Loris#9229]
**Describe the bug**

Related to point 6. in instruments module test plan.
In configuration, the `instrument resetting`  config has no value (expected Y/N).

![image](https://github.com/aces/Loris/assets/25327259/c9cb6951-8c3f-406a-b360-380d2c3c2cea)

Minor one because the `delete instrument data` button does not show up in the UI.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to configuration > Study tab > instrument resetting
2. See error

**What did you expect to happen?**
Have the `No` config button selected by default.

**Comment by ridz1208** [comment]
fixed on prod
