### ISSUE TITLE
{CBIGtest} [ConflictResolver] error occured while loading page

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#9230]
Placeholder to re-test this issue after instrument "save "troubleshooting is complete 
cc @ridz1208 

Conflict resolver  - testing on clinical_data_als for TOSI0000001 --

one instrument sent to Admin:Partial, one Admin:All -- when they seemed to "save", the conflict module displays red error message
`An error occured while loading the page.
TypeError: Cannot read properties of undefined (reading 'i_clinical_data_als_diagnosis')`

on the CBig Test vm, for the 26 release.

**Comment by ridz1208** [comment]
This is a confirmed issue It seems the Conflict resolver is confusing instrument name with instrument table. Not sure how it works with JSON data instruments with no tables...

**Comment by christinerogers** [comment]
Sounds like this should be re-tested on Loris core / Test VM, especially with json data instruments?  
cc @driusan

**Comment by driusan** [comment]
I think this is replaced by the linked issue above (#9242)
