### ISSUE TITLE
{CBIGtest} [candidate_parameters] Date of Birth Tab not showing.

### ISSUE THREAD

**Issue by racostas** [aces/Loris#9233]
**Describe the bug**
This testing was done in the CBIGtest release candidate. 
The `Date of Birth` Tab not showing for the candidate parameters modules.
This module have overrides so maybe it's part of it (intentional)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Been user `testadmin`
2. Go to MainManu->Candidate->Access Profile.
3. Choose one subject and click on it. Then the `Candidate info `button.  
4. See that there is not `Date of Birth Tab`
![image](https://github.com/aces/Loris/assets/37309344/0ec062c2-b079-4e26-8dc2-6f226ed2d86e)

**What did you expect to happen?**
The tab to be there.

**Comment by ridz1208** [comment]
I confirm DOB is not editable on CBIG
