### ISSUE TITLE
[Behavioural Feedback] Blank Page Appear on Closing an Opened Behavioural Thread

### ISSUE THREAD

**Issue by sruthymathew123** [aces/Loris#9243]
**Describe the bug**
Blank Frozen Page appear on Closing an Opened Behavioural Thread
**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to instrument list of any candidate visit.
2. Click on Behavioral feedback
3. Try to create a new thread or select and Open status thread
4. Update the open status to close and you will see a blank page; (You need to refresh the page to get the updated status; but rendering is not happening without refreshing the page)

![Screen Shot 2024-05-09 at 10 42 51 AM](https://github.com/aces/Loris/assets/23702452/56190d74-eb2f-428c-8f08-8976b1a6c857)

**Additional context**
tested on https://cbigr-test.loris.ca/ as part of release testing

**Comment by ridz1208** [comment]
@sruthymathew123 can you and @racostas see why/when this issue happens ?

**Comment by sruthymathew123** [comment]
Tried again and couldn't recreate the issue anymore; so closing this for now. Thanks @racostas  for checking this.
