### ISSUE TITLE
[imaging_uploader] Form freezes when uploading a big file

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#9247]
I tried uploading a file that exceeds the max upload size set on cbigr-test.loris.ca (2G). The upload got to 1% but then the form froze...I saw this in the JS console:
```
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
```
This bug occurs both for large candidate scans and large phantom scans.

**Comment by driusan** [comment]
I think in other modules this is solved by sending the max size from the php.ini settings to the frontend and verifying that the scan can be handled in the current php settings before sending the request.

**Comment by driusan** [comment]
When looking for an example I found that this module is one thats already supposed to do that:

https://github.com/aces/Loris/blob/main/modules/imaging_uploader/jsx/UploadForm.js#L357-L360

Might be server setup related.

**Comment by nicolasbrossard** [comment]
Although it takes a while, I get an error message saying that the file is too big as of 2024SEP18. Closing this issue.
