### ISSUE TITLE
[ConflictResolver] add support for JSON Instruments [ known issue ]

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#9248]
for the roadmap: 

Update the conflict resolver to show conflicts on JSON instruments. 

per C-Big testing for release 26, discussed may 9 with @ridz1208 and Dave

**Comment by driusan** [comment]
I don't see anywhere in the code that this would break. 

the conflict resolver looks uses `NDB_BVL_Instrument::factory` with the commentID and then calls  `_saveValues()` to save the new entry:
https://github.com/aces/Loris/blob/main/modules/conflict_resolver/php/endpoints/unresolved.class.inc#L260-L273

The conflict detector uses the factory and calls diff:
https://github.com/aces/Loris/blob/main/php/libraries/ConflictDetector.class.inc#L78

and diff uses getInstanceData which is handles JSON data correctly:
https://github.com/aces/Loris/blob/main/php/libraries/NDB_BVL_Instrument.class.inc#L2064

The only possible problem is this line:
https://github.com/aces/Loris/blob/main/php/libraries/NDB_BVL_Instrument.class.inc#L2080

which depends on how the person coded the instrument. If they use jsonData and set table=testname in their linst file or php instrument it should work transparently as far as I can tell.

**Comment by driusan** [comment]
That is the same line I referenced above.

**Comment by driusan** [comment]
@CamilleBeau I'm assigning this to you since you self-assigned #9242 and it should be the same fix. Just make sure your PR notes both as resolved.
