### ISSUE TITLE
[issue Tracker] Assignee field not required when adding an issue

### ISSUE THREAD

**Issue by KLaFleur** [aces/Loris#9253]
**Describe the bug**
 Assignee field not required when adding an issue, though the test plan specifies that it should be. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to issue tracker module
2. Click on new issue
3. Scroll down to Assignee field. There is no asterisk, and the module allows you to submit without including an assignee. 

**What did you expect to happen?**

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser **Chrome**

**Comment by driusan** [comment]
I think that test plan is wrong. Why would the assignee be required to create a new issue?

**Comment by KLaFleur** [comment]
I had the same thought - should I just make a PR update the test plan to reflect that?

**Comment by KLaFleur** [comment]
here it is!
https://github.com/aces/Loris/pull/9259
