### ISSUE TITLE
[Issue Tracker] site doesn't set to null when creating an issue with 'all sites' and no PSCID

### ISSUE THREAD

**Issue by KLaFleur** [aces/Loris#9254]
**Describe the bug**
The issue tracker test plan states:
 'Do not provide a PSCID value and set site to All Sites. This should set Site to NULL after success'
--> I found that this wasn't the case, and the issue populated in the list with every site listed. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to issue tracker
2. Click on new issue
3. add a new issue **without setting a PSCID** and set site to 'All Sites'
4. See error (the site attribute should show as null, not a list of every site)

**What did you expect to happen?**

**Browser Environment (please complete the following information):**
Chrome

**Comment by driusan** [comment]
Is the value in the backend null?

**Comment by jeffersoncasimir** [comment]
The value in the `issues` table is `NULL`.

The Issue Tracker table displays all sites.

I believe this is the expected behaviour, not an issue, and can be closed.

**Comment by driusan** [comment]
maybe the test plan should be updated to clarify?
