### ISSUE TITLE
[media] Import bug fixes - users can't download,  instrument auto-select

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#9272]
Ideally this is a quick patch on aces/LORIS code to apply the [CCNA solution (CCNA#7118)](https://github.com/aces/CCNA/pull/7118) for a few Media module bugs 

Note: Some of this might be already resolved by  #9162

per [Camille's notes](https://github.com/aces/CCNA/pull/7118) this is to: 
- [x]   let users with the view / download media files permission actually download files
- [x] fix the upload file page so that instruments are not autoselected when only one instrument exists for a visit.

Also to do as part of this issue: 
- [ ] update test plan if needed
- [ ] update Module readme if needed 

cc @racostas @laemtl 
Adding this to the backup queue of `GSOC` issues, could be a nice medium starter task for a rainy day

**Comment by ridz1208** [comment]
@CamilleBeau assigning to you just to keep track what's in @racostas 's PR (#9162) what's not there and maybe what could be assigned to GSOC
