### ISSUE TITLE
[Data Dictionary] Data Dictionary page is empty when accessed

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#9276]
When accessing the Data Dictionary, the page appears empty (see screenshot below with reported error):

<img width="1380" alt="Screenshot 2024-05-23 at 10 31 24 AM" src="https://github.com/aces/Loris/assets/54332302/6f40d3c2-c9f6-4f9a-b60b-1ba46087a7ff">

**Comment by driusan** [comment]
The URL is cut off. Is this `/datadict` or `/dictionary` and on what server?

**Comment by SantiagoTG** [comment]
https://cbigr-test.loris.ca/dictionary

**Comment by driusan** [comment]
CBIG had an override for the candidate_parameter module which did not incorporate #9227. This bug is already fixed in LORIS.
