### ISSUE TITLE
[imaging_browser] Error 500 caused by PDO error

### ISSUE THREAD

**Issue by maximemulder** [aces/Loris#9349]
**Describe the bug**

While testing #9304 , I got a very strange PDO error (see below) on a query that did not seem to be touched by the PR. I suspect this bug was introduced by #9334 .

```
> SQLSTATE[HY000]: General error: 2014 Cannot execute queries while there are pending result sets. Consider unsetting the previous PDOStatement or calling PDOStatement::closeCursor()
```

**To Reproduce**

Go to the following page on your dev VM and get an error.
https://your-vm-dev.loris.ca/imaging_browser/viewSession/?sessionID=2145&backURL=/imaging_browser/

To print the PDO error, you can copy-paste this code in `modules/imaging_browser/php/viewsession.class.inc` line 397.

```php
        try {
            return $this->_DB->pselectOneInt($query, ['fileID' => $fileID]);
        } catch (\Exception $e) {
            echo $e->getMessage();
            die();
        }
```

**Comment by driusan** [comment]
I'm not able to reproduce this error. Loading sessions on RB works for me.

One thing you can try is calling closeCursor as suggested in pselectRow (which is where pselectOneInt indirectly creates the query) before returning the result in the Database class.
