### ISSUE TITLE
[mri_violations] Broken query results serialization

### ISSUE THREAD

**Issue by maximemulder** [aces/Loris#9350]
# Description of the bug

Another bug found while testing #9304 (closed the other one for now because I cannot reproduce it anymore as well, we'll see if it happens a second time in the future). This one seems clearer. `pselect` used to return the results directly (I think ?). But now it returns a query. As such the following API in `mri_violations` that immediatly serialized the results does not work anymore.

# To Reproduce

Go to the MRI violations module, and click on "Could not identify scan type"
https://your-vm-dev.loris.ca/mri_violations

An error should appear, the reason for this error is that the `protocols` field of this (example) HTTP call is unexpectedly empty. 
https://your-dev-vm.loris.ca/mri_violations/?format=json&violationtype=protocolviolation&seriesUID=1.3.12.2.1107.5.2.32.35008.2009052710345172469142735.0.0.0

The reason this field is empty is that the LORIS query is wrongly serialized here:
https://github.com/aces/Loris/blob/0413aaf275212a8fb3a69efc8605f67dca9e371d/modules/mri_violations/php/mri_violations.class.inc#L109

**Comment by driusan** [comment]
Can you wrap that in iterator_to_array and send a PR? (Assuming it fixes it..)
