### ISSUE TITLE
LORIS v26.0.0 - CouchDB_Import_Demographics.php error

### ISSUE THREAD

**Issue by Johan-Peralta** [aces/Loris#9507]
### Discussed in https://github.com/aces/Loris/discussions/9499

<div type='discussions-op-text'>

<sup>Originally posted by **Johan-Peralta** December  3, 2024</sup>
Hi, I am getting the following error when executing the CouchDB_Import_Demographics.php script on LORIS v26.0.0:

```
/var/www/loris/tools$ php CouchDB_Import_Demographics.php
Updating Config:BaseConfig: unchanged contentsDemographics_Session_HBN0000_VIS1: new
Demographics_Session_DCC0000_VIS1: new
PHP Fatal error:  Uncaught TypeError: Project::getProjectFromID(): Argument #1 ($projectID) must be of type ProjectID, int given, called in /var/www/loris/tools/CouchDB_Import_Demographics.php on line 380 and defined in /var/www/loris/php/libraries/Project.class.inc:105
Stack trace:
#0 /var/www/loris/tools/CouchDB_Import_Demographics.php(380): Project::getProjectFromID()
#1 /var/www/loris/tools/CouchDB_Import_Demographics.php(496): CouchDBDemographicsImporter->_updateDataDict()
#2 /var/www/loris/tools/CouchDB_Import_Demographics.php(512): CouchDBDemographicsImporter->run()
#3 {main}
  thrown in /var/www/loris/php/libraries/Project.class.inc on line 105

```
The projects seem to be properly setup in the MySQL side.
Any ideas on what could be causing the error?

Any help will be greatly appreciated, Johan</div>

**Comment by driusan** [comment]
I don't have a couchdb instance to test this on as v26 is moving towards the new SQL based dataquery tool, but #9508 should in theory fix the error that you posted. Can you test it and let me know?

**Comment by driusan** [comment]
My mistake, the singleton method was added after the 26 release.

I've updated the PR to use "new" instead of singleton. Can you try it again? As I said, I don't have a CouchDB instance to test it on.

**Comment by driusan** [comment]
Not sure why this wasn't auto-closed, the PR that fixes it was merged.

**Comment by Johan-Peralta** [comment]
Dave, thanks for your help resolving the script failure.

Best regards, Johan
