### ISSUE TITLE
Excel Dump call-time pass-by-reference errors

### ISSUE THREAD

**Issue by Jkat** [aces/Loris#956]
excelDump.php is having call-time pass-by-reference errors. This needs to be addressed as this script does not work out of the box for >= PHP 5.4

**Comment by driusan** [comment]
Is this resolved by #1449 ?

**Comment by Jkat** [comment]
Quite possible. Will be a bit hard for me to test this issue properly because I don't have an instance ready with >=PHP 5.4 + data

**Comment by Jkat** [comment]
Has been resolved since
